### ISSUE TITLE
Saving a map where the game has no write access causes an ArgumentNullException

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#11261] opened 2016-05-11 20:10 UTC
Two issues I found when starting a new map:
1. In the dialogue box that let's you put the map name, author, file name, etc. the tab button doesn't allow you to switch between fields.
2. If when creating a new map you use a filename that is already in use, instead of bringing up some sort of box asking if you'd like to overwrite the existing map the program just exits, no crash dialogue or anything even.

EDIT: Just reproduced 2, created a crash dialogue this time. Here's the exception.log:

> Red Alert Mod at Version release-20160508
> on map 1b896bb92014607fc1d9c3c1feff5f2a22f902ea (Desert Shellmap by Scott_NZ).
> Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
> Runtime Version: .NET CLR 4.0.30319.34209
> Exception of type `System.ArgumentNullException`: Value cannot be null.
> Parameter name: key
>    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
>    at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
>    at OpenRA.Primitives.Cache`2.get_Item(T key)
>    at OpenRA.MapCache.get_Item(String key)
>    at OpenRA.Mods.Common.Widgets.Logic.SaveMapLogic.<SaveMapLogic>c__AnonStorey0.<>m__1()
>    at OpenRA.Mods.Common.Widgets.ButtonWidget.<ButtonWidget>m__A(MouseInput _)
>    at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
>    at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
>    at OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
>    at OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey2.<>m__0()
>    at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
>    at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
>    at OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler)
>    at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler)
>    at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
>    at OpenRA.Game.RenderTick()
>    at OpenRA.Game.Loop()
>    at OpenRA.Game.Run()
>    at OpenRA.Program.Run(String[] args)
>    at OpenRA.Program.Main(String[] args)

**Comment by obrakmann** [comment] 2016-05-11 20:30
Actually, the tab button in our UI doesn't work anywhere as you'd expect it from Windows. I'm not sure if we should fix it just for the save dialog if we can't do it consistently across the whole UI.

But the crash needs to be fixed indeed.

**Comment by Mailaender** [comment] 2016-05-15 13:45
> If when creating a new map you use a filename that is already in use, instead of bringing up some sort of box asking if you'd like to overwrite the existing map the program just exits, no crash dialogue or anything even.

Can't reproduce the crash. For me the map just gets overwritten.

**Comment by GraionDilach** [comment] 2016-05-15 16:33
Since it's the shellmap the exception assumes, this might be a writing-into-a-folder-where-only-admin-access-can issue.

**Comment by PunkPun** [comment] 2022-07-06 21:58
Is this still an issue? I saw writability checks in map saving code

**Comment by Mailaender** [comment] 2022-07-07 18:54
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/9430

**Closed by Mailaender** 2022-07-07 18:54 UTC
Labels: Crash, Map Editor
