### ISSUE TITLE
Tiberian Dawn: You can build defence towers on bridges

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14258] opened 2017-10-24 15:24 UTC
Hello,

I'm not sure this is intended, but you can build defence towers on bridges (The AI did it so I tried it too):

https://imgur.com/a/bGTvH

Bonus bug (if that behavior is intended):
1. Place the tower, where I wanted to do it in the screenshot
2. Destroy the bridge (by force-shooting at the side where the tower is not placed)
3. The defence tower survives that and still works while it hovers in the air
4. Sell the tower
5. You aren't able to build a new tower at the same place

**Comment by FrameLimiter** [comment] 2017-10-24 16:24
Related: #14132
(Unlike in RA, TD has no defined "bridge" terrain type for mobile actors.)

**Comment by KOYK** [comment] 2017-11-06 15:45
this was in the original TD by the way

**Comment by pchote** [comment] 2017-11-06 15:47
I don't really have a problem with placing buildings on bridges, but of course they need to be destroyed along with the bridge (possible duplicate of #9416?)

**Comment by Smittytron** [comment] 2017-11-23 17:04
For the sake of consistency I think adding Bridge to TerrainTypes is the way to go here. Also, towers on bridges just look weird.

**Closed** 2018-03-04 20:29 UTC
Labels: Bug, Tiberian Dawn
