### ISSUE TITLE
Crash after removing earphones

### ISSUE THREAD

**Issue by sprice** [OpenRA/OpenRA#10879] opened 2016-03-05 01:04 UTC
OpenRA crashed immediately after I removed the earphones from my Macbook's earphone jack.

OSX 10.11.3

exception.log
```
Red Alert Mod at Version release-20150919
on map a55c86fa5b11a125a9b0f800aafc76c30bc64893 (Alaska Anarchy Redux by Buddha).
Operating System: OSX (Unix 15.0.0.0)
Runtime Version: Mono 4.0.1 ((detached/ed1d3ec) CLR 4.0.30319.17020
Exception of type `System.InvalidOperationException`: Out of sync in frame 670.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (Int32 frame) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager+<TickImmediate>c__AnonStorey0.<>m__0 (Int32 clientId, System.Byte[] packet) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.ReplayRecorderConnection+<Receive>c__AnonStorey0.<>m__0 (Int32 client, System.Byte[] data) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.EchoConnection.Receive (System.Action`2 packetFn) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.ReplayRecorderConnection.Receive (System.Action`2 packetFn) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by pchote** [comment] 2016-03-05 10:21
I've seen this happen before, but I'm not sure how to reproduce it.  It is a native crash in OpenAL / the sound driver, so that exception log is going to be unrelated.

**Comment by pchote** [comment] 2016-04-17 17:17
Can you please try the new playtest (20160403, or later) and let us know if this still happens?  The OpenAL integration has changed, and that might have fixed the problem.

**Comment by Mailaender** [comment] 2016-04-25 05:21
I assume this is a duplicate of https://github.com/OpenRA/OpenRA/issues/9788.

**Closed by Mailaender** 2016-04-25 05:21 UTC
Labels: Crash, OS: MacOS X
