### ISSUE TITLE
Selection-Box doesnt work on enemy units

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#8802] opened 2015-07-26 18:02 UTC
selection box doesnt show up anymore when doing a left-click/rubberband-selection on enemy units 
something is broken here ... (reproducible only with fog/shroud "ON") 

http://logs.openra.net/?year=2015&month=06&day=29#16:13:38

**Comment by Mailaender** [comment] 2015-07-26 19:06
Duplicate of https://github.com/OpenRA/OpenRA/issues/8804 I suppose.

**Comment by MicroJOo** [comment] 2015-07-26 19:29
![release bleed](https://cloud.githubusercontent.com/assets/9139965/8895497/7114b14e-33dd-11e5-9328-22070f2b4a45.png)

**Closed** 2015-07-27 17:38 UTC
