### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by St3x** [OpenRA/OpenRA#16077] opened 2019-01-18 18:07 UTC
Hi !

### Issue Summary

I got a `System.ArgumentNullException` while watching a 100 % AI game.

#### System Information
- Operating System : Windows 10
- .Net Version :.Net 4.7.2
- OpenRA Version : playtest-20190106
- Mod : Red Alert

#### Additional Information
- Logs : https://ufile.io/z6cc9
- Replay : https://ufile.io/v61tn
- Map : https://resource.openra.net/maps/12213/

**Comment by St3x** [comment] 2019-01-18 18:33
I retried, and it happened again.

- New logs : https://ufile.io/ngv10
- New replay : https://ufile.io/7kor4

**Comment by pchote** [comment] 2019-01-18 18:49
Thanks for the report! This is a duplicate of #16019, which will be fixed in the next playtest.

**Closed by pchote** 2019-01-18 18:49 UTC

**Comment by St3x** [comment] 2019-01-18 18:54
Oh that's nice ! Thank you for the info and sorry for the duplicate.
