### ISSUE TITLE
playtest: "Invalid <Option>" when loading this map in multiplayer

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14060] opened 2017-09-21 20:57 UTC
Hey,
made[ this map](http://resource.openra.net/maps/22831/) which works fine in playtest20170902 skirmish. No playtest Lint errors. (some random warnings)
In multiplayer however I can't choose techlevel or AI, even though that is perfectly possible in skirmish mode. 
EDIT: I can choose low or medium tech, but no idea why. I reconfigured all techlevels after all.

21:15:20 - pchote: interesting
21:15:27 - pchote: seems to be related to the resource center fetching
...
21:33:58 - pchote: afaik none of the code related to this bug has changed recently
...
21:34:57 - pchote: the key point is that this only happens when a dedicated server doesn't have the map installed

**Comment by CH4Code** [comment] 2017-09-28 11:59
Not sure if this is a bug anymore, I found the cause:
I modified the Player: trait in two different files. Combining those two files removed the error.

However, I think there should be an error for this case. Alternatively (even better) the traits files would be overwritten in the order they are listed in the map.yaml.
i.e. "Rules: a.yaml, b.yaml, c.yaml"   (c overwrites b overwrites a)

**Comment by pchote** [comment] 2017-09-28 12:32
> Alternatively (even better) the traits files would be overwritten in the order they are listed in the map.yaml.

This is how it already works.

**Comment by CH4Code** [comment] 2017-09-28 12:50
Then it ain't workin' good enough!   ;)

**Comment by pchote** [comment] 2017-09-28 13:11
It is more likely that the error was from what was merged rather than the merging itself.  If that was broken then we would see many other things break.

Can you please post the yaml snippets from the two files that fail and also the manually merged yaml snippet that works?

**Comment by CH4Code** [comment] 2017-09-28 14:00
[Working map: ](http://resource.openra.net/maps/22979)
```
#file ab.yaml
Player:
	ProvidesTechPrerequisite@new:
		Name: New Techlevel
		Prerequisites: techlevel.new
		Id: newlevel
	HackyAI@Omnius:
		Name: Bug
```
[Failing map:]( http://resource.openra.net/maps/22977) (techlevel selection fails with "Invalid Option", also name "Bug" doesnt not appear for AI omnius)
```
#file a.yaml
Player:
	HackyAI@Omnius:
		Name: Bug
```
```
#file b.yaml
Player:
	ProvidesTechPrerequisite@new:
		Name: New Techlevel
		Prerequisites: techlevel.new
		Id: newlevel
```

**Comment by pchote** [comment] 2017-09-30 00:07
I haven't tested the theory yet, but it looks pretty obvious that the problem is related to the way rules are parsed from remote maps.

Multiple rule files are concatenated together for the resource center api, which in this case causes there to be two `Player:` blocks in the rule overrides.  This is somehow breaking the yaml merging.  When the map is available on the server then can parse and merge the files directly, so the bug doesn't occur.

I put 50/50 odds on this either being a straightforward fix or a total nightmare.  Adding to the milestone for now in the hopes that it will be the former.

**Comment by pchote** [comment] 2017-09-30 11:11
The fix is straightforward, but too low level for me to be happy with putting it in to the playtest.  Moving to the Next + 1 milestone.

This issue also applies to normal yaml file, so a simpler repro case is to add the following to bottom of one of the `misc.yaml` rule files:
```
mpspawn:
	EditorOnlyTooltip:
		Name: Crash
```

**Closed** 2017-10-06 15:54 UTC
Labels: Bug
