### ISSUE TITLE
[playtest-20190825] Possible selectbox overlap issue

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17048] opened 2019-09-05 19:10 UTC
Reported on #bug-reporting

goat:

> this is a rather weird one. it happened to me in the dark tournament as well but i wasnt sure if it was a bug or I just messed up, but seeing as it has now happened again I'm leaning towards it being a bug.
> but this happens at approx 16:30 in my main base; I sell the ref and for some reason it automatically sells the airfield next to it as well.
> oh and I am not sure this is a coincidence, but I do believe it was the exact same scenario in the dark tournament: I sold a building next to an airfield and somehow the airfield was also sold.
> not sure if it is related to the airfield or what it is. i can find the dark tournament replay if needed as well. i havent been able to reproduce this in singleplayer though.
> 
> oh as for the double sell the most logical explanation would simply be me messing up and moving my mouse over the airfield instantly and clicking, but seeing as it has now happened twice on the playtest and never before and i really dont see myself ever clicking like that, i find it a bit weird

https://cdn.discordapp.com/attachments/279290580201373696/618580877978632192/goatblackenedpt.orarep

**Comment by pchote** [comment] 2019-09-07 19:49
I'm fairly certain that this really was a false alarm caused by a miss click, so closing until further reports come to light.

1. The two buildings are quite far separated and their selection regions (the red squares) are completely disjoint.
   ![Screenshot 2019-09-07 at 20 46 42](https://user-images.githubusercontent.com/167819/64479552-aee1e580-d1b0-11e9-974b-cfbb50e06241.png)

2. The refinery was sold first in tick 24915 and the airfield in tick 24921. If this was a bug I would expect both to happen in the same tick.

**Closed by pchote** 2019-09-07 19:49 UTC

**Comment by BlackenedRA** [comment] 2019-09-08 16:53
Well I'm not sure if this qualifies as the same issue but I had something I thought was the same. During a game I had a tesla tucked into the top right of a ref and attempted to sell the coil. Instead I sold the ref.

I went and verified it in debug. While it wasn't a double sell issue, the cursor indicated I was highlighting a tesla but the ref was sold. I also tested to confirm this happens with the service depot.
