### ISSUE TITLE
Exception of type `System.IO.EndOfStreamException`: Attempted to read past the end of the stream.

### ISSUE THREAD

**Issue by francisxxx0** [OpenRA/OpenRA#10261] opened 2015-12-22 11:35 UTC
My game is keep crashing, still after re installation... Athlon X2 215 + Geforce 7200 - Windows 7 32bit

Red Alert Mod at Version release-20150919
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IO.EndOfStreamException`: Attempted to read past the end of the stream.
   at OpenRA.StreamExts.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count)
   at OpenRA.StreamExts.ReadBytes(Stream s, Int32 count)
   at OpenRA.StreamExts.ReadUInt32(Stream s)
   at OpenRA.FileSystem.MixFile.ReadBlocks(Stream s, Int64 offset, Int32 count)
   at OpenRA.FileSystem.MixFile.DecryptHeader(Stream s, Int64 offset, Int64& headerEnd)
   at OpenRA.FileSystem.MixFile..ctor(String filename, PackageHashType type, Int32 priority)
   at OpenRA.FileSystem.GlobalFileSystem.OpenPackage(String filename, String annotation, Int32 order)
   at OpenRA.FileSystem.GlobalFileSystem.<Mount>c__AnonStorey0.<>m__0()
   at OpenRA.FileSystem.GlobalFileSystem.Mount(String name, String annotation)
   at OpenRA.FileSystem.GlobalFileSystem.LoadFromManifest(Manifest manifest)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment] 2015-12-22 12:48
Thanks for the report.  This is a duplicate of #9624, so I will close this one.  Both these issues should be fixed in the playtests, but the stack traces are too general to be certain about that.

**Closed by pchote** 2015-12-22 12:48 UTC

**Comment by francisxxx0** [comment] 2015-12-23 19:05
how can i send you more details?
