### ISSUE TITLE
Should units without an attack not move on attack move?

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14084] opened 2017-09-28 12:10 UTC
Hi,
this might be a neat solution to the "frontline medics" issue. (or frontline engineers, frontline mechanics)
When removing the AttackMove trait from a unit, it does not move at all when given an attack move or assault move order. Move commands work as usual.
What do you think, would that be an improvement or worsening of the current behaviour if this were standard for all units without weapons?

**Comment by pchote** [comment] 2017-09-28 12:31
This would be better discussed on the forum.  We have several issues in this tracker from people arguing both sides of this, and none of them are particularly actionable.

**Comment by matjaeck** [comment] 2019-02-26 18:30
Potential duplicate of #5507.

**Comment by abcdefg30** [comment] 2020-08-29 18:42
Closing as duplicate of #5507.

**Closed by abcdefg30** 2020-08-29 18:42 UTC
Labels: Balancing, Red Alert
