### ISSUE TITLE
Stuck harvesters in Red Alert - Playtest 20150808

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#9025] opened 2015-08-10 14:15 UTC
At 06:00 two harvesters get stuck, most likely due to infantry crossing their paths right in front of the refinery.

http://s000.tinyupload.com/index.php?file_id=04664812877526441848
##

**Comment by penev92** [comment] 2015-08-10 18:48
Just another example of the long-standing #5968 (#9010).

**Comment by Mailaender** [comment] 2015-08-10 19:09
Maybe show an "idle harvesters" icon like they did for the workers in Age of Empires >2.

**Comment by reaperrr** [comment] 2017-02-02 19:31
Duplicate of #5968.

**Closed by reaperrr** 2017-02-02 19:31 UTC
Labels: Bug, Pathfinding
