### ISSUE TITLE
new crash login

### ISSUE THREAD

**Issue by duy5161** [OpenRA/OpenRA#13514] opened 2017-06-16 01:14 UTC
```
Date: 2017-06-16 00:54:28Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.1
Exception of type `System.Reflection.ReflectionTypeLoadException`: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OpenRA.Exts.GetNamespaces(Assembly a)
   at OpenRA.ObjectCreator.<ObjectCreator>m__0(Assembly asm)
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles)
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by reaperrr** [comment] 2017-06-16 07:33
@duy5161 Please try updating your .NET installation to 4.5 or newer, the Runtime Version indicates you have an older version than that.

**Comment by Mailaender** [comment] 2017-08-05 09:04
Duplicate of https://github.com/OpenRA/OpenRA/issues/13773

**Closed by Mailaender** 2017-08-05 09:04 UTC
Labels: Crash, OS: Windows
