### ISSUE TITLE
TS Adjust altitude should be predictive

### ISSUE THREAD

**Issue by AndriiYukhymchak** [OpenRA/OpenRA#14187] opened 2017-10-15 16:30 UTC
Aircraft in TS looks really wonky. Best option would be to make predictive scan in-front of the heli to not look like they all are going to crash into closest ridge

**Comment by pchote** [comment] 2017-10-15 16:33
Closing as duplicate of #13334.

**Closed by pchote** 2017-10-15 16:33 UTC
