### ISSUE TITLE
.net Framework Initiation Error: Unable to find a version of the runtime to run this application.

### ISSUE THREAD

**Issue by SzMithrandir** [OpenRA/OpenRA#10307] opened 2015-12-27 22:28 UTC
Screenshot attached; my PC is of Windows XP.
![qq 20151227043144](https://cloud.githubusercontent.com/assets/16450943/12009720/58c78b28-ac52-11e5-8cd8-6a476b88782e.png)

Sorry if this is a dummy question, but .. I tried searching the keywords, and found nothing in the repository. My questions are:
1. Is OpenRA supposed to be run independently, or merged into the existing C&C / RA1 / etc directory?
2. Since I'm still using the antiquated XP, I don't need to run in compatible mode right? OpenRA is not something created under Win98, I guess?
3. I don't see any setup or settings file to run ahead -- except for the OpenRA.Game.exe.config which contains some html voodoo that I have no clue of manipulating.

Thanks ahead!

**Comment by pchote** [comment] 2015-12-27 22:33
OpenRA needs at least XP SP3 plus .NET 4.0 to be installed.  I'm surprised that this error wasn't caught by the installer.

**Comment by SzMithrandir** [comment] 2015-12-27 23:03
I do have Service Pack 3.
I'm not sure about .NET framework (learned this term just now) .. I'll try to install some post-4.0 version, if it's not yet in the computer.

The XP was installed in 2012 summer. The computer hardware was bought in 2011, lenovo E420 --- this is not that bad right?

**Comment by penev92** [comment] 2015-12-28 00:38
Interesting.
In theory it should work if you install .NET 4.0.

**Comment by SzMithrandir** [comment] 2015-12-28 00:58
.NET 4.0 installed, many thanks!

However I'm still confused about "how to run"..
![qq 20151227195745](https://cloud.githubusercontent.com/assets/16450943/12012812/dff92904-acd3-11e5-907a-ab32048f7981.png)

Under {{D:\Program Files\Command & Conquer}} I have many items installed, including C&C95, ra1, ra2, yuri, and OpenRA, in their respective folders. Do I have to copy the files into OpenRA folder? Or are they supposed to be detected by OpenRA? --- why there ain't any hint in the FAQs or any help/readme files .. :/

**Comment by Phrohdoh** [comment] 2015-12-28 01:02
There are help topics.
https://github.com/OpenRA/OpenRA/wiki/Game-Content

**Comment by penev92** [comment] 2015-12-28 01:18
Something is wrong with the rendering. That dialog should look like this:
![](http://i.imgur.com/DwUv2be.png)
You can try clicking where the buttons should be, or you can read the wiki article to see how to install the assets manually.

**Comment by SzMithrandir** [comment] 2015-12-28 01:59
Here are the two logs of interest. I have renamed them as .txt files.
The Chinese character 在 means "at / in".

[exception.txt](https://github.com/OpenRA/OpenRA/files/72895/exception.txt)
[graphics.txt](https://github.com/OpenRA/OpenRA/files/72896/graphics.txt)

**Comment by Mailaender** [comment] 2015-12-28 12:16
```
GL Error: OutOfMemory
   在 OpenRA.Platforms.Default.ErrorHandler.CheckGlError()
   在 OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
   在 OpenRA.Graphics.Sheet.GetTexture()
   在 OpenRA.Graphics.SpriteRenderer.Flush()
   在 OpenRA.Graphics.SpriteRenderer.SetRenderStateForSprite(Sprite s)
   在 OpenRA.Graphics.SpriteRenderer.DrawSprite(Sprite s, float2 location, Single paletteTextureIndex, float2 size)
   在 OpenRA.Widgets.WidgetUtils.FillRectWithSprite(Rectangle r, Sprite s)
   在 OpenRA.Widgets.WidgetUtils.DrawPanelPartial(Rectangle bounds, PanelSides ps, Sprite borderTop, Sprite borderBottom, Sprite borderLeft, Sprite borderRight, Sprite cornerTopLeft, Sprite cornerTopRight, Sprite cornerBottomLeft, Sprite cornerBottomRight, Sprite background)
   在 OpenRA.Widgets.WidgetUtils.DrawPanelPartial(String collection, Rectangle bounds, PanelSides ps)
   在 OpenRA.Mods.Common.Widgets.ButtonWidget.DrawBackground(String baseName, Rectangle rect, Boolean disabled, Boolean pressed, Boolean hover, Boolean highlighted)
   在 OpenRA.Mods.Common.Widgets.ButtonWidget.DrawBackground(Rectangle rect, Boolean disabled, Boolean pressed, Boolean hover, Boolean highlighted)
   在 OpenRA.Mods.Common.Widgets.ButtonWidget.Draw()
   在 OpenRA.Widgets.Widget.DrawOuter()
   在 OpenRA.Widgets.Widget.DrawOuter()
   在 OpenRA.Widgets.Widget.DrawOuter()
   在 OpenRA.Widgets.Widget.DrawOuter()
   在 OpenRA.Widgets.Widget.DrawOuter()
   在 OpenRA.Widgets.Widget.DrawOuter()
   在 OpenRA.Game.RenderTick()
   在 OpenRA.Game.Loop()
   在 OpenRA.Game.Run()
   在 OpenRA.Program.Run(String[] args)
   在 OpenRA.Program.Main(String[] args)


OpenGL Information:
Vendor: Intel
Renderer: Intel(R) HD Graphics 3000
GL Version: 3.1.0 - Build 6.14.10.5415
Shader Version: 1.40 - Intel Build 6.14.10.5415
Available extensions:
GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_EXT_texture_swizzle GL_ARB_sync GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_ARB_framebuffer_object GL_EXT_texture_array GL_EXT_texture_integer GL_ARB_map_buffer_range GL_EXT_texture_snorm GL_INTEL_performance_queries GL_ARB_copy_buffer GL_ARB_sampler_objects GL_NV_primitive_restart GL_ARB_seamless_cube_map GL_ARB_uniform_buffer_object GL_ARB_depth_clamp GL_ARB_vertex_array_bgra GL_ARB_shader_bit_encoding GL_ARB_draw_buffers_blend GL_ARB_texture_query_lod GL_ARB_explicit_attrib_location GL_ARB_draw_elements_base_vertex GL_ARB_instanced_arrays GL_ARB_fragment_coord_conventions GL_EXT_gpu_program_parameters GL_ARB_texture_buffer_object_rgb32 GL_ARB_compatibility GL_ARB_texture_rgb10_a2ui GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_timer_query GL_ARB_vertex_array_object GL_ARB_provoking_vertex 
```

Duplicate of https://github.com/OpenRA/OpenRA/issues/9739 :cry:

**Closed by Mailaender** 2015-12-28 12:16 UTC
Labels: Crash, OS: Windows
