### ISSUE TITLE
wall generates way to much agro for AI

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13441] opened 2017-06-03 15:02 UTC
The AI is just fixed on destroying a wall even if it has access via pathfinding to the base and actual buildings

**Comment by reaperrr** [comment] 2017-06-03 15:15
We can probably fix that once @pchote's AutoTargetPriority is in (by giving walls a low priority).

**Comment by RRPRIME** [comment] 2017-06-03 15:15
![screen shot 2017-06-03 at 4 54 36 pm](https://cloud.githubusercontent.com/assets/6293391/26754723/4319eebc-4880-11e7-8a49-9f35eacbef50.png)

**Comment by Smittytron** [comment] 2017-09-15 02:22
Duplicate of #7636

**Closed** 2017-09-15 06:52 UTC
Labels: AI
