### ISSUE TITLE
GrantConditionOnMovement ignores rotation as such

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15127] opened 2018-05-08 14:50 UTC
Basically since I cant use Transforms due to #15126 , I am making the actors Transform on condition (Graions trait) using the exclusive trait and waiting until they stay still, but since this ignores rotation, the unit can transform mid way by mistake.

**Comment by abcdefg30** [comment] 2018-05-08 20:31
Judging from the title this is a duplicate of #13346.

**Closed by abcdefg30** 2018-05-08 20:31 UTC
