### ISSUE TITLE
Game crash due to File not found: jtc04.husk.shp

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#19775] opened 2021-10-27 07:10 UTC
OpenRA release-20210321 AppImage

Red Alert, single player skirmish vs many AI.
Map: Asia Universalis v0.01 by Pinkthoth.

Crash happens when I detonate an explosive truck in the enemy base.

```
OpenRA engine version release-20210321
Red Alert mod version release-20210321
on map 085b9192b14e6548de0d60b0cd085c53169e0af4 (Asia Universalis v0.01 by Pinkthoth).
Date: 2021-10-27 07:01:05Z
Operating System: Linux (Unix 5.7.0.0)
Runtime Version: Mono 6.4.0.198 (tarball Tue Sep 24 01:20:30 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: File not found: jtc04.husk.shp
  at OpenRA.Mods.Common.Graphics.FileNotFoundSequence.OpenRA.Graphics.ISpriteSequence.get_Tick () [0x00000] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Graphics.Animation.CurrentSequenceTickOrDefault () [0x00011] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Graphics.Animation.PlaySequence (System.String sequenceName) [0x0000d] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Graphics.Animation.PlayRepeating (System.String sequenceName) [0x0000e] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Mods.Common.Traits.Render.WithSpriteBody..ctor (OpenRA.ActorInitializer init, OpenRA.Mods.Common.Traits.Render.WithSpriteBodyInfo info, System.Func`1[TResult] baseFacing) [0x000d6] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Mods.Common.Traits.Render.WithSpriteBody..ctor (OpenRA.ActorInitializer init, OpenRA.Mods.Common.Traits.Render.WithSpriteBodyInfo info) [0x00000] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Mods.Common.Traits.Render.WithSpriteBodyInfo.Create (OpenRA.ActorInitializer init) [0x00000] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.Actor..ctor (OpenRA.World world, System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x001a2] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.World.CreateActor (System.Boolean addToWorld, System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00000] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.World.CreateActor (System.String name, OpenRA.Primitives.TypeDictionary initDict) [0x00000] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Mods.Common.Traits.SpawnActorOnDeath+<>c__DisplayClass5_0.<OpenRA.Traits.INotifyRemovedFromWorld.RemovedFromWorld>b__4 (OpenRA.World w) [0x00000] in <5ef18333659f4b3884b32134748e7e88>:0 
  at OpenRA.World.Tick () [0x001c5] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001bc] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.LogicTick () [0x0003e] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.Loop () [0x000f1] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.Run () [0x0003c] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <24adfa0d4e934ea8abdc965bd2260629>:0 
  at OpenRA.Launcher.Program.Main (System.String[] args) [0x00044] in <654d601744ea40a08007c756fb7dd724>:0 
```

Replay:
[ra-2021-10-27T061406Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/7423927/ra-2021-10-27T061406Z.orarep.zip)

**Comment by pchote** [comment] 2021-10-27 08:29
This crash appears to be caused by an incorrectly defined custom unit in the [Asia Universalis v0.01](https://resource.openra.net/maps/44241/) map. This map has several lint failures that need to be fixed by the map author.

Thanks for the report, but there's nothing we can do in OpenRA to help so I suggest commenting on the map on the resource center!

**Closed as completed by pchote** 2021-10-27 08:29 UTC
Labels: Crash
