### ISSUE TITLE
Add queued actions

### ISSUE THREAD

**Issue by francisxxx0** [OpenRA/OpenRA#10634] opened 2016-01-29 10:54 UTC
Hello,
It would be awsome if i could move my units to spezific points automaticaly by queued actions. Or queued attacks. I mean clicking on some spots or units and my unit will drive to these spot sequence or destroy this tanks.

**Comment by pchote** [comment] 2016-01-29 11:17
You can hold shift while queuing (most) orders to queue them up.

**Comment by Mailaender** [comment] 2016-01-29 21:44
Duplicate of https://github.com/OpenRA/OpenRA/issues/2598.

**Closed by Mailaender** 2016-01-29 21:44 UTC
