### ISSUE TITLE
Oum Hadjer map script fatal error

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#18693] opened 2020-10-09 16:09 UTC
## Issue Summary

The mission stops suddenly saying the map script has encountered a fatal error in release-20200503
[lua.log](https://github.com/OpenRA/OpenRA/files/5355730/lua.log)

## Reproduction

In order for this to happen you must reach the first bridge by the beginning without destroying the GDI APC with the civilians

## Expected behavior

Go past the first bridge regardless of the bug

## Screenshots / Screen recordings / Replays

![OpenRA-2020-10-09T155837828Z](https://user-images.githubusercontent.com/72616219/95605611-91c0bb80-0a2f-11eb-943b-774c16f6a21e.png)
![OpenRA-2020-10-09T155839294Z](https://user-images.githubusercontent.com/72616219/95605621-94231580-0a2f-11eb-98a0-9ffcab290fff.png)

**Comment by abcdefg30** [comment] 2020-10-10 23:33
Thanks for the report. I cannot reproduce this on our development branch the same way I can on the last release, so this must have been fixed in the meantime. (#18070)

**Closed as completed by abcdefg30** 2020-10-10 23:33 UTC
Labels: Bug, Scripting
