### ISSUE TITLE
Keep skirmish and multiplayer loby settings\rules after each game

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#10859] opened 2016-03-02 10:47 UTC
Title^

well this is tiresome,after each game you must set the settings from start...the only option for multiplayer that must get back to default is the "debug mode" for obvious reasons.

**Comment by pchote** [comment] 2016-03-02 11:06
Duplicate of #4122.

**Closed by pchote** 2016-03-02 11:06 UTC
