### ISSUE TITLE
Exception of type `System.ArgumentException`: Illegal characters in path.

### ISSUE THREAD

**Issue by ibrokemypie** [OpenRA/OpenRA#12689] opened 2017-02-04 10:50 UTC
Crashes immediately upon selecting RA2 in mods. On windows 10, running latest bleeding pulled from git 5 minutes ago for both OpenRA and RA2.

Have done some searching, does not appear to be a dupe.

[exception-2017-02-04T104336Z.txt](https://github.com/OpenRA/OpenRA/files/752197/exception-2017-02-04T104336Z.txt)

**Comment by abcdefg30** [comment] 2017-02-04 11:15
Duplicate of https://github.com/OpenRA/ra2/issues/334 (RA2 related issues are kept in https://github.com/OpenRA/ra2).

**Closed by abcdefg30** 2017-02-04 11:15 UTC
