### ISSUE TITLE
AI is unable to find targets for paratroopers superpower

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#7174] opened 2014-12-22 18:47 UTC
AirstrikePower, on the other hand, seems to work:

![screenshot from 2014-12-22 19 42 09](https://cloud.githubusercontent.com/assets/4331210/5529364/4ec5518a-8a13-11e4-9cc6-6abac94cb467.png)

Will affect the new Tank Drop, too.

May or may not be a duplicate of #6899.

**Comment by obrakmann** [comment] 2015-01-17 09:09
This isn't completely broken. In a game yesterday I saw these messages for a while, but later two different AIs also attacked me with both paratroopers and a tank drop.

**Comment by UberWaffe** [comment] 2015-04-10 05:19
Just some clarification on this issue.
When I setup the power considerations for paratroopers initially, I went for the idea that:
"Paratroopers are most effective when they can be thrown on an undefended part of the enemy's base."

This can be seen here: https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/ai.yaml#L74-L88

Consideration@1 gives attractiveness to buildings (i.e. the AI would like to target your base.)
Consideration@2 decreases attractiveness for enemy units or defenses nearby.

So if the AI is looking at an enemy, but the enemy has its entire base relatively well covered, then the above mentioned scenario will occur.
You could change:
```
Consideration@2:
				Attractiveness: -10
```
to 
```
Consideration@2:
				Attractiveness: -1
```
Or such to make it care less about only targeting completely undefended parts of the enemy base, but rather only parts that have less defense than buildings.

**Comment by Mailaender** [comment] 2015-07-28 19:30
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/8564.

**Closed by Mailaender** 2015-07-28 19:30 UTC
Labels: AI, Red Alert, Regression
