### ISSUE TITLE
Renaming cancels when someone enters the server.

### ISSUE THREAD

**Issue by CortexReaver** [OpenRA/OpenRA#20049] opened 2022-05-29 14:00 UTC
When someone enters the room (server), while you trying to change your name in the lobby, it cancels process of renaming and leaves you with what you have managed to type already.

**Comment by Mailaender** [comment] 2022-05-29 15:03
Duplicate of https://github.com/OpenRA/OpenRA/issues/5802

**Closed as completed by Mailaender** 2022-05-29 15:03 UTC
Labels: Bug
