### ISSUE TITLE
Multiply all damage and health values by 100 or 1000 in the nonD2K mods.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11719] opened 2016-07-26 12:27 UTC
One of the actual benefits of Dune 2000's arbitrarily huge health pools and damage values is to have more bits for the float-integer conversion during actual damage calculation, preventing issues like #11425 to happen.

I think it would be useful to add this D2k trait to the other mods as well (would give more freedom to balancers without triggering rounding-to-0 possibilities).

**Comment by AoAGeneral** [comment] 2016-07-27 19:17
Does this mean every unit is getting a HP increase? Cause I thought the issue was fixed in #11460

**Comment by MustaphaTR** [comment] 2016-07-27 19:19
It actually buffs them. Instead of just letting them damage. They are dealing at least 1 damage now. Instead of, for example, 0.5 as it can't deal that damage. If we multipile all damage and HP values, it can deal that damage as supposed.

**Comment by AoAGeneral** [comment] 2016-07-27 19:27
The issue in #11425 which leads to #11460 never fixed the issue. It instead now kills tanks like no tomorrow. The issue is veterancy on tanks allowed immunity from minigunners. If the HP based units and structures are going to be increased this can cause quite a balance shift.

**Comment by MustaphaTR** [comment] 2016-07-27 19:31
I can't see why it will effect balance. Not HPs are gonna incrased,  damages too. It just makes maths easier. And indeed can prevent immunities.

**Comment by GraionDilach** [comment] 2016-07-27 21:45
Damages and SelfHealing/DamagedByTerrain values would need as well. The whole point on raising this issue is to instead of dealing 6 damage with 10% verses against a unit with 50 HP, deluiver, say, 600 damage with the same 10% damage against that same unit but having 5000 HP. (Except that in the latter case, the 10% damage is calculated to 60 damage, compared to the 0.6 rounded to 0 in the former case).

Scaling, @AoAGeneral , scaling.

**Comment by AoAGeneral** [comment] 2016-07-27 23:20
Aye but there are units that have shots that only do mitigated damage depending if the shots hit mark or not which can shave off only a % of the hit based on projectile landing.

**Comment by GraionDilach** [comment] 2016-07-28 05:53
Yes, and #11425 showcased how low health pool values perform when mitigated. You start with two percentage values applied by default by each warhead (verses and falloff), with the veterancy armor multiplier being the third.

On a base value of <100, it's quite likely that these three values will be enough to reduce that base value to 0. On a base value of 10000, it is a lot less likely.

**Comment by AoAGeneral** [comment] 2016-07-28 20:14
Hmm I see. Kinda weird how Veterancy has an armor value on it when I figured it did only damage and HP multipliers.

**Comment by GraionDilach** [comment] 2016-07-29 03:02
The HP multiplier is what I referred as armor, because it doesn't change the HP of the unit, but applies a percentage value to incoming damages instead.

**Comment by reaperrr** [comment] 2016-08-20 23:58
Ok, so what factor should we settle on? Personally, I think 10x might be enough (would approximately match D2k), but I guess we could play it save and go for 100x. 1000x is definitely overkill in my eyes.

I'm asking because I wouldn't mind taking this on, but I don't want to go for one multiplier only to have it rejected during review and being forced to redo it.

**Comment by pchote** [comment] 2016-08-21 11:40
Either 10 or 100 would be fine by me.

**Comment by GraionDilach** [comment] 2016-08-21 11:47
I'd prefer 100 tbh.

**Comment by MustaphaTR** [comment] 2016-08-21 11:51
100 sounds good.

**Comment by reaperrr** [comment] 2017-03-18 15:49
I think D2k is fine the way it is, but we should possibly give this another try regarding RA/TD/TS for Next+1.

@pchote I don't remember what exactly you meant in #11852 with
> On second thought... this has the unfortunate and not very nice side-effect that our integer-percentage damage modifiers are now nowhere near precise enough.

Could you give an example?

**Comment by GraionDilach** [comment] 2017-03-18 17:27
I assume that this would stress that we cannot have precisions under 1% (say, 0.5% damage), something I don't believe should be even considered as an issue because a modder can create such via custom armors.

**Comment by pchote** [comment] 2017-03-18 17:50
The problem is that when you have a damage > 1000 that spread damage produces a staircase with steps of damage / 100 instead of a continuous-ish decay. This is already a problem for the RA/TD nukes, which we work around by scaling the Falloff up and the damage down.

**Comment by AoAGeneral** [comment] 2017-03-18 21:22
Is there a way to have the unit do 1 damage every other shot if its below the %?

**Comment by reaperrr** [comment] 2017-03-18 22:39
> The problem is that when you have large damage that spread damage produces a staircase instead of a continuous-ish decay.

But in terms of actual effect on balance, going 70-30-10 is no different to 7-3-1. Is that really such a problem?
And if this is only about the shipping mods, we could simply take the Falloff approach on all weapons, thanks to inheritance that would now be easier than changing all base damages directly anyway.

> Is there a way to have the unit do 1 damage every other shot if its below the %?

I suspect that the coding required for this would be too complicated to chose this over possible alternatives.

**Comment by Arular101** [comment] 2017-11-06 19:44
I made a PR for the RA mod. See #14301

**Comment by Arular101** [comment] 2017-11-27 17:35
After the green light for the changes and all the progression made in the PR for the RA mod, I started to do the same changes for the TD mod. Luckily, it seems less time consuming than the RA mod. Thanks to fewer custom weapon rules in missions.

I'll start with the D2K mod after the TD mod. This could also be changed relatively fast. The values of D2K will be multiplied by 10, bringing it in line with the other mods. I presume this is also wanted (looking at @MustaphaTR, as our main contributor for D2K, for conformation).

I'll have this done well in time before Christmas.

Last but not least is the TS mod. I'll do it after all the PRs are finished.

**Comment by Arular101** [comment] 2017-11-29 17:48
@MustaphaTR, while I started to change the values for D2K, I noticed that the `armor type: concrete` is only defined in a couple of places:

Weapons\debris.yaml
`Debris: Versus: concrete: 100`
`Debris2: Versus: concrete: 100`
Weapons\other.yaml
`PlasmaExplosion: Versus: Concrete: 60`

Rules\structures.yaml:
`large_gun_turret: Armor: Type: concrete`

The other weapons don't have concrete defined, resulting in 100% damage vs the Large Gun Turret (the only building with concrete armor).

I assume this is not correct.

**Comment by MustaphaTR** [comment] 2017-11-29 18:51
I'll check original values when i get to other Computer, this one doesn't run TibEd's D2K mode for some reason.

**Closed** 2017-12-28 09:12 UTC
Labels: Red Alert, Refactor, Tiberian Dawn, Tiberian Sun
