### ISSUE TITLE
Crash playing same map after game close

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#11378] opened 2016-05-29 22:32 UTC
It seems that exiting the game when playing a skirmish map and then launching the game again and playing the same map without entering the map chooser sometimes causes a crash. On bleed. Can't replicate every time.

> Red Alert Mod at Version {DEV_VERSION}
> on map 9249aabd4af5fd9dfe19dcbb6de6e5b86b436265 (Mad Science by PizzaAtomica).
> Operating System: Linux (Unix 4.4.0.22)
> Runtime Version: Mono 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4) CLR 4.0.30319.17020
> Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
>   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.<BindingRefresh>m__1 () <0x40d50780 + 0x00039> in <filename unknown>:0 
>   at OpenRA.Primitives.ActionQueue.PerformActions (Int32 currentTime) <0x40c7b8b0 + 0x001ba> in <filename unknown>:0 
>   at OpenRA.Game.LogicTick () <0x40c7b790 + 0x0002b> in <filename unknown>:0 
>   at OpenRA.Game.Loop () <0x40c7b540 + 0x0014b> in <filename unknown>:0 
>   at OpenRA.Game.Run () <0x40c7b3d0 + 0x00077> in <filename unknown>:0 
>   at OpenRA.Program.Run (System.String[] args) <0x40d9ca80 + 0x0005f> in <filename unknown>:0 
>   at OpenRA.Program.Main (System.String[] args) <0x40d9bd60 + 0x000f7> in <filename unknown>:0

[logs.zip](https://github.com/OpenRA/OpenRA/files/288577/logs.zip)

**Comment by RoosterDragon** [comment] 2016-12-23 21:05
Reverse duplicate of #12271.

**Closed by RoosterDragon** 2016-12-23 21:05 UTC
Labels: Crash
