### ISSUE TITLE
Turreted units on AttackAnything ignoring new targets

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14279] opened 2017-10-31 02:00 UTC
Didn't retry to reproduce it, and not sure this is what exactly happened, but here is my guess : 
- Set a turreted unit on AA stance
- During combat, acquire a first target
- Move it away from combat. Turret still aimed at first target
- New target comes in bound, but is ignored by the unit. 

Not sure if this applies to only turreted unit, and not sure it's really related to AA.
 
Happened to me in this case : https://go.twitch.tv/videos/186335395 at 04:57:55 , where purple tank is aiming at a previous target. (one of the teslas)

**Comment by GraionDilach** [comment] 2017-10-31 03:20
Duplicate of #12856.

**Closed** 2017-11-01 12:43 UTC
Labels: Bug
