### ISSUE TITLE
[bleed] Crash occurs when queue ordering reusable engineer after production exit.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#15734] opened 2018-10-25 23:42 UTC
Log: https://pastebin.com/2XBqZd5L

I can't seem to pin down the exact reproduce steps and for whatever reason can't reproduce this in debug mode.

Rally point your barracks/tent to a distance, spam queue orders from the first rallypoint move-order. You'll probably want 'explored map: on' and fastest gamespeed to save you time. 'Reusable Engineers: on' off course.

**Comment by pchote** [comment] 2018-10-26 13:12
Duplicate of #15697 which luckily we know exactly how to solve.

**Closed by pchote** 2018-10-26 13:12 UTC
Labels: Crash
