### ISSUE TITLE
Unit cancel movement orders when path is temporarily blocked

### ISSUE THREAD

**Issue by TAK02** [OpenRA/OpenRA#9010] opened 2015-08-09 06:15 UTC
Sometimes, when the unit path is blocked by another unit, the unit will stop moving at all.

**Comment by deniz1a** [comment] 2015-08-09 15:50
May be related: #5968

**Comment by obrakmann** [comment] 2015-12-30 14:49
In fact a duplicate of #5968.

**Closed by obrakmann** 2015-12-30 14:49 UTC
Labels: Bug, Pathfinding
