### ISSUE TITLE
[Idea] missions seqense

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#12417] opened 2016-11-23 13:05 UTC
Now, if we finish single player mission, we can only quit in main menu.
"Next mission" and "Return to mission list" buttons after finish any mission will be very userful I think.

**Comment by Mailaender** [comment] 2016-11-23 21:42
Duplicate of https://github.com/OpenRA/OpenRA/issues/4492 and https://github.com/OpenRA/OpenRA/issues/7214.

**Closed by Mailaender** 2016-11-23 21:42 UTC
