### ISSUE TITLE
Fine Tune Cooperative Mode

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12929] opened 2017-03-08 12:54 UTC
Now days we all love coop,you and your friend vs the world! what a better joy two friends can have in a game.well here is some of my ideas for a prefect coop play.

1) Automatically re join previous server (if the server allows it,this can be a server option).

2) Automatically play mission briefing\info video after mission start\end.

3) Save next\unfinished map in player profile, like in red alert 2 

4) Reload next\unfinished map in the lobby,based on players(user names) currently in the lobby and the game type (coop) like in red alert 2.

5) If not the above, then an in-game save\load ability (and then i woke up)

6) Allow players to watch briefing\info videos in the lobby like in single missions (release-20161019)

7a) Share control for units, buildings, radar, economy, based on the mission layout.

7b) Show player selected actors(units ect) with color indication in the selection square.

7c) OPTIONAL* deny control of player selected actors by coop partner,until they are unselected.

8) Automatically select next mission in the lobby if previous mission was won by the players.

9) Ability to toggle between mission default player colors or player selected colors,in the lobby.

I can't think any thing else that can be added or needed at this point.
Can you imagine how it will be to play a coop game with the above options? that will be a good memory in our gaming lives.

**Comment by obrakmann** [comment] 2017-03-08 20:47
First of all, please one issue per ticket.  Also please use the search function before opening a ticket. We have over a thousand open tickets, many of them suggestions, and the chances that someone already had the same idea as you've had are very high. Consequently, a lot of your points are duplicates of existing issues.

1. Duplicate of #6131.

2. and 6. are basically the same.

3. Duplicate of #4492.

4. Just as 2. and 6., you're basically asking for a MP campaign lobby. We might get there eventually, but for now, I don't even know anyone who's working on a coop campaign, so implementing a lobby for that now would just be wasting time.

5. Duplicate of #2743.

6. See 2.

7. Just no.

8. Duplicate of #4492.

9. Ah well, I'll allow it.

I'm gonna close this as WONTFIX for now. As I mentioned, we might get around to this eventually, but I suspect this ticket would otherwise still be open five years down the road.

**Closed by obrakmann** 2017-03-08 20:47 UTC
Labels: Idea/Wishlist

**Comment by KOYK** [comment] 2017-03-09 05:57
You are right,sorry for making a mess.

7 can you be more specific why not?

9 you will allow it?

**Comment by GraionDilach** [comment] 2017-03-09 10:29
7 might look nice on paper, but is complicated to code, and just messes with the player's controls in an unintuitive way. I am definitely certain the two players would conflict on the orders for sure.

**Comment by MustaphaTR** [comment] 2017-03-09 11:49
Even tho it wasn't working really fine, in RA2/YR it was possible to give a player control of more than one House. I was using it mostly on some of my maps that has some Allied units on Soviet Commander's control and vice versa during YR Campaign. It is a bit annoying that we can't do that here as i actually need that on a map.
