### ISSUE TITLE
Game logic for seaborne aircraft carriers

### ISSUE THREAD

**Issue by wuschel** [OpenRA/OpenRA#3481] opened 2013-06-27 12:01 UTC
Currently, there is no support for aircraft carriers in OpenRA. 

Two kinds of aircraft carriers would be great to have: 

a) a carrier for VTOL type of aircraft (helicopters, harriers), preferably for allies.
b) a carrier of jets e.g. a jump start carrier with a ramp, preferably for soviets.

Planes should be able to land, repair and rearm on carrier vessels. Optionally, carriers should also have on-board weaponry - but this is not necessary.

See also: http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=285423#285423

**Comment by pchote** [comment] 2015-11-22 11:32
Reverse duplicate of #3787

**Closed by pchote** 2015-11-22 11:32 UTC
Labels: Idea
