### ISSUE TITLE
Lobby crash

### ISSUE THREAD

**Issue by Raymond-cnc** [OpenRA/OpenRA#10348] opened 2015-12-30 22:35 UTC
http://pastebin.com/74V9Fnhz

Red Alert Mod at Version release-20151224
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.<SetupFactionWidget>c__AnonStorey18.<>m__0()
   at OpenRA.Mods.Common.Widgets.LabelWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment] 2015-12-30 22:36
Duplicate of #10342.

**Closed by pchote** 2015-12-30 22:37 UTC

**Comment by pchote** [comment] 2015-12-30 22:42
@Raymond-cnc: you should apply the patch https://github.com/pchote/OpenRA/commit/a6606d1cb4980f83a1e9ec8056a9b337b869750f or copy [this dll file](https://www.dropbox.com/s/jojajyjo7ocxecg/OpenRA.Mods.Common.dll?dl=0) to mods/common on your server to protect it from the script kiddy causing these crashes.

**Comment by Raymond-cnc** [comment] 2015-12-31 00:09
thanks for the heads up!
