### ISSUE TITLE
Crashes in multiplayer lobby

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#15526] opened 2018-08-16 04:43 UTC
Just catched two crashes in sequence in the same lobby featuring mostly the same players. First happened when I was picking a map, it also happened to several other players; second - just when pressing "Choose map" button. 

https://pastebin.com/AW6E4ysp

**Comment by FiveAces** [comment] 2018-08-21 17:49
Confirmed, just had the same exact problem when switching maps:
https://pastebin.com/467jbKuH

**Comment by pchote** [comment] 2018-08-21 20:04
This has happened multiple times in @FiveAces's stream tonight - this is clearly new and bad.

**Comment by matjaeck** [comment] 2018-08-21 20:28
`OpenRA engine version release-20180307
Red Alert mod version release-20180307
Date: 2018-08-18 19:45:45Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.EndOfStreamException`: Über das Ende des Datenstroms hinaus kann nicht gelesen werden.
   bei System.IO.BinaryReader.ReadString()
   bei OpenRA.Order.Deserialize(World world, BinaryReader r)
   bei OpenRA.Network.OrderIO.ToOrderList(Byte[] bytes, World world)
   bei OpenRA.Network.ReplayRecorder.IsGameStart(Byte[] data)
   bei OpenRA.Network.ReplayRecorder.Receive(Int32 clientID, Byte[] data)
   bei OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   bei OpenRA.Network.OrderManager.TickImmediate()
   bei OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   bei OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   bei OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   bei OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   bei OpenRA.Game.LogicTick()
   bei OpenRA.Game.Loop()
   bei OpenRA.Game.Run()
   bei OpenRA.Game.InitializeAndRun(String[] args)
   bei OpenRA.WindowsLauncher.RunGame(String[] args)

`

**Comment by pchote** [comment] 2018-08-22 01:44
Does anyone have replays for these? They won't show up in the replay browser, but should still exist on the filesystem.

**Comment by netnazgul** [comment] 2018-08-22 09:27
Replays of what? This crash happens in multiplayer server lobby when choosing a map.

**Comment by pchote** [comment] 2018-08-22 09:31
Seems that I forgot about #10304, which deliberately prevented replays from saving if a game hasn't started (grr....).  Coincidentally, this seems to be the code that is crashing here.

**Comment by FiveAces** [comment] 2018-08-23 16:49
For me, it was when I tried downloading a map I didn't own from the resource center. First it started searching the center, but after five seconds it froze and crashed. Happened 3 times, the MO was always the same. Hope that helps!

**Comment by netnazgul** [comment] 2018-08-24 04:34
Both times I had that involved me pressing the "Choose map" button.

**Comment by netnazgul** [comment] 2018-08-25 18:28
> 21:26] RiceShpoocher: I had that yesterday I believe. Picking a different map (after deciding and clicking on it) made the game crash for both me and everyone else in the lobby, at the same time as well.

**Comment by netnazgul** [comment] 2018-08-25 18:28
I'll try to reprocase this the following days if I have time.

**Comment by pchote** [comment] 2018-08-28 19:56
#15575 shows that this is not new, but something recently must have made this more likely to occur.

```
OpenRA engine version release-20180307
Red Alert mod version release-20180307
Date: 2018-08-28 19:42:04Z
Operating System: Linux (Unix 4.15.0.33)
Runtime Version: Mono 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1) CLR 4.0.30319.42000
Exception of type `System.IO.EndOfStreamException`: Unable to read beyond the end of the stream.
  at System.IO.BinaryReader.ReadString () [0x000ba] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.Order.Deserialize (OpenRA.World world, System.IO.BinaryReader r) [0x00243] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Network.OrderIO.ToOrderList (System.Byte[] bytes, OpenRA.World world) [0x00021] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Network.ReplayRecorder.IsGameStart (System.Byte[] data) [0x00046] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Network.ReplayRecorder.Receive (System.Int32 clientID, System.Byte[] data) [0x0001c] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Network.EchoConnection.Receive (System.Action`2[T1,T2] packetFn) [0x0007b] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x000b4] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00001] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1[TResult] fn) [0x00007] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x0000e] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0010a] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.Loop () [0x000d6] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.Run () [0x00042] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
```

**Comment by pchote** [comment] 2018-09-05 02:11
Has anybody seen the "Ignoring malformed order that would have crashed the game" warning from #15554?

**Comment by pchote** [comment] 2018-09-09 01:11
I guess not.  Removing from the milestone.

**Comment by dragunoff** [comment] 2018-09-11 22:07
I got the same crash as netnazgul's second exception, several times, immediately after joining a lobby. Here's the log:
```
OpenRA engine version playtest-20180825
Red Alert mod version playtest-20180825
Date: 2018-09-11 19:36:06Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at OpenRA.Network.Session.ClientInSlot(String slot)
   at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList()
   at System.Action.Invoke()
   at OpenRA.Game.SyncLobbyInfo()
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   at OpenRA.Network.OrderManager.TickImmediate()
   at OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```

**Comment by netnazgul** [comment] 2018-09-12 07:14
> at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList()

I think this is a clue that something got broken with lobby player list?

**Comment by abcdefg30** [comment] 2018-09-20 21:59
Closing as duplicate of #13915. (No reports of different exceptions.)

**Closed by abcdefg30** 2018-09-20 21:59 UTC
Labels: Crash

**Comment by netnazgul** [comment] 2018-09-21 04:28
Wait, when should the warning be logged? If it doesn't crash the game now then noone will notice the warning and report it...

**Comment by pchote** [comment] 2018-09-21 08:45
The warning is written to the game chat whenever the game recovers from a situation that would have previously caused a crash.
