### ISSUE TITLE
chinooks stack on top of each other when landing

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13480] opened 2017-06-08 17:57 UTC
chinooks stack on top of each other when landing
Mission:Intervention
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/6293391/26943112-c057fc18-4c84-11e7-9d41-c3785536ce94.gif)

**Comment by FRenzy-OpenRA** [comment] 2017-06-09 08:38
Duplicate of this ? #13177

**Comment by atlimit8** [comment] 2017-06-09 10:16
Duplicate of #6068 & arguably #4605.

**Closed by atlimit8** 2017-06-09 10:16 UTC
Labels: Bug, Pathfinding
