### ISSUE TITLE
[RA] Tanya visually appears buildable when inside pillbox/ranger/chinook.

### ISSUE THREAD

**Issue by jaZzKCS** [OpenRA/OpenRA#12252] opened 2016-10-17 18:59 UTC
When Tanya is not active ON the battlefield, but rather in a transport or building, whe appears (visually) as "buildable".

Release-20161015

**Comment by abcdefg30** [comment] 2016-10-17 20:25
Duplicate of #5872.

**Closed by abcdefg30** 2016-10-17 20:25 UTC
