### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#15645] opened 2018-09-25 19:32 UTC
latest release, in lobby

Exception of type `System.InvalidOperationException`: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x419fbfa0 + 0x0018f> in <filename unknown>:0 
  at OpenRA.Network.Session.ClientInSlot (System.String slot) <0x41d97600 + 0x00117> in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList () [0x00080] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyLogic.cs:549 
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at OpenRA.Game.SyncLobbyInfo () <0x41d94f00 + 0x00015> in <filename unknown>:0 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) <0x41d8d000 + 0x0189b> in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () <0x41c69330 + 0x00463> in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () <0x41c687d0 + 0x00019> in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1 fn) <0x41c68690 + 0x00039> in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) <0x41c68540 + 0x00113> in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) <0x41c67cc0 + 0x0030b> in <filename unknown>:0 
  at OpenRA.Game.LogicTick () <0x41c661a0 + 0x000b3> in <filename unknown>:0 
  at OpenRA.Game.Loop () <0x41c65d40 + 0x0014f> in <filename unknown>:0 
  at OpenRA.Game.Run () <0x41c657d0 + 0x00077> in <filename unknown>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) <0x419baa80 + 0x0004f> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x419b9d60 + 0x000f7> in <filename unknown>:0 

AL lib: FreeContext: (0x2edc240) Deleting 32 Source(s)

**Comment by abcdefg30** [comment] 2018-09-26 10:13
Duplicate of #13915.

**Closed by abcdefg30** 2018-09-26 10:13 UTC
Labels: Crash
