### ISSUE TITLE
Multiple helicopters fail queued movement if exact waypoint not available

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11796] opened 2016-08-10 14:30 UTC
If you give a group of helicopters queued move orders, they will not move to the second waypoint until they can reach the first waypoint precisely. If the first waypoint is blocked (by another helicopter trying to access the waypoint), the other helicopters will hover as close as possible rather than being "close enough" and moving to the next waypoint.

build 5 helicopters
give them a waypoint and queue a second waypoint
Hind units will bunch close together and none of them will reach the waypoint. Chinook and Longbow units will typically have the first 1 or 2 units reach the first waypoint and move on to the second. The others will circle around the first waypoint.
If you manually move one of the stuck helicopters out of the way, that will usually clear up the first waypoint and the other helicopters will reach the first waypoint and move to the second.

**Comment by WolfGaming** [comment] 2016-08-10 14:37
This is probably some weird interaction with nudging and waypoints, nudging makes this hard as the point isn't inaccessible so we can't just drop the first waypoint and continue to the next as that would break waypoints completely.

**Comment by Smittytron** [comment] 2018-02-18 01:27
Duplicate of #11521

**Closed** 2018-02-19 14:03 UTC
Labels: Pathfinding
