### ISSUE TITLE
"Cannot Build Here" cursor for walls noexistent

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#15002] opened 2018-03-26 17:33 UTC
Red placement cursor for walls is nonexistent. Other structures such as flame tower or powerplant have red cursor if something is blocking placement. Not walls.

**Comment by Smittytron** [comment] 2018-03-26 17:52
Duplicate of #13632

**Closed** 2018-03-26 20:19 UTC
Labels: Bug
