### ISSUE TITLE
Remove fake structures building off fake structures

### ISSUE THREAD

**Issue by OpenOP2Admin** [OpenRA/OpenRA#18723] opened 2020-10-13 17:53 UTC
Reverse the fake building building off their own building radius, meaning, the capabilities added in https://github.com/OpenRA/OpenRA/pull/15091

With fakes building off fakes, you can just spam a gigantic wall or create an artificial chokepoint for very little money. Plus, it looks absolutely stupid and irritates casual players. This is exactly as predicted in this post: https://github.com/OpenRA/OpenRA/pull/15091#issuecomment-386818004

**Comment by Orb370** [comment] 2020-10-13 18:25
:-1: 

It's a good feature that solved the issue of fake structures cluttering your base. Without a build radius fake structures stopped you from placing your normal structures.

If the issue is specifically fake powerplants being used as walls, they could receive a price increase of 30 -> 50.

If it's an issue with it in general, I'd prefer a compromise rather than just stripping the feature entirely. For example, fake structures being able to be placed further away (like walls IIRC).

**Comment by KOYK** [comment] 2020-10-13 19:04
If fake structures take up space, then don't build them, ive never understood the idea behind this edit. 

The general idea of fakes is that you pop them and go, or cleverly leave some of them at your base, if some one wants to place obstacles well, use walls as its their primary faction. 
Changing the price won'solve the problem obviously, since if the price is too high people will just build power plants (witch defeats the purpose of fakes), if the price is too low, even $100 still not enough to be considered as a preventing factor, people will still spam them. 
And to be honest it gives the feeling of a bad mod author decision, the sooner this is fixed the better. So :+1:

**Comment by Orb370** [comment] 2020-10-13 19:17
Oh, the thumbs down brigade is here.

This change was to fix a problem. Proposing to remove the fix without fixing the problem is just going in circles.

Without a build radius you are actively punished building fakes because it clutters your base. 

At 50 price it is still reasonable to build a fake powerplant to stop snipes, but building walls instead is more reasonable if that what you were using them for.

**Comment by OpenOP2Admin** [comment] 2020-10-13 19:38
> compromise

https://pasteboard.co/JvuUGrg.png
https://pasteboard.co/JvuUP5u.png
https://pasteboard.co/JvuUXFl.png
https://pasteboard.co/JvuV5to.png

**Comment by KOYK** [comment] 2020-10-13 19:48
Sorry but aren't you the one who thump down this issue first? just look at your first post, furthermore why is a bad thing to express ones vote? 
Why are you trying to ridicule the vote\opinions of others? Maybe you should tone down your fascism a bit, we have enough of that in this world already.


> This change was to fix a problem. Proposing to remove the fix without fixing the problem is just going in circles.

That fix created other problems. 
So it wasn't a fix at all, as mentioned by the OP, re-read it again please. 

>Without a build radius you are actively punished building fakes because it clutters your base.

Yes, and you should, fakes are for deceiving your opponent, creating a game-play of smart deception, adding to the overall enjoyment of the game. 
So I don't know why fakes have become just a spam-me-plenty actor, that downgrades the game experience for the user.

>At 50 price it is still reasonable to build a fake powerplant to stop snipes, but building walls instead is more reasonable if that what you were using them for.

As I explained changing the price won't effect any thing positively. People will still spam them as walls.

**Comment by anjew175** [comment] 2020-10-13 21:38
> At 50 price it is still reasonable to build a fake powerplant to stop snipes, but building walls instead is more reasonable if that what you were using them for.

Its primarily to stop grenadiers and unless its a rare map where you can wall off every possible entrance from your starting position (so really not that many maps), walling the powerplant will not help since grenadiers can throw over walls and flamers damage the wall cell but have a big enough spread to cause damage to the cell next to it.

The main issue I see other than a wall of pp's (which is cheaper than a concrete wall to cover the same amount of distance and builds just as fast, though weaker it still makes units go a different way when used to block a choke), was one pointed out in the original discussion.
> it can be used to congest a base to make infantry crushes more reliable (an army erasing tactic)

and thats exactly what its used for in some circumstances. It really depends if you think that is someone being smart or someone abusing mechanics

**Comment by deleted-user-1** [comment] 2020-10-14 17:07
Make them consume power.

**Comment by Smittytron** [comment] 2020-10-14 17:46
If you're building fakes you aren't building pillboxes. I stand behind this change 100%.

**Comment by KOYK** [comment] 2020-10-14 18:09
if you are building fakes that take like 3 second to build you are not building pillboxes? how is that even possible? can you explain this time paradox logic behind this?

**Comment by OpenOP2Admin** [comment] 2020-10-14 19:01
>I stand behind this change 100%.

![7247b995-0782-433b-88eb-4be6f5566dd9](https://user-images.githubusercontent.com/65933392/96033486-fbb4d880-0e14-11eb-907c-624a6cf1d8a0.png)

**Comment by deleted-user-1** [comment] 2020-10-14 21:32
Another easy fix to the spamming problem would be to move a fake building to the same production queue the real building is in. This would not hurt much if only building a few fake powerplants but put you noticeably behind when spamming them (selecting and placing the building also costs time in which your building-queue is blocked). It's also more logical. The only disadvantage is that you'll need to have to scroll down the building-tab.

**Comment by pchote** [comment] 2020-10-14 21:44
> The only disadvantage is that you'll need to have to scroll down the building-tab

If we wanted to go that route we could add new button/toggle to the sidebar that switches between regular and fake structures.

**Comment by abcdefg30** [comment] 2020-10-15 08:08
Another idea could be to raise their build time without increasing the price (which is 10% of the original price).

**Comment by Zoniier** [comment] 2020-10-18 09:04
would like to see the feature kept but re-balanced. 
make them take longer to build like abcdefg30 suggested or make them cost more/require some power which would require you to build more real power plants to support them.
 or some combination of peoples suggestions.
 you could even make them require radar dome to be built or something...............

**Comment by pchote** [comment] 2020-11-01 21:26
Do we have a plan on how to address this on the timescale of a playtest?

**Comment by abcdefg30** [comment] 2020-11-02 11:42
The idea was to add this to the milestone so discussion happens and we either resolve this (doesn't look like there is much support for this change at the moment) or close it, since keeping balance issues open for long doesn't make sense when the underlying game changes (= new release). (If you think it is worth keeping this open after the playtest/release then I don't object either.)

**Comment by pchote** [comment] 2020-11-02 14:36
Ok, in that case lets close this. It seems that there are valid arguments both for keeping it as it is, and also for changing it - but no clear justification for preferring one option over the other. If either option is going to upset people, we should keep the status quo and avoid unnecessary churn.

This is the kind of issue that is best iterated in community balance maps before a concrete proposal for changes is created here.

**Closed as completed by pchote** 2020-11-02 14:36 UTC
Labels: Balancing, Red Alert

**Comment by OpenOP2Admin** [comment] 2020-11-07 05:54
![working as intended](https://user-images.githubusercontent.com/65933392/98433287-825a7f80-207a-11eb-8ade-3d7f7cf899f1.png)

Consider reconsidering - this is ridiculous
