### ISSUE TITLE
Custom "join server" sound

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#15016] opened 2018-04-05 10:08 UTC
I think it would be a good idea to add a custom sound when a user joins a server, currently, it uses the same sound as chat and server messages, meaning it's impossible to distinguish between someone joining a server and a server admin message when alt-tabbing.

**Comment by Smittytron** [comment] 2021-03-17 18:36
Duplicate of #6246

**Closed by Smittytron** 2021-03-17 18:36 UTC
Labels: Feature, Idea/Wishlist
