### ISSUE TITLE
Service depot waypoint system does not work for Helis [playtest-20160904]

### ISSUE THREAD

**Issue by jaZzKCS** [OpenRA/OpenRA#11980] opened 2016-09-05 16:22 UTC
As reported by Frame_Limiter on IRC:
"Service depot waypoints don't work for heli's, they will low hover over the depot after a repair."

**Comment by obrakmann** [comment] 2016-09-05 17:27
This is a duplicate of #11979

**Closed by obrakmann** 2016-09-05 17:27 UTC
Labels: Regression
