### ISSUE TITLE
TD: Repaired Orca does not return to rally point

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#12012] opened 2016-09-11 09:13 UTC
Orcas built by the helipad are sent to the rally point (blue flag)
Orcas repaired by the helipad were sent to the rally point as well after repairs, but in current bleed they are stuck on the helipad (it seems they move 1-2 pixels up after repairing)

**Comment by obrakmann** [comment] 2016-09-11 09:27
Duplicate of #11979

**Closed by obrakmann** 2016-09-11 09:27 UTC
Labels: Regression
