### ISSUE TITLE
Units breaking orders and stopping without being told to do so

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#15138] opened 2018-05-13 18:12 UTC
This has been an issue for a while now. When ordering units to move, or attack move, over a significant distance, at some point, the units will just stop. Then you have to re-order them to do what you wanted, only to have them randomly stop again. Even for short distances this can happen.
Couple that with the unit pathing issues, if your attention is called to another event on the map, when you look back to your units.......they're already dead. A force, which should have won the engagement, is dead.

RIP, you'll always be remembered brave soldiers! <3

**Comment by ABrandau** [comment] 2018-05-13 19:49
From what I know, this bug has been present for years, and its a duplicate of #14822 and maybe others.

My guess is that OpenRA will cancel all queued orders of any actors that are blocked, and on this case, i define blocked when an actor is unable to move to a cell that the pathfinder planned to move it, should happen often when moving blobs.

As proof i made this gif the soldiers move around a hostile conyard with attack anything stance, and I do not issue any stop orders.

![conyard](https://user-images.githubusercontent.com/11763228/39971147-77f46218-56c4-11e8-92eb-fa9cec90aa8b.gif)

CG, use http://www.screentogif.com/ if you need to put some proof next time.

**Comment by CatGirls420-NerevarII** [comment] 2018-05-13 21:36
Ah, thank you for commenting and providing that! I figured proof wouldn't be needed because I'm sure everyone has experienced this :p 

I hope it gets fixed soon!

**Comment by abcdefg30** [comment] 2018-08-03 16:36
See #5968, #3288.

**Closed by abcdefg30** 2018-08-03 16:36 UTC
Labels: Bug

**Comment by abcdefg30** [comment] 2018-08-03 16:37
OpenRA has blocked this user from our GitHub organization.
