### ISSUE TITLE
Map download bug - Spectators kicked out as game starts

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10489] opened 2016-01-11 20:52 UTC
Recently there have been a bug : 
When you click "Install map" from lobby, tick ready, and game starts, then you get kicked out when the game starts.

You have to install the map, exit the lobby, then enter again, to avoid being kicked.

I dunno if happens on all maps / everytime, but happening to a lot of players recently.

**Comment by ShadowA** [comment] 2016-01-12 01:22
As @anjew175 pointed out, and I tested, seems to happen to spectators only.

**Comment by klaas1** [comment] 2016-01-14 09:18
This happened in the previous release too, and is specially during streams/ casts, for obvious reasons.

**Comment by pchote** [comment] 2016-03-31 19:23
Duplicate of #8233, which was fixed by #10939.

**Closed by pchote** 2016-03-31 19:23 UTC
Labels: Bug
