### ISSUE TITLE
Unit lost sound in TD is really loud

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#15574] opened 2018-08-28 02:47 UTC
This drowns out when someone orders and airstrike. It's almost impossible to hear if you're engaged in a large battle.

**Comment by abcdefg30** [comment] 2018-08-28 17:17
Duplicate of #3449 / #3844?

**Comment by pchote** [comment] 2018-08-28 17:18
Indeed.

**Closed by pchote** 2018-08-28 17:18 UTC
