### ISSUE TITLE
Do dogs attack differently now (less efficiently)?

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9171] opened 2015-08-26 15:48 UTC
(playtest 20150808)
It seems to me that dogs score much less kills than before. Try attack-moving them into enemy infantry...
Have their attack jumps been disabled? It seems that they don't reach their targets fast enough and get killed even before they attack. It happens way too often.

While I could be wrong it feels quite off to me.

You can easely test on your own but here's a sample replay (see just after 8th minute, just above pink base) for some serious dog slaughter...

http://www.filedropper.com/dogs

**Comment by pi99y** [comment] 2015-08-28 10:10
OK, so I compared dog attack behavior in the latest playtest to the last two stable versions (20150614, 20141029) and I guess nothing really changed, my bad.

However dogs still seem quite inefficient (for killing regular infantry) for the 200$. Do you think they should be made cheaper to train?

**Comment by Unit158** [comment] 2015-08-28 13:27
the trick is to wait for the inf to attack your base or something, then get a collateral. What also works is mixing them in with tanks or something if there's no arty shelling.

**Comment by TheRaffy** [comment] 2015-08-28 15:04
The Problem is that they cant get used in mass. because they all attack 1 unit and then 1 dog remains. The others die somewhere, even if the unit is not shooting.

**Comment by pi99y** [comment] 2015-08-28 15:22
Thanks for the tip @Unit158 I'll try it out.
@TheRaffy I see... maybe its role should be scouting then. If it's determined to be currently too pricey/not cost effective maybe some "scouting" features should be added - like more vision instead of lowering its price.

**Comment by TheRaffy** [comment] 2015-08-28 15:35
If you talk about that, I think dogs should be able to force jump. that would allow them to access areas where soviets normally aren't able to go, because they don't have the chinook.
So jumping over walls or cliffs, would be nice In my opinion. currently it only works when a unit is there that you can attack.

**Comment by MicroJOo** [comment] 2015-08-28 15:43
they shouldnt jump at all ... and not up a cliff or over a wall .. .thats just stupid (and we had that allready in) ... dogs need to be fixed so they work like in the original ...

**Comment by pi99y** [comment] 2015-08-28 19:16
@MicroJOo would fixing dog movement also improve their effectiveness? How effective were they in the original?

**Comment by GraionDilach** [comment] 2015-08-28 21:15
Looking to that animation, I'd guess insta-kill.

**Comment by pi99y** [comment] 2015-08-29 14:56
It's insta-kill already *IF* it manages to attack before it's killed...

**Comment by MicroJOo** [comment] 2015-08-31 09:14
@pi99y : what i mean by fixing it , is ... we should add the "running frames" which we currently dont use ... aka. he has a normal speed for scouting ... and as soon as he sees a enemy "starts running" and then he makes a 1 cell jump ... this ends up "tearing apart" the enemy (which gives him a break , so he cant just jump to the next enemy

so this is far away from a insta-kill ...

**Comment by pi99y** [comment] 2015-08-31 14:14
Thanks for the clarification @MicroJOo

**Comment by pchote** [comment] 2015-11-22 14:22
Duplicate of #7506.

**Closed by pchote** 2015-11-22 14:22 UTC
Labels: Balancing, Question, Red Alert
