### ISSUE TITLE
[RA] Option to show/hide '% of game played' information in the replay viewer.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10745] opened 2016-02-13 13:59 UTC
Like TD and D2K the U.I. shouldn't reveal how much of the game has passed. It's a spoiler for viewing other people's replays, including casts.

**Comment by pchote** [comment] 2016-02-13 14:44
What if we showed the percentage progress in the ingame menu (when you press escape) instead?

**Comment by SoScared** [comment] 2016-02-13 14:51
That would sounds fine.

**Comment by pchote** [comment] 2016-10-01 10:55
Duplicate of #12017.

**Closed by pchote** 2016-10-01 10:55 UTC
Labels: Feature, UI
