### ISSUE TITLE
AI dose not handle Plugbuilding like Componentdower 

### ISSUE THREAD

**Issue by Alfredlang1989** [OpenRA/OpenRA#18154] opened 2020-05-19 17:48 UTC
## Issue Summary

DESCRIPTION
The AI is unable to place things lige gasam, garock etc on component tower. 

## Reproduction
Allow AI to build Component Dower, the ai run in failture placelimit

## Expected behavior

AI get all exisiting building with compatible plugs, and set the upgrade on it.

I was free do write a working funktion with muss insertet in BaseBuliderQueumanager, to handle that:

		bool TickQueue(IBot bot, ProductionQueue queue)
		{
			var currentBuilding = queue.AllQueued().FirstOrDefault();

			// Waiting to build something
			if (currentBuilding == null && failCount < baseBuilder.Info.MaximumFailedPlacementAttempts)
			{
				var item = ChooseBuildingToBuild(queue);
				if (item == null)
					return false;

				bot.QueueOrder(Order.StartProduction(queue.Actor, item.Name, 1));
			}
			else if (currentBuilding != null && currentBuilding.Done)
			{
				// Production is complete
				// Choose the placement logic
				// HACK: HACK HACK HACK
				// TODO: Derive this from BuildingCommonNames instead
				var type = BuildingType.Building;
				CPos? location = null;
				string os = "PlaceBuilding";

				// Check if Building is a defense and if we should place it towards the enemy or not.

				///Check if Building is a plug for other Building
				if (world.Map.Rules.Actors[currentBuilding.Item].HasTraitInfo<PlugInfo>())
				{
					var pluginf = world.Map.Rules.Actors[currentBuilding.Item].TraitInfoOrDefault<PlugInfo>();
					var currentBuildings_with_plugports = world.ActorsHavingTrait<Pluggable>().Where(a => a.Owner == player);

					foreach (var building in currentBuildings_with_plugports)
					{
						foreach (var plug in building.TraitsImplementing<Pluggable>())
						{
							if (plug.AcceptsPlug(building, pluginf.Type))
							{
								os = "PlacePlug";
								location = building.Location + plug.Info.Offset;
								break;
							}
						}

						// Plug found..
						if (location != null)
						{
							break;
						}
					}

					// No Plug found, ... exit
					if (location == null)
					{
						return false;
					}
				}
				else
				{
				// Check if Building is a defense and if we should place it towards the enemy or not.
					if (world.Map.Rules.Actors[currentBuilding.Item].HasTraitInfo<AttackBaseInfo>() && world.LocalRandom.Next(100) < baseBuilder.Info.PlaceDefenseTowardsEnemyChance)
						type = BuildingType.Defense;
					else if (baseBuilder.Info.RefineryTypes.Contains(world.Map.Rules.Actors[currentBuilding.Item].Name))
						type = BuildingType.Refinery;

					location = ChooseBuildLocation(currentBuilding.Item, true, type);
				}

				if (location == null)
				{
					AIUtils.BotDebug("AI: {0} has nowhere to place {1}".F(player, currentBuilding.Item));
					bot.QueueOrder(Order.CancelProduction(queue.Actor, currentBuilding.Item, 1));
					failCount += failCount;

					// If we just reached the maximum fail count, cache the number of current structures
					if (failCount == baseBuilder.Info.MaximumFailedPlacementAttempts)
					{
						cachedBuildings = world.ActorsHavingTrait<Building>().Count(a => a.Owner == player);
						cachedBases = world.ActorsHavingTrait<BaseProvider>().Count(a => a.Owner == player);
					}
				}
				else
				{
					failCount = 0;

					bot.QueueOrder(new Order(os, player.PlayerActor, Target.FromCell(world, location.Value), false)
					{
						// Building to place
						TargetString = currentBuilding.Item,

						// Actor ID to associate the placement with
						ExtraData = queue.Actor.ActorID,
						SuppressVisualFeedback = true
					});

					return true;
				}
			}

			return true;
		}

EXPECTED BEHAVIOR

**Comment by abcdefg30** [comment] 2020-05-19 19:01
The issue looks like a duplicate of #8900.
Regarding the code/implementation: We are a bit hesitant to touch the AI at the moment, since we want to do some more fundamental reworks. In any case it is probably better if you submitted that patch as Pull Request, so that we can have a proper look at and discussion of your proposal.

**Closed as completed by abcdefg30** 2020-05-19 19:01 UTC
Labels: Bug, Tiberian Sun, AI

**Comment by Alfredlang1989** [comment] 2020-05-19 20:45
Ok, thanks... I never did that before..
