### ISSUE TITLE
D2K turret build animations are missing.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8378] opened 2015-06-04 20:43 UTC

**Comment by Mailaender** [comment] 2015-06-05 04:39
We could re-use the silo crumble animation here. The reason I didn't do that in the past was that the turret Z-Offset and appearance was glitchy. May be easy to solve though.

**Comment by MustaphaTR** [comment] 2015-06-05 05:25
Duplicate of #6578

Orginal Turret Build Anim is same as silo's one.

**Comment by penev92** [comment] 2015-06-05 07:36
Closing as duplicate.

**Closed by penev92** 2015-06-05 07:36 UTC
Labels: Dune 2000, Polish
