### ISSUE TITLE
(All games) Repair cursor does not allow L-click drag select

### ISSUE THREAD

**Issue by danbeyer** [OpenRA/OpenRA#12839] opened 2017-02-23 23:47 UTC
In the original C&C (not sure about D2K / Red Alert) you were able to left-click and drag select with the repair option selected with the repair cursor.  This is not present in this engine.  I tested it with D2K and C&C and Red Alert.  Instead, you need to right click to set the cursor back to default, then left-click drag.  It would be nice to have this left-click drag with the repair cursor implemented since it was present in the original versions.

Version: 20161019

**Comment by HenrytheSlav** [comment] 2017-02-24 09:10
Our controls are quite different from original, and to be honest what I would now expect from action you described is repairing a bulk of units, rather that ignoring the repair cursor and selecting them (Iif I understood correctly).

**Comment by danbeyer** [comment] 2017-02-24 19:48
Nope I was referring to normal click and drag selection with the repair cursor, not repairing bulk units.  So when you click and drag select with the repair cursor, it would act as a normal drag select box.  I just thought since this could be a quality of life issue and since it was also present in the original, I would bring it up.  It would save an extra click when wanting to quickly select units after repairing buildings.

**Comment by abcdefg30** [comment] 2020-08-29 19:09
Closing as duplicate of #17339.

**Closed by abcdefg30** 2020-08-29 19:09 UTC
Labels: Feature
