### ISSUE TITLE
Why not allow users to set the difficulty of the game in single player mode?

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#13043] opened 2017-04-01 06:24 UTC
Hi,

I do enjoy OpenRA, mostly because it's the closest open-source alternative I've found to [Outlive](https://en.wikipedia.org/wiki/Outlive), a proprietary futuristic RTS game from 2001. One thing I would like to suggest, however, is that you add difficulty modes (e.g., easy, medium, difficult) for how difficult single player games are. So that those of us that are poorer at strategy games can learn the ropes without getting totally annihilated by the opposing team (played by the computer). Likewise those of us that have found the existing game difficulty too easy can still get ourselves a challenge by the most difficult mode. 

Thanks for your time,
Brenton

**Comment by jaZzKCS** [comment] 2017-04-01 10:07
The single player campaign missions (most of them) do feature different difficulty levels to choose from in the mission select screen before game start. 
For the skirmish mode, the client uses an AI script that is not divided into different difficulties. Instead there are different bots to choose from (Turtle AI, Rush AI, etc...). Instead of a set difficulty rate for a certain AI (which does not exist), the different AI's are meant to provide you with different behaviors/difficulties. 

Try playing around with the different AIs. For example, Rush is more heads on compared to Turtle. Please do keep in mind that the AIs (at least at the moment) do not differ to greatly. Their buildup is mostly the same (except for Naval), but their unit behavior differs slightly.

Some ppl are working on the AI once in a while, instead of introducing difficulty levels for each AI (which would make things really difficult to implement) - it is planned to enhance the AIs further to make them more varied.

Ultimately it would be preferable to have more varied AI including e.g. "Easy AI, Medium Ai..." select-able.

**Comment by GraionDilach** [comment] 2017-04-01 10:14
Keep in mind that the reason the AI personalities act differently is mostly due to their unit compositions. As long as the current HackyAI is the sole skirmish AI without Lua expansions, you can't really create difficulty settings for it.

**Comment by fusion809** [comment] 2017-04-01 11:44
Difficulty settings would be helpful, especially for those that have only just started playing OpenRA that do not know how Rush, Turtle, Naval, *etc.* differ. As not everyone knows how Rush, Turtle, Naval, *etc.* differ, while every English-speaker would understand the difference between easy, medium, hard, *etc.* (e.g., if you want to make the difficulty setting even more customizable you could split easy into very easy and easy, medium into lower medium and upper medium, hard into mildly hard and very hard).

**Comment by StormWingDelta** [comment] 2017-04-05 20:54
The AI's have no specific difficulty settings they are more play styles than anything.  So their difficulty is based on how hard or easy they style with randomness is to deal with.

**Comment by obrakmann** [comment] 2017-04-08 13:49
Note that while the AI itself does not have any difficulty settings, you can still make it easier for you to fight it by tweaking some game options:

* Choose the lowest amount of starting cash. Do *not* make the mistake and choose the highest in the hopes that it will give you an advantage. The AI will make better use of the money and will annihilate you within minutes.
* Disable starting units
* Choose small maps.

**Comment by fusion809** [comment] 2017-04-08 14:20
Yeah I see your points, but being able to set difficulty of AIs would be a nice feature. But I suppose you's aren't so interested in adding it and I personally don't have the C# skills to do it myself, so well I suppose I could manage without this feature (as I am ATM).

**Comment by lovalmidas** [comment] 2017-04-12 11:15
Mission difficulty settings is the responsibility of the scripter, and can be introduced to a mission through a YAML setting. _Actual difficulty adjustments has to be made on **Lua**._

The use of a custom Hacky-AIs has been done based on some fan-made maps on the YAML level. Here I used a custom HackyAI to give the AI nuclear powers: http://resource.openra.net/maps/19901/

However, the ability for the difficulty settings to affect other _**YAML**_ settings (e.g. attachment of Hacky-AI to a map player) is probably not there, but this has to be tested.

**Comment by pchote** [comment] 2019-06-08 12:07
Closing as reverse duplicate of #16126.

**Closed by pchote** 2019-06-08 12:07 UTC
Labels: Idea/Wishlist
