### ISSUE TITLE
bleed branch can not enter any game and quit abnormal.

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13360] opened 2017-05-26 14:42 UTC
System: debian 8.8 i386
build on 2017 05 26, and build sucess, but running any game not sucessful since middle of this month. 
can enter the main menu and  the game lobby, but once start any game, it crashed.
This is the linux console log:

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1440x900
Using resolution: 1024x768
Using window scale 1.00
OpenGL version: 4.5.13399 Compatibility Profile Context 15.20.1046
Using default sound device
Internal mods:
	all: All mods (bleed-20170526)
	cnc: Tiberian Dawn (bleed-20170526)
	d2k: Dune 2000 (bleed-20170526)
	modcontent: Mod Content Manager (bleed-20170526)
	ra: Red Alert (bleed-20170526)
	ts: Tiberian Sun (bleed-20170526)
External mods:
	ra-bleed-20170422: Red Alert (bleed-20170422)
	ra-bleed-20170526: Red Alert (bleed-20170526)
	ts-bleed-20170422: Tiberian Sun (bleed-20170422)
Loading mod: ts
NAT discovery failed: 
Missing method System.Net.Sockets.UdpClient::AllowNatTraversal(bool) in assembly /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll, referenced in assembly /home/carlos/build/openra/openra/rix0rrr.BeaconLib.dll
Exception of type `System.Reflection.TargetInvocationException`: Exception has been thrown by the target of an invocation.
Inner
  Exception of type `System.TypeInitializationException`: An exception was thrown by the type initializer for OpenRA.Mods.Common.Server.MasterServerPinger
  Inner
    Exception of type `System.MissingMethodException`: Method not found: 'System.Net.Sockets.UdpClient.AllowNatTraversal'.
      at OpenRA.Mods.Common.Server.MasterServerPinger..cctor () [0x00000] in <filename unknown>:0 
    at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at OpenRA.ObjectCreator.CreateBasic (System.Type type) [0x00000] in <filename unknown>:0 
  at OpenRA.ObjectCreator.CreateObject[ServerTrait] (System.String className, System.Collections.Generic.Dictionary`2 args) [0x00000] in <filename unknown>:0 
  at OpenRA.ObjectCreator.CreateObject[ServerTrait] (System.String className) [0x00000] in <filename unknown>:0 
  at OpenRA.Server.Server..ctor (System.Net.IPEndPoint endpoint, OpenRA.ServerSettings settings, OpenRA.ModData modData, Boolean dedicated) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.CreateLocalServer (System.String map) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.StartSkirmishGame () [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.ButtonWidget.<ButtonWidget>m__B (MouseInput _) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput (MouseInput mi) [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (MouseInput mi) [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Ui.HandleInput (MouseInput mi) [0x00000] in <filename unknown>:0 
  at OpenRA.DefaultInputHandler+<OnMouseInput>c__AnonStorey2.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.DefaultInputHandler.OnMouseInput (MouseInput input) [0x00000] in <filename unknown>:0 
  at OpenRA.Platforms.Default.Sdl2Input.PumpInput (OpenRA.Platforms.Default.Sdl2GraphicsDevice device, IInputHandler inputHandler) [0x00000] in <filename unknown>:0 
  at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput (IInputHandler inputHandler) [0x00000] in <filename unknown>:0 
  at OpenRA.Renderer.EndFrame (IInputHandler inputHandler) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.RenderTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 

AL lib: (WW) FreeContext: (0x97d62b0) Deleting 32 Source(s)
AL lib: (WW) FreeDevice: (0x97e9b00) Deleting 2 Buffer(s)
exception inside UnhandledException handler: Stream does not support writing

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by reaperrr** [comment] 2017-05-26 15:14
We're aware of it and will fix it soon.

Closing as duplicate of #13348.

**Closed by reaperrr** 2017-05-26 15:14 UTC
