### ISSUE TITLE
TS Cursor cell selection inaccurate for tall terrain

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#19168] opened 2021-02-19 20:03 UTC
## Issue Summary
On Oasis Trouble, in the north-eastern starting point, whether a structure is allowed to be placed in some of the cells at the top of the map depends on the cursor's position within a given cell.

## Screenshots / Screen recordings / Replays
https://user-images.githubusercontent.com/3650108/108555321-3cee5500-72ed-11eb-8e04-82ab5d673fd0.mp4

**Comment by pizzaoverhead** [comment] 2021-02-19 20:55
Looking into this further, it affects general cursor use: Force firing on the ground can target the wrong cell. This only happens when the terrain height is 12, which most maps don't reach. It looks like it's trying to map the cursor as if the cell was at a lower height.

**Comment by PunkPun** [comment] 2023-05-02 14:33
Reverse duplicate of #20813

**Closed as not planned** 2023-05-02 14:33 UTC
Labels: Bug, Tiberian Sun
