### ISSUE TITLE
Suggestion rank up engineers after captureing something?

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#9912] opened 2015-11-06 22:49 UTC
I thought about that Engineers can't kill other units. So mayebe he gets promotions another way like captured some buildings. I didn't think about the other "not shooting units" like medics, mechanics, hijackers,... dogs :D

**Comment by obrakmann** [comment] 2015-11-06 23:02
Duplicate of #5095.

**Closed by obrakmann** 2015-11-06 23:02 UTC
