### ISSUE TITLE
Aircraft landing can be interrupted

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13880] opened 2017-08-21 03:06 UTC
Discovered while testing #13861

Press stop when the aircraft is near ground level.

https://youtu.be/gubzUATl_m4

Helicopter landing/take off can be interrupted too, in that case, they stay in some altitude between cruise height and ground level, where is given the stop order.

**Comment by MustaphaTR** [comment] 2017-08-21 05:35
Duplicate of #13301

**Closed** 2017-08-21 11:25 UTC
