### ISSUE TITLE
"Restart" option during a replay causes crash

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#12523] opened 2016-12-29 14:08 UTC
When I watch a replay and pause it + press "leave" I see the "restart" option. This causes the game to crash for me. But also probably it shouldnt be there (unless it means 'restart the replay', but if Im correct its a leftover from the normal menu when playing a mission/skirmish?).

**Comment by pchote** [comment] 2016-12-29 14:14
It means "restart the replay", and crashing is definitely not the normal or expected behaviour.

**Comment by noobmapmaker** [comment] 2016-12-30 10:25
Ah yeah, it seems to work for me when the replay is finished. But I was able to reproduce the issue though! My game crashes when I press "restart" while watching a replay. It does not crash when the replay is finished and I press "restart", then it just restarts as intended.

**Comment by rob-v** [comment] 2017-03-17 22:26
I can reproduce it also, not always, but often. Maybe not related, but I was able to crash it by changing replay speed several times and trying to restart.

[OpenRA.Replay.txt](https://github.com/OpenRA/OpenRA/files/851915/OpenRA.Replay.txt)

**Comment by pchote** [comment] 2018-08-13 08:40
Closing as a reverse-duplicate of #14104.

**Closed by pchote** 2018-08-13 08:40 UTC
Labels: Crash
