### ISSUE TITLE
Turn when idle trait for infantry

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14808] opened 2018-02-10 14:38 UTC
Think nobody remembered this, but in RA2 and TS infantry turned when they were idle (changed their current facing), idk if they did that back in td / ra, but I am certain tanks in d2k also aimed their turrets randomly when idle.

**Comment by Mailaender** [comment] 2018-02-11 09:51
Duplicate of https://github.com/OpenRA/OpenRA/issues/9161.

**Comment by GraionDilach** [comment] 2018-02-11 11:34
Uhm, no, not really, that one explicitly mentions turrets while this is about infantry.

**Comment by Mailaender** [comment] 2018-02-11 12:41
My bad.

**Comment by GraionDilach** [comment] 2019-12-02 23:41
@CDVoidwalker did this obne ages ago. https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/TurnOnIdle.cs

**Closed** 2020-05-25 11:07 UTC
Labels: Feature, Tiberian Sun

**Comment by Mailaender** [comment] 2020-05-25 14:32
Note: our implementation differs slightly now after review changes.
