### ISSUE TITLE
Crushing engineer capturing building does not abort capturing.

### ISSUE THREAD

**Issue by praetp** [OpenRA/OpenRA#16663] opened 2019-06-09 09:21 UTC
### Issue Summary
In the attached game replay you can see how comrat tries to capture spetsnaz84's construction yard (bottom right). The capturing engineer is crushed with an ore truck but the capturing does not abort. Although ownership of the building is not transferred to comrat, spetsnaz84 cannot place any buildings anymore (can still build though).

#### System Information
- **Operating System**: Ubuntu 18.04
- **OpenRA Version**: release-20190314
- **Mod:** Red Alert

- OpenRA Replays
Problem occurs after around 4:10.
[OpenRA-2019-06-09T090151Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/3269387/OpenRA-2019-06-09T090151Z.orarep.zip)

- Screenshots & Videos
![Schermafdruk op 2019-06-09 11-09-02](https://user-images.githubusercontent.com/3198728/59157305-af32ed80-8aa8-11e9-8b46-253dea593c94.png)
![Schermafdruk op 2019-06-09 11-09-10](https://user-images.githubusercontent.com/3198728/59157306-af32ed80-8aa8-11e9-8b21-df27ac610bcb.png)

**Comment by pchote** [comment] 2019-06-09 09:27
Closing as duplicate of #16505, which is fixed for the next release by #16556.

**Closed by pchote** 2019-06-09 09:27 UTC
