### ISSUE TITLE
Air units can land on top of ground units

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#10436] opened 2016-01-06 20:31 UTC
If you issue a command for a helicopter to land on a tile, then issue a command for a ground unit to move to the tile before the helicopter lands, or vice-versa, the units will both move to the same square and the helicopter will land with the unit stood on top of it. Please see link for a replay demonstrating this. This also works with the repair pad.

[Download air_bugs.orarep](https://www.dropbox.com/s/iv018izrxwkdo67/air_bugs.orarep?dl=0)

**Comment by abcdefg30** [comment] 2016-01-06 20:46
Duplicate of #4605 (also see #7537 and #6068).

**Closed by abcdefg30** 2016-01-06 20:46 UTC
