### ISSUE TITLE
TD Tiberium not harvestable in some games.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12939] opened 2017-03-09 05:01 UTC
In some games (perhaps maps) there will be a patch of tiberium that harvesters refuse to pick up.

https://www.dropbox.com/s/j73s2um2yj85kld/OpenRA-2017-03-09T034106Z.orarep?dl=0

Becomes more apparent at 6:00. Watch it at high speed at my base and you will see it. I even tried clicking on it with the harvesters and they go around it. I shot at it with my humvee thinking it was a stealth tank.

I also just noticed harvesters do drive over it.

**Comment by abcdefg30** [comment] 2017-03-09 08:32
Duplicate of #5547.

**Closed by abcdefg30** 2017-03-09 08:32 UTC
Labels: Bug
