### ISSUE TITLE
Counterintuitive lobby options behaviour when switching maps/servers.

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#6754] opened 2014-10-14 16:23 UTC
1.
if i load a map on my server , where the "default map options" are changed (without any input from myself)  , it wont give me a message in the chat window ... 

2.
when the "default map options" have been changed (without any input from myself) drop-zone map is a good example ... and i load  "haos ridge" with the basic map-options set ... then .... the map-options (check-box to be specific) wont change , so it stays on the "dropzone map options" ... and no message will pop up to give a hint 

this is a problem specially for dedicated servers , when the server has currently a drop-zone map loadet , admins change the map to something else ... but dont check the options ... and theres no message that anything has been changed ... once the game starts ... it will most likely result in a "RE" and players blame the Admin for changing the options without telling them ... (but he most likely didnt even know himself)

just so you know what i mean : 

download playtest 
create a server (or join a dedicated)
load map "haos ridge" (check options) 
load a"dropzone" map (check options) 
load map "haos ridge" again (check options and chat-window)

![map options](https://cloud.githubusercontent.com/assets/9139965/4632628/951e29e8-53bf-11e4-9ffd-a2b021e070d5.png)

I think the most interesting question here is ... "if" a dedicated server ... like hetzners for example ... "automatically" get maps from http://resource.openra.net/ ... 

and the "default rules" for maps have been overwritten (as in dropzone maps) .... 

does every new loadet map start with the drop-zone map options ?

**Comment by MicroJOo** [comment] 2015-10-27 18:23
this is still a quite serious issue in the current relase (20150919) 

ive made a map just couple days ago using this options switches : 

Options:
	Crates: False
	Fog: False
	Shroud: False
	AllyBuildRadius: False
	FragileAlliances: False
	StartingCash: 99
	TechLevel: Unrestricted
	ConfigurableStartingUnits: False
	ShortGame: False

and this completely overrides the defaults of the next loaded map 

![override](https://cloud.githubusercontent.com/assets/9139965/10768196/21679a20-7ce0-11e5-8584-a3b484a428f8.png)

**Comment by Micr0Bit** [comment] 2016-07-22 08:34
changing the map from @ScottNZ 's "Evacuation" to any other standard map ... will keep the options fucked up and it doesnt give any output by doing so

this is still present in todays bleed

**Comment by pchote** [comment] 2016-07-31 18:22
I can't reproduce with an in-game server or a locally-run dedicated server, but that's not too surprising because I specifically set up the feature to behave as expected.

Can you please provide specific steps to reproduce?

**Comment by pchote** [comment] 2016-07-31 18:31
Wait, hang on... this is an ancient issue that was fixed by #11364.  The recent discussion (and not checking the dates...) made me think the new lobby backend had regressed.

I still can't reproduce your Evacuation issue.  Please create a new issue with specific steps to reproduce that.

**Closed by pchote** 2016-07-31 18:31 UTC
Labels: Bug, UI
