### ISSUE TITLE
OpenRA crash window popup disappeared on Windows.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#13146] opened 2017-04-17 16:14 UTC

**Comment by pchote** [comment] 2017-04-17 16:28
We'll need a bit more info to go on here... is this a permanent change, or did it happen just once?

**Comment by GraionDilach** [comment] 2017-04-17 16:42
I believe this was caused by #12966.

I am launching OpenRA.Game.exe directly with an explicit Game.Mod parameter however at the moment, notsure if that's how it should be

**Comment by pchote** [comment] 2017-04-17 17:16
This is expected behaviour then.  The crash windows are provided by the OS specific launchers, and the Windows `openra.exe` launcher is now built only as part of the installer creation.  OpenRA.Game.exe doesn't have any crash dialog logic built in.

For dev versions your choices are either to run OpenRA.Game.exe directly and not have the crash dialog, or to use the `launch-game.cmd` scripts from the main repo (default mods) or the mod template (third party mods).  The mod template is currently a bit meh because we need all the mod chooser / package changes merged before we can finish most of the missing features.

**Closed by pchote** 2017-04-17 17:16 UTC

**Comment by GraionDilach** [comment] 2017-04-17 17:25
I see. Ofcourse the third option is to build OpenRA.exe manually. Thanks for the infos regardless.
