### ISSUE TITLE
WAV music issues.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#14153] opened 2017-10-08 13:57 UTC
Carried over from #13763.

On bleed, music ends up silent, but still playing and the next track will return to be played at the volume it supposed to.

@RoosterDragon with your current music branch, I'm getting a crash-during-loading with OpenAL Error 40963.

**Comment by GraionDilach** [comment] 2017-10-14 09:13
Hypnotic died in this run but I can't see anything out in the ordinary.

[music.log](https://github.com/OpenRA/OpenRA/files/1384536/music.log)

**Comment by RoosterDragon** [comment] 2017-10-18 19:28
Looks like more logging is the first order of business then. I'll have to think about what to add.

**Comment by RoosterDragon** [comment] 2018-03-29 19:25
@GraionDilach: Are you still able to reproduce this on current bleed?

**Comment by GraionDilach** [comment] 2018-03-29 20:50
Dropped the ball on AS for some months now, but I'll do some tests ASAP.

**Comment by GraionDilach** [comment] 2018-04-25 17:13
This bug is still happening but it's really hard to trigger these days, not as usual as it was when the ticket opened.

**Comment by RoosterDragon** [comment] 2018-04-26 18:32
From the logs:

```
2017-10-14T09:06:31.9623006Z Starting music track Hypnotic
2017-10-14T09:06:31.9628054Z Streaming task is about to load audio.
2017-10-14T09:06:32.0108349Z Reclaiming source for a completed OpenAlAsyncLoadSound
```

I wonder if as Hypnotic started, some race condition allowed the audio source for it to be reclaimed, hence the lack of audio?

I have added the source IDs into the logging, so we can see if that is the case (it could be a different ID is getting reclaimed, which is normal).

I can't repro this on my system, so you'll need to try the updated logging. Sorry I can't offer any better suggestions.

(Rebased the logging onto master, https://github.com/RoosterDragon/OpenRA/tree/sound-logging)

**Comment by GraionDilach** [comment] 2018-04-27 13:07
At this point I am really considering of creating some sort of a public and more straightforward testing environment because it didn't caught anything out of the ordinary either while the song was cut in the middle.

The sole thing I noticed out of interest was that when the game cuts the song itself during menu->game transition, the buffer is only reclaimed after the song would have ended on it's own anyway.

**Comment by GraionDilach** [comment] 2019-11-19 18:00
Note that considering I have seen this bug at one point during the RV streams, I think this happens when too many audio played at the same time and the game drops the music instead of a particular sound.

**Comment by dnqbob** [comment] 2020-01-18 10:55
>Note that considering I have seen this bug at one point during the RV streams, I think this happens when too many audio played at the same time and the game drops the music instead of a particular sound.

I also think so.

**Comment by Smittytron** [comment] 2021-10-02 16:15
Closing per: https://github.com/OpenRA/OpenRA/pull/19660#pullrequestreview-767063637

**Closed by Smittytron** 2021-10-02 16:15 UTC
Labels: Bug, Audio
