### ISSUE TITLE
Con yards overlap

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8281] opened 2015-05-28 19:00 UTC
![overlap](https://cloud.githubusercontent.com/assets/6599106/7868466/ea3e9e72-0584-11e5-94e9-6e40f63b5425.png)

on this map: https://www.dropbox.com/s/l51xgmsaa4ldf7x/timertest.7z

**Comment by abcdefg30** [comment] 2015-05-28 19:02
Duplicate of #6683.

**Closed by abcdefg30** 2015-05-28 19:02 UTC
