### ISSUE TITLE
Random seed for procedural generation

### ISSUE THREAD

**Issue by NarcolepticL1** [OpenRA/OpenRA#16605] opened 2019-05-27 23:06 UTC
### Issue Summary
I'm currently developing a singleplayer map (mission) for ra mod which uses Lua for procedural generation. The function which does this is triggered after x amount of seconds (1) at the start of a level. My problem is: Values returned via functions like Utils.Random always return the same exact value. For what I understand, the random seed is dependent on engine tick so it makes sense that the result is always the same. If that's not the case then this is a Bug. If not, is there another way to get random values at the very start of each game/level?

On other hand. I tried to 2 ways to call the procedural generation function and the "wall fill space" behavior of sandbags is missing in the first one.
1) Unit enters footprint trigger (which happens at the very start of level). Result:
![ScreenClip](https://user-images.githubusercontent.com/12752563/58441248-6ba2b180-80ae-11e9-80b2-fe9c084ec36f.png)

2) Triggers after a delay (1 Second). Result:
![image](https://user-images.githubusercontent.com/12752563/58441266-9f7dd700-80ae-11e9-823e-a9bc143e5e89.png)

The function called is the exact same. 

This is the LUA code I'm using:
```
Trigger.OnEnteredFootprint({triggerer_of_procedural.Location}, function(a, id)
	Trigger.RemoveFootprintTrigger(id)
	ProceduralInit(OutVec1.Location, 9, 9)
	ProceduralInit(OutVec2.Location, 3, 9)
	ProceduralInit(OutVec3.Location, 9, 3)
	ProceduralInit(OutVec4.Location, 9, 5)
	ProceduralInit(OutVec5.Location, 5, 9)
	ProceduralInit(OutVec6.Location, 5, 5)
	ProceduralInit(OutVec7.Location, 9, 9)
	ProceduralInit(OutVec8.Location, 11, 5)
	ProceduralInit(OutVec9.Location, 5, 11)
end)

--[[
Trigger.AfterDelay(DateTime.Seconds(1), function()
	ProceduralInit(OutVec1.Location, 9, 9)
	ProceduralInit(OutVec2.Location, 3, 9)
	ProceduralInit(OutVec3.Location, 9, 3)
	ProceduralInit(OutVec4.Location, 9, 5)
	ProceduralInit(OutVec5.Location, 5, 9)
	ProceduralInit(OutVec6.Location, 5, 5)
	ProceduralInit(OutVec7.Location, 9, 9)
	ProceduralInit(OutVec8.Location, 11, 5)
	ProceduralInit(OutVec9.Location, 5, 11)
end)
]]

ProceduralInit = function(pos, w, h)
	local area = (w * h) - 1
	local start_x = ( (w - 1) / 2) * -1
	local start_y = ( (h - 1 ) / 2)* -1
	local origin = CVec.New(start_x, start_y)
	CampInitialization(pos, area, origin, w)
end

CampInitialization = function(pos, area, origin, limit)
	local x_pos = 0
	local y_pos = 0
	for i = 0, area, 1 do
		local start = origin
		local iterator = CVec.New(x_pos, y_pos)
		local wall = {"sbag"}
		local wall_pos = {}
		local defence = Utils.Random({"pbox", "gun"})
		local defence_pos = {}
		local unit = Utils.Random({"jeep", "arty", "1tnk", "2tnk"})
		local unit_pos = Utils.Random({"e1", "e3", "jeep", "arty", "1tnk", "2tnk"})
		if 
		(x_pos == 0 and y_pos == 0) or (x_pos == 1 and y_pos == 0) or
		(x_pos == 2 and y_pos == 0) or (x_pos == 6 and y_pos == 0) or
		(x_pos == 7 and y_pos == 0) or (x_pos == 8 and y_pos == 0) or
		(x_pos == 0 and y_pos == 1) or (x_pos == 8 and y_pos == 1) or
		(x_pos == 0 and y_pos == 2) or (x_pos == 8 and y_pos == 2) or
		(x_pos == 0 and y_pos == 6) or (x_pos == 8 and y_pos == 6) or
		(x_pos == 0 and y_pos == 7) or (x_pos == 8 and y_pos == 7) or
		(x_pos == 0 and y_pos == 8) or (x_pos == 1 and y_pos == 8) or
		(x_pos == 2 and y_pos == 8) or (x_pos == 6 and y_pos == 8) or
		(x_pos == 7 and y_pos == 8) or (x_pos == 8 and y_pos == 8)
		then
			Actor.Create("sbag", true, { Owner = enemy, Location = (pos + start + iterator)  })
		end
		if 
		(x_pos == 3 and y_pos == 0) or (x_pos == 5 and y_pos == 0) or
		(x_pos == 0 and y_pos == 3) or (x_pos == 8 and y_pos == 3) or
		(x_pos == 0 and y_pos == 5) or (x_pos == 8 and y_pos == 5) or
		(x_pos == 3 and y_pos == 8) or (x_pos == 5 and y_pos == 8)
		then
			Actor.Create(defence, true, { Owner = enemy, Location = (pos + start + iterator)  })
		end
		x_pos = x_pos + 1
		if x_pos == limit then
			x_pos = 0
			y_pos = y_pos + 1
		end
	end
end
```

#### System Information
- **Operating System:** [Windows 10]
- **.NET / Mono Version:** [No idea]
- **OpenRA Version:** [e.g. release-20190314]
- **Mod:** [Red Alert]
#

**Comment by pchote** [comment] 2019-05-27 23:11
I wouldn't be surprised if this was related to the issue where the random faction selection isn't very random. These are both natural consequences of the RNG not being initialized properly.

**Comment by NarcolepticL1** [comment] 2019-05-28 01:14
Making more tests, the RNG is indeed different each time I start the level from the mission selection menu, but if I restart the level (without leaving the in-game scene) the random seed is the same.

**Comment by pchote** [comment] 2019-06-08 12:09
Ok, that makes this a duplicate of #11190 so closing.

**Closed by pchote** 2019-06-08 12:09 UTC
