### ISSUE TITLE
Connection failed to 127.0.0.1 when performance drops

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#15143] opened 2018-05-17 12:09 UTC
OpenRA-20180307 C&C installed normally on my laptop, using Sabayon.

After a long game with 4 teams, 2 players per team, all AI except for myself, near the end of the game I got a message:
```text
Connection Failed
Could not connect to 127.0.0.1:45817
Server is not responding
```
The game was responding and I could finish it, only keyboard shortcuts stopped working.

![screenshot_20180517_140455](https://user-images.githubusercontent.com/5844619/40176442-b186e194-59db-11e8-855a-9d8432d56bda.png)

**Comment by Beep6581** [comment] 2018-05-17 12:10
P.S. I'm gold. The pink AI was HAL 9001 and as you can see it was pretty useless, never attacked and slowed the game down.

**Comment by Mailaender** [comment] 2018-06-08 14:35
Do you have a personal firewall or other software which could interfere running in the background?

**Comment by Beep6581** [comment] 2018-06-08 15:18
@Mailaender 
```text
$ systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
```
Its status didn't change during the game as far as I know.

**Comment by Steeex** [comment] 2018-06-09 13:18
I experienced this too multiple times on Windows and it had nothing to do with the network (despite the message shown when you encounter this).

To reproduce :
- Create a local game with many AIs on a tortuous map to let the AIs continuously  build and train units which will be accumulated at multiple locations
- Start the game and let it slow down, slow down, slooow... dooown..., slo... ooo... o... ...
- BOOM this message pops up

@Beep6581 You can enable the Performance graph in the Settings

**Comment by Beep6581** [comment] 2018-06-09 13:45
@Steeex exactly the same here. As can be seen in my screenshot, my AI ally built many units, didn't move or attack using any of them, and just slowed the game down.

**Comment by Mailaender** [comment] 2022-01-19 10:18
Possible reverse duplicate of https://github.com/OpenRA/OpenRA/issues/19849 which has logs.

**Closed by Mailaender** 2022-01-19 10:18 UTC
Labels: Bug, Performance, Networking

**Comment by anvilvapre** [comment] 2022-03-09 20:41
Isn't it odd that it tries to setup a connection? Since the game is already in progress - for a long time - there already should be a connection in progress.
