### ISSUE TITLE
Actors don't auto target frozen actors

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#10004] opened 2015-11-15 13:41 UTC
Currently on bleed, prep-1512 (playtest-20151114) and release-20150919.
You can order them to attack, and they will, but they won't autotarget.
##

**Comment by Mailaender** [comment] 2016-01-24 21:47
Is this a duplicate of https://github.com/OpenRA/OpenRA/issues/10361?

**Comment by penev92** [comment] 2016-01-29 09:22
[09:03:57]	< penev|m> Well the context is different
[09:04:06]	< penev|m> One is about being unable to attack
[09:04:31]	< penev|m> The other is about AutoTarget dismissing frozen actors as potential targets 
[09:05:13]	< pchote> I assume it was dismissing them because they were unable to attack
[09:05:54]	< penev|m> Don't think so from what I recall
[09:06:22]	< penev|m> Like I said on the ticket, they attack if ordered

**Comment by obrakmann** [comment] 2016-03-25 21:59
Found out that [this](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs#L88) returns false for frozen actors, which is obviously wrong.

**Comment by RoosterDragon** [comment] 2016-03-29 23:11
This isn't a regression - it's always been like this as best I can tell. I assume the fix we need is to disentangle the targeting and rendering decisions from each other - but there will probably be some side effects we'll have to fix if we do that.

**Closed** 2018-12-17 21:19 UTC
Labels: Bug
