### ISSUE TITLE
Bridge damage state can be seen through fog with explored map

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#11598] opened 2016-07-08 14:01 UTC
Perhaps another prerequisite to #11531? With explored map, you can see when bridges are destroyed, take damage and repaired both on the minimap and through the fog

On release

**Comment by Mailaender** [comment] 2016-07-08 20:20
Duplicate of https://github.com/OpenRA/OpenRA/issues/3654.

**Closed by Mailaender** 2016-07-08 20:20 UTC
Labels: Bug
