### ISSUE TITLE
Out of sync crash relating to owner change

### ISSUE THREAD

**Issue by darkademic** [OpenRA/OpenRA#19930] opened 2022-02-06 15:56 UTC
As far as I can tell this happens due to this commit: https://github.com/OpenRA/OpenRA/commit/6421c1751546ad275e4e00546a78046761c45ce2

CA has a few weapons that change the target actor to Neutral. It doesn't crash immediately, but after a few minutes, an out of sync crash occurs which only causes one client to crash (so only that client has a sync log generated).

Seems to happen due to owner changes more broadly (as it also happened after I removed weapons that change actors to Neutral, I think due to mind control units still being present, which also use ChangeOwner()).

Example of the exception:

```OpenRA engine version {DEV_VERSION}
Red Alert mod version {DEV_VERSION}
on map 4070a9a020bcd8a5f1f85cb18eb4c2afda47398b (Mass Confliction by Nuke'm Bro.).
Date: 2022-02-05 18:51:55Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 6.0.1
Exception of type `System.InvalidOperationException`: Out of sync in frame 1561.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame) in J:\ora\OpenRA.Game\Network\OrderManager.cs:line 77
   at OpenRA.Network.OrderManager.ReceiveSync(ValueTuple`3 sync) in J:\ora\OpenRA.Game\Network\OrderManager.cs:line 155
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in J:\ora\OpenRA.Game\Network\Connection.cs:line 309
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in J:\ora\OpenRA.Game\Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in J:\ora\OpenRA.Game\Sync.cs:line 205
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in J:\ora\OpenRA.Game\Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in J:\ora\OpenRA.Game\Game.cs:line 623
   at OpenRA.Game.LogicTick() in J:\ora\OpenRA.Game\Game.cs:line 638
   at OpenRA.Game.Loop() in J:\ora\OpenRA.Game\Game.cs:line 803
   at OpenRA.Game.Run() in J:\ora\OpenRA.Game\Game.cs:line 856
   at OpenRA.Game.InitializeAndRun(String[] args) in J:\ora\OpenRA.Game\Game.cs:line 294
   at OpenRA.Launcher.Program.Main(String[] args) in J:\ora\OpenRA.Launcher\Program.cs:line 32
```

Orignally replicated by adding this class: https://github.com/darkademic/CAmod/blob/master/OpenRA.Mods.CA/Warheads/ChangeOwnerToNeutralWarhead.cs

Then changing M1Carbine to use this warhead.

```salt
	Warhead@DriverKill: ChangeOwnerToNeutral
		ValidTargets: Vehicle
		ValidRelationships: Enemy
		Range: 0c511
```

But have since tried with the standard ChangeOwnerWarhead and that also replicates the issue.

```salt
	Warhead@c: ChangeOwner
		Duration: 0
		ValidRelationships: Enemy
		Range: 0c511
		ValidTargets: Vehicle
```

**Comment by dnqbob** [comment] 2022-02-10 05:36
Hi, man. There is a few questions here I want to ask due to we met a very similar issue in RV&SP:

1. Does this crash always happen in mutiplayer? 
(becuase in our case, we confirm that it is related with AI player using owner change weapon -- mindcontrol, it is fine when there is no AI player in multiplayer)

2. I notice the description in your crash report is very similar to our snyc crash #19834. Therefore, there is a question, did you have any custom change on server code as we did?
> but after a few minutes, an out of sync crash occurs which only causes one client to crash (so only that client has a sync log generated)

3. Besides "weapons that change the target actor to Neutral", is there any other weapon, especially mind control in CA, will result in this crash?

**Comment by dnqbob** [comment] 2022-02-10 05:56
@pchote
According to our tests here, there is some usecase in OpenRA may reproduce this bug:

OpenRA(D2K)
2 players VS 2 AI
Player uses owner change rocket on enemy AI units & enemy AI use owner change rocket on players' units
wait for crash

OpenRA(RA)
2 players VS 2 AI
Player uses theif on enemy AI vehicles
wait for crash

**Comment by darkademic** [comment] 2022-02-10 09:01
> Does this crash always happen in mutiplayer?

I've only been able to replicate it by double spectating AI games. I did think this was an example of it happening without AI: https://discord.com/channels/376842723086303232/408252043107631114/939780980154204160 but that could just've been due to dev test version mismatch.

> Did you have any custom change on server code as we did?

No custom server code. I replicated on RA bleed only using the changes described.

> Besides "weapons that change the target actor to Neutral", is there any other weapon, especially mind control in CA, will result in this crash?

It happened in a game after I'd removed everything that changes actors to Neutral, so yea, I'm guessing it was mind control in that case.

**Comment by dnqbob** [comment] 2022-02-10 09:09
We got a stable reproduction usecase on SP:
1. Have a game on dedicated server
2. 2 Human Players VS 2 AI (AI use owner-change weapon related actor)
3. Play and wait for crash. Both player pay the attention to owner change weapon used by AI

**Comment by dnqbob** [comment] 2022-02-10 09:10
> No custom server code. I replicated on RA bleed only using the changes described.

So I guess it is not the server code change we apply result in this bug @MustaphaTR

**Comment by dnqbob** [comment] 2022-02-10 09:18
I and [MustaphaTR](https://github.com/MustaphaTR) are very confused by this bug especially it lacks of useful sync report from both players. I check the AI module I modified again and again, while MustaphaTR also check the Mind Control carefully but we failed to find anything that is problematic to sync. I thought it was due to our modification, but now I think it should be a universal bug on OpenRA mods.

The key point is how to reproduce it on OpenRA default mods. I think the most possible one is the D2k owner change rocket

**Comment by dnqbob** [comment] 2022-02-10 09:32
> As far as I can tell this happens due to this commit: https://github.com/OpenRA/OpenRA/commit/6421c1751546ad275e4e00546a78046761c45ce2

Are you sure it is this one? I think I can try some reproduction with this commit with my test usecase

**Comment by darkademic** [comment] 2022-02-10 09:35
> Are you sure it is this one? I think I can try some reproduction with this commit with my test usecase

99% sure. Checking out the commit before that one and running a test game resulted in no crashes. Checking out that commit (or any after it) and doing the same resulted in the crash. Replicated on the default RA mod with ChangeOwnerToNeutral warhead added, but also crashes just with the ChangeOwner warhead.

**Comment by dnqbob** [comment] 2022-02-10 13:17
I think this issue shoud have a tag of "Crash" here @Mailaender

**Comment by dnqbob** [comment] 2022-04-21 06:09
Ping
Is anyone here looking into this crash?

**Comment by Mailaender** [comment] 2022-04-21 09:30
https://github.com/OpenRA/OpenRA/pull/19958 was merged over a week ago, so you should get proper sync reports to compare.

**Comment by darkademic** [comment] 2022-04-22 09:27
Have a pair of sync logs resulting from this crash, but don't know if there's anything out of the ordinary in them. http://www.darkademic.co.uk/uploads/synclogs1.zip

Happened quite quickly in one test, but then in two subsequent tests I couldn't get the crash to happen at all with hundreds of units firing owner changing weapons.

**Comment by dnqbob** [comment] 2022-04-22 09:51
> Have a pair of sync logs resulting from this crash, but don't know if there's anything out of the ordinary in them. http://www.darkademic.co.uk/uploads/synclogs1.zip

Something interesting here
![image](https://user-images.githubusercontent.com/13763394/164682855-ff69faed-16c6-4494-89b6-f51beae2f1a0.png)

**Comment by Mailaender** [comment] 2022-04-22 11:34
https://gist.github.com/Mailaender/71d2101f4141e77371f9a45dd4ba8b66/revisions here is the full diff. I presume the owner change is not carried out on all machines so `AutoTarget` differs as the units attack different things in the next frame.

**Comment by dnqbob** [comment] 2022-04-22 14:32
Even the shared random is different. They should always be the same right?

**Comment by Mailaender** [comment] 2022-04-22 14:41
Yes, it means that random values were taken unequally in this case most probably from
https://github.com/OpenRA/OpenRA/blob/0e7ad4342578b420ab35c5921f51ee1cef9da618/OpenRA.Mods.Common/Traits/AutoTarget.cs#L291
which does it to distribute the load over multiple ticks.

**Comment by darkademic** [comment] 2022-04-22 14:52
Replicated on RA bleed. Changed the weapon of Medium Tank to include a ChangeOwner warhead. Doesn't crash on every attempt, and can take a few minutes when it does. Have attached another pair of sync logs as well as a map for testing.

http://www.darkademic.co.uk/uploads/synclogs2.zip
http://www.darkademic.co.uk/uploads/testdesyncmap.zip

**Comment by Mailaender** [comment] 2022-04-22 16:41
Looks similar https://gist.github.com/Mailaender/ae4e55c2e438779f7942a677e0953810/revisions

**Comment by abcdefg30** [comment] 2022-06-24 14:32
I filed #20084 which hopefully resolves this. Would be good if you could test it yourself too so we are sure it works.

**Comment by darkademic** [comment] 2022-06-24 15:40
Tried it before the update and still got the desync, but latest change appears to have fixed it. Huzzah!

**Closed as completed** 2022-06-25 16:18 UTC
Labels: Crash, Bug
