### ISSUE TITLE
Extreme Lag in Multiplayer

### ISSUE THREAD

**Issue by GrayHatter** [OpenRA/OpenRA#13183] opened 2017-04-23 03:55 UTC
If someone has a poor network connection, or is running the game on a toaster. The game lags and becomes unenjoyable, and in some cases unplayable. 

Regardless of the abilities of any users computer. The game shouldn't lag for the other players.

**Comment by anjew175** [comment] 2017-04-23 06:47
Is there a way to implement a latency option?
Like if you are playing with someone who has a bad but stable connection, there could be a higher latency to the server for both players so it plays more smoothly. Apparently Crystallized Doom already has a function like this

**Comment by GraionDilach** [comment] 2017-04-23 06:53
There is already a latency option, assigned to the game speeds. This latency works like collecting all orders between key frames and fire them up in the said key frame.

What CD experiments with - and seems to be working well for them - is to double this latency on all gamespeeds IIRC. Mind you that this affects the overall micro potential.

**Comment by anjew175** [comment] 2017-04-23 06:59
>Mind you that this affects the overall micro potential.
I haven't tried out CD's latency option but if it maintains the game speed then I feel this is a better solution since putting the game on slow also boosts the ability to micro

**Comment by GraionDilach** [comment] 2017-04-23 06:59
@GrayHatter Every game slows down to the slowest player, that's not a bug. Your implication would result with other players outrunning the slowest which immediately would lead to a desync.

**Comment by GrayHatter** [comment] 2017-04-23 07:19
First person shooters don't have this bug. And while I admit it's been years and years; I don't remember ever seeing this bug in the original RA or RA2.

**Comment by GraionDilach** [comment] 2017-04-23 07:31
I can assure you, as one who was causing lag for years before gained access to fiber, RA2 definitely slows down to the slowest player, and it's especially notable with people with terrible internet.

FPSes can drop frames because there's a much more limited amount of actions a player can do in an FPS, and these can even be predicted in a way, also losing an action doesn't mean the world state starts snowballing onwards. The same logic can't apply to an RTS.

**Comment by jaZzKCS** [comment] 2017-04-23 09:09
It is understandable that complains like these pop up more often now, seeing as the new release has a tad higher system requirements compared to last release. I cannot pin-point to exactly what is causing it, but I can definitely say that - after trying the new release on three different systems on which I knew the exact performance of ORA from last release - either the new release is not running as effective as the last one or the system requirements have gone up. There is a definitive difference in performance of the last two releases. The newest release is MUCH beefier.

**Comment by GraionDilach** [comment] 2017-04-23 09:17
Does that performance drop affects all mods? I can imagine the new shroud-related logics eating perf on RA and D2k but TD is left alone by them.

**Comment by pchote** [comment] 2017-04-23 09:21
The lockstep networking model is used by pretty much every RTS game ever built, it is absolutely standard because it is the only reasonable technical approach that these kind of games can use.

According to somebody claiming to be a former EA developer who worked on the 2013 C&C reboot, using a FPS-style server-client networking model was [one of the big failings that contributed to the bad gameplay that lead to its cancellation](https://www.reddit.com/r/AskReddit/comments/65pd76/if_you_could_bring_back_any_game_from_your/dgd3o7j/):
> Speaking of engineering. God damn. The game was an authoritative client-server model, where the server would model the game, and broadcast game state to the clients, which merely rendered it. Great for stopping cheating, but due to performance issues, the game's logical frame rate was 4FPS (literally 250ms per tick). And that didn't really account for latency. So you'd order a unit to go in one direction, and then very noticeably later, it would finally obey that order. This slow gameplay frame rate also made things like accurate crushing, and other effects (like high rate-of-fire weapons like gatts and quads) almost impossible.

This ticket is going in at least two different directions, so I'm going to close it now.
If anybody has specific information about performance problems then please create a new ticket, one per problem.

**Closed by pchote** 2017-04-23 09:21 UTC
Labels: Performance

**Comment by GrayHatter** [comment] 2017-04-23 17:17
It seems like a mistake to close this issue outright, at least without a definitive answer as to why it's `wontfix` or `invalid`. I may be mistaken in my interpretation of your response, but either it's a known bug, and it's not fixable. Or it's not really a bug at all, and the lag in multiplayer in intentional. Because I agree the latter is hyperbolic, the former must be the reason.

That's a very interesting quote, and more than enough reason to abandon my original suggestion, IMO it's not enough to close this issue yet. 

I'd like to work through this issue a bit more, is there any other issues, or pages, or lines of code that would give me a better understanding of how and why the game would go out of sync? I'd like too look into it and offer some real suggestions to reduce or minimize the apparent lag for players who's system and network is capable of handling multiplayer.

**Comment by Mailaender** [comment] 2017-04-24 05:52
People need to either upgrade their connection and computers or avoid large games with many units and players/spectators. To help improve the performance on weak machines, upload `perf.log` files and replays of games where it went noticeable bad.
