### ISSUE TITLE
AttackGarrisoned-related bug

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#11552] opened 2016-07-01 01:53 UTC
I cannot come up with a better title, if you have one feel free to change the title.
I was trying to reproduce #11454 when I came across this.

4d90361b8bcd9193f372756acfd7f33d05b0bde2

![ra-11454](https://cloud.githubusercontent.com/assets/4861023/16509613/6b40d81e-3f04-11e6-9895-e73cc17df177.gif)

**Comment by obrakmann** [comment] 2016-07-03 17:08
Looks like an instance of #9404, where the visual position doesn't match the real position.

**Comment by pchote** [comment] 2016-07-03 17:10
Does this only happen when you use the "alt to enter nearby transports" feature?  I think its more likely that feature isn't handling the enter-actor behaviour properly.

**Comment by obrakmann** [comment] 2016-07-04 12:19
It does indeed only happen after alt-entering, and is a duplicate of #11454.

**Closed by obrakmann** 2016-07-04 12:19 UTC
Labels: Bug
