### ISSUE TITLE
Tanya get crushed under vehicles

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7730] opened 2015-03-24 15:01 UTC
Tanya enters the Tanks cell and he can't shot at his own cell and randomly move to the cell she was in before entering the tanks cell and they move at the same time to this cell and she gets squashed as the tank blowup simultaneously.

https://www.youtube.com/watch?v=kqOhOyWOftM&t=11m55s
https://www.youtube.com/watch?v=HYTR8r_SzEA&t=0m40s
##

**Comment by MicroJOo** [comment] 2015-03-25 04:36
what ?

**Comment by SilverlineDev** [comment] 2015-03-25 15:26
Sounds like they're saying that sometimes a tank and Tanya will enter a cell at the same time and Tanya will blow up the tank while the tank crushes her.

**Comment by penev92** [comment] 2015-03-25 17:13
Sounds realistic enough.

**Comment by cjshmyr** [comment] 2015-03-25 17:32
@penev92 vague comment, are you OK with this behavior? It seems stupid

**Comment by penev92** [comment] 2015-03-25 18:56
You are basically telling her "run under that tank and slap a chunk of explosive to it". I am OK with her getting crushed during that.

**Comment by MicroJOo** [comment] 2015-03-26 09:14
the question here imo is ... why the hell did someone revive the abilty to "c4" vehicles for tanya ? ... for the red alert missions ? its ridiculous op , thats why it got removed from multiplayer in the first place

**Comment by Snurre86** [comment] 2015-04-24 19:43
still happens on easy in playtest 2015-04-18.

**Comment by Snurre86** [comment] 2015-05-04 11:52
Still happens in release 2015-04-24 on easy but have not been able to reproduce on hard.

**Comment by Snurre86** [comment] 2015-05-15 22:43
Fixed in release 2015-04-24

**Comment by Snurre86** [comment] 2015-06-02 19:39
Well it is back

**Comment by reaperrr** [comment] 2017-02-02 19:36
Reverse duplicate of #9792.

**Closed by reaperrr** 2017-02-02 19:36 UTC
Labels: Balancing, Red Alert
