### ISSUE TITLE
TD: AI using super weapons through fog of war?

### ISSUE THREAD

**Issue by ymladenov** [OpenRA/OpenRA#13458] opened 2017-06-05 14:50 UTC
Release-20150527
AI: Cabal

I can accept that tiberium fields being blindly attacked with air strikes, but having an ion cannon launched at my army's staging point, in front of my base... Or is it that advanced that it can estimate that? 
Seen such AI behavior in other RTS games as well, so I thought this is not the intended behavior.

Thank you for your work!

**Comment by abcdefg30** [comment] 2017-06-06 12:05
Duplicate of #7659. Thanks for the report, though. :)

**Closed by abcdefg30** 2017-06-06 12:05 UTC
Labels: AI, Bug
