### ISSUE TITLE
Aircraft fly endlessly in a circle when ordered to attack inside own turning radius

### ISSUE THREAD

**Issue by Gishten** [OpenRA/OpenRA#7083] opened 2014-12-07 09:08 UTC
Steps to reproduce:
1. Use either MiG or Yak that's in flight 
2a. Ctrl + Right click on ground really close\* to where the aircraft is flying
2b. Right click on enemy unit that is really close to where the aircraft is flying
*Doesn't have to be the same grid, inside the aircraft's turning raidus seems to be enough.

Both 2a and 2b can be used to reproduce the bug. Expected behavior would be that the aircraft enters an attack run pattern directly, which it does after successfully firing otherwise.  
##

**Comment by abcdefg30** [comment] 2015-12-08 19:45
It seems like this returned https://github.com/OpenRA/OpenRA/pull/7088#issuecomment-162576460.

**Comment by pi99y** [comment] 2016-01-07 09:22
I am unable to reproduce this on current release. Might already be fixed, but it was always a bit tricky to pull off so I can't be certain.

**Comment by pchote** [comment] 2016-07-09 00:39
This has been fixed on bleed (hint: if you pause the game it becomes much easier to select a target).

**Comment by pi99y** [comment] 2016-10-06 13:51
This can still/again happen in current playtest (20161001) and bleed.

I tested with Yaks. It's a bit tricky but doable.
Order it real close to traget, when Yak starts turning (since it reached the ordered destination) click on the enemy unit. Yak will endlessly loop around the unit showing "red targer line" if you select the yak.

At the end of the replay: north east, pik yak attacking/looping around blue light tank 
https://filebin.net/xn4uht6snu06l4vb/OpenRA-2016-10-06T133002Z.zip

**Comment by pi99y** [comment] 2016-10-14 08:31
While tricky to reproduce when you want it to, it happens to me suprizingly frequent during games.

Maybe "polish" isn't a fair label since it affects gameplay: Your aircraft doesn't shoot at the enemy unit and retreat but circles around it endlessly, leaving itself open to any AA threats.

**Comment by matjaeck** [comment] 2018-08-13 17:12
I am unable to reproduce this in playtest-20180729.

**Comment by FrameLimiter** [comment] 2018-08-13 17:55
If you queue move orders adjacent to the target, then queue an attack order it'll get stuck idling above the unit. This is a bit different from the bug reported in the ticket though, as the plane remains idle even if the target moves out from under it.

**Comment by matjaeck** [comment] 2018-11-25 15:58
This frequently happens in the latest release.

**Comment by reaperrr** [comment] 2018-11-25 17:06
@pchote It's quite possible that will be fixed by my PRs (possibly even through #15848).

**Comment by reaperrr** [comment] 2019-02-08 18:41
Closed by #16054.

**Closed by reaperrr** 2019-02-08 18:41 UTC
Labels: Bug, Red Alert
