### ISSUE TITLE
[TD request] Display a visual warning of an air strike or a nuke (optional)

### ISSUE THREAD

**Issue by gdavegdave** [OpenRA/OpenRA#14027] opened 2017-09-15 19:42 UTC
Various players (myself included) have reported not hearing EVA warn of an airstrike or a nuke in TD, preventing the player from taking evasive action. I suspect that occurs when a lot is going on and the audio channels get 'maxed out' (I seem to experience it during a battle, though air strikes are often called then anyway). This is not new, having been experienced over a good few releases.

I suggest we have the option of displaying a visual (textual) warning when an enemy airstrike is called or an enemy nuke is launched. That would also help those playing without sound (either by choice, necessity, physical impairment, or when the sound bugs out - as happens to me on occasion). 

If adopted, perhaps it could be on by default (to help newer players), but with the option to turn it off in the menu.

**Comment by MustaphaTR** [comment] 2017-09-16 06:09
Related to #12954.

**Comment by dsimmons87** [comment] 2017-12-29 00:04
I've noticed the same issue in TD. Sometimes the Airstrike notification sound just doesn't play.

If there were to be a textual warning, should this show in the chat, like when you select all units, or somewhere else?

**Comment by penev92** [comment] 2017-12-29 12:41
```
[14:16] <+penev> is #14027 something we'd want?
[14:17] <+pchote> if we can do it properly, yes
[14:18] <+pchote> (not just for airstrike or nuke)
[14:18] <+penev> ofc
[14:18] <+penev> so... chat notification or what?
[14:19] <+pchote> the original idea was to have a dedicate place on the screen for them, like other games
[14:19] <+pchote> but chat notifications would work failing that
```
So with a proper implementation yes, it's worth following up on ;)
If you have questions you can join us on IRC ([Freenode's web client](http://webchat.freenode.net/?channels=openra) is the easiest way to do that).

**Comment by pchote** [comment] 2017-12-29 12:43
Note that #12954 and #12954 have important context here.

Closing as duplicate of #12954.

**Closed by pchote** 2017-12-29 12:43 UTC
Labels: Balancing, Idea/Wishlist, Tiberian Dawn, UI
