### ISSUE TITLE
sounds in lobby

### ISSUE THREAD

**Issue by m0nk33** [OpenRA/OpenRA#3519] opened 2013-07-03 13:41 UTC
Sometimes the sound stops working (the "ping" sound when messages are send, or someone enters the game)

I think the sounds should vary. Another sound for "someone enters the game" as chat sounds. 

Before the game starts something like a 5 sec countdown would be nice too (with sounds). 
##

**Comment by abcdefg30** [comment] 2020-05-10 15:33
Closing as reverse duplicate of #14032. (That one has a better title and I'm not aware of any issues with sound disappearing in the latest release.)

**Closed by abcdefg30** 2020-05-10 15:33 UTC
Labels: Audio, Feature, UI
