### ISSUE TITLE
AI doesn't deploy replacement MCV

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#11305] opened 2016-05-16 20:41 UTC
After destroying the AI's conyard in bleed d2k, its remaining two MCVs continued to path across the map from one buildable area to the next, without ever deploying either MCV. The cause of this appears to be that ActorExtensionsForMove.IsMoving doesn't detect MovePart moves (MoveFirstHalf and MoveSecondHalf), resulting in new location orders regularly being appended to the units' queues. While debugging, there were just under 2000 Move orders queued for one of the MCVs.

**Comment by GraionDilach** [comment] 2016-05-16 21:31
This sounds like the reason I also tend to see that it takes 4 minutes at least for my AI to deploy it's mobile war factories.

**Comment by obrakmann** [comment] 2016-05-17 05:33
Thanks for the report, but reaperrr was quicker :)

Duplicate of #11304.

**Comment by reaperrr** [comment] 2016-06-04 14:41
Reopening this because accoding to my tests, fixing the `IsMove` check alone won't be enough, `HackyAI.FindAndDeployBackupMcv` is simply crap.

**Comment by pchote** [comment] 2016-10-07 20:06
Closing as a reverse-duplicate of #12159.

**Closed by pchote** 2016-10-07 20:06 UTC
Labels: AI, Bug
