### ISSUE TITLE
Allow to specify the unit stance for buildings

### ISSUE THREAD

**Issue by MVBarros** [OpenRA/OpenRA#18594] opened 2020-09-06 19:15 UTC
## Motivation

There is currently no way to define the default stance for new units.  This can be tedious as new units may be created with a stance that is not ideal for the current situation, and the player as to manually set it.

## Proposed solution

Allowing to define a stance to production buildings. Units that come out of these buildings will inherit this stance. This was present in CnC 3, but not the original games. It can be a great quality of life and user experience improvement.

**Comment by deleted-user-1** [comment] 2020-09-06 21:28
Duplicate of #13817?

**Closed as completed** 2020-09-07 08:55 UTC
Labels: Idea/Wishlist
