### ISSUE TITLE
Able to do units formation and handle their moves

### ISSUE THREAD

**Issue by bioinfornatics** [OpenRA/OpenRA#18338] opened 2020-06-28 13:23 UTC
## Motivation

Currently when we click to move units all those units try to reach exactly the `X,Y` coordinates. This imply lot of micro managing to move units by units at the right position.

Allowing units formation will improve considerably the strategy and tactics.

## Proposed solution

Allow some basic units formations: triangle, rectangle and square
The formations is applied to a group of units (ctrl+1, ctrl+2 …)

In order to be simple we could hard code that a formation as at max 3 rows  and units are puts in `y` columns on 3 rows

Those formations could be enhanced with the following rules:
 - support units such medic, technician, engineer are put at last row
 - shortest range unit first rows followed by medium and high range units
## Side effects

When  crossing small area such a bridge a temporary unit formation (a rectangle with a tiny width) should be applied.

## Alternative

Allow to place units while right mouse button is hold. With mouse button we can draw a path to put units. Once the mouse button is released the drown path length is divide by the number of units in order to distribute units along the given path.

**Comment by tovl** [comment] 2020-06-28 18:18
See also #4813, #3880 and #3241.

It might be worth reviving #16883 at some point.

**Comment by abcdefg30** [comment] 2020-06-28 19:08
Closing as duplicate of the other listed issues then.

**Closed as completed by abcdefg30** 2020-06-28 19:08 UTC
Labels: Idea/Wishlist, UI, Pathfinding
