### ISSUE TITLE
Plane shadows culled from view incorrectly

### ISSUE THREAD

**Issue by sinf** [OpenRA/OpenRA#8111] opened 2015-05-08 16:40 UTC
Plane shadows are culled near the top edge of view if the plane itself is culled which is obviously not correct. Tested with D2k carryalls and RA yaks on current release.
![pop20](https://cloud.githubusercontent.com/assets/9487531/7540918/ffa48662-f5b9-11e4-9a51-9bccd44b824d.gif)

**Comment by pchote** [comment] 2015-05-08 17:54
Duplicate of #6987.

**Closed by pchote** 2015-05-08 17:54 UTC

**Comment by sinf** [comment] 2015-05-08 18:29
Sorry. Didn't cross my mind to search for anything like "bib" (wtf).
