### ISSUE TITLE
Groups of helicopters do not reload when sent to helipad

### ISSUE THREAD

**Issue by kerryhall** [OpenRA/OpenRA#13753] opened 2017-07-29 21:40 UTC
Hello,

After running out of ammo, I try to send a group of helicopters to a helipad to reload. The entire group will return to the helipad, but only one of them will reload. The rest will idle. Expected behavior: each helicopter takes turns using the helipad to reload.

Thanks!

**Comment by pchote** [comment] 2017-07-29 22:48
Which mod and version is this?

**Comment by kerryhall** [comment] 2017-07-30 02:08
My apologies, release-20170527 and Red Alert. In Command and Conquer, the helicopters just reload in mid air.

**Comment by abcdefg30** [comment] 2017-08-07 09:25
I couldn't reproduce this on the latest playtest, so I assume this was fixed? Thanks for the report anyway. ^^

**Comment by netnazgul** [comment] 2017-08-07 15:10
Can confirm it in the playtest https://youtu.be/JgPacZdobJ0 (squitchy sound due to mic enabled)
Either several (2-3) helicopters reload in queue or only one, but not the whole group. Looks like the group tries to go to the previously stated move point instead of reloading.

**Comment by abcdefg30** [comment] 2017-08-07 15:39
Yes, they're moving to their previously given move point, but will then go to reload once the managed to get there. Unfortunately the block each other, indeed. The reload order should probably cancel the previous move order.

**Comment by matjaeck** [comment] 2019-05-28 22:19
Helicopters block each other on queued move orders, too. For a real fix we would need a refactor of the aircraft repulsion and related path-finding code I assume.

**Comment by tovl** [comment] 2019-05-29 08:31
The aircraft repulsion logic is fundamentally broken. Luckily, I've finally got some progress in getting to the root causes of why it is broken. I will take on revising the aircraft steering behaviour, but don't expect a PR for a while.

**Comment by PunkPun** [comment] 2022-07-11 17:48
This was fixed via tovl's aircraft refector

**Closed by PunkPun** 2022-07-11 17:48 UTC
Labels: Bug
