### ISSUE TITLE
Add Runtime MiniYAML editor.

### ISSUE THREAD

**Issue by KAmaia** [OpenRA/OpenRA#15015] opened 2018-04-03 06:35 UTC
To simplify and streamline the modding process of OpenRA an in game miniYAML editor would be extremely useful, as one could launch the game, create a new unit/structure/whatever, click a save and test button, and be taken immediately to a test map that would allow for the testing of said unit. 

This would be way more convenient than opening [vim|emacs|notepad++] modifying the rules.yaml file in question, launching the game and waiting for all content to load, creating a new game, setting the debug options, waiting for the map to load, exiting the game, and repeating the process until the unit suits your taste.  

This could also make the editing process simpler if the ui was designed in such a way that like with the map selection you could simply add traits to your {thing} and set their appropriate values, rather than typing out the yaml long hand.  For example, the ui could have the core features of a {thing} such as name sequence etc at the top, and then simply an 'add trait' button that would add a dropdown from which you could select the desired trait, which in turn would spawn an indented 'add attribute' button to allow you to add and modify the attributes of that trait.

**Comment by CatGirls420-NerevarII** [comment] 2018-04-10 18:13
Funny, I planned on making this a while ago but I can't devote time to that. It would be a very useful tool.

**Comment by pchote** [comment] 2018-04-10 19:56
Closing as duplicate of #14506.  An in-game editor is not feasible to build or maintain, so bindings for an external editor is the best that anyone can hope for.

**Closed by pchote** 2018-04-10 19:56 UTC
Labels: Idea/Wishlist
