### ISSUE TITLE
Sell Vehicles Via Service Depot...

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#12410] opened 2016-11-21 21:13 UTC
The idea of being able to sell certain vehicles via service depot; like in the original RA would be a sensible implementation.

Say you don't want a vehicle or built one to many of a unit. Select said vehicle: command move unit to the Service Depot: sell vehicle with "Sell" cursor.

**Comment by abcdefg30** [comment] 2016-11-21 21:18
Duplicate of #3798.

**Closed by abcdefg30** 2016-11-21 21:18 UTC
