### ISSUE TITLE
Infantry sometimes do not attack-move when on Defend stance

### ISSUE THREAD

**Issue by vietman391** [OpenRA/OpenRA#9504] opened 2015-10-01 18:53 UTC
My rocket soldiers often do this in engagements when tanks get out of range. After they find a target after the a-move, they do not attack their target once it comes out of range. This did not happen in the previous release.

**Comment by obrakmann** [comment] 2015-10-01 18:57
Duplicate of #8184

**Closed by obrakmann** 2015-10-01 18:57 UTC
