### ISSUE TITLE
AA guns can't shoot at aircraft outside the map

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#10481] opened 2016-01-11 03:10 UTC
So I was just playing a 1v1 on singles and noticed that if I kept my aircraft at the very top of the map and moved them to engage a nuclear silo also placed at the top of the map the AA guns defending it couldn't hit my yaks because they'd move outside of the map.

**Comment by Phrohdoh** [comment] 2016-01-11 03:22
Perhaps [this type of logic](https://github.com/OpenRA/OpenRA/blob/652f38ff66367e177a99e24faf48d185f8efa113/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs#L349) should be handled by child classes.

**Comment by r34ch** [comment] 2016-01-12 19:15
Duplicate of #9552

**Comment by abcdefg30** [comment] 2016-01-12 19:59
Closing as duplicate of #9552 then.

**Closed by abcdefg30** 2016-01-12 19:59 UTC
Labels: Bug
