### ISSUE TITLE
TD Stealth Tanks

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11055] opened 2016-04-05 20:11 UTC
In TD playtest version 20160403 Tanks and other turreted vehicles can lock onto Stealth tanks. Even though they are in stealth mode once the turret is locked they can fire on them.

Shown in replay example at 12:04 to 12:16.

https://www.dropbox.com/s/n46hvd1ag7a5hkx/OpenRA-2016-04-05T194601Z.orarep?dl=0

**Comment by LipkeGu** [comment] 2016-04-16 19:56
TS has also this problem...

Reproduce case:

1. start a TS skirmish
2. enable devmode (/all) and build 3 or 5 stealth tanks and order them 8 - 10 cells away from the enemy base
4. wait ... when the enemy is starting the scan for enemy units "in the near" it will directly order the attack squad to the position of your placed stealth tanks
5. order the stealth tanks to another position.... 10 cells away... the same squad will run to that new position..

you can enforce a "Cat and mice" game... with this "issue" when you are funny!.

**Comment by AoAGeneral** [comment] 2016-04-17 07:51
If this is happening in TS it might be happening with the Phase Transports in RA as well.

**Comment by MustaphaTR** [comment] 2016-04-17 08:01
Or Stealth Raiders in D2K.

**Comment by GraionDilach** [comment] 2016-04-17 10:07
Isn't this a duplicate of #11046? In that case, the next playtest will have this fixed through #11105.

**Comment by AoAGeneral** [comment] 2016-04-17 23:48
Doesnt look like it. In that ticket its saying they couldnt be attacked. The Stealth Tanks can be attacked even while its cloaked so long as the turret is locked on them. Requires no stealth detection.

**Closed** 2016-04-21 11:02 UTC
Labels: Bug
