### ISSUE TITLE
A Balance Proposal For Tiberian Dawn

### ISSUE THREAD

**Issue by ZxGanon** [OpenRA/OpenRA#16624] opened 2019-05-31 22:39 UTC
My proposal has been made to get at least some changes going for Tiberian Dawn. It has been stagnating over the last year and it just makes me sad. I have talked with almost all active Tbierian Dawn players in 2018 about these changes. Now in 2019 I could only reach out to only few of them so I hope this proposal reaches the core community and they leave some feedback.

I still hope these changes will be taken over because they are fixing some really odd scenarios in TD.

**Construction Yard:**
**- Cost from 2500$ to 3000$**
To make it consistent with the MCV cost change I planned.
**- BaseProvider: Cooldown: 75 --> 0**
With the removal of the BaseProvider cooldown you will no longer have a penalty upon placing a structure. I guess people feared that defence structure spamm might become a thing in TD but seriously you cannot win a game by turtelling your base. TD is a very fast paced game based arround building units and striking the opponent where it hurts most. Such a penalty does not only hurt in teamgames (when you plant a structure in the BaseBuildingRange of your mates Conyard which causes him to wait until he can finally place his structure) also hurts people playing in 1v1 where fast players (like me) screw themselves by placing the less important structure first than having to wait to place (for instance) a refinery or another factory. Also due to defences taking longer to build there is no way that defence spam becomes a big issue in teamgames (except the AGT but that tower is just overperforming and would need an extra PR to handle). This change is overdue and finally has to be made (most people even believe it is a bug). 

**MCV:**
**- Decreased cost from $4000 to $3000**
**- Buildtime should remain at 60 seconds though**
Due to the fact that the $4000 MCV is just impossible to build (especially in 1v1) without dying to counter attacks the cost of the MCV has been set to $3000. Back then when $2000 MCV was a horrible meta I can understand people being scared by trying to change it´s cost but I assure you the $3000 MCV has been tested already last year and it was still not possible to go for a second MCV early on (till 7th minute mark) without dying to an immediate response from your opponent that might even use 2xFactory/Airstrip at that point.
**- Removed Repair Facility as the requirement (still requires Radar)**
Even the removal of the Repair Facility hasn´t improved the strategy to rush out an MCV but people are now encouraged to rebuild their MCV when they lost their first one.

**Refinery:**
**- Storage capacity from $700 to $1000**
This has been an annoying state of the refinery for a long time. I have asked a lot of TD players last year and now in 2019 and they still hate the fact that the refinery almost stores nothing. This results in having very weird economy behaviour´s to not be able to collect enough money to ship a mid game strategy more proper without having to be forced to build a Tiberium Silo or an extra refinery you might not even need (they also cost 40 energy which slows down and limits build orders). Even being forced to build Tiberium Silo´s in general is just a a poor design decision. 

**Commando:**
**- Cost from $2000 to $1500**
Commando´s have been overnerfed after it´s assumption it may overperform when turning it into a high ranged infantry sniper. Also due to it´s now equivalent cost of 20 Minigunners it is just better to spam out 20 Minigunners rather than one Commando. Sure it can plant C4 and level entire bases but this is very hard to pull of and is quite a heavy investment and also one Guard Tower shuts down this strategy very effectively. With 1500$ it might see use outside of dropping it into the opponents base or to clean up Chemical Troopers (even though 15 Minigunners do a better job at killing them as well).

**Comment by JMegaTank** [comment] 2019-06-01 00:44
**These are all good ideas into improving the game play in OpenRA Tiberian Dawn**

The MCV is currently at $3500 each and should be lowered to $3000 each.
MCV Build time is currently 00:45 sec - and could be lowered to 00:40 seconds. 

Refinery Storage capacity from $700 to $1000 work for me because you will not have to build a silo in the early game which cost $300 and you might go low power. " Will help new players in TD"

Commando cost from $2000 to $1500 is a yes from me.

Removing the Baseprovider cool down helps in team games when trying to places a building in your base when next to you Ally when you place a structure in the base building range of your Ally Construction yard which causes him to wait until he can finally places A structure. When places building at the same time. Needs to be fixed.

Yes!

And make the Nod Airstrip deliver the units quicker from the supply aircraft so than it is evenly timed with the GDI Weapons factory.

And 1 more thing make the Nod Obelisk of Light more Stronger and Faster Laser Zapping with increased range. As I feel GDI is stronger in game because the Obelisk of Light requires Temple of Nod but the GDI Advanced Guard Tower is just Communications centre.

Currently Obelisk is $1500 each 
Currently Advanced Guard Tower is $1000 each "and it attacks air units" Just 1 more thing to point out.

**Comment by AoAGeneral** [comment] 2019-06-01 06:06
MCV is currently 3500. Not 4000 as MegaTank specified.

Refinery - People build more then one refinery which turns to a 1400 limit. The silo used to hold less and was increased to 3000. Even just one silo helps.

Silo - The silo itself can be built early in the game but if a player finds himself filling up on income with a "Silos needed" EVA then they are not spending fast enough. The idea that a silo can be built mid to late game helps to aleviate this.

The repair facility is another notch to the tech tree. Players should have one built anyways for vehicle repairs.

Commando - A few Commandos can eliminate squads of infantry. A high price point yes, but also useful in a late game scenario. More so when Nod starts using chem trooper compositions. 

Construction Yard - Agreed. But unaware of any structure capable of building a construction yard. (Except in debug mode)

Base Provider - No comment.

The MCV price you mentioned out tells me you haven't really had a great look into the game itself lately. I suggest doing some feedback sessions in the forums. Have you also spoken to Mesacer? There are plans for the A10, SAM, and AGT right now.

@JMegaTank Nod Obelisk already one shots every unit in the game (Except medium tanks and mammoth tanks). Increasing the speed means tanks will die faster.

The AGT has already had testing in reducing its damage. Decreasing the damage spread on the AGT has put more survivability on armies.

Airstrip cargo plans has been in talks and been brought up a few times. I still think its beneficial for the current plane speed to prevent buggy/bike spams from happening. However, lets look into it and see what happens in making adjustments.

The airstrike fiasco -=++=-

The changes to the airstrike has made AA much more powerful. (More so structures). With the changes in place this has greatly reduced the over all effective of the A10s which in the long run will not be able to fly to the center of the map and kill armies easily. Its been adjusted and changed (Ideas from Mesacer btw) making the airstrikes more viable for base raids or defensive strikes. With the directional airstrikes working and changes to the A10s speed has made some large overhauls to many of the complains players have made. In short::::

Airstrikes take longer to reach the center of the map. (Harder to snipe armies)

Airstrikes now come quicker at the edges of the maps. (Good for last ditch defenses or base strikes.)

Airstrike A10 planes now fly slower. (Allows SAM, AGT, MSAMs, and to some degree E3 able to snipe planes)

Correct. The A10 planes is being tested as being shootable. So far it seems promising but there are plans to test this. The build that Mesacer and the devs have helped with is being tested for stability right now. (IE: Nod is broken because Cargo planes fly in circles instead of delivering units haha!)

**Comment by anjew175** [comment] 2019-06-01 07:31
Some of these seem like reasonable quality of life changes.

**Construction Yard:
Cost from 2500$ to 3000$**
Not sure what this changes, isnt the ability to build a construction yard only in debug mode? Also it appears to be 3500, the same price as the current MCV (because otherwise the sell value would be less than the current 1750, i imagine)

**MCV:
- Decreased cost from $4000 to $3000
- Buildtime should remain at 60 seconds though
- Removed Repair Facility as the requirement (still requires Radar)**

As pointed out the current build time is less than 60 seconds.
Ive given up my stance on MCV cost changes, this change could be fine but it would be nice to play it a bit more, personally.
Also dont see the harm in removing the requirement for repair facility, it wasnt a big problem originally, like you said, i think it was implemented to slow down mcv production (which is already slow).

**Refinery:
- Storage capacity from $700 to $1000**
The primary problem with the current storage capacity on the refinery is the fact it cant handle a full load of blue even while producing. It also doesnt drop off money if that money is going to exceed the current hold limit. Blue does a drop of $1200 so even this capacity wouldnt hold it but it might be possible to spend $200 in the time its completely dropped.

**Commando:
- Cost from $2000 to $1500**
Id be curious to see how this goes but there may be other options to make the unit more viable. 

Its interesting to compare its impact (in infantry killing) to the amount of rifleman it costs because it can hardly stand up to vsing that many. An unmicro'd commando will succumb to 8 rifleman. It requires a lot of hard work to actually keep it alive.  You would think adding another commando into the mix would help but if they are firing in unison they end up overkilling one unit at a time. It appears to work perfectly fine against its worth of chemical troopers but a quick change over in production to mass infantry could easily overwhelm the commandos. I think something needs to be done but the price point wont fix the actual problem of it being underwhelm (except in the backlines).

**Comment by ZxGanon** [comment] 2019-06-01 08:50
Apologies for some facts have been stated incorrect in my first post of course the current cost of the MCV and Conyard are $3500 not $4000. But the Buildtime of 60 seconds is still correct.

Anjew´s argument with blue tiberium actually delivering $1200 is a fair point to maybe even increasing the refinery storage yet again. So Id like to update my proposal in a following post.

**Comment by ZxGanon** [comment] 2019-06-01 09:01
**Construction Yard:**
**- Cost from 2500$ to 3000$**
**- BaseProvider: Cooldown: 75 --> 0**

**MCV:**
**- Decreased cost from $4000 to $3000**
**- Buildtime should remain at 60 seconds though**
**- Removed Repair Facility as the requirement (still requires Radar)**

**Refinery:**
**- Storage capacity from $700 to $1200**
Following Anjew´s interesting idea of increasing the storage to $1200. It would be having the same storage capacity as a Harvesters dropping blue Tiberium value of $1200.

**Commando:**
**- Cost from $2000 to $1500**

The explanations to all the changes (except the new proposed Refinery storage) are mentioned in my first post.

Edit: The Construction Yard cost has to be in line with the cost of the MCV because it would be odd that they both share different values resulting in a different sell value.

**Comment by AoAGeneral** [comment] 2019-06-01 10:17
Anjew:

If there is an issue with Commandos besides the price point discussion then its something I haven't heard yet. If you can specify further about it? 

The Commando is a mixed role unit. Standing on its own it can take out a few infantry but will succumb to an infantry army. If you mix them with tanks they can kill the E3 from range and other infantry that would make this army more dangerous.

You could also mix in some other infantry units with a few Commandos to make this more lethal.

To add points of the possible underwhelming state, Commandos require two shots to kill another Commando unranked. For firing in unison on same targets the only work around to this is have them scatter so their shots end up being spaced out.

The refineries blue dump is more understandable. Is the main issue of silos being built from the get go a power issue? Is a fix to remove power requirement of the silo from 10 to 0?

**Comment by ZxGanon** [comment] 2019-06-01 15:59
No it is the same as the requirement for RF on MCV:
Why forcing people to build something that is just a tool and not just let the players decide if they need these tools?

Enforcing ppl to build such buildings is no good game design.

**Comment by AoAGeneral** [comment] 2019-06-02 02:52
Negative on both enforcing people and the low storage.

The low storage on refineries was done to nerf quick bike build methods.

People don't have to build repair pads. If they don't then they don't get to repair their units or a MCV. Much like people aren't forced to build a command center. They don't have too, they just won't get the higher tech.

**Comment by Bain222** [comment] 2019-06-17 16:04
My biggest issues is with the mammoth tanks, I've got to say they are hugely over preforming, there's no way to combat them, as a nod player, you use to be able to use chems, the problem is that, the new forcing without attack moving, means you can use them to kill chems, without the chem troppers being able to get to them, I feel the best way to nerf the mammoth, would just be to set them back to the old system, so they only fire, when you attack move, this has been done in other mods, such as SP, with units, so I know this is something that could be done.

I also feel that the commando is a under used unit, because of the price pool, to use them effectively, you need to micro them, and even then, a AS can just crush two of them, which costs 4k atm. I understand what anjew is saying, about even a price reduction would not benefit them much, but all things considered I don't see how that would harm them in anyway, and if no one has any better suggestions, then I would think the price reduction from, 2k to 1.5 would be a good idea.

as for the SD, I think that it should be speed up a little more, that way it would influence people to use them more often, at this point (I've tried in a few games) it's not worth building them, unless you want a mcv, but no one builds mcv, because they are not viable. A speed increase would just mean players have to micro there units more, and I think this could add a viable strategy to the game, considering that vehicles in TD play such a big role.

**Comment by AoAGeneral** [comment] 2019-06-17 23:15
Im currently working on trying to combat an error with garrisonable GTs. Its an older idea but giving Guard Towers and Gun Turrets to GDI and Nod specific means I can buff the Gun Turret to combat the Mammoth Tanks a bit more on the defense side. More so in team games.

When the firing on the move was implemented I had mixed feeling about it due to tanks and vehicles able to withstand attacks better and the Mammoth vs Chems is one such problem.

Im all for changing the mammoth tanks to the old style where you need to use attack move or are unable to do move attack but might be some inconsistency in the game itself if other vehicles can do it but mammoths can't.

While im still working on the GT and Gun Turret stuff im gonna be releasing a sort of testing map. It will have increased Nod cargo plane speeds just to see what happens and reducing the silos power to 0. With this request ill increase the SD speed a little to and see what happens.

**Comment by Bain222** [comment] 2019-06-18 16:35
I feel as if a buff to the streath tank would be a great counter to the mammoths while also making them a really fun unit to use, I've been trying to use them for a few games now, this would not only be a way for the nod player to be able to beat mammoths, but also would not need much of a buff, I think a buff to health and fire power, would make these a really fun unit to use, because in there current state, they are a bit meh.

**Comment by AoAGeneral** [comment] 2019-06-18 20:53
How much of a HP buff and firepower buff? Their firepower right now kills buildings and medium tanks rather well as it is.

Normally the current state of the Stealth Tanks is at a good spot. But with the changes to attacking while on the move made units with turrets stronger and those lacking it a little weaker. Im leaning more to giving STanks a little rope on the HP side and see what happens in testing.

I don't want to see STanks start devestating armor armies leaving the player with a "Welp. That was fun.." that has that mixed with MRLS/Arty. Mainly, just don't want them soaking to much damage from certain unit types.

**Comment by Bain222** [comment] 2019-06-20 05:22
Stanks have hardly any role in the game atm, using the hp is going to do hardly anything, this unit requires a lot of micro to use probably, the Dmg and hp suggestion, is more of a way, for the unit to be able to fight mammoths, while not being able to kill them head on, it would make them a good support unit vs them. It's more of a stealth bike atm rather then a tank. 

Lower commando price to 1.2k
Gives players the ability to use a really fun unit, that requires micro, no one was moaning when they were 1k I'm not sure why they even got nerdfed, these are high tech units they should be powerful, while giving gdi players a fun way to kill nod tech statures it's just another viable option for the player to use, again they require a huge amount of micro, and could be really fun. 

Stanks I've already spoke about, however just consider what I said about the commando same rule stands here.

Mammoth tank, I honestly think if you gave the Stank a increase in Dmg and Hp, these would be a lot less op, that said I they might be the only unit that's made in a gdi mirror, just something to consider. 

Chems seem fine to me. 

Nuke amazing, Fucking shits on the RA one.

IC I'm unsure about, I feel as if the time could be upped a little, that said I don't know how much.

**Comment by AoAGeneral** [comment] 2019-06-20 07:08
Mammoth Tanks were being brought into a spot where it became issues for Nod to defend against them. Im unaware of the effects artillery would have in the back lines or if other players would pitch in. But an increase in STanks damage would help the defense strategy a bit more.

Im jut solely saying im worried about their damaging being to high in destroying things way to quickly for players to react too. Will try an increase in their damage and HP but not sure by how much yet in testing. When I do unit tests I do numbers vs numbers and one on one unit tests to see damages and play in a micro orientation/reaction.

1.2k? Hasn't their been suggestions for 1.5k? The Commandos were nerfed due to large quantities being produced and killing infantry off. Being that they are 1k its worth was cheap in compared to chem troopers. The price was brought to 2k to prevent this.

I can meet half way in the "Social Experiment" and do 1.3k to see what happens.

The super powers I don't want to touch at this time until the A10 fixtures/additions are in the game/playtest.

**Comment by AoAGeneral** [comment] 2019-06-23 23:08
I have linked a list of map changes here: https://forum.openra.net/viewtopic.php?f=82&t=17430&p=310437#p310437

**Comment by BeanBnZ** [comment] 2019-06-26 14:38
I formally object to all of these suggestions by ZxGanon with the sole exception of the Commando price reduction (for testing purposes). Zxganon with all due respect is not an active member the community, has a history with regards to diminishing existing playerbases, and would change the games fundamental charms making it unrecognisable from its current form if given the chance.

I'm sure the reasons to be sighted for not being an active player will be that the game has poor balance, but this is easily challenged. 

Please be very careful before considering drastic changes to this timeless classic, as history over the last few years has proven, its the core players that keep this game alive. Do not be hasty to listen to new radicals promising the earth, as they often move from place to place inciting issues and division, causing havoc, and then moving on to the next group of victims.

**Comment by tovl** [comment] 2019-06-26 19:37
> But with the changes to attacking while on the move made units with turrets stronger and those lacking it a little weaker.

Just a heads up related to this: The proposed engine changes in #16696 would make it possible to have non-turreted units that can attack while moving and also to have turreted units that need to stop to attack. This could be relevant for the mammoth tank versus stealth tank balance discussion.

**Comment by anjew175** [comment] 2019-06-27 04:46
> I formally object to all of these suggestions by ZxGanon with the sole exception of the Commando price reduction (for testing purposes). 
> 
> Custom build times are just terrible, why this is still being debated is beyond reason.
> 
> Please be very careful before considering drastic changes to this timeless classic, as history over the last few years has proven, its the core players that keep this game alive. Do not be hasty to listen to new radicals promising the earth, as they often move from place to place inciting issues and division, causing havoc, and then moving on to the next group of victims.

None of these changes are drastic or, from what i can see, change the gameplay in a large manner other than the commando change (not saying its a bad change). The irony is that a lot of these changes were in the game previously, prior to being changed. 

Im surprised you dont find the inability of a harvester to offload blue (even while producing) a negative thing considering it never used to be like. From what I can gather, it was implemented in order to slow down bike rushes apparently but it does not do its intended function. It is still just as easy to pull off an effective bike rush in the same amount of time. It was implemented in #12536

Also repair facility, prior to the change, has never been a prerequisite of building an MCV, it was implemented for the purpose of making the MCV harder to get (and encouraging repair pad building). In the original all you needed was the faction tech centre. I believe this method was chosen because its how its done in the RA mod. Its was implemented in #10552

Also which custom build times? From what I can tell, the mod is already riddled with custom build times.
I looked back at a few of the lines and some of its unrelated to presented findings. You would be surprised what units have custom build times.
eg. The custom build time on LT. #12536 was advertised as "Light Tank price reduced from 700 to 650." but it also came with the change of "BuildDuration: 1020 BuildDurationModifier: 40" which only effectively increased the build time by 1 seond.

**Comment by BeanBnZ** [comment] 2019-06-27 05:15
I wouldn't object to testing this,

Making more custom build times just because there are already some minor ones is not a good plan in my opinion, we will end up with Frankenstein's Monster of a game.

But more importantly we need to set up a small council and change the way things are implemented, we have alot of committed players who have alot of different ideas, this can be done with votes and proper arbitration. At the moment its a shout fest, and who has the strongest personality, Zxganon cannon be allowed to be in control, if he does RIPTD.

**Comment by AoAGeneral** [comment] 2019-06-28 07:17
@anjew175 

#12536 Not exactly sure what you mean here. Are you mentioning mainly about the refinery holding/silo changes? Harvester hold count was never adjusted. - The ref changes as mentioned in that ticket itself, was to prevent ref selling and producing harvesters rather quickly with no repercussions. Since one refinery held 2000 you can stay alive with a refinery for a long time without an economy cap.

Correct on the MCV being Temple of Nod and Adv. Com needed for the original. Not so much in ORA. In which common build orders were power > ref > factory > MCV + power > barracks OR ref. This was already much faster then the original and adding a repair depot allowed not only a slight stalling but scouting to pick up "I see a service depot. Possible quick expansion?" Just adds more to the guessing games and more so if players weren't intending on quick MCV builds.

**Comment by anjew175** [comment] 2019-06-29 16:00
@AoAGeneral 

Im not talking about harvester hold count, im talking about the lack of refinery storage to handle a harvester offloading a full blue drop in the early game.

You mention just earlier:
> The low storage on refineries was done to nerf quick bike build methods.

I dont believe it has had that impact.

**Comment by AoAGeneral** [comment] 2019-06-30 03:33
Still somewhat possible. But harder to do. You can pull it off in the beginning but its harder to recover from it if you fail in the attacks. Compared to before its much easier to recover from if it fails.

In terms of harvester unloads and etc I prefer GDave's response back in 2017 where if the silo/ref isn't a value hold number but an amount it would mean that green and blue can be unloaded fully at least once before needing a silo. This however for it to work is a known issue as there are other problems.

See this ticket number:

#12943

**Comment by ZxGanon** [comment] 2019-07-14 09:03
Well Beans still most of my proposed changes did find interest and have been taken over (Commando change is even better than mine which is interesting).

There is even a change to the Techstructure capturing system which is surprising.

If the BaseProvider: Cooldown: 75 --> 0 get´s adjusted it would be amazing.

Also TD is heavily modified and alienated to the original already.
Almost all unit´s have customg buildtimes which becomes very confusing when diving into the game. Especially Defence Structures got there very own modifier which may stop tower spam in team games but kinda ruins anti snowball strategies in 1v1 and 2v2.

**Comment by pchote** [comment] 2019-07-16 09:08
The window for getting changes into the playtest is rapidly closing, and as far as I can tell there are still no concrete plans to have any changes merged for this.

**Comment by BeanBnZ** [comment] 2019-07-16 09:30
With regards to Balance Council, we are taking a serious and long term approach towards preservation of the game and crucially the community that keeps it alive. Due to this the process of debate and votes for testing within the Council, we are unable to submit suggested changes at this time. We are working through things in a democratic way and therefore due to time constraints, proper testing, Balance Council voting procedures, we hope that fully tested and properly processed changes will be submitted for the playtest following the one, for your review.

**Comment by Judian81** [comment] 2019-07-18 16:32
i have something to say about "openra tiberian - dawn gets the rods back."

the secondary mission: "eliminete 12 nod units for reiforcements."

when i play the game and kill 24 nod units i get an extra reinforcement.

so my guess is that the nod keeps getting reinforcemnts too.

personaly i find the game very hard to play.
the maps that follows i got slachtered.

**Comment by AoAGeneral** [comment] 2019-07-22 20:42
@Judian81 Interesting issue. Will have a look at the mission as well.

**Comment by abcdefg30** [comment] 2019-10-04 15:15
Fwiw, having targetable airstrikes would be my preferred solution for campaign missions (see e.g. #12215 ).

**Comment by abcdefg30** [comment] 2020-06-20 18:58
Closing since balance will change a lot with #18273.

**Closed by abcdefg30** 2020-06-20 18:58 UTC
Labels: Balancing, Tiberian Dawn
