### ISSUE TITLE
Destroyer can't damage buildings

### ISSUE THREAD

**Issue by thephoenix87** [OpenRA/OpenRA#11195] opened 2016-04-27 13:25 UTC
In my last game, a destroyer of the AI was firing at my building, but there was no damage. 
Appears in playtest-20160424, no problems in release-20151224.
Bug?

**Comment by abcdefg30** [comment] 2016-04-27 13:50
Duplicate of #10186. Thanks for the report though! :)

**Closed by abcdefg30** 2016-04-27 13:50 UTC
