### ISSUE TITLE
Make units avoid friendly mines at least in singleplayer

### ISSUE THREAD

**Issue by hacklex** [OpenRA/OpenRA#16856] opened 2019-07-28 09:21 UTC
Would love to have that in ants mission, as well as some other single player missions. I read this being considered a balance issue, so it would be good to at least have your units being aware of your mines in singleplayer.

**Comment by Smittytron** [comment] 2021-03-18 15:23
Closing as duplicate of #13291

**Closed by Smittytron** 2021-03-18 15:23 UTC
Labels: Red Alert
