### ISSUE TITLE
Increase screen redraw rate while scrolling

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7614] opened 2015-03-07 19:01 UTC
Currently the screen looks not clear, not smooth while scrolling. It looks so as if the redraw rate is too low and the steps are noticable to the eye. 

[20:52:34] <+pchote> 18:46 <+pchote> oh, now I get you
[20:52:35] <+pchote> 18:46 <+pchote> you mean how often it moves
[20:52:35] <+pchote> 18:46 <+pchote> that is fixed at 25 steps per second
[20:52:36] <+pchote> 18:46 <+Phrohdoh> he means the size of the movement
[20:52:41] <+pchote> 18:47 <+pchote> the size of the movement is what the setting controls

So I think this 25 steps per second frequency should be increased to something like 60 so that these steps are not noticable and the movement looks smooth and continuous and fluid.

**Comment by deniz1a** [comment] 2015-03-08 10:59
[12:54:35] <+pchote> the redraw rate is greater than 25fps
[12:54:42] <+pchote> it is the tick rate which is fixe
[12:54:43] <+pchote> d
[12:54:46] <deniz1a> oh?
[12:55:11] <deniz1a> oh so the tick frequency is coupled to screen redraw rate? it is redrawn after every tick?
[12:55:43] <deniz1a> and what's the tick frequency?
[12:56:30] <+pchote> no
[12:56:37] <+pchote> the tick rate is decoupled from the redraw rate
[12:56:43] <+pchote> and runs at a fixed 25 ticks per second
[12:56:53] <+pchote> which is why the screen moves at that rate
[12:57:04] <+pchote> the jerkyness is because that is slower than the redraw rate
[12:57:48] <deniz1a> ok. so the screen movement would have to be decoupled from tick rate?
[12:58:26] <+pchote> yes

**Comment by pchote** [comment] 2016-07-09 00:33
Duplicate of #9275.  Fixed by #11605.

**Closed by pchote** 2016-07-09 00:33 UTC
Labels: Performance, Polish, UI
