### ISSUE TITLE
Sometimes the pathfinding algorithm or AI is trying to hard

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13424] opened 2017-06-01 22:41 UTC
Sometimes the pathfinding algorithm or AI is trying to hard. Units are blocking the way but somebody is trying hard to move the units, as soon as I chrono the blocking units the problem disappears 

https://imgur.com/a/C6l6M

**Comment by obrakmann** [comment] 2017-06-03 12:03
Duplicate of #12435. Yes, blocking all paths for units creates heavy lag in OpenRA. Is is known.

**Closed by obrakmann** 2017-06-03 12:03 UTC
Labels: Pathfinding
