### ISSUE TITLE
Issues with RA official map 'Evacuation'

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#14451] opened 2017-11-28 22:35 UTC
comments made at: https://resource.openra.net/maps/22452/#comments

**ThunderStruck commented on Nov. 27, 2017, 11:28 p.m.**
"For some reason, the mission won't end. Even after I evacuate Einstien and destroy all soviet units and buildings, it won't end. Also, an infinite number of yaks keep coming from the northeast, which I kept guarded by rocket soldiers to shoot them down as they came in."

**Seth commented on Nov. 28, 2017, 12:53 p.m.**
"can confirm this - the victory trigger doesn't seem to work."

I had the official map uploaded to my account some time ago to make it visible in OpenRA's game tracker.

**Comment by abcdefg30** [comment] 2017-11-28 22:51
Duplicate of #14247.

**Closed by abcdefg30** 2017-11-28 22:51 UTC

**Comment by koolkideco** [comment] 2020-08-27 12:08
Evacuation mission crashes at random times. I was able to complete the game once but usually crashes around 10 mins into the game. 

Fatal Lua Error: [string "BindingSupport.lua"]:30: Uncaught CLR exception at Lua->CLR boundary: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Eluant.LuaException: [string "BindingSupport.lua"]:30: WVec does not define a member 'facing'
  at Eluant.LuaRuntime.Call (System.Collections.Generic.IList`1[T] args) [0x000c9] in <c8bc0b4612b543268b8307855c69585a>:0 
  at Eluant.LuaRuntime.Call (Eluant.LuaFunction fn, System.Collections.Generic.IList`1[T] args) [0x00032] in <c8bc0b4612b543268b8307855c69585a>:0 
  at Eluant.LuaFunction.Call (System.Collections.Generic.IList`1[T] args) [0x00007] in <c8bc0b4612b543268b8307855c69585a>:0 
  at Eluant.LuaFunction.Call (Eluant.LuaValue[] args) [0x00001] in <c8bc0b4612b543268b8307855c69585a>:0 
  at OpenRA.Mods.Common.Scripting.UtilsGlobal.Do (Eluant.LuaValue[] collection, Eluant.LuaFunction func) [0x0000a] in /Users/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Scripting/Global/UtilsGlobal.cs:30 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <b814b509d4ad406fb40c6c93e38929e7>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <b814b509d4ad406fb40c6c93e38929e7>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <b814b509d4ad406fb40c6c93e38929e7>:0 
  at OpenRA.Scripting.ScriptMemberWrapper.Invoke (Eluant.LuaVararg args) [0x000f0] in <d572d317940047d2a5a305d62d990530>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <b814b509d4ad406fb40c6c93e38929e7>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <b814b509d4ad406fb40c6c93e38929e7>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <b814b509d4ad406fb40c6c93e38929e7>:0 
  at Eluant.LuaRuntime+MethodWrapper.Invoke (System.Object[] parms) [0x0000d] in <c8bc0b4612b543268b8307855c69585a>:0 
  at Eluant.LuaRuntime.MakeManagedCall (System.IntPtr state, Eluant.LuaRuntime+MethodWrapper wrapper) [0x0047d] in <c8bc0b4612b543268b8307855c69585a>:0 
  at OpenRA.Scripting.ScriptContext.FatalError (System.String message) [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Mods.Common.Scripting.TriggerGlobal+<>c__DisplayClass2_0.<AfterDelay>b__0 () [0x0002b] in <9e3fa2bb555742fe978c8856b72f04b6>:0 
  at OpenRA.Effects.DelayedAction.<Tick>b__3_0 (OpenRA.World w) [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.World.Tick () [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Game.Loop () [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Game.Run () [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00000] in <d572d317940047d2a5a305d62d990530>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <d572d317940047d2a5a305d62d990530>:0

**Comment by abcdefg30** [comment] 2020-08-27 12:15
Thanks for the report, this was fixed in #18204 and will not occur in our latest release.
