### ISSUE TITLE
Fatal Error on launch

### ISSUE THREAD

**Issue by Musket519** [OpenRA/OpenRA#12553] opened 2017-01-07 16:03 UTC
The log is giving me: Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.

**Comment by reaperrr** [comment] 2017-01-07 17:22
What operating system do you have? What graphics card (or integrated graphics) do you have?
Also, in the folder where the exception log is located you can find graphics.log, the error message from that would help as well.

**Comment by Musket519** [comment] 2017-01-07 18:15
I am on windows home 64bit with a nvidia gt 750m, this is what my graphics.log says: GL Error: 1280
   at OpenRA.Platforms.Default.OpenGL.CheckGLError()

**Comment by StexoO** [comment] 2017-01-07 19:19
`GL Error: 1280`, https://github.com/OpenRA/OpenRA/issues/12496 ?

**Comment by abcdefg30** [comment] 2019-08-04 13:05
Closing as duplicate of #12496.

**Closed by abcdefg30** 2019-08-04 13:05 UTC
Labels: Crash
