### ISSUE TITLE
GivesCashOnCapture ignores given CaptureTypes and works for any

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#20829] opened 2023-04-29 10:19 UTC
exactly what it says in the title,

here i have uploaded a map showcasing the issue:
https://resource.openra.net/maps/52150/

**Comment by anvilvapre** [comment] 2023-06-02 22:40
Related source code. This suggests it does check?

`void INotifyCapture.OnCapture`

https://github.com/OpenRA/OpenRA/blob/c82be175e10c07d6f5352a775dcfba3811cebc35/OpenRA.Mods.Common/Traits/GivesCashOnCapture.cs#L50-L51


Looking at the map yaml, it seems indentation might be messed up? It seems to have both tabs and spaces. Could that be the cause?

i.e. ^I shows tabs. 

```
cat -A rules.yaml 
World:$
^IMissionData:$
^I^IBriefing: Expectation: Capturing a neutral Oil Derrick will grant 500 on capture.\nOccurence: 500 gets granted on any Capture, not only from Neutral.$
^IGlobalLightingPaletteEffect:$
^I^IRed: 1.1$
^I^IGreen: 0.95$
^I^IBlue: 1.051$
^I^IAmbient: 0.68$
$
V19:$
^ICapturable@FIRSTTIME:$
^I^ITypes: building-onlyonce$
        ValidRelationships: Neutral$
        RequiresCondition: !enabled$
    Capturable:$
        Types: building$
        ValidRelationships: Enemy$
        RequiresCondition: enabled$
    GivesCashOnCapture:$
        Amount: 500$
        CaptureTypes: building-onlyonce$
$
E6:$
^ICaptures@CAPTURES:$
        CaptureTypes: building, husk, building-onlyonce$
```

**Comment by PunkPun** [comment] 2023-06-03 07:23
The GivesCashOnCapture checks the capture types of the capturee, that is `building, husk, building-onlyonce`, which does indeed contain `building-onlyonce`

And yes it better to avoid spaces. The oraide extention helps spot them
<img width="662" alt="Screenshot 2023-06-03 at 10 05 16" src="https://github.com/OpenRA/OpenRA/assets/37534529/8367c308-bf51-4ba4-949e-f19d9a19a255">

**Comment by abcdefg30** [comment] 2023-06-03 15:28
Closing then.

**Closed as completed by abcdefg30** 2023-06-03 15:28 UTC
Labels: Bug
