### ISSUE TITLE
Linux, Mono, SocketOptionName 0x17 is not supported at IP level

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#16614] opened 2019-05-29 18:38 UTC
Ubuntu 18.04.2 LTS
mono-devel                                                       5.20.1.19-0xamarin2+ubuntu1804b1

Console/shell logs the below message when joining a game:
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=netframework-4.8

**Comment by anvilvapre** [comment] 2019-05-29 18:40
Not a crash. Only the message. Prio low.

**Comment by LipkeGu** [comment] 2019-07-16 19:07
This is a Mono related problem.

**Comment by matjaeck** [comment] 2019-07-25 22:38
When I let the MD debugger watch for `System.Net.Sockets.SocketException`, it shows that the error occurs on calling the `AllowNatTraversal` method when creating `new Probe()` or `new Beacon()` from the rix0rrr/beacon lib ([src](https://github.com/rix0rrr/beacon/blob/master/BeaconLib/Beacon.cs))  .

Below is the stacktrace from the MD debugger:
Message: "Protocol option not supported"

```  
at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Int32 optionValue) [0x0002f] in <e8eb3d7a311640f484845e45cbec8973>:0 
  at System.Net.Sockets.Socket.SetIPProtectionLevel (System.Net.Sockets.IPProtectionLevel level) [0x00038] in <e8eb3d7a311640f484845e45cbec8973>:0 
  at System.Net.Sockets.UdpClient.AllowNatTraversal (System.Boolean allowed) [0x00003] in <e8eb3d7a311640f484845e45cbec8973>:0 
  at BeaconLib.Beacon..ctor (System.String beaconType, System.UInt16 advertisedPort) [0x00068] in <b50cf4ca64784ce88d2e4f584c721920>:0 


```

**Comment by anvilvapre** [comment] 2019-09-27 16:14
no HRESULT is displayed in the console, only:

System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level

**Comment by BenjaminHerbert** [comment] 2019-11-26 21:48
Still happens with: Red Alert (release-20191117)

**Comment by bggardner** [comment] 2020-05-18 12:40
I get this on the client when the server rejects joining a multiplayer game due to version mismatch.

**Comment by pchote** [comment] 2020-05-18 13:14
This message is caused by the LAN game broadcasts and is completely benign. There is no relationship between this and any other errors that you might see, and its not worth having to fork the library to suppress it.

**Comment by bggardner** [comment] 2020-08-26 20:50
From the [.NET docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=netcore-3.1) for code 0x17 (23, IPv6Only):

>Indicates if a socket created for the AF_INET6 address family is restricted to IPv6 communications only. Sockets created for the AF_INET6 address family may be used for both IPv6 and IPv4 communications. Some applications may want to restrict their use of a socket created for the AF_INET6 address family to IPv6 communications only. When this value is non-zero (the default on Windows), a socket created for the AF_INET6 address family can be used to send and receive IPv6 packets only. When this value is zero, a socket created for the AF_INET6 address family can be used to send and receive packets to and from an IPv6 address or an IPv4 address. Note that the ability to interact with an IPv4 address requires the use of IPv4 mapped addresses. This socket option is supported on Windows Vista or later.

I agree it's benign, but then can it be suppressed from stdout?  I can try to do so, **but I'll need help determining which files to examine**.  The message occurs when entering the Multiplayer Lobby and when creating a Server.

Edit: @pchote suggests starting [here](https://github.com/rix0rrr/beacon/blob/master/BeaconLib/Beacon.cs#L30).

**Comment by anvilvapre** [comment] 2020-08-27 17:47
Line 516: http://138.201.20.148/file/120976053/mono/metadata/socket-io.c/

Possible options:
0. Disable IPV6? Which may cause the option to not even be set for IPv4?
1. Not set the option.
2. Suppress g_warning 
3. Set MONO_LOG_LEVEL, MONO_LOG_MASK to exclude warnings, i.e. https://www.mono-project.com/docs/advanced/runtime/logging-runtime-events/
4. For now. Filter stderr/out in bash to filter out the explicit message.

**Comment by bggardner** [comment] 2020-08-31 01:09
Good find.  Here's the link on GitHub: https://github.com/mono/mono/blob/5d03a6fe116b6ab1570ba2c67933813ede00a0d4/mono/metadata/w32socket.c#L617

I vote for (2) or (3) for releases.

**Comment by Mailaender** [comment] 2022-05-29 16:06
Closing as @mono is now deprecated. This message is not visible when using .NET on Linux.

**Closed by Mailaender** 2022-05-29 16:06 UTC
Labels: Networking, OS: Linux
