### ISSUE TITLE
Gamechrash on Linux

### ISSUE THREAD

**Issue by shiby77** [OpenRA/OpenRA#7139] opened 2014-12-16 12:58 UTC
Game crashes during palying. Feels like random crashes..
```
exception.log:
doRed Alert Mod at Version release-20141029
Operating System: Linux (Unix 3.13.0.1)
Runtime Version: Mono 2.10.8.1 (Debian 2.10.8.1-8) CLR 4.0.30319.1
Exception of type `System.TypeLoadException`: Could not load type 'OpenRA.Mods.RA.Move.MobileInfo' from assembly 'OpenRA.Mods.RA, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
TypeName=`OpenRA.Mods.RA.Move.MobileInfo`
  at System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at OpenRA.ObjectCreator.CreateBasic (System.Type type) [0x00000] in <filename unknown>:0 
  at OpenRA.ObjectCreator.CreateObject[ITraitInfo] (System.String className, System.Collections.Generic.Dictionary`2 args) [0x00000] in <filename unknown>:0 
  at OpenRA.ObjectCreator.CreateObject[ITraitInfo] (System.String className) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.CreateObject[ITraitInfo] (System.String name) [0x00000] in <filename unknown>:0 
  at OpenRA.ActorInfo.LoadTraitInfo (System.String traitName, OpenRA.MiniYaml my) [0x00000] in <filename unknown>:0 
  at OpenRA.ActorInfo..ctor (System.String name, OpenRA.MiniYaml node, System.Collections.Generic.Dictionary`2 allUnits) [0x00000] in <filename unknown>:0 
  at OpenRA.RulesetCache.<LoadMapRules>m__0 (OpenRA.MiniYamlNode k, System.Collections.Generic.Dictionary`2 y) [0x00000] in <filename unknown>:0 
  at OpenRA.RulesetCache+<LoadYamlRules>c__AnonStorey1`1[OpenRA.ActorInfo].<>m__0 (OpenRA.MiniYamlNode wkv, System.Collections.Generic.Dictionary`2 wyy) [0x00000] in <filename unknown>:0 
  at OpenRA.RulesetCache+<LoadYamlRules>c__AnonStorey1`1[OpenRA.ActorInfo].<>m__1 (OpenRA.MiniYamlNode kv) [0x00000] in <filename unknown>:0 
  at OpenRA.Exts.ToDictionaryWithConflictLog[MiniYamlNode,String,ActorInfo] (IEnumerable`1 source, System.Func`2 keySelector, System.Func`2 elementSelector, System.String debugName, System.Func`2 logKey, System.Func`2 logValue) [0x00000] in <filename unknown>:0 
  at OpenRA.RulesetCache.LoadYamlRules[ActorInfo] (System.Collections.Generic.Dictionary`2 itemCache, System.String[] files, System.Collections.Generic.List`1 nodes, System.Func`3 f) [0x00000] in <filename unknown>:0 
  at OpenRA.RulesetCache.LoadMapRules (OpenRA.Map map) [0x00000] in <filename unknown>:0 
  at OpenRA.RulesetCache.LoadDefaultRules () [0x00000] in <filename unknown>:0 
  at OpenRA.ModData.<ModData>m__1 () [0x00000] in <filename unknown>:0 
  at System.Lazy`1[OpenRA.Ruleset].InitValue () [0x00000] in <filename unknown>:0 
```

**Comment by shiby77** [comment] 2015-01-18 14:09
How about mono 3.12?

**Comment by Phrohdoh** [comment] 2015-01-18 14:35
We have not tested 3.12.
Feel free to be the first to do so.

**Comment by Mailaender** [comment] 2015-03-21 08:11
We always build against the latest Mono version from Xamarin now so everything from 3.6 and 3.12.1 has been continuously tested. Mono 2.10 is a legacy version and not recommended anymore (also for performance reasons) and Xamarin is now going for rolling release so only the latest version is supported. They provide repositories for Debian which can't keep up with the release cycle: http://www.mono-project.com/download/#download-lin

----
These crashes are all completely unrelated:

> An element with the same key already exists in the dictionary.

This happened in sprite loader. Without context there is not much we can do. Maybe a broken custom map?

> Out of sync in frame 8004: Blame Tick. Compare syncreport.log with other players.

Do as the error message says. Otherwise we have no chance to debug this. See https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed

> Widget PLAYER_WIDGETS has no child SIDEBAR_TICKE

This stack trace is again incomplete, but it indicates a YAML error which could be caused by an incomplete installation or an outdated custom mod?

----
Closing as this confused report doesn't help. File them individually at the moment they happen. It is now too late to investigate and we already lost the overview.

**Closed by Mailaender** 2015-03-21 08:11 UTC
Labels: Crash, OS: Linux
