### ISSUE TITLE
TD Minor issues.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#8488] opened 2015-06-15 10:22 UTC
Infantry no longer prone when shot at. I am unsure if this actually ignores the prone mechanic or an animation glitch. They do however slow walk when shot at which indicates they are supposed to prone. I will test later if they get damage reductions or not.

Unable to double click select same units while in spectator mode or on the enemies units.

(( All of the above I am unsure how to fix myself. I am not good with LUA and animation mechanics. ))

**Comment by penev92** [comment] 2015-06-15 11:50
We are aware of the prone problem. Infantry actually do go prone, but something overrides the prone animation, so they look like they don't. @reaperrr tried to work around that not long ago, but the workaround seems to work just half of the time, unfortunately.

We recently had several changes to selection logic, but I believe that one is because of @obrakmann's change to not be able do double-click-select enemy units (assuming that you're saying was possible before).

**Comment by Mailaender** [comment] 2015-06-15 17:12
Closing as duplicate of https://github.com/OpenRA/OpenRA/issues/8075.

**Closed by Mailaender** 2015-06-15 17:12 UTC
Labels: Question, Tiberian Dawn
