### ISSUE TITLE
^Plane: with Aircraft: with IdleBehavior: ReturnToBase hangs Midair when last Airfield actor gets sold

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#19366] opened 2021-04-23 08:11 UTC
^ exactly what it says on the Tin can.
Also sorry if its duplicate.

**Comment by ThomasChr** [comment] 2022-10-19 11:12
This is a duplicate for https://github.com/OpenRA/OpenRA/issues/20373
As the new one has nice pictures and a few comments we should close this one here.

**Comment by PunkPun** [comment] 2022-10-19 11:41
Closing as reverse duplicate of #20373

**Closed as not planned** 2022-10-19 11:42 UTC
Labels: Bug
