### ISSUE TITLE
SmudgeLayer.cs Overdraws glDrawArrays

### ISSUE THREAD

**Issue by alexeik** [OpenRA/OpenRA#17125] opened 2019-09-18 19:54 UTC
to save glDrawCalls for Terrain
i modified **SmudgeLayer.cs**
added needRenderCall variable.

```
void ITickRender.TickRender(WorldRenderer wr, Actor self)
		{
			var remove = new List<CPos>();
			if (dirty.Count == 0)
			{
				needRenderCall = false;
			}
			else
			{
				needRenderCall = true;
			}
			foreach (var kv in dirty)
			{
				if (!self.World.FogObscures(kv.Key))
				{
					// A null Sprite indicates a deleted smudge.
					if (kv.Value.Sprite == null)
						tiles.Remove(kv.Key);
					else
						tiles[kv.Key] = kv.Value;
					render.Update(kv.Key, kv.Value.Sprite);

					remove.Add(kv.Key);
				}
			}

			foreach (var r in remove)
				dirty.Remove(r);
		}

		void IRenderOverlay.Render(WorldRenderer wr)
		{
			if (!needRenderCall)
			{
				return;
			}
			render.Draw(wr.Viewport);
		}
```

if not add this flag . everytime openRA run gl_DrawArrays with VertexBuffer that has xyz are zeroes.

**Comment by fruestueck** [comment] 2019-09-18 23:46
Hello alexeik,

I can't say much about your code suggestion (thats up to the devs) but if it improves performance, thats great!

Please consider the [wiki](https://github.com/OpenRA/OpenRA/wiki) for [contributing](https://github.com/OpenRA/OpenRA/wiki/Contributing). You could fork the OpenRA project and create Pull Requests with your suggested changes. It provides a better and easyer way to comment and merge your code suggestions. If you have some questions you can also join the irc channel ([getting in touch](http://www.openra.net/community/)).

**Comment by GraionDilach** [comment] 2019-09-20 06:37
Have you tested this with cases when there are actual smudges on the screen and you shift the viewport?

**Comment by GraionDilach** [comment] 2019-09-20 07:00
I'd close this one in favor of https://github.com/OpenRA/OpenRA/issues/17126#issuecomment-533432208 - both tickets are about thge same underlying issue pretty much.

**Comment by RoosterDragon** [comment] 2019-09-20 20:31
Closing in favour of the linked issue - the root cause is that `TerrainSpriteLayer` which several traits using to render various sprites (e.g. the terrain layer uses it to render the terrain, the smudge layer uses it to render the smudges, etc) will draw "empty" things and makes no attempt to avoid that.

**Closed by RoosterDragon** 2019-09-20 20:31 UTC
Labels: Refactor
