### ISSUE TITLE
No way to override voice announcement for specific actors getting built

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#20149] opened 2022-07-26 08:23 UTC
I had the idea of using a seperate EVA to announce specific units, like Commando Ready when RMBO gets built, or Harvester Ready alas it seems tied to ProductionQueue. VoiceAnnouncement exists but it will not make the inbuilt ReadyAudio go unheard, so there seems no way to override it.

Maybe a new trait that functions similar to ActorLostNotification can get implemented that will let specific actors override the voice announcement on getting built.

**Comment by MustaphaTR** [comment] 2022-07-26 08:29
Duplicate of #16088?

**Comment by MlemandPurrs** [comment] 2022-07-26 09:26
indeed seems to be, sorry didnt search.

**Closed as not planned** 2022-07-26 14:06 UTC
Labels: Idea/Wishlist
