### ISSUE TITLE
TS Laser Fence: Enclosed Units attacking unreachable causes game freezing

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21203] opened 2023-11-11 02:28 UTC
![lag](https://github.com/OpenRA/OpenRA/assets/13763394/6fdd7c8f-5a7a-4c2e-8ad7-7dbd5dfce084)
You can simply reproduce this bug by using units enclosed by laser fence to attack somewhere un reachable.

**Comment by tinix0** [comment] 2023-11-17 21:12
I am not able to reproduce this on bleed, is there anything special about the order you are issuing? Ive tried 30 light infantry in a wall box and giving them a move order or a force attack order and I havent seen tick times above 2ms.

**Comment by dnqbob** [comment] 2023-11-18 00:33
Use force attack order and target somewhere far.

**Comment by dnqbob** [comment] 2023-11-18 01:29
I found it is related with energy wall while normal wall is OK.

**Comment by RoosterDragon** [comment] 2023-12-01 11:20
Regular walls are recognised by HierarchicalPathFinder. The change in #21164 means units surrounded by walls and trying to move out benefit from a fast check that realises they can't make it and significantly reduces the performance impact of trying this.

Laser walls, and various other things such as gates, other units, etc are not recognised by HierarchicalPathFinder. So the changes in #21164 won't help. Trying to move these units out requires a pathfinding attempt.

You can use the `/hpf` debug command and select the units. You'll notice for regular walls it's detected that inside and outside the walls belong to different regions. But for laser walls you can see it's all the same region.

![image](https://github.com/OpenRA/OpenRA/assets/3399086/ead47428-be5e-4937-8b87-a480d0afdb69)

However the main performance problem here is actually #21187: If you *move* the units, you'll notice a small lag spike on that tick and that's it. They pathfind once. If you *attack move* the units repeat a pathfinding attempt *every tick* because they get blocked and keep retrying.

If we fix #21187 then both move and attack move will have similar performance. If we close that issue, I think we can close this issue too.

**Closed as completed** 2024-07-01 12:56 UTC
Labels: Bug, Performance, Pathfinding
