### ISSUE TITLE
No mouse pointer

### ISSUE THREAD

**Issue by Oretrucker** [OpenRA/OpenRA#11269] opened 2016-05-13 21:35 UTC
I downloaded the latest version of Red Alert 2 days ago. I use Windows. First night it worked fine without problems. After that the mouse pointer has disappeared in the menu and in the game itself. Mouse is still working and I can chance settings or play without visible pointer. I already installed game several times again, but the problem continues.

**Comment by abcdefg30** [comment] 2016-05-13 21:53
You should be able to work around this by clicking on the mods button (needs some luck to find the button though, the highlighting helps). Then the mouse cursor should reappear.

**Comment by abcdefg30** [comment] 2016-05-13 21:56
As pointed out by @pchote you can disable "Use Hardware Cursors" in the settings as long-term "fix".

**Comment by obrakmann** [comment] 2016-05-13 22:03
Also, please check the `debug.log` file for lines starting with "Failed to create hardware cursor", and then please post the complete line here.

**Comment by Oretrucker** [comment] 2016-05-13 22:18
Thank you abcdefg30, that fixed the problem. But it seems that I have to do it every time I start the game again. Disabling "Use Hardware Cursors" didn´t fix it permanently. I´m afraid I´m too dumb to check the debug.log. My computer skills are very limited.

**Comment by Oretrucker** [comment] 2016-05-13 22:42
I opened the debug.log file, but there wasn´t any lines about "Failed to create hardware cursor". There was only lines like "Could not find collection 'dialog' and " --Tick: 0 (net)".

**Comment by obrakmann** [comment] 2016-05-14 09:46
Well, of course now that you have disabled hardware cursors in the settings, the debug message won't appear. You'd have to re-enable it again (the logs get cleared when the game starts).

**Comment by Oretrucker** [comment] 2016-05-14 22:58
Failed to initialize hardware cursors. Falling back to software cursors.
Error was: Failed to create hardware cursor `guard-minimap` - Failed to create cursor: CreateIconIndirect(): Parametri ei kelpaa.

**Comment by StexoO** [comment] 2016-06-06 21:54
I never see the cursor when I start OpenRA but I always see it when I click on Mods.

![mods fixes the cursor](https://cloud.githubusercontent.com/assets/8930382/15839046/87784dee-2c41-11e6-93fc-0d554a4ef066.gif)

(Mouse inside the bounds in this entire gif)

**Comment by Mailaender** [comment] 2016-06-22 05:23
Duplicate of https://github.com/OpenRA/OpenRA/issues/10172?

**Closed by Mailaender** 2016-06-22 05:23 UTC
Labels: Bug
