### ISSUE TITLE
Add UI scaling.  It's very hard to see on high res displays

### ISSUE THREAD

**Issue by arcooke** [OpenRA/OpenRA#11365] opened 2016-05-28 02:32 UTC
The UI (especially the construction/minimap dialog) is extremely hard to see at high resolutions.  I use 2560x1440 and the text is about 2mm tall; Playing at 3840x2160 would be close to impossible.  UI is not currently impacted by pixel doubling.

I have attempted running the game in a lower resolution in all window modes, but there are some major rendering issues related to the positioning of things when forcing non-native resolutions in settings.yaml (at least on Linux), which of course is another issue entirely.  

The preferred solution anyway would be to allow scaling of the UI elements.

I searched around and couldn't find this posted anywhere, hopefully this isn't a dupe post.  Wonderful game, just very difficult to play.

**Comment by x-a-n-a-x** [comment] 2016-05-28 07:47
might be related to #10382 and #4945

**Comment by obrakmann** [comment] 2016-05-28 08:55
Yup, duplicate of #10382.

**Closed by obrakmann** 2016-05-28 08:55 UTC
