### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by jrojer** [OpenRA/OpenRA#15101] opened 2018-05-01 19:56 UTC
[exception-2018-05-01T194956Z.log](https://github.com/OpenRA/OpenRA/files/1965019/exception-2018-05-01T194956Z.log)

**Comment by pchote** [comment] 2018-05-01 20:04
Thanks for the report.  This is a duplicate of #14942 which has been fixed (by #14976) for the next release.

**Closed by pchote** 2018-05-01 20:04 UTC
