### ISSUE TITLE
Stances resetting during or after combat, even before

### ISSUE THREAD

**Issue by SmittyShitDevs** [OpenRA/OpenRA#14192] opened 2017-10-16 23:38 UTC
Stances in newest release are resetting to hold fire, either during, before, or after combat.

**Comment by FRenzy-OpenRA** [comment] 2017-10-17 06:49
Issue identified in #14195

**Comment by pchote** [comment] 2017-10-17 08:59
Closing as reverse-duplicate of #14195.

**Closed by pchote** 2017-10-17 08:59 UTC
