### ISSUE TITLE
localised GPS effect?

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11759] opened 2016-08-02 11:22 UTC
This is a question I need to ask, is it possible give a unit the ability to provide a localised GPS effect?
For example everything comes in range of it's detection area it drops a pip on them for the duration their in the detection area.

This is basically what Tiberium Sun's mobile sensor array did but I want to apply it to a custom unit in red alert.

**Comment by pchote** [comment] 2016-08-02 12:03
Not currently possible but, like you suggest, we will have to implement this in the not-too-distant future for TS.

**Comment by Aquilar** [comment] 2016-08-02 13:42
Well as request, could you make it a common trait rather than an exclusive trait to TS?

**Comment by Micr0Bit** [comment] 2016-08-03 18:39
interesting

**Comment by r34ch** [comment] 2016-08-11 08:09
In a similar fashion, will it be possible to remove a GPS pip in a localized radius? This would give an interesting dynamic to the RA radar jammer.

**Comment by WolfGaming** [comment] 2016-08-11 10:05
@r34ch This would be easily possible by introducing a new trait and then filtering it out when we loop over the enemy actors, or we filter in the trait and put that trait by default on every unit like we do with Huntable.

**Comment by pchote** [comment] 2018-05-10 18:40
Closing as reverse duplicate of #12912.

**Closed by pchote** 2018-05-10 18:40 UTC
Labels: Idea/Wishlist
