### ISSUE TITLE
Clients get stuck when server quits

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17268] opened 2019-10-22 19:37 UTC
If the player running the server disconnects (not dedicated) then the clients are stuck with the `Server not responding` messages and the whole game has to be restarted.
Version is playtest-20191021.

**Comment by abcdefg30** [comment] 2019-10-22 19:55
You mean you can not open the menu using `esc`? If that is the case, then you can still exit by manually clicking the menu button (gears), but this is indeed an annoying bug.

**Comment by abmyii** [comment] 2019-10-22 20:06
Gears? I cannot remember seeing them, but I'll take a look when it happens again. The fix is simple, surely?

**Comment by abcdefg30** [comment] 2019-10-22 20:08
I mean the thing in the top right. ^^)
(I think that are gears.)
![grafik](https://user-images.githubusercontent.com/7704140/67327560-69873680-f518-11e9-95b3-36ed597b1ee4.png)

**Comment by abmyii** [comment] 2019-10-22 20:32
Yes, I didn't realise I could escape the "deadlock" using it - I tried it and it worked. Should pressing Escape should allow you to quit to menu?

**Comment by matjaeck** [comment] 2019-10-22 20:33
Should pressing Escape be set to allow you to quit to menu?

IMO yes.

**Comment by abmyii** [comment] 2019-10-22 21:06
As for the Escape key, then I've identified the relevant function as `HandleKeyPress`. At what level would I override the base function? Or have I got the wrong idea?

**Comment by abmyii** [comment] 2019-10-22 21:18
I found the `Key: escape` hotkey option for buttons but this dialogue has none. Should one be added?

**Comment by pchote** [comment] 2019-10-22 21:18
Closing as a duplicate of #12314, which has a hint on how this should be fixed.

**Closed by pchote** 2019-10-22 21:18 UTC
Labels: Bug, UI

**Comment by abmyii** [comment] 2019-10-22 21:22
All right, thanks.
