### ISSUE TITLE
Flamethrower/Shock soldier animation stays bright after attacking.

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6928] opened 2014-11-10 15:04 UTC
The Flamethrower soldier appears brighter after it has fired, not during. There seems to be a delay.

Same effect happens to Shock Trooper.

**Comment by reaperrr** [comment] 2016-05-14 16:18
Duplicate of #5584.

**Closed by reaperrr** 2016-05-14 16:18 UTC
Labels: Polish, Red Alert
