### ISSUE TITLE
Minimap leaking harvesting information through fog of war

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12698] opened 2017-02-05 05:00 UTC
This bug likely to affect the game play and lets you watch your enemy's economic activity: e.g, whether they have an expansion at a location or not.
Steps to reproduce

* Start the game with "Explored Map" option. (probably not required but makes debugging easier)
* Build a radar dome
* Stare at the radar screen and watch ore grow or get harvested

ResourcesLayer have codes to prevent information leaking through FoW in the battlefield screen but the information is leaked through Radar screen.

**Comment by Mailaender** [comment] 2017-02-05 07:37
Duplicate of https://github.com/OpenRA/OpenRA/issues/5908.

**Closed by Mailaender** 2017-02-05 07:37 UTC
