### ISSUE TITLE
AI Loops support power targeting without firing

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#6899] opened 2014-11-07 05:06 UTC
I found the following while spectating an all-bot match:

![screen shot 2014-11-07 at 17 58 50](https://cloud.githubusercontent.com/assets/167819/4948678/aa467054-66a8-11e4-9262-c52250d87de8.png)

The AI never actually fired the power, and instead spammed the chat log with many thousands of targeting debug entries.

**Comment by Mailaender** [comment] 2015-01-04 19:30
I wonder if it could be something simple as a missing `public` which I fixed in https://github.com/OpenRA/OpenRA/commit/1b0e3a7a7f62dec3b704a2ea6dbc5fd8f3037b45#diff-10 but only to satisfy StyleCop.

**Comment by Mailaender** [comment] 2015-07-28 19:31
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/8564.

**Closed by Mailaender** 2015-07-28 19:31 UTC
Labels: AI, Bug
