### ISSUE TITLE
Non wrapping text in chat inputs

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#9336] opened 2015-09-13 16:37 UTC
It is currently possible to type looooooooong sentenses that are not cut off correctly if they reach the end of the line.

![Image of the bug](https://cloud.githubusercontent.com/assets/7704140/9833518/c22b719e-5999-11e5-9411-610eec5e28d5.png)

Bug found by @abcdefg30: https://github.com/OpenRA/OpenRA/pull/8636#issuecomment-139815417
##

**Comment by pchote** [comment] 2017-02-05 18:57
Line-breaking in the middle of a word is very difficult to implement.  I think we'd be better off using the newish text truncation feature to cut the word off with ellipsis instead.

**Comment by pchote** [comment] 2017-02-05 19:09
Duplicate of #3823.

**Closed by pchote** 2017-02-05 19:09 UTC
Labels: Polish, UI
