### ISSUE TITLE
Stats ingame v2.0

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#2650] opened 2013-02-01 03:07 UTC
Its amazing, wishlist for next:

- [ ] Make the screen smaller when fewer players
- [x] after game stats
- [x] stats view when dead
- [ ] make it more transparent?
- [ ] combined team view, and team view also on all (line for teams in graph)
- [ ] fix for long player names.. (should be banned)
- [ ] afk icon for players

**Comment by Tunefix** [comment] 2015-10-11 14:01
I would also wish that all "per minute" stats freezes when a player is defeated/surrender.
Then you would get a more accurate measurement of earnings and actions.

**Comment by abcdefg30** [comment] 2015-10-11 14:14
See #3451.

**Comment by pchote** [comment] 2015-11-22 01:09
Reverse duplicate of #5121.

**Closed by pchote** 2015-11-22 01:09 UTC
Labels: Idea
