### ISSUE TITLE
Units die when near repaired bridge.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12475] opened 2016-12-12 20:12 UTC
Another one I had no idea about. Might be in RA as well. https://youtu.be/GONKwkT2Rzk?t=2m48s

**Comment by abcdefg30** [comment] 2016-12-12 20:18
Duplicate of #9378 I think.

**Closed by abcdefg30** 2016-12-12 20:18 UTC
Labels: Bug

**Comment by AoAGeneral** [comment] 2016-12-12 20:22
Ah true sorry about that!
