### ISSUE TITLE
Game lost response when a aircraft landing on a pit

### ISSUE THREAD

**Issue by moosewoler** [OpenRA/OpenRA#16235] opened 2019-02-23 05:49 UTC
### Issue Summary
Game lost response when a aircraft landing on a pit. 

#### System Information
- **Operating System:** Linux version 4.19.0-2-amd64 (debian-kernel@lists.debian.org) (gcc version 8.2.0 (Debian 8.2.0-14)) #1 SMP Debian 4.19.16-1 (2019-01-17)
- **.NET / Mono Version:** Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-2 Sat Jan 26 18:28:53 UTC 2019)
- **OpenRA Version:** playtest-20190209
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	

1. Choose SinglePlayer --> Skirmish --> Change Map(e.g. A Nuclear Winter) --> left others unchanged --> Start Game
2. Build a Power Plant --> Ore Refinery --> Radar Dome --> Airfield
3. Build a Yak Attack Plane
4. make the yak plane landing on the pit, then the game stop working.
5. wait for a while, it threw out an exception with logs listed below.

- Logs
```
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at System.Collections.Generic.LargeArrayBuilder`1[T].GetBuffer (System.Int32 index) [0x00022] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.LargeArrayBuilder`1[T].CopyTo (System.Collections.Generic.CopyPosition position, T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00041] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].CopyTo (T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00035] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].ToArray () [0x00028] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].LazyToArray () [0x00048] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].ToArray () [0x00016] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at OpenRA.Mods.Common.Activities.ResupplyAircraft.OnFirstRun (OpenRA.Actor self) [0x00087] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs:37 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x00050] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Actor.Tick () [0x00010] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.World.Tick () [0x00046] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00237] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Game.Loop () [0x000d6] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Game.Run () [0x00042] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <ae7dfa45d27e459d9f823d1b6c64b87b>:0 
```

- OpenRA Replays

- Screenshots & Videos

[bug_video.zip](https://github.com/OpenRA/OpenRA/files/2896529/bug_video.zip)

**Comment by pchote** [comment] 2019-02-23 12:08
I'm not able to reproduce this on Mono 5.18 on macOS. Can anyone else repro?

**Comment by matjaeck** [comment] 2019-02-23 17:08
Unable to reproduce on Mono 5.18.0.240 on Ubuntu 18.04, Linux version 4.15.0-45-generic (buildd@lgw01-amd64-031) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019

**Comment by 0x0aNL** [comment] 2019-04-06 10:39
Able to reproduce using the release-20190314 AppImage with:
Debian buster/testing
Linux 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
mono 5.18.0.240+dfsg-2

It took about 20 seconds for the game to throw an exception, until that time it just seemed to be frozen.
[crash.zip](https://github.com/OpenRA/OpenRA/files/3050376/crash.zip)

It seems suspicious that OP and I are both on the same Mono version in Debian.

**Comment by LipkeGu** [comment] 2019-04-25 20:59
I tried to reproduce this the only thing what i have noticed in bleed is that the airlplane is "landing in the snow and is rolling (driving) to the side pit :/ 
[OpenRA-2019-04-25T205234Z.zip](https://github.com/OpenRA/OpenRA/files/3118855/OpenRA-2019-04-25T205234Z.zip)

**Comment by Klaas-** [comment] 2019-05-02 18:25
This seems to be happening here aswell:
```
Platform is Linux
Engine version is release-20190314
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL version: 3.0 Mesa 19.0.3
Using default sound device
Internal mods:
	modcontent: Mod Content Manager (release-20190314)
	ra: Red Alert (release-20190314)
External mods:
	cnc-release-20181215: Tiberian Dawn (release-20181215)
	d2k-release-20181215: Dune 2000 (release-20181215)
	ra-playtest-20190302: Red Alert (playtest-20190302)
	ra-release-20190314: Red Alert (release-20190314)
Loading mod: ra
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
[2019-05-02T19:45:40] Game started
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at System.Collections.Generic.LargeArrayBuilder`1[T].GetBuffer (System.Int32 index) [0x00000] in /builddir/build/BUILD/mono-5.18.1.0/external/corefx/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs:321 
  at System.Collections.Generic.LargeArrayBuilder`1[T].CopyTo (System.Collections.Generic.CopyPosition position, T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00041] in /builddir/build/BUILD/mono-5.18.1.0/external/corefx/src/Common/src/System/Collections/Generic/LargeArrayBuilder.cs:278 
  at System.Collections.Generic.SparseArrayBuilder`1[T].CopyTo (T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00035] in /builddir/build/BUILD/mono-5.18.1.0/external/corefx/src/Common/src/System/Collections/Generic/SparseArrayBuilder.cs:133 
  at System.Collections.Generic.SparseArrayBuilder`1[T].ToArray () [0x00028] in /builddir/build/BUILD/mono-5.18.1.0/external/corefx/src/Common/src/System/Collections/Generic/SparseArrayBuilder.cs:226 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].LazyToArray () [0x00048] in /builddir/build/BUILD/mono-5.18.1.0/external/corefx/src/System.Linq/src/System/Linq/Concat.cs:297 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].ToArray () [0x00016] in <e2bcde62ca9243808c40cb82765b2e2d>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in /builddir/build/BUILD/mono-5.18.1.0/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:18 
  at OpenRA.Mods.Common.Activities.ResupplyAircraft.OnFirstRun (OpenRA.Actor self) [0x00087] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs:37 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x00050] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Actor.Tick () [0x00010] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.World.Tick () [0x00046] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00237] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.Loop () [0x000d6] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.Run () [0x00042] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <f69fafde25414782b71cd55dd1b3d620>:0 

AL lib: FreeContext: (0x55d6103123f0) Deleting 32 Source(s)
```

Platform Fedora 30
```
# uname -a
Linux notebook 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linu

# rpm -qa|grep mono|sort
dejavu-sans-mono-fonts-2.37-1.fc30.noarch
gnu-free-mono-fonts-20120503-20.fc30.noarch
liberation-mono-fonts-2.00.5-1.fc30.noarch
mono-basic-4.7-3.fc30.x86_64
mono-core-5.18.1-2.fc30.x86_64
mono-data-5.18.1-2.fc30.x86_64
mono-data-sqlite-5.18.1-2.fc30.x86_64
mono-extras-5.18.1-2.fc30.x86_64
mono-mvc-5.18.1-2.fc30.x86_64
mono-wcf-5.18.1-2.fc30.x86_64
mono-web-5.18.1-2.fc30.x86_64
mono-winforms-5.18.1-2.fc30.x86_64
python2-monotonic-1.5-2.fc30.noarch
urw-base35-nimbus-mono-ps-fonts-20170801-12.fc30.noarch
```

**Comment by bggardner** [comment] 2019-06-05 00:53
Reproduced on Linux/Ubuntu 19.04 w/ Mono 5.18.0.240 (Debian 5.18.0.240+dfsg-2ubuntu2).  Upgraded Mono to 5.20.1.19-0xamarin2+ubuntu1804b1 and now unable to reproduce.  More evidence the issue lies with Mono 5.18.0.240.

**Comment by pchote** [comment] 2019-06-05 07:53
The next OpenRA release will avoid this (and several other issues) by shipping its own runtime instead of depending on the distro version. Upgrading mono using https://www.mono-project.com/download/stable/#download-lin reliably works around the issue in the current release, so closing.

**Closed by pchote** 2019-06-05 07:53 UTC
Labels: Crash
