### ISSUE TITLE
Reload activity breaks building sell

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11625] opened 2016-07-10 07:31 UTC
This is probably the same underlying problem that happend with the repair pad in https://github.com/OpenRA/OpenRA/issues/7225. If I rearm a helicopter and sell it during a reload action, the heli pad becomes unsellable. Noticed during testing of https://github.com/OpenRA/OpenRA/pull/11620.

**Comment by reaperrr** [comment] 2016-07-10 09:00
Another reason to replace the `Rearm` activity with an upgradable trait solution.
Note that I already have a basically-ready local branch for that, the only missing part is some docking logic + `ProvideUpgradeToDockedActors` trait.

**Comment by WolfGaming** [comment] 2016-08-10 11:13
Wonderfull to see how my prerequisite system went to an upgrade system ionto fixing so many bugs, I can retire now :palm_tree:

**Comment by pchote** [comment] 2016-10-01 10:43
Reverse duplicate of #12035 and fixed by #12051.

**Closed by pchote** 2016-10-01 10:43 UTC
Labels: Bug
