### ISSUE TITLE
crash/game can't open

### ISSUE THREAD

**Issue by mattathebest** [OpenRA/OpenRA#11401] opened 2016-06-05 09:42 UTC

**Comment by abcdefg30** [comment] 2016-06-05 09:47
Could you provide us the `exception.log`, please?

**Comment by mattathebest** [comment] 2016-06-05 10:39
Operating System: OSX (Unix 15.3.0.0)
Runtime Version: Mono 4.2.3 (explicit/832de4b) CLR 4.0.30319.17020
Exception of type `System.IO.FileNotFoundException`: Could not load file or assembly '/Users/Matthieu/Downloads/OpenRA.app/Contents/Resources/OpenRA.Platforms.Null.dll' or one of its dependencies
  at (wrapper managed-to-native) System.Reflection.Assembly:LoadFrom (string,bool)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile, System.Security.Policy.Evidence securityEvidence) [0x00000] in /private/tmp/source-mono-4.2.3/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.3/mcs/class/corlib/System.Reflection/Assembly.cs:548 
  at System.Reflection.Assembly.LoadFile (System.String path, System.Security.Policy.Evidence securityEvidence) [0x00031] in /private/tmp/source-mono-4.2.3/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.3/mcs/class/corlib/System.Reflection/Assembly.cs:585 
  at System.Reflection.Assembly.LoadFile (System.String path) [0x00000] in /private/tmp/source-mono-4.2.3/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.3/mcs/class/corlib/System.Reflection/Assembly.cs:590 
  at OpenRA.Sound..ctor (System.String engineName) <0x4e71d10 + 0x00097> in <filename unknown>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) <0x3aeeaa8 + 0x00367> in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) <0x781b28 + 0x0003b> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x780f48 + 0x000cb> in <filename unknown>:0

**Comment by obrakmann** [comment] 2016-06-05 12:32
duplicate of #11403

**Closed by obrakmann** 2016-06-05 12:32 UTC
Labels: Crash
