### ISSUE TITLE
Nuke trucks kills are not taken in account in the statistics

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16184] opened 2019-02-09 14:26 UTC
Hi !

### Issue Summary

If you send a nuke truck and kill 10 billion infantry with it your stats report 0 Kills, 1 Death, $0 Destroyed and $2500 Lost.
Expected : 10 billion Kills, 1 Death, $correspondingValue Destroyed and $2500 Lost.

#### System Information

- Operating System : Windows 10
- .Net Version : .Net 4.7.2
- OpenRA Version : release-20181215
- Mod : Red Alert

**Comment by Punsho** [comment] 2019-02-09 22:22
Demo truck gives score to whoever kills it

**Comment by St3x** [comment] 2019-02-10 13:15
I played a game where a teammate built only nuke trucks.
He got rid of hundreds of units and structures (literally) but finished the game with only 8 kills.
I thought it was a bug, but now I understand.
Shouldn't the nuke truck give score to its owner, whoever or whatever kills it (even a crate) ?

**Comment by Punsho** [comment] 2019-02-10 21:57
You can blow it up yourself by deploying, it's a tricky unit to balance

**Comment by deleted-user-1** [comment] 2020-08-15 19:55
Possible duplicate of  #14502 but at least related.

**Comment by abcdefg30** [comment] 2020-08-16 10:40
Indeed. #14502 looks like it is covering the more general case.

**Closed by abcdefg30** 2020-08-16 10:40 UTC
