### ISSUE TITLE
Crash when downloading music 

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9077] opened 2015-08-15 13:52 UTC
W10, latest release, crash after downloading the RA mod music and extracting scores.mix. (This might actually just be #9078)

http://pastebin.com/e3RTUWF5

**Comment by Mailaender** [comment] 2015-08-15 14:59
Duplicate of https://github.com/OpenRA/OpenRA/issues/6242. Fixed since playtest-20150628.

**Closed by Mailaender** 2015-08-15 14:59 UTC
