### ISSUE TITLE
make tiles crossable by ground units and by naval 

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#17071] opened 2019-09-09 15:09 UTC
I would like to see special on Teamgames a better interaction between ground units and naval, but there are no tiles which is crossable by both unit types. Bridges and "flooded land" are just passable by ground units. It often happen that naval A in sea A cant fight against the other naval B because there is a bridge or "flooded land"between in worst case both teams/players have on every sea non useable assets. Other RTS like AOE2 have tiles too which are crossable by both units types too. 
My idea is to made this flooded land tiles crossable by ground units and naval.
![Tiles](https://user-images.githubusercontent.com/54892539/64542576-17050880-d324-11e9-9588-8e8411bc3f8f.png)

**Comment by abcdefg30** [comment] 2019-09-09 18:32
Making those passable for transports is something I could get behind, but I think it would be odd for ships and definitely out of place for subs.

**Comment by UppsAlert** [comment] 2019-09-09 19:05
Transports can already doing that. Yeah subs have to appear atleast. With another tileset with more water then land it looks way better for sure.

**Comment by airetaM** [comment] 2019-09-09 22:47
You can test such a paths in this map.
https://resource.openra.net/maps/31853/

**Comment by tovl** [comment] 2019-09-14 12:57
Related: #14218

**Comment by Smittytron** [comment] 2021-03-18 15:54
Closing as reverse duplicate of #18190

**Closed by Smittytron** 2021-03-18 15:54 UTC
Labels: Balancing, Red Alert
