### ISSUE TITLE
Ability to Ally and Un-ally in Multiplayer

### ISSUE THREAD

**Issue by benhbell** [OpenRA/OpenRA#17736] opened 2020-02-29 22:21 UTC
## Motivation
Multiplayer games can get an added layer of character if players were allowed to un-ally or ally once in game. 

## Proposed solution
On the leaderboard, a user can request to join a team. Once Joined, they share the map data and their units no longer attack each other. And they can build on each others base.

On the leaderboard, allied players can leave an alliance. their map data is no longer shared, and units are hostile to each other. 

## Side effects
This has potential conflicts around maps, fog of war, and victory conditions.

## Alternatives
More complex would be for users to be able to control alliance settings
* map
* unit hostility
* building
* with with (victory conditions)

**Comment by AoAGeneral** [comment] 2020-02-29 23:24
This one ive personally liked due to the old school nostalgia of FFA games.

With how easy it is to break teams though might be a good idea to have a checkbox feature in the host settings to enable ingame alliances.

**Comment by Mailaender** [comment] 2020-03-01 15:52
See https://github.com/OpenRA/OpenRA/issues/15061

**Comment by benhbell** [comment] 2020-03-02 17:25
So then if we do this can it be done for Dune 2k too?

**Comment by MustaphaTR** [comment] 2020-03-02 17:30
FYI, this used to be an option, but it was removed because it was unfixably broken. But if someone would reimplement it better, of course it could get back in.

**Comment by abcdefg30** [comment] 2020-03-03 14:55
Closing as duplicate of #15061 then.

**Closed as completed by abcdefg30** 2020-03-03 14:55 UTC
Labels: Idea/Wishlist
