### ISSUE TITLE
Rifle Infantry cannot damage heavy tanks.

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11611] opened 2016-07-09 08:02 UTC
Rifle Infantry cannot damage heavy tanks.

**Comment by jaZzKCS** [comment] 2016-07-09 08:24
Design choice.
Heavy armor is not supposed to be penetrated by rifle infantry.

**Comment by Micr0Bit** [comment] 2016-07-09 08:29
i have noticed this too , yesterday ... same goes for light tanks ... 30 rifle-soldiers cant do "any" damage

this is a bug (not design choice) , they used to do atleast a little bit of damage ...

**Comment by Mailaender** [comment] 2016-07-09 09:36
Duplicate of https://github.com/OpenRA/OpenRA/issues/11425. I assume https://github.com/OpenRA/OpenRA/issues/11460 did already fix it.

**Closed by Mailaender** 2016-07-09 09:36 UTC
