### ISSUE TITLE
GPS - Fog of War - Unit Targeting

### ISSUE THREAD

**Issue by e1d1s1** [OpenRA/OpenRA#9953] opened 2015-11-10 05:50 UTC
Long range units, such as artillery and V2s do not auto-target enemies within range when GPS ability is up, they will only fire if another unit has line of sight.  AI skirmish opponents seem to have no trouble targeting deep within the players base when they should not have line of sight. This was a change introduced with the playtest 20151031. You did not need active line of sight (cleared fog of war), just GPS was enough for artillery to fire on enemy units in previous releases.

**Comment by penev92** [comment] 2015-11-10 09:16
This was most likely caused by the series of fixes to the targeting code. I guess those were too strict.
As I understand, we *do* want stuff to auto fire at GPS icons, so marking this as a bug.

**Comment by penev92** [comment] 2015-11-10 09:23
Also adding to the milestone, because I think we should try and remedy this before the release.

**Closed** 2015-11-10 21:23 UTC
Labels: Bug, Red Alert

**Comment by penev92** [comment] 2015-11-11 08:44
Thanks for the report, by the way! :)
It has been fixed now.

**Comment by e1d1s1** [comment] 2015-11-11 15:09
Thank you! always loved the original, and have been poking around in the
code for quite a while now too. I might contribute some in the future. You
guys are doing an awesome job.

On Wed, Nov 11, 2015 at 3:44 AM, Pavel Penev <notifications@github.com>
wrote:

> Thanks for the report, by the way! :)
> It has been fixed now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRA/OpenRA/issues/9953#issuecomment-155706117>.
>



-- 

*Eric D. Schmidt*

Senior Software Engineer

M: 412-559-5192

www.aquionenergy.com



[image:
http://cdn2.hubspot.net/hub/147472/file-70650512-png/Brand_Elements/aquion_logo_full_color_signature.png]

This e-mail message and any files transmitted with it contain confidential
and/or proprietary information intended only for the named recipient.  Any
review, dissemination, distribution, or copying of this e-mail message by
persons or entities other than the intended recipient is prohibited.  If
you have received this e-mail message in error, please delete it and notify
the sender immediately by telephone or e-mail.
