### ISSUE TITLE
TS mod crashes when viewing .vxl files in the asset browser

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19187] opened 2021-02-24 20:06 UTC
## System Information

- Operating System:  Windows 10 Home 20H2 
- OpenRA Version: Bleed from 2/23/21
- OpenRA Mod: Tiberian Sun 
- Source: Self-compiled

## Exception log

```
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
Date: 2021-02-23 22:24:26Z
Operating System: Windows (Microsoft Windows NT 10.0.19042.0)
Runtime Version: .NET CLR 5.0.1
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.Logic.AssetBrowserLogic.SelectNextFrame() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Mods.Common\Widgets\Logic\AssetBrowserLogic.cs:line 293
   at OpenRA.Widgets.Widget.TickOuter() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 468
   at OpenRA.Widgets.Widget.TickOuter() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 470
   at OpenRA.Widgets.Widget.TickOuter() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Widgets\Widget.cs:line 470
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Sync.cs:line 166
   at OpenRA.Sync.RunUnsynced(Boolean checkSyncHash, World world, Action fn) in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Sync.cs:line 167
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Game.cs:line 646
   at OpenRA.Game.LogicTick() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Game.cs:line 661
   at OpenRA.Game.Loop() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Game.cs:line 864
   at OpenRA.Game.InitializeAndRun(String[] args) in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Game\Game.cs:line 274
   at OpenRA.Launcher.Program.Main(String[] args) in C:\Users\Leonard\Downloads\OpenRA-bleed (4)\OpenRA-bleed\OpenRA.Launcher\Program.cs:line 30
```

## Replay

N/A

## Additional information

Using the asset browser for awhile the game will crash to desktop I don't remember if it also crashes with .shp files.

**Comment by penev92** [comment] 2021-02-26 13:31
~I can not reproduce on current `bleed` version `8b81078929549c47facc1d56873b846c29bc4b89`. (Nor have I spotted such crashes in the past 2 weeks of working on the Asset Browser.
Your exception says `line 293`, but on current `bleed` [that is a closing parenthesis](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/Logic/AssetBrowserLogic.cs#L293) and `AssetBrowserLogic.cs` hasn't changed since 10.01.2021. Please make sure your repository is clean, fetch & checkout latest and test again.~

Never mind, reproduced.
#19143 will fix this anyway.

**Comment by Leo512bit** [comment] 2021-02-27 00:24
> Never mind, reproduced.

Does it also crash with .shp files?

**Comment by penev92** [comment] 2021-02-27 00:38
Crashes when a sprite animation is playing and you switch to a different type of asset (like a voxel).

**Comment by Leo512bit** [comment] 2021-02-27 06:14
> Crashes when a sprite animation is playing and you switch to a different type of asset (like a voxel).

Ah okay thanks for the info.

**Closed as completed** 2022-01-09 17:40 UTC
Labels: Crash, Asset Browser
