### ISSUE TITLE
Targeting regression

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16913] opened 2019-08-09 16:50 UTC
In release-20190314, when you give an attack order while out of range of the target and then a move order so the unit passes the target, it will attack as long it is in attack range. This does no longer work on 7cfc65010f9eb3a5f8f3b4145e918fa8f2419f8f, see the gifs below.

<details>

## Release-20190314:

![stickyrelease](https://user-images.githubusercontent.com/37185497/62794983-db351400-bad5-11e9-9e85-b016ceb05caf.gif)

## Bleed

![bleedstickybug](https://user-images.githubusercontent.com/37185497/62795006-edaf4d80-bad5-11e9-9a7e-48fa71f8167d.gif)

**Comment by matjaeck** [comment] 2019-08-09 17:49
Regression was introduced by 30de4df749bf9df43ef5477ea1381024a4e0b0be (90ddf24cf3997d5db8bcf3bad6ef095f63c39f7e, the commit before, is not affected).

**Comment by pchote** [comment] 2019-08-12 09:31
Possibly related to https://forum.openra.net/viewtopic.php?p=310611#p310611 which provides a replay for debugging.

**Comment by pchote** [comment] 2019-08-17 12:44
Confirmed that this is a regression from 30de4df, and specifically because of https://github.com/OpenRA/OpenRA/commit/30de4df749bf9df43ef5477ea1381024a4e0b0be#diff-d888e8822ba56bbbab4330304a9b80f1L278-R286 for tanks.

Digging deeper, the "correct" behavior here relied on a bug that was fixed by switching to child activities:

Previously, `AttackFollow` would insert the `MoveWithinRange` into the activity queue before it, and issuing the move order to go past the target would cancel that activity. The original `AttackFollow` would simply be nulled out, not having a chance to tick. The `requestedTarget` stays set to the original target.

Now, `AttackFollow` is the one cancelled by the move, which gives it the chance to demote the target from `requestedTarget` to `opportunityTarget`. The opportunity target is then immediately cleared for reasons that I haven't yet debugged and have likely changed as the opportunity logic was significantly rewritten after 30de4df.

**Comment by pchote** [comment] 2019-08-17 12:57
The opportunity target is cancelled because it is not in range when it is demoted, and it isn't reacquired later because tanks won't automatically acquire structures in the Defend stance.

We could add a workaround of not resetting the opportunity target if there is nothing else to switch to, but I don't see the point there - it will lose it as soon as it sees anything else along the route.

Its not clear to me what the expected behaviour here should even be when we try to consider all the edge cases that apply (different ways of cancelling the activity, whether or not the tank sees an auto-targetable enemy while en-route, whether we lose visibility for the target while en-route, etc) so IMO our best option here is probably going to be calling this an intentional/acceptable change and leaving it be.

**Comment by pchote** [comment] 2019-08-17 13:01
@tovl do you have any thoughts on this?

**Comment by tovl** [comment] 2019-08-17 16:03
I tend to agree with @pchote. The target being cancelled because it is out or range sounds perfectly logical and consistent to me. I'm afraid that trying to emulate the buggy behaviour can not be done in a manner that is both consistent and transparent. My vote would be for wontfix.

**Comment by matjaeck** [comment] 2019-08-17 21:30
> The target being cancelled because it is out or range sounds perfectly logical and consistent to me.

Agreed. Consistency, clean code and predictable  behavior is more important than restoring this feature.

**Comment by abcdefg30** [comment] 2019-08-17 22:23
Closing as won't fix/not a bug then.

**Closed by abcdefg30** 2019-08-17 22:23 UTC
Labels: Regression
