### ISSUE TITLE
hetzner server crash reports

### ISSUE THREAD

**Issue by ihptru** [OpenRA/OpenRA#6033] opened 2014-07-22 19:07 UTC
hetzners got 3 crashes today on a new 2014-0722 release.

***

<pre>
Exception of type `System.InvalidOperationException`: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[OpenRA.Server.Connection].MoveNext () [0x00000] in <filename unknown>:0
  at OpenRA.Mods.RA.Server.PlayerPinger.Tick (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__EE (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[OpenRA.Server.Connection].MoveNext () [0x00000] in <filename unknown>:0
  at OpenRA.Mods.RA.Server.PlayerPinger.Tick (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__EE (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
</pre>

***

<pre>
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Network.Session+<PingFromClient>c__AnonStorey68.<>m__110 (OpenRA.Network.ClientPing p) [0x00000] in <filename unknown>:0
  at System.Linq.Enumerable.Single[ClientPing] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0
  at System.Linq.Enumerable.SingleOrDefault[ClientPing] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0
  at OpenRA.Network.Session.PingFromClient (OpenRA.Network.Client client) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__EE (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Network.Session+<PingFromClient>c__AnonStorey68.<>m__110 (OpenRA.Network.ClientPing p) [0x00000] in <filename unknown>:0
  at System.Linq.Enumerable.Single[ClientPing] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback) [0x00000] in <filename unknown>:0
  at System.Linq.Enumerable.SingleOrDefault[ClientPing] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0
  at OpenRA.Network.Session.PingFromClient (OpenRA.Network.Client client) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__EE (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
</pre>

***

<pre>
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.RA.Server.LobbyCommands.ValidateCommand (OpenRA.Server.Server server, OpenRA.Server.Connection conn, OpenRA.Network.Client client, System.String cmd) [0x00000] in <filename unknown>:0
  at OpenRA.Mods.RA.Server.LobbyCommands.InterpretCommand (OpenRA.Server.Server server, OpenRA.Server.Connection conn, OpenRA.Network.Client client, System.String cmd) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__EE (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenRA.Mods.RA.Server.LobbyCommands.ValidateCommand (OpenRA.Server.Server server, OpenRA.Server.Connection conn, OpenRA.Network.Client client, System.String cmd) [0x00000] in <filename unknown>:0
  at OpenRA.Mods.RA.Server.LobbyCommands.InterpretCommand (OpenRA.Server.Server server, OpenRA.Server.Connection conn, OpenRA.Network.Client client, System.String cmd) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__EE (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
</pre>

**Comment by Mailaender** [comment] 2015-01-02 16:51
Duplicate of https://github.com/OpenRA/OpenRA/issues/6941.

**Closed by Mailaender** 2015-01-02 16:51 UTC
Labels: Crash, Dedicated
