### ISSUE TITLE
Can't force fire on (most) parts of a bridge under fog of war

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10221] opened 2015-12-14 08:06 UTC
Tested on: release-20150919, playtest-20151213 

It looks like a variation of #7546 is still present (and not only in the single player missions) in the current playtest - but only under fog of war and if no units are there.

Screenshot:
Green = Can't force fire
Red = Can force fire
![forcefirebridges](https://cloud.githubusercontent.com/assets/10639257/11775741/9824465a-a241-11e5-9a9c-81b2e8da1fa0.jpg)

**Comment by pchote** [comment] 2015-12-14 08:17
Can you please test this on bleed? I suspect it is just a duplicate of #7546 (which indeed hasn't been fixed on release-20150919, playtest-20151213 – only bleed)

**Comment by pi99y** [comment] 2015-12-14 08:30
Confirmed! This is fixed on bleed.

**Comment by penev92** [comment] 2015-12-14 09:46
Great, so I guess we're done here.

**Closed by penev92** 2015-12-14 09:46 UTC
Labels: Bug
