### ISSUE TITLE
Selection boxes are rendered about the shroud.

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#14689] opened 2018-01-08 05:39 UTC
When we select Units like infantry (and keeping them selected) and restart the mission after that, the selection boxes will be rendered about the Shroud.

**Comment by pchote** [comment] 2018-01-27 16:40
This doesn't make much sense because the selection belongs to the world, which is disposed and recreated when the game is restarted.

I fail to reproduce this by starting Soviet01, selecting the infantry in the base, and then restarting the mission.  Can you please provide specific steps to reproduce and a video?

**Comment by pchote** [comment] 2018-09-09 01:37
Any updates here @LipkeGu?

**Comment by LipkeGu** [comment] 2018-09-14 21:08
Yes select a civillian or enemy unit, and let it move into the shroud...

**Comment by matjaeck** [comment] 2019-04-22 10:05
> Yes select a civillian or enemy unit, and let it move into the shroud...

Can not reproduce.
<details>

![selectionbox](https://user-images.githubusercontent.com/37185497/56495657-bef57300-64f6-11e9-8fba-6da769ae8569.gif)

**Comment by LipkeGu** [comment] 2019-04-25 19:07
in your Image it is seeable @harvester

**Comment by matjaeck** [comment] 2019-04-30 14:10
@LipkeGu so, can we close this?

**Comment by deleted-user-1** [comment] 2020-08-29 20:01
[Comment above](https://github.com/OpenRA/OpenRA/issues/14689#issuecomment-485382374) indicates this was fixed, although not tested against TS.

**Closed** 2020-08-29 20:02 UTC
Labels: Bug
