### ISSUE TITLE
nullptr exception

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#15187] opened 2018-05-30 20:25 UTC
Engine version is release-20180307
Using SDL 2 with OpenGL renderer
Desktop resolution: 1600x900
No custom resolution provided, using desktop resolution
Using resolution: 1600x900
Using window scale 1.00
OpenGL version: 3.0 Mesa 12.0.6
Using sound device `Built-in Audio Analog Stereo`
Internal mods:
        cnc: Tiberian Dawn (release-20180307)
        d2k: Dune 2000 (release-20180307)
        modcontent: Mod Content Manager (release-20180307)
        ra: Red Alert (release-20180307)
External mods:
        cnc-release-20180307: Tiberian Dawn (release-20180307)
        d2k-release-20180307: Dune 2000 (release-20180307)
        ra-release-20180307: Red Alert (release-20180307)
        cnc-release-20180218: Tiberian Dawn (release-20180218)
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
Loading mod: ra
NAT discovery failed: One or more errors occurred.
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.Common.Traits.Guard.GuardTarget (OpenRA.Actor self, Target target, Boolean queued) [0x0001c] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Guard.cs:54 
  at OpenRA.Mods.Common.Traits.Guard.ResolveOrder (OpenRA.Actor self, OpenRA.Order order) [0x00029] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Guard.cs:44 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) <0x4052ae30 + 0x01fd6> in <filename unknown>:0 
  at OpenRA.Network.OrderManager.Tick () <0x4041da70 + 0x0016f> in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) <0x40415de0 + 0x005c3> in <filename unknown>:0 
  at OpenRA.Game.LogicTick () <0x40412ec0 + 0x000b3> in <filename unknown>:0 
  at OpenRA.Game.Loop () <0x40412ad0 + 0x0014f> in <filename unknown>:0 
  at OpenRA.Game.Run () <0x40412560 + 0x00077> in <filename unknown>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) <0x40177a80 + 0x0004f> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x40176d60 + 0x000f7> in <filename unknown>:0

**Comment by pchote** [comment] 2018-05-30 20:31
Thanks for the report.  This is a duplicate of #15081 which has been fixed with #15122, so closing.

**Closed by pchote** 2018-05-30 20:31 UTC
