### ISSUE TITLE
Alt modifier doesn't work on Linux

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17388] opened 2019-11-27 00:02 UTC
Alt (force-move) modifier doesn't work at all. You have to use Alt+Gr (right alt) to perform the same function.

This should be `KMOD_LALT` though it doesn't make a difference for some reason:
https://github.com/OpenRA/OpenRA/blob/f325a4d190f74e1519935fcf2111474c1cf045ce/OpenRA.Platforms.Default/Sdl2Input.cs#L36

**Comment by obrakmann** [comment] 2019-11-27 10:48
Duplicate of #15527. Also check [this FAQ entry](https://github.com/OpenRA/OpenRA/wiki/FAQ#some-hotkeys-do-not-work-under-linux).

**Closed by obrakmann** 2019-11-27 10:48 UTC
Labels: Bug, OS: Linux
