### ISSUE TITLE
Install map is broken sometimes

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#6196] opened 2014-08-06 14:24 UTC
Sometimes even when map is on the resource.openra.net it cant install the map for some reason. Happens to me sometimes too.
##

**Comment by pchote** [comment] 2016-07-09 00:46
This was fixed by the map installation rewrite in the last release (or maybe earlier).  No repro on release-20160508.

**Comment by Elizadmin** [comment] 2017-09-01 16:20
I see this in release-20170527.
Sometimes (I would say randomly) you can't install a map available in the Resource Center. OpenRA doesn't say "Searching" but simply "Can't install". If you restart OpenRA and reconnect to that server the map is installed normally.
I joined servers where hosts and players said "if you can't install restart OpenRA" so it's somehow known.

**Comment by pchote** [comment] 2017-11-23 20:57
Thanks to a useful discussion in zxganon's stream chat we discovered that this is caused by 
https://github.com/OpenRA/OpenRA/blob/7c901c27f10ca594a56abac5fbbd5635fbf53e6e/OpenRA.Game/Map/MapPreview.cs#L430-L431
not accounting for `MapStatus.DownloadError` if the resource center 404's the first time the download button is pressed.  I have encouraged one of the chat members to file a PR with their fix, but otherwise have my own waiting as a fallback.

**Comment by dsimmons87** [comment] 2017-11-23 21:29
Ok I've added an extra condition to that if statement which also checks for MapStatus.DownloadError.

#14410

**Comment by penev92** [comment] 2017-11-27 13:27
Should be fixed now that #14410 is merged.

**Closed by penev92** 2017-11-27 13:27 UTC
Labels: Bug
