### ISSUE TITLE
Chronoshift return can be interrupted by issuing movement orders

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15497] opened 2018-08-11 03:03 UTC
To reproduce:
Chronoshift a unit, then spam click some movement orders right as the duration expires and the unit will remain.

**Comment by abcdefg30** [comment] 2018-08-12 14:32
Is this a regression or already present on the last release?

**Comment by pchote** [comment] 2018-08-12 14:34
Looks like the `Teleport` activity is interruptable.  We probably don't want that.

**Comment by FrameLimiter** [comment] 2018-08-12 14:47
I'd assume a regression as can't seem to reproduce it on the release, at least during my handful of attempts. While it's quite easy to reproduce on the playtest.

**Comment by pchote** [comment] 2018-08-12 19:13
This happens when the unit is running a `Move` activity when the timer expires.

1.  The return code calls `Cancel`, and the activity returns true (indicating that it is cancelled), but actually isn't cancelled because of https://github.com/OpenRA/OpenRA/blob/dcf93203ea0eff1ee0fc6b28639eb0845012d648/OpenRA.Mods.Common/Activities/Move/Move.cs#L161-L167
2.  The `Teleport` activity is queued after the `Move`.
3.  A `"Move"` order is resolved by Mobile, which calls `Cancel` again.  This again hits `Move`, but then happily discards the `Teleport` activity because of a long standing bug where queued activities are thrown away without checking whether this is safe, or calling `Cancel` on them.

Fixing this properly requires major surgery on the activity code which we have been actively avoiding for years because we expect it to be a huge and awful job.  The best we can hope to do is identify what has changed to make this specific case worse, and revert it.

**Comment by pchote** [comment] 2018-08-12 19:30
I have a hack that can solve this with minimal changes.  Will file a PR and hope it doesn't get rejected for being really nasty.

**Comment by matjaeck** [comment] 2018-08-12 20:59
#8670 seems related and a [gif](http://i.imgur.com/lylDYxw.gif) in this [comment ](https://github.com/OpenRA/OpenRA/issues/8670#issuecomment-124958707) seems to show the behavior described here.

**Closed** 2018-08-15 20:17 UTC
Labels: Regression
