### ISSUE TITLE
Game Crashed/Fatal Error on opening, Nothing in the Logs?

### ISSUE THREAD

**Issue by RustyShacklefordd** [OpenRA/OpenRA#18348] opened 2020-07-03 15:16 UTC
Hello - looks like my game crashed/had a Fatal Error upon opening, and when i go to check the logs they're all blank?  

Just tried uninstalling/reinstalling and still having the problem....any ideas?

**Comment by deleted-user-1** [comment] 2020-07-03 15:35
Hi, thanks for reporting! Usually this indicates that something is interfering with OpenRA - maybe an anti-virus-program is blocking? Could you share details about your system and the OpenRA version you are running? See the guideline for posting a [crash report](https://github.com/OpenRA/OpenRA/issues/new?assignees=&labels=Crash&template=crash-report.md&title=My+game+crashed) for required information :wink: (you don't need to open a new one).

**Comment by peskydan** [comment] 2020-07-09 22:26
I have exactly the same problem, using the current OpenRA appimage release 20200503. Logs are created, but are all empty files (zero bytes). I'm on Linux, and I have nothing installed that is blocking execution.

X server is "X.Org 1.20.8". Kernel is "5.4.0-40-generic x86_64". Distribution is Kubuntu 20.04 (KDE Plasma 5.18.5).

I suspect this is video/OpenGL/X related, since I did once get the game to run, very slowly, with software rendering, when there was no graphics driver installed. The system I'm having this issue on is an i5 M 520 using i915 graphics driver, which supports OpenGL 2.1. It's a vanilla system, and glmark2 runs all scenes without any issues, with full hardware acceleration. System is fully up to date.

Deleting all OpenRA directories makes no difference; same error.

/var/log/syslog contains only the following new entries after the failed run attempt:
Jul  9 23:06:38 server3-deb systemd[1]: tmp-.mount_OpenRAXOjbpG.mount: Succeeded.
Jul  9 23:06:38 server3-deb systemd[1068]: tmp-.mount_OpenRAXOjbpG.mount: Succeeded.
![Screenshot_20200709_232627](https://user-images.githubusercontent.com/47797932/87096859-a9738280-c23b-11ea-9d48-e8182eb07f64.png)

**Comment by pchote** [comment] 2020-07-09 22:32
Do the AppImages from https://github.com/pchote/OpenRA/releases/tag/release-20200503-graphicstest2 fix the issue?

**Comment by peskydan** [comment] 2020-07-09 23:11
Thanks for the response. Just tried Dune, Red Alert and Tiberian Sun appimages from the URL you provided; sadly no change. Same error.

**Comment by peskydan** [comment] 2020-07-10 00:02
I invoked the appimage with redirected output and captured the following:

```
Platform is Linux
Engine version is release-20200503
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  4 (X_DestroyWindow)
  Resource id in failed request:  0x7a0001d
  Serial number of failed request:  283
  Current serial number in output stream:  284
```

This would appear to be happening before an OpenGL context is created, since InitializeOpenGL() in Sdl2GraphicsContext would throw an exception (presumably logged or written to stderr) if SDL_GL_CreateContext() or SDL_GL_MakeCurrent() failed. Note though that I don't know OpenRA's codebase at all; this is the first time I've seen it, and only briefly, so I'm probably looking in the wrong places.

My initial thought on seeing the X error above was that a GL context request was probably failing, followed by some cleanup code trying to destroy a nonexistent window without checking its value, leading to the failure on X_DestroyWindow. But unless there's GL init stuff going on in more than one place, that doesn't seem to be the case. Maybe GL is a red herring. Is this build supposed to support OpenGL 2.1?

Is there a way to invoke OpenRA with some command line parameters, to force e.g. software rendering, or to make it do something that will definitely throw a logged exception early in startup?

---

Edit: I've unpacked the appimage, so if for example adding or altering the content of a file would cause helpful diagnostic behaviour, I'm happy to do that and report back. Or if you could provide some simple build instructions, I could probably trace the problem.

I also just installed Assault Cube (a full 3D first-person shooter from the Ubuntu repositories) to test whether there are any issues with my system, but it seems to run flawlessly.

**Comment by bggardner** [comment] 2020-08-25 12:35
Possible duplicate of #18061

**Comment by abcdefg30** [comment] 2021-07-15 09:57
Closing due to inactivity.

**Closed as completed by abcdefg30** 2021-07-15 09:57 UTC
Labels: Crash
