### ISSUE TITLE
D2k outpost dish looks broken during placement preview and make animation

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#19171] opened 2021-02-20 15:52 UTC
* A black square is visible around it in the placement preview
* It draws above the crumble animation in the make animation

This has been broken since at least release-20200503.

**Comment by abcdefg30** [comment] 2023-06-09 11:11
Closing as reverse duplicate of #20744.

**Closed as completed by abcdefg30** 2023-06-09 11:11 UTC
Labels: Dune 2000, Polish
