### ISSUE TITLE
Make all Create() functions in YyyInfo overridable

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12673] opened 2017-02-02 03:07 UTC
All traits in Mods.Common are not inheritable.
For example, I've been trying to create Marvest trait from Harvester trait.
They will share most of the code except I only have to remove docking behavior.

One way is to copy paste the whole Harvester.cs to make a separate MarvesterInfo and Marvester Trait class. Then, I run into trouble: I have to copy whole FindResources.cs in activities, as it requires Harvester trait and HarvesterInfo and any other stuff that reference Harvester trait.

Modders will then decide and inherit HarvesterInfo into MarvesterInfo so they can take advantage of implemented FindResources.

The problem with this decision is that when I inherit HarvesterInfo like this,

	public class OreTeleportHarvesterInfo : HarvesterInfo
	{
		**new** public object Create(ActorInitializer init) { return new OreTeleportHarvester(init.Self, this); }
	}

the new Create() function never gets run.

	public OreTeleportHarvester(Actor self, OreTeleportHarvesterInfo info)
		{
			Info = info;
			mobile = self.Trait<Mobile>();
			Game.Debug("MARV has arrived");
		}

This can be verified by putting a debug message.

Throughout modding this occurs very often.
It happened to me before when I tried to implement SharedCargo from Cargo trait: https://github.com/OpenRA/OpenRA/issues/6409#issuecomment-275822047

**Comment by pchote** [comment] 2017-02-02 08:26
Duplicate of #11813 with is being fixed by #12554.

**Closed by pchote** 2017-02-02 08:26 UTC
