### ISSUE TITLE
Units twitching

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13437] opened 2017-06-03 10:33 UTC
Units twitching:
In some cases the V2 rocket Launcher when he sets the target does ~30 degrees turns really quick
The chinook, yak when they flay have a twitching or a wobble in the flight path

**Comment by reaperrr** [comment] 2017-06-03 12:22
The V2 target anim sprite has only 8 facings, so unless someone adds the missing facings to the shp, not much we can do about it.

**Comment by reaperrr** [comment] 2017-06-03 14:47
The V2 twitching is a duplicate of #12117 and aircraft twitching is a duplicate of #4824, so I'll close this ticket, but I agree that fixing the latter is a bit overdue by now, so I'm putting #4824 on the next milestone, hopefully someone will find the time to fix it.

**Closed by reaperrr** 2017-06-03 14:47 UTC
