### ISSUE TITLE
Regressed Thief behaviour

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#17043] opened 2019-09-04 09:20 UTC
From https://forum.openra.net/viewtopic.php?p=310692#p310692:
> Thiefs miss their target, they often just run by and bug out. After this they forget their target.

A quick test on bleed confirmed this.

**Comment by pchote** [comment] 2019-10-02 19:47
Possibly related to the other locomotor cache issues?

**Comment by abcdefg30** [comment] 2019-10-05 11:49
I can still reproduce this on #17159.

**Comment by pchote** [comment] 2019-10-06 14:12
It looks like something may have regressed with pausing `Mobile` to stop movement.

Add
```
WithColoredOverlay@CAPTURED:
	RequiresCondition: being-captured
```
to `^Vehicle` and notice that the target continues moving while the condition is active. The target moves outside the capture threshold, and the thief cancels the capture.

**Comment by pchote** [comment] 2019-10-06 14:59
Comparing vs `release-20190314` we were previously freezing movement immediately, between cells, but now keep moving until reaching the middle of the next cell.

**Comment by GraionDilach** [comment] 2019-10-06 15:08
This could also be caused by the activity refactor not letting the move stop mid-cell. I'd propose keeping this as-is and using `SpeedMultiplier: 0 ` in YAML to restore the behaviour.

**Comment by pchote** [comment] 2019-10-06 15:09
Do we have a use case for pausing `Mobile` not freezing movement immediately?

**Comment by GraionDilach** [comment] 2019-10-06 15:10
Carryall?

**Comment by tovl** [comment] 2019-10-06 15:18
>I'd propose keeping this as-is and using SpeedMultiplier: 0 in YAML to restore the behaviour.

There is no need for such workarounds. This appears to have been a regression from #16262. There is a missing `IsTraitPaused` in `MovePart`

https://github.com/OpenRA/OpenRA/blob/acea19312d1e3cfcb0b95fd03208ef25c102ab0e/OpenRA.Mods.Common/Activities/Move/Move.cs#L410

Before this PR this condition triggered a disable not a pause.

**Comment by tovl** [comment] 2019-10-06 15:33
That said, making sure the units always stop in the center of a cell might be saner overall.

**Comment by pchote** [comment] 2019-10-06 15:33
Subterranean movement is a good point - the proper EMP behaviour there is for the unit to move to a valid cell and surface before freezing its movement. The SpeedMultiplier workaround is more compatible with implementing this.

**Comment by tovl** [comment] 2019-10-06 15:44
I just checked: In the original Tiberian Sun, normal units hit with an EMP will still finish moving towards the center of the cell.

**Closed** 2019-10-06 19:28 UTC
Labels: Regression
