### ISSUE TITLE
Dogs will kill each other if attacking infantry at same time, only one dog remains alive

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#6798] opened 2014-10-19 22:42 UTC
If you press 2 or more dogs to attack an infantry unit at same time, and all the dogs jump at same time, there will be only 1 dog left, rest of the dogs are magically vanished from existence.

**Comment by TheRaffy** [comment] 2015-04-06 18:53
I have news here. I can reproduce this and found something unexpected.
Under special circumstances when 2 dogs attack 1 infantry at the same time all 3 units die.
I also can reproduce that (see picture). That might help detecting the issue. 
The positions of the dogs are important. At this screen I have 3 dogs, but will just attack with the upper 2 dogs. They will jump over the wall, what's fine to me, but then kill each other.

![radogbug](https://cloud.githubusercontent.com/assets/5147014/7009939/2e3d8c6a-dc9e-11e4-876f-86faaecea047.png)

**Comment by pchote** [comment] 2015-11-22 14:22
Reverse-duplicate of #7506.

**Closed by pchote** 2015-11-22 14:22 UTC
Labels: Bug, Red Alert
