### ISSUE TITLE
Exception while playing Red Alert commit f5d788f4fc39a4c8fff360de6c91db0774a685f6: Attempting to query the position of an invalid Target

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#16003] opened 2019-01-05 08:04 UTC
Hi,

While playing Red Alert commit f5d788f4fc39a4c8fff360de6c91db0774a685f6 the game crashed, with the exception log:

```bash
OpenRA engine version 25563
Red Alert mod version 25563
on map 2efd90a8e05d3c58b1c99e7cc863faafea0cfa0d (Engagement by Nuke'm Bro.).
Date: 2019-01-05 07:59:34Z
Operating System: Linux (Unix 4.20.0.1)
Runtime Version: Mono 5.16.0 (makepkg/bb3ae37d71a Sat Dec  8 13:21:35 CET 2018) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
  at OpenRA.Traits.Target.get_CenterPosition () [0x00051] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Mods.Cnc.Activities.Leap.Tick (OpenRA.Actor self) [0x00060] in <bd1354135dca41359e2bbf5004235481>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005f] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Mods.Cnc.Activities.LeapAttack.Tick (OpenRA.Actor self) [0x00037] in <bd1354135dca41359e2bbf5004235481>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005f] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Actor.Tick () [0x00010] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.World.Tick () [0x00046] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00237] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Game.Loop () [0x000d6] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Game.Run () [0x00042] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <f1dad0b2724c47d9bf4744734c94c5b6>:0 
```

I must admit I do not remember what I was doing (after all, it was quite unexpected), but my full logs and the replay are in:

[openra-ra-logs-25563-commit-f5d788f4fc39a4c8fff360de6c91db0774a685f6-20190105.zip](https://github.com/OpenRA/OpenRA/files/2729318/openra-ra-logs-25563-commit-f5d788f4fc39a4c8fff360de6c91db0774a685f6-20190105.zip).

My OS is Arch Linux.

Thanks for your time,
Brenton

**Comment by MustaphaTR** [comment] 2019-01-05 08:39
Probably a duplicate of #15993.

**Comment by pchote** [comment] 2019-01-05 09:37
Indeed. Closing as duplicate.

**Closed by pchote** 2019-01-05 09:37 UTC
