### ISSUE TITLE
No clean exit possible on failed server connection

### ISSUE THREAD

**Issue by mmmh81** [OpenRA/OpenRA#13329] opened 2017-05-21 11:56 UTC
Just after the end of a MP match yesterday (WIndows 10, 64 bit, release-20170421), the server connection failed while I was in the statistics menu. I could browse through all statistics, but not leave the game. I guess this was because the error message window blocked the "Close" button. I also tried "Escape" on the keyboard in vain. The only way out was to kill the programme in the task manager. Attaching replay and screenshot.
[OpenRA-2017-05-20T201912Z.zip](https://github.com/OpenRA/OpenRA/files/1016914/OpenRA-2017-05-20T201912Z.zip)
![noexit](https://cloud.githubusercontent.com/assets/12261410/26283700/2e77a3b2-3e2d-11e7-93af-43ffbddc1e09.png)

**Comment by rob-v** [comment] 2017-05-21 13:01
I am not sure about your situation with Statistics and hidden Close button, but in general, currently the (only?) way to return back in case of 'Connection Failed' message on screen is to click on Options button (ESC doesn't work, but mouse click yes). Not ideal, but better than having to kill the process.

**Comment by abcdefg30** [comment] 2017-05-21 15:13
Duplicate of #12314. Thanks for the report, though. :)

**Closed by abcdefg30** 2017-05-21 15:13 UTC
Labels: Bug
