### ISSUE TITLE
Hold click speed is too fast.

### ISSUE THREAD

**Issue by Atreedee** [OpenRA/OpenRA#13487] opened 2017-06-10 16:42 UTC
In Dune2000, when I try to move units while moving the mouse, most of the times it triggers the selecting rectangle, so it cancels the selection of the units I was trying to move. Delaying the hold click trigger some milliseconds would fix it.

**Comment by abcdefg30** [comment] 2020-08-29 19:30
Is this still an issue?

**Comment by deleted-user-1** [comment] 2020-08-29 19:57
> Is this still an issue?

Nothing has changed in the code as far as i can tell with regard to selection deadzone for LMB orders. The issue could be treated as a reverse duplicate of #17360, which contains more information.

**Comment by abcdefg30** [comment] 2020-08-29 19:59
Closing as reverse duplicate then.

**Closed by abcdefg30** 2020-08-29 19:59 UTC
Labels: Polish
