### ISSUE TITLE
Team colors in "All Players" spectator mode

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15833] opened 2018-11-18 18:26 UTC
Currently, while spectating team games in "All Players" view, "player stance color" show all players as beige. 

It would be interesting to have an additional toggle that shows each team in a different, predefined color. (colors in : minimap + health bars)

Colors could be predefined as : Red, Blue, Green, .... / or using the standard RA colors.

**Comment by matjaeck** [comment] 2018-11-20 13:18
Related to #15027.

**Comment by FRenzy-OpenRA** [comment] 2018-11-20 18:40
Yes indeed, haven't found it in search bar.

**Comment by matjaeck** [comment] 2019-06-16 17:18
This is also an issue ingame, the radar widget shows wrong colors too. This was already the case in 20180309.

**Comment by dragunoff** [comment] 2022-10-10 12:45
Duplicate of #7497 ?

**Comment by Mailaender** [comment] 2024-02-21 08:13
Duplicate of https://github.com/OpenRA/OpenRA/issues/2462

**Closed by Mailaender** 2024-02-21 08:13 UTC
Labels: Feature, UI
