### ISSUE TITLE
Single Click doesn't work on Mac OSX Ventura 13.2 after upgrade to 20230225 

### ISSUE THREAD

**Issue by carefreepineapple** [OpenRA/OpenRA#20738] opened 2023-03-11 06:33 UTC
## Issue Summary

on OSX 13.2 after upgrade from 20210321 to 20230225, single clicks are not recognized.  A double click is recognized as a single click.
DESCRIPTION
```
➜  ~ sw_vers
ProductName:		macOS
ProductVersion:		13.2
BuildVersion:		22D49
```

After upgrading from 20210321 to 20230225, i have to perform a double click to get it recognized as a single click.
Im using a logitech mx vertical plugged into KVM.  I also use a targus docking station that uses displaylink software.

uninstalling and rolling back to 20210321 fixed the issue for me.

Sometimes on 20230225 if I closed and reopened openra multiple times, I could get it to recognize single click properly.  Unfortunately this was tedious and not reliable, I could have to close and reopen openra 20+ times before I got it working properly.

## Reproduction

STEPS TO REPRODUCE THE ISSUE
On OSX 13.2, install latest openra cask, 20230225 at the time of this writing.  Im not sure if having the KVM or docking station is having an impact on the mouse input, but it very wall may.

## Expected behavior

EXPECTED BEHAVIOR
single clicks are recorded properly

## Screenshots / Screen recordings / Replays

n/a

ADDITIONAL INFORMATION
It should also be noted that after the upgrade to 20230225, I could no longer move the window from one display to another as the application would lock up.  Rolling back to 20210321 resolved this as well.
This may not be directly correlated with the single mouse click issue, but it could be.

**Comment by PunkPun** [comment] 2023-03-11 07:31
I have a Ventura 13.2 and it everything works as intended. Are you using an m1 pro mac? The exact same issue was reported for it #20715

**Comment by carefreepineapple** [comment] 2023-03-11 07:56
@PunkPun nope, i'm using the M2 mac pro, though it could very well be the exact same issue.

```
➜  ~ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.2 (22D49)
      Kernel Version: Darwin 22.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
    
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 22 days, 10 hours, 16 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,7
      Model Number: Z16S0005DLL/A
      Chip: Apple M2
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 8419.80.7
      OS Loader Version: 8419.80.7
    
      Hardware UUID: AFD7B92C-DE03-547C-BCE8-BC97132B3469
      Provisioning UDID: 00008112-001219CA14F1401E
      Activation Lock Status: Enabled
```

**Comment by PunkPun** [comment] 2023-03-11 08:01
Closing as duplicate #20715

**Closed as not planned by PunkPun** 2023-03-11 08:01 UTC
Labels: Bug

**Comment by PunkPun** [comment] 2023-03-11 08:02
You can check if their solution works for you

**Comment by PunkPun** [comment] 2023-04-12 10:13
Please test wether this [devtest build](https://github.com/PunkPun/OpenRA/releases/download/devtest-20230412/OpenRA-devtest-20230412.dmg) fixes your issue.
