### ISSUE TITLE
mapeditor: setup default players

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#9573] opened 2015-10-07 22:23 UTC
I miss this setting.

**Comment by penev92** [comment] 2015-10-07 22:41
I don't get what you miss. It is done automatically now, which means people no longer have issues because they forgot to press that button.

**Comment by kyrreso** [comment] 2015-10-07 23:30
did not know that.. But you have to set player spawn, and that means getting mcv or you have to find the code and code it out?
If no player spawns are set, then you cannot place multi units in editor...

**Comment by penev92** [comment] 2015-10-08 06:36
In that case you set the player spawn points. Then in `map.yaml` you remove the `SpawnMPUnits` trait from the world actor. That is the one that does the spawning of initial actors.
Taken from Fort Lonestar:
```
	World:
		-SpawnMPUnits:
		-MPStartLocations:
```

**Comment by abcdefg30** [comment] 2015-10-08 13:51
You can also add `PlayerReferences` in `map.yaml` by hand.

**Comment by abcdefg30** [comment] 2015-10-08 13:54
Wait actually, we could still add a function to add players in the editor.

**Comment by pchote** [comment] 2015-10-08 14:06
Duplicate of #2053 (actually closer to #4488, but there was an objection to keeping that as the master ticket for the player panel).

**Closed by pchote** 2015-10-08 14:06 UTC
Labels: Feature, Map Editor
