### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by ningwang747** [OpenRA/OpenRA#13435] opened 2017-06-03 07:11 UTC
[exception-2017-06-03T070725Z.log.zip](https://github.com/OpenRA/OpenRA/files/1049437/exception-2017-06-03T070725Z.log.zip)

**Comment by RoosterDragon** [comment] 2017-06-03 08:49
```
Red Alert Mod at Version release-20170527
on map 1c6bd120f5b724c5e14103a702caf648e427d33b (Countercross by Comrade Tiki).
Date: 2017-06-03 07:07:25Z
Operating System: OSX (Unix 16.6.0.0)
Runtime Version: Mono 5.0.1.1 (2017-02/5077205) CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Out of memory
GC Memory (post-collect)=351,365,872
GC Memory (pre-collect)=757,225,520
Working Set=615,952,384
Private Memory=615,956,480
Virtual Memory=1,860,829,184
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at OpenRA.Mods.Common.FileFormats.AudReader.LoadSound (System.IO.Stream s, System.Byte[]& rawData, System.Int32& sampleRate) [0x0006c] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at OpenRA.Mods.Common.AudioLoaders.AudFormat+<AudFormat>c__AnonStorey0.<>m__0 () [0x00002] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at System.Lazy`1[T].CreateValue () [0x00081] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/Lazy.cs:443 
  at System.Lazy`1[T].LazyInitValue () [0x00080] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/Lazy.cs:388 
  at System.Lazy`1[T].get_Value () [0x0003a] in /private/tmp/source-mono-2017-02/bockbuild-2017-02/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/Lazy.cs:339 
  at OpenRA.Mods.Common.AudioLoaders.AudFormat.GetPCMInputStream () [0x00001] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at OpenRA.Sound.LoadSound (OpenRA.ISoundLoader[] loaders, OpenRA.FileSystem.IReadOnlyFileSystem fileSystem, System.String filename) [0x00061] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Sound+<Initialize>c__AnonStorey0.<>m__0 (System.String s) [0x00000] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Exts.GetOrAdd[K,V] (System.Collections.Generic.Dictionary`2[TKey,TValue] d, K k, System.Func`2[T,TResult] createFn) [0x0000f] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Primitives.Cache`2[T,U].get_Item (T key) [0x00001] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Sound.PlayMusicThen (OpenRA.GameRules.MusicInfo m, System.Action then) [0x0005a] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Mods.Common.Traits.MusicPlaylist.Play () [0x00017] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at OpenRA.Mods.Common.Traits.MusicPlaylist.<Play>m__2 () [0x0002c] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at OpenRA.Sound.Tick () [0x00023] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00110] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.Loop () [0x000d6] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.Run () [0x00042] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <a32af65b47eb431c9a06ff1bce40d751>:0 
```

Duplicate of #12494.

**Closed by RoosterDragon** 2017-06-03 08:49 UTC
