### ISSUE TITLE
Manifest - Recursively include a folder path

### ISSUE THREAD

**Issue by Holloweye** [OpenRA/OpenRA#11729] opened 2016-07-28 19:03 UTC
The ability to include every file and subfolder recursively. In my mod I am working with a single file for each unit and I am using a folder structure to easily maintain and find units. Instead of having a huge YAML for all structures. But the manifest right now is not really great at handling this as I have to make a new entry for each file. The manifest is getting quite large.

How I would like it to work:

Now you have to do like this:
Rules:
	wwi|rules/player.yaml
	wwi|rules/palettes.yaml
	wwi|rules/world.yaml
	wwi|rules/misc.yaml
	wwi|rules/defaults.yaml
	wwi|rules/decoration.yaml
	wwi|rules/civilian.yaml
	...

I would like to be able to do this:
Rules:
	wwi|rules/**

Same goes for:
Rules, Sequences, TileSets, Cursors, Chrome, ChromeLayout, Weapons, Voices, Notifications, Music and Translations

**Comment by abcdefg30** [comment] 2016-07-28 19:35
Duplicate of #11326, I think.

**Closed by abcdefg30** 2016-07-28 19:35 UTC
Labels: Feature, Mod Support
