### ISSUE TITLE
northern shroud bug

### ISSUE THREAD

**Issue by runeavalon** [OpenRA/OpenRA#12424] opened 2016-11-24 15:47 UTC
I dont know if you all would call this a bug or not, i think it is. Anyway if you move units of any kind behind the northern shroud edge of the map all units and static defences wont trigger the attack by themselves. this allows you to sneak behind enemy base with for exemple a load of rocket soldiers in chinooks, without having to be afraid of the aa guns or missle defences or rocket soldiers placed there by the enemy team. I dont think this is an intentional thing. Let me know what you guys think of this. Cheers Ohmk Torque

**Comment by abcdefg30** [comment] 2016-11-24 15:55
Duplicate of #9552.

**Closed by abcdefg30** 2016-11-24 15:55 UTC
Labels: Bug
