### ISSUE TITLE
Memory Leak (dedicated server)

### ISSUE THREAD

**Issue by Jozodezokokotar** [OpenRA/OpenRA#10925] opened 2016-03-15 09:40 UTC
Hello guys,

I've run latest release over night in dedicated server mode.
This morning I noticed that memory consumption is 10 times bigger than it was yesterday.
This is called a memory leak and it reveals a severe coding error / incomplete garbage collection / ...

Let me know how can I help you with testing / providing data.
![snap6](https://cloud.githubusercontent.com/assets/16616074/13773595/537e8a5a-ea9a-11e5-9d86-063f332b19d7.png)

Thanks

**Comment by pchote** [comment] 2016-03-15 10:00
That usage looks fairly typical for release-20151224, especially if you sync maps with the resource center.  The server aggressively caches map data, so the memory usage does grow over time as players switch between maps.  This was a design decision rather than an unintentional leak.

We are aware that server owners didn't like that behavior, and the next release will completely change the way that maps are loaded and cached to reduce this.

**Comment by Jozodezokokotar** [comment] 2016-03-15 12:14
You are right, memory consumption depends dramatically on number of maps loaded.
With built-in maps it eats approx 60 MB, however with all ra maps from resource center (32 MB disk space) we are at 450 MB of memory. Whoa! :-)

I appreciate that decision, In the meantime I'll disable custom maps. Memory is very limited (and expensive) on my Virtual Server.

**Comment by pchote** [comment] 2016-03-15 13:38
Closing as duplicate of #10433 (which is already fixed on bleed).

**Closed by pchote** 2016-03-15 13:38 UTC
