### ISSUE TITLE
A tiberium tile that is impossible to harvest

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#5547] opened 2014-06-04 21:27 UTC
First I noticed that there was a tile with Tiberium the harvesters avoided and when it was the only tile left I marked one harvester and specified it to harvest the tile and saw that the red line indicating the units movement would not go to this tile no matter what. I then tried a number of other harvesters and no luck getting them to harvest it. I tried to walk a infantry unit (commando) on the tile and he would walk on it, then removed him to see it that changed anything but it diden't so i damaged the tiberium with a mammoth tank, no change, then i (killed) the tiberium with 3 shot then 15 shots but could not kill the tiberium. What i mean is that the animation of tiberium was gone but the harvesters still hade the attack symbole on the tile but would not enter the tile still.
![tiberium that wont be harvested any time soon 1](https://cloud.githubusercontent.com/assets/7798635/3180271/130cafbc-ec2f-11e3-8e2e-6d52ce2e43e5.png)
##

**Comment by Snurre86** [comment] 2016-11-21 05:54
I still get this in short multiplayer games online. Version 2006-10-19

**Comment by StexoO** [comment] 2016-11-21 19:09
I finally have a clue, at least for RA, and reproducable on any ore tile of any map (release 20161019)
1. Stop all harvesters on the map (S) so no tile can be reserved (https://github.com/OpenRA/OpenRA/issues/5547#issuecomment-47705700)
2. Select one harvester and tell it to harvest some ore
4. When it is on the ore tile and has started to harvest (not sure if it's required), stop it (S) and kill it
5. Try to harvest the tile with any other harvester, yours or not, newly built or not

**Comment by pchote** [comment] 2016-11-21 19:11
> pchote commented on 5 Jun 2014 
>
> This happens when you have multiple harvesters, and another harvester has reserved that cell. This is one of a number of issues with the current harvester code.

It looks like the reservations isn't being removed when a harvester is killed.

**Comment by Snurre86** [comment] 2017-03-19 16:39
Figured it out!
https://youtu.be/2pQJKjLtKXo

**Comment by Snurre86** [comment] 2017-03-21 21:48
See #10500

**Comment by Snurre86** [comment] 2017-03-26 11:13
@pchote 

> It looks like the reservations isn't being removed when a harvester is killed.

This is not the only way this happens, but it is a guaranteed way to reproduce the issue, that's all.

**Comment by pchote** [comment] 2017-04-22 20:06
I tracked this down to `FindBidiPath` failing because the unit is blocking its own cell in the reverse destination -> start check.  This in turn happens because `Mobile.IsBlockedBy` considers `self` as a blocker, which is an old known issue that also causes #9378.

We original "fixed" that issue in 8676562d4712868478f95846fbdf08f8fe509647, but that was found to introduce even worse regressions from code that relied on that bogus behaviour, so we reverted it in a13f9ea3eb316c8d425d43b626e29ff522071a8a.

**Comment by matjaeck** [comment] 2018-08-13 14:10
> It looks like the reservations isn't being removed when a harvester is killed.

> This is not the only way this happens, but it is a guaranteed way to reproduce the issue, that's all.

I can't reproduce the issue in in RA of playtest-20180729.
![101](https://user-images.githubusercontent.com/37185497/44036896-37478fe6-9f13-11e8-82d1-e7f1b8c75906.gif)

The cell can also be harvested when the harvester started harvesting and a stop order was issued before it was killed.

**Comment by pchote** [comment] 2018-08-13 14:15
This was recently fixed by #15339.

**Closed by pchote** 2018-08-13 14:15 UTC
Labels: Bug
