### ISSUE TITLE
Doesn't work d2k-mod and ra-mod at release-20210321

### ISSUE THREAD

**Issue by natomist** [OpenRA/OpenRA#19999] opened 2022-04-23 10:56 UTC
OS: Kubuntu 21.10
I downloadeds AppImage from https://www.openra.net/download/
The image "Tiberian Dawn" works fine. 
But Dune 2000 and Red Alert shows loading splash infinitely.
![d2k](https://user-images.githubusercontent.com/25938138/164891568-dbda87d3-bbff-4d25-bcdc-78c5647b6957.png)
![ra](https://user-images.githubusercontent.com/25938138/164891584-59af3668-c6c7-419c-a675-7a3e71eac98f.png)

Release "Release 20200202" works fine for all mods.

**Comment by pchote** [comment] 2022-04-23 11:03
This is caused by https://gitlab.freedesktop.org/mesa/mesa/-/issues/4847.

Setting the environment variable `GALLIUM_THREAD=0` or installing the Flatpak version (which has been patched with this workaround) will fix this.

**Comment by abcdefg30** [comment] 2022-04-24 19:07
Closing as already resolved for the next release.

**Closed as completed by abcdefg30** 2022-04-24 19:07 UTC
