### ISSUE TITLE
MapSize/Bounds calculation when creating new map is broken

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10944] opened 2016-03-18 23:01 UTC
If I tell the editor to create a 64x80 map, it creates a 64x96 map. 64x78 resulted in 64x94. So it always adds 16 to the height. Pretty annoying.

**Comment by pchote** [comment] 2016-03-18 23:31
When a map is created it will add `MapGrid.MaximumTerrainHeight` to the height to account for the behaviour of the heightmap at the north edge of the map.  This is *supposed* to be cropped out by the border, but it looks like this was broken.  Should be an easy fix (one or two lines max).

**Comment by GraionDilach** [comment] 2016-03-19 10:39
Probably never worked and sounds like the reason why the TS map importer overshoots the map cordons now, á lá #10686.

**Comment by GraionDilach** [comment] 2016-03-23 15:37
This is a duplicate of #8806 though.

**Comment by obrakmann** [comment] 2016-03-27 21:33
This has more info, so I'll close #8806 instead of this one.

**Comment by GraionDilach** [comment] 2016-03-27 23:36
For the record though, in some ways it IS a regression, @obrakmann.

When the TS map importer was at it's first run (before pre-merge) it undershoot the map cordons, so all maps ended up losing some of their bottom cells which converted into map cordon. But that didn't crashed on people.

Now it tries to draw more rows than what actually exist if the map was imported. So this is quite well related to #10686 as well.

**Closed** 2016-04-01 15:04 UTC
Labels: Bug, Map Editor, Tiberian Sun
