### ISSUE TITLE
Lobby admin tooltip shows the local (player) client instead of "local host" on OS X

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7303] opened 2015-01-09 22:13 UTC
![screen shot 2015-01-10 at 10 36 46](https://cloud.githubusercontent.com/assets/167819/5688238/98b0bc6c-98b9-11e4-9bd3-72a6ecf164de.png)

This was apparently not reproduced by the windows-using players in the server.

**Comment by obrakmann** [comment] 2015-01-10 16:45
Confirmed that it doesn't happen on release-20141029

**Comment by Mailaender** [comment] 2015-01-11 10:10
This happened before https://github.com/OpenRA/OpenRA/issues/3833 and was fixed in https://github.com/OpenRA/OpenRA/pull/4108. The line was last changed in https://github.com/OpenRA/OpenRA/pull/7066. I can't reproduce this issue. Maybe your `IPAddress.Loopback` is set to something non-standard.

**Comment by obrakmann** [comment] 2015-01-11 11:19
Seems to happen on OS X only then.

![screenshot from 2015-01-11 12 16 45](https://cloud.githubusercontent.com/assets/4331210/5695047/058061ee-998c-11e4-8e2b-dc5dbe302a96.png)

**Comment by Phrohdoh** [comment] 2015-01-11 11:27
![](http://i.imgur.com/QSCLDkG.png)

**Comment by obrakmann** [comment] 2015-01-11 11:34
That IP address is indeed the correct one (ie., mine), so Phrohdoh on OS X doesn't see the problem, either. Do you have any fancy networking setup on your machine, pchote?

```
$ host 77.20.66.14
14.66.20.77.in-addr.arpa domain name pointer ip4d14420e.dynamic.kabel-deutschland.de.
```

Anyway, I'll take this off the milestone.

**Comment by pchote** [comment] 2015-01-11 11:34
looks like you all are only testing with dedicated servers - try it with a regular one.

**Comment by Mailaender** [comment] 2015-01-11 11:36
@pchote Can you post your output of

```csharp
Console.WriteLine(IPAddress.Loopback.ToString());
```

**Comment by Phrohdoh** [comment] 2015-01-11 12:15
Non-dedicated exposes the issue of IPs for me:

![](http://i.imgur.com/i0jSFzl.png)

**Comment by pchote** [comment] 2015-01-11 13:37
Restored labels and milestones since @Phrohdoh has confirmed this.

**Comment by Mailaender** [comment] 2015-01-11 13:39
I still can't reproduce this so you will have to fix this yourselves. Also can't find suspicious changes in https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.RA/Widgets/Logic/ClientTooltipLogic.cs so I doubt this is a regression.

**Comment by pchote** [comment] 2015-01-13 09:04
This is a regression, introduced by 962d8fe74f16c7464b217b157265636c7cb26372.

Updating from Mono.Nat 1.1.0 to 1.2.21.0 appears to have fixed a bug that was preventing some bogus code on our end from running, and so we now see the (correctly) bogus IP under OSX.  Mono.Nat must still be broken under Linux if you aren't seeing the problem there.

The offending lines are ClientTooltipLogic.cs:L79-80, which checks if the client IP determined by the *remote server* is localhost (which occurs only for the admin of a non-dedicated server), and replaces it with the external IP for the *local client*.  That's completely wrong.

**Comment by Mailaender** [comment] 2015-01-17 07:30
Nope, downgrading to https://smuxi.im/attachments/download/78/mono-nat-1.1.0-bin.zip fixes nothing. Both the NAT discovery and the verbose NAT logging does not work at all for me anymore on Linux.

**Closed** 2015-01-17 09:57 UTC
Labels: Bug, UI
