### ISSUE TITLE
White pixels in desert tileset

### ISSUE THREAD

**Issue by MrRocket50** [OpenRA/OpenRA#15548] opened 2018-08-21 01:28 UTC
While I'm playing Red Alert or Tiberian Dawn the maps that uses desert tileset appear with white pixel mainly in the houses and the bridges.

![screen2](https://user-images.githubusercontent.com/28467698/44375051-0a6b0380-a4c8-11e8-909a-d855e21f52d1.PNG)

**Comment by abcdefg30** [comment] 2018-08-21 02:30
Do you happen to know if that was already the case in the last release (20180307), or just occurs on the playtest (20180729)?

**Comment by MrRocket50** [comment] 2018-08-21 02:51
It occurs in 20180307 and some older versions I've played. I reinstalled the Windows but this graphical glitch still occurs.

**Comment by GraionDilach** [comment] 2018-08-21 04:36
Could you please try TS to create a screenshot in water? I suspect #8596.

**Comment by airetaM** [comment] 2018-08-21 08:48
I had the same glitch on my old laptop a few years ago.

**Comment by MrRocket50** [comment] 2018-08-23 12:30
@GraionDilach
![untitled](https://user-images.githubusercontent.com/28467698/44525341-0f41da00-a6b7-11e8-9efe-fdc89e4924bb.PNG)

**Comment by pchote** [comment] 2018-08-23 12:32
Ok, that confirms this is a duplicate of #8596, so closing.

**Closed by pchote** 2018-08-23 12:32 UTC
Labels: Bug
