### ISSUE TITLE
Air transports take off and land for each entering inf

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16740] opened 2019-06-30 16:54 UTC
Minor regression/remaining issue from #16509:

Transport helis take-off and land for each individual entering infantry if the transport had already force-landed before the infantry is ordered to enter.

**Comment by Punsho** [comment] 2019-06-30 17:21
I thought that this was intentional

**Comment by reaperrr** [comment] 2019-06-30 17:25
I meant that if you order multiple infantry at once to enter the transport, the transport will take off after the first infantry enters, then immediately lands again to let then 2nd enter, etc.

**Comment by Punsho** [comment] 2019-06-30 17:46
![Chinook](https://user-images.githubusercontent.com/37534529/60400077-aef1b380-9b77-11e9-918b-39a0575eca64.gif)

![Chinook 2](https://user-images.githubusercontent.com/37534529/60400095-faa45d00-9b77-11e9-9d4a-3534d5cf98fc.gif)

I don't see the issue

**Comment by reaperrr** [comment] 2019-06-30 18:04
It doesn't happen when the infantry are all relatively close to each other and arrive at nearly the same time.

**Comment by Punsho** [comment] 2019-06-30 18:14
And that is why it's not a bug. I can have even a conga line of infantry streaming in and it will stay landed for each one

**Comment by pchote** [comment] 2019-06-30 18:18
The real issue is clear in your second gif: force-landed helicopters should not automatically take off after passengers enter or leave.

**Closed** 2019-07-01 14:00 UTC
Labels: Polish, Regression
