### ISSUE TITLE
Clicking on an online game to join will launch OpenRA with the Directory.GetCurrentDirectory() returning the browser's directory

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#8592] opened 2015-06-28 19:43 UTC
Causing a crash when switching mods for sure.

**Comment by pchote** [comment] 2015-06-28 20:12
Openra itself is perfectly happy with being invoked from any dir. The modchooser must be defining bogus file paths (missing the initial ./) if it is crashing

**Comment by GraionDilach** [comment] 2015-06-28 20:18
Hm, true!

**Comment by Mailaender** [comment] 2015-06-29 05:24
I can't reproduce so I believe this is Windows .NET specific.

**Comment by RoosterDragon** [comment] 2015-06-29 19:22
A workaround I've employed previously is to do:
```Directory.SetCurrentDirectory(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))``` as the first line in ```Main``` in order to ensure the current directory is actually what you expect. This way if another process launches you with an unexpected current directory all your relative paths don't explode.

**Comment by pchote** [comment] 2015-06-29 23:32
You would need to be careful not to break the utility (again).  That explicitly cares about the working dir.

**Comment by pchote** [comment] 2015-07-14 19:55
For what its worth, this is exactly the kind of thing I was trying to avoid by having platform-specific validation of the url and file handlers.

**Comment by obrakmann** [comment] 2015-07-14 20:04
[Here's an installer](https://seacloud.cc/d/5d1adbebce/files/?p=/OpenRA-release-20150614-with-dir-fix.exe) with a proposed fix for this (see diff below). It's compatible with our current stable release. It would be nice if someone on Windows could

1. reproduce the bug
2. confirm that the bug is fixed with the linked installer

```diff
diff --git a/OpenRA.GameMonitor/GameMonitor.cs b/OpenRA.GameMonitor/GameMonitor.cs
index bbf9c74..8d648ee 100644
--- a/OpenRA.GameMonitor/GameMonitor.cs
+++ b/OpenRA.GameMonitor/GameMonitor.cs
@@ -28,6 +28,8 @@ static void Main(string[] args)
                        var executableDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                        var processName = Path.Combine(executableDirectory, "OpenRA.Game.exe");
 
+                       Directory.SetCurrentDirectory(executableDirectory);
+
                        var psi = new ProcessStartInfo(processName, string.Join(" ", args));
 
                        try
```

**Comment by penev92** [comment] 2015-07-14 21:20
@pchote that has nothing to do with the platform-specific validation of the url and file handlers though.

**Closed** 2015-07-15 16:24 UTC
Labels: Crash, OS: Windows
