### ISSUE TITLE
Allow custom resolutions in full-screen mode

### ISSUE THREAD

**Issue by SteamsDev** [OpenRA/OpenRA#14903] opened 2018-03-11 00:21 UTC
So I don't have a very good laptop (I think @Mailaender and @abcdefg30  would know that by now), and I thought about something which might not have been thought about, but I think it should be addressed for older PCs: Allow for other custom resolutions (for example 1024x768) in full-screen mode. It would definitely help to increase the performance of OpenRA on an older system and I think it would be a great addition to OpenRA in general. Is this possible with the engine that OpenRA runs on? I'm curious.

**Comment by Mailaender** [comment] 2018-03-11 11:02
It wouldn't really help as performance doesn't scale with the screen resolution. The sprites have a fixed size. You can double it in the settings, but a dynamic setting would cause visual glitches.

**Comment by pchote** [comment] 2018-03-11 14:53
Closing as a duplicate of #10382.

**Closed by pchote** 2018-03-11 14:53 UTC
Labels: Performance, Question / Support
