### ISSUE TITLE
restarting a replay desyncs the replay

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13312] opened 2017-05-17 01:42 UTC
I think this happens in bleed and I think it might have something  to do with recent PR:
https://github.com/OpenRA/OpenRA/pull/13273
New random seed at the restart of the replay restart might be the cause of the desync.

I'm not 100% sure about this, I'm on my mod branch with cherry picked random seed fix mentioned above. My guess is the same thing will happen on current bleed too.

**Comment by pchote** [comment] 2017-05-17 07:13
The AI's choices get baked into the order stream, which are then replayed like any other player in the replay.  The AI code shouldn't be running at all in replays, so something much deeper than the seed is bogus if #13273 did introduce this.

**Comment by forcecore** [comment] 2017-05-17 12:54
Reproduced this bug in bleed, commit 0e3cc1ad28b3fd992566a070c81158ed2363bf42. (just one commit behind current head, as the build is failing in current head)
And like you mentioned, it doesn't have anything to do with Random seed as I've experienced this bug in branch without the random seed commit.

When I experience desync, I see projectiles on screen during game restart. I think that has something to do with desync.

This is the replay with desync.
[desync.zip](https://github.com/OpenRA/OpenRA/files/1007749/desync.zip)
[syncreport-2017-05-17T124704Z.zip](https://github.com/OpenRA/OpenRA/files/1007750/syncreport-2017-05-17T124704Z.zip)

Steps to reproduce, including game setup
https://youtu.be/wjrK-XYjD3E

**Comment by rob-v** [comment] 2017-05-17 13:40
@forcecore Re failing head build - You might need to update your workspace - .sln for VS was updated - there is one file LobbyMapPreviewLogic -> MapPreviewLogic renamed.
There is some error now, but I think it is not related, maybe temporary:
1) Invalid : C:\projects\openra\OpenRA.Test.dll
File not found: C:\projects\openra\OpenRA.Test.dll

**Comment by forcecore** [comment] 2017-05-18 15:08
Pausing the replay before restarting the games solves the problem. The introduction of pause in restart function will solve the issue.

**Comment by pchote** [comment] 2018-08-13 08:40
Closing as reverse-duplicate of #14104.

**Closed by pchote** 2018-08-13 08:40 UTC
Labels: Bug
