### ISSUE TITLE
Iron curtain effect transfered to MCV on deploy.

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#14063] opened 2017-09-23 04:15 UTC
First i hope i post this in the right place.

I noticed that IC effect shuts off when passing from conyard to mcv and from mcv top conyard
I was wondering is it is intended, a bug, something that never been reported or never bothered people.

I would gladly see the effect transfered one to another.

Example 

Lone MCV caught off guard, saved by IC and can deploy in MCV still under IC protection for the remaining time.

Conyard about to die, saved by IC, repacked and still under IC effect while getting away.

Both thing sounds good to me.

**Comment by GraionDilach** [comment] 2017-09-23 04:18
Yes, you posted at the right place, but this is a duplicate of #9940.

**Comment by WhoCaresora** [comment] 2017-09-23 11:53
My bad then, i intended a search before posting but i diden't find the one you linked me.

**Closed** 2017-09-23 19:51 UTC
