### ISSUE TITLE
No super-weapons option in skirmish/multiplayer

### ISSUE THREAD

**Issue by SMPJavan** [OpenRA/OpenRA#7523] opened 2015-02-22 19:03 UTC
It would be quite nice to be able to disable super-weapons in skirmishes and multiplayer games. I'd be happy to implement this feature.

**Comment by deniz1a** [comment] 2015-02-22 19:22
Yes, the medium tech level removes super weapons but it also removes other high tech units/structures.

**Comment by penev92** [comment] 2015-02-22 19:48
Yes please. No superweapons lobby option.

**Comment by LipkeGu** [comment] 2015-02-22 21:13
duplicate of: #6583, #4957

is already includeded ... see: #6583

**Comment by Mailaender** [comment] 2015-02-24 05:29
See https://github.com/OpenRA/OpenRA/issues/4957#issuecomment-48833361

**Closed by Mailaender** 2015-02-24 05:29 UTC

**Comment by LipkeGu** [comment] 2015-02-26 20:36
maybe we should enable this function as lobby option but disable it by default :/ as @chrisforbes already said in another PR

**Comment by Mailaender** [comment] 2016-01-24 12:44
See https://github.com/OpenRA/OpenRA/pull/10580.
