### ISSUE TITLE
Spectators can't select multiple buildings with a double click

### ISSUE THREAD

**Issue by Elizadmin** [OpenRA/OpenRA#13254] opened 2017-05-06 16:40 UTC
Release-20170421.
As a player you can select all of your flame turrets by double clicking on one of them and you can see what area is defended.
As a spectator you can't do the same.

![control_area](https://cloud.githubusercontent.com/assets/25843400/25774207/656efc10-328b-11e7-8caa-fd39a5caa33a.jpg)

**Comment by aydjay** [comment] 2017-05-06 18:20
I've confirmed and fixed this locally - I will submit a PR.

**Comment by pchote** [comment] 2017-05-06 18:28
Closing as duplicate of #9492.

**Closed by pchote** 2017-05-06 18:28 UTC
Labels: Bug
