### ISSUE TITLE
managing games on dedicated servers

### ISSUE THREAD

**Issue by Fahrradkette** [OpenRA/OpenRA#3529] opened 2013-07-06 00:19 UTC
Admins of dedicated servers should be able to set spots and teams. There should also be a vote for the admin role implemented so "dickhead admins" can get replaced by more reasonable people. In addition, kicking by admins shoudn't be allowed but only a remove vote. On top of it, the kick vote should also be possible during running games.

on non-dedicated servers, admin-kick should be still allowed, also ingame kick.

**Comment by pchote** [comment] 2015-11-22 01:16
Reverse duplicate of #6538.

**Closed by pchote** 2015-11-22 01:16 UTC
Labels: Dedicated, Idea
