### ISSUE TITLE
Unexpected behavior while switching between groups

### ISSUE THREAD

**Issue by ooshlablu** [OpenRA/OpenRA#17678] opened 2020-02-13 18:42 UTC
## Issue Summary

I've noticed an issue where if I have a group selected and then call another group with the numeric shorcuts that the orders will be sent to the previously selected groups.

## Reproduction

For instance, if I have 2 groups assigned (1 and 2), I will:
  - Select group 1 via using the `1` key
  - Give them a command
  - Select group `2` via the 2 key
  - Give them a command
  - Group 1 will start moving

Each time, the group that is receiving orders will be highlighted, but the previous group will obey the commands.

I've notice this behavior on MacOS Mojave and Catalina, and on Ubuntu 18.04. I have not tried on other OS's 

My current workaround is to switch to a group that doesn't exist, for instance "3", and then switch to the group that I am intending to command.

I believe this has existed for the past 2 releases (20200202 and 20191117), but I can't confirm for sure.

## Screenshots / Screen recordings / Replays

I'll figure out a way to get you a video.

**Comment by abcdefg30** [comment] 2020-02-13 21:25
Duplicate of #16275.

**Closed as completed by abcdefg30** 2020-02-13 21:25 UTC
Labels: Bug

**Comment by michuzet** [comment] 2020-04-28 16:27
@ooshlablu It's considered here like obsolete issue, but has been around since 2017...

Hilarious guys! I've checked new playtest version and it's still here. Why ooshlablu and mine requests are closed?!

**Comment by abcdefg30** [comment] 2020-04-28 16:28
#16275 is not closed. This was closed because we already have #16275.

**Comment by michuzet** [comment] 2020-04-28 16:30
@abcdefg30 OK, sorry, my fault, I missed the status of first one.
Do you need anything from us to target the issue?

**Comment by abcdefg30** [comment] 2020-04-28 16:48
Actually nothing since you already gave us the reproduction steps. The problem was that the problem proofed hard to reproduce (I think I was the only one in the dev team?) and that someone would have needed to invest the time to debug the issue.
Saying that, I just found an easier way to reproduce this and potentially even fix the issue: https://github.com/OpenRA/OpenRA/issues/16275#issuecomment-620726559
