### ISSUE TITLE
Game crashes with SDL_VIDEODRIVER set to Wayland

### ISSUE THREAD

**Issue by An4cl3t0** [OpenRA/OpenRA#20014] opened 2022-04-28 21:46 UTC
Hi,
the game crashes with SDL_VIDEODRIVER set to Wayland.

- Operating System:  ARCH LINUX
- OpenRA Version: release-20210321
- OpenRA Mod: no mod
- Source: Arch Community Repo
- GPU: Intel HD 620

log
```
Platform is Linux
Engine version is release-20210321
Renderer initialization failed. Check graphics.log for details.
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0018a] in <56f19cef6d9e4065b64bc91b24abee63>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00006] in <56f19cef6d9e4065b64bc91b24abee63>:0 
  at OpenRA.Launcher.Program.Main (System.String[] args) [0x00044] in <9cbebe5c92b247ee9d4a064d46edae24>:0 
```

graphics.log 
```
System.InvalidOperationException: No supported OpenGL profiles were found.
  at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor (OpenRA.Primitives.Size requestEffectiveWindowSize, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile requestProfile, System.Boolean enableLegacyGL) [0x000b7] in <74b0cc0afb3241f4a25e710bf71641b8>:0 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow (OpenRA.Primitives.Size size, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile profile, System.Boolean enableLegacyGL) [0x00000] in <74b0cc0afb3241f4a25e710bf71641b8>:0 
  at OpenRA.Renderer..ctor (OpenRA.IPlatform platform, OpenRA.GraphicSettings graphicSettings) [0x00057] in <56f19cef6d9e4065b64bc91b24abee63>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00227] in <56f19cef6d9e4065b64bc91b24abee63>:0 
System.InvalidOperationException: No supported OpenGL profiles were found.
  at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor (OpenRA.Primitives.Size requestEffectiveWindowSize, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile requestProfile, System.Boolean enableLegacyGL) [0x000b7] in <74b0cc0afb3241f4a25e710bf71641b8>:0 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow (OpenRA.Primitives.Size size, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile profile, System.Boolean enableLegacyGL) [0x00000] in <74b0cc0afb3241f4a25e710bf71641b8>:0 
  at OpenRA.Renderer..ctor (OpenRA.IPlatform platform, OpenRA.GraphicSettings graphicSettings) [0x00057] in <56f19cef6d9e4065b64bc91b24abee63>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00227] in <56f19cef6d9e4065b64bc91b24abee63>:0
```

Tried to run the game with SDL_VIDEODRIVER=x11 and it starts but it freezes at loading screen.
Within the 2 problems I think It's worth more to fix the Wayland one. :)

Thanks

**Comment by pchote** [comment] 2022-04-28 21:50
The x11 freeze is caused by a deadlock in mesa's gallium driver. Set the environment variable to `GALLIUM_THREAD=0` to work around it.

The current release ships quite an old version of SDL2. The next release will update that so should *hopefully* behave better under Wayland (please feel free to try compiling the bleed branch and report back!)

**Comment by Mailaender** [comment] 2022-06-14 19:04
I also get the freeze when the shellmap should appear with an NVIDIA Optimus Intel combination on the current release. I can confirm that https://github.com/OpenRA/OpenRA/pull/19897 resolves it. The application icon is still X11 so this might be some kind of fallback.

**Comment by Mailaender** [comment] 2022-08-04 09:07
I just tested `SDL_VIDEODRIVER=wayland ./launch-game.sh` on @openSUSE 15.4 and it still crashes:
```
ANGLE: SDL init failed: wayland not available
ANGLE: SDL window creation failed: wayland not available
Modern: SDL init failed: wayland not available
Modern: SDL window creation failed: wayland not available
Embedded: SDL init failed: wayland not available
Embedded: SDL window creation failed: wayland not available
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 164
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 382
ANGLE: SDL init failed: wayland not available
ANGLE: SDL window creation failed: wayland not available
Modern: SDL init failed: wayland not available
Modern: SDL window creation failed: wayland not available
Embedded: SDL init failed: wayland not available
Embedded: SDL window creation failed: wayland not available
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 164
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:line 382

**Comment by Mailaender** [comment] 2022-10-09 07:55
@teinarss can you update NuGet?

**Comment by Mailaender** [comment] 2022-11-17 10:05
@teinarss can you package: https://github.com/OpenRA/SDL2-binaries/actions/runs/3487207508 please? https://github.com/OpenHV/OpenHV/issues/649#issuecomment-1317814700 indicates the latest SDL2 version solves it.

**Comment by Mailaender** [comment] 2022-11-19 17:40
> make TARGETPLATFORM=unix-generic
> SDL_VIDEODRIVER=wayland ./launch-game.sh Game.Mod=ra

resolves it, so it is clearly our pre-packaged version.

**Comment by Mailaender** [comment] 2023-06-08 08:43
@penev92 do you want to tag a new NuGet release?

**Comment by penev92** [comment] 2023-06-08 08:45
There are 4 NuGets that need to be updated, all 4 with a minor open PR. I would love to have those all merged first and then tag a new version for each of them, then update OpenRA in one go.

**Comment by Mailaender** [comment] 2023-06-11 08:36
They still crash with

```
ANGLE: SDL window creation failed: Could not initialize OpenGL / GLES library
Modern: SDL window creation failed: Could not initialize OpenGL / GLES library
Embedded: SDL window creation failed: Could not initialize OpenGL / GLES library
System.InvalidOperationException: No supported OpenGL profiles were found.
  at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor (OpenRA.Primitives.Size requestEffectiveWindowSize, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile requestProfile, System.Boolean enableLegacyGL) [0x00101] in OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:163 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow (OpenRA.Primitives.Size size, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile profile, System.Boolean enableLegacyGL) [0x00000] in OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:21 
  at OpenRA.Renderer..ctor (OpenRA.IPlatform platform, OpenRA.GraphicSettings graphicSettings) [0x0003e] in OpenRA/OpenRA.Game/Renderer.cs:78 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0024e] in OpenRA/OpenRA.Game/Game.cs:379 
ANGLE: SDL window creation failed: Could not initialize OpenGL / GLES library
Modern: SDL window creation failed: Could not initialize OpenGL / GLES library
Embedded: SDL window creation failed: Could not initialize OpenGL / GLES library
System.InvalidOperationException: No supported OpenGL profiles were found.
  at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor (OpenRA.Primitives.Size requestEffectiveWindowSize, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile requestProfile, System.Boolean enableLegacyGL) [0x00101] in OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:163 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow (OpenRA.Primitives.Size size, OpenRA.WindowMode windowMode, System.Single scaleModifier, System.Int32 batchSize, System.Int32 videoDisplay, OpenRA.GLProfile profile, System.Boolean enableLegacyGL) [0x00000] in OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:21 
  at OpenRA.Renderer..ctor (OpenRA.IPlatform platform, OpenRA.GraphicSettings graphicSettings) [0x0003e] in OpenRA/OpenRA.Game/Renderer.cs:78 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0024e] in OpenRA/OpenRA.Game/Game.cs:379 
```

**Comment by Mailaender** [comment] 2023-06-11 11:30
I came up with a fix https://github.com/OpenRA/SDL2-CS/pull/11 that works on my system.

**Closed as completed** 2023-06-12 17:57 UTC
Labels: Crash, OS: Linux
