### ISSUE TITLE
Make gap generator/MGG render fog circle instead of shroud

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#15364] opened 2018-07-21 17:48 UTC
I remember seeing a discussion regarding this and have had a search but couldn't find a related PR or issue, so I thought I'd create one.

Currently the gap generator and MGG render shroud regardless of whether explored map is enabled or not, I think it would be better to render fog when fog of war is enabled, and shroud otherwise, the current implementation just gives away the position when explored map is enabled, or when fog is enabled and the area has been scouted.

I found the following links in which @pchote makes the suggestion, and, assuming I understand him correctly, I agree with most of his ideas on this.

* http://logs.openra.net/?year=2015&month=02&day=22#14:43:56
* http://logs.openra.net/?year=2014&month=10&day=26#01:35:55

The part I don't agree with, is actively hiding the building previews underneath, I think having them just instantly disappear when the gap generator is built / the MGG comes into range would be a dead giveaway, also what do you do in the scenario where a building preview under fog is part covered by the gap fog?

**Comment by pchote** [comment] 2018-07-22 13:17
> what do you do in the scenario where a building preview under fog is part covered by the gap fog?

The same as we do when a building preview under fog is part covered by shroud - show the preview unless all the tiles in the footprint are covered by the gap-fog.

**Comment by GraionDilach** [comment] 2018-07-22 13:19
I hope this is suggested only as a mod balance suggestion and not as an engine feature replacement. The current GapGen mechanic is the WW accurate one.

**Comment by AMHOL** [comment] 2018-07-23 01:36
> what do you do in the scenario where a building preview under fog is part covered by the gap fog?

>> The same as we do when a building preview under fog is part covered by shroud - show the preview unless all the tiles in the footprint are covered by the gap-fog.

I think that still opens the issue of buildings disappearing / appearing out of nowhere and giving it away, I think the best course of action in that scenario is to just show the frozen actor (or whatever it's called) preview, as happens now with buildings under fog that aren't actually there/in camo state.

**Comment by AMHOL** [comment] 2018-07-23 01:38
> I hope this is suggested only as a mod balance suggestion and not as an engine feature replacement. The current GapGen mechanic is the WW accurate one.

I get that, yes it is a balance issue rather than a bug / not replicating the original properly, but as pchote said, the original didn't have fog of war so the behaviour was appropriate there.

**Comment by matjaeck** [comment] 2018-07-23 10:32
I could imagine that the proposed change would work for the ~30 players that play the game "competitively" (or whatever you call a "league" in which half of the players use macro scripts aka cheat) and make the MGG more useful in 1v1 games. However, I never heard such complaints from any casual players in big (chaotic) teamgames. 

I see Gap Generators and MGG used A LOT there. The black shroud also creates such a different "feel" than a FOW-generator would, it could never replace it. While not happening in 1v1, I often see people build multiple decoy MGG or position the MGG not in the middle of a blob but at the edges to deter artillery and V2 force fire. When you buid enoygh of them it becomes quite scary for the eneny team.

Bottom line: Yes, MGG can give away your position and yes, the ~30 players that define themselves as competitive community - an attribute they don't deserve because of widespread cheating - don't use it.

However, it is all completely irrelevant for RA or OpenRA. Nobody except these few people has an issue with that iconic unit.

To be very clear: I don't see that there is anything for OpenRA or its users to gain by balancing the RA mod around the opinion of a minority that does not care at all about the mod or the engine. Nobody of them cares about C&C or OppenRA or RA, all they care about is preserving the environment they can fight their little competition in. How can people who cheat and call it an "OK" thing to do have ever any word in the development of a game they have shown such disrespect for? There are many many casual players, many people who play against AI, nobody needs the OpenRA "competitive scene" and the game should never be balanced around what they think would be good or bad.

**Comment by PunkPun** [comment] 2023-03-02 07:49
Reverse duplicate of #15887

**Closed by PunkPun** 2023-03-02 07:49 UTC
Labels: Idea/Wishlist, Red Alert
