### ISSUE TITLE
[IDEA] Pilot from downed aircraft.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10175] opened 2015-12-03 23:47 UTC
Then you can upgrade a units veterancy with the pilot like in Generals? I dunno man, its just a idea.

**Comment by Phrohdoh** [comment] 2015-12-04 01:01
So you want https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/EjectOnDeath.cs#L17?

**Comment by epicelite** [comment] 2015-12-04 01:39
What else would I be talking about?

**Comment by Aaron-Lloyd** [comment] 2015-12-04 02:18
I think he means having a separate pilot unit which would inherit any veterancy the plane/heli he ejected from had and have that pilot be able to enter another plane so that that plane gains the veterancy.

Sounds like a lot of work for relatively small pay-off tbh.

**Comment by epicelite** [comment] 2015-12-04 02:37
None of yall' ever played Generals?

**Comment by jaZzKCS** [comment] 2015-12-04 10:25
If a Generals flying unit had veterancy on it it will pop out a vetted pilot after destruction. This pilot - assumed it landed safely and is not killed - would have been able to be sent into ANY vehicle (not only planes) of the player giving that vehicle a plus1 in veterancy.

**Comment by GraionDilach** [comment] 2015-12-04 10:30
Not plus1, but plus-pilot's-level.

I'd want to do this but I don't think it would fit into any of the default mods.

**Comment by pchote** [comment] 2015-12-04 10:40
I agree that this doesn't fit with the default mods.

**Comment by jaZzKCS** [comment] 2015-12-04 13:32
This was a Generals specific thing, considering all earlier CnC titles did not have that. Implementing this into RA/TD may be a little too much in terms of wanting to cramp every feature of this kind from the later games into the earlier ones.

I do not say that this is generally a bad idea...
I just think that this can't be compared to things like attack-move  which also obv. were not present, yet totally make sense even in the older titles.

This was one of the things that made Generals Generals.

**Comment by GraionDilach** [comment] 2015-12-04 14:02
Attack-move was present in TS and RA2 for sure.

**Comment by Mailaender** [comment] 2015-12-04 19:14
Duplicate of https://github.com/OpenRA/OpenRA/issues/4693 I assume.

**Closed by Mailaender** 2015-12-04 19:14 UTC
Labels: Balancing, Idea

**Comment by r34ch** [comment] 2015-12-04 20:15
Part of me wants the hijacker to have this ability. Even with the buffs lately, the mech is so much better.

**Comment by Phrohdoh** [comment] 2015-12-04 23:33
> What else would I be talking about?

You've been here long enough to know creating an issue about something that exists isn't helping anyone.
