### ISSUE TITLE
Neutral Chronosphere causes huge lag

### ISSUE THREAD

**Issue by jedininja28** [OpenRA/OpenRA#17546] opened 2020-01-01 22:52 UTC
Hey, i'm a long time fan of openra and I've been making some maps for the map site and discovered that a neutral Chronosphere causes huge lag in single player skirmishes. my pc is not great im using OpenRA-release-20191117-x64

![sysspecs](https://user-images.githubusercontent.com/51716121/71646996-87a1ad80-2ca4-11ea-80d0-dc774e9dc0e9.PNG)

I also have a few suggestions. 

1) Random AI selector in skirmish game

2) More AIs as the current ones get pretty easy

3) making the AI's effectively use superpowers and unique units like the nuke truck, cronotank and phase tank. all of which i think need to avoid non-friendly units and defenses scaling with AI difficulty.

4) Making the AI's use engineers to take over neutral buildings and tech buildings

5) The Neutral Tech center should do the same as the Neutral tech center in RA2 in which the player gains a new tech. 

6) Incorporating the ant mound from Island Wars Extreme in RA Aftermath to spawn ants. 

7) perhaps a unique building, if possible, for each country. Like a "testla Center"

8) The map editor could use some tweeks, larger brushes, and a paint brush eraser. 
 
9) Perhaps spys could show superpower targets if the player infiltrates the radar and X superpower building.

Amazing game, the C&C skirmish is the c&c game iv always wanted. Kill Bounties is awesome, the way the engineers work is really cool, and i love the Supreme Commander Style Map and the RA2 superpowers display. This mod really honors Westwood and shames EA's stupid business practices. I Hope you all get something out of your work.

**Comment by jedininja28** [comment] 2020-01-02 04:48
After reading  some of these path finding posts, i realize that every time i captured the story neutral Chronosphere all of the computers moved to destroy it due to the map size and layout. Since i separated the starting positions with concrete walls which are also neutral the computers could not find a way to destroy it after i captured it. 

It seems this type of thing happens a lot, perhaps a script to destroy whatever it is in the path of the computer, followed a use of ranged ground units, air units or long rang navel units to clear the path to the intended target, like a nuke silo, iron curtain or chronosphere, as a player would. 

I've noticed that the AI's would rather go around neutral concrete walls where as it will spend an excessive amount of time destroying Creep walls. i tested this in my map "Money" by remove the central chonosphere and adding a few creep walls into the neutral wall dividers, and it worked, but it took about 5 minutes for the computer to determine that the walls needed to be destroyed to get to the intended target. 

Im really interested in the AI's in this mods, as iv made my own mods for TS and the AI's were a huge focus for me on there. In TS the AI's really rely a lot on credit and stat boats for difficulty and iv noticed that in OpenRA RA its pretty even ground, though i haven't went and tinkered with the code yet due to "s**t  pc syndrome".

Which files would i need to tinker with and which compiler should i use?

**Comment by abcdefg30** [comment] 2020-01-02 05:36
If you want to edit the source code it is probably a good idea to get an IDE like Visual Studio. That will also come with a compiler. See https://github.com/OpenRA/OpenRA/wiki/Compiling for further instructions.

You can find files related to the AI here: https://github.com/OpenRA/OpenRA/tree/bleed/OpenRA.Mods.Common/Traits/BotModules
(Also note that each mod defines an `ai.yaml` file with configuration parameters.)

**Comment by jedininja28** [comment] 2020-01-11 19:38
Will do, i was checking out the ai scripts and noted that you guys used some code from the hack ai demo, specifically the 2 flamer apc. Where would i find the grouping of units the computer uses. In normal ra it was editable in the rules.ini. I would like to make the ais target supers with a +- tile/cost script which would go around unfriendly units and deffenceses with in a range to destroy priority targets.

Also costom art/music packs may be a way to get some funding. Iheard alot of great c&c music covers on you tube.

**Comment by Mailaender** [comment] 2020-06-01 12:14
I made a test map with a neutral chronosphere to check if AI bots try to use them in invalid ways. I didn't encounter any slowdowns. Closing as possible duplicate of #12435.

**Closed by Mailaender** 2020-06-01 12:14 UTC
Labels: AI, Pathfinding, Performance
