### ISSUE TITLE
Force move / Double click move feature for infantries

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13302] opened 2017-05-15 04:45 UTC
Double clicking on the ground in RA1 or force moving infantries with G key in C&C3 or RA3 removed suppression status from infantries and forced them to walk, instead of prone. Useful for controlling commando or tanya to bomb multiple structures quickly or making infantries move away from danger

**Comment by abcdefg30** [comment] 2017-05-15 11:56
Duplicate of #10967.

**Closed by abcdefg30** 2017-05-15 11:56 UTC
Labels: Feature
