### ISSUE TITLE
Allow to save elite rank after deploy/undeploy units

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10827] opened 2016-02-25 12:32 UTC
MCV lost elite abilities after deploy, see replay

[OpenRA-2016-02-25T122146Z.zip](https://github.com/OpenRA/OpenRA/files/146466/OpenRA-2016-02-25T122146Z.zip)

**Comment by reaperrr** [comment] 2016-02-25 12:37
That's because MCVs still use the old `Transforms` logic. For tick tanks / artillery we already have the required logic in place.

**Comment by penev92** [comment] 2016-02-25 12:38
There are currently 2 ways to deploy a unit. One is widely used across all mods (most common use-case are MCVs) and has a bunch of issues like the one you pointed out.
The other one is new and is currently only used for some TS deploying units (eventually it will be used for all of them). That method does *not* have the issues of the first one, and that's why we're introducing it. I don't expect the first one to be fixed though (although experience as a special case can be transferred, I suppose).

**Comment by yaaaaa** [comment] 2016-02-25 13:09
Thank You for the quick ansvers)

**Comment by Mailaender** [comment] 2016-02-25 19:29
The easy solution would be to disallow ranks on MCVs.

**Comment by StexoO** [comment] 2016-02-25 22:22
Do the ranked MCVs have the speed bonus ? I have to check that.

**Comment by MustaphaTR** [comment] 2016-02-26 06:13
Speed, Armor, ROF, Damage, Accuraty and Self Heal(only on 4th). As MCV has no weapon this only affects Speed, Armor and Self Heal.

**Comment by Mailaender** [comment] 2016-07-10 13:57
Duplicate of https://github.com/OpenRA/OpenRA/issues/7021.

**Closed by Mailaender** 2016-07-10 13:57 UTC
Labels: Bug
