### ISSUE TITLE
System.InvalidOperationException on Mac OS X

### ISSUE THREAD

**Issue by Juravenator** [OpenRA/OpenRA#14906] opened 2018-03-11 20:06 UTC
### Issue Summary
Was playing online, when a fatal exception occurred.

#### System Information
- **Operating System:** Mac OS 10.12.6
- **.NET / Mono Version:** mono-4.8.0-branch/8f6d0f6
- **OpenRA Version:** release-20180307
- **Mod:** Red Alert
- Logs
  - [exception-2018-03-11T195439Z.log](https://github.com/OpenRA/OpenRA/files/1800823/exception-2018-03-11T195439Z.log)
  - [debug.log](https://github.com/OpenRA/OpenRA/files/1800825/debug.log)

**Comment by RoosterDragon** [comment] 2018-03-18 20:29
```
Exception of type `System.InvalidOperationException`: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00067] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:956 
  at OpenRA.Mods.Common.Traits.AttackMoveOrderGenerator.GetCursor (OpenRA.World world, OpenRA.CPos cell, OpenRA.int2 worldPixel, OpenRA.MouseInput mi) [0x0003b] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/AttackMove.cs:174 
  at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget+<GetCursor>c__AnonStorey5.<>m__0 () [0x000ad] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:243 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1[TResult] fn) [0x00043] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.GetCursor (OpenRA.int2 screenPos) [0x00027] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:227 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x00091] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x0004d] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x0004d] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x0004d] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.RenderTick () [0x000d9] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.Loop () [0x00142] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.Run () [0x00042] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
```

**Comment by RoosterDragon** [comment] 2018-03-18 20:29
Dupe of #14942.

**Closed by RoosterDragon** 2018-03-18 20:29 UTC
Labels: Crash
