### ISSUE TITLE
Custom rules map isn't displaying "This map contains custom rules" prompt.

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14342] opened 2017-11-12 00:14 UTC
When loading this custom [map](http://resource.openra.net/maps/23855/) in _multiplayer_ it isn't displaying the usual "This map contains custom rules" lobby prompt.

In singleplayer skirmish it works fine.

**Comment by pchote** [comment] 2017-11-25 00:53
I'm unable to reproduce this bug in multiplayer, using a dedicated server.  It always shows the "This map contains custom rules" message for me.

Can you please post a screenshot showing the (lack of) messages in the chat window?

**Comment by FrameLimiter** [comment] 2017-11-25 16:31
![maperror](https://user-images.githubusercontent.com/22008761/33232399-b2199fa6-d1d3-11e7-943c-aaadeecbefc6.png)

**Comment by pchote** [comment] 2017-11-25 17:53
Closing as duplicate of #14060, which was fixed by #14090.

In this case the duplicated node was `^NeutralPlane`, so the symptoms were different to #14060.

**Closed by pchote** 2017-11-25 17:53 UTC
Labels: Bug
