### ISSUE TITLE
Z-Buffer support [$15]

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#7520] opened 2015-02-22 16:06 UTC
~~Corpses being rendered above vehicles is looking glitchy and bugging me for quite some time. Somehow not easy to fix. The ZOffset is ignored. I tried adding it to sequences and hard-coded into the corpse effect.~~

Already fixed by https://github.com/OpenRA/OpenRA/issues/10119.

**Comment by pchote** [comment] 2015-02-22 16:38
This applies to all Effects, which aren't z-sorted for performance reasons.  This will eventually be fixed when we redo the renderer with proper z-buffer support (which is a prerequisite for proper TS support).

**Comment by pchote** [comment] 2015-09-28 20:33
We merged #7968 in the last release, and I have just filed #9476.  The next step is to fix our treatment of the vertex z coordinates, and it then becomes easy to construct a depth image for the terrain:

![screen shot 2015-09-28 at 21 15 02](https://cloud.githubusercontent.com/assets/167819/10147824/3678beae-6628-11e5-971d-e44d3c132361.png)

**Comment by pchote** [comment] 2015-09-28 21:10
Once we have the depth image, it then becomes straightforward (but not trivial) to enable proper depth filtering:

![screen shot 2015-09-28 at 22 09 27](https://cloud.githubusercontent.com/assets/167819/10148831/b9c62c74-662d-11e5-8879-273692a62da6.png)

**Comment by Mailaender** [comment] 2015-09-29 15:22
Looks impressive! Is the missing door overlay a regression due to wrong Z sorting?

**Comment by pchote** [comment] 2015-09-29 15:58
It is a regression due to wrong z sorting because of the quick and dirty way it was implemented.  The proper implementation (which depends on some refactoring that hasn't happened yet) won't have that problem.

**Comment by pchote** [comment] 2016-04-08 19:49
I now have a big chunk of this feature completed and ready for review/merge:

* #11058 puts in place the initial groundwork and adds depth buffer support for terrain.
* [shroud-vertex-depth](https://github.com/pchote/OpenRA/tree/shroud-vertex-depth) adds depth buffer support for regular sprites and fixes shroud rendering.
* [tileset-depth](https://github.com/pchote/OpenRA/tree/tileset-depth) makes some depth metadata configurable and sets up the correct offsets for TS.

[depthbuffer-part-two](https://github.com/pchote/OpenRA/tree/depthbuffer-part-two) is a bucket of prototype changes that will grow into more PRs after the earlier ones are merged.

**Closed** 2016-08-27 15:57 UTC
Labels: Bounty, Feature
