### ISSUE TITLE
Heli goes to pad if SD is occupied

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12991] opened 2017-03-18 19:03 UTC
If there is a queue on the SD the heli goes to the pad instead.
https://www.youtube.com/watch?v=GM2uXP3SVEo

**Comment by Wobling** [comment] 2017-03-18 23:16
Should the correct functionality be it moves to the service depot and waits?

**Comment by Snurre86** [comment] 2017-03-19 00:35
Well it does not need ammo but (health) so unless it can get health at the pad it should try to get the health where it can get it.

**Comment by rob-v** [comment] 2017-04-08 15:43
PR #13081

This is complicated/hacky currently. Some buildings can repair, some rearm, some both. There is only 1 order now "Enter" and Heli/Plane AirCraft behaves differently.

Heli, when target is reserved, looks always for next free HeliBase, which does not repair. Should heli go to next base or service pad or? Did you want to rearm or repair?

I did one minimal change/fix - If target is reserved Repair building, do nothing instead of searching for next HeliBase. So it doesn't fly away and you can send it again to repair. 
Not changed - if target is reserved Rearm building (HeliBase), go to next free HeliBase like so far.

**Comment by matjaeck** [comment] 2019-05-19 17:52
Bug is is still present on bleed and presumably in last release (20190314).

**Comment by fruestueck** [comment] 2019-07-19 11:08
This bug affects all aircraft in RA and TS. #16712 is more precise but basically a duplicate.

**Comment by abcdefg30** [comment] 2019-07-19 11:32
Closing as duplicate of #16712 then.

**Closed by abcdefg30** 2019-07-19 11:32 UTC
Labels: Bug
