### ISSUE TITLE
Teammate can build when enemy engineer are converting base

### ISSUE THREAD

**Issue by meg4** [OpenRA/OpenRA#10052] opened 2015-11-21 14:47 UTC
When a base are being converted by engineer, the initial owner of base can't build, but his teammates yes.

**Comment by obrakmann** [comment] 2015-11-21 15:09
Can you please clarify what you mean exactly?

At the moment, this sounds like either a duplicate of #8122, or it's working as intended.

**Comment by meg4** [comment] 2015-11-21 15:22
I edited my initial post. It isn't sufficient clarity i will try again. sorry.

**Comment by pchote** [comment] 2015-11-21 15:24
By base do you mean construction yard?  When a building is captured its production becomes disabled, but you are still able to place buildings around it.  This applies to you if you have multiple construction yards, and also to your allies.

**Comment by meg4** [comment] 2015-11-21 15:26
yes.

I don't thought production cancel is a bug, i think should be a feature. If it is a bug, my post have not sense

**Comment by r34ch** [comment] 2015-11-21 15:35
Or do you mean that you cannot build in the build radius around the construction yard being captured using a different con yard, while your team-mates can?

**Comment by meg4** [comment] 2015-11-21 15:46
yes r34ch i wanted say this

**Comment by SoScared** [comment] 2016-03-06 12:02
Agreed with meg4. Intentional or not, the production cancelling with the engineer has become a cool feature. Hope to see it stay.

**Comment by pchote** [comment] 2016-10-15 12:09
Fixed by #11951.

**Closed by pchote** 2016-10-15 12:09 UTC
Labels: Balancing, Bug
