### ISSUE TITLE
Carryall is trying pick up Harvester while its still in the Factory

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21229] opened 2023-11-24 13:47 UTC
Version: Bleed

https://github.com/OpenRA/OpenRA/assets/100044015/a593d0e2-f713-48ab-8ced-111ee132ec0d

**Comment by tysonliddell** [comment] 2023-11-27 15:10
I'd like to have a go at fixing this.

**Comment by penev92** [comment] 2023-11-27 15:16
@tysonliddell ok, great!
Keep in mind that if you need to discuss anything it's easiest to reach us on Discord.

**Comment by PunkPun** [comment] 2023-11-27 17:50
Is it fixed by #21076 ?

**Comment by tysonliddell** [comment] 2023-11-27 19:45
@PunkPun it looks like it 🎉. I cannot reproduce the error when checking out 56bbb7d0eba26d777dbf4a29a014609455796712, the tip of your `fix-transports` branch.

**Comment by tysonliddell** [comment] 2023-11-27 19:57
In particular, it's bac3bfe81e701a5f06d86823aefd38c4dde3c113 that fixes it.

**Comment by Porenutak** [comment] 2023-11-28 10:51
> Is it fixed by #21076 ?

Confirm, #21076 fix this issue.

**Closed as completed** 2023-12-03 19:27 UTC
Labels: Bug
