### ISSUE TITLE
Tiberian Dawn: Small construction yard bug

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14235] opened 2017-10-21 15:43 UTC
Hello,

I found this small bug:

When you have multiple construction yards in tiberian dawn, these are numbered and you can build different things in each construction yard.

Everything OK so far.

if you start a skirmish game and expand your initial MCV to the construction yard, the construction yard gets the number '1'. This is still correct (you only have that one construction yard yet).

If you make the construction yard back to a MCV and expand it again, it gets the number '2'.
If you do this again, it gets the number '3'.

And so on ;-).

**Comment by FRenzy-OpenRA** [comment] 2017-10-22 09:00
Same if you sell production buildings, numbers are not reorganized.

**Comment by GraionDilach** [comment] 2017-10-22 09:28
Duplicate of #10976.

**Comment by penev92** [comment] 2017-10-22 10:49
Thanks for the report, but closing as duplicate.

**Closed by penev92** 2017-10-22 10:49 UTC
