### ISSUE TITLE
Implement ingame access to Resource Center

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14773] opened 2018-01-30 06:54 UTC
[this was highly likely to have already been mentioned before, but haven't found it right away]

Probably a tough task to handle, but would be great to have actual Resource Center browser accessible ingame. This way you won't need to manually download maps from RC, put them to the appropriate folder and (the worst part) relaunch the client to update the map list.

A button on any map browser window (and a separate button in menu) than will open a web source with either just direct RC webpage (easier, but I suppose not implementable in legacy mode, also issues with link handling and account auth) or a custom-made window reimplementing stuff from https://resource.openra.net/maps/

**Comment by abcdefg30** [comment] 2018-01-30 08:40
Duplicate of #3357.

**Closed by abcdefg30** 2018-01-30 08:40 UTC
