### ISSUE TITLE
Units give up too easily on following their path

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17526] opened 2019-12-30 21:00 UTC
When you give a move order to a large army it instead of blobbing up makes a long line. 

Demonstrated here by a tiny army (gave only 1 order)
![move bug](https://user-images.githubusercontent.com/37534529/71600510-ec032680-2b57-11ea-9a1f-8170096838e4.gif)

possible cause of #17438

**Comment by abcdefg30** [comment] 2019-12-30 21:51
Duplicate of #5968.

**Closed by abcdefg30** 2019-12-30 21:51 UTC
Labels: Bug

**Comment by tovl** [comment] 2019-12-30 22:06
This is a long-standing issue caused by the `nearEnough` logic, which makes the units immediately give up when colliding with another unit when within a certain number of cells from the destination. 'Stringiness' while moving a blob is also caused by the fact that we prioritize waiting for the blocking unit to move over finding a way around it. 

Letting units in a blob distribute their destination cells (like in original TS) and making the `nearEnough` distance one cell at most would fix the first problem (#16883 already does this for airplanes and should be generalized to ground units in a follow up). It was my plan to fix the second problem by letting units prioritize short detours over waiting. This has a number of prerequisites though&mdash;mainly a restructuring of the `Move` code&mdash;which have met with some delay and will not be ready soon.

Meanwhile, #16408 has made the problem worse on bleed, because units now ignore moving actors on the initial pathfinding. This means units in a blob will generally move along the exact same path and therefore collide more often. This is a good thing in the long run, as it allows us to separate high-level pathfinding from local avoidance behaviours. However, if the rest of the movement rework is still pending come next release, it would be better to change `BlockedByActor.Stationary` to `BlockedByActor.All` in the initial pathfinding so as not to make things worse than they already are.
