### ISSUE TITLE
Playername is blanked out when having a # before the name

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8031] opened 2015-04-25 22:48 UTC
And it crashes when starting the game.

Reported by `pr37` in IRC.

**Comment by penev92** [comment] 2015-04-25 23:03
Related to a long line of nickname-sanitation issues :|

**Comment by Mailaender** [comment] 2015-04-26 10:19
Essentially a duplicate of https://github.com/OpenRA/OpenRA/issues/3332 but a lot more pressing.

**Closed** 2015-05-30 19:21 UTC
Labels: Bug, Crash
