### ISSUE TITLE
AI cant recognize islands and check for pathability so it lags  (solution)

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#10860] opened 2016-03-02 11:17 UTC
The AI right now don't recognize islands or water limits,if you put a normal rush or turtle AI the game will lag from the vast numbers of the ground units that seek unreachable targets.

A solution could be on the player starting position.
an option can be made to toggle land unit production to only naval and air units.

An example of my idea:
on player starting position properties\settings (in map editor)

1) is island: true\false (the ai will stop or engage ground unit production,and use the units if any only for defense

2) is island bridge: true\false (the ai will build both ground and naval units BUT the ground units will not try to engage with the bridge destroyed, see below)

3) island bridge link: bridge01,bridge02,bridge04 (this will tell the ai what bridges can be passed from ground units)

4) player path link: playerposition1,playerposition2 ect. (with this the ai will engage if enemy the player that is on the same island or group of island linked with a bridge,using the ground units)

so the ai will check if the the starting position is an island,then it will check if "any" the bridges are working,and then will check if the enemy can be reached with ground units.

the names like bridge01 playerposition1 ect are imaginary i don't remember the actual names.

final words,this is just a way,toggling off and on things.i dont know if this is the best way to do it,but this is the general idea.i am not a programmer so if some one can filter out this idea and make it work then...it will work..

**Comment by reaperrr** [comment] 2016-03-02 20:05
I thought our domain system should actually do this, but looks like it doesn't (at least not properly).

**Comment by hypercube33** [comment] 2016-11-24 18:21
We noted this on a few maps we've played - once the bridges are destroyed, the AI freaks out and the game grinds to 1/10th speed about while the AI appears to go into some mad loop trying to find pathing. Very much appears to be harvester driven - as the AI is desperately trying to harvest your ore / when harvesters are destroyed, the game speeds up. (This may be a coincidence, however)

**Comment by godest88** [comment] 2016-11-29 20:51
@hypercube33 This is not only related to bridges sadly.

**Comment by abcdefg30** [comment] 2020-08-29 20:33
Closing as duplicate of #12435.

**Closed by abcdefg30** 2020-08-29 20:33 UTC
Labels: AI, Performance
