### ISSUE TITLE
Transport helicopters (Chinook) occupy same tile when landed

### ISSUE THREAD

**Issue by ghcmat** [OpenRA/OpenRA#6068] opened 2014-07-26 04:15 UTC
Tested in both RA and CnC. If multiple transport helicopters are issued a move command, they will fly to their destination and land at the same location (tile). When mixed unit selections containing ground vehicles and infantry are ordered to board the transport, a vehicle will move to and occupy the same tile as the landed chopper.

**Comment by abcdefg30** [comment] 2016-01-06 20:47
Closing as a duplicate of #4605.

**Closed by abcdefg30** 2016-01-06 20:47 UTC
Labels: Bug
