### ISSUE TITLE
Replace current structure selection brackets with the ones from the original game.

### ISSUE THREAD

**Issue by MikillRosen** [OpenRA/OpenRA#17466] opened 2019-12-15 09:21 UTC
Do I need to say more?

**Comment by MikillRosen** [comment] 2019-12-15 09:22
Also, for Tiberian Sun mod

**Comment by teinarss** [comment] 2019-12-15 09:26
Duplicate of #4783 ?

**Comment by MikillRosen** [comment] 2019-12-15 09:27
oh, sorry

**Closed** 2019-12-15 09:28 UTC
