### ISSUE TITLE
Map Upgrade Utility in release changes hash probably when map does not require upgrade

### ISSUE THREAD

**Issue by ihptru** [OpenRA/OpenRA#10319] opened 2015-12-29 11:16 UTC
maybe bug maybe not; I file it so it can be checked;

case: 1 map parsed by release, Lint succeeds; same map upgraded to release results in different hash.
example: http://resource.openra.net/maps/4711
this is map included in release distribution; automated upgrade from release-20150919
 to release-20151224 already created new revision of it as hash after running map-upgrade changed

That's the same for many maps.
Noticed while manually uploading fresh distributed maps to Resource Center.
##

**Comment by ihptru** [comment] 2016-04-08 10:03
is it still a problem in the latest playtest?

**Comment by PunkPun** [comment] 2022-07-05 22:35
Is this still relevant?

**Comment by pchote** [comment] 2022-07-05 22:47
~~Yes. The map code should be smarter about not updating the internal timestamp if there are no actual changes.~~
never mind, I’m thinking of something different.

**Comment by abcdefg30** [comment] 2022-07-06 09:22
> ~~Yes. The map code should be smarter about not updating the internal timestamp if there are no actual changes.~~

Running `--update-map` on an `oramap` still changes the hash (at least it shows up as untracked change in git) even when the yaml didn't change.

**Comment by pchote** [comment] 2022-07-06 09:23
The untracked changes in git is because of the file timestamps inside the zip. These shouldn't impact the sha1 (which is calculated over the contents, not the container) though which is why i edited my comment.

**Comment by Mailaender** [comment] 2022-09-07 10:48
> Is this still relevant?

To reproduce:
1) backup any map someplace else
2) run `./utility.sh ra --update-mod RenameCloakTypes --apply` it doesn't matter which rule
3) see all the `.oramap` changed in git.
4) extract both before and after `.oramap`
5) compare individual `map.yaml` `map.bin` and `map.png`: no difference

**Comment by Mailaender** [comment] 2022-09-07 10:52
Closing as this is not actually change hashes, so it shouldn't impact the resource center. The title is misleading.

**Closed by Mailaender** 2022-09-07 10:52 UTC
Labels: Bug, Utility
