### ISSUE TITLE
FlyAndContinueWithCirclesWhenIdle works sporadically

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13703] opened 2017-07-23 00:36 UTC
Tested on current bleed. (probably the same as Playtest)

https://youtu.be/U8WsW5MELDU

FlyAndContinueWithCirclesWhenIdle activity is meant to make Migs and Yaks stay in the air indefinitely, but depending on which cell you order them to move, they become idle and return to the Airfield.

**Comment by obrakmann** [comment] 2017-07-24 15:42
This was introduced by #13021.

Because a circling aircraft is considered idle after that, [World.Tick triggers `ReturnOnIdle`](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/World.cs#L339-L341), which queues `ReturnToBase`.

I guess it's kind of a problem that `ReturnOnIdle` runs every tick for circling aircraft.

**Comment by pchote** [comment] 2017-07-24 15:49
#13015 is annoying, but IMO not a serious bug (since it only affects map scripts, and can be documented as a known issue).  IMO we should consider reverting #13021 as the fix for this.

**Comment by obrakmann** [comment] 2017-07-24 20:12
Alternatively, this one seems to work as well, and would be my preference. It's more in line with what I have in mind for idle activities in the long run.

```diff
diff --git a/OpenRA.Game/Actor.cs b/OpenRA.Game/Actor.cs
index 148385f..0a90e52 100644
--- a/OpenRA.Game/Actor.cs
+++ b/OpenRA.Game/Actor.cs
@@ -78,6 +78,7 @@ public WRot Orientation
                readonly IDisable[] disables;
                readonly IVisibilityModifier[] visibilityModifiers;
                readonly IDefaultVisibility defaultVisibility;
+               readonly INotifyIdle[] idleTraits;
 
                internal Actor(World world, string name, TypeDictionary initDict)
                {
@@ -121,6 +122,7 @@ internal Actor(World world, string name, TypeDictionary initDict)
                        visibilityModifiers = TraitsImplementing<IVisibilityModifier>().ToArray();
                        defaultVisibility = Trait<IDefaultVisibility>();
                        Targetables = TraitsImplementing<ITargetable>().ToArray();
+                       idleTraits = TraitsImplementing<INotifyIdle>().ToArray();
 
                        SyncHashes =
                                TraitsImplementing<ISync>()
@@ -160,6 +162,12 @@ Rectangle DetermineVisualBounds()
                public void Tick()
                {
                        var wasIdle = IsIdle;
+
+                       // Use a null-check here instead of IsIdle to prevent matching against idle activities
+                       if (CurrentActivity == null)
+                               foreach (var ni in idleTraits)
+                                       ni.TickIdle(this);
+
                        CurrentActivity = ActivityUtils.RunActivity(this, CurrentActivity);
 
                        if (!wasIdle && IsIdle)
diff --git a/OpenRA.Game/World.cs b/OpenRA.Game/World.cs
index 37774d7..e8c56c6 100644
--- a/OpenRA.Game/World.cs
+++ b/OpenRA.Game/World.cs
@@ -335,11 +335,6 @@ public void Tick()
                        {
                                WorldTick++;
 
-                               using (new PerfSample("tick_idle"))
-                                       foreach (var ni in ActorsWithTrait<INotifyIdle>())
-                                               if (ni.Actor.IsIdle)
-                                                       ni.Trait.TickIdle(ni.Actor);
-
                                using (new PerfSample("tick_activities"))
                                        foreach (var a in actors.Values)
                                                a.Tick();
```

**Comment by pchote** [comment] 2017-07-25 16:56
[Related IRC discussion](http://logs.openra.net/index.php?year=2017&month=07&day=24#20:18:57).

This issue causes a gameplay regression as reported in #13681, so adding to the milestone.

**Closed** 2017-08-10 10:22 UTC
Labels: Bug
