### ISSUE TITLE
Bibs disappear at top of screen

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9850] opened 2015-11-01 14:45 UTC
I tried finding the issue with bridges looking destroyed at the side of the screen but came up short.

![bib](https://cloud.githubusercontent.com/assets/3636652/10869407/ce5261ba-80a6-11e5-9ca7-8bf564234675.gif) 
(top left)

On both release and bleed.
Resolution 1366 x 768

**Comment by pchote** [comment] 2015-11-01 14:47
Duplicate of #6987.  Some of the more recent bounds changes may have made it possible to solve this now.

**Closed** 2015-11-01 14:48 UTC
