### ISSUE TITLE
Too many simultaneous "UNIT LOST" 

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11616] opened 2016-07-09 08:06 UTC
If many units get destroyed at once, the game plays "UNIT LOST" loud enough to distort speakers.

**Comment by Mailaender** [comment] 2016-07-09 09:32
See also https://github.com/OpenRA/OpenRA/issues/4690.

**Comment by obrakmann** [comment] 2016-07-09 10:51
Duplicate of #3844

**Closed by obrakmann** 2016-07-09 10:51 UTC
Labels: Bug
