### ISSUE TITLE
OpenRA crashes on MSI CR500 laptop

### ISSUE THREAD

**Issue by ConcealedSentinel** [OpenRA/OpenRA#18052] opened 2020-05-08 09:09 UTC
## System Information

- OS:  Windows 7 Ultimate x64
- CPU: Mobile DualCore Intel Pentium T4500, 2300 MHz, Penryn-1M, support SSSE3 
- GPU: nVIDIA GeForce 8200M G (MSI) 256 Mb, C79-MVL, nVIDIA Tesla, compatible with OpenGl up to 3.3, OpenCL 1.0 CUDA
- RAM: Dual Channel DDR2 SDRAM 4 Gb (2x2) SK hynix HYMP125S64CP8-S6
- Motherboard: MSI MegaBook CR500/CR600 (MS-1683)
- Chipset: North- and SouthBridge nVIDIA GeForce 8200M G (MCP79MVL)
- OpenRA Version: Release 20200503
- OpenRA Mod: Red Alert, Tiberian Dawn and Dune 2000
- Source: Official download package

## Exception log
[exception-2020-05-08T082023Z.log](https://github.com/OpenRA/OpenRA/files/4597909/exception-2020-05-08T082023Z.log)

## Additional information
I suspect that OpenRA crashes because of OpenGL or others GPU requirements. Release 20200202 works fine without any problems.
[graphics.log](https://github.com/OpenRA/OpenRA/files/4597918/graphics.log)

**Comment by pchote** [comment] 2020-05-08 09:30
Closing as a duplicate of #18047, and see my comment in https://github.com/OpenRA/OpenRA/issues/18047#issuecomment-624905514 for an explanation and solution - this is not a bug in OpenRA, and it is frustrating that there is no straightforward solution to protect it from these external tools.

**Closed as completed by pchote** 2020-05-08 09:30 UTC
Labels: Crash
