### ISSUE TITLE
HackyAI building multible structures despite buildlimits [bleed].

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#15605] opened 2018-09-12 14:35 UTC
This is reproducible by starting massive AI games with the most apparent duplicate being the Radar Dome.

At a guesstimate you'll be able to see at least Normal and Turtle AI build twin Radar Domes in about 1 in 10. I've also seen this bug occur with structures as Airfield, Service Depot and Tech Centers.

*A nice way of testing the AIs is with 'Explored Map' for better observer vision, uncheck 'Build off Allies' and ofc 'Fastest' game speed.

**Comment by SoScared** [comment] 2018-09-13 12:00
Same issue lies with all mods.

**Comment by SoScared** [comment] 2018-09-16 19:10
Related to https://github.com/OpenRA/OpenRA/issues/14024 https://github.com/OpenRA/OpenRA/pull/14025

**Comment by abcdefg30** [comment] 2019-11-09 10:07
Closing as duplicate of #14024.

**Closed by abcdefg30** 2019-11-09 10:07 UTC
Labels: AI, Bug
