### ISSUE TITLE
Exception of type `System.InvalidOperationException`

### ISSUE THREAD

**Issue by fastslack** [OpenRA/OpenRA#7484] opened 2015-02-15 22:34 UTC
Trying to play the map downloaded from http://resource.openra.net/maps/2235 i got this fatal error:

```
Exception of type `System.InvalidOperationException`: Unit `explosion` does not have a sequence named `big_frag`
  at OpenRA.Graphics.SequenceProvider.GetSequence (System.String unitName, System.String sequenceName) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.Animation.PlayThen (System.String sequenceName, System.Action after) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Effects.Explosion..ctor (OpenRA.World world, WPos pos, System.String sequence, System.String palette) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Warheads.CreateEffectWarhead+<DoImpact>c__AnonStorey0.<>m__0 (OpenRA.World w) [0x00000] in <filename unknown>:0 
  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by Unit158** [comment] 2015-02-16 06:09
This crash is not related to the main OpenRA code. Notify the map's creator instead.

**Comment by pchote** [comment] 2015-02-16 14:44
OpenRA really ought to be more robust against this kind of error.  It may be a good idea to run a lint pass the first time a custom map is loaded (per version), and then mark the map incompatible if it fails.  We already do that if the rules are outright bogus, but that doesn't catch the majority of errors.

**Comment by Mailaender** [comment] 2015-02-16 20:24
The linter won't complain as it only checks if `explosion` is listed in the sequences.yaml not if the definition of `big_frag` exists or works. This is a duplicate of https://github.com/OpenRA/OpenRA/issues/2283#issuecomment-28044915 and yes, fixing that bug will help maintaining custom maps and mods a lot.

**Closed by Mailaender** 2015-02-16 20:24 UTC
Labels: Crash
