### ISSUE TITLE
Defeated players can select units below fog of war when an ally has GPS

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#17041] opened 2019-09-03 22:15 UTC
![grafik](https://user-images.githubusercontent.com/7704140/64212238-fca4d800-cea8-11e9-914f-a1d07ba11e51.png)

Reproduction case is having an ally with an active GPS, then surrendering and selecting your own view. Also doable by spectators.

This is already present on the last release, so not a regression.

**Comment by deleted-user-1** [comment] 2020-06-07 14:54
This is still an issue but a bit harder to spot now:

![Bildschirmfoto von 2020-06-07 15-56-18](https://user-images.githubusercontent.com/59416324/83970733-8caffc00-a8d7-11ea-9228-8b89dca7c0a9.png)

**Comment by deleted-user-1** [comment] 2020-06-07 21:39
Also a reverse-duplicate of #17858 which will hopefully get fixed in #18077.

**Closed** 2020-10-26 23:39 UTC
Labels: Bug, UI
