### ISSUE TITLE
Husks don't chronoshift back to original location

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#9349] opened 2015-09-15 10:50 UTC

**Comment by pchote** [comment] 2015-09-15 10:55
This regression may have been introduced by the husk/viceroid spawner merge?

**Comment by abcdefg30** [comment] 2015-09-15 10:57
Shouldn't, as I didn't touch that code at all: [Diff](https://github.com/OpenRA/OpenRA/pull/8744/files#diff-72f5025743864a1bd2ce4b95283f1a7bR112)

Will test that though.

**Comment by abcdefg30** [comment] 2015-09-15 11:02
The bug seems to be already present in 1bc84275fd36a3ad2575a04947855338ecd40ac4, the commit before #8744.

**Comment by obrakmann** [comment] 2015-09-17 18:01
Is this really a regression? In which release did it use to work? Any chance that this is just a duplicate of #8670?

**Closed** 2015-11-08 18:07 UTC
Labels: Red Alert, Regression
