### ISSUE TITLE
Can not create OpenGL context. (Error: Invalid window) when prime-select on-demand is set

### ISSUE THREAD

**Issue by eliascasta** [OpenRA/OpenRA#16327] opened 2019-03-19 14:42 UTC
### Issue Summary
OpenRA crashes at startup showing the following error:

```
`Exception of type `System.InvalidOperationException`: Can not create OpenGL context. (Error: Invalid window)
  at OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL () [0x00066] in <a4debf887ee14158b13d4169d50b2963>:0 
  at OpenRA.Platforms.Default.ThreadedGraphicsContext.RenderThread (System.Object contextObject) [0x0002d] in <a4debf887ee14158b13d4169d50b2963>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x0002c] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 `
```

> ===========================================================================
OpenRA engine version release-20190314
Date: 2019-03-19 14:12:18Z
Operating System: Linux (Unix 4.15.0.46)
Runtime Version: Mono 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1) CLR 4.0.30319.42000
**Mod:** [Red Alert]
===========================================================================

**Comment by Mailaender** [comment] 2019-03-24 16:18
What graphics card do you have?

**Comment by phpbg** [comment] 2020-04-24 17:23
I had this problem too.
Like many laptops, I have two graphic cards: intel+nvidia. See https://www.geforce.com/hardware/technology/optimus/technology

I solved the problem by disabling nvidia card (on ubuntu you can use the nvidia control panel to do that)

**Comment by Mailaender** [comment] 2020-04-24 18:10
It works fine for me when I disable intel with `sudo prime-select nvidia` so I can't reproduce.

**Comment by phpbg** [comment] 2020-05-08 21:28
yes, you can use either `prime-select nvidia`, `prime-select intel`, but not `prime-select on-demand`: in that case the issue will occur

**Comment by Smittytron** [comment] 2021-04-09 14:29
Closing. This is 2 years old and a possible workaround was suggested.

**Closed by Smittytron** 2021-04-09 14:29 UTC
Labels: Crash, OS: Linux
