### ISSUE TITLE
Unexpected behavior when interrupting rearming

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16492] opened 2019-05-04 16:38 UTC
See gif below.

<details>

![landingbroken](https://user-images.githubusercontent.com/37185497/57182091-9fb5f880-6e9b-11e9-95b1-de5adad1f620.gif)

Note that rearming is aborted when giving the move order.

</details>

This does not happen with helicopters.

**Comment by reaperrr** [comment] 2019-05-04 21:07
Could be caused by https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Resupply.cs#L88, which was added with ground actors in mind.

**Comment by pchote** [comment] 2019-05-04 21:26
Almost certainly.

**Comment by matjaeck** [comment] 2019-05-19 20:05
I noticed in #16509 that spamming land orders will interrupt rearming of helis, but this can not be reproduced on bleed.

**Comment by matjaeck** [comment] 2019-05-20 05:02
When you interrupt repairing at a shipyard, the unit moves up and down and becomes uncontrollable.

**Comment by matjaeck** [comment] 2019-05-23 07:44
NTM: Test #14094 when this gets fixed.

**Comment by pchote** [comment] 2019-06-30 16:17
Fixed on current bleed: the yak takes off as expected when the move order is issued.

**Comment by matjaeck** [comment] 2019-07-15 21:27
> When you interrupt repairing at a shipyard, the unit moves up and down and becomes uncontrollable.

**Closed** 2019-07-15 22:48 UTC
Labels: Regression
