### ISSUE TITLE
Cash ticks don't play when the menu is opened

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#12235] opened 2016-10-15 19:14 UTC
#11907 moved the cash ticks to a chrome logic class that lives on a widget in the ingame-player branch of the widget tree. That part of the tree gets removed when the menu is opened, so the logic class can't tick anymore and ergo doesn't play any sounds either.

Fixing that could be as easy as moving that widget up the tree, but that might also introduce other problems.

**Comment by pchote** [comment] 2016-12-12 19:49
#12465 (intentionally) mutes most other sounds when the menu is open, although I guess you could argue that the cash ticks are UI rather than world sounds.

**Comment by pchote** [comment] 2017-02-05 18:35
I'm going to close this as "fixed" (promoted from bug to feature) by #12465.  Feel free to argue if you disagree.

**Comment by gdavegdave** [comment] 2017-06-06 16:15
It's not a major issue, but I think it'd be better if the cash ticks still played whilst the menu is open. For example, when I go into the menu to change a setting, I would get an indication of whether my attention was needed from the cash ticks (or lack thereof).

**Comment by pchote** [comment] 2017-06-06 18:11
We now mute *all* world sounds in the menu, so I would consider reintroducing this to be a regression.

**Comment by gdavegdave** [comment] 2017-06-07 03:26
Off the top of my head, I can think of two real reasons (i.e. have impacted me) to have sounds play in the menu:
1. Tweaking volumes to balance e.g. sounds, music, Discord/TeamSpeak. The lack of sounds now makes this a frustrating iterative process. 
2. The aforementioned ability to see if your attention is needed (structure built, silos needed, base under attack, etc), especially in a multiplayer game where pausing is not realistic. 

What are the motivations to mute sounds in menu?

**Comment by WolfGaming** [comment] 2017-06-07 05:44
To fix issue number 1 I would rather introduce a sound that gets played when the slider gets adjusted, think when the windows mixer sliders get changed with the mouse, this is also better when you are messing with the options outside of a game.

**Comment by GraionDilach** [comment] 2017-06-07 15:28
>What are the motivations to mute sounds in menu?

Consistency with every other game on the market sounds like one.

**Comment by anjew175** [comment] 2017-06-08 06:04
`Consistency with every other game on the market sounds like one`
This primarily in single player games when the match is usually paused from entering the menus. Most multiplayer games display warnings when in menus since in MP your attention is actually needed. This is the same for FPS and RTS games

**Comment by gdavegdave** [comment] 2017-06-08 13:57
Indeed, in single-player mode (skirmish, mission, 'multiplayer' vs AI), the game pauses when you open the menu, so sounds stop. 

In multiplayer, where it doesn't pause when the menu is opened, I think that all sounds should continue playing. I think I noticed when this stopped being the case and found it disruptive. Players have the option to mute (m) before going into multiplayer menu.

A possible issue with your solution to issue 1, @WolfGaming, is that a slider-bar sound would be a poor proxy for the actual in-game sounds. Then, there is still issue 2.

**Comment by pchote** [comment] 2017-06-08 14:31
> In multiplayer, where it doesn't pause when the menu is opened, I think that all sounds should continue playing. 

Making this work properly (without bugs like exactly this one) would require redesigning the way our UI code works, making it uglier and harder to maintain.  Muting sounds with the menu was just as much a technical decision as a UI consistency one.

**Comment by PunkPun** [comment] 2023-04-23 19:31
Closing as a non-issue.

6-7 years have passed making the initial change the norm

**Closed by PunkPun** 2023-04-23 19:31 UTC
Labels: UI
