### ISSUE TITLE
playtest crash: System.OverflowException`: Number overflow

### ISSUE THREAD

**Issue by ihptru** [OpenRA/OpenRA#11051] opened 2016-04-05 11:55 UTC
Crashed when lost TS game with 5 bots and moved around the map about 10 seconds.
playtest-20160403
```
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1366x768
No custom resolution provided, using desktop resolution
Using resolution: 1366x768
OpenGL version: 3.0 Mesa 10.1.3
Using OpenAL sound engine
Using default device
Available mods:
        all: All mods ({DEV_VERSION})
        cnc: Tiberian Dawn (playtest-20160403)
        d2k: Dune 2000 (playtest-20160403)
        modchooser: Mod Chooser ({DEV_VERSION})
        ra: Red Alert (playtest-20160403)
        ts: Tiberian Sun (playtest-20160403)
Loading mod: d2k
Loading mod: modchooser
Loading mod: ts
[2016-04-05T13:35:19] Game started
Exception of type `System.OverflowException`: Number overflow.                                                                                                                                  
  at System.Decimal.op_Explicit (Decimal value) [0x00000] in <filename unknown>:0                                                                                                               
  at OpenRA.WPos.LerpQuadratic (WPos a, WPos b, WAngle pitch, Int32 mul, Int32 div) [0x00000] in <filename unknown>:0                                                                           
  at OpenRA.Mods.Common.Effects.Bullet.Tick (OpenRA.World world) [0x00000] in <filename unknown>:0                                                                                              
  at OpenRA.World.<Tick>m__4 (IEffect e) [0x00000] in <filename unknown>:0 
  at OpenRA.WorldUtils.DoTimed[IEffect] (IEnumerable`1 e, System.Action`1 a, System.String text) [0x00000] in <filename unknown>:0 
  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by GraionDilach** [comment] 2016-04-05 12:31
Looks like a duplicate of #11026

**Comment by obrakmann** [comment] 2016-04-05 15:51
Yup, it is.

**Closed by obrakmann** 2016-04-05 15:51 UTC
