### ISSUE TITLE
Pathing KeyNotFoundException crash

### ISSUE THREAD

**Issue by isphariel** [OpenRA/OpenRA#14923] opened 2018-03-16 13:57 UTC
### Issue Summary
A pathing bug where an item in a dictionary of ICustomMovementLayer is missing and the game crashes.

#### System Information
OpenRA engine version {DEV_VERSION}
Tiberian Sun mod version {DEV_VERSION}
on map 6c8644cb1053fc1a462a8c00568aed9273e97254 (Tiers of Sorrow by Westwood Studios).
Date: 2018-03-16 09:27:08Z
Operating System: Linux (Unix 4.9.0.6)
Runtime Version: Mono 5.10.0.160 (tarball Wed Mar  7 15:12:26 UTC 2018) CLR 4.0.30319.42000

#### Additional Information:
No idea how to reproduce, sorry

Debug and Exception log
[report.zip](https://github.com/OpenRA/OpenRA/files/1819394/report.zip)

**Comment by reaperrr** [comment] 2018-03-16 14:20
Likely related to or even duplicate of #14863, but I'll leave both open for now since their exceptions differ a little.

**Closed** 2018-03-22 12:52 UTC
Labels: Bug, Pathfinding, Tiberian Sun
