### ISSUE TITLE
LeapAttack ignores queued status and doesn't revoke conditions when queued & cancelled

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#16076] opened 2019-01-18 17:47 UTC
If you queue up multiple move orders then an attack order, the aim condition is applied immediately despite the attack being at the end of the queue. Also if you cancel the queued actions, the aim condition isn't revoked.

To reproduce:
∙Build a dog.
∙Queue up multiple move orders for the dog.
∙Queue an attack order for the dog. (the aim condition is applied immediately)
->The dog will immediately start running.
∙Tell the dog to stop. (the aim condition isn't revoked)
->The dog will be stuck always running instead of walking.

**Comment by pchote** [comment] 2019-01-18 17:49
This will be partially fixed (at least for `AttackFollow`) by #16067.

**Comment by pchote** [comment] 2019-01-18 18:53
This is caused by https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/OpenRA.Mods.Cnc/Activities/LeapAttack.cs#L48

Moving the line to OnFirstRun will fix the issue.

**Closed** 2019-01-22 22:52 UTC
Labels: Bug, Red Alert
