### ISSUE TITLE
Longbow creation limits circumvented

### ISSUE THREAD

**Issue by whi7ed3vil** [OpenRA/OpenRA#10937] opened 2016-03-18 05:19 UTC
Longbow unit limits (appears to be 10 units per helipad, or perhaps 10 units max, I haven't checked which directly) can be circumvented by reloading a longbow on the helipad while you have a constructed longbow (over the limit, triggering the "unable to build more" message) waiting and ready to deploy. When the reloaded longbow leaves the helipad, it will split into two longbows (the one you reloaded and the one you just constructed. Must be a semaphore glitch. This allows an arbitrarily large number of airborne units to be produced with a little finesse.

**Comment by MustaphaTR** [comment] 2016-03-18 06:14
Unable to build more plays when a helicopter is already on pad or another one is coming to rearm. There is no build limit.

**Comment by whi7ed3vil** [comment] 2016-03-18 06:27
Thanks for your reply. My last gameplay says otherwise, possibly for
different reasons than I initially assumed: No choppers in queue for
reloading (just hovering on another part of the map), and nothing on the
pad. Placing one of the emptied choppers on the helipad and letting it
reload releases one unit. After that, the queue gums up again. Perhaps this
is related to the bug mentioned elsewhere regarding the reload blocking
behavior for airborne vehicles?


Jonathan C. Nilson

**Comment by abcdefg30** [comment] 2016-03-18 16:37
Yeah, we don't have a build limit on helis, but what you describe indicates the reload blocking bug. If a helicopter is already on its way back to reload, it reserves an helipad which can't release a heli then.

**Comment by abcdefg30** [comment] 2016-03-18 17:41
Actually, closing as duplicate of #10500 than here. Thanks for taking the effort to report this, though. :)

**Closed by abcdefg30** 2016-03-18 17:41 UTC
