### ISSUE TITLE
be able to see game setting in game, are crates

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#15860] opened 2018-11-25 23:31 UTC
once all is lost .. there is still the hope of crates .. 

how disappointing to have to wait for hours to come to the conclusions crates are off.

**Comment by anvilvapre** [comment] 2019-09-27 16:19
i found out later that game settings are displayed as text chat in the chat log. 
i am fine with closing this issue.

**Comment by dragunoff** [comment] 2019-09-29 11:40
Digging in the chat is cumbersome so I think there is value in displaying the settings in an user-friendly form - a readonly copy of the lobby options pane for example.

**Comment by Smittytron** [comment] 2021-05-07 00:12
Closing this as a duplicate of #12349, which covers this specific issue.

**Closed by Smittytron** 2021-05-07 00:12 UTC
Labels: Idea/Wishlist

**Comment by anvilvapre** [comment] 2021-07-15 17:11
`penalty` is a private variable. It is not explicitly initialized. I assume the value is read from Yaml. 

The initial value is not too relevant for as long as its value is below 250 or at least after x ticks ends up being 100 or less.

Each game tick `penalty` is reduced by integer value 100. Once below zero one of the  `BuildTimeModifiers` is applied. The modifier becomes the `penalty` value. No actual multiplication involved.

As I read it this means that only values that are a multiplication of 100 will have a noticeable impact(?). I.e. whether the multiplier value is 120 or 190 won't make a difference - since in both cases the value will be below 100 the next tick.
