### ISSUE TITLE
Gap generating rework

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17728] opened 2020-02-25 12:50 UTC
The shroud is really something that does not really play in competitive games. 

Explored map is always chosen by default, proof 0% of the (edit : ONLINE) player base wants to lose time "exploring" the map.  

When it comes to the shroud generation, static or mobile, the flaws do really impact the usefulness.

My rework idea is drop the shroud and just play with fog of war vision.

Static gap gen : 

- Does not generate shroud anymore
- still reduce vision of unit in range
-  As long as it is powered down, make disappear all "known" actors under it's area of effect. with this we get the building/defence positions masked for the enemy but not the exact position of the gap generator. More subtle and better in the overall.

MGG : 

- Does not generate shroud anymore (does not be a big position giveaway anymore)
- still reduce vision of unit in range
-  (OPTIONAL) make disappear all "known" actors under it's area of effect. with this we get the building/defence positions masked for the enemy but not the exact position of the MGG. More subtle and better in the overall. 

last effect "optional" -> why ? As the gap gen is used to make your base "invisible" under fog of war, the principal perk of the MGG would be to reduce vision of the enemy on battlefield .So to not make it redundant with the static one he could not be able to hide building under fog in range (and still be super usefull).

Conclusion, openra big change in compare of the original is the fog of war, i think it is time gap generator and mgg adapt to this new mechanic and stop working on an old not used feature "shroud".

**Comment by pchote** [comment] 2020-02-25 13:20
>Explored map is always chosen by default, proof 0% of the player base want to lose time "exploring" the map.

Only a small fraction of players play online, so statements like this really aren't very useful.

**Comment by deleted-user-1** [comment] 2020-02-25 13:24
Potential duplicate of #15364 and related to #15887. See also the discussion in https://forum.openra.net/viewtopic.php?p=309805#p309805 and https://forum.openra.net/viewtopic.php?p=309985#p309985.

**Comment by WhoCaresora** [comment] 2020-02-25 15:19
> Only a small fraction of players play online, so statements like this really aren't very useful.

My bad, i meant the portion that plays online, corrected.

#15364 covers this pretty much, shall i comment there and this one to be deleted ?

**Comment by abcdefg30** [comment] 2020-02-25 16:44
> #15364 covers this pretty much, shall i comment there and this one to be deleted ?

Closing as duplicate of #15364 then.

**Closed as completed by abcdefg30** 2020-02-25 16:44 UTC
Labels: Idea/Wishlist
