### ISSUE TITLE
MapEditor bug: Some actors place in mapEditor not appearing in-game

### ISSUE THREAD

**Issue by DanRea** [OpenRA/OpenRA#7514] opened 2015-02-21 05:36 UTC
Steps to reproduce:
1 - Place tran.husk1 (or any  burnt-out/crashed vehicle actor) in a map.
2 - run map and explore placed actors.

Expected result:
Placed actors are where they were placed.

Actual Result:
Placed actors can not be seen.

Relevant debug log output:
harv.emptyhusk #335 killed by harv.emptyhusk #335
mcv.husk #540 killed by mcv.husk #540
harv.emptyhusk #715 killed by harv.emptyhusk #715
tran.husk2 #1556 killed by tran.husk2 #1556
tran.husk1 #1560 killed by tran.husk1 #1560
tran.husk1 #1561 killed by tran.husk1 #1561

**Comment by Mailaender** [comment] 2015-02-21 11:29
That is because the actors are damaged over time with the https://github.com/OpenRA/OpenRA/wiki/Traits#burns trait. I know that this is confusing. Closing as a duplicate of https://github.com/OpenRA/OpenRA/issues/7115.

**Closed by Mailaender** 2015-02-21 11:29 UTC
Labels: Question

**Comment by penev92** [comment] 2015-02-23 18:26
Wouldn't say duplicate, but doing that would fix this problem.
