### ISSUE TITLE
Only one infantry unit can move into a cell with a crushable actor at a time

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#4826] opened 2014-03-08 00:38 UTC
##

**Comment by matjaeck** [comment] 2018-08-13 13:49
I can reproduce this in playtest-20180729 and if I understand it correctly, this only applies to mines so it might be good to give it a more precise title.

![101](https://user-images.githubusercontent.com/37185497/44035720-68661c4e-9f10-11e8-9df1-0b29844a9d98.gif)

**Comment by reaperrr** [comment] 2018-08-13 21:03
We should at least try to fix this for next+1.

**Comment by pchote** [comment] 2018-10-25 21:32
@reaperrr do you think this is still in-scope for Next + 1, or shall we drop this off?

**Comment by reaperrr** [comment] 2019-04-22 22:53
I think/hope this will be fixed by @teinarss' pathfinding refactoring, but since there's no ETA yet and there's no explicit PR for this bug on the horizon right now, I'll move it to Next+1. If we could sneak in a fix for this before the next playtest anyway that would be nice, but I guess after over 4 years living with this it shouldn't be a blocker.

**Comment by teinarss** [comment] 2019-04-23 12:06
This would get fixed by https://github.com/OpenRA/OpenRA/pull/15112 and https://github.com/teinarss/OpenRA/commit/f93b7832447a9562ff89aeb43b524e03bf911a2e but i can also fix it directly it the curret code.

**Comment by matjaeck** [comment] 2019-10-02 04:03
This has not been fixed yet on current bleed.

**Comment by pchote** [comment] 2020-01-05 00:21
It turns out that the infantry aren't actually blocked by the mine/crate/etc. They are blocked by the first infantry that starts moving into the cell to crush it.

So this is actually just another aspect of #5968, but it is a sufficiently useful testcase that IMO we should keep the issue open instead of having a single monster "out path following sucks" issue that can't be directly actioned against.

Changing https://github.com/OpenRA/OpenRA/blob/535144b208dec52c2ebe0312555e663e8a50ce1f/OpenRA.Mods.Common/Activities/Move/Move.cs#L227 to add `check: BlockedByActor.Immovable` solves the issue, but probably causes other undesirably regressions.

**Comment by pchote** [comment] 2020-01-05 00:57
Digging deeper, the issue is that these fast-path assumptions in the Locomotor:
https://github.com/OpenRA/OpenRA/blob/535144b208dec52c2ebe0312555e663e8a50ce1f/OpenRA.Mods.Common/Traits/World/Locomotor.cs#L285-L303

are not account for subcell availability. It really doesn't matter if the cell has an actor that you can't crush if is occupying a different subcell!

The one-line fix for this issue is to add `subCell == SubCell.FullCell` to the check and make all subcell checks take the slow path. This isn't ideal though - we can and should still take the fast path if we know that the cell occupants don't use subcells.

**Comment by pchote** [comment] 2020-01-05 01:05
https://github.com/OpenRA/OpenRA/blob/535144b208dec52c2ebe0312555e663e8a50ce1f/OpenRA.Mods.Common/Traits/World/Locomotor.cs#L263-L265

This comment is also wrong - `HasFreeSpace` is set to 0, so is false if any other flag is set. This means that it can't tell us anything about free subcells, and should probably be renamed to `IsEmpty`

**Comment by pchote** [comment] 2020-01-05 01:15
Digging deeper still... This case is supposed to be handled by `CellFlag.HasFreeSpace`, which would normally be set (and all other flags left unset) when we detect that there is at least one free subcell available.

The problem is that `ActorMap.HasFreeSubCell` does not account for crushability, so returns false because the crate/mine/whatever is supposedly occupying the full cell. I'm surprised that more things aren't broken by this.

**Comment by pchote** [comment] 2020-01-05 01:31
A starting point that works for crates and mines:
```diff
diff --git a/OpenRA.Mods.Common/Traits/World/Locomotor.cs b/OpenRA.Mods.Common/Traits/World/Locomotor.cs
index 7e26b21cb3..5d01f8df57 100644
--- a/OpenRA.Mods.Common/Traits/World/Locomotor.cs
+++ b/OpenRA.Mods.Common/Traits/World/Locomotor.cs
@@ -483,7 +483,20 @@ void UpdateCellBlocking(CPos cell)
                                        return;
                                }
 
-                               if (sharesCell && actorMap.HasFreeSubCell(cell))
+                               Func<Actor, bool> isBlocker = other =>
+                               {
+                                       var crushables = other.TraitsImplementing<ICrushable>();
+
+                                       // TODO: This will only work for actors that can be crushed by everybody...
+                                       // We need to find a way to manage `CellFlag.HasFreeSpace` conditionally on player...
+                                       foreach (var crushable in crushables)
+                                               if (crushable.CrushableBy(other, Info.Crushes) == world.AllPlayersMask)
+                                                       return false;
+
+                                       return true;
+                               };
+
+                               if (sharesCell && actorMap.FreeSubCell(cell, SubCell.Any, isBlocker) != SubCell.Invalid)
                                {
                                        cache[cell] = new CellCache(default(LongBitSet<PlayerBitMask>), cellFlag);
                                        return;
```

**Comment by teinarss** [comment] 2020-01-05 08:35
> 
> 
> Digging deeper still... This case is supposed to be handled by `CellFlag.HasFreeSpace`, which would normally be set (and all other flags left unset) when we detect that there is at least one free subcell available.
> 
> The problem is that `ActorMap.HasFreeSubCell` does not account for crushability, so returns false because the crate/mine/whatever is supposedly occupying the full cell. I'm surprised that more things aren't broken by this - for example, are we able to paradrop units into a cell with mines/crates?

Yes we can paradrop units into a cell with mine/crates, the problem would arise if we had one unit that shares cells but not collect crates occupying this cell together with the mine/crate and then trying to paradrop into this cell.

**Comment by teinarss** [comment] 2020-01-05 10:27
Another solution would be to implement the mine and crate refactoring that
me and rreaper started, and let actors that share cell and can crush be
something we don't support.

**Comment by pchote** [comment] 2020-01-05 12:51
My motivation for digging into this was that I didn't like the idea of just migrating crates and mines away without understanding exactly what the issue was with the crushing logic.

Now that I do (may already have been obvious to you and @reaperrr) I can get behind removing crushing support from subcell actors as our proper long term fix.

We all seem to be struggling with motivation to complete #15112 / #17197, so probably not feasible for Next + 1 now. The question is whether we want to bump this off the milestone, or implement my first suggestion to push this case to the slow path and treat #15112 / #17197 as performance optimizations?

**Comment by teinarss** [comment] 2020-01-05 12:55
Are you sure that jumping directly to the slow path for this case will
solve the problem?

**Comment by pchote** [comment] 2020-01-05 12:57
My tests suggested that it does, but maybe I was focusing too narrowly and missed some other issues? Do we have a reason to suspect that it wouldn't in all cases?

**Comment by teinarss** [comment] 2020-01-05 13:01
Only that this is not a new problem, right? And the slow path is using the
old code more or less, I'm maybe forgetting something.

**Comment by pchote** [comment] 2020-01-05 13:10
@abcdefg30 suggested that #17222 probably fixed the slow path case.

**Comment by tovl** [comment] 2020-01-05 23:23
> Digging deeper, the issue is that these fast-path assumptions in the Locomotor:

It's a bit silly to blame these: They are relatively recent additions to the code (in fact still bleed-only at this point), while the issue here is years old.

>  let actors that share cell and can crush be something we don't support.

That would be a pity. The most general solution would be to just have a per-subcell cache. IMO we should investigate what the practical implication on memory usage of that would be.

**Comment by teinarss** [comment] 2020-01-06 15:42
Also found a regression with using the slow path solution, when several infantries trying to collect a crate together several of them got gibbed.

**Closed** 2020-02-09 12:18 UTC
Labels: Bug, Pathfinding
