### ISSUE TITLE
Alliances

### ISSUE THREAD

**Issue by BeanBnZ** [OpenRA/OpenRA#15695] opened 2018-10-09 18:14 UTC
Idea for TD/RA/D2k

Re introduce alliance option in map options menu, this will be especially useful in free for all matches & could be lot of fun in many situations. Like removing the build radius it won't always be used, but it will create new dimension of play.

**Comment by abcdefg30** [comment] 2018-10-09 22:54
Duplicate of #15061. :)

**Closed by abcdefg30** 2018-10-09 22:54 UTC
