### ISSUE TITLE
Option to play or spec

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12642] opened 2017-01-29 16:47 UTC
Option to jump in and play as a spectator when a player leaves.

"Player" left do want to play in his place?

Will also help somewhat on spectators being auto kicked before game start.

**Comment by obrakmann** [comment] 2017-01-29 17:01
Duplicate of #3255 and #6131.

**Closed by obrakmann** 2017-01-29 17:01 UTC

**Comment by Snurre86** [comment] 2017-01-29 17:40
not really a duplicate as you don't rejoin the game.

**Comment by obrakmann** [comment] 2017-01-29 18:30
Doesn't matter, spectators still need the full state of the game, so just jumping into a running game doesn't work.
