### ISSUE TITLE
AI BuildingLimit doesn't limit anything

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14024] opened 2017-09-15 14:36 UTC
The **AI happily ignores building limits.** In Dune2k every production structure and all tech structures are set to max 1. Despite that the AI builds 1,2 or 3 repair pads, 2 warfactories, 5 refineries, multiple outposts etc...
![bug_buildinglimit3](https://user-images.githubusercontent.com/16046997/30487360-8c24cdc0-9a33-11e7-9e3f-060e4b4ec996.png)

On units the limit seems to work.

Also, the limit should imply **all transformations** of a unit. So, if I say MCV: 1 the AI should build one mcv ONLY if it hasn't a conyard allready. As of now the AI builds one mcv, deploys it and then builds another one... -.-
That would also require new errors if two conflicting limits are set. (MCV=1, Conyard=3)

**Comment by reaperrr** [comment] 2017-09-15 14:46
Is this at Normal gamespeed?

The problem could be that the AI only consider buildings which have already been placed, not those that are currently in production.

Additionally, we had an issue in the past (and maybe still have) that at higher game speeds, the AI would give a build order twice, due to some issues with the order queue.

**Comment by MustaphaTR** [comment] 2017-09-15 14:56
Duplicate of #11917?

**Comment by CH4Code** [comment] 2017-09-15 15:04
Indeed a duplicate, with the exception of the **all transformations** issue.

Fastest gamespeed, no dev mode. Once it places a building, the AI should know about what it has built.. wonder how three repair pads can occur...

**Comment by reaperrr** [comment] 2017-09-15 15:08
> wonder how three repair pads can occur...

That's likely to be that order queue issue I talked about (for the 3rd one).

The 2nd is in all cases due to a horribly stupid bug, I'll file a fix shortly.

**Comment by CH4Code** [comment] 2017-09-15 15:11
One thing that comes to my mind is that OnProduction (LUA) does not trigger at all for buildings. Maybe that has to do with it..?

**Comment by reaperrr** [comment] 2017-09-15 15:28
#14025 should at least reduce the issue.

I can't say for sure how much the AI order queue issue is to blame though, so at fastest game speed, #14025 might help less than I'd hoped.

**Comment by GSonderling** [comment] 2017-10-10 09:53
I hate to say this, but should this even be considered a bug? If it does diminish efectivity of AI then by all means, but building few spare factories and refineries is not exactly a bad tactical decision in my book.

I myself do it, and I bet others do too. It certainly comes in handy if you loose half a base to a nuke.

**Comment by GraionDilach** [comment] 2017-10-10 16:46
Modders should be able to limit the amount of buildings built by the AI. Sure, limiting it to one or two per production building might not make sense, but I actually have a complex counter-example where limiting makes absolute sense.

The AI wants to produce on ALL available queues. With individual queues per factories + unlimited amount of factories this gets problematic itself, if the AI end up with so many factories that it runs out of cash simply because it's ecomony ain't strong enough to supply all of them. Now, I have a mercenary branch as well, where stuff is trained faster than standard but for a fee. With unlimited buildings, you basically force me for a situation where my AI might end up running out of cash, because it built more merc factories than one or two and wasted it's cash on this production fee, which led to being outrun by it's opponent and losing the match.

The above situation is completely doable, and should be supported as it's part of modding.

**Comment by NotoriousPyro** [comment] 2020-02-07 01:51
I have witnessed the AI more than once, with one conyard build two radars within ms of each other on CNC at the fastest game speed. As if it had duplicated the radar deployment...

**Comment by muppet9010** [comment] 2021-08-03 23:13
I've seen this double building occur in testing AI's at normal game speed and the buildings are queued and placed sequentially.

1. Radar limited to max 1 and AI with 1 construction yard (CnC).
2. Queue radar
3. Places radar
4. Queue another radar
5. Place second radar

**Comment by Mailaender** [comment] 2021-09-04 17:27
3 radars in @OpenHV

![image](https://user-images.githubusercontent.com/756669/132103303-39cbf40e-3c8e-462b-b8e1-8e78a31714a9.png)

I think the AI is picking the first one in the list that isn't construction yard or power plant.

**Comment by NotoriousPyro** [comment] 2021-11-04 09:34
I remember spending a lot of time watching this behaviour when I was changing the AI around. I found that the AI seemed to simultaneously schedule another build of the same structure, even when it was at the build limit.

The sequence is something like this:

1. AI does not have enough of X building, so it schedules X to be built
2. X is built, a thread in OpenRA starts the placement sequence.
3. As soon as the building is placed, the AI instantaneously places another build order for X. As if two threads were running simultaneously, one to check if we need to queue it and another to place it.

In some circumstances it appears as though there is a brief window in which the AI is checking what it needs to build and the building becoming "visible" to the other thread by finishing placement.

Almost as if
1. Thread 1: Count of building X: 0
2. Thread 2: Is building in queue? No -> Schedule building X: 1
3. Executing simultaneously: Thread 3: Place building X, increase building count by 1 Thread 1: Count of building X: 0
4. Thread 2: Is building in queue? No -> Schedule building X: 1

It's a possible race condition of accessing the same memory... The example here explains the situation I think https://en.wikipedia.org/wiki/Race_condition#Example

**Comment by Mailaender** [comment] 2021-11-04 12:33
I am not sure if it is a race condition in the classical term as no threading is involved as far as I know. 

More like the update of the player's buildings

https://github.com/OpenRA/OpenRA/blob/e1e76411f7c7e6411906991a2caa297f8faa4d4b/OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs#L96-L100

is slower than the rescheduling of a new item for the build queue

https://github.com/OpenRA/OpenRA/blob/e1e76411f7c7e6411906991a2caa297f8faa4d4b/OpenRA.Mods.Common/Traits/BotModules/BotModuleLogic/BaseBuilderQueueManager.cs#L109-L114

which is also random and that makes this harder to reproduce.

**Comment by PunkPun** [comment] 2024-03-11 08:48
fixed by #20133 ?

**Comment by PunkPun** [comment] 2024-03-11 09:06
In my games AI doesn't build multiple tech buildings

**Closed by PunkPun** 2024-03-11 09:06 UTC
Labels: Bug, AI

**Comment by Mailaender** [comment] 2024-03-11 11:34
This shows `d2k` which like `hv` has a longer delay until the building is placed. I think the bots queued faster than the placement. https://github.com/OpenRA/OpenRA/commit/52b597d5d24d1706a14ff55646fddeeae6808788 increased the `StructureProductionActiveDelay` which I believed helped. https://github.com/OpenRA/OpenRA/pull/20981 should also lessen the problem.

**Comment by PunkPun** [comment] 2024-03-11 11:41
I'm more thinking about dbfb08ff6fe78149ade2d6dbf164efc55e87a746 which now considers buildings being produced as being already produced
