### ISSUE TITLE
You can see mines when it is laid

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#11728] opened 2016-07-28 17:35 UTC
It is only for one tick or so but enough for artys too shoot on them and blow up the minefield and often the minelayer with it.
You can also see them in shroud for a short moment so players sometimes see your minelayer working on a minefield wich makes it like useless.
Its the moment it is laid.

**Comment by abcdefg30** [comment] 2016-07-28 19:37
Duplicate of #7995. Thanks for the report though! :)

**Closed by abcdefg30** 2016-07-28 19:37 UTC
Labels: Bug, Red Alert
