### ISSUE TITLE
Voice "Training" for many times

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12573] opened 2017-01-13 04:51 UTC
As we all know, we click soldiers in the barrack or  want click some vehicles in the factory, OpenRA will says"Training" for many times, this sounds very bad

**Comment by jaZzKCS** [comment] 2017-01-13 10:47
This is not a "bug", this is intended behavior. Are you perhaps proposing the sound to be optional (i.e. to have a tick box in the options like the "cash"-ticks)?

**Comment by GraionDilach** [comment] 2017-01-13 14:35
No, this is about limiting the amount of UI voices played at the same time, similarly how unit voices got a similar fix a while ago.

**Comment by Micr0Bit** [comment] 2017-01-13 15:27
i wouldnt necessarily call that a fix ... when audiofiles get "cut" by the next audiofile before they end ... instead of "overlapped"

**Comment by GraionDilach** [comment] 2017-01-13 15:31
True, I want to change that by dropping the newer voice instead and playing the old because that's what the RA2 and Generals did and it's absolutely annoying with voicesets containing long lines (two three seconds)..

**Comment by Mailaender** [comment] 2017-01-14 07:14
Duplicate of https://github.com/OpenRA/OpenRA/issues/4690.

**Closed by Mailaender** 2017-01-14 07:14 UTC
Labels: Audio, Polish
