### ISSUE TITLE
teleport 13 tank in one chrono action

### ISSUE THREAD

**Issue by AliT1993** [OpenRA/OpenRA#13994] opened 2017-09-07 08:42 UTC
hi
in multiplayer game i saw this action more than one time and i attach last replay in this issue
i know this is a bug but how can do it ? when somebody do it against me its not be a fareplay !!!
and somtimes teleported tanks don't returned to beginig place and stay on other side!
you can see this in attached replay file more than one time and first one ocured in 17:12

[OpenRA-2017-09-06T155120Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1283990/OpenRA-2017-09-06T155120Z.orarep.zip)

**Comment by MustaphaTR** [comment] 2017-09-07 08:57
Teleporting 13 tank is not a bug, it is Special to Germany.

Tanks not turning back is a bug tho which makes this duplicate of #13059.

**Comment by AliT1993** [comment] 2017-09-07 09:12
idk Germany special action sorry
thanks for respond

**Comment by pchote** [comment] 2017-09-07 13:14
Closing as duplicate.

**Closed by pchote** 2017-09-07 13:14 UTC
