### ISSUE TITLE
Resources growing/spreading logic should be configurable seperatly from each other

### ISSUE THREAD

**Issue by Dutchygamer** [OpenRA/OpenRA#9525] opened 2015-10-03 20:29 UTC

**Comment by penev92** [comment] 2015-10-03 20:55
Also as I understand, those work separately in TS.

**Comment by pchote** [comment] 2015-10-13 08:08
Duplicate of #9524.

**Closed by pchote** 2015-10-13 08:08 UTC
Labels: Refactor, Tiberian Sun

**Comment by penev92** [comment] 2015-10-13 09:08
Not as far as I understood it.  :?

**Comment by GraionDilach** [comment] 2015-10-13 11:55
The resource seed splitting should be configurable per resource. #9524 is just related. I can understand why they overlap but even then that other issue should be closed then.

**Comment by Mistranger** [comment] 2017-06-02 19:02
Done: https://github.com/OpenRA/OpenRA/pull/13428
