### ISSUE TITLE
Instructing group of rocket soliders to hit inaccessible target causes game to slow significantly

### ISSUE THREAD

**Issue by collimation** [OpenRA/OpenRA#11614] opened 2016-07-09 08:04 UTC
Instructing group of rocket soliders to hit inaccessible target causes game to slow significantly

**Comment by djlists** [comment] 2016-07-09 08:22
This happened while trying to shoot down a mig circling over the water.

**Comment by WolfGaming** [comment] 2016-08-10 11:20
Probably because every one of them is pathing through all accessible cells and continue to do so every tick, couple of ways to fix this would be:
   1. To group path this so we only path once.
   2. Drop the order if inaccessible.
   3. Move to the closest cell to the target and if its still inaccessible drop the order.
Number 1 would be the best as we preserve the order that the player gave but we would need to implement formations and formation moving with compensation for inaccessible terrain, this might break something too since the movement code is finicky at best.

**Comment by GraionDilach** [comment] 2016-08-10 11:26
Number 3 is what the Westwwod games did.

**Comment by WolfGaming** [comment] 2016-08-10 11:39
Number 3 is kind of a bandaid since we would still need to do that expensive pathing until they drop the order so the game will slow down while they are moving there unless we don't repath and just queue the Attack order after the Move order but that would mean they had to move to the end of the move order so even if for example that mig flew over them they wouldn't target it.

**Comment by WolfGaming** [comment] 2016-08-10 11:43
Maybe we could try reverse pathing it, pathing from the enemy to the actor then flipping it, we would need to figure out range vs inaccessible terrain though...and this would make pathing way worse if the target was on a big inaccessible island and the actor was on a small isolated island.

**Comment by pchote** [comment] 2016-08-10 12:01
Our movement code already does (3) (which is the source of several bugs), and does a bidirectional a* (forward and reverse pathong at the same time, meeting in the middle)

**Comment by WolfGaming** [comment] 2016-08-10 12:29
Guess we already have that in place then, do we stop the bidirectional a* if one of them is unable to find more cells, because if so then it shouldn't slow if we target something inaccessible since we would stop very early on.

**Comment by pchote** [comment] 2016-08-10 13:03
We calculate and the connected regions at map load, and don't path at all if we know it's not accessible.

**Comment by WolfGaming** [comment] 2016-08-10 13:04
Something wierd with aa to flying units then?
According to what you say we shouldn't be slowing down at all in this case.

**Comment by pchote** [comment] 2016-08-10 13:07
I wouldn't be too surprised if this case was managing to somehow skip the DomainIndex check.

**Comment by WolfGaming** [comment] 2016-08-10 13:09
Maybe its failing or succeeding on some check because one of the actors doesn't think the terrain is inaccessible. In which case that needs some refactoring.

**Comment by reaperrr** [comment] 2017-07-11 16:42
Is this still the case on bleed or did the 'CanInteractWith*Layer' stuff possibly fix this?

**Comment by reaperrr** [comment] 2019-07-27 11:38
Moving to Next+1, but more of a reminder to check if this is even still an issue to begin with.

**Comment by Logicon2020** [comment] 2020-05-05 09:18
How about a 'follow the leader' approach if there are several units next to each other.  Do path finding for one and then once the lead unit has moved from the first node, relay that point to the second unit in the group which will then take the place of where the first unit was. Keep moving the valid nodes from the top to bottom of the units. You can still do a 'is still valid' on each unit as it checks the position it has been given by the one in front.

**Comment by abcdefg30** [comment] 2020-08-29 20:34
Closing as duplicate of the more general #12938.

**Closed by abcdefg30** 2020-08-29 20:34 UTC
Labels: Bug, Performance
