### ISSUE TITLE
My game crashed (because additional monitor?)

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#19103] opened 2021-01-30 15:32 UTC
- Operating System:  Windows 10 Home
- OpenRA Version: OpenRA engine version release-20200503
- OpenRA Mod: Red Alert mod version release-20200503
- Source: Official download package

## Exception log
```
`OpenRA engine version release-20200503
Red Alert mod version release-20200503
on map f6c528c39e04c6880343ef6be5d2a43d086980fa (Desert Shellmap by Scott_NZ).
Date: 2021-01-29 17:01:30Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentNullException`: Der Wert darf nicht NULL sein.
Parametername: key
   bei System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   bei System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   bei OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   bei OpenRA.MapCache.<>c__DisplayClass14_0.<QueryRemoteMapDetails>b__0(String uid)
   bei System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bei System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   bei OpenRA.MapCache.QueryRemoteMapDetails(String repositoryUrl, IEnumerable`1 uids, Action`1 mapDetailsReceived, Action queryFailed)
   bei OpenRA.Mods.Common.Widgets.Logic.ServerListLogic.<>c__DisplayClass37_0.<RefreshServerListInner>b__0()
   bei OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   bei OpenRA.Game.LogicTick()
   bei OpenRA.Game.Loop()
   bei OpenRA.Game.Run()
   bei OpenRA.Game.InitializeAndRun(String[] args)
   bei OpenRA.WindowsLauncher.RunGame(String[] args)`
```

## Replay
nope

## Additional information
Just got a crash when clicking on "multiplayer" in the main menu, twice. Then I unplugged a hdmi cable to a monitor, and it worked on the next try. Can't tell if it was audio or video.

**Comment by pchote** [comment] 2021-01-30 15:35
This was from yesterday afternoon or evening, right? That will make it a duplicate of #19098 which is already fixed.

**Comment by Mailaender** [comment] 2021-01-30 16:18
Yes, same stacktrace as https://www.reddit.com/r/openra/comments/l7z583/is_openra_down/gl9nyh3/

**Closed as completed by Mailaender** 2021-01-30 16:18 UTC
Labels: Crash

**Comment by TheRaffy** [comment] 2021-01-31 08:38
Yes, it was. Good job btw! Thanks!
