### ISSUE TITLE
[map editor] How to rotate ?

### ISSUE THREAD

**Issue by bioinfornatics** [OpenRA/OpenRA#19308] opened 2021-03-31 20:46 UTC
Dear,

I read the documentation about [mapping](https://github.com/OpenRA/OpenRA/wiki/Mapping), but I do not found how to rotate a selection ?
Indeed, in order to make a symmetrical map I would like to make one spawn area with ore etc … copy the area and put this template at multiple location. But to do this I need to rotate the selection. Or able to trace a symmetric line and apply all items in one side as mirror to another side.

I tried to look into `.bin` file in order to make a custom script for this task, but I have not found the specification of such file.

Thanks for your help best regards

**Comment by Leo512bit** [comment] 2021-04-01 20:49
You can't currently rotate stuff using the copy-paste tool you can only rotate certain actors like units.

**Comment by Smittytron** [comment] 2021-04-09 15:08
Closing as a duplicate of #10513. While not a 1:1 duplicate, symmetrical overlay tools are much more feasible than something that copies and rotates map tiles.

[Here is a concept](https://www.youtube.com/watch?v=swGe6noc-YA) of what such a tool could look like.

**Closed as completed by Smittytron** 2021-04-09 15:08 UTC
Labels: Idea/Wishlist, Map Editor
