### ISSUE TITLE
War factory door seizure

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9966] opened 2015-11-11 14:54 UTC
I'm not sure EXACTLY what was causing it but my theory is below. The war factor door was having a seizure. 
My theory is something moved into the way of the door JUST as a unit was created so it wasn't able to exit.

I dunno shit was going down pretty fast and hard.
##

**Comment by penev92** [comment] 2015-11-11 15:02
Can you give us a replay?

**Comment by epicelite** [comment] 2015-11-11 15:16
Yeah where can I upload it? 

Its this war factory at 14:10 watch it, Tesla Tank comes out and then door goes nuts.
![](https://lh3.googleusercontent.com/-N-T_RTppimA/VkNbAEF8FGI/AAAAAAAABfU/ZHDgUrm7hso/s1024-Ic42/crazy%252520door.JPG)

**Comment by pi99y** [comment] 2016-05-11 14:20
This bug is still present in Release 20160508.
Replay: http://filebin.net/2fmwk2henb/OpenRA-2016-05-11T133940Z.orarep

(upper left corner, greenish Normal AI's War factory **at ~12:06**)

**Comment by abcdefg30** [comment] 2020-08-29 19:33
Closing as reverse duplicate of #13489.

**Closed by abcdefg30** 2020-08-29 19:33 UTC
Labels: Bug
