### ISSUE TITLE
release-20180307: Ungracefully crashes mid-game. Cannot restart game. Problem persists after re-install (game not starting).

### ISSUE THREAD

**Issue by Lukemtesta** [OpenRA/OpenRA#15318] opened 2018-07-01 22:54 UTC
[exception-2018-07-01T225117Z.log](https://github.com/OpenRA/OpenRA/files/2153313/exception-2018-07-01T225117Z.log)
[exception-2018-07-01T225207Z.log](https://github.com/OpenRA/OpenRA/files/2153314/exception-2018-07-01T225207Z.log)
[traitreport.log](https://github.com/OpenRA/OpenRA/files/2153315/traitreport.log)
[install.log](https://github.com/OpenRA/OpenRA/files/2153316/install.log)

Step to reproduce (Intermittent)

Run latest Red Alert release candidate. Join active server. Spam units and builds.

Environment: Windows 10

**Comment by Lukemtesta** [comment] 2018-07-01 23:01
Maybe file discovery has an issue, but would expect the install to delete and re-deploy dependencies. Default installation path used (The game was running fine for 3 matches over an hour).

**Comment by pchote** [comment] 2018-07-01 23:04
The first exception is #15187, which will be fixed in the next release.
The second exception occurs when you try to run `OpenRA.Game.exe` directly, which is no longer supported.   You must run RedAlert.exe or the other launchers instead.

**Comment by Lukemtesta** [comment] 2018-07-02 11:30
@pchote Sweet. I will check tonight to see if the shortcuts were legacy or deployed.

**Comment by Lukemtesta** [comment] 2018-07-02 20:00
@pchote Can confirm legacy shortcut was causing the problem.

**Comment by pchote** [comment] 2018-07-02 20:03
Great.  Closing as duplicate of #15187 then.

**Closed by pchote** 2018-07-02 20:03 UTC
