### ISSUE TITLE
glitch with transport units

### ISSUE THREAD

**Issue by normannorman** [OpenRA/OpenRA#9594] opened 2015-10-11 01:22 UTC
if you select many empty transport units like chinook or apc, in some of those, units are displayed sometimes

**Comment by ChaoticMind** [comment] 2015-10-11 08:31
This is actually most likely a side effect of having the healthbars show (when units are selected or when they're set to always show) and having the health bars and the "units in transport squares" use the same colors (as well as having the squares be transparent when empty).

In other words, if there's another unit's healthbar on "top" of a transparent empty unit transport-square, it would seem as if the transport square is green (filled) even though it's not really. 

I've seen this as well and was originally confused. I think some possible solutions are: 

1. Don't let the empty unit transport squares be transparent, but give them a color. (potentially confusing and ugly)
2. Have the unit-transport bars have a different color than the health bar's (green). Either a static color or a player color? This might be still confusing, but is worth a try.
3. Have the health bar be a different color (player color? unsure if it would look weird). If we pick player color, we probably want to add the "healthbar green" to the list of disallowed player-selection colors (like civilian or terrain color). This also applies for 2.
4. Combination of 1 and 2
5. Something more complicated like: If a healthbar and a "unit transport square" are overlapping, change the drawing order to be: healthbar/terrain/squares (or equivalently just terrain/squares, i.e. don't draw the other unit's healthbar) instead of the current terrain/healthbar/squares (or equivalently terrain/squares/healthbar since squares are transparent). In other words, the terrain shows in the transparent squares instead of the other unit's healthbar when the squares are empty. (This is probably the nicest solution imo but also probably very not worth it)
6. ???

I think if we change the transport bars to be the same color as the player, we should bear in mind that this issue could resurface if someone decides to change the healthbars to the player color in the future.

I probably prefer solution 2 - or it's worth experimenting with, at least. Solution 5 is preferred if detecting that case and just not drawing the other unit's healthbar is actually not-that-hard to do (or is realistically feasible).

**Comment by obrakmann** [comment] 2015-10-11 10:35
Duplicate of #9559.

**Closed by obrakmann** 2015-10-11 10:35 UTC
Labels: Polish
