### ISSUE TITLE
Chase units outside its vision in "fog of war" 

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#10484] opened 2016-01-11 14:46 UTC
When a unit leaves a chasing units vision in a chase it should follow in that direction for 10 cells not knowing where the unit is but assuming a strait direction for 10 or so cells and continue following if it pops back in to view.

**Comment by obrakmann** [comment] 2016-01-11 19:26
Duplicate of #10223.

**Closed by obrakmann** 2016-01-11 19:26 UTC
Labels: Idea
