### ISSUE TITLE
Ingame map editor : Smart tile drawing [$35]

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#4995] opened 2014-03-30 18:02 UTC
It would be really useful if the new ingame map editor could analyze the direction of cursor when the player is drawing with tiles.

With this "path", OpenRA could maybe apply correct tiles, in order to create nice looking cliffs.

Currently, here is what we can do:
![screenshot002](https://cloud.githubusercontent.com/assets/1732773/2562007/121faf7e-b835-11e3-99f5-a273600335a4.png)

OpenRA would record the mouse gesture, record which category of tile is currently used (here : cliffs):
![screenshot003](https://cloud.githubusercontent.com/assets/1732773/2562009/5b5dce14-b835-11e3-8e3e-825d8aac7efd.png)

And with these informations, it could redraw the player's tiles with correct ones:
![screenshot004](https://cloud.githubusercontent.com/assets/1732773/2562010/5e5d15ca-b835-11e3-9fd4-0744f8f48c84.png)

**Comment by xan2622** [comment] 2014-06-06 19:59
I was not asking to support this TMX map format. We already discussed about Tiled months ago, and my idea about supporting Tiled maps was just ... a simple idea among many others. :) The current ingame map editor already fills all needs.

Here, I showed you these videos for the concepts of map creation they brought.

**Comment by pchote** [comment] 2015-05-26 17:04
This feature isn't practical, and probably isn't possible at all in TD/RA because of artwork constraints.  Closing as part of a cleanup of editor bugs.

**Closed by pchote** 2015-05-26 17:04 UTC
Labels: Bounty, Idea, Map Editor

**Comment by Mailaender** [comment] 2016-01-30 21:48
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/10652.
