### ISSUE TITLE
Faster edge scroll speed & static mouse for middle mouse scrolling

### ISSUE THREAD

**Issue by MeSaber** [OpenRA/OpenRA#3390] opened 2013-06-10 09:56 UTC
make a wider range for the edge scroll so u can edge scroll faster than currently possible.

Maybe make the mouse static when holding mid mouse so u wont have to do a 2 motion to make 1 scroll.

**Comment by penev92** [comment] 2015-09-21 00:22
Duplicate of several other tickets including #5368 and #9399.

**Closed by penev92** 2015-09-21 00:22 UTC
Labels: Feature
