### ISSUE TITLE
Duplication crate can put the free unit in impossable spots.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10850] opened 2016-02-28 15:56 UTC
For example: 
![](https://lh3.googleusercontent.com/-Pq-sTQwVU7s/VtMX9IRFCAI/AAAAAAAABn0/lGurbwzn2dw/s548-Ic42/glitch%252520crate%252520ore%252520truck.JPG)

**Comment by penev92** [comment] 2016-02-28 16:40
Fixed your image despite the rude borderline order you gave on IRC. Please fix your attitude.

That position is perfectly valid. The one thing we can do is have it place the new unit in the same pathing domain, but I don't know if that's even worth the effort.

**Comment by yaaaaa** [comment] 2016-02-29 11:28
It is normal practic in RA, was not it?

**Comment by pchote** [comment] 2016-04-25 14:34
Duplicate of #6515.

**Closed by pchote** 2016-04-25 14:34 UTC
Labels: Polish, Red Alert
