### ISSUE TITLE
Hijacker has trouble stealing moving vehicles

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#9879] opened 2015-11-04 02:10 UTC
so apparently , after buffing the speed of the hijacker so he is equally fast as a harvester or medium tank ... it turns out that this doesnt help to fix the problem to actually steal the vehicle ... 

when he is trying to steal a unit that is currently "moving" (harvester) ... he kinda get "set back" after trying to enter the vehicle ... so its looks like he is doing a jump backwards ... 

this is easy to reproduce , just try to steal a moving harvester (it might work sometimes , but it probably also depends on the angle youre coming from) 

people are still not satisfied , but this is something we cant fix by tweaking yaml-rules 
##

**Comment by penev92** [comment] 2015-11-04 08:17
I'm not sure I like the idea of training a hijacker guaranteeing you a stolen vehicle without effort (unless it's protected by infantry). Just saying.

**Comment by pi99y** [comment] 2015-11-04 08:36
Let me try to clarify my "problem" with the hijacker a bit...

* He is now much more useful than he was before, you can actually steal a vehicle. :heavy_check_mark: 

* I do agree with @penev92 that it should take some skill to capture a vehicle (but probably just in a way that if you start chasing a vehicle too late it might get away or that the vehicle has a (small) chance to crush you...)

* However the "jumping backwards" behavior @MicroJOo described feels like a bug and the player probably feels it's not his fault for not succeeding.

**Comment by r34ch** [comment] 2015-11-04 10:17
MicroJOo has a point. Imho the problem is the movement of infantry in general imho. It is also very noticeable with tanya and infantry moving 'into' buildings.

If you order a hijacker to steal a vehicle in a cell and that vehicle moves as the hijacker moves into that cell you expect either three things to happen;
-Go to the original cell, then move directly to the cell the vehicle moved to
-Change direction as the vehicle is moving taking the shortest route (not sure if this is possible with the current implementation)
-Capture the vehicle a cell away (as other games seem to do to solve this issue)

Currently however, the hijacker is 'repulsed' and generally moves back a cell in the opposite direction - which given the hijackers role, is puzzling to a player and can be viewed as a bug / glitch / etc

Depending on how the vehicle moves too can add to the frustration. If the vehicle moves toward the direction of the hijacker it gets squished without capturing the vehicle which again seems like a glitch from a player point of view #9560

Likewise a tanya under fire nearly always seems to crawl to a cell then crawl to a different cell before returning fire. I expect her to crawl to one cell and then return fire (although this could be #9851)

Then you have the issue of infantry visually entering buildings when they actually don't and getting crushed by a vehicle in a 'different' cell #8064

And also #9197

These situations might be working fine by code design but from a game-play point of view all these issues seem 'off' to me and give the impression of all being related (even though they probably aren't).

**Comment by epicelite** [comment] 2015-11-04 10:56
Why is the hijacker not an Allied unit?

**Comment by pi99y** [comment] 2015-11-04 11:03
@epicelite Allies get all the cool "sophisticated" units. His ways are "savage" enough that he was thankfully permitted to be a soviet unit :)

**Comment by MicroJOo** [comment] 2015-11-04 14:14
@epicelite : we gave the mechanic (allied unit) the ability to repair "husks" ... for that reason , we've made a "hijacker" out of the original "thief" ... and gave it to the soviets

cause its fair

**Comment by TheRaffy** [comment] 2015-11-12 00:21
Does the mechanic also need some skill to enter a husk? I think nope.

**Comment by MicroJOo** [comment] 2015-11-12 00:29
@TheRaffy : atleast ... it only has 10% health ...

**Comment by TheRaffy** [comment] 2015-11-12 09:15
Its not clever to hijack any damaged units, because they will die faster in battle. So you are mainly focusing for the healthy units anyway. What could considered as equal. But mechanics can repair them again and hijackers have fancy cap on their head.

Hijackers could be faster and cause 10% damage due to breaking down a entry. Would make it even more uninteresting to capture already wounded units.

**Comment by Szunti** [comment] 2015-11-18 17:00
What about stopping the vehicle while the hijacker enters? Wouldn't that solve all the glitches? With stopping it can also be slower than the target and still intercept it. Intercepting micro could be the thing against the effortless stealing.

**Comment by praetp** [comment] 2018-11-17 21:08
Tried to use hijackers and was also disappointed by the results. Can the priority of this be raised ?

**Comment by abcdefg30** [comment] 2018-11-17 22:43
https://github.com/OpenRA/OpenRA/pull/15661#issuecomment-427656171 fixed this for the next release. (We just forgot to close this issue.)

**Closed by abcdefg30** 2018-11-17 22:43 UTC
Labels: Balancing, Bug, Pathfinding, Red Alert
