### ISSUE TITLE
Bridges appear undamaged at the screen's edge

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#9322] opened 2015-09-11 22:18 UTC
... although the bridge is actually destroyed.

This happenes when the bridge is at the edge of my screen:
![bridgebuga](https://cloud.githubusercontent.com/assets/7704140/9827501/19013772-58e3-11e5-93ae-5eebb5b2e51a.png)
And this when the bridge is not at the edge (like it should be at the edge too):
![bridgebugb](https://cloud.githubusercontent.com/assets/7704140/9827502/1a84938c-58e3-11e5-8249-f9f3095e8048.png)

**Comment by pchote** [comment] 2015-09-11 22:48
I bet that adding a `CustomSelectionSize` trait will fix this.

**Comment by Mailaender** [comment] 2015-09-12 08:16
I filed https://github.com/OpenRA/OpenRA/issues/9327. Not sure which change is responsible for these regressions.

**Comment by reaperrr** [comment] 2015-09-13 15:58
Buildings completely disappear from screen once a row of cells is off-screen as well, I suspect this is a similar issue (and I doubt selection size has to do with it, unless the game wants the *whole* selection size to be on-screen).

**Comment by reaperrr** [comment] 2015-09-19 21:11
As mentioned on IRC, the previous releases (I tested June and April releases from this year) had the same issue, so it's not a recent regression and doesn't seem to be caused by the Render/SelectionSize refactorings.

**Comment by reaperrr** [comment] 2015-09-28 22:31
Fixed by #9327.

**Closed by reaperrr** 2015-09-28 22:31 UTC
Labels: Regression
