### ISSUE TITLE
Bridge dont destroy shipyard/subpen if it is repaired

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#13570] opened 2017-06-30 13:35 UTC
![bridgebug](https://user-images.githubusercontent.com/14834585/27737767-acd7dab0-5da9-11e7-8acc-7dcb0ae3dfc2.png)

**Comment by MustaphaTR** [comment] 2017-06-30 14:18
Duplicate of #9416

**Closed** 2017-07-01 14:10 UTC
