### ISSUE TITLE
Can't install assets from a TFD disk.

### ISSUE THREAD

**Issue by Bynnar18** [OpenRA/OpenRA#7550] opened 2015-02-26 03:24 UTC
This should probably be a low priority since since you can download a disk image online and make a cd, but I figure this convenience would be nice since my only readable disk at this point is a TFD one.

**Comment by Phrohdoh** [comment] 2015-02-26 03:28
Duplicate of #3863.

**Closed by Phrohdoh** 2015-02-26 03:28 UTC

**Comment by Bynnar18** [comment] 2015-02-26 03:32
My bad, I should have done a search first.
