### ISSUE TITLE
Prevent auto-RTB when aircraft without ammo are ordered to attack

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16668] opened 2019-06-09 16:20 UTC
This is in most cases not what the player wants and often the reason why aircraft get killed during attacks. This mechanic makes it really hard to micro aircraft in attacks (constantly have to babysit the units that automatically want to return to rearm so they don't fly over the next AA gun) and only rewards laziness. It should at least be a thing that can be configured via yaml. I haven't found an issue for this, but this has been requested before.

Instead of silently overriding the attack order with a RTB order that the player never wanted to issue, aircraft without ammo should behave like other unarmed units. As long as there is an armed unit selected, show the attack cursor and order unarmed units to move towards the attack target. When all units are out of ammo show the move cursor.

**Comment by Punsho** [comment] 2019-06-09 16:47
I would prefer that when an attack order was issued, the ammoless aircraft would just cancel it and start idling. That also creates another useful behaviour for when orders are queued, all attack ones will be skipped. That behaviour can be used to easily separate ammoless aircraft from a group as well as preset paths for rearming

**Comment by pchote** [comment] 2019-06-09 16:51
That would lead to aircraft idling inside the enemy base if you queue attack orders against multiple structures.

**Comment by matjaeck** [comment] 2019-06-09 17:09
If `AbortOnResupply` is set to true they wouldn't be able to continue queued orders. I can understand that this does not seem ideal but IMO it's a win when used together with `AbortOnResupply`.

**Comment by Punsho** [comment] 2019-06-09 17:44
Same would happen if you just queue an attack order for just one structure. If after those attack orders  a move or any other order that does not require attacking the ammoless aircraft will just skip to them. 

On a side note it would also be good if attack orders were canceled for all non-armed units such as medics.

**Comment by matjaeck** [comment] 2019-06-09 18:39
Attempting the attack / moving to the target would also be more similar to the original RA. Aircraft only returned when idle.

<details>

![Peek 2019-06-09 20-32](https://user-images.githubusercontent.com/37185497/59162693-ccda7400-8af5-11e9-9c55-973f7be98737.gif)
![Peek 2019-06-09 20-24](https://user-images.githubusercontent.com/37185497/59162694-ccda7400-8af5-11e9-8695-924b63ce3230.gif)

**Comment by abcdefg30** [comment] 2019-06-09 22:23
> That would lead to aircraft idling inside the enemy base if you queue attack orders against multiple structures.

That is still better than your aircraft taking the direct path back to your base through enemy defences. I really like the idea of @Punsho.

**Comment by matjaeck** [comment] 2019-06-09 23:10
The more I think about it I agree with @Punsho as well. A behavior that I could get behind is aircraft only  ignoring attack orders and continuing their running orders when out of ammo - so you have full control on move and precision on attack.

**Comment by matjaeck** [comment] 2019-11-14 20:38
I tried out both alternatives (become idle / move to target instead) and lean more towards dropping the attack order and move to the target instead. The fundamental problem I have with the current aircraft behavior is the autonomous movement behavior on attack orders. Is is an improvement when the units go idle when they can't attack but it can still lead to unexpected behavior IMO. Idle units may have the QoL-improvement that it is easier to split them from armed aircraft, but only at the cost of responsiveness and micro-ability. It also looks not right that unit just don't respond to orders when clicking somewhere with the attack cursor.

The easiest fix for the issue is to conditionally enable `Armament`s on aircraft with `RequiresCondition: ammo`. This has the effect that aircraft move to targets when they can not attack and that the attack cursor is only shown when any selected aircraft can attack (move otherwise).

**Comment by deleted-user-1** [comment] 2020-08-15 21:13
Discord discussion from some months ago made it clear that this will only be fixed when it does not mean removing auto-RTB completely from the game.

**Comment by matjaeck** [comment] 2021-05-25 00:24
This disappointment continues in #19427.

**Comment by abcdefg30** [comment] 2021-06-05 10:36
Closing as duplicate of #19427 then.

**Closed by abcdefg30** 2021-06-05 10:36 UTC
Labels: Balancing, Idea/Wishlist
