### ISSUE TITLE
Countdown before game start

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#5704] opened 2014-06-22 11:05 UTC
Could there be small delay before the game stats?

Currently i dont have the time to move my mouse over my MCV so i could deploy it as quickly as possible.

2 seconds delay at beginning would be enough. Now it starts kind of without warning.
##

**Comment by abcdefg30** [comment] 2020-05-10 15:33
Closing as reverse duplicate of #14032.

**Closed by abcdefg30** 2020-05-10 15:33 UTC
Labels: Feature, UI
