### ISSUE TITLE
Linux performance problem rendering menu

### ISSUE THREAD

**Issue by StijnDW** [OpenRA/OpenRA#7971] opened 2015-04-18 10:00 UTC
The game itself plays mostly fine. However when opening the menu, especially the input tab, the frame rate drops tremendously. This issue only exists on Linux.
Note that I have hardly any CPU or GPU usage. The nvidia driver is slightly older on Linux, but the game ran fine on windows back when it also had the older nvidia driver. So I doubt that the problem can be fixed with a simple driver update. 

These screenshots illustrate the problem:
http://i.imgur.com/A7WukI1.png

My pref.log:
http://paste.ee/r/hIVZ6

It could be related to this problem:
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=15660&postdays=0&postorder=asc&start=0

Some system stats:
software  

* Linux manjaro 3.19.3-1-MANJARO #1 SMP PREEMPT Thu Mar 26 19:16:03 UTC 2015 x86_64 GNU/Linux  
* Mono JIT compiler version 3.12.1 (tarball Thu Mar 12 06:31:20 UTC 2015)  
* openra release-20141029  
* NVIDIA Driver Version: 346.47  

Hardware  

* Nvidia GeForce GTX 960  
* Intel i7-4790k @ 4Ghz  
* 8GB ram

**Comment by Mailaender** [comment] 2015-04-18 10:07
I can't reproduce the constant widget rendering slowdowns with my Intel HD 4000 with Mesa 10.3.7 on 3.16.7 Linux kernel. Does the problem disappear when you switch to the Open Source http://nouveau.freedesktop.org/ drivers?

**Comment by penev92** [comment] 2015-04-18 10:49
This isn't linux-specific. I can show you some jaw-dropping performance graphs for widget rendering on Windows 7.
The widget rendering code need some attention in general.

**Comment by Unit158** [comment] 2015-04-18 12:29
I can't reproduce this on ubuntu trusty with my latest drivers, so I've a feeling that this is a very specific problem. The only noticeable slowdown related to UI in the past has been the sidebar when spamming units.

**Comment by penev92** [comment] 2015-04-18 13:54
OK so here's what I've got:

Opening the game lobby (it still hasn't loaded everything):
![](http://i.imgur.com/JsmVpqs.png)

Starting a game (I guess that's the sidebar being rendered):
![](http://i.imgur.com/dYwQFdS.png)

Note: Red is `render` and orange is `render_widgets`, as shown here (screenshot ingame with nothing happening):
![](http://i.imgur.com/nA3Dxsg.png)


P.S.: I just now realized that the huge rendering time increase isn't for a single tick on @StijnDW's screenshot, so it's not exactly the same issue. I think it is still related though.
I did check my perf graph in the settings menu, it just has a lot of stuff to render and for some reason renders them anew each tick. My graph was still not as bad as @StijnDW's, though.

**Comment by StijnDW** [comment] 2015-04-18 14:10
@Mailaender I tried installing the nouveau drivers, but they didn't work at all. There homepage lists support for the 960 as "work in progress" so I guess I could try this again in a few months.

@penev92 Yeah I'm getting those spikes on Windows too (just not so severe). But my problem is that they remain high.

**Comment by StijnDW** [comment] 2015-04-18 16:28
I have installed Linux manjaro 3.19.3 and openra on my laptop with NVidia GT555M driver 346.59 , it does not have this issue. So it seems specific to my GTX960 (or the 900 series in general?) on Linux.
It does have a much higher constant batch graph than @penev92.

**Comment by Mailaender** [comment] 2015-04-19 09:50
@chrisforbes we need your help. :sos:

**Comment by chrisforbes** [comment] 2015-05-01 19:23
@StijnDW unfortunately there's all kinds of madness around NVIDIA requiring signed firmware on the 900 series, so working nouveau support might be a while.

@Mailaender this looks like NVIDIA's bug. I don't have any affected hardware, but if someone who does can open a ticket with them...

**Comment by chrisforbes** [comment] 2015-05-01 19:24
A few more thoughts: if you're seeing batch count discrepancies, that's NOT something the driver has any influence over. We submit exactly the same work regardless of the driver you're running on.

Whether that work executes efficiently or not *is* up to the driver.

**Comment by Mailaender** [comment] 2015-05-01 19:30
Closing as an upstream problem outside of our control.

**Closed by Mailaender** 2015-05-01 19:30 UTC
Labels: OS: Linux, Performance, UI

**Comment by chrisforbes** [comment] 2015-05-02 05:48
OK with closing on our side, but someone needs to talk to NV about this to get it fixed ;)

**Comment by StijnDW** [comment] 2015-08-06 17:37
Update: I'm currently currently running Linux mint, kernel 3.13 with nvidia driver 349.16 and I no longer have this issue. The newer driver probably fixed this.
