### ISSUE TITLE
Naval units cause lag when no path available

### ISSUE THREAD

**Issue by TheGrinningSkull** [OpenRA/OpenRA#15083] opened 2018-04-27 17:39 UTC
I realise this pathfinding issue exists, however there's an additional element to this.

After some time during an FFA game of 6 players, with 2 lakes in the map, the game began to lag.  The lag was curbed when we told the players to highlight their naval units and press the S key to stop them and in effect reset their pathing.  This solved the lag issue in an indirect way.

I believe this issue happens after naval chronos and move order commands.

**Comment by abcdefg30** [comment] 2018-04-27 17:50
Related to #7694, #12938, #12435 and #10860.

**Comment by St3x** [comment] 2019-08-28 17:22
On bleed, AI submarines still never stop trying to reach their target, alive or dead, visible or not, which causes lag.
The pathfinding issues of units trying to reach unreachable destinations/enemies could probably be solved with a timeout.
It's not as good as the "trying to get as close as possible" comment I saw somewhere but it could end this type of pathfinding issues.
(End even if units "get as close as possible", a timeout would still be needed if the destination is still unreachable)

![OpenRA-2019-08-28T170100181Z](https://user-images.githubusercontent.com/54636529/63877755-7f6cf500-c9c8-11e9-8b11-4c05da18b92a.png)

**Comment by abcdefg30** [comment] 2020-08-29 20:33
Closing as duplicate of #12435.

**Closed by abcdefg30** 2020-08-29 20:33 UTC
Labels: Pathfinding, Performance
