### ISSUE TITLE
Add support for mp3 format

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#13610] opened 2017-07-08 10:47 UTC
Maps would be nicer if they can have their own music playing.
It should be in the .oramap so its easier to download, and be bundled with the maps.

Uses of that:
- Make it so game and modders triggers can change track and sounds: "1 minute remaining, and fast music song plays". Another track when the attack start in the mission, and triggers when first nuke is sent. etc.. First time godzilla arrive, victory music... Should be controlled by lua
- Make it easy for modders to include track with maps, also on repeat and as environment/ambient background
- Multiple tracks should be allowed to be played at once, like the aud's
- Easy bundling: Mp3 included in .oramap will be played when map starts, with no code needed in yaml or lua

In my humble opinion, this would change a lot about map-modding. It changes the feel of the game.
We did one map with zombies, lightning and thunder, and it was scary. But the music was the old normal songs, and that could really be improved. I would like to bounty this, but at least I want to promote this wish.

See also: #2174 #5491 #8999 #2774

Mailaender commented on the other:

> "The MP3 patents expired recently http://www.audioblog.iis.fraunhofer.com/mp3-software-patents-licenses/ so you can open a new issue if you want that file support added."

Example sound: https://www.freesound.org/people/danielc0307/sounds/24007/
Other sunds: https://www.freesound.org/search/?q=scary&f=&s=duration+desc&advanced=0&g=1

**Comment by reaperrr** [comment] 2017-07-09 13:41
I don't think this needs its own ticket, because once we add mp3 support, everything that is currently possible with aud and wav will be possible with mp3, too, and we already have tickets asking for adding mp3 support.

Closing as duplicate of the tickets you linked.

**Comment by pchote** [comment] 2017-07-09 13:59
Note that we don't currently have an issue for *just* mp3 format support.

**Comment by reaperrr** [comment] 2017-07-09 14:33
> Note that we don't currently have an issue for just mp3 format support.

Fair enough. I've updated the issue title to make this a non-duplicate, so I guess it can stay open.

**Comment by Comanche93** [comment] 2017-07-12 21:50
> * Multiple tracks should be allowed to be played at once, like the aud's

> * Easy bundling: Mp3 included in .oramap will be played when map starts, with no code needed in yaml or lua

Idea is good, but there is another side of the coin...
Imagine, because of *mp3 files inside, how big these *oramap files gonna be?
I believe, the best solution can be mp3 files, that go separate (e.g. like in Half-Life), so map can be downloaded without heavy *mp3 files.
IMHO

**Comment by Unit158** [comment] 2017-11-14 03:10
https://github.com/ZaneDubya/MP3Sharp

**Closed** 2021-07-07 13:20 UTC
Labels: Audio, Idea/Wishlist
