### ISSUE TITLE
Release-20151224: Attempted to finalize an undisposed DisposableAction

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#10455] opened 2016-01-07 18:25 UTC
<pre><code>Red Alert Mod at Version release-20151224
on map e359ad3b103dee63159278940e37624501fd5959 (Vegetation by hamb/Chris Forbes).
Operating System: Linux (Unix 4.3.0.1)
Runtime Version: Mono 4.2.1 (Debian 4.2.1.102+dfsg2-5) CLR 4.0.30319.17020
Exception of type `System.InvalidOperationException`: Attempted to finalize an undisposed DisposableAction. hind (490) reserved fix (452)
  at OpenRA.Mods.Common.Traits.Reservable+<Reserve>c__AnonStorey0.<>m__2 () <0x41860820 + 0x0016f> in <filename unknown>:0 
  at OpenRA.Primitives.ActionQueue.PerformActions (Int32 currentTime) <0x40491c10 + 0x001ba> in <filename unknown>:0 
  at OpenRA.Game.LogicTick () <0x40491af0 + 0x0002b> in <filename unknown>:0 
  at OpenRA.Game.Loop () <0x404918a0 + 0x0014b> in <filename unknown>:0 
  at OpenRA.Game.Run () <0x40491730 + 0x00077> in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) <0x40826a80 + 0x0005f> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x40825d60 + 0x000f7> in <filename unknown>:0
</code></pre>

Replay:
<url>http://s000.tinyupload.com/index.php?file_id=03958062858888979251</url>

**Comment by RoosterDragon** [comment] 2016-01-09 18:40
Duplicate of #9783, fixed in #9786. The fix didn't make it into release-20151224, but it will be in for the next playtest/release.

**Closed by RoosterDragon** 2016-01-09 18:40 UTC
Labels: Crash
