### ISSUE TITLE
A possibility to hide the replay % when watching a replay.

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#12438] opened 2016-11-28 20:31 UTC
It would be nice if the user is able to hide the number that shows how far the replay is in % (and turn it back on if wanted).

This to make replays more exciting to watch.

**Comment by pchote** [comment] 2016-11-28 20:36
This has already been fixed (by #12096) for the next release.

**Comment by abcdefg30** [comment] 2016-11-28 20:36
Duplicate of #12017 which was closed by #12096.

**Comment by abcdefg30** [comment] 2016-11-28 20:37
Well, ninja'd.

**Closed** 2016-11-28 20:36 UTC
