### ISSUE TITLE
Actors outside the map edge on "Center of Attention Redux 2"

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#16814] opened 2019-07-20 15:01 UTC
There are some actors just off the right edge of the map "Center of Attention Redux 2". Discovered during testing as the AI players are attacking the invisible structures.
![изображение](https://user-images.githubusercontent.com/1355810/61580234-33e94080-ab18-11e9-82b4-1687f5969d74.png)

**Comment by GraionDilach** [comment] 2019-07-20 15:45
Duplicate of #13589?

**Comment by dragunoff** [comment] 2019-07-20 15:53
Just two creepy power plants:
![изображение](https://user-images.githubusercontent.com/1355810/61580886-9c87eb80-ab1f-11e9-9920-8cb088d4a59e.png)

**Comment by airetaM** [comment] 2019-07-21 02:12
> Just two creepy power plants

The aa guns in mid need them, otherwise they are disabled.

**Comment by airetaM** [comment] 2019-07-21 02:35
To solve this the pp's could be placed in the mid, maybe with some walls surrounding them and in arty range, then it's not so easy to just capture them.
I think the reason  why they are placed outside is because the map has been created before buildradius was introduced.
So if someone touches this map, the pp's must be central or someone could build in mid without placing a base there ( this could lead to unfair startingpositions ).
Or just remove the aa's and power.

Btw looks like the ai was able to damage the outside placed buildings is this right?

**Comment by dragunoff** [comment] 2019-07-21 08:47
AI is able to destroy them. Player units in attack anything stance should also be able to target them.

A simple work-around here could be to move them farther away from the edge, to the right, so they fall out of range. Though I'm not  sure how AI would behave in that case.

**Comment by GraionDilach** [comment] 2019-07-21 09:00
> Though I'm not sure how AI would behave in that case.

It will try to attack them regardless and try gathering units around the closest map edge cell. The AI targeting is a bit wonky in this regard.

Can't the map be modded instead to have powerless AA guns in the middle?

**Comment by abcdefg30** [comment] 2019-07-21 11:14
Imho, if we go that far, the better solution would be to keep the AA guns as is but let the creeps player have something like a not-in-world dummy actor generating power.

**Comment by Smittytron** [comment] 2021-03-18 23:24
This was removed from the official map pool by #18617.

**Closed by Smittytron** 2021-03-18 23:24 UTC
Labels: AI, Bug, Polish
