### ISSUE TITLE
WithDeathAnimation doesn't use RenderSprites Scale setting

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#17428] opened 2019-12-06 20:33 UTC
As the title says.

Below you can see an infantry dying which has Scale: 2 under RenderSprites (like the others).

![deathanim](https://user-images.githubusercontent.com/8225171/70354482-888f1d00-1867-11ea-824c-d8573c984953.png)

**Comment by matjaeck** [comment] 2019-12-06 20:38
Duplicate of #3031.

**Closed** 2019-12-06 23:01 UTC
