### ISSUE TITLE
IntegerExpressions are slooow, causing UI lag

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#13526] opened 2017-06-17 17:29 UTC
Since cd0898236d934cfe5701b1d90a051bc5004a5348, some UI actions are noticeably sluggish, for example clicking the "Skirmish" button in the main menu, or pressing the menu button in the in-game UI, which after that commit take up to a full second, while on the immediately preceding commit they are instantaneous.

**Comment by pchote** [comment] 2017-06-27 18:07
Reproduced.  This is a major issue, so adding as a blocker.

@atlimit8: do you have enough info to start on a fix for this, or do we need more debugging?

**Comment by reaperrr** [comment] 2017-06-27 18:38
For the record, I haven't seen a noticable difference on Windows either, so maybe the issue is limited to specific Mono version(s).

**Comment by RoosterDragon** [comment] 2017-06-28 19:53
As with reaperrr, I can't say I notice any particular UI slowness on Windows.

On Windows, about half the time taken opening the Skirmish UI is spent in [compiling the expression](https://github.com/OpenRA/OpenRA/blob/cd0898236d934cfe5701b1d90a051bc5004a5348/OpenRA.Game/Support/VariableExpression.cs#L664) (for clarity - in the `System.Linq.Expressions.Expression<TDelegate>.Compile()` method specifically - generating the expression itself takes negligible time).

Maybe this is extra slow on Ubuntu for some reason? Try sticking a stopwatch around that line and see how much time it burns.

**Comment by pchote** [comment] 2017-06-28 20:19
You appear to be correct. Each `Compile()` call takes between 3ms (for integer constants like `67`) through ~14 ms for expressions with two terms and up to about 30ms for expressions with 3 terms.  Adding those up over ~600 expressions takes about 4 seconds to construct the lobby on my Ubuntu VM with mono 5.0.1.1.

**Comment by atlimit8** [comment] 2017-06-28 22:16
I created a branch that handles the compiling and MiniYaml data loading in advance otherwise on demand through *WidgetInfo. I pushed a work in progress: https://github.com/atlimit8/OpenRA/tree/WidgetInfo. I had to overhaul a lot for that redesign of the widget creation plumbing. `91 files changed, 1402 insertions(+), 903 deletions(-)`

**Comment by pchote** [comment] 2017-06-29 19:11
That appears to solve the issue (and then some!), but I think its a bit much to finish, debug, and review that before the next release.  I think our best and possibly only option here is to revert #13247 and then aim for @atlimit8's solution and reverting the revert in next + N.

We'll still pay the compilation cost on trait conditions, which sucks, but isn't a deal breaker since (a) there are a lot less of them, and (b) the delay is hidden behind a loadscreen.

**Comment by pchote** [comment] 2019-05-20 18:57
We should test this again now that we require mono >= 5.4.

**Comment by Mailaender** [comment] 2023-05-20 18:28
This problem seems to be gone with
> Runtime: Mono 6.12.0 (makepkg/6dd9def57ce Wed Apr 19 22:09:27 UTC 2023) CLR 4.0.30319.42000

**Closed** 2023-06-04 18:29 UTC
Labels: Performance, Regression, UI
