### ISSUE TITLE
Harvesters always going onto Allies Refinery if it closer.

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21395] opened 2024-04-11 11:53 UTC
Version: Bleed

https://github.com/OpenRA/OpenRA/assets/100044015/c8b576dd-ef80-470b-a44d-b0b8462ab26a

**Comment by PunkPun** [comment] 2024-04-11 11:55
duplicate of #21027

**Closed as not planned** 2024-04-11 11:55 UTC
Labels: Bug
