### ISSUE TITLE
Exiting passengers ignore map bounds

### ISSUE THREAD

**Issue by terasecond** [OpenRA/OpenRA#17053] opened 2019-09-05 21:09 UTC
Mod: Any
Version: playtest-20190825

Out of bound cells are valid exit points for unloading cargo. This issue is not present on release-20190314.

To reproduce:
1.)Fill a Cargo actor with passengers.
2.)Move this cargo actor to the edge of the map and unload the passengers.

**Comment by teinarss** [comment] 2019-09-05 21:19
Duplicate of #17006

**Closed by teinarss** 2019-09-05 21:19 UTC
