### ISSUE TITLE
Redalert and Dune crashed before I can choose Singleplayer or Multiplayer. Tib Dawn is working

### ISSUE THREAD

**Issue by thomase1993** [OpenRA/OpenRA#19434] opened 2021-05-30 12:58 UTC
## System Information

- Operating System:  archlinux
- OpenRA Version: release-20210321
- OpenRA Mod: red alert
- Source: archlinux package Version 20210321-1. 

## Exception log

no exception log under .config/openra/Logs

## Additional information
I try to start the openra-ra mod with this command. It starts and tries to load. If I use some keys after a minute, a popup appears "window is not responding". Tib Dawn is working.

If I start the game with a shell:
```
$ openra-ra
Platform is Linux
Engine version is release-20210321
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 3840x2160
No custom resolution provided, using desktop resolution
Using resolution: 3840x2160
Using window scale 1.00
OpenGL renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 21.1.1
Using default sound device
Internal mods:
	modcontent: Mod Content Manager (release-20210321)
	d2k: Dune 2000 (release-20210321)
	cnc: Tiberian Dawn (release-20210321)
	ra: Red Alert (release-20210321)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
Loading mod: ra
/usr/bin/openra-ra: line 12: 10690 Killed                  mono --debug OpenRA.exe Game.Mod=ra Engine.LaunchPath="/usr/bin/openra-ra" "${JOIN_SERVER}" "$@"
```
I'm happy to provider further information and I also have a working c# env if I should compile something.

**Comment by thomase1993** [comment] 2021-06-02 16:47
Found a error message, if I use the command `mono --debug --trace=program /usr/lib/openra/OpenRA.exe Game.Mod=ra` :

[0x7ff18a1ff640:] EXCEPTION handling: System.Net.Sockets.SocketException: Connection refused

Do you know which connection it tries to open?

I can compile bleed and run it. There isn't an error msg and I can see the server list with participants (but of course not connecting).

**Comment by abcdefg30** [comment] 2021-06-03 22:07
> Do you know which connection it tries to open?

I'd suppose one via the loopback address, even for local games:
https://github.com/OpenRA/OpenRA/blob/d10c59298787f925ebf7cec6804d210084172e81/OpenRA.Game/Game.cs#L974-L980

**Comment by pchote** [comment] 2021-06-04 00:45
https://old.reddit.com/r/openra/comments/nrmsxw/red_alert_and_dune_freezing_on_linux/ is reporting a similar issue.

Since this impacts RA and D2k but not TD it is probably related to Lua, and because the only two reports we've seen are on Arch (which uses system libraries instead of our bundled ones) it is probably an Arch packaging or library bug.

Can you please test whether the AppImages from the website show the same issue? If they work it confirms that this is an Arch issue and you will need to file an issue against https://archlinux.org/packages/community/any/openra/.

**Comment by thomase1993** [comment] 2021-06-04 10:40
The AppImage has the same issue. TD ist working but Redalert and Dune is not.

The reddit Link explains the same thing I think. I can't build the current release due to LuaValue errors (not found).

**Comment by jack82374** [comment] 2021-06-05 15:41
Author of the linked Reddit post here. I can confirm that this is the same issue and that the AppImages of Red Alert and Dune aren't working while Tiberian Dawn is.

**Comment by pchote** [comment] 2021-06-06 10:50
Does enabling the "Pause Menu Background" option in the display settings work around the problem?

**Comment by jack82374** [comment] 2021-06-06 11:18
Both games hang when loading the main menu so I can't access the settings.

**Comment by pchote** [comment] 2021-06-06 11:24
You can enable the setting in TD and then switch over to RA or D2k.

**Comment by pchote** [comment] 2021-06-06 11:34
It is also possible that this is https://gitlab.freedesktop.org/mesa/mesa/-/issues/4847. Try setting the environment variable `GALLIUM_THREAD=0` before launching OpenRA.

**Comment by thomase1993** [comment] 2021-06-06 11:43
> Does enabling the "Pause Menu Background" option in the display settings work around the problem?
> You can enable the setting in TD and then switch over to RA or D2k.

Can't find it.

![image](https://user-images.githubusercontent.com/21145632/120923106-09cda700-c6cd-11eb-8620-9a8ee4bdba13.png)

**Comment by thomase1993** [comment] 2021-06-06 11:46
`GALLIUM_THREAD=0 openra-ra ` as shell command is working for me. Thanks!

**Comment by pchote** [comment] 2021-06-06 11:48
Ok, looks like the Lua thing was a red herring after all.

Closing as there doesn't seem to be anything (aside from the `GALLIUM_THREAD` workaround) we can do on our side to work around the Mesa bug.

**Closed as not planned by pchote** 2021-06-06 11:48 UTC
Labels: Crash, Documentation, OS: Linux

**Comment by thomase1993** [comment] 2021-06-06 11:52
Ok for me. Thanks.

**Comment by jack82374** [comment] 2021-06-06 17:23
GALLIUM_THREAD=0 is also working for me. Thanks.

**Comment by sirius1242** [comment] 2021-06-07 14:55
Thanks! GALLIUM_THREAD=0 solved my and my friends' problems.

**Comment by bttger** [comment] 2022-06-19 23:00
Maybe it would be good to put some link of this issue in the installation instructions? A friend and I had the same issue today on both our laptops and it took us hours to find this issue here after reading quite a lot in several forums, reddit and other issue trackers.

Anyway, thanks for the fix. I am grateful that I finally get to play this great game again after many years.

**Comment by Mailaender** [comment] 2022-11-19 19:33
[Documented](https://github.com/OpenRA/OpenRA/wiki/FAQ/_compare/d4b453a5fd773dc7df4c52d60cb9ee5696e3ed92...3f93d4d85fa032775719fdebf13abd6716279105).
