### ISSUE TITLE
Buying air units fails while airpad has a unit docked in it (Red Alert)

### ISSUE THREAD

**Issue by amr-el-sayed** [OpenRA/OpenRA#16711] opened 2019-06-19 01:52 UTC
If you buy an air unit while a helicopter is landing in the helipad, 
it will announce unit ready but nothing happens and no unit come out.

**Comment by matjaeck** [comment] 2019-06-19 04:40
Possible duplicate of #10500.

**Comment by abcdefg30** [comment] 2019-06-19 08:07
Imho this is intentional: You can't buy a new unit if the hpad/airfield is already occupied otherwise you have two units on the same building. However, we might want to consider letting the blocking unit take off.

**Comment by MlemandPurrs** [comment] 2019-06-19 09:12
Ideally the completed unit would be put on hold until an free helipad is available, then will appear from there.

**Comment by amr-el-sayed** [comment] 2019-06-19 09:40
I don't think the unit will appear when the helipad is available. It just cut from your credit and announce  "unit ready". Please re-check it.

**Comment by amr-el-sayed** [comment] 2019-06-19 09:42
If it is intentional, then the helipad should be disabled, not allowing purchase, to avoid any confusion.

**Comment by amr-el-sayed** [comment] 2019-06-22 15:23
But it still takes the money

**Comment by Smittytron** [comment] 2021-03-18 15:12
Closing as duplicate of #10500

**Closed by Smittytron** 2021-03-18 15:12 UTC
Labels: Polish
