### ISSUE TITLE
64 bit for MacOS?????

### ISSUE THREAD

**Issue by ningwang747** [OpenRA/OpenRA#14293] opened 2017-11-05 10:09 UTC
<img width="616" alt="screen shot 2017-11-05 at 6 11 25 pm" src="https://user-images.githubusercontent.com/18260727/32413843-c733661c-c254-11e7-858a-ce37115d58b1.png">

**Comment by pchote** [comment] 2017-11-05 10:30
Closing as duplicate of #13478.

In the meantime, a 64 bit build of the current release is linked in #14178.

**Closed by pchote** 2017-11-05 10:30 UTC
