### ISSUE TITLE
Sometimes, the freezes shooting effect at Sardaukar.

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10674] opened 2016-02-01 21:46 UTC
It is happend, then sardakuar kills something.
[bandicam 2016-02-02 03-15-17-136.zip](https://github.com/OpenRA/OpenRA/files/113064/bandicam.2016-02-02.03-15-17-136.zip)

**Comment by Mailaender** [comment] 2016-02-02 18:32
Duplicate of https://github.com/OpenRA/OpenRA/issues/7131.

**Closed by Mailaender** 2016-02-02 18:32 UTC
Labels: Dune 2000, Polish

**Comment by Mailaender** [comment] 2016-02-02 18:33
or https://github.com/OpenRA/OpenRA/issues/5884.
