### ISSUE TITLE
"Player Relationship Colors" when spectating all players is useless

### ISSUE THREAD

**Issue by RoosterDragon** [OpenRA/OpenRA#21158] opened 2023-10-26 18:53 UTC
- Activate the "Player Relationship Colours" setting in the menu.
- In a replay, spectate "All Players".
- The minimap and healthbars are all the same offputting beige colour.

![image](https://github.com/OpenRA/OpenRA/assets/3399086/f4cf593c-a607-4cc7-bfae-faf7e94f7ccd)

This setting *is* useful if I spectate an individual player, the relationship colours for their team, etc, get applied. But for "All Players" having everybody appear as neutral is a bit useless. Maybe this should be special cased to use individual colours, the same as you get if the setting is off.

**Comment by PunkPun** [comment] 2023-10-26 19:13
Duplicate of #15833?

**Closed as not planned** 2023-10-27 15:13 UTC
Labels: Idea/Wishlist, Polish
