### ISSUE TITLE
Attempted to get trait from destroyed object (dog 912 (not in world))

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#7991] opened 2015-04-19 17:40 UTC
Dont know what happened, but game crashed;

Red Alert Mod at Version release-20141029
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18444
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (dog 912 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.TraitDictionary.WithInterface[T](Actor actor)
   at OpenRA.Actor.TraitsImplementing[T]()
   at OpenRA.Mods.RA.Move.MobileInfo.<GetAvailableSubCell>c__AnonStorey1.<>m__0(Actor a)
   at OpenRA.Traits.ActorMap.AnyUnitsAt(CPos a, SubCell sub, Func`2 withCondition)
   at OpenRA.Mods.RA.Move.MobileInfo.GetAvailableSubCell(World world, Actor self, CPos cell, SubCell preferredSubCell, Actor ignoreActor, CellConditions check)
   at OpenRA.Mods.RA.Move.Move.PopPath(Actor self, Mobile mobile)
   at OpenRA.Mods.RA.Move.Move.Tick(Actor self)
   at OpenRA.Traits.Util.RunActivity(Actor self, Activity act)
   at OpenRA.Mods.RA.Activities.MoveAdjacentTo.Tick(Actor self)
   at OpenRA.Traits.Util.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment] 2015-04-19 17:55
Duplicate of #6883, #7016, #7034, #7150, #7394.  This has been fixed for ages in the playtests.

**Closed by pchote** 2015-04-19 17:55 UTC
