### ISSUE TITLE
Auth code remains on clipboard when loading the game.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15604] opened 2018-09-11 23:08 UTC
Usually when I am loading OpenRA, I am also doing other stuff, like for example copying a piece of text to paste it somewhere else, and I have noticed many times that ORA overwrittes whatever I was copying with the authorization code.

**Comment by matjaeck** [comment] 2018-09-12 10:13
Duplicate of #15560.

**Closed** 2018-09-12 17:44 UTC
