### ISSUE TITLE
Silo fix

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#9156] opened 2015-08-24 20:46 UTC
The normal ore silo is currently not worth of building. I think that common sense.
pro players don't buiild them and even joke about them, cause silos don't give a significant advantage. But in my Opinion they hold great potential, in combinations with the engineers and the spies.
They should get a fix.

For example lower the ore what the refinery can stock, to make silos more needed.
The silos should get an alternativ weakpoint in my opinion. Splitting the potential of attacking the economy in two. Incomming ore (refineries + harvesters), and the ore stock (silos + refineries).

Instead of sniping a refinery it should be more worth it to snipe the silos.

**Comment by penev92** [comment] 2015-08-24 20:48
:+1:

**Comment by cjshmyr** [comment] 2015-08-24 21:49
Previous discussion at #3816.

A refinery currently stores $2000 worth of resources in both TD & RA, and players build a handful of these anyways. Some careful thought is required for adjusting capacity - a pro player constantly spends $ and might not be affected, while less experienced players are hit with a resource macro game.

It's also possible that when you've hit full resource capacity to just spend the money, and refund it to get back cash (which won't count towards capacity), which I feel would be abused if silos were actually needed. Silos might make sense if they refund the type of resource originally spent, but I think silos in all are just a flawed concept :-1:

**Comment by penev92** [comment] 2015-08-24 22:58
Closing as duplicate of #3816

**Closed by penev92** 2015-08-24 22:58 UTC
Labels: Balancing, Idea
