### ISSUE TITLE
Helicopters completely refuse to listen to commands given by the player

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16164] opened 2019-02-03 22:35 UTC
If you shift queue an action while the helicopter is on a trip to refill he is going to execute that action after refill and will not listen to any commands until he finishes that queued action

![helibug](https://user-images.githubusercontent.com/37534529/52183736-b9e82800-2813-11e9-949d-2867194dc551.gif)

I believe that this bug should be fixed by making helicopters forget all queued actions after refill

Also this bug is present in the newest [playtest](https://github.com/pchote/OpenRA/releases/tag/pkgtest-20190203) as well as in the current release

**Comment by matjaeck** [comment] 2019-02-03 22:41
Confirmed. Bug also present in release-20181215 so it is not a regression.

**Comment by reaperrr** [comment] 2019-02-03 23:02
According to @pchote not forgetting queued actions was intentional (and there was some controversy around that, which ultimately led to this decision), but not being able to abort those queued actions with move orders, for example, is definitely a bug.

**Comment by penev92** [comment] 2019-02-03 23:59
Forgetting what they are ordered to do is a serious no-no.

**Comment by FrameLimiter** [comment] 2019-02-04 03:01
Duplicate of #14094

**Comment by Punsho** [comment] 2019-02-04 05:53
Why is it a no-no? When one is controlling a big helicopter fleet some run out of ammo sooner and get their actions queued while returning, this means that if they got no more action orders after the queued ones they are going to execute them without your will. I see only one instance that queueing actions would be actually beneficial and that while the heli is reloading

**Comment by matjaeck** [comment] 2019-02-04 07:03
> Why is it a no-no?

Think you misunderstood. What penev meant was that it must not happen that you lose control over your units.

> Duplicate of #14094

**Comment by pchote** [comment] 2019-02-04 12:31
Closing as duplicate of #14094.

**Closed by pchote** 2019-02-04 12:31 UTC
Labels: Bug

**Comment by Punsho** [comment] 2019-02-04 12:40
@penev92 I'm not fully understanding what you're trying to say, automatic refill is already forced, the unit will stop attacking whatever he is told to and will go to refill that's what I call units not obeying orders. Then if it's forced I would like it also to cancel all other queued orders as well since I'm no longer controlling it, it has a mind of it's own and it's already hard to keep track of everything on screen so most of the time you either notice that your units are disobeying or you lose them
