### ISSUE TITLE
Map appears all black on the Editor.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#20252] opened 2022-09-03 08:17 UTC
I was trying to continue to update Sole Survivor since #20245 is merged. But seems like there are more issues that seems to be coming from https://github.com/OpenRA/OpenRA/pull/19599. It looks like it is rendering the Shroud on the whole map in the editor: 
![resim](https://user-images.githubusercontent.com/7933210/188262356-cf9397d5-8258-4a16-b19a-15039149101b.png)

**Comment by PunkPun** [comment] 2022-09-03 08:30
This is caused by #20245, editor worked fine before. @anvilvapre

**Comment by Smittytron** [comment] 2022-09-03 20:22
Closed by #20253

**Closed as completed by Smittytron** 2022-09-03 20:22 UTC
Labels: Bug, Regression
