### ISSUE TITLE
Cnc ingame player menu graphics glitch

### ISSUE THREAD

**Issue by WolfGaming** [OpenRA/OpenRA#7063] opened 2014-12-03 10:10 UTC
![image](https://cloud.githubusercontent.com/assets/3696546/5278731/8083b70a-7ad4-11e4-8466-f91cd77d8be9.png)

The black bar that goes over the tab number

**Comment by pchote** [comment] 2015-02-15 15:39
Closing as duplicate of #6911.

**Closed by pchote** 2015-02-15 15:39 UTC
Labels: Polish, Tiberian Dawn
