### ISSUE TITLE
Change game data and save data path

### ISSUE THREAD

**Issue by aaronfranke** [OpenRA/OpenRA#14732] opened 2018-01-15 02:03 UTC
To put it simply, the `Documents` folder, and home directory, are not ideal locations for game data.

* Windows: Move to either `%appdata%\OpenRA` (usually evaluates to `AppData\Roaming\OpenRA`) or `Documents\My Games\OpenRA`. Ensure that OpenRA supports spaces in filepaths, if the latter. 

* Linux: The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) establishes a standard for the best location to use. The rule is, if `$XDG_CONFIG_HOME` is defined, use `$XDG_CONFIG_HOME/openra`, and if it's not, use `$HOME/.config/openra`

* Mac: I'm not sure what the recommended location is. The current path may be fine.

**Comment by pchote** [comment] 2018-01-15 08:32
Closing as duplicate of #10374.

**Closed by pchote** 2018-01-15 08:32 UTC
