### ISSUE TITLE
Introduce order queue + upper limit of orders per tick for players

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8810] opened 2015-07-27 15:12 UTC
This works great for AI, so we should consider something similar for human players.

Obviously responsiveness is far more important for player-controlled units, so we'd have to set far more lenient limits (let's say 8 or 10 orders per tick), but even then we could turn massive single-tick lag spikes when huge armies are sent around into a couple of smaller spikes that don't almost halt the game for a second, only slow it down a little.

**Comment by deniz1a** [comment] 2015-07-27 15:14
Maybe related: #3923

**Comment by Unit158** [comment] 2015-07-27 19:42
I think fixing the problem with order compression and group pathing (group-move) would be better for humans. 10 orders per tick isn't very many especially when the game is lagging.

**Comment by penev92** [comment] 2015-07-27 20:33
The idea is to avoid lag. And when there is no lag, 250 orders per second sounds feasible. At least as a "temporary" solution.

**Comment by Unit158** [comment] 2015-07-28 04:19
Bad lag (see: 5+ second hangs) often isn't caused by orders. This will need some sort of dynamic solution to make sure all the player's demands are processed or not happen at all.

**Comment by RoosterDragon** [comment] 2015-07-28 18:25
For demonstration purposes, I've implemented some truly awful code that implements grouped orders. [Grouped Orders Concept Branch](https://github.com/RoosterDragon/OpenRA/tree/grouped-orders-concept)

I take a sync hash of the world state after processing orders for the whole group. This means ordering a group of *n* units around incurs 1 sync hash rather than *n*. The advantage is perf - the disadvantage is that if the grouped order causes a desync you now have multiple possible actors that could be the cause.

Here's a screenshot of the perf graph from ordering 200 rifles a short distance without the grouped orders, and an inset graph using grouped orders.

![Perf Comparison](http://i.imgur.com/ABOmJbm.png)

As you can see, you still have to pay a moderate pathfinding cost for both - but the rest of the spike in the first one is due to all the extra sync hashes being generated.

**Comment by reaperrr** [comment] 2015-07-29 16:09
Tested that concept branch, the difference is mind-boggling. In my opinion this is a must, at the very least for single-player/skirmish where sync doesn't matter.

**Comment by pchote** [comment] 2015-07-29 16:49
> single-player/skirmish where sync doesn't matter.

This still matters for replay integrity, but it can be a lot more relaxed.

**Comment by RoosterDragon** [comment] 2015-08-20 16:20
With #9022 merged, the only real bottleneck now is slow orders themselves. I'm pretty sure the only orders that cause obvious lag spikes are pathfinding.

To that end I think we may wish to close this in favour tackling pathfinding specifically, i.e. #3241.

**Closed** 2015-08-20 18:23 UTC
Labels: Idea, Performance
