### ISSUE TITLE
show admin idle time

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18502] opened 2020-08-09 16:28 UTC
every now and them 5+ people are waiting for some admin to return to his game. while the 5 leave, the next 5 join in, can go on for hours.

some way to be able to see an admin is afk (last window focus, last key press) or how long a lobby has been open, would be nice. 

auto kick feature of server is an alternative solution. i.e. someone holding up a lobby for 15+mins without starting a game.

**Comment by anjew175** [comment] 2020-08-10 03:58
duplicate of an issue you already made?
#16108

**Closed as completed** 2020-08-10 08:37 UTC
Labels: Idea/Wishlist, UI
