### ISSUE TITLE
Per-mod AUTHORS file

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#9826] opened 2015-10-31 19:06 UTC
```
[20:39:38]	<Phroh|work> pchote: Would you be against moving (or allowing a new) mod authors out to their own file? mods/ra2/AUTHORS
[20:39:55]	<pchote> not at all
[20:40:18]	<pchote> if we want to do "everything is a tab" now, we could have tabs in the credits page
[20:40:24]	<Phroh|work> Okay, cool. I'll open a ticket.
[20:40:27]	<pchote> one for openra, and one for the mod if it includes the right file 
```

**Comment by obrakmann** [comment] 2015-10-31 19:08
Duplicate of #6225.

**Closed by obrakmann** 2015-10-31 19:08 UTC
