### ISSUE TITLE
Enter cursor in ts is flickering

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16453] opened 2019-04-28 00:34 UTC
In some frames the cursor is drawn below its correct position. I didn't manage to record the flickering but am sure that some frames are displayed incorrectly.

**Comment by abcdefg30** [comment] 2019-10-03 18:07
Can you still reproduce this?

**Comment by matjaeck** [comment] 2019-10-03 18:45
I can reliably reproduce this on Linux but am not sure about Windows. I checked the animated repair wrench cursor, but this cursor does not show any issues.

**Comment by pchote** [comment] 2020-03-21 16:52
Can anybody still reproduce this after the cursor fixes that were included in release-20200202?

**Comment by tsunamistate** [comment] 2020-03-23 11:45
Cannot reproduce on git-9faf9aa1b TS mod on Windows 10
All cursors are displayed correctly

**Comment by abcdefg30** [comment] 2020-03-23 11:47
I suppose it is save to close this and wait if someone (possibly on a Linux system) encounters this issue again.

**Closed by abcdefg30** 2020-03-23 11:47 UTC
Labels: Bug, Tiberian Sun
