### ISSUE TITLE
Very bad performance.

### ISSUE THREAD

**Issue by Askmewho** [OpenRA/OpenRA#16259] opened 2019-03-03 03:18 UTC
Hi devs. Ive compile the game on rpi3 and with mesa 19 the performancee its not great at all. Fps goes from 10 to 15, sometimes a bit more... The game lloks great. I know you put a lot of effort on it.  Bu t for being such an old game you should try to improve the engine. I belive than even on emulation this game should run better, so it was a trully disappointment the performance. Hope than you focus more on performance on low end devices lkike the arm boards. The bottleneck was clearly the cpu, because the amount of fps gain getting down the resolution was minimal. Hope you all find the way to improve the engine. Best wishes.

**Comment by GraionDilach** [comment] 2019-03-03 07:47
This game is as much of an old one as Loria. There's a heckton of new features/less hardcodings/less robustness within the engine which makes comparison to the WW games pointless. Sure, it could be more efficient, but there isn't enough knowledge how fast would be ideally. It's highly probable that the Pi will never be able to run TS/RA2 on acceptable speed for starters though.

Also, AFAIK, playtest improved the situation since the release.

**Comment by IceReaper** [comment] 2019-03-03 08:18
Also: openra is NOT just an open source red alert engine! Due to the concept how this engine works, it allows you to mod the game on an extremely deep Level. This costs resources ofcourse. Example: if you want to check "do i have a tech center build?" OpenRA goes the approach of letting you mod the dependencies in your mod, which causes the game to loop through all actors, find the techcenter which is yours, which is enabled (power, ...) And tells your requirement trait that the prerequisite exists. If you would just do a red alert clone, all you need is a variable "has techcenter" and Update it whenever you get or lose a tech center. Such a hardxoded variable however will as said hardcode the game functionality. So if other games use the openra engine, they have this code too. If another game then needs a different research implementation, you have to hardcode that into the engine code too, causing you to branch away from the core engine to make it compatible. Openra is designed to be extremely modular and moddable. Its so great that i was able to build kknd on it, which uses a lot of fundamental different mechanics. So do not just think about openra as a red alert clone game code, but a completely generalized rts engine allowing (theoretically) any rts or even different game typea to be build on it. Thats the reason it costs way more resources than the original game, even in emulation. Ofcourse a lot can be optimized but thats actualy happening already. I have seen a bunch of performance commita in the last years. But there is a limit a handful of developers can do in their free time. There have to be way more developers to be able to push towards more performance faster.

**Comment by pchote** [comment] 2019-03-03 14:00
At the risk of turning this into a dogpile, i'll add my two cents here too because IMO the response can be stated much more concisely.

Don't be fooled by the graphics - OpenRA's engine works completely differently to the original RA1, and is actually much closer to Emperor: Battle for Dune or C&C Generals in the way that it is structured and works.  The tradeoff in performance may not seem worth it when looking at the Red Alert and Tiberian Dawn mods, but it means that the engine can also support projects like https://www.youtube.com/watch?v=0IXdkMb1KWs (built entirely on OpenRA) and https://www.youtube.com/watch?v=IGtrJaiUZaA (UE4 renderer talking to OpenRA's game code).

The feedback is appreciated, and performance on the RPi3 is a goal that I am slowly working towards. I'll close this as a duplicate of #12231 which is tracking the Raspberry Pi support.

**Closed by pchote** 2019-03-03 14:00 UTC
