### ISSUE TITLE
Dark text is not easy to see

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7592] opened 2015-03-05 11:28 UTC
The player name is not easy to see. Maybe there should be an outline on the text?
![473c87ea-ed5f-11e3-8d60-2591363a8885](https://cloud.githubusercontent.com/assets/7798635/6504007/a9f71946-c332-11e4-9f7c-282a11c36de9.png)
![openra game_2015_03_05_12_26_57_381](https://cloud.githubusercontent.com/assets/7798635/6504055/507d0b72-c333-11e4-957a-ee09285d032a.png)
![openra game_2015_06_22_19_05_28_666](https://cloud.githubusercontent.com/assets/7798635/8309096/c74e1dd6-19c8-11e5-91d7-d163bef1b514.png)

Also see  #5563

**Comment by Snurre86** [comment] 2015-03-06 18:32
Hard to see the atom bomb and time text.
![openra game_2015_03_06_19_29_14_910](https://cloud.githubusercontent.com/assets/7798635/6531183/8082e530-c437-11e4-95fe-ee99f12d0fd1.png)

**Comment by penev92** [comment] 2015-03-06 18:49
That last one is because your screen is too big :D

**Comment by Phrohdoh** [comment] 2015-03-06 18:55
@penev92 No it isn't.

**Comment by Snurre86** [comment] 2015-03-06 18:57
Just outline the text
![post-7619-white-text-with-black-outline-v4dl](https://cloud.githubusercontent.com/assets/7798635/6531633/ea3b50a4-c43a-11e4-9f1f-ab23eb8a19be.png)

**Comment by Phrohdoh** [comment] 2015-03-06 18:57
@Snurre86 The text is outlined.

The problem is dark colors on a dark background.

**Comment by Snurre86** [comment] 2015-03-06 18:59
or bright color on bright background.

**Comment by penev92** [comment] 2015-03-06 18:59
I don't know, I have no problems with the timer.
The player names really could use an outline.

**Comment by Snurre86** [comment] 2015-03-06 19:02
but you can't outline with a dark color on a dark color that is stupid.

**Comment by Phrohdoh** [comment] 2015-03-06 19:03
You can outline it with a brighter color.

**Comment by penev92** [comment] 2015-03-06 19:03
You don't really care about the background. You only need to use a color for the outline that contrasts well with the color of the text.

**Comment by Snurre86** [comment] 2015-03-06 19:04
you got it penev. like it does now with the color being to similar to the terrain.

**Comment by pchote** [comment] 2015-03-06 23:08
This is a known long-standing limitation, so thanks for creating a ticket. The planned fix has always been to give "dark" (by an appropriate metric) text a white border instead of black.

**Comment by SMIFFGIG** [comment] 2015-08-13 00:33
Perhaps the SW icons shown in the top left should be x2 size? (would have to be remade)

**Comment by Snurre86** [comment] 2016-01-10 14:15
Maybe there could be added a background? I know it will look ugly and would not be transparent but at least you can read it.

**Comment by GraionDilach** [comment] 2016-07-19 11:22
#11647 fixed this, requesting for closing.

**Comment by pchote** [comment] 2016-07-19 12:06
Adding to milestone because it's silly to fix one case and not the others when the fix is so simple.

**Closed** 2016-09-02 19:24 UTC
Labels: Polish, UI

**Comment by Snurre86** [comment] 2016-11-22 05:15
I am not satisfied with the result, it is better but way too hard to read.
![openra game_2016_11_22_06_11_04_530](https://cloud.githubusercontent.com/assets/7798635/20511705/c3d50670-b07a-11e6-9187-512ab58d89cf.png)
![openra game_2016_11_22_06_14_20_788](https://cloud.githubusercontent.com/assets/7798635/20511742/f6a86376-b07a-11e6-831f-fee46b804488.png)

**Comment by Snurre86** [comment] 2016-11-22 06:47
The player color as background.
![openra game_2016_11_22_06_11_04_530](https://cloud.githubusercontent.com/assets/7798635/20513664/c2dd6de0-b087-11e6-9ddd-ee9f47a56ba1.png)
