### ISSUE TITLE
Riflemen are unable to harm veteran heavy armor

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12983] opened 2017-03-17 23:40 UTC
Here you can see the riflemen and the light tank shoot itself without taking damage but the flame tower can still damage it.

Also the physics of how the light tank can shoot itself is a mystery to me. 

https://youtu.be/LvbI7BsszAM

**Comment by FrameLimiter** [comment] 2017-03-17 23:59
Confirmed: Rifles are unable to harm veteran vehicles...again.

-The tank being able to shoot itself has been around forever. A long time ago they used to do damage to themselves so you could suicide the units :D

**Comment by Snurre86** [comment] 2017-03-18 00:47
do we close the issue? is the tank suppose to shoot itself or is there a copy of it?

**Comment by FrameLimiter** [comment] 2017-03-18 01:04
The veteran tanks not taking damage is an issue that needs to be fixed. Leave it open.

**Comment by atlimit8** [comment] 2017-03-18 03:40
The riflemen's inability to damage is probably caused by rounding down to 0 by the `DamageMultiplier` enabled by the veterancy status. Scaling up all of the damage values is probably the best way to fix this. Health is stored as an integer - whole numbers only.

**Comment by GraionDilach** [comment] 2017-03-18 11:11
Duplicate of #11425.

@atlimit8 See #11719 which is your suggestion as an actual ticket and the made-up rejection reasons in #11852 - I still have no idea what precision issue @pchote talked there.

**Comment by abcdefg30** [comment] 2017-03-18 15:54
Closing as duplicate.

**Closed by abcdefg30** 2017-03-18 15:54 UTC
Labels: Bug
