### ISSUE TITLE
Make "Demolition:" trait conditional.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12604] opened 2017-01-22 12:46 UTC
I actually need `Infiltrates:` to be upgradable, but those tags are related and neither are Upgradable, so i think if one can be made upgradable, all can be.

I'm trying to make Spies built from a seperate structure which is available at start (like kennel) and get infiltartion ability only if player has Radar Dome for my modmaps.

**Comment by MustaphaTR** [comment] 2017-02-02 09:56
I tried to make `Infiltrates:` upgradeable at https://github.com/MustaphaTR/OpenRA/tree/ra-make-infiltrates-upgradeable . But has a small problem, when Trait gets disabled after target has set, infiltaror unit doesn't stop. Currently it enters the building but nothing happens.

**Comment by GraionDilach** [comment] 2017-02-02 15:14
You have to add any of the following two to the Infiltrates activity class:
```
public override Activity Tick(Actor self)
{
if (self.Trait<Infiltrates>().IsTraitDisabled)
	return nextActivity;

return base.Tick(self);
}

OR

public override Activity Tick(Actor self)
{
	if (IsCanceled || !self.Trait<Infiltrates>().IsTraitDisabled)
		return CanceledTick(self);

	// Check target validity if not exiting or done
	if (nextState != EnterState.Done && (target.Type != TargetType.Actor || !target.IsValidFor(self)))
		AbortOrExit(self);

	// If no current activity, tick next activity
	if (inner == null && FindAndTransitionToNextState(self) == EnterState.Done)
		return CanceledTick(self);

	// Run inner activity/InsideTick
	inner = inner == this ? InsideTick(self) : ActivityUtils.RunActivity(self, inner);

	// If we are finished, move on to next activity
	if (inner == null && nextState == EnterState.Done)
		return NextActivity;

	return this;
}
```

The former violates the aim of explicit-interface everything in OpenRA though even if it looks much more easier than c'n'ping everything OpenRA.Mods.Common/Activities/Enter.Tick has and then edit that.

**Comment by MustaphaTR** [comment] 2017-02-03 06:18
I got the first one work. Unit simply freezes until a new order is given instead of going idle but i don't see this as a big problem.

I couldn't get the last one work so i don't know how it would effect that.

**Comment by MustaphaTR** [comment] 2017-03-04 10:47
As https://github.com/OpenRA/OpenRA/issues/12681 is now merged, Infiltates is now upgradeable. Captures and Demolition still needs to be made upgradeable imo, but don't have a prirority unless someone comes with a use case that they need.

**Comment by PunkPun** [comment] 2022-07-07 18:06
This issue should be renamed as both Infiltrates and Captures are now conditional

**Comment by PunkPun** [comment] 2022-10-01 19:52
closing as a reverse duplicate of #15265

**Closed by PunkPun** 2022-10-01 19:52 UTC
Labels: Feature
