### ISSUE TITLE
OpenRA does not consider turning on the spot a movement

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13346] opened 2017-05-24 21:15 UTC
In original TS, mechs played their walking anim even when turning on the spot (which makes sense), in OpenRA they don't.

**Comment by obrakmann** [comment] 2017-05-30 15:48
That should be pretty easy to fix. Just set `Mobile.IsMoving` to true in `Turn.OnFirstRun` and reset it to the previous value (not blindly to false) in `Turn.OnLastRun`.

**Comment by reaperrr** [comment] 2017-06-15 21:08
That regresses things when infantry turns to face a new target, for example.

Maybe it would be better to add a `ConsiderTurnOnSpotAsMoving` property and a `facing.Facing != oldFacing` check to `WithMoveAnimation` instead, like what `WithVoxelWalkerBody` already does. I'm wary of dabbling in the activities themselves.

**Comment by pchote** [comment] 2018-04-29 21:10
Duplicate of #11885?

**Comment by reaperrr** [comment] 2018-06-01 01:31
> Duplicate of #11885?

No. #11885 is about that visible 1-tick stop at the end of an L-turn transitioning to straight movement. This issue is about (optionally) considering the Turn activity as IMove.IsMoving. L-turns don't use the Turn activity, so these are separate issues.

**Closed** 2018-07-19 20:09 UTC
Labels: Polish, Tiberian Sun
