### ISSUE TITLE
Add support for 'borderless' windowed mode

### ISSUE THREAD

**Issue by NinovanderMark** [OpenRA/OpenRA#9052] opened 2015-08-12 20:27 UTC
Add a menu option that removes window decorations and places the window at 0,0 on the main monitor.
##

**Comment by Aaron-Lloyd** [comment] 2015-08-14 15:02
This would be great to have.

**Comment by Smittytron** [comment] 2021-03-17 18:44
Closing as reverse duplicate of #15056

**Closed by Smittytron** 2021-03-17 18:44 UTC
Labels: Feature, UI
