### ISSUE TITLE
Any idea what this is?

### ISSUE THREAD

**Issue by PredatorFett** [OpenRA/OpenRA#13663] opened 2017-07-19 21:01 UTC
![untitled](https://user-images.githubusercontent.com/30301505/28389184-b50d3270-6c9a-11e7-87b4-d5dc4b314f7c.jpg)

Here's my specs: 
[DxDiag.txt](https://github.com/OpenRA/OpenRA/files/1160456/DxDiag.txt)

And my graphics card info: 
[NVIDIA System Information 07-19-2017 16-00-21.txt](https://github.com/OpenRA/OpenRA/files/1160459/NVIDIA.System.Information.07-19-2017.16-00-21.txt)

**Comment by ltem** [comment] 2017-07-19 21:18
Seems to be a duplicate of #13034.

He mentions that it works perfectly fine in windowed mode. Does that work for you as well?

**Comment by abcdefg30** [comment] 2017-07-19 21:25
Hm, your report says `Driver version: 344.24`. I got `384.76`, but am on Windows 10. Are there any driver updates for your card available? (P.S. thanks for providing such a detailed report. ^^)

**Comment by PredatorFett** [comment] 2017-07-20 16:33
Item: I can try that right now, and I'll get back to you on it
abcdefg30: You're welcome, but I checked for some updates to no avail, however, I uninstalled all traces of the game, reinstalled, and it works fine now. Don't understand what went wrong tbh.

**Comment by abcdefg30** [comment] 2017-07-20 21:32
Hm, ok. Good if it works now though. :D

**Closed by abcdefg30** 2017-07-20 21:32 UTC
Labels: Bug, OS: Windows
