### ISSUE TITLE
German localized TFD disc support

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#9082] opened 2015-08-16 02:18 UTC
List of German CabFileIDs for all Mods

```
Cabinet: data1.hdr

File group: Tiberian Sun
MAPS01.MIX - 452
MAPS02.MIX - 453
MOVIES01.MIX - 455
MOVIES02.MIX - 456
SCORES.MIX - 464
TIBSUN.MIX - 473
e01scd01.mix - 483
e01scd02.mix - 484
expand01.mix - 485
gmenu.mix - 504
multi.mix - 506
patch.mix - 507
scores01.mix - 508
wdt.mix - 509
wdtvox.mix - 510

File group: Red Alert
EXPAND.MIX - 232
EXPAND2.MIX - 233
HIRES1.MIX - 235
LORES1.MIX - 238
REDALERT.MIX - 251
main.mix - 257

 File group: CnC
AUD.MIX - 39
CCLOCAL.MIX - 42
CONQUER.MIX - 45
DESEICNH.MIX - 46
DESERT.MIX - 47
GENERAL.MIX - 48
LOCAL.MIX - 49
SC-000.MIX - 53
SC-001.MIX - 54
SCORES.MIX - 55
SOUNDS.MIX - 56
SPEECH.MIX - 57
TEMPERAT.MIX - 58
TEMPICNH.MIX - 59
TRANSIT.MIX - 62
UPDATE.MIX - 63
UPDATEC.MIX - 64
WINTER.MIX - 66
WINTICNH.MIX - 67
covert\AUD.MIX - 215
covert\CONQUER.MIX - 216
covert\DESERT.MIX - 217
covert\GENERAL.MIX - 218
covert\MOVIES.MIX - 221
covert\SCORES.MIX - 225
covert\SOUNDS.MIX - 226
covert\TEMPERAT.MIX - 227
covert\WINTER.MIX - 228

File group: Red Alert 2
language.mix - 610
maps01.mix - 613
maps02.mix - 614
movies01.mix - 615
movies02.mix - 616
multi.mix - 618
ra2.mix - 623
theme.mix - 628
wdt.mix - 629

File group: Yury
expandmd01.mix - 737
langmd.mix - 739
mapsmd03.mix - 742
movmd03.mix - 743
multimd.mix - 745
ra2md.mix - 749
thememd.mix - 751

```

**Comment by LipkeGu** [comment] 2015-08-16 02:27
To get the IDs you have to Change the line https://github.com/twogood/unshield/blob/master/src/unshield.c#L524

to:

```
printf(" %8" SIZE_FORMAT "  %s%s - %d\n",
          unshield_file_size(unshield, i),
          dirname,
          unshield_file_name(unshield, i),i);
```

and list the files in the hdr file...

**Comment by Unit158** [comment] 2015-08-16 02:41
Why is this an issue? Can you please move this [to the wiki](https://github.com/OpenRA/OpenRA/wiki/List-of-German-CabFileIDs)

**Comment by penev92** [comment] 2015-08-16 06:22
I think the idea is you can't install from TFD DVD right now, unless you have the English version.

**Comment by GraionDilach** [comment] 2015-08-16 10:19
The problem is that the German localized versions differ in files as well (blood to oil etc) so I'm not really certain if supporting the German TFD would not lead to file errors in the long run caused by the German censorship.

**Comment by LipkeGu** [comment] 2015-08-16 11:10
thats we cant use german DVDs is right but they work, you can grab a german DVD and change de mod.yaml from TS to

```
InstallShieldCABFilePackageIds: 473:CRC32
InstallShieldCABFileIds: 464, 473
```

and the content will be copied nicely from the disk... 

we could check the DISK labels on german it is "DE10J" but i dont know how they are labeled in US

**Comment by LipkeGu** [comment] 2015-08-16 14:52
I forgot to add Filegroup "Yury" ... so i added them to the List...

**Comment by pchote** [comment] 2015-08-16 15:35
> The problem is that the German localized versions differ in files as well (blood to oil etc) so I'm not really certain if supporting the German TFD would not lead to file errors in the long run caused by the German censorship.

This is an important point, which I had also raised in one of the other threads about this.  It is a bad idea to start supporting non-english installation media until after we have proper translation support (including downloadable language asset packs).

**Comment by GraionDilach** [comment] 2015-08-16 22:40
@LipkeGu: comparing the mixes is one thing, comparing their `content` is a different story.

There are already issues with the plenty variants (RA 2.00 vs RA 3.03 or pchote not having the intro song of RA1 at first...)

I know that EA butchered out a mission from German Generals, even if the bigs are supposed to be the same - and unfortunately I don't know the exact differences in the WW games. Howevet it is a risk that files got omitted in their cases as well, which can't be tested reliably.

**Comment by LipkeGu** [comment] 2015-08-16 23:27
But this problem does exists since the abilty of CD installation i can use german Tiberian SUn CDs or Red Alert 1 CDs (legacy) and the problem is the same since years.

**Comment by Unit158** [comment] 2015-08-17 00:40
It looks like the general consensus around this topic is "yes we want it, but not right now."

**Comment by Mailaender** [comment] 2015-08-17 05:51
This is independent from https://github.com/OpenRA/OpenRA/issues/8968. Those localized assets are binary compatible. Lot's of people are already playing with those. I just usually don't post the videos from YouTube in our social media channels as the commentary is often also in German.

**Comment by Mailaender** [comment] 2016-09-05 04:51
Have a look at the new https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/installer You will need to expand those entries. The metadata can be read with the following `OpenRA.Utility.exe` formats.

```
  --list-installshield ARCHIVE.Z
  Lists the content ranges for a InstallShield V3 file

  --list-installshield-cab DATA.HDR
  Lists the filenames contained within an Installshield CAB volume set

  --list-mix ARCHIVE.MIX
  Lists the content ranges for a mix file

  --list-mscab ARCHIVE.CAB
  Lists the filenames contained within a MSCAB file
```

**Comment by abcdefg30** [comment] 2023-06-09 14:50
Closing as covered by #10475 which has a bullet point about loading non-english assets.

**Closed by abcdefg30** 2023-06-09 14:50 UTC
Labels: Feature
