### ISSUE TITLE
32-bit PNG spritesheets support for tiles and actors

### ISSUE THREAD

**Issue by katzsmile** [OpenRA/OpenRA#14498] opened 2017-12-12 07:58 UTC
Can we have 32-bit PNG spritesheets support for tiles and actors?

like this example from Factorio game:
[car.zip](https://github.com/OpenRA/OpenRA/files/1550687/car.zip)

**Comment by Mailaender** [comment] 2017-12-12 09:31
Duplicate of https://github.com/OpenRA/OpenRA/issues/5589

**Closed by Mailaender** 2017-12-12 09:31 UTC

**Comment by katzsmile** [comment] 2017-12-12 09:58
duplicate issue is dated back to 2014, we still need it, 256 bit limitation for sprites in 2017-2018 is a bit eww

**Comment by Mailaender** [comment] 2017-12-12 10:35
Please continue the discussion at #5589 or add a +1 there to voice your support/wish.
