### ISSUE TITLE
Give descriptions to AI types.

### ISSUE THREAD

**Issue by MikillRosen** [OpenRA/OpenRA#20554] opened 2022-12-15 21:41 UTC
OpenRA needs descriptions for its AI players, especially the ones with vague names like "Watson", "Gladius" etc.

**Comment by pchote** [comment] 2022-12-20 00:28
Those names are intentional specifically *because* the differences between them are vague. They have different play styles which are not necessarily any harder or easier than others.

**Comment by MikillRosen** [comment] 2022-12-20 01:06
No offense, but that sounds stupid. Why do we have to figure out what the AI types do unlike in RA?

**Comment by abcdefg30** [comment] 2022-12-20 20:29
It's rather that RAs types are the odd one out, the difference between those AIs is "vague" as well.

**Comment by Mailaender** [comment] 2022-12-22 19:33
Duplicate of https://github.com/OpenRA/OpenRA/issues/16126

**Closed as not planned by Mailaender** 2022-12-22 19:33 UTC
Labels: Idea/Wishlist
