### ISSUE TITLE
defend mode problems.

### ISSUE THREAD

**Issue by vipches** [OpenRA/OpenRA#10115] opened 2015-11-26 12:56 UTC
So, I know on the new version, the unit was normally on a defend mode, so that was good to let them not to chaseing enemy away, but there is problem, some time they will stay on postition and don't attack the enemy that was on range, and will take damage till died, I have this situation a lot time, once my rocket soldier with the rifleman was attacking the enemy tanks, and the soldier on behind suddenly stanting there doing nothing but takeing hit and died, before they died, I was check they moveing line, which it's still on a red attacking line, but still standing there not fight back, this was a really big problems, especially when you control a huge group on battle, most of them just stay behind getting shot at... each game has a same problems.

**Comment by GraionDilach** [comment] 2015-11-26 13:02
Duplicate of #5841.

**Closed** 2015-11-26 19:47 UTC
