### ISSUE TITLE
AI defenses don't stop tracking units even if InitialStanceAI is set to Defend

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9837] opened 2015-10-31 21:54 UTC
They do switch once a new target comes into range, but as long as that doesn't happen, AI turrets continue to track a target even if it's out of range.

**Comment by obrakmann** [comment] 2015-10-31 21:58
Probably a duplicate of #6185?

**Comment by penev92** [comment] 2015-10-31 22:28
Yes, turreted structures and units alike have this damn "oh I saw you once, now I'm going to track you even though I'm just sitting here and you're moving to the other side of the map" thing.

**Closed** 2016-02-18 16:02 UTC
Labels: AI, Bug
