### ISSUE TITLE
Tooltip issue in server list when a player name is "empty"

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16389] opened 2019-04-07 00:19 UTC
### Issue Summary

You can see a list of the players connected to a server when you put your cursor over that server.

When a player name is "empty" (can't find what character it is) the tooltip has an issue :

![OpenRA-2019-04-07T000703055Z](https://user-images.githubusercontent.com/49353682/55676741-f18a5380-58da-11e9-90ed-bd4682912fcd.png)

When this player and his friend started the game the tooltip became

![OpenRA-2019-04-07T000757327Z](https://user-images.githubusercontent.com/49353682/55676743-07981400-58db-11e9-8d6f-c0dba5ffd3f2.png)

#### System Information

- Operating System : Windows 10
- .Net Version : 4.7.2
- OpenRA Version : release-20190304
- Mod : Red Alert

**Comment by matjaeck** [comment] 2019-04-07 09:41
We should consider to do some basic validation on values entered in the settings.yaml that are used for usernames. New players could get a wrong impression if they see someone with a "hacker" username. Not completely sure though, because it doesn't harm anyone and some users have created really nice looking nicknames by using a custom font or other tricks.

**Comment by deleted-user-1** [comment] 2020-08-15 20:30
Reverse duplicate of #17884

**Closed** 2020-08-16 10:39 UTC
Labels: Polish, UI
