### ISSUE TITLE
OpenRA - Red Alert Randomly Crashing 

### ISSUE THREAD

**Issue by Baknamy** [OpenRA/OpenRA#14290] opened 2017-11-04 16:47 UTC
Hello! I've been having an issue where the OpenRA - Red alert is crashing randomly. On this issue, I haven't found any information. So I've decided to write here, for your help. Before that, I've went through all the allied and soviet missions in singleplayer. And all was good. After that, I've wanted to play in remaining missions in a single player such as Exodus, Intervention and game start crashing. More of it, a simple game in a skirmish is also crashing. Is it possible to do anything with this? Thanks. And sorry for English it's not my native language.

OpenRA engine version release-20171014
[debug.log](https://github.com/OpenRA/OpenRA/files/1443369/debug.log)
[exception-2017-10-29T160149Z.log](https://github.com/OpenRA/OpenRA/files/1443370/exception-2017-10-29T160149Z.log)
[exception-2017-10-30T191924Z.log](https://github.com/OpenRA/OpenRA/files/1443371/exception-2017-10-30T191924Z.log)
[exception-2017-10-30T193519Z.log](https://github.com/OpenRA/OpenRA/files/1443372/exception-2017-10-30T193519Z.log)
[exception-2017-11-01T154227Z.log](https://github.com/OpenRA/OpenRA/files/1443373/exception-2017-11-01T154227Z.log)
[exception-2017-11-03T155841Z.log](https://github.com/OpenRA/OpenRA/files/1443374/exception-2017-11-03T155841Z.log)

**Comment by abcdefg30** [comment] 2017-11-04 16:52
Looks like you are missing some of the expansion sound files. Sounds like https://github.com/OpenRA/OpenRA/issues/12420#issuecomment-262778529 and like you have to install the assets from another source (e.g. the download, or from [here](https://github.com/OpenRA/OpenRA/issues/12420#issuecomment-262632380)).

**Comment by MustaphaTR** [comment] 2017-11-04 16:52
Those are Aftermath sound files. Duplicate of #12420, i guess.

Try reinstalling game files from a different source.

**Comment by Baknamy** [comment] 2017-11-04 17:23
Thanks for the quick reply. Tried to install [this ](https://github.com/OpenRA/OpenRA/issues/12420#issuecomment-262632380)file, they really differ but without success. See attachment. I will try to completely re-install the RA content from another source.
[exception-2017-11-04T170531Z.log](https://github.com/OpenRA/OpenRA/files/1443414/exception-2017-11-04T170531Z.log)

**Comment by reaperrr** [comment] 2017-11-06 17:21
The first list is actually the voices and sounds from The Aftermath.

> It is interesting that the music file await.aud from
The Athermath, the full name "Afterlife (await)" is the same as in the Base Game Music.

Await isn't an Aftermath track.

> in the list of Counterstrike music, there is a track called "Radio 2 Remix" but I do not have it. Nobody knows why?

That remix was an audio-CD-exclusive track, it's not available in-game. It can be found on both the CS and Aftermath CDs as track 02, you can play it on any CD player (track 01 is game data, tracks 03-06 are CD quality versions of Chaos2, Shut It, VR2 and Backstab).

**Comment by abcdefg30** [comment] 2017-11-08 17:23
Good to hear the issue is resolved.

**Closed by abcdefg30** 2017-11-08 17:23 UTC
Labels: Crash
