### ISSUE TITLE
Memory leak OpenRA

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13415] opened 2017-06-01 09:38 UTC
Hey guys I have a 6GB ram system, it seems that OpenRa is just inflating till it runs out of memory. This happens both in the mainscreen and during play:

```
Red Alert Mod at Version release-20170421
on map aae0ea0b52e1b2050f1ebe608c70813f5c608063 (Desert Shellmap by Scott_NZ).
Date: 2017-05-31 06:58:18Z
Operating System: OSX (Unix 16.5.0.0)
Runtime Version: Mono 4.8.0 (mono-4.8.0-branch/9d74414) CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Out of memory
GC Memory (post-collect)=1,265,223,056
GC Memory (pre-collect)=1,973,597,976
Working Set=2,115,325,952
Private Memory=2,115,330,048
Virtual Memory=3,380,146,176
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at System.Collections.Generic.List`1[T].set_Capacity (System.Int32 value) [0x0002a] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:123 
  at System.Collections.Generic.List`1[T].EnsureCapacity (System.Int32 min) [0x00046] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:419 
  at System.Collections.Generic.List`1[T].Add (T item) [0x00013] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:228 
  at OpenRA.Network.SyncReport.GenerateSyncReport (OpenRA.Network.SyncReport+Report report) [0x001d3] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Network.SyncReport.UpdateSyncReport () [0x00001] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Network.OrderManager.Tick () [0x000e4] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001fd] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Game.Loop () [0x000d6] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Game.Run () [0x00042] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <2d2eafa0e2154496ab7cc059c50a1b74>:0 
```

```
Red Alert Mod at Version release-20170527
on map ab1e2a5cc55feaf6d2734b39d58d4751ca728872 (God's Great Divide Fixed - Non-Faction by Vigor, God, Stex, AMHOLE).
Date: 2017-06-01 06:54:11Z
Operating System: OSX (Unix 16.5.0.0)
Runtime Version: Mono 4.8.0 (mono-4.8.0-branch/9d74414) CLR 4.0.30319.42000
Exception of type `System.OutOfMemoryException`: Out of memory
GC Memory (post-collect)=499,380,584
GC Memory (pre-collect)=962,014,120
Working Set=921,563,136
Private Memory=921,563,136
Virtual Memory=2,156,314,624
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x00063] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:2589 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:856 
  at OpenRA.Mods.Common.Traits.AffectsShroud.ProjectedCells (OpenRA.Actor self) [0x000e3] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at OpenRA.Mods.Common.Traits.AffectsShroud.OpenRA.Traits.ITick.Tick (OpenRA.Actor self) [0x0009a] in <fdc1a2308ba047f88b49109de7f2737a>:0 
  at OpenRA.World.<Tick>m__3 (OpenRA.TraitPair`1[T] x) [0x00000] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at (wrapper delegate-invoke) System.Action`1[OpenRA.TraitPair`1[OpenRA.Traits.ITick]]:invoke_void_T (OpenRA.TraitPair`1<OpenRA.Traits.ITick>)
  at OpenRA.WorldUtils.DoTimed[T] (System.Collections.Generic.IEnumerable`1[T] e, System.Action`1[T] a, System.String text) [0x00022] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.World.Tick () [0x00100] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0021a] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.Loop () [0x000d6] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Game.Run () [0x00042] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in <a32af65b47eb431c9a06ff1bce40d751>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <a32af65b47eb431c9a06ff1bce40d751>:0 
```

**Comment by GraionDilach** [comment] 2017-06-01 10:55
Duplicate of #12494.

**Closed** 2017-06-03 08:49 UTC
Labels: Crash
