### ISSUE TITLE
We should be allowed to choose default stances, not have them forced upon us, breaking varying styles of gameplay

### ISSUE THREAD

**Issue by SmittyShitDevs** [OpenRA/OpenRA#14194] opened 2017-10-16 23:46 UTC
This should be self explanatory. While it may seem beneficial to you, it is not to other players. Having stances forced upon us, makes players have to break habits and learn new ones, which is unnecessary and annoying. And, it breaks players varying play styles. Yes, we could eventually learn to work around that, but why should we? "If it isn't broken, don't fix it." It adds more unneeded clicks to everything and wastes micro manage time.

**Comment by FRenzy-OpenRA** [comment] 2017-10-17 06:54
Could be a new panel under (Settings > 'Stances'), where individual units' stance would be customized.

**Comment by abcdefg30** [comment] 2017-10-17 09:06
Also see #13817.

**Comment by netnazgul** [comment] 2017-10-17 13:13
@abcdefg30 this is probably a duplicate of #13817, not "also see" ;)

**Comment by pchote** [comment] 2017-10-17 13:22
Indeed. Closing as duplicate.

**Closed by pchote** 2017-10-17 13:22 UTC
Labels: Idea/Wishlist
