### ISSUE TITLE
RA2 ChronoShift sounds are not parsed correctly

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10540] opened 2016-01-17 17:01 UTC
> schrlo1.wav, schrlo2a.wav schrlo2b.wav, schrlo2c.wav, schrlo3.wav

results in

```
Failed to parse WAV file schrlo1.wav. Error message:
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
  at OpenRA.StreamExts.ReadBytes (System.IO.Stream s, System.Byte[] buffer, Int32 offset, Int32 count) [0x0002e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/StreamExts.cs:37 
  at OpenRA.StreamExts.ReadBytes (System.IO.Stream s, Int32 count) [0x00023] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/StreamExts.cs:25 
  at OpenRA.FileFormats.WavLoader.LoadSound (System.IO.Stream s) [0x001bf] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/FileFormats/WavLoader.cs:82 
  at OpenRA.FileFormats.WavLoader.TryParseSound (System.IO.Stream stream, System.String fileName, System.Byte[]& rawData, System.Int32& channels, System.Int32& sampleBits, System.Int32& sampleRate) [0x0001e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/FileFormats/WavLoader.cs:189 
```

![image](https://cloud.githubusercontent.com/assets/756669/12378623/2cb54ae0-bd44-11e5-83df-3e97fc0ac443.png)

![image](https://cloud.githubusercontent.com/assets/756669/12378627/41594884-bd44-11e5-87ee-7649413ae6a1.png)

`FmtChunkSize` is 16 on these files while all the others have 20.
##

**Comment by Apollo-X** [comment] 2016-01-26 16:25
This is some kinda process to build wav header for audio.bag files of RA2? Either way that fmt size looks out of spec for wav.

**Comment by MustaphaTR** [comment] 2019-05-06 08:32
I would close this as a reverse duplicate of https://github.com/OpenRA/OpenRA/issues/15994 that one is more generic.

**Closed by MustaphaTR** 2019-05-06 08:32 UTC
Labels: Audio, Crash
