### ISSUE TITLE
Wayland doesn't work

### ISSUE THREAD

**Issue by Korothi** [OpenRA/OpenRA#20451] opened 2022-11-11 21:28 UTC
It crashes with forced wayland
SDL_VIDEODRIVER=wayland
same happens with openHV
tried with intel igpu.
Arch Linux using sdl2 2.24.2-1 2022-11-03 
[message.txt](https://github.com/OpenRA/OpenRA/files/9993300/message.txt)

**Comment by PunkPun** [comment] 2022-11-11 21:33
Duplicate of #20014

**Closed as not planned** 2022-11-11 22:01 UTC
Labels: Crash, OS: Linux

**Comment by Mailaender** [comment] 2022-11-16 20:44
Can you check if this patch works for you?

```diff
 OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj | 2 +-
 OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj     | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj b/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
index 6c24b8dd43..49582560fa 100644
--- a/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
+++ b/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
@@ -3,7 +3,7 @@
     <ProjectReference Include="..\OpenRA.Game\OpenRA.Game.csproj" />
     <PackageReference Include="OpenRA-Freetype6" Version="1.0.4" />
     <PackageReference Include="OpenRA-OpenAL-CS" Version="1.0.16" />
-    <PackageReference Include="OpenRA-SDL2-CS" Version="1.0.31" />
+    <PackageReference Include="OpenRA-SDL2-CS" Version="1.0.33" />
   </ItemGroup>
   <ItemGroup>
     <Content Include="OpenRA.Platforms.Default.dll.config" Condition="'$(TargetPlatform)' != 'win-x64' And '$(TargetPlatform)' != 'win-x86'">
diff --git a/OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj b/OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
index c52492d025..a1bc3e9038 100644
--- a/OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
+++ b/OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
@@ -21,7 +21,7 @@
     </AssemblyAttribute>
   </ItemGroup>
   <ItemGroup>
-    <PackageReference Include="OpenRA-SDL2-CS" Version="1.0.31" />
+    <PackageReference Include="OpenRA-SDL2-CS" Version="1.0.33" />
   </ItemGroup>
   <ItemGroup>
     <ProjectReference Include="..\OpenRA.Game\OpenRA.Game.csproj" />
```

It doesn't for me, but maybe my system just doesn't support Wayland.

**Comment by Korothi** [comment] 2022-11-16 20:51
It works if i replace sdl .so file to latest one from my usr/lib (or lib64)

śr., 16 lis 2022, 21:45 użytkownik Matthias Mailänder <
***@***.***> napisał:

**Comment by Mailaender** [comment] 2022-11-16 21:21
That is not what I mean. Try updating the project files as indicated above and then https://github.com/OpenRA/OpenRA/wiki/Compiling#linuxmac
