### ISSUE TITLE
Dune 2000 multiplayer crash

### ISSUE THREAD

**Issue by alvra** [OpenRA/OpenRA#17500] opened 2019-12-23 12:42 UTC
### Issue Summary
Crash during a multiplayer game. Not sure exactly what caused it, but both participants got the same error in the log.

#### System Information
- **Operating System:** Linux Debian 8 and Windows 10
- **.NET / Mono Version:** ?
- **OpenRA Version:** release-20191117
- **Mod:** Dune2000

#### Additional Information:
- Steps to reproduce
unknown

- Logs
[attached](https://github.com/OpenRA/OpenRA/files/3994969/dune_crash.log)

- OpenRA Replays
[attached](https://github.com/OpenRA/OpenRA/files/3994967/OpenRA-2019-12-23T113735Z.orarep.zip), the crash happens at the end

**Comment by reaperrr** [comment] 2019-12-23 14:08
```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (harvester 851 (not in world))
  at OpenRA.TraitDictionary.CheckDestroyed (OpenRA.Actor actor) [0x0001c] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.TraitDictionary.Get[T] (OpenRA.Actor actor) [0x00000] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Actor.Trait[T] () [0x00000] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Mods.Common.Activities.PickupUnit..ctor (OpenRA.Actor self, OpenRA.Actor cargo, System.Int32 delay) [0x00020] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/PickupUnit.cs:41 
  at OpenRA.Mods.Common.Traits.AutoCarryall+FerryUnit.OnFirstRun (OpenRA.Actor self) [0x00000] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/AutoCarryall.cs:116
```

Duplicate of the crash fixed in #17353.

**Closed** 2019-12-23 14:08 UTC
Labels: Crash
