### ISSUE TITLE
Apple M1: Crash on start when running natively

### ISSUE THREAD

**Issue by adietrichs** [OpenRA/OpenRA#20251] opened 2022-09-03 00:06 UTC
## System Information

- Operating System:  macOS 12.5.1
- OpenRA Version: git-dfd5a960ed
- OpenRA Mod: all
- Source: self-compiled
- Runtime Version: .NET CLR 6.0.8

## Exception log

exception.log
```
OpenRA engine version git-dfd5a960ed
Date: 2022-09-02 00:07:15Z
Operating System: OSX (Unix 12.5.1)
Runtime Version: .NET CLR 6.0.8
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args) in .../OpenRA/OpenRA.Game/Game.cs:line 361
   at OpenRA.Game.InitializeAndRun(String[] args) in .../OpenRA/OpenRA.Game/Game.cs:line 304
   at OpenRA.Launcher.Program.Main(String[] args) in .../OpenRA/OpenRA.Launcher/Program.cs:line 32
```

graphics.log
```
ANGLE: SDL window creation failed: Window data not set
Modern: SDL window creation failed: Window data not set
Embedded: SDL window creation failed: Window data not set
Legacy: SDL window creation failed: Window data not set
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in .../OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 164
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in .../OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in .../OpenRA/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in .../OpenRA/OpenRA.Game/Game.cs:line 382
ANGLE: SDL window creation failed: Window data not set
Modern: SDL window creation failed: Window data not set
Embedded: SDL window creation failed: Window data not set
Legacy: SDL window creation failed: Window data not set
System.InvalidOperationException: No supported OpenGL profiles were found.
   at OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile, Boolean enableLegacyGL) in .../OpenRA/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs:line 164
   at OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile, Boolean enableLegacyGL) in .../OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 21
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings) in .../OpenRA/OpenRA.Game/Renderer.cs:line 79
   at OpenRA.Game.Initialize(Arguments args) in .../OpenRA/OpenRA.Game/Game.cs:line 382
```

## Additional information
I tried compiling the game natively for arm64 (MacBook Air M1), but keep running into the above error message on launch. I tried compiling alternatively with `TARGETPLATFORM=unix-generic` and by manually linking the relevant arm libraries, with no change in outcome. Installing and running the packaged version (via Rosetta) works without issues.

**Comment by Mailaender** [comment] 2022-09-10 16:06
We currently build SDL 2 for Intel only. https://github.com/pchote/SDL2-binaries/blob/master/.github/workflows/build.yml#L13-L27 I guess you have to replace this pre-compiled library.

**Comment by Mailaender** [comment] 2022-09-10 16:07
https://github.com/OpenRA/OpenRA/pull/19887 promised a fix.

**Comment by Shrooblord** [comment] 2022-09-21 12:25
@adietrichs what works for me is following this work-around:
https://github.com/OpenRA/OpenRA/issues/19805

And then using `make RUNTIME=mono` instead of `make all`. It's not .NET 6.0 this way unfortunately, but at least it allows you to run the game without crashing.

**Comment by Mailaender** [comment] 2022-09-21 13:57
You can also try https://github.com/abcdefg30/OpenRA/releases/tag/devtest-20220910

**Comment by Shrooblord** [comment] 2022-09-21 14:04
Thanks. I've tried now, but for me, that has the same effect as targeting `bleed`. I.e. only `mono` works.

**Comment by pchote** [comment] 2022-10-09 17:18
This is caused by https://github.com/libsdl-org/SDL/commit/3046d55d0e9058d47df1abf41fea1e51c1cd7fd5 in SDL 2.24, which I expect will cause the same issue on intel macs.

Downgrading to SDL 2.20 to match our precompiled intel lib should work around this.

**Comment by adietrichs** [comment] 2022-10-17 17:25
Thanks, this seems to have been it! I can confirm that using SDL 2.0.20 (they switched the version numbering scheme between 2.0.22 and 2.24.0) I am able to run OpenRA natively with .NET 6.0.

**Comment by pchote** [comment] 2022-11-26 13:00
This was fixed by https://github.com/libsdl-org/SDL/commit/913e403f2aa5a23beee878b6b13f7603b884c18a in SDL 2.26. Compiling with `TARGETPLATFORM=unix-generic` using SDL 2.26 from homebrew now works natively on my M1 pro.

**Closed as completed by pchote** 2022-11-26 13:00 UTC
Labels: Crash, OS: MacOS
