### ISSUE TITLE
Main menu crash in debian jessie with gnome shell

### ISSUE THREAD

**Issue by clasm** [OpenRA/OpenRA#10054] opened 2015-11-21 15:31 UTC
Crash happens immediately after loading OpenRA, every time I do that.
Problem seems to be specific to GNOME, as I had no problems under MATE.
```
Red Alert Mod at Version release-20150614
Operating System: Linux (Unix 3.16.0.39)
Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1) CLR 4.0.30319.17020
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.Common.Widgets.Logic.SpawnSelectorTooltipLogic+<SpawnSelectorTooltipLogic>c__AnonStorey0.<>m__1 () [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.Draw () [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Widget.DrawOuter () [0x00000] in <filename unknown>:0 
  at OpenRA.Widgets.Ui.Draw () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.RenderTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by penev92** [comment] 2015-11-21 16:59
The log suggests you are running a quite outdated release.
Can you please try the latest playtest and see if the issue persists?

**Comment by Mailaender** [comment] 2015-11-22 06:22
This is a multiplayer lobby related crash. Nothing that should happen in the main menu nor be related to the desktop environment. Maybe the `exception.log` is completely unrelated. After you have updated can you run `openra` in a terminal and post what happens there?

**Comment by clasm** [comment] 2015-11-22 09:44
Ah. So I think that exception.log comes from when I tried once in Gnome
Classic (instead of Gnome Shell). On that occasion, I made it to the
lobby before the crash occurred.

Here's the terminal text of the immediate main menu crash that happens
every time Gnome Shell:

Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1366x768
No custom resolution provided, using desktop resolution
Using resolution: 1366x768
Detected OpenGL version: 3.0
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn (playtest-20151114)
	d2k: Dune 2000 (playtest-20151114)
	modchooser: Mod Chooser (playtest-20151114)
	ra: Red Alert (playtest-20151114)
Loading mod: ra
Failed to open BO for returned DRI2 buffer (1366x768, dri2 back buffer,
named 11).
This is likely a bug in the X Server that will lead to a crash soon.
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.wrapper_native_0x7fbc28a2b240
(OpenTK.Graphics.OpenGL.ClearBufferMask) <IL 0x00023, 0xffffffff>
  at OpenTK.Graphics.OpenGL.GL.Clear
(OpenTK.Graphics.OpenGL.ClearBufferMask) <IL 0x00006, 0x0001e>
  at OpenRA.Platforms.Default.Sdl2GraphicsDevice.Clear () <IL 0x00020,
0x00057>
  at OpenRA.Renderer.BeginFrame (OpenRA.int2,single) <IL 0x00007, 0x00028>
  at OpenRA.Game.RenderTick () <IL 0x00048, 0x00133>
  at OpenRA.Game.Loop () <IL 0x0013e, 0x001e7>
  at OpenRA.Game.Run () <IL 0x00042, 0x0006b>
  at OpenRA.Program.Run (string[]) <IL 0x00011, 0x0004f>
  at OpenRA.Program.Main (string[]) <IL 0x00050, 0x000ff>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object
(object,intptr,intptr,intptr) <IL 0x0005c, 0xffffffff>

Native stacktrace:

	mono() [0x4b5ca0]
	mono() [0x50edab]
	mono() [0x424183]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7fbc369988d0]
	/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x353d2d) [0x7fbc273dcd2d]
	/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x30ea98) [0x7fbc27397a98]
	[0x40109f14]

Debug info from gdb:


=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted
Gtk-Message: GtkDialog mapped without a transient parent. This is
discouraged.

**Comment by Mailaender** [comment] 2015-11-22 10:08
Duplicate of https://github.com/OpenRA/OpenRA/issues/7277 which has been reported fixed in upstream. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762809#37

**Closed by Mailaender** 2015-11-22 10:08 UTC
Labels: Crash, OS: Linux
