### ISSUE TITLE
Infantry blinks in a stand frame after a long L turn.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11895] opened 2016-08-27 12:05 UTC
Example (recorded on a Timestep of 100, sorry about it):
![blinkinf](https://cloud.githubusercontent.com/assets/1136302/18027253/6a715fa2-6c5f-11e6-94d9-0df6b5e7a0d1.gif)

Particular frame:
![092](https://cloud.githubusercontent.com/assets/1136302/18027247/4382203e-6c5f-11e6-8218-c026fd701aa6.gif)

Pretty sure this is a recent regression.

**Comment by reaperrr** [comment] 2016-08-27 12:20
> Pretty sure this is a recent regression.

Nope, I can reproduce it on release 20151224.

**Comment by GraionDilach** [comment] 2016-08-27 12:22
Wow. I never noticed it until today. O_o

**Comment by obrakmann** [comment] 2016-08-27 12:24
Might be related to the issue where `IsMoving` returns false during turns

**Comment by reaperrr** [comment] 2016-08-27 12:31
> Might be related to the issue where IsMoving returns false during turns

I bet that's exactly the cause.

**Comment by pchote** [comment] 2016-08-27 12:32
Lets fix that, then.

**Comment by Micr0Bit** [comment] 2016-08-27 13:30
@GraionDilach : nice catch

**Comment by reaperrr** [comment] 2016-08-27 13:52
There must be some transition tick where the current activity is not `MovePart` (probably just `Move`) even though the actor is moving. We can't just add `Move` to [line 347](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Move/Move.cs#L347), as that causes other regressions.

An idea I'd like to throw into the open:
Maybe we could/should refactor the `IsMoving` check to ignore the `Move` activities entirely and only check for horizontal position changes.
Then we'd need some kind of `BlockAnimation` boolean for special cases like troops on TD landing craft, troops transported by carryalls and teleporting, of course, but that still sounds easier to me than messing around with `Move`.

**Comment by pchote** [comment] 2016-08-27 14:04
I don't like the idea of plastering over the real issue by introducing new logic outside `Move`.  Lets start by identifying the real issue, and then the best fix should become more obvious (and probably a lot easier).

**Comment by reaperrr** [comment] 2018-06-08 16:44
As mentioned in #11885, there's always a 2-tick Turn activity  running as ChildActivity in Move after an L-turn (occasionally in other situations, too), which is the culprit behind this (the actor is indeed not moving forward during that time-frame). Closing as duplicate of #11885.

**Closed by reaperrr** 2018-06-08 16:44 UTC
Labels: Bug
