### ISSUE TITLE
Attack orders dropped by tanks after MCV undeploy

### ISSUE THREAD

**Issue by JustSomeDev1** [OpenRA/OpenRA#18468] opened 2020-07-30 12:23 UTC
## Issue Summary

Orders to attack an MCV may get lost after the MCV is undeployed. This seems to be specific to certain unit types (E.G. tanks are affected, infantry aren't)

## Reproduction

Try to attack an mcv with infantry and tanks. When undeployed, the infantry re-acquire target almost instantly, while the tanks lose it.
P.S. you should try to attack your own MCV or and enemy MCV surrounded by other units/defenses, otherwise tanks may still target the MCV because it's the only valid target (the attack orders is lost anyway).

## Expected behavior

The tanks should keep their target, as it's already the case for the infantry.

## Screenshots / Screen recordings / Replays

Here is an example -- a bit confusing, let me explain it.
Rockets and tanks are attacking the MCV. When the MCV is undeployed, the rockets lose their target for an instant and re-acquire it almost immediately. The tank doesn't (you can see the cannon turning and the red line disappearing).

The confusing frames are the A-move on rifles and the manual re-target at the end, happening after a misclick resulting in a short-living move order. Just ignore those :grin: 

![ORA_mcv](https://user-images.githubusercontent.com/68991120/88922020-c82fcc80-d26f-11ea-9209-fca160412f05.gif)

**Comment by deleted-user-1** [comment] 2020-07-30 12:45
Indeed, something has regressed that part of #15866 which originally fixed #10887. Related to #17706.

**Comment by PunkPun** [comment] 2020-07-30 12:46
slowed it down so it would be easier to see
![test](https://user-images.githubusercontent.com/37534529/88924357-d1bf3180-d27b-11ea-8d1f-404162de731b.gif)

**Comment by PunkPun** [comment] 2020-07-30 12:48
duplicate of #17706

**Comment by deleted-user-1** [comment] 2020-07-30 12:53
> duplicate of #17706

I don't think so, that one is explicitly about force-fire. Alrhough both could have the same cause, lets have this one too to make clear it's a problem for normal targeting and forcefire.

**Comment by PunkPun** [comment] 2020-07-30 12:57
> > duplicate of #17706
> 
> I don't think so, that one is explicitly about force-fire. Alrhough both could have the same cause, lets have this one too to make clear it's a problem for normal targeting and forcefire.

In that issue force fire isn't even mentioned. It's the exact same issue except this one has a gif

**Comment by deleted-user-1** [comment] 2020-07-30 12:58
> > > duplicate of #17706
> > 
> > 
> > I don't think so, that one is explicitly about force-fire. Alrhough both could have the same cause, lets have this one too to make clear it's a problem for normal targeting and forcefire.
> 
> In that issue force fire isn't even mentioned. It's the exact same issue except this one has a gif

See issue title?

**Comment by deleted-user-1** [comment] 2020-07-30 13:05
My bad, I actually read "force fire", sorry. It's a duplicate, @Punsho is correct.

**Comment by pchote** [comment] 2021-04-02 17:37
Closing as duplicate.

**Closed as completed by pchote** 2021-04-02 17:37 UTC
Labels: Bug

**Comment by JustSomeDev1** [comment] 2021-05-31 19:21
@pchote  Should I add the gifs to the original issue #17706 as a reference?
