### ISSUE TITLE
Spy gets squashed even though he is not anymore under the vehicle

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13481] opened 2017-06-08 18:10 UTC
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/6293391/26943609-74cc3550-4c86-11e7-810a-b99d561f5f84.gif)

**Comment by GraionDilach** [comment] 2017-06-09 13:11
Duplicate of #8064.

**Closed** 2017-06-11 11:15 UTC
Labels: Bug
