### ISSUE TITLE
Fake chronosphere is easily revealed

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7591] opened 2015-03-05 07:04 UTC
Here you can see that the fake structure is not imitating the real one and is easy to reveal.
![openra game_2015_03_05_08_02_15_431](https://cloud.githubusercontent.com/assets/7798635/6500618/434f4c0a-c30e-11e4-819f-07116d55ce38.png)
Here is the nuke example:
![openra game_2015_03_06_11_15_17_239](https://cloud.githubusercontent.com/assets/7798635/6523722/98616086-c3f2-11e4-9a1b-86d6fd933b2a.png)
![openra game_2015_03_06_11_16_08_328](https://cloud.githubusercontent.com/assets/7798635/6523715/8dd04bb4-c3f2-11e4-9b0f-3f9d453de960.png)

So all you do is wait until he lunches then lunch on his nuke, he does not know where your real one is but you know where his real one is.

Here you can see that the real chronoshift has a bib under it and the fake does not:
![openra game_2015_03_06_11_45_30_393](https://cloud.githubusercontent.com/assets/7798635/6524106/667ae9f8-c3f6-11e4-9998-34b9628a6be0.png)

**Comment by pchote** [comment] 2015-03-05 08:35
The build animation is only ever played on one structure at a time (the primary or last built one).  The same thing happens if you have two real construction yards.

**Comment by Snurre86** [comment] 2015-03-05 10:24
ok, i'am going to do some more testing the other one that comes to mine is the lunching of nuke silo.

**Comment by deniz1a** [comment] 2015-03-05 10:56
Why doesn't the barracks have player color?

**Comment by WolfGaming** [comment] 2015-03-05 10:59
Because he took the screenshot in the middle of the build animation.

**Comment by MicroJOo** [comment] 2015-03-05 12:57
sry but thats just bullshit , nobody will reveal a fake - structure by "watching it get built" ...

**Comment by MicroJOo** [comment] 2015-03-05 16:52
im fine with that , when my enemy detects a "fake structure" by observing the building with a scout-unit ... and he puts a alot of time and attention into that 

as longs as scroud and fog doesnt reveal such things ...

**Comment by WolfGaming** [comment] 2015-03-05 17:39
I would say that this goes under the same umbrella as you can try to guess that building is fake because it doesnt produce any units. etc

**Comment by Snurre86** [comment] 2015-03-06 11:01
More images (here you can see the real nuke silo easier if your enemy is to your south.

Lunching (here both can see the lunch):
![openra game_2015_03_06_11_50_34_627](https://cloud.githubusercontent.com/assets/7798635/6524277/27630230-c3f8-11e4-8882-ef9117686e0e.png)
![openra game_2015_03_06_11_50_08_356](https://cloud.githubusercontent.com/assets/7798635/6524295/52d9d24a-c3f8-11e4-9b86-221d9021fb38.png)
Nukes on its way up (the north one is already gone):
![openra game_2015_03_06_11_51_37_788](https://cloud.githubusercontent.com/assets/7798635/6524319/88c76e1c-c3f8-11e4-96b1-4e2c91809619.png)
![openra game_2015_03_06_11_51_28_895](https://cloud.githubusercontent.com/assets/7798635/6524320/8db1f0f0-c3f8-11e4-8b17-730d657dd59e.png)

**Comment by WolfGaming** [comment] 2015-03-06 12:03
And if your enemy has a nuke that has launched and you are spending your time flying around in a base with no units I think you have already lost because that would mean your base is being overrun.

**Comment by penev92** [comment] 2015-03-06 13:26
While I agree that the nuke silo shouldn't be a problem (you don't want your enemy to have vision of that anyway), did someone pay any attention to:
>Here you can see that the real chronoshift has a bib under it and the fake does not:

?
One of those chrono-machine-thingies is not like the others (if you look closely)...

**Comment by Snurre86** [comment] 2015-03-06 19:18
I could put your mother in there to WolfGameing might change the way the nuke silo is revealed.

**Comment by Snurre86** [comment] 2015-03-06 19:23
This is your base and this is what you see, now where is the nuke silo?
![untitled](https://cloud.githubusercontent.com/assets/7798635/6532141/9bf605e8-c43e-11e4-8808-555c42496af2.png)

**Comment by penev92** [comment] 2015-03-06 20:05
Somewhere south of your base.

**Comment by penev92** [comment] 2015-03-06 20:18
Issue resolved:
![](http://i.imgur.com/hv94ido.png)

**Comment by obrakmann** [comment] 2015-03-06 21:19
So, I unlocked this again. That said, I reserve the right to lock it back up. For what it's worth, the arguments have been made, so I won't tolerate any more harping on about the same issue.

Just let it be said that the fake structures aren't meant to completely mirror the real structures, especially not in behaviour. They're meant to visually distract or mislead an opponent to gain a few precious moments while organizing the defense of your base during attacks. Nothing more, nothing less. For this purpose, fakes do an excellent job.

**Comment by MicroJOo** [comment] 2015-03-06 21:30
if theres no vandalism ... then there shouldnt be "any" kind of locks or limited conversations ... this is a open source project ... maybe some people , with certain administrator-rights dont understand that

you could just "ignore" what you dont like ... and later on when the interest is gone ... do a clean up on stale trivial issues that dont have any progress and seem to get dusty after some time ... 

@Mailaender is doing it that way ... and its imo more gentle instead of locking a conversation

**Comment by Mailaender** [comment] 2015-03-07 08:39
> One of those chrono-machine-thingies is not like the others (if you look closely)...
![Proof](http://i.imgur.com/7cPxVbl.png)

Oh, we forgot the bib on the fake chronosphere! That is easily fixed though.

**Comment by pchote** [comment] 2015-03-07 08:45
Duplicate of #7600, fixed by #7602.

**Closed by pchote** 2015-03-07 08:45 UTC
Labels: Bug, Easy, Red Alert

**Comment by Snurre86** [comment] 2015-03-09 08:31
Thank you for creating this issue Snurre86.
