### ISSUE TITLE
Kennel requires a bib 

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#8955] opened 2015-08-05 12:23 UTC
dogs won't come out when the kennel is placed unhappy ... 

![kennel](https://cloud.githubusercontent.com/assets/9139965/9085489/7ede6fa2-3b7d-11e5-840a-1447ea859272.png)

**Comment by abcdefg30** [comment] 2015-08-05 12:24
Duplicate of #7663.

**Closed by abcdefg30** 2015-08-05 12:24 UTC
