### ISSUE TITLE
Navy AI in RA using aircraft that can't attack air to try to attack air

### ISSUE THREAD

**Issue by Nineeva** [OpenRA/OpenRA#12190] opened 2016-10-08 12:58 UTC
It seems like in Skirmish mission the Navy AI at least tries to use migs to attack my helicopters which they can't succeeded in doing as they don't have anti-air weapons.  They end up just circling around them and following them, making them very easy to kill.

**Comment by GraionDilach** [comment] 2016-10-08 15:49
I can see this happening vice versa, AI gathering his stuff under helicopters.

**Comment by abcdefg30** [comment] 2016-10-08 16:29
See #3468.

**Comment by abcdefg30** [comment] 2018-10-01 08:40
Closing as duplicate of #3468.

**Closed by abcdefg30** 2018-10-01 08:40 UTC
Labels: AI, Bug
