### ISSUE TITLE
AI acts quite predeterminated.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#13256] opened 2017-05-07 11:47 UTC
Notsure what's causing this though.

Observe a full AI match and restart the game from the options menu. The game then ends up recreating the same situations.

**Comment by pchote** [comment] 2017-05-07 12:17
This is the same issue as #11190.  The RNG seed does not change, so the same "random" outcomes occur.  Not closing as duplicate, because this is a distinct bug that just happens to have the same fix.

**Comment by forcecore** [comment] 2017-05-08 17:19
I encountered this during scripted AI and thought this was on purpose.

**Comment by rob-v** [comment] 2017-05-09 15:39
GlobalSettings.RandomSeed is created from DateTime.Now on Server creation used by World.SharedRandom so using Game.CosmeticRandom (seeded once) wouldn't help? I think the issue is that on match restart, this seed is not changed, not seed source itself.

**Comment by pchote** [comment] 2017-05-09 15:42
CosmeticRandom isn't reset on game restart, so it will sample a different position in the pseudo-random sequence each time the game is restarted.  This will then seed a different sequence from the AI's RNG.

**Comment by rob-v** [comment] 2017-05-10 10:08
On World creation, SharedRandom could be Game.CosmeticRandom (if there is no reason to create new RNG like now) or GlobalSettings.RandomSeed reseeded. It solves these 2 issues, but I am not sure it is the right solution.
1. currently - no change in factions, spawns, course of the game (with AIs only)
2. after change - new factions, spawns, course of the game (as requested here #11190)

When I Restart I am used/expect that setup (factions, spawns,..) stays the same. With at least one human player, it is achieved that course of the game will be different, looks strange to observe the same AI match, but this is minor issue. (could we randomize only behaviour and keep factions,.. on Restart?)

**Comment by pchote** [comment] 2017-05-10 11:03
#11190 and this are separate both in terms of implementation and in whether or not we want to implement them, so It would be better to keep the two discussions separate.

For this one, I don't see any strong arguments for keeping identical AI behaviour on restart.  The way to fix it is to change [HackyAI.cs#L345](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/AI/HackyAI.cs#L345) to be seeded with something that is different each invokation.  `CosmeticRandom` is one such source (`SharedRandom` won't work, because that needs to be synced across all players), or the current time is another.

**Closed** 2017-05-13 18:08 UTC
Labels: AI, Polish
