### ISSUE TITLE
Sound effects and unit voices stop when reloading a saved game when already in a game

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#17938] opened 2020-04-14 06:00 UTC
Playing Red Alert in Playtest 20200303 and I noticed that when opening the pause menu ingame in a singleplayer mission and loading a saved game, there will be no sound for sound effects (like guns, explosions, etc) and unit voices. Audio such as music and EVA announcements will still be present however.

I could get around this bug by quitting to the main menu and loading the saved game from there. Unsure if this bug also occurs in skirmish matches or in TD and D2K since I didn't test for that.

**Comment by abcdefg30** [comment] 2020-07-23 14:26
Closing as duplicate of #17359.

**Closed as completed by abcdefg30** 2020-07-23 14:26 UTC
Labels: Bug
