### ISSUE TITLE
Rocket Soldiers not doing damage to Hinds when directly above them.

### ISSUE THREAD

**Issue by blackendra** [OpenRA/OpenRA#13012] opened 2017-03-23 01:18 UTC
Noticed this while specing a game. I tried to provide a few screen caps as I don't have a video capture.

![openra-2017-03-23t011402069z](https://cloud.githubusercontent.com/assets/24085448/24227607/803dd8aa-0f2b-11e7-9b9e-e875d2861d76.png)
![openra-2017-03-23t011403846z](https://cloud.githubusercontent.com/assets/24085448/24227609/8041dca2-0f2b-11e7-81ad-ee5d55dba7e4.png)
![openra-2017-03-23t011400265z](https://cloud.githubusercontent.com/assets/24085448/24227608/803e2c92-0f2b-11e7-86df-8da2fe345cac.png)
![openra-2017-03-23t011358796z](https://cloud.githubusercontent.com/assets/24085448/24227605/803c75c8-0f2b-11e7-8880-b95d171f3d90.png)
![openra-2017-03-23t011405733z](https://cloud.githubusercontent.com/assets/24085448/24227606/803cf7be-0f2b-11e7-9388-158f42ffe578.png)

**Comment by GraionDilach** [comment] 2017-03-23 06:30
Duplicate of #12123. Apparently #12563 wasn't a fix?

**Comment by pchote** [comment] 2017-03-23 09:32
No version was mentioned, so I assume this is release-20161019.  #12563 came after that.

Closing as duplicate / fixed.

**Closed by pchote** 2017-03-23 09:32 UTC
