### ISSUE TITLE
Minimap shows resource change under fog

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9177] opened 2015-08-27 01:17 UTC
You can see on the minimap where resources are spreading and being harvested under the Fog of War. Most visible with the Grow Resources debug option.

**Comment by deniz1a** [comment] 2015-08-27 04:46
See #5908.

**Comment by abcdefg30** [comment] 2015-08-27 08:41
Indeed a duplicate of #5908.

**Closed by abcdefg30** 2015-08-27 08:41 UTC
Labels: Bug
