### ISSUE TITLE
Units blocking refinery and Warfactory untargetable.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#15012] opened 2018-03-30 18:26 UTC
When you block a unit with something that can't be scouted (IE: Stealth tank) You can't force fire at the entrance of the refinery or war factory.

Has not been tested if this also applies in RA.

**Comment by ltem** [comment] 2018-03-31 10:46
Possible duplicate of #14994?

**Comment by GraionDilach** [comment] 2018-03-31 11:16
Sounds like it, yes.

**Comment by reaperrr** [comment] 2018-03-31 14:50
Closing as duplicate then, moved the other issue to milestone.

**Closed by reaperrr** 2018-03-31 14:50 UTC
Labels: Regression
