### ISSUE TITLE
Crash related idle behavior of dead aircraft

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20370] opened 2022-10-14 09:11 UTC
Mod: SP

```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (stormrider 1564 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\TraitDictionary.cs:line 84
   at OpenRA.Mods.Common.Traits.Locomotor.UpdateCellBlocking(CPos cell) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\Locomotor.cs:line 488
   at OpenRA.Mods.Common.Traits.Locomotor.CanMoveFreelyInto(Actor actor, CPos cell, SubCell subCell, BlockedByActor check, Actor ignoreActor) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\Locomotor.cs:line 230
   at OpenRA.Mods.Common.Pathfinder.DensePathGraph.GetConnections(CPos position) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\DensePathGraph.cs:line 131
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 219
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 290
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 755
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 131
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 114
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 129
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 103
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 636
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 651
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 820
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

I apply the [engine](https://github.com/MustaphaTR/OpenRA/commit/02d9ba020dc91939160568d38bceec444d61d859) with https://github.com/MustaphaTR/OpenRA/pull/61 but it should not be the cause of the bug right?

**Comment by dnqbob** [comment] 2022-10-14 09:12
Ah damn it is a crash, I need a crash tag here

**Comment by PunkPun** [comment] 2022-10-14 09:17
Looks like the stormrider forgot to remove itself from the actor map. Did the storm rider ever land? Because if not then this is likely cause by custom logic as flying units simply don't occupy actor map

**Comment by dnqbob** [comment] 2022-10-14 09:30
>  Because if not then this is likely cause by custom logic as flying units simply don't occupy actor map

stormrider can land, and not the one that removed the actor map effect (which is named as stormrider-spawn).

**Comment by dnqbob** [comment] 2022-10-14 09:34
![image](https://user-images.githubusercontent.com/13763394/195813861-8d531318-c4f5-43a5-89ed-ee81f8e7d2f2.png)

And in code here I only disable `AddInfluence` when aircraft doesn't take up cell, they always `RemoveInfluence` when take off. I think it should not be the problem that I don't remove the influence.

**Comment by dnqbob** [comment] 2022-10-14 09:59
going to debug deeper.

**Comment by PunkPun** [comment] 2022-10-14 10:03
Did the strom rider get teleported while on gound? Because we don't allow aircraft to be teleported. #20313 may be related incase of a teleport

**Comment by dnqbob** [comment] 2022-10-14 10:06
Nope

**Comment by dnqbob** [comment] 2022-10-14 12:11
The actor who perform a pathfinding is an engineer unit
![image](https://user-images.githubusercontent.com/13763394/195843849-5e641b53-c7dc-4194-b065-bc190d362e58.png)

**Comment by dnqbob** [comment] 2022-10-14 12:15
![image](https://user-images.githubusercontent.com/13763394/195844401-2bc8f4c7-904a-48ec-a9ef-eb4b816556dd.png)
And the occupied cell (70, 20), it is here.

**Comment by PunkPun** [comment] 2022-10-14 12:21
It doesn't matter which unit triggered the crash. We care about the stormrider and how it relates to that cell

**Comment by dnqbob** [comment] 2022-10-14 12:42
![bug-showcase](https://user-images.githubusercontent.com/13763394/195847796-5f000108-d9a3-413c-83d3-8fef36046525.gif)

Before the end of the replay, I track a "strom rider" which is landed at the bug position. It is killed at the end of the replay, where the crash happends.

**Comment by PunkPun** [comment] 2022-10-14 12:51
So it is likely that #20313 fixes it. You can try applying https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:fix-aircraft which is a cleaner fix and see if it still crashes. Though if a unit tried to pathfind over that cell the replay might desync earlier. 

It could be debugged by checking the value of OccupiedCells on influence being added and removed. It is not unlikely that occupied cells changed before removing influence thus ending up never removing influence. It might as well be somehow possible that it never even attempted to remove influence.

**Comment by dnqbob** [comment] 2022-10-14 12:52
very strange. I am going to hardcode to check the add and remove influence of this unit

**Comment by dnqbob** [comment] 2022-10-14 13:03
> So it is likely that #20313 fixes it. You can try applying [bleed...PunkPun:OpenRA:fix-aircraft](https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:fix-aircraft) which is a cleaner fix and see if it still crashes. Though if a unit tried to pathfind over that cell the replay might desync earlier.
> 
> It could be debugged by checking the value of OccupiedCells on influence being added and removed. It is not unlikely that occupied cells changed before removing influence thus ending up never removing influence. It might as well be somehow possible that it never even attempted to remove influence.

will try later

**Comment by PunkPun** [comment] 2022-10-14 13:04
I'm suspect that https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L883 is the cause. It likely didn't return true when the aircraft started the takeoff activity. The whole aircraft occupying space logic is a bit bogus and fixed in https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:fix-aircraft

**Comment by dnqbob** [comment] 2022-10-14 13:53
![image](https://user-images.githubusercontent.com/13763394/195864058-9f69388b-5f58-4fa8-8589-4782d3863e3f.png)

This means, `RemoveInfluence` may not remove influence properly?

**Comment by dnqbob** [comment] 2022-10-14 14:20
![bug-showcase3](https://user-images.githubusercontent.com/13763394/195869778-9a5b137e-0c80-4b36-87a1-fb762b677758.gif)

**Comment by dnqbob** [comment] 2022-10-14 14:36
Summary:
1. The stormrider get killed and crash later generate first "++influence" and "--influence" pair on a resupply run.
2. we can also find that another stormrider has 1x"++influence"  and 2x"--influence" on a resupply run.

Strange things:
1. if it is the influence cannot be removed properly, I think the first stormrider should block ally from entering the RD. However, it doesn't.

**Comment by PunkPun** [comment] 2022-10-14 15:05
Are those numbers from OccupiesCells? Because RemoveInfluence removes influence from OccupiedCells

**Comment by dnqbob** [comment] 2022-10-14 15:28
> Are those numbers from OccupiesCells? Because RemoveInfluence removes influence from OccupiedCells

~~Sure~~ no, they are from `landingcells`

**Comment by dnqbob** [comment] 2022-10-14 15:41
so this problem is result from the OccupiesCells != landcells ?

**Comment by dnqbob** [comment] 2022-10-15 04:14
![add-remove-pair](https://user-images.githubusercontent.com/13763394/195968804-a23717cc-1224-470d-8a2e-fea74bab10dd.gif)


like Pun says, `AddInflunce` and `RemoveInflunce` on actormap is related with the `OccupiedCells`, instead of `landcell`, so I make the debug shows `OccupiesCells[0]` as well as `landcell`.

It looks normal, too. Feels very strange.

**Comment by dnqbob** [comment] 2022-10-15 11:19
~~Crash fixed in https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:fix-aircraft and surprisingly the replay is synchronized.~~

~~https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:fix-aircraft is not synchronized. It is end at 15s before replay finished.~~

I need to confirm it further, due to the actual replay time does not correspond to the replay time displayed in the replay category. Maybe it is due to the speed setting.

Confirmed: Crash fixed in https://github.com/OpenRA/OpenRA/compare/bleed...PunkPun:OpenRA:fix-aircraft and surprisingly the replay is synchronized.

Before fix: there is an exception throwing line
![bug1](https://user-images.githubusercontent.com/13763394/195985656-631dde54-2a7c-4066-a91e-d54a293ca82e.png)

After fix: 
![fix1](https://user-images.githubusercontent.com/13763394/195985668-fe025f74-2bc2-4d64-8714-09af81f2947c.png)

And this is the output after the fix, maybe don't have much senses:
![image](https://user-images.githubusercontent.com/13763394/195983677-e33ae732-b8ed-4c44-b2b0-6eb5aa4d6336.png)

**Comment by dnqbob** [comment] 2022-10-15 12:15
I will also test if https://github.com/OpenRA/OpenRA/pull/20313 fix it
@RoosterDragon

**Comment by dnqbob** [comment] 2022-10-15 12:35
https://github.com/OpenRA/OpenRA/pull/20313 also fix the crash

![image](https://user-images.githubusercontent.com/13763394/195986698-6d398e10-5211-4851-9d1c-693e7c29ae74.png)

**Comment by dnqbob** [comment] 2022-10-15 12:40
Still I quite don't understand why the crash happen and how it is fixed by tested PR. 

But I think you can link this crash issue to the PR that fixes it.

**Comment by Mailaender** [comment] 2022-10-24 18:44
I can confirm that it is related to the aircraft carrier code from https://github.com/OpenRA/ra2/pull/682 as https://github.com/OpenHV/OpenHV/issues/602 is affected as well.

**Closed as completed** 2022-10-30 13:01 UTC
Labels: Crash, Regression

**Comment by Mailaender** [comment] 2022-10-30 13:25
Corrections: I think this is related to carrier-based aircraft that define
https://github.com/OpenRA/OpenRA/blob/57143087d733e6708d0b0a016373baadd6324f6c/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L38
