### ISSUE TITLE
GarrisonCapture Trait Idea

### ISSUE THREAD

**Issue by StormWingDelta** [OpenRA/OpenRA#12648] opened 2017-01-29 18:11 UTC
I figured this trait must have simply not been thought of to add to OpenRA yet since you guys are likely focusing on bigger things so here it is.

GarrisonCapture Trait: this allows a player to garrison a structure or unit and change the side/faction of said unit/structure to that of the side/faction of the units inside it.  I've seen this happen in the version of Red Alert and TS that came after the first versions where if you sent units into a building to garrison it the building would change to the side of those units with a few exceptions.  Like in the case of mind-controlled units where their faction/side on entry is used instead of their faction/side after once control over them has been returned to the original owner.

I figured this trait could be very handy to players that like to mess with the code and it'd also help with someone is building a city map and wants players to be able to send their units to take it over to slow down their enemies.

Also a side note idea for those of you that know how to mess with the AI's main C# code why not tell the AI to locate any structures/units that have empty garrison/cargo slots for units and tell it to randomly select correct units to fill those slots.  In the case of transports there could also be a trait to tell the AI to auto deploy them when close enough to an enemy force.  In both these AI ideas it does add a couple more traits for the players to mess with to let them change things up a bit.

As for the main idea of a GarrisonCapture Trait this will help open up some doors you may have been scratching your heads as to how to open. :)

**Comment by GraionDilach** [comment] 2017-01-30 16:36
Duplicate of #11214.

**Comment by pchote** [comment] 2017-02-03 10:40
Closing as duplicate.

**Closed by pchote** 2017-02-03 10:40 UTC
Labels: Feature
