### ISSUE TITLE
#17472 broke network protocol compatibility without increasing the protocol version

### ISSUE THREAD

**Issue by jrb0001** [OpenRA/OpenRA#18046] opened 2020-05-06 19:45 UTC

**Comment by abcdefg30** [comment] 2020-05-06 20:29
https://github.com/OpenRA/OpenRA/pull/17472/files#diff-d040ed0daafa0ce1819a4eed21cb0f09R69
Looks like that got lost due to a rebase fail.

**Comment by abcdefg30** [comment] 2020-05-07 07:51
This will be fixed by the follow-up of #17472 since that increases the version again anyway.

**Comment by MustaphaTR** [comment] 2020-09-20 14:53
This seems to be still an issue and there has been a followup PR to #17472. I had reverted that PR in rv-engine back when i made the engine update, since we really needed servers back then, but now i'm trying to do another engine update that will include #18512, i really don't wanna create a mess with revertations and merge conficts so would be nice if this can be handled. I'm not sure if all that needs to be done is to increase the number, so will leave it to someone who understands better.

**Comment by abcdefg30** [comment] 2020-09-20 14:58
I didn't make a follow-up to #17472 which changes the orders again afaik. #17578 will handle the bump of the version.

**Comment by MustaphaTR** [comment] 2020-09-20 15:13
I was talking about #18512 when i said followup. The way i understood your comment was that you would increase the number with a related followup PR even if that didn't require number bump by itself. I'm not sure how close to being merged #17578 is, but i would rather see the bump that should've happened with #17472 soon so jrb can update the servers properly and i can get the Grouped Orders in rv-engine with the next engine update because a) it is a nice improvement to have b) i don't wanna mess with the conflicts that may get caused by my fork's lack of that feature. Tho if that happens #17578's author shouldn't forget to update his PR so this won't repeat again.

If #17578 may get merged in a week at most tho, i can wait.

**Comment by pchote** [comment] 2020-09-21 10:36
There is just one last problem to solve in #17578, so that will hopefully be merged soon.

**Comment by MustaphaTR** [comment] 2020-10-10 09:13
#17578 is merged, so i guess this can be closed now.

**Closed as completed by MustaphaTR** 2020-10-10 09:13 UTC
Labels: Bug, Networking
