### ISSUE TITLE
Large map names wont show up entirely in the lobby screen.

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12595] opened 2017-01-17 22:39 UTC
As the title say,having a large name for a map is like looking in the night sky for venus with a naked eye.
Larger map names are getting often out of screen,and the user can only see the half part of the sentence.
probably 2 options can be used as a solution first make the letters smaller as the sentence gets bigger and 
make this "\n" work too in the game lobby.Any other ideas?

**Comment by pchote** [comment] 2017-01-17 23:37
> Any other ideas?

My preference is for the simple solution: use shorter map names.

**Comment by airetaM** [comment] 2017-01-18 01:54
The problem is if someone changes an exsisting map and just write it behind the mapname what he modded you can only read ...
even from extreme tournament island you can only read "extreme tournament is..."

**Comment by FrameLimiter** [comment] 2017-01-18 02:18
If a map requires an explanation you can write a description of it under World>MissionData>Briefing and it will show up in the lobby for everyone.
Rules:
+World:
++MissionData:
+++Briefing:  "Details about the map"

**Comment by KOYK** [comment] 2017-01-18 12:01
we are talking about names not descriptions.using shorter map names is not a solution and does not responds to the quality of the OpenRa,not to mention that you can't force the map author to count his letters or limit his actions.having the ability to use at least 2 lines or smaller letters is a missing feature and not an option to avoid.

**Comment by WolfGaming** [comment] 2017-01-18 13:55
I would have to agree with @pchote here, names really don't have to be that long and it is imo up to the authors of each map to present their map in the best way possible (aka use names that can be fully seen ingame).

**Comment by obrakmann** [comment] 2017-01-18 21:33
I concur with both pchote and FrameLimiter here. The fact that it has modified rules shouldn't be part of the map's name.

**Comment by kyrreso** [comment] 2017-01-18 22:22
A simple solution here is to make "mouseover" reveal the whole name of the map.

**Comment by airetaM** [comment] 2017-01-19 01:38
There are so many maps with too long names when i look on the resource center and even 2 RA standard maps end with ...

**Comment by kyrreso** [comment] 2017-01-22 22:34
Is it possible to fix this by having servers just write the name of the map in the chat? Then we do not need new game clients to have this fixed, just make servers do it in next server version?

**Comment by KOYK** [comment] 2017-01-24 19:52
i will say again..** ## we are talking about names not descriptions** try to add the name "tanya's training grounds" this is an official map name from red alert 2,so sooner or later the "use shorter map names" won't just work people.

**Comment by abc013** [comment] 2017-01-25 17:25
@KOYK we mostly shortened large mission names, e.g. Allies06a: `Infiltrate and destroy Iron Curtain research center`. We changed it to `Cripple Iron Curtain research`.

Also there was already a small discussion about that [here](https://github.com/OpenRA/OpenRA/pull/12322#discussion_r87827133).

**Comment by airetaM** [comment] 2017-01-25 20:48
Then the names of these sthandard maps should be changed maybe: "Drop Zone - Battle of Tikiaki", "Center of Attention Redux 2", in TD "Morbid Aimless Poseidon" Dune is all fine.

**Comment by rob-v** [comment] 2017-03-20 19:12
PR created https://github.com/OpenRA/OpenRA/pull/13005

Added tooltip to Map title

![obrazok](https://cloud.githubusercontent.com/assets/16348750/24117122/3ade9750-0da9-11e7-95c3-04ed41a4031e.png)
In current version when map is changed in lobby, the new map name is written in chat (but not client connects first time).

**Comment by pchote** [comment] 2017-03-20 19:27
That tooltip is unreasonably long - I'd consider not truncating that to be a bug.

**Comment by rob-v** [comment] 2017-03-20 19:31
How long it can be? I'l truncate it. (I assume map titles are usually shorter, this was so long only for test)

**Comment by abcdefg30** [comment] 2017-05-10 13:00
#13005 was merged.

**Closed by abcdefg30** 2017-05-10 13:00 UTC
Labels: Polish, UI
