### ISSUE TITLE
Cheats to give opponent things.

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#2677] opened 2013-02-10 07:04 UTC
Feature request:
When I'm testing, I always need to cheat to make things go faster. But I can't cheat for the AI and give him stuff I want him to have. I have to wait, because I am still reliant on the AI to produce something to test my weapons on. It would be great if I could just plop down 5 guard towers in the enemy's base, or give him 20 mammoth tanks, or give him money. That would make my life a lot easier and more  fun while testing.   :)

please & thank you.

**Comment by Mailaender** [comment] 2015-04-10 04:56
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/7905.

**Closed by Mailaender** 2015-04-10 04:56 UTC
Labels: Feature
