### ISSUE TITLE
Exception of type `System.IO.FileNotFoundException`: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

### ISSUE THREAD

**Issue by DomN86** [OpenRA/OpenRA#11779] opened 2016-08-07 01:04 UTC
Hi,

I installed the newest version, overwriting a previous version that was at least 2 years old. I went straight to the settings to reset the settings, and set to open 'windowed'. Upon accepting the restart request, the program fails to launch with a 'Fatal Error' message. I've tried un-installing, and re-installing, but still get the 'Fatal Error' dialogue.

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.Sound..ctor(String engineName)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

Regards,
Dominic Naylor.

**Comment by pchote** [comment] 2016-08-07 01:22
Duplicate of #11252 which was fixed by #11757.

Deleting your settings.yaml (or just the sound engine line from inside it) will work around the problem.

**Closed by pchote** 2016-08-07 01:22 UTC
