### ISSUE TITLE
Play-on after game is done, old ending with chat and stats [$5]

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#7956] opened 2015-04-14 22:10 UTC
I want the old ending, where we could play on after game ended (force fire, look around, move units, wait for nuke to land, etc). We could also chat... 
I also want the beacons to be on.

Later I want the possibility to draw on map for analyzing and explaining.
See also:
#6865  and #6864

**Comment by x-a-n-a-x** [comment] 2015-04-15 04:44
Check https://github.com/OpenRA/OpenRA/issues/3037

**Comment by obrakmann** [comment] 2015-04-15 07:53
Why exactly did you feel the need to open a new ticket for this again when you knew exactly that there already are existing tickets? You even linked them. Please stop wasting my time.

Also: One issue per ticket, please.

That said, we will not return to the old behaviour, as we told you already about a gazillion times. The score screen will stay, although the particular implementation might change. I will probably add the possibility to hide the score screen to pan around the map, and I might even move the chat below the stats if there's enough space, but it's too late for that for the upcoming release. It also depends on how much I feel like dealing with the inevitable shitstorm I now know I will have to endure.

Closed as duplicate of #6865, #6864 and #3037.

**Closed by obrakmann** 2015-04-15 07:53 UTC
Labels: Bounty

**Comment by mylemans** [comment] 2015-04-15 08:39
@obrakmann Maybe you have a point but "Please stop wasting me time" "I" this, "I" that... Really? I wasn't aware that OpenRA was owned by you. My mistake...

**Comment by obrakmann** [comment] 2015-04-15 09:01
It most certainly is not, and I apologize if I came across that way, but I wrote that piece of code in question, so I see it as my responsibility to deal with the fallout.

I'm also very, very tired of this discussion about the score screen, since we have rehashed it endlessly since forever, so I my answer may have been sharper than necessary.

**Comment by mylemans** [comment] 2015-04-15 09:03
@obrakmann Well all have our bad days :)

**Comment by kyrreso** [comment] 2015-04-15 10:30
:-)

Sorry for not finding any other tickets. I tried to search for "ending",
"end", and some others, but did not find. I also asked in IRC but I guess
ppl where busy.
The other tickets do not have "play on", but just other parts of this
ticket..

Have the devs made the final decision about this? What is the procedure for
me if I still want this, one time in the future?

**Comment by Mailaender** [comment] 2017-08-21 21:06
> Have the devs made the final decision about this?

Yes, sorry.

> What is the procedure for me if I still want this, one time in the future?

Create your own mod with custom code. For now, I can only offer to ask @bountysource-support for a refund https://www.bountysource.com/issues/11158880-play-on-after-game-is-done-old-ending-with-chat-and-stats to get your money back.

**Comment by Cervator** [comment] 2017-08-28 01:48
FYI I just refunded the bounty - am a Bountysource volunteer and noticed by chance.

Keep up the great project. Love the old Westwood games :-)
