### ISSUE TITLE
Long range ordinance exposure

### ISSUE THREAD

**Issue by skeights** [OpenRA/OpenRA#10930] opened 2016-03-15 16:23 UTC
After a short while of play testing, I feel that long range ordinance is a fantastic offensive and defensive measure, but I also feel that they are over powered. 

The ranges and damages are fine but the ability for a unit to fire from within the shroud while also remaining concealed is unfair on the player being fired upon. 

I propose that if the player has a powered radar installation, then the unit firing upon them should have a small area of the shroud revealed around them temporarily allowing the player that is fired upon to counter attack with their own artillery or aircraft.

**Comment by Phrohdoh** [comment] 2016-03-15 16:25
Related to #5061.

**Comment by skeights** [comment] 2016-03-15 16:33
After reading the comments from #5061, I think my proposal is a fair compromise that wont nerf arty units substantially whilst evening the odds slightly for the targeted player.

**Comment by obrakmann** [comment] 2016-03-15 17:19
Duplicate of #3476

**Closed by obrakmann** 2016-03-15 17:19 UTC
