### ISSUE TITLE
Allow choosing which monitor the game should use, on multi-monitor systems

### ISSUE THREAD

**Issue by chrisforbes** [OpenRA/OpenRA#12363] opened 2016-11-08 03:19 UTC
This requires a bit of extra SDL plumbing to do properly, but is straightforward.

**Comment by everclear72216** [comment] 2020-02-05 02:02
I implemented this feature and will be able to submit a pull request within the week.

I just wrote a feature request and found it would be a duplicate of this ticket. I will post my ticket contents below.

## Motivation
I play on a PC that runs Debian and Gnome3 with 3 Monitors. Whenever I switch to full screen mode I cannot choose which monitor will be used for full screen display. The default choice in my case is not acceptable and I will not change my desktop setup for a single application or game.

## Proposed solution
SDL2 provides all the necessary API to technically solve this problem. In the display tab of the settings menu I would like a drop down to be available if I choose full screen mode that enables me to choose which monitor I would like to display the game on (after a restart). The choice shall be saved persistently.

## Side effects
Display selection should not change for users accustomed to the current behavior. 

## Alternatives
A user-side alternative would be to play in windowed mode, which did not work for me. I inadvertently keep moving around the window in hasty situations.
On the developer side making this configuration only available through the configuration files would be sufficient to cater for this (corner?)-case. However, I think this feature may be of value to others and should not be hidden from the people who just want to play instead of looking for hidden options.

**Closed** 2020-02-08 18:14 UTC
Labels: Feature
