### ISSUE TITLE
Not all Armaments ranges are taken into account in reach target checks

### ISSUE THREAD

**Issue by Holloweye** [OpenRA/OpenRA#9266] opened 2015-09-05 10:58 UTC
If you have multiple Armaments only the first one will be counted for the unit range. And if you for example disable (with upgrades) the first armament (which might have a longer range then the second Armament) then the unit will just stand still and try to shot but cant reach the target. As the range for the units is not updated upon disabling the first Armament.

**Comment by obrakmann** [comment] 2015-09-05 14:30
Sounds like a duplicate of #8184.

**Comment by pchote** [comment] 2015-09-05 15:32
Maybe fixed by #8768?

**Comment by obrakmann** [comment] 2015-09-06 13:39
No, unfortunately it doesn't.

**Comment by matija-hustic** [comment] 2015-10-09 14:08
Could you check if #8768 solved this?

**Comment by abcdefg30** [comment] 2016-07-01 12:25
This should be fixed now (if not by #8768 then by #11459).

**Closed by abcdefg30** 2016-07-01 12:25 UTC
Labels: Bug
