### ISSUE TITLE
Player name input gets reverted/loses focus while typing

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14852] opened 2018-02-24 11:50 UTC
Small but rather annoying issue: whenever anyone joins/leaves the server or types a message, player name edit gets reset/saved if you type something in it. This leads to make it very hard to change nickname to something long on a busy lobby because you'd barely have time to type 1-2 letters in.

**Comment by pchote** [comment] 2018-02-24 11:56
Duplicate of #5802.  Follow the chain of issues/prs within for explanations on the cause and explanations of the code changes required to fix it.

**Closed by pchote** 2018-02-24 11:56 UTC
