### ISSUE TITLE
Engineer cant enter empty pillbox anymore

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#8128] opened 2015-05-10 11:37 UTC
even though the pillbox has full hp , it will only show the "locked-repair-icon" .. thus making it unaccessible for engineers

used to be a nice addition to prevent unused engineers from getting sniped by scout-vehicles ( soviets even have the 5-slot bunker on wheels  called "apc") 
##

**Comment by obrakmann** [comment] 2015-05-10 12:47
Introduced with commit ce6c883fb14e7406f543cc9a80aa21dd67680ffa in #7445

**Comment by sinf** [comment] 2015-05-12 22:44
Engineer could be allowed to enter a pillbox but not repair it. Makes more sense that way. Why would anyone want to repair a $500 pill box with a $500 engineer?

**Comment by GrayHatter** [comment] 2015-05-25 04:48
If empty - enter, else - repair

Maybe he used up his usefulness?

**Comment by MicroJOo** [comment] 2015-09-21 21:39
still present in Release 20150919 ... just saying

**Comment by pchote** [comment] 2018-05-10 18:34
Closing as reverse duplicate of #13449 as that one has some discussion about how to fix this.

**Closed by pchote** 2018-05-10 18:34 UTC
Labels: Bug, Regression
