### ISSUE TITLE
Implement suspending multiplayer game when all players agree

### ISSUE THREAD

**Issue by kovzol** [OpenRA/OpenRA#14138] opened 2017-10-07 12:09 UTC
As far as I know there is no way to suspend the game with more players. If a multiplayer game takes long, all players may want to suspend it and continue it at a later time. It would be nice to save the game as a snapshot and resume it later. Is this feature planned to be implement?

**Comment by pchote** [comment] 2017-10-07 12:17
> Is this feature planned to be implement?

This is a feature that we would all like to include, and there is a plan on how it could be done.
Unfortunately, this feature requires an absolutely huge amount of work, and we simply don't have enough experienced development manpower to be able to actively work on it.

Closing as duplicate of #2743.

**Closed by pchote** 2017-10-07 12:17 UTC

**Comment by kovzol** [comment] 2017-10-07 12:52
Thank you! Good luck on #2743!
