### ISSUE TITLE
sell delay?

### ISSUE THREAD

**Issue by shpookys** [OpenRA/OpenRA#14050] opened 2017-09-18 05:07 UTC
the title is self-explanatory

-basically gives a player the chance to capture structures of a enemy base he has occupied with his army and not have to deal with the BS of having his opponent selling off structures just as hes about to cap it

**Comment by Elizadmin** [comment] 2017-09-18 06:10
It sounds like if you want to capture an enemy building then he has to give it to you ! 😮 

How about a delay to the iron curtain ? Basically gives a player the chance to nuke structures of a enemy base and not have to deal with the BS of having his opponent ICing structures just as hes about to nuke it.

![1248i6](https://user-images.githubusercontent.com/25843400/30530552-d43f5dda-9c47-11e7-9eb0-c048261e2628.jpg)

**Comment by shpookys** [comment] 2017-09-18 07:02
iron curtain does have a charge time maybe add a charge time to sell? :+1:

**Comment by AoAGeneral** [comment] 2017-09-19 00:39
Sell delay would cause some issues with other things such as artillery fire and V2 fire. This also might escalate into having MCVs have a move delay so engineers have a chance to capture these as well which causes the same issues with arty and V2. (As well as nuclear missiles.)

The engineer already locks structures into place and prevents a sell off while it is capturing. Part of the problem is they aren't viable during mid to late game in the competitive scene.

**Comment by CH4Code** [comment] 2017-09-21 21:13
I think he means TD engies. Those enter buildings like commandos and can be killed easily by selling the structure. But, since the new playtest has hit-shapes which should improve commando behaviour, is this a problem in the palytest still, shpooky?

**Comment by AoAGeneral** [comment] 2017-09-21 23:40
The commandos and engineers both enter in by hitshape cells. With the engineers its slightly difficult only because of the 50% requirement. After the release I will be looking (once again) to change this around since currently the engineers are a bit to strong (in TD).

The Commandos however are much stronger because of the hitshapes. By the time the Commando starts to enter and you move your MCV it will die. So this unit got a buff in regard to this.

**Comment by gdavegdave** [comment] 2017-09-24 09:52
@AoAGeneral, previously you wanted to change the TD engi to timer capture because you claimed they were not viable in 1v1. On each occasion, that was poorly received by most players. 

Now you claim that engis are too strong because of hitshapes. They really aren't. They're fine. 

I realise that you played and enjoyed games in the series that did feature timer capture (CnC3?). The same isn't true for others. We must maintain mod differentiation, as per the OpenRA roadmap: "OpenRA should retain the feel and nostalgia of the older games, but remove the frustrating and dated elements."

**Comment by AoAGeneral** [comment] 2017-09-25 05:02
Off topic. Cut pasting to Balance thread.

**Comment by GraionDilach** [comment] 2017-09-25 07:14
In Generals, this "was implemented" as the possibility of still capturing the building while it's selling, in which case the new owner was granted with the sold cash.

**Comment by pchote** [comment] 2018-05-10 17:04
Implementing a sell delay isn't really feasible, so closing.  As mentioned above, I expect that the introduction of hit shapes in 20171014 should have helped a lot here.

**Closed by pchote** 2018-05-10 17:04 UTC
Labels: Balancing, Feature
