### ISSUE TITLE
ground unit (paratrooper?) stuck outside of the map

### ISSUE THREAD

**Issue by mmmh81** [OpenRA/OpenRA#10396] opened 2016-01-03 16:24 UTC
I happened to get a unit outside of the map (upper left corner). I assume it was a paratrooper, but I am not sure. I could not do anything with this unit, neither could the enemy kill it. But it added visibility to the corresponding corner:
![out-of-map unit](https://cloud.githubusercontent.com/assets/12261410/12079569/3cdc7ae4-b23e-11e5-86e5-4ad40db1e545.png)
This is the replay of the game: [OpenRA-2016-01-03T153137Z.zip](https://github.com/OpenRA/OpenRA/files/76654/OpenRA-2016-01-03T153137Z.zip)

**Comment by r34ch** [comment] 2016-01-09 20:16
I think this happens when infantry from a paradrop are unable to spawn from the plane when there isn't enough room. 

Instead they spawn (and I think they stack) at that point.

**Comment by r34ch** [comment] 2016-01-12 19:17
Also, duplicate of #9750

**Comment by abcdefg30** [comment] 2016-01-12 20:00
Closing as duplicate of #9750 then.

**Closed by abcdefg30** 2016-01-12 20:00 UTC
Labels: Bug
