### ISSUE TITLE
Dune 2000 - Crashes on Arch / Gnome-Shell

### ISSUE THREAD

**Issue by Lokke** [OpenRA/OpenRA#9149] opened 2015-08-23 21:20 UTC
When i play D2K on Arch and change the volume via the hardware keys on my notebook the game stops running.

I am running Arch (x64) with Gnome 3.16.2 on an Intel Ironlake Mobile 
##

**Comment by Unit158** [comment] 2015-08-24 00:37
For clarification: the game just hangs? Is it specific to D2K?

**Comment by Mailaender** [comment] 2017-09-02 15:40
Closing as Arch and GNOME Shell have moved on and either way we need more information to find the cause for this. Reopen if this is still a problem.

**Closed by Mailaender** 2017-09-02 15:40 UTC
Labels: Bug, OS: Linux
