### ISSUE TITLE
Add .png support

### ISSUE THREAD

**Issue by Kaito-Kid** [OpenRA/OpenRA#7858] opened 2015-04-04 15:18 UTC
I hate to create shps.

With the 256 colors from temperate.pal you have horrible pictures. You can create your own palette bur it takes very long time and the pictures are not perfect. It takes many of hours to create a good shp from a png file. 

It would be great if you can put png files in OpenRA.
+ Easy created
+ Many colors / good quality
+ Opacity in every color
+ Easy to read / write and modify

![5](https://cloud.githubusercontent.com/assets/5711422/6993244/821eb7ac-daee-11e4-91f6-7db2dbd4a857.jpg)

**Comment by obrakmann** [comment] 2015-04-04 15:21
Duplicate of #5075

**Closed by obrakmann** 2015-04-04 15:21 UTC
