### ISSUE TITLE
Tiberian Dawn - Skirmish game crashed

### ISSUE THREAD

**Issue by DENCHIKTEAM** [OpenRA/OpenRA#19877] opened 2022-01-12 14:51 UTC
## System Information

- Operating System:  Windows 10 Pro x64 20H2
- OpenRA Version: Release-20210321
- OpenRA Mod: Tiberian Dawn
- Source: Official download package
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version release-20210321
Tiberian Dawn mod version release-20210321
on map a8630d3836b63e05c8f981027f49006375725f59 (Trial of Possession by The Echo of Damnation).
Date: 2022-01-12 14:39:58Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: nuyell4.aud is not a valid sound file!
   в OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat)
   в OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   в OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   в OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoiceLocal(Actor self, String phrase, String variant, Single volume)
   в OpenRA.VoiceExts.PlayVoiceLocal(Actor self, String phrase, Single volume)
   в OpenRA.Mods.Common.Traits.Sound.DeathSounds.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   в OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   в OpenRA.Mods.Common.Warheads.DamageWarhead.InflictDamage(Actor victim, Actor firedBy, HitShape shape, WarheadArgs args)
   в OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, WarheadArgs args)
   в OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target& target, WarheadArgs args)
   в OpenRA.GameRules.WeaponInfo.Impact(Target& target, WarheadArgs args)
   в OpenRA.Mods.Common.Projectiles.Bullet.Explode(World world)
   в OpenRA.Mods.Common.Projectiles.Bullet.Tick(World world)
   в OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   в OpenRA.World.Tick()
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   в OpenRA.Game.LogicTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Game.InitializeAndRun(String[] args)
   в OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)


```

**Comment by penev92** [comment] 2022-01-12 14:57
Hello. Can you tell us where you installed your game content from? Is it a Russian version of the original game? Because it looks like one (or more) of the audio files are corrupt or missing.

**Comment by DENCHIKTEAM** [comment] 2022-01-12 15:06
I installed content from virtual images of the original disks, maybe I should download and reinstall the game and check

**Comment by reaperrr** [comment] 2022-01-12 16:59
This is (in all likeliness) a duplicate of #18882 and #18828.
The problem is that some versions of the original C&C use a different audio compression than regular AUD for the nuyell4.aud file (and a few other .aud files in C&C and RA).
@pchote suggested we should simply add support for that compression now that we have access to C&C's audio source code.
Although, as long as nobody with the necessary skills finds the time and motivation to do that before our next release (fwiw, I currently lack all 3), I think we should consider temporarily shipping working versions of the files in question in `bits` to work around this, leaving a potential crash unfixed for that long wouldn't be great.

**Comment by pchote** [comment] 2022-01-12 17:03
I might try and look into that, depending on how long we have before the next playtest.

**Comment by DENCHIKTEAM** [comment] 2022-01-12 17:17
I reinstalled the game and everything seems stable, no crashes, thank you

**Comment by DENCHIKTEAM** [comment] 2022-01-12 17:19
most likely, some file was damaged and did not want to be read, reinstalling helps at least

**Comment by penev92** [comment] 2022-01-12 18:24
Reinstalling from the same source that initially produced the crash? 🤔

**Comment by DENCHIKTEAM** [comment] 2022-01-12 19:34
no I downloaded it again and reinstalled it

**Comment by DENCHIKTEAM** [comment] 2022-01-12 19:35
I played a couple of skirmish fights completely, no errors or crashes
previously, in the middle of the battle, the game just crashes

**Comment by abcdefg30** [comment] 2022-01-12 21:53
Closing as duplicate of #18882 and #18828.

**Closed as completed by abcdefg30** 2022-01-12 21:53 UTC
Labels: Crash
