### ISSUE TITLE
Red Alert AA-guns fire outside their range circle

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#10046] opened 2015-11-20 23:04 UTC
That's the case with any actor to some extent. They are able to fire at targets that are on cells that are only barely inside their range, having the actual target position just outside the range circle.
This, however, I believe is different. Targeting (and range circle rendering) is done based on cells, without any regard for altitude. Here are two screenshots:
First one is of an AA gun firing at a Mig (it was firing at the moment the screenshot was taken because of GPS):
![](http://i.imgur.com/BZTGl2U.png)

And the second one shows two AA guns _not_ targeting the Mig that is supposedly inside their range:
![](http://i.imgur.com/Je38ooh.png)

This undoubtedly affects all anti-air defenses in all mods.
##

**Comment by Mailaender** [comment] 2015-11-22 14:13
Can you check if https://github.com/OpenRA/OpenRA/pull/9874 solves your issue?

**Comment by Mailaender** [comment] 2015-11-22 14:17
Sounds like a duplicate of https://github.com/OpenRA/OpenRA/issues/6185.

**Comment by penev92** [comment] 2015-11-22 14:32
No, the issue here is that the aircraft are *visually* outside the weapon's range, but the targeting code doesn't account for the altitude, and the cell that the aircraft is flying *over* is *inside* the range circle.

**Comment by matjaeck** [comment] 2018-08-13 12:36
I can't reproduce this in playtest-20180729 and assume this got fixed in #10750.

![101](https://user-images.githubusercontent.com/37185497/44032031-31347d9c-9f06-11e8-9c69-266f062d53bb.gif)

**Closed** 2018-08-13 12:48 UTC
Labels: Bug
