### ISSUE TITLE
Red Alert - Engineer capture of MCV cancels bulding production

### ISSUE THREAD

**Issue by Raymond-cnc** [OpenRA/OpenRA#11770] opened 2016-08-05 15:07 UTC
Even if you have a defense ready to be placed it gets cancelled. Bug or feature? Players specifically build engineers on maps with no oil to do an early cancel on your production.

**Comment by StexoO** [comment] 2016-08-05 15:20
Feature !

**Comment by pchote** [comment] 2016-08-05 15:45
Bug.  Duplicate of #8122.

**Closed by pchote** 2016-08-05 15:45 UTC
