### ISSUE TITLE
OpenRA won't start up

### ISSUE THREAD

**Issue by Jamesasthenia** [OpenRA/OpenRA#12006] opened 2016-09-09 15:43 UTC
Everytime I open up OpenRA I get an error message saying it crashed, and once I go to the logs I get this:

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.Sound..ctor(String engineName)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

In the FAQ's it does suggest downloaded the external dependencies however my laptop already has them installed. 
Any suggestions as to what the issue is? I'm not exactly the most tech savy but any help would be greatly appreciated

**Comment by pchote** [comment] 2016-09-09 15:46
This is a known bug that has been fixed for the next release.  The easiest workaround on your end is to install and run the new playtest.

**Comment by Jamesasthenia** [comment] 2016-09-09 15:51
Ok, thanks :)

**Comment by Mailaender** [comment] 2016-09-09 19:28
Duplicate of https://github.com/OpenRA/OpenRA/issues/11874.

**Closed by Mailaender** 2016-09-09 19:28 UTC
Labels: Question
