### ISSUE TITLE
Game freeze without exception

### ISSUE THREAD

**Issue by SIRprise** [OpenRA/OpenRA#16322] opened 2019-03-17 19:28 UTC
### Issue Summary

RA stopped ~10 Min after playing: Graphic was frozen, music continued to play for >1 Minute. CPU load increased.
... ... ...

#### System Information
- **Operating System:** Microsoft Windows 10 Pro (x64) • CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (2.00GHz) • Memory: 7.9 GiB Total (2.4 GiB Free) • Storage: 146.1 GiB / 237.2 GiB (91.1 GiB Free) • VGA: Intel(R) UHD Graphics 620, Radeon (TM) RX 550
- **.NET / Mono Version:** .NET 4.7.03190
- **OpenRA Version:** Release 20190314
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Choose Singleplayer->Skirmish
	2. Choose MAP X-Lake, Choose Spectate
	3. add 4 AI players: 2x rush, 2x normal, 2x soviet, 2x allied
	4. start and wait 15 minutes

[perf.log](https://github.com/OpenRA/OpenRA/files/2975606/perf.log)

**Comment by SIRprise** [comment] 2019-03-17 19:32
Replay:
[OpenRA-2019-03-17T175939Z.zip](https://github.com/OpenRA/OpenRA/files/2975618/OpenRA-2019-03-17T175939Z.zip)

**Comment by SIRprise** [comment] 2019-03-18 20:03
Maybe a duplicate of #16235
I didn't notice a landing plane but perf.log indicates a plane was in the air shortly before crash. The crash behaviour was exactly the same as in #16235 with the difference I used windows.

**Comment by LipkeGu** [comment] 2019-04-25 19:23
maybe the same problem in #16441

**Comment by reaperrr** [comment] 2019-04-25 19:32
That perf.log clearly indicates an infinite Loop in Fly(Attack).
It's quite possible #16369 will fix that.

**Comment by matjaeck** [comment] 2019-04-25 19:59
Might be coincidence but I had a very similar issue on win 10 with my laptop that also has the Intel 620 chip.

**Comment by LipkeGu** [comment] 2019-04-25 21:06
I also tried to reproduce this in bleed with debugger enabled in VS 2019 win10 x64 1903 and the game doesnt crash. im using nvidia a Geforce 760 GT driver version: 388 could this be music related, i did not install the music

**Comment by GraionDilach** [comment] 2019-04-26 10:03
> 
> 
> That perf.log clearly indicates an infinite Loop in Fly(Attack).
> It's quite possible #16369 will fix that.

Sounds like a duplicate of #15948 then.

**Comment by pchote** [comment] 2019-06-30 16:51
This should have been fixed by the activity rework.

**Closed by pchote** 2019-06-30 16:51 UTC
Labels: Crash
