### ISSUE TITLE
F button does not work for Chronotank

### ISSUE THREAD

**Issue by spetsnaz84** [OpenRA/OpenRA#13977] opened 2017-09-03 17:48 UTC
In release-20170527, you can hit the F button for 'deploying' e.g. an MCV. I would expect you can also use this to activate the Chronotank's special ability.
This does not work.

**Comment by GraionDilach** [comment] 2017-09-03 17:53
Duplicate of #13105.

**Comment by netnazgul** [comment] 2017-09-03 18:36
You can also use force move (alt+click) to chrono (multiple tanks at the same time too)

**Comment by pchote** [comment] 2017-09-05 18:55
Closed by mistake? Reopening.

**Comment by Mailaender** [comment] 2017-09-05 18:56
> Duplicate of #13105.

**Comment by pchote** [comment] 2017-09-05 18:56
Ah, my bad.

**Closed by pchote** 2017-09-05 18:56 UTC
Labels: Bug, Red Alert
