### ISSUE TITLE
Desync in AutoTarget TargetedActor

### ISSUE THREAD

**Issue by PanzerFurrry** [OpenRA/OpenRA#12143] opened 2016-10-01 19:40 UTC
Clients crashed for all players in playtest-20160914 on map Barracuda by PizzaAtomica while playing on our dedicated server.
http://imgur.com/iqyFqKx

Exception.log - Player 1 (me, Linux): http://pastebin.com/iV4jkLXT
Syncreport.log - Player 1 (me, Linux): http://pastebin.com/hyR3yxWP

Exception.log - Player 2 (Linux): http://pastebin.com/HAjWriNr
Syncreport.log - Player 2 (Linux): http://pastebin.com/UxEs1BFm

Exception.log - Player 3 (Mac): http://pastebin.com/irp2LJr4

EDIT: As of this moment, new playtest is available, we will try to reproduce the problem again.

**Comment by LipkeGu** [comment] 2016-10-01 19:43
can you test the about an hour released playtest 20161001?

**Comment by PanzerFurrry** [comment] 2016-10-01 20:57
We played two times on the same map, same people, same settings with the new playtest-20161001 without crash.

**Comment by Mailaender** [comment] 2016-10-02 01:33
Diff: https://gist.github.com/Mailaender/22b0acf83b1afe7977956477748d06d3/revisions Thanks for the report. This gives valueable intel.

**Comment by pchote** [comment] 2016-10-30 15:24
This will be a duplicate of #12253, which was fixed by #12260.

**Closed by pchote** 2016-10-30 15:24 UTC
Labels: Crash
