### ISSUE TITLE
Tanya build limit bug

### ISSUE THREAD

**Issue by AzureAnemone** [OpenRA/OpenRA#18057] opened 2020-05-08 17:29 UTC
Putting Tanya in Phase Transport/Ranger will highlight her building bar as of she was buildable, yet pressing it will play a message "Unable to build more"

**Comment by dragunoff** [comment] 2020-05-08 18:39
Duplicate of #5872?

**Comment by abcdefg30** [comment] 2020-05-08 18:57
Yes, closing as duplicate of #5872. Thanks for the report though!

**Closed as completed** 2020-05-08 18:57 UTC
Labels: Bug
