### ISSUE TITLE
Replay is incompatible when opened from the browser

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12466] opened 2016-12-11 10:54 UTC
Now if I open a replay from the browser i get the incompatible message. This used to work but I don't know why it doesn't any longer. But the same file works if you manually place it in the replay folder open the game and play it.
![untitled](https://cloud.githubusercontent.com/assets/7798635/21079648/7ff1880c-bf98-11e6-9a45-822f7b742fc9.png)
![openra game_2016_12_11_11_36_19_519](https://cloud.githubusercontent.com/assets/7798635/21079626/95eecb5c-bf97-11e6-9a39-5af6bb4fa3df.png)

**Comment by RockyTV** [comment] 2016-12-11 17:50
I think this could be caused by temporary files being stored in a "silly" location that messes up with OpenRA's code.

**Comment by Snurre86** [comment] 2016-12-14 21:12
Nope, all temp files are deleted.

**Comment by RockyTV** [comment] 2016-12-19 22:37
Seems like this issue was already fixed in `bleed`, so it should be fixed in an upcoming version. To fix it, just right-click the replay file and remove the read only property from it.

**Comment by Snurre86** [comment] 2017-03-21 21:53
Replay metadata could not be read.

**Comment by rob-v** [comment] 2017-03-21 22:19
What you mean? Is this issue still open? Could you send me link to such replay and OpenRA version?

**Comment by Snurre86** [comment] 2017-03-23 05:47
It is the release 20161019. Site is https://www.gamereplays.org/openra/replays.php?game=92&tab=popular&show=index&tab_new=upcoming

Everyone of them gives me "unavailable map"  from chrome and "Replay metadata could not be read" from FF

Also see: #11149

**Comment by GraionDilach** [comment] 2017-03-23 06:43
I believe this issue should be closed as a wontfix when #12909 gets merged.

**Comment by rob-v** [comment] 2017-03-23 07:24
@Snurre86 Thanks. I can't watch due to unavailable map. I don't know yet how to find out which map it is in general. Anyway, as @GraionDilach wrote, it seems this feature will be removed so I assume we can close this issue.
@GraionDilach Thanks.

**Comment by abcdefg30** [comment] 2020-08-29 18:49
> I believe this issue should be closed as a wontfix when #12909 gets merged.

**Closed by abcdefg30** 2020-08-29 18:49 UTC
Labels: OS: Windows, Regression
