### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#15389] opened 2018-07-26 13:31 UTC
### Issue Summary
Game crashed when I moved a dog as it died

#### System Information
- Ubuntu 16.04 LTS
- Mono JIT compiler version 5.10.1.47 (tarball Tue Apr 17 15:12:35 UTC 2018)
- release-20180307
- Red Alert

#### Additional Information:
- Steps to reproduce
Unsure

- Logs
```
OpenRA engine version release-20180307
Red Alert mod version release-20180307
on map b8d970b58906b86b6de461bef4f273fd52d82f18 (Doublestep by FRenzy, SoScared).
Date: 2018-07-26 13:04:18Z
Operating System: Linux (Unix 4.15.0.29)
Runtime Version: Mono 5.10.1.47 (tarball Tue Apr 17 15:12:35 UTC 2018) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <4bd4dbd20d094f3f8734f677798e9741>:0 
  at OpenRA.Mods.Common.Traits.AttackMoveOrderGenerator.GetCursor (OpenRA.World world, OpenRA.CPos cell, OpenRA.int2 worldPixel, OpenRA.MouseInput mi) [0x0003b] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/AttackMove.cs:174 
  at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget+<GetCursor>c__AnonStorey5.<>m__0 () [0x000ad] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:243 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1[TResult] fn) [0x00043] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Mods.Common.Widgets.WorldInteractionControllerWidget.GetCursor (OpenRA.int2 screenPos) [0x00027] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs:227 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x00091] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x0004d] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x0004d] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Widgets.Widget.GetCursorOuter (OpenRA.int2 pos) [0x0004d] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.RenderTick () [0x000d9] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.Loop () [0x00142] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.Run () [0x00042] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <3903fca0b6764cce95c3a4b1c6c33812>:0 
```

- OpenRA Replays
[dog_crash.orarep.zip @ 4:01](https://github.com/OpenRA/OpenRA/files/2232178/dog_crash.orarep.zip)

- Screenshots & Videos
![selection_011](https://user-images.githubusercontent.com/1582784/43264448-c4283a5e-9118-11e8-86c7-88664a4fb308.png)

- Last frame of orders
```json
{
  "orders": [
    {
      "frame": "2289",
      "order": "{:order_type=>"\xFF", :command=>"CreateGroup", :subject_id=>4, :flags=>4, :target_string=>"410"}",
      "client_name": "i iz experts"
    },
    {
      "frame": "2289",
      "order": "{:order_type=>"\xFF", :command=>"Move", :subject_id=>410, :flags=>65, :target_type=>2, :target_x=>71, :target_y=>34, :target_layer=>"\x00", :target_sub_cell=>0}",
      "client_name": "i iz experts"
    },
    {
      "frame": "2289",
      "order": "{:order_type=>"\xFF", :command=>"CreateGroup", :subject_id=>5, :flags=>4, :target_string=>"460"}",
      "client_name": "Servant"
    },
    {
      "frame": "2289",
      "order": "{:order_type=>"\xFF", :command=>"Attack", :subject_id=>460, :flags=>1, :target_type=>1, :actor_id=>435}",
      "client_name": "Servant"
    }
  ]
}
```

**Comment by pchote** [comment] 2018-07-26 13:33
Closing as duplicate of #14942 which was fixed by #14976.

**Closed by pchote** 2018-07-26 13:33 UTC

**Comment by AMHOL** [comment] 2018-07-26 13:34
My bad

**Comment by pchote** [comment] 2018-07-26 13:34
Nah, it's our bad for still not having shipped the months-old fix!
