### ISSUE TITLE
Ubuntu 19.04 RedAlert crash with 100%CPU Load

### ISSUE THREAD

**Issue by aha-007** [OpenRA/OpenRA#16441] opened 2019-04-23 16:02 UTC
Hello there. I updated to Ubuntu 19.04 and do now have problems with openra.

### Issue Summary
Game crashes after about 10minutes played with 100%CPU Load on the CPU where it runs on.

#### System Information
OpenRA engine version release-20190314
Red Alert mod version release-20190314
on map 6e75b9d1c9f341387e5fdc27843054857a79d55b (Alaska Anarchy Redux by Buddha).
Date: 2019-04-23 15:50:34Z
Operating System: Linux (Unix 5.0.0.13)
Runtime Version: Mono 5.18.0.240 (Debian 5.18.0.240+dfsg-2ubuntu2 Wed Apr 17 23:39:09 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object

#### Additional Information:
- Steps to reproduce

1. Start game, play for about 10 minutes and game crashes with 100%CPU Load @CPU where it startetd
- Logs
[openracrash-19.04.zip](https://github.com/OpenRA/OpenRA/files/3108469/openracrash-19.04.zip)

**Comment by testian** [comment] 2019-04-28 14:46
Your exception stacktrace & behaviour description is similar to mine, especially the fact that it crashes:
  at method OpenRA.Mods.Common.Activities.ResupplyAircraft.OnFirstRun

I can reproduce the issue easily.
I start a skirmish map without opponent (with debug mode in order to get it done faster)
I build a hind or a longbow, forceshoot using Ctrl to a random place on the map until ammo depletes.
The aircraft returns to resupply ammo. That's when the game freezes.



OpenRA engine version release-20190314
Red Alert mod version release-20190314
on map c03e7fe6cf205de831d90175512663ca4a03042f (East vs West by Chris Forbes).
Date: 2019-04-28 14:37:37Z
Operating System: Linux (Unix 5.1.0.6)
Runtime Version: Mono 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 16:37:36 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at System.Collections.Generic.LargeArrayBuilder`1[T].GetBuffer (System.Int32 index) [0x00022] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.LargeArrayBuilder`1[T].CopyTo (System.Collections.Generic.CopyPosition position, T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00041] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].CopyTo (T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00035] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].ToArray () [0x00028] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].LazyToArray () [0x00048] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].ToArray () [0x00016] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at OpenRA.Mods.Common.Activities.ResupplyAircraft.OnFirstRun (OpenRA.Actor self) [0x000de] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs:45 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x00050] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Actor.Tick () [0x00010] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.World.Tick () [0x00046] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00237] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.Loop () [0x000d6] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.Run () [0x00042] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <f69fafde25414782b71cd55dd1b3d620>:0

**Comment by testian** [comment] 2019-04-28 14:55
Some new info: I wasn't able to reproduce this with OpenRA built from the bleed branch.
Maybe it was fixed?! I'll see if i can bisect an cherrypick something...

**Comment by testian** [comment] 2019-04-28 18:45
Commit https://github.com/dragunoff/OpenRA/commit/8191a6566b74f016e7d6fe7f2478b13a1dc36c2e fixes the issue for me. I can even cherry pick it and apply it to release-20190314 (with some manual adjustments to satisfy conflicts and compiler) and I can no longer reproduce it. Let's see how it behaves generally.

**Comment by pchote** [comment] 2019-04-28 19:04
Great news. Closing this issue as fixed.

**Closed by pchote** 2019-04-28 19:04 UTC
Labels: Crash, OS: Linux

**Comment by testian** [comment] 2019-04-28 19:56
I just had a crash anyway in a network game.. but somehow i first had a mod-incompatibility message before i could enter the lobby and I had to restart the game so now I don't know exactly if the crash happened under genuine circumstances

aha-007 says it no longer works for him since upgrading.. maybe there is some red herring and the cherrypicked patch that I applied is only mixing the cards.. I will try to understand it a little bit better.

**Comment by testian** [comment] 2019-04-28 21:26
Oooook: I found yet another fix - and maybe that fix is more reliable.. (I will go and test it in network games now) and maybe the fix I found earlier is just a red herring.

I got mono from the official Debian repositories and (and aha-007 from official Ubuntu repositories, I suppose) and that configurations seems to lead to the crash with the latest release.

I now installed the Debian packages provided by the mono-project directly (Basically like the OpenRA website suggests) and this solves the issue as well and I don't need to cherry-pick above commit.

https://www.mono-project.com/download/stable/#download-lin-ubuntu

$ mono --version
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019)

**Comment by testian** [comment] 2019-04-29 15:08
I was now able to complete a naval network game with plenty of aircrafts without crash.
I conclude that installing the most recent mono packages from mono-project.com (version 5.20) instead of the native packages in Debian Buster respectively Ubuntu 19.04 (version 5.19) reliably fixes this issue.

**Comment by pchote** [comment] 2019-04-29 15:32
The next release will be shipping our own mono runtime inside the AppImage, so still fixed :)

**Comment by cocoonairs** [comment] 2019-08-22 14:57
Hi. I have the same problem on my Laptop (i5 8250U) - RedAlert freezes when an airplane lands to reload ammo. I am using the newest release (20190314). Using Debian Buster, however mono-version 5.18.

Any advice how to fix my issue. Missing a good game. :-) Thanks.

**Comment by pchote** [comment] 2019-08-22 15:38
The version of mono packaged by Debian contains a serious bug that causes this crash in OpenRA and other software. Switch to the upstream mono packages from https://www.mono-project.com/download/stable/#download-lin to fix the issue.

**Comment by aha-007** [comment] 2019-08-22 16:31
Thanks for your good support. Updated Mono and everything works smoothly now.

Kind regards,

Andre

**Comment by cocoonairs** [comment] 2019-08-22 16:40
Thanks also from me. Updated to Mono 6 and first test went smoothly. Seems to be working!! :-)
