### ISSUE TITLE
Tanks able to drive forward and backwards

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#15017] opened 2018-04-05 11:56 UTC
It would be nice if tanks can move both directions not just forward.

**Comment by CatGirls420-NerevarII** [comment] 2018-04-10 18:11
This would let tanks retreat much easier with the current unit pathing dilemma.

**Comment by TehStex** [comment] 2018-04-11 16:51
[THIS ?](https://github.com/OpenRA/OpenRA/issues/4968#issuecomment-38682655)

🙄

**Comment by matjaeck** [comment] 2018-08-12 21:14
Duplicate of the issue referenced above.

**Comment by pchote** [comment] 2018-08-12 21:46
Closing as duplicate.

**Closed by pchote** 2018-08-12 21:46 UTC
Labels: Feature, Idea/Wishlist
