### ISSUE TITLE
Production widget for specs

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#10783] opened 2016-02-20 00:37 UTC
[In a recent video by SoScared on Youtube](https://youtu.be/0IDixZguIP0?t=323) he overlaid the production breakdown on the top left of the screen, it would be cool to see this as a built in feature, and show all players when you're in the all players/disable shroud perspective and only the player you're in perspective of when viewing from player perspective.

**Comment by AMHOL** [comment] 2016-02-20 00:38
In addition to this it would be cool to have more general widgets for specs, i.e. a statistics box under the minimap that can be hidden/expanded, with a dropdown to choose which tab to view.

**Comment by obrakmann** [comment] 2016-02-20 21:21
Duplicate of #5121

**Closed by obrakmann** 2016-02-20 21:21 UTC
Labels: Feature, UI
