### ISSUE TITLE
predetermined loop or patrol between multiple points

### ISSUE THREAD

**Issue by lou-xia** [OpenRA/OpenRA#21616] opened 2024-10-10 11:09 UTC
## Motivation
In the current gameplay of OpenRA, I noticed that there is no option for units to follow a looped path or set up a patrol between multiple points. This is a limitation that could reduce strategic options for players, especially in defense or surveillance scenarios. Having a looped pathing or patrol feature would make it easier to manage unit movements, without the need for constant micromanagement.

## Proposed solution
I propose adding a feature that allows players to assign units to follow a looped route. This could be implemented by clicking on the previous path point in Waypoint Mode, just like the traditional RA2. This would improve the strategic depth of the game, especially in base defense or reconnaissance.

**Comment by PunkPun** [comment] 2024-10-11 12:40
duplicate of #10470

we are unlikely to implement persistent ones, see #21531 for a demo of a temporary path

**Closed as not planned by PunkPun** 2024-10-11 12:40 UTC
Labels: Idea/Wishlist
