### ISSUE TITLE
Bug: All Projectiles Pass Through Cliffs/Interior Walls 

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#16380] opened 2019-04-03 03:50 UTC
### Issue Summary

-**Issue:** All land projectiles pass through interior map walls and most pass through cliffs.

In the original version of Red Alert: most land projectiles (flames and grenades especially) could not hit through cliffs (terrain with cliffs that obstruct targets on the opposite side). 

When interior maps were involved: Facility walls (interior walls) stopped **all** projectiles. 

In OpenRA: **All** projectiles pass through solid walls and concrete walls (both in missions and in skirmish).

In regards to missions, the lack of collisions with walls is somewhat game-breaking since there's parts of some missions that involve units that need to hide behind walls to avoid getting hit by flame towers and tanks.

Outdoors: The only things that *should* be able to fire 'through' cliffs are tesla bolts, artillery units (artillery, V2s, cruisers, etc) while vehicles can fire at least 1 to 2 tiles ahead of a cliff if they're on the low end of the cliff.

Indoors: Nothing should be able to fire through the walls.

The only 'projectiles' that should be able to pass through walls are grenades **but** this would only apply with the "brown walls" seen in some missions that aren't in the game's tile sets yet (at least I don't think they are).

*here's a video with the grenade walls: https://youtu.be/1bC52u8Y2OY?t=187
*timestamped around the 3 minute mark
*note how the units never engage each other until they're directly within each others line of sight (throughout the entire video)

... ... ...

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:** Not sure.
- **OpenRA Version:** release-20190314
- **Mod:** Red Alert

- Logs

- Screenshots & Videos
Here's a video to show how projectiles should work with unit peripheral views (just in case you guys need to see it): https://www.youtube.com/watch?v=lSkXTItM014 

![cliff collisions](https://user-images.githubusercontent.com/25542788/55445035-69791680-5587-11e9-9ded-f4496b0de383.png)
![cliff collisions](https://user-images.githubusercontent.com/25542788/55445463-84e52100-5589-11e9-82a5-509a54e2484d.png)

**Comment by Smittytron** [comment] 2021-05-03 14:03
Closing as working as intended.

> In the original version of Red Alert: most land projectiles (flames and grenades especially) could not hit through cliffs (terrain with cliffs that obstruct targets on the opposite side).

This is incorrect. I tested the original and it behaves the same as OpenRA.

**Closed by Smittytron** 2021-05-03 14:03 UTC
Labels: Feature
