### ISSUE TITLE
MoveWithinRange gets blocked by friendly units who shares cell

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13512] opened 2017-06-15 14:38 UTC
On theory, infantries share cells with friendly units but in practice, they block someone's way who is doing MoveWithinRange

https://youtu.be/MyU3n966C2Y

* If I remove Tanya and retry attack dog leaps as expected
* If I move Tanya when it is stuck in MoveWithinRange state, the unit stays still, stuck in MoveWithinRange

**Comment by GraionDilach** [comment] 2017-06-15 15:08
Sounds like a duplicate of #5841 to me.

**Closed** 2017-06-19 14:57 UTC
