### ISSUE TITLE
SD "O" cell (passable but not stoppable) - Unit still can idle on those cells. (

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17889] opened 2020-04-01 15:24 UTC
This is 2 bug in one related to https://github.com/OpenRA/OpenRA/pull/17141

## Issue Summary
The service depot has now cells you can pass through but not stop or idle. there is 2 way where unit can stop and idle on those cells.

1) Unit idle and become uncontrollable on those cells when a unit is under repair
2) Unit can stop and idle on those cell after an attack order and a stop order

## Reproduction
1)
![bug cell](https://user-images.githubusercontent.com/28893854/78158837-080db100-7442-11ea-92dd-6163bda4477a.gif)
a) Send several tanks to repair
b) Be sure to be broke so the repair never ends
c) Once a tank is under repair, 2 other tanks will come and block 2 cells they should not waiting their turn
d) Try to control those two tanks independently, they don't respond to move command
e) if you select all the tank including the one under repair, you can "unlock" them.

2)
![bug cell2](https://user-images.githubusercontent.com/28893854/78158887-1a87ea80-7442-11ea-915e-bb13f6c74ee1.gif)
a) Send several tanks to repair or just move across the sd
b) while they are entering/passing through the sd, issue a force fire order
c) Issue a stop order
d) tank will stop and idle on cell they should not

## Expected behavior
they should stay out of those cells or leave them asap

both issues are minor, if it can't be fixed before the release it is not problem as it is very circumstantial.

**Comment by adammitchelldev** [comment] 2020-04-07 16:30
Initially, I don't think the tanks are actually idle, the are currently in the `Approaching` state but can't complete their moves into the service depo because it becomes occupied when they are on the transit only tiles. Problem A is that there is no logic here to dictate that they need to move to a stoppable cell, the `MoveAdjacentTo` move type doesn't appear to implement it because it is not necessarily a stopping move.

~~I believe the logic that causes them to stick is because something (possibly `ReturnToCellActivity.Cancel`) expects moving on the spot to shift the Actor to a valid position, which it won't. `ReturnToCell` is also non-interruptible, which might explain why it fails to stop, although I've not stepped through a reproduced example yet.~~ I'm now more certain that this is all `Move` and `MoveAdjacentTo` having states where they can't progress due to the SD being full, but the `Move` can't be cancelled either because the tank isn't on a cell it can stay on. Moving the tank on the SD fixes the lock.

I think the more general problem here is the implementation of transit-only tiles is as as a "parent activity concern" rather than a move-level property. Any activity which does a move that thinks it might be a stopping move needs to additionally consider that, when cancelled, it shouldn't stop on a transit only tile. Really, if this is going to be tight, the move should know whether or not it is allowed to stop on the given tile.

I'd suggest we need some way for a move to know what is coming next, basically whether or not it can actually stop on a `CanStayInCell` tile. At the very least, if the move is going to be cancelled, it needs to check that its final position is a valid stopping cell.

**Comment by adammitchelldev** [comment] 2020-04-07 16:57
In the second case, I just don't think that the cancel logic is bulletproof for `Move`, it works by clearing the current path, but only if `CanStayOnCell` is true for its current position. If `MoveAdjacentTo` or similar is also used for moving into firing range, the tank can have its destination set to a transit-only tile, so when the path is cleared, there's nothing to tell the unit to move off of the current cell. I think perhaps an expectation is that when it enters idle it checks again? But then again, I think there's an issue here with it getting stuck in one of these positions and unable to be freed.

**Comment by pchote** [comment] 2020-04-07 17:05
It sounds like major surgery may be needed to fix this. We should instead consider reverting the service depot / Resupply footprint changes as a lower risk solution for the release.

It sounds like #17849 and the TS bibs are fine because they are never targets for docking orders?

**Comment by pchote** [comment] 2020-04-07 17:54
@tovl do you have any thoughts on simpler solutions here?

**Comment by adammitchelldev** [comment] 2020-04-07 18:35
I think the general problem here is that `Move` could fail to cancel if the target is on a transit only space, and might be solvable by some extra logic to ensure it doesn't get stuck if the path is blocked or that if it ends on a transit only space due to a cancelled "dynamic" move order, it moves the unit off of it.

**Comment by adammitchelldev** [comment] 2020-04-07 19:50
Issue number 2 is simple to reproduce, you only need one tank. Just need to force fire slightly out of range so that the tank moves into onto the cell and stops to start firing. Once it is firing, issue a stop order and it's stopped on the space.

Issue is that attacking uses `MoveWithinRange`, which is just a subclass of `MoveAdjacentTo` that stops when it's within range. `MoveAdjacentTo` actually cancels the `Move` order as soon as it is within range (as defined by `MoveWithinRange`), but `Move` simply avoids clearing its path:
```C#
		public override void Cancel(Actor self, bool keepQueue = false)
		{
			// We need to clear the path here in order to prevent MovePart queueing new instances of itself
			// when the unit is making a turn.
			if (path != null && mobile.CanStayInCell(mobile.ToCell))
				path.Clear();

			base.Cancel(self, keepQueue);
		}
```
The path is actually already empty here, so the unit stops on the cell that it is not meant to stay on. The move order is then successfully finished because either its path count is zero or it's at its destination (in this case, both):
```C#
		public override bool Tick(Actor self)
		{
			// ...
			if (IsCanceling && mobile.CanStayInCell(mobile.ToCell))
			{
				if (path != null)
					path.Clear();

				return true;
			}

			// ...

			if (destination == mobile.ToCell)
				return true;

			if (path.Count == 0)
			{
				destination = mobile.ToCell;
				return false;
			}

```

`MoveAdjacentTo` is used **directly** by `Enter`, one of the only places to use it, debugging that now.

**Comment by adammitchelldev** [comment] 2020-04-07 20:15
![Screenshot 2020-04-07 at 21 08 46](https://user-images.githubusercontent.com/1878992/78714618-195c2f00-7914-11ea-8a72-801fd31e41c1.png)
![Screenshot 2020-04-07 at 21 08 59](https://user-images.githubusercontent.com/1878992/78714628-1c571f80-7914-11ea-87f3-d5bba2e3a23e.png)

First issue is reproducible with only 2 tanks. Ensure both are damaged. Send one to the SD, and at any time before or after it arrives, send the other. It will get stuck attempting to enter the SD and be unable to move. Issue is that `PopPath` will never gives us an alternative cell, so it's stuck trying to cancel the move when it can't (the first part of `Tick` doesn't allow it to cancel if it's on a transit space, but there's no other code path that would return true in the situation).

**Comment by tovl** [comment] 2020-04-08 00:19
>  @tovl do you have any thoughts on simpler solutions here?

Yes. The second issue is solved by adding the following to `Mobile.OnBecomingIdle`:

```
if (!Locomotor.CanStayInCell(self.Location))
{
     self.QueueActivity(MoveTo(self.Location, evaluateNearestMovableCell: true));
     return;
}
```
This then also makes it redundant to make the cancelling of `Move` conditional on `CanStayInCell`. Removing that condition mostly solves the first issue as well. The units will still wait on a cell they shouldn't, but they won't be uncontrollable.

The best way to make sure units won't want to wait for their turn on the repair pad in those cells in the first place is to actually implement the concept of waiting for their turn, i.e. to implement reservation logic for repair pads. The lack of that doesn't strike me as a release-blocking issue though, as long as the issue of those units becoming uncontrollable is fixed.

**Comment by adammitchelldev** [comment] 2020-04-08 14:29
@tovl 
> The best way to make sure units won't want to wait for their turn on the repair pad in those cells in the first place is to actually implement the concept of waiting for their turn, i.e. to implement reservation logic for repair pads.

This matches the logic I'm familiar with in RA2, not sure about RA. It's definitely a better solution but the idea that certain moves can stop on a transit-only cell is still a potential problem (easy to do with force-fire).

RE: your solution. I like it but here's an alternative that's more complete but might be do-able: Maybe some logic could also be added to `Move` that scans the path ahead if the next tiles are transit-only? In the case that the exit is blocked, it can select a nearby valid tile to wait on until it becomes unblocked, rather than just stopping. It's effectively an extension to the current blocking detection and waiting, and would (should) cover all move types that might not otherwise respect transit-only tiles. Would also mean the OnIdle logic wouldn't be required.

In case 1, the tank would realise that it can't get to the resource depot that it wants to and wait before entering the transit-only tiles, or if it was currently on the tile then it would move off first.

In case 2, the tank would evaluate its path over the transit-tile, rather than only onto it, so it would have a path to continue following when the move order is cancelled due to being in range to attack. In any other case where the tank would end up on the tile, at least cancelling the move order would work.

**Comment by pchote** [comment] 2020-04-08 16:41
> the idea that certain moves can stop on a transit-only cell is still a potential problem (easy to do with force-fire).

This can/should be fixed by making `MoveAdjacentTo` and `MoveWithinRange` understand that they are not valid stopping locations:
```diff
diff --git a/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs b/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
index 7f83636d37..6561f8a15d 100644
--- a/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
+++ b/OpenRA.Mods.Common/Activities/Move/MoveAdjacentTo.cs
@@ -78,7 +78,8 @@ protected virtual bool ShouldRepath(Actor self, CPos targetLocation)
 
                protected virtual IEnumerable<CPos> CandidateMovementCells(Actor self)
                {
-                       return Util.AdjacentCells(self.World, Target);
+                       return Util.AdjacentCells(self.World, Target)
+                               .Where(c => Mobile.CanStayInCell(c));
                }
 
                protected override void OnFirstRun(Actor self)
diff --git a/OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs b/OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs
index 0dfae9694d..c79ac68951 100644
--- a/OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs
+++ b/OpenRA.Mods.Common/Activities/Move/MoveWithinRange.cs
@@ -33,13 +33,13 @@ protected override bool ShouldStop(Actor self)
                {
                        // We are now in range. Don't move any further!
                        // HACK: This works around the pathfinder not returning the shortest path
-                       return AtCorrectRange(self.CenterPosition) && Mobile.CanInteractWithGroundLayer(self);
+                       return AtCorrectRange(self.CenterPosition) && Mobile.CanInteractWithGroundLayer(self) && Mobile.CanStayInCell(self.Location);
                }
 
                protected override bool ShouldRepath(Actor self, CPos targetLocation)
                {
                        return lastVisibleTargetLocation != targetLocation && (!AtCorrectRange(self.CenterPosition)
-                               || !Mobile.CanInteractWithGroundLayer(self));
+                               || !Mobile.CanInteractWithGroundLayer(self) || !Mobile.CanStayInCell(self.Location));
                }
 
                protected override IEnumerable<CPos> CandidateMovementCells(Actor self)
@@ -49,7 +49,7 @@ protected override IEnumerable<CPos> CandidateMovementCells(Actor self)
                        var minCells = minRange.Length / 1024;
 
                        return map.FindTilesInAnnulus(lastVisibleTargetLocation, minCells, maxCells)
-                               .Where(c => AtCorrectRange(map.CenterOfSubCell(c, Mobile.FromSubCell)));
+                               .Where(c => Mobile.CanStayInCell(c) && AtCorrectRange(map.CenterOfSubCell(c, Mobile.FromSubCell)));
                }
 
                bool AtCorrectRange(WPos origin)
```

As a side note, we should also fix the code style issue of `CanStayInCell` not having an initial `self` parameter.

<hr>

> This then also makes it redundant to make the cancelling of `Move` conditional on `CanStayInCell`. 

This risks regressing any cases where `Move` is a child activity that is cancelled by a parent without the unit going idle.

**Comment by adammitchelldev** [comment] 2020-04-08 17:48
```C#
              protected virtual IEnumerable<CPos> CandidateMovementCells(Actor self)
                {
-                       return Util.AdjacentCells(self.World, Target);
+                       return Util.AdjacentCells(self.World, Target)
+                               .Where(c => Mobile.CanStayInCell(c));
                }
```

@pchote This method will break in the case that a target is surrounded by transit-only tiles. No tiles will be returned and `MoveAdjacentTo` will be unable to calculate a path at all, which I'm not sure is always the desired behaviour.
```C#
	foreach (var cell in CandidateMovementCells(self))
					if (domainIndex.IsPassable(loc, cell, Mobile.Info.LocomotorInfo) && Mobile.CanEnterCell(cell))
						searchCells.Add(cell);
			}

			if (!searchCells.Any())
				return NoPath;
```

I don't think targets being surrounded with transit-only is technically possible with structure layouts right now? So in practice it probably works fine.

**Comment by pchote** [comment] 2020-04-08 18:37
IMO the desired behaviour here should be that `MoveAdjacentTo` behaves the same way if surrounded entirely by transit-only cells as it does when surrounded by unpathable cells. In both cases the unit is not allowed to end up in those places.

**Comment by adammitchelldev** [comment] 2020-04-08 19:16
Well in that case the logic for `Resupply` should probably be reworked not to use it, since SD is the building with transit-only cells.

**Comment by pchote** [comment] 2020-04-08 19:26
The checks are made on the cells surrounding the SD, not the SD cells themselves!

**Comment by adammitchelldev** [comment] 2020-04-08 19:50
Ah of course!

**Comment by pchote** [comment] 2020-04-10 20:38
@adammitchelldev did you still want to try and put together a PR to fix this?

**Comment by adammitchelldev** [comment] 2020-04-11 15:01
> @adammitchelldev did you still want to try and put together a PR to fix this?

Yeah, sure, will do that.

**Comment by adammitchelldev** [comment] 2020-04-11 15:04
> The checks are made on the cells surrounding the SD, not the SD cells themselves!

@pchote Are we sure this is true? I need to look into it harder but if this was the case, surely this bug wouldn't happen because the transit tiles would count as part of the footprint?

**Closed as completed** 2020-04-17 09:13 UTC
Labels: Bug
