### ISSUE TITLE
Getting a System Overflow exception

### ISSUE THREAD

**Issue by DoGyAUT** [OpenRA/OpenRA#11026] opened 2016-04-02 19:40 UTC
Since updateing my OpenRA I get those system overflow exceptions.

https://github.com/OpenRA/OpenRA/blob/a29b9ff7bede856b975ef69600c445513327736a/OpenRA.Game/WPos.cs#L68 

http://pastebin.com/zpnvNMRY

**Comment by obrakmann** [comment] 2016-04-02 20:24
33f26e05e148aa284929666077beaf7913106e0f from #10972 touched that just a few days ago.

**Comment by obrakmann** [comment] 2016-04-02 20:30
Crash happens when `WPos.LerpQuadratic` is called with these arguments:
```
args.Source: 32512,75392,1536
target: 30730,79682,1536
angle: 256
ticks: 20
length: 58
```

**Comment by pchote** [comment] 2016-04-03 08:21
This is caused by the `angle: 256`, which is bogus (it indicates a projectile fired vertical, which can never hit anything except the target).  This should be fixed in two ways:
* Clamp the angle to the range 0 <= angle < 256 in `LerpQuadratic` (both of them).
* Add a lint check to statically validate the projectile properties.

**Comment by reaperrr** [comment] 2016-04-05 14:46
The debris in TS currently have maximum angles of `264`, which will also trigger this.

**Comment by UnknownProgrammer** [comment] 2016-08-15 20:14
An angle of 256 results in a pitch.Tan() lookup of the value int.MaxValue. That value is then multiplied and other values are added and becomes even bigger. If this big decimal value is casted to int it raises an exception.
The bug is very annoying, because it forces the game to crash most of the time in the late game when the base is already built.
I wrote a fix to limit the offset to int.MaxValue respectively int.MinValue. Replace the `LerpQuadratic()` function in `WPos.cs` with the following code and this exception won't ruin your game again:

    public static WPos LerpQuadratic(WPos a, WPos b, WAngle pitch, int mul, int div)
    {
      // Start with a linear lerp between the points
      var ret = Lerp(a, b, mul, div);

      if (pitch.Angle == 0)
          return ret;

      var tempoffset = (decimal)(b - a).Length * pitch.Tan() * mul * (div - mul) / (1024 * div * div);

      var offset = (int)Math.Min(Math.Max((decimal)int.MinValue, tempoffset + (decimal)ret.Z), (decimal)int.MaxValue);

      return new WPos(ret.X, ret.Y, offset);
    }

I Just wanted to share it, but I can create a PR if there is a need for it.

**Comment by GraionDilach** [comment] 2016-08-15 20:34
Yes, a PR would be better for crediting purposes.

**Comment by UnknownProgrammer** [comment] 2016-08-15 21:01
Created a PR #11821

**Comment by pchote** [comment] 2016-08-15 21:12
Good idea making the code robust, but we'll still want a lint test checking for 0 <= angle < 255 because values outside that range are logically bogus.

**Comment by jvdgroup** [comment] 2016-10-18 14:24
I guess I have the same problem with the latest release:

```
Red Alert Mod at Version release-20160508
on map bef6071277b36ec28890493ff89ab9bf478f05b9 (Raraku_Pumpuilla by Jopani Kansaro).
Operating System: OSX (Unix 15.6.0.0)
Runtime Version: Mono 3.12.0 ((detached/a813491) CLR 4.0.30319.17020
Exception of type `System.OverflowException`: Value is too small.
  at System.Math.Abs (Int32 value) [0x00000] in <filename unknown>:0 
  at OpenRA.WAngle.ArcTan (Int32 y, Int32 x, Int32 stride) [0x00000] in <filename unknown>:0 
  at OpenRA.WAngle.ArcTan (Int32 y, Int32 x) [0x00000] in <filename unknown>:0 
  at OpenRA.WVec.get_Yaw () [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.Turreted.FaceTarget (OpenRA.Actor self, Target target) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.AttackTurreted.CanAttack (OpenRA.Actor self, Target target) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.AttackBase.DoAttack (OpenRA.Actor self, Target target, IEnumerable`1 armaments) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Traits.AttackFollow.Tick (OpenRA.Actor self) [0x00000] in <filename unknown>:0 
  at OpenRA.World.<Tick>m__3 (TraitPair`1 x) [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) System.Action`1<OpenRA.TraitPair`1<OpenRA.Traits.ITick>>:invoke_void_T (OpenRA.TraitPair`1<OpenRA.Traits.ITick>)
  at OpenRA.WorldUtils.DoTimed[TraitPair`1] (IEnumerable`1 e, System.Action`1 a, System.String text) [0x00000] in <filename unknown>:0 
  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Any update on this?

**Comment by reaperrr** [comment] 2016-10-18 18:08
> Red Alert Mod at Version release-20160508

That's not the latest release (we released 20161015 a few days ago).

**Comment by jvdgroup** [comment] 2016-10-18 18:22
> That's not the latest release (we released 20161015 a few days ago).

Oh, that's true, I pasted the wrong log file. Here's the proper one:

```
Red Alert Mod at Version release-20161015
on map b9fef174ff11c0f0a93288c7fd1c0c676bd9926b (Suden Tukka™ by Jopani Kansaro).
Date: 2016-10-18 13:03:15Z
Operating System: OSX (Unix 15.6.0.0)
Runtime Version: Mono 3.12.0 ((detached/a813491) CLR 4.0.30319.17020
Exception of type `System.InvalidOperationException`: Out of sync in frame 7962.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (Int32 frame) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager+<TickImmediate>c__AnonStorey0.<>m__0 (Int32 clientId, System.Byte[] packet) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.EchoConnection.Receive (System.Action`2 packetFn) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

The same crash happened two times in two consecutive games, and then we resorted back to the older release (20160508). There's also the syncreport file, you can find it here if it's of any help:

https://www.dropbox.com/s/uoqtr0y94aa89nh/syncreport-2016-10-18T130315Z.log?dl=0

**Comment by GraionDilach** [comment] 2016-10-18 18:24
That has nothing to do with this ticket though.

**Comment by jvdgroup** [comment] 2016-10-18 18:25
> That has nothing to do with this ticket though.

That's also true. I'll try and find if there's an open issue or if not, open one. Thanks for the help.

**Comment by reaperrr** [comment] 2018-05-04 09:52
>    Clamp the angle to the range 0 <= angle < 256 in LerpQuadratic (both of them).
    Add a lint check to statically validate the projectile properties.

This was fixed quite some time ago. Closing.

**Closed by reaperrr** 2018-05-04 09:52 UTC
Labels: Crash
