### ISSUE TITLE
Activities break on intercepting and killing enemy when they are expected to continue

### ISSUE THREAD

**Issue by lovalmidas** [OpenRA/OpenRA#13018] opened 2017-03-24 03:52 UTC
Several actor commands that is expected to continue are interrupted and the activity assumed complete when the interruption is resolved. This results in significantly different behaviour from their counterparts on the original games.

Hunt() - Breaks after killing one enemy (Expected: continue Hunt)
AttackMove() - Breaks after killing one enemy (Expected: continue AttackMove until waypoint is reached)
Guard() - Breaks after killing one enemy (Expected: continue Guard)

By 'break', I mean the action is deemed complete and the actors moves on to the next activity.

Patrol() and PatrolUntil() are also affected since they are based on a AttackMove()-Wait() loop. Actors will go to the next waypoint, skipping his/her current waypoint if an enemy is intercepted.

-----------------------------------

**To reproduce:**

Give an actor a _single_ command using an Lua script. Then throw an enemy in its path.

Hunt():
 Actor will hunt for one actor and attack it. Then it will become Idle.

AttackMove():
 Actor will move towards the target location and attack the first enemy it sees. Then it will become Idle.

Guard():
 Actor will move towards the target actor and attack the first enemy it sees. Then it will become Idle.

-----------------------------------

This forces scripters to create their own custom scripts to ensure such activity 'resumes'. This is seen in current campaigns and Lua customised maps across all mods. 

**Case example:**
If you have noticed, almost every mission in the RA mod defines their own IdleHunt and PatrolLoop Lua functions. As they heavily rely on OnIdle script triggers, I expect aircrafts to handle this badly. #13015

-----------------------------------

There exists the possibly of scripters viewing the interruptions as features.

As a solution exists by re-creating the logic on Lua, I would like some word from the devs if the current implementation should be the maintained.

Edit: Engrish.
Edit 2: Clarity.

**Comment by abcdefg30** [comment] 2017-03-24 16:06
I always thought that's the expected behaviour for hunting. Anyway, for guarding also see #11439.

**Comment by GraionDilach** [comment] 2017-03-24 18:44
As said, in the WW games, hunting meant "find all enemy units on the map and destroy them" automatically and was mostly seen in nonshortgames when the AI sold everything for it's final rush.

**Comment by obrakmann** [comment] 2017-03-24 21:17
Duplicate of #7454.

**Comment by GraionDilach** [comment] 2017-03-25 05:48
That strictly is about Lua while the cases apply to actual orders as well ordered by the player.

**Comment by reaperrr** [comment] 2017-06-29 09:45
I can actually confirm this issue, while testing my WeaponStrafing branch I noticed that more often than not, the Yak starts to idle after killing a target instead of returning to the airfield.

**Comment by reaperrr** [comment] 2017-06-29 09:50
What all of these have in common is that things are interrupted when a target is killed, so the bug might be in the attack code.

It's also annoying enough that this should be fixed by next release at latest, ideally before the playtest.

**Comment by pchote** [comment] 2017-06-29 12:54
If someone can provide a reduced testcase in the form of a replay (ideally using a custom map with *only* this bug being shown) then it will be much easier to identify and fix the issue.

**Comment by duy5167** [comment] 2017-06-29 13:03
yeah if you guy do that some know c progam can help fix it with you guy

**Comment by duy5167** [comment] 2017-06-29 13:05
some play this game

**Comment by reaperrr** [comment] 2017-06-29 14:37
@pchote branch: https://github.com/reaperrr/OpenRA/tree/activity-break-test

I was too lazy to upload it somewhere else, so I stuffed the replay file in the lua folder (last commit).

**Comment by forcecore** [comment] 2017-06-29 17:36
This one will be tough to fix.
Anything that invokes attack move gets its activity queue reset.

In attackbase.cs, in InnterTick,

public void AttackTarget(Target target, bool queued, bool allowMove, bool forceAttack = false) function is called as a non-queued move so

		if (!queued)
			self.CancelActivity();

It cancels everything. It should only cancel necessary part of the activity graph.

**Comment by pchote** [comment] 2017-06-29 18:04
I'm really not keen on rewriting yet another major part of our combat/activity code as a prereq for the next release.  The current bleed-master delta has already grown beyond what is reasonably manageable.

**Comment by reaperrr** [comment] 2017-06-29 19:07
> I'm really not keen on rewriting yet another major part of our combat/activity code as a prereq for the next release. The current bleed-master delta has already grown beyond what is reasonably manageable.

Ok, I wrote that hoping this is 'just' a bug that is easy to fix once discovered.

**Comment by obrakmann** [comment] 2017-06-29 19:39
Sorry for sounding harsh, but this all isn't exactly new, and I explained the problems related to attack-move and activities quite a few times already.  The fact is, `AttackMove` only ever works correctly when it is invoked by a player. It *just will not work as expected* when you just call the activity, be it in C# code or in Lua scripts, because it doesn't do enough. I explained why with these [two](https://github.com/OpenRA/OpenRA/issues/7454#issuecomment-73757364) [comments](https://github.com/OpenRA/OpenRA/issues/7454#issuecomment-107056625). https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:activities-pt3 will fix this eventually.

Also, again, calling `self.CancelActivity()` *anywhere* besides the code that handles the `Stop` command (plus a handful of exceptions, such as the Lua method with the same name or evaluating non-queued orders), is a bug. Hence [this comment](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Activities/Activity.cs#L40).

And this is still a duplicate of #7475.

**Comment by reaperrr** [comment] 2017-06-29 20:19
Sorry, I should have looked past the issue title of #7454. I also hadn't noticed the issue to this extent until I tested my WeaponStrafing branch, so I wasn't aware that this is such an old issue (I rarely ever queue orders or play RA, so I guess I didn't run into it often enough to really notice).

Re-closing as duplicate then.

**Closed by reaperrr** 2017-06-29 20:19 UTC
Labels: Bug, Scripting
