### ISSUE TITLE
AttackTurreted with FacingTolerance >128 may ignore targets remaining outside of it's arc

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18316] opened 2020-06-21 12:40 UTC
FacingTolerance doesnt function properly for AttackTurreted. Providing one lesser than 128 causes unit to entirely ignore targeting commands given on targets outside of this arc.
It would be expected the unit to try turning towards the target that remaint outside the arc until its within the arc and can be fired on, not sit there not reacting to attack order at all.

**Comment by reaperrr** [comment] 2020-06-21 12:51
> FacingTolerance >128

> lesser than 128

I'm confused, which one is it?

For the record: There's only 256 facings, and FacingTolerance goes in both directions, so FacingTolerance: 128 would cover the entire 360°.

**Comment by MlemandPurrs** [comment] 2020-06-21 13:03
sorry i meant lesser than 128. 
In my case it was FacingTolerance: 48 on JEEP's AttackTurreted and FacingTolerance: 56 on FTRK's AttackTurreted causing this.

**Comment by tovl** [comment] 2020-06-21 14:50
Duplicate of #10855

Also #16696 would have fixed it...

**Closed as completed** 2020-06-21 14:55 UTC
Labels: Bug
