### ISSUE TITLE
Planes don't trigger idle notifications

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16197] opened 2019-02-11 09:14 UTC
Regression from #15848.

We saw one major regression from this with #16092, but #16028 correctly points out that this is also an issue for missions that would like to use `Trigger.OnIdle` from Lua.

`INotifyBecomingIdle` is triggered from `Actor.Tick`, which is guaranteed to run before `ITick.Tick`. We should therefore be able to replace the implementation in `Aircraft` with an `if (self.IsIdle) OnBecomingIdle(self);` check at the start of its Tick. This will make sure it only runs if no other trait responds to the notification. It may be necessary to queue it as `ActivityUtils.RunActivity` to avoid a one-tick pause.

`INotifyIdle.TickIdle` can be called either from `FlyCircle` or from `Aircraft` if `self.CurrentActivity` is `FlyCircle`. Note that we will need to be careful to avoid activity loops with `ReturnOnIdle`.

**Comment by pchote** [comment] 2019-02-11 09:29
On second thought, this is way too risky to put in a final playtest, so lets push this to Next + 1.

**Comment by GraionDilach** [comment] 2019-02-11 10:19
Isn't this a duplicate of #15948?

**Comment by pchote** [comment] 2019-06-30 16:55
This is sufficiently distinct from the other aircraft/activity changes that IMO we can get away with deferring this.

**Closed** 2019-09-01 14:38 UTC
Labels: Regression
