### ISSUE TITLE
Deleting and re-adding the first player spawn crashes the in-game map editor

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14232] opened 2017-10-21 15:17 UTC
Hello,

I spotted following bug in the map editor of tiberian dawn:

Steps to reproduce:
1. Create a new, empty map (I've chosen "Desert" and "128x128")
2. Switch to the "Actor" tab, where the buildings are
3. Add a player spawnpoint
4. Switch the "owner" dropdown to  "Multi 0"
5. Select a base building (I selected a power plant) and place it somewhere
6. Remove the spawnpoint by right-clicking it
7. Try to re-add the spawn point at different location -> Crash!

Happens at least under Linux Mint 18.1

**Comment by Mailaender** [comment] 2017-12-20 08:47
Confirmed:

```
Saved current map at /home/matthias/.openra/maps/cnc/{DEV_VERSION}/test.oramap
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException () [0x00000] in /home/abuild/rpmbuild/BUILD/mono-4.6.1/mcs/class/referencesource/mscorlib/system/throwhelper.cs:68 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <dca3b561b8ad4f9fb10141d81b39ff45>:0 
  at OpenRA.Mods.Common.Traits.EditorActorLayer.Add (System.String id, OpenRA.ActorReference reference, System.Boolean initialSetup) [0x0001c] in /home/matthias/Entwicklung/OpenRA/OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs:111 
  at OpenRA.Mods.Common.Traits.EditorActorLayer.Add (OpenRA.ActorReference reference) [0x0000a] in /home/matthias/Entwicklung/OpenRA/OpenRA.Mods.Common/Traits/World/EditorActorLayer.cs:107 
  at OpenRA.Mods.Common.Widgets.EditorActorBrush.HandleMouseInput (OpenRA.MouseInput mi) [0x001aa] in /home/matthias/Entwicklung/OpenRA/OpenRA.Mods.Common/EditorBrushes/EditorActorBrush.cs:118 
  at OpenRA.Mods.Common.Widgets.EditorViewportControllerWidget.HandleMouseInput (OpenRA.MouseInput mi) [0x0005e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Mods.Common/Widgets/EditorViewportControllerWidget.cs:96 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x000ce] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Widgets/Widget.cs:400 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x00065] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Widgets/Widget.cs:391 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x00065] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Widgets/Widget.cs:391 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x00065] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Widgets/Widget.cs:391 
  at OpenRA.Widgets.Widget.HandleMouseInputOuter (OpenRA.MouseInput mi) [0x00065] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Widgets/Widget.cs:391 
  at OpenRA.Widgets.Ui.HandleInput (OpenRA.MouseInput mi) [0x00044] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Widgets/Widget.cs:105 
  at OpenRA.DefaultInputHandler+<OnMouseInput>c__AnonStorey2.<>m__0 () [0x00006] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Input/InputHandler.cs:50 
  at OpenRA.Sync.CheckSyncUnchanged[T] (OpenRA.World world, System.Func`1[TResult] fn) [0x00044] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Sync.cs:183 
  at OpenRA.DefaultInputHandler.OnMouseInput (OpenRA.MouseInput input) [0x00020] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Input/InputHandler.cs:50 
  at OpenRA.Platforms.Default.Sdl2Input.PumpInput (OpenRA.Platforms.Default.Sdl2GraphicsDevice device, OpenRA.IInputHandler inputHandler) [0x0016c] in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2Input.cs:102 
  at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput (OpenRA.IInputHandler inputHandler) [0x0000f] in /home/matthias/Entwicklung/OpenRA/OpenRA.Platforms.Default/Sdl2GraphicsDevice.cs:486 
  at OpenRA.Renderer.EndFrame (OpenRA.IInputHandler inputHandler) [0x0000e] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Renderer.cs:162 
  at OpenRA.Game.RenderTick () [0x00142] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:677 
  at OpenRA.Game.Loop () [0x00142] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:787 
  at OpenRA.Game.Run () [0x00042] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:805 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Game.cs:253 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /home/matthias/Entwicklung/OpenRA/OpenRA.Game/Support/Program.cs:37
```

**Comment by LipkeGu** [comment] 2017-12-30 20:46
It seems to be a duplicate of #9364

**Closed** 2017-12-30 22:08 UTC
Labels: Crash, Map Editor
