### ISSUE TITLE
[RA] Oil Derricks not being used by the AI during Skirmish

### ISSUE THREAD

**Issue by Maurice84** [OpenRA/OpenRA#11626] opened 2016-07-10 10:31 UTC
I don't know if this is a known issue, but it's disappointing the AI isn't aware of the cash flow produced by the Oil Derricks. I created a few maps for multiplayer and it seems the AI relies on ore and diamonds only. When there are no more resources the AI immediately stops and acts like a sitting duck surrounded by unclaimed Oil Derricks. Very unfortunate and makes the game finish very quickly and not that challenging. Could this be fixed?

**Comment by GraionDilach** [comment] 2016-07-10 12:09
#11417 is a step towards it.

**Comment by Mailaender** [comment] 2016-07-10 15:41
Duplicate of https://github.com/OpenRA/OpenRA/issues/4561.

**Closed by Mailaender** 2016-07-10 15:41 UTC
Labels: AI, Feature
