### ISSUE TITLE
Cut sound on window defocus

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#4818] opened 2014-03-07 12:20 UTC
The volume for all sounds should be faded to zero when the OpenRA window loses focus, and restored on regaining focus.

**Comment by Mailaender** [comment] 2016-07-30 08:29
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/11736 and https://github.com/OpenRA/OpenRA/issues/5619.

**Closed by Mailaender** 2016-07-30 08:29 UTC
Labels: Audio, Polish
