### ISSUE TITLE
varying unit prices

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2252] opened 2012-06-23 09:38 UTC
The Dune 2000 starport is some kind of a market where you can buy vehicles. It's prices vary around a maximum percentage to the actual costs (cheaper and more expensive). I don't know if it could be added to ProductionAirdrop so easily.
##

**Comment by MustaphaTR** [comment] 2016-10-11 16:12
We should keep the costs same for different players at the same time so it wouldn't cause much balance problem, not sure if it was handled like that in original game, haven't played D2K multiplayer much.

**Comment by penev92** [comment] 2021-02-03 00:50
Please refer to my comment on #7055 for how fluctuating prices should work.

**Comment by pchote** [comment] 2021-02-13 16:36
Closing as a reverse duplicate of #7055. @penev92's comment there provides all the details on what is required here, and my experimentation has shown that this is best implemented together with the rest of the starport production logic in a new `IProductionQueue` implementation.

**Closed by pchote** 2021-02-13 16:36 UTC
Labels: Dune 2000, Feature
