### ISSUE TITLE
System.ObjectDisposedException: Safe handle has been closed

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#13052] opened 2017-04-02 16:05 UTC
happend when i did exit out of a running game 

```
Red Alert Mod at Version release-20161019
Date: 2017-04-02 15:56:42Z
Operating System: Linux (Unix 3.16.0.4)
Runtime Version: Mono 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017) CLR 4.0.30319.42000
Exception of type `System.ObjectDisposedException`: Safe handle has been closed
  at System.Runtime.InteropServices.SafeHandle.DangerousAddRef (System.Boolean& success) [0x00025] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Net.Sockets.Socket.Shutdown_internal (System.Net.Sockets.SafeSocketHandle safeHandle, System.Net.Sockets.SocketShutdown how, System.Int32& error) [0x00002] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Sockets.Socket.InternalShutdown (System.Net.Sockets.SocketShutdown how) [0x00017] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Sockets.NetworkStream.Dispose (System.Boolean disposing) [0x0004f] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.IO.Stream.Close () [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Net.Sockets.TcpClient.Dispose (System.Boolean disposing) [0x0002d] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Sockets.TcpClient.Dispose () [0x00000] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at System.Net.Sockets.TcpClient.Close () [0x00000] in <5641e4edad4f4464ba58c620a7b8ea48>:0
  at OpenRA.Network.NetworkConnection+<NetworkConnection>c__AnonStorey0.<>m__0 (System.Object _) [0x00144] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x0002c] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <f712f98eb8e445c8918edaf595bbe465>:0
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00012] in <f712f98eb8e445c8918edaf595bbe465>:0
```

**Comment by RoosterDragon** [comment] 2017-04-02 16:31
Duplicate of #12676.

**Closed by RoosterDragon** 2017-04-02 16:31 UTC
