### ISSUE TITLE
Changing to a server in another mod leaves you on the main menu

### ISSUE THREAD

**Issue by dsimmons87** [OpenRA/OpenRA#14642] opened 2018-01-02 22:08 UTC
If you load the playtest version of openra, go to multiplayer, then double click a server in another mod, it does change mods correctly, but then just leaves you on the main menu. To join the server, you then have to click multiplayer and find it again.

**Comment by pchote** [comment] 2018-01-03 20:52
No repro on macOS.  Switching from D2k playtest -> TD playtest and TD playtest -> TD release both worked fine.  This may be an OS specific issue, can anyone else confirm?

**Comment by ltem** [comment] 2018-01-03 21:02
Couldn't reproduce on Linux (Debian 9). TD playtest -> RA playtest -> D2K playtest ->  TD playtest.

**Comment by dsimmons87** [comment] 2018-01-03 21:12
I was running Windows 10. It's only joining playtest servers in another mod. Joining other non-playtest servers works fine.

**Comment by pchote** [comment] 2018-01-03 21:13
Probably a regression from #14435 then.  I suspect that may be mangling the Launch.Connect argument.

**Comment by dsimmons87** [comment] 2018-01-03 21:20
Just to add, running:

RedAlert.exe Launch.Connect=127.0.0.1:1234

Works on release but not on playtest.

**Comment by pchote** [comment] 2018-01-06 13:24
> RedAlert.exe Launch.Connect=127.0.0.1:1234

This works on both release and playtest when running the windows launchers under mono.
I don't have a working windows toolchain, won't be investigating or working on this any further.

**Comment by reaperrr** [comment] 2018-01-13 15:30
Certainly an annoying bug, but my gut feeling tells me we probably won't be able to fully debug and fix this before the upcoming release, so moving to Next+1 for now.

**Comment by pchote** [comment] 2018-01-13 15:59
I'm pretty sure that this is just an escaping issue.  If someone ever gets around to debugging this I suspect they will find that the launcher is passing the argument in as `""Launch.Connect=ip:port""` or something similarly silly that stops it from being parsed.

**Comment by RoosterDragon** [comment] 2018-01-24 20:40
https://github.com/OpenRA/OpenRA/blob/8a6091884127ea2c6706662332ee70097c81885e/OpenRA.Game/Game.cs#L493-L494

`SwitchToExternalMod` does not pass the Engine.LaunchPath argument - it should probably do so.

In #14435, when no Engine.LaunchPath is provided, the logic was changed from "append launch path to existing args and relaunch" to "discard existing args - relaunch with launch path and mod args instead". https://github.com/OpenRA/OpenRA/pull/14435/files#diff-a733e38b669341b9d052d974bfadee94R67 This may not have been intentional - perhaps it should retain existing args? (Although it may wish to take steps to avoid adding a second Game.Mod arg if it does decide to go this route)

I'm not quite sure what the fix should be - but the cause is certainly:
- `SwitchToExternalMod` does not specify Engine.LaunchPath.
- Failing to find a launch path, the launcher decides to run another launcher via `RunInnerLauncher` instead of running the game directly. https://github.com/OpenRA/OpenRA/pull/14435/files#diff-a733e38b669341b9d052d974bfadee94R38
- `RunInnerLauncher` discards the existing args - thus the Launch.Connect arg is lost.
- Mod starts without a Launch.Connect argument and hits the main menu.

**Comment by pchote** [comment] 2018-01-24 20:43
I think the proper fix will be to preserve args in `RunInnerLauncher`.

**Comment by pchote** [comment] 2018-01-28 14:28
@RoosterDragon do you want to put a PR together for this?

**Closed** 2018-02-04 15:14 UTC
Labels: Regression
