### ISSUE TITLE
Ingame IRC join crash

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#10974] opened 2016-03-24 20:42 UTC
Just happened, no idea why. Did not happen during subsequent tries.

```
Red Alert Mod at Version release-20151224
on map f952d7560302bcb9b5363ce65a66ebaf2a1590d7 (Desert Shellmap by Scott_NZ).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij OpenRA.Chat.GlobalChat.OnJoin(Object sender, JoinEventArgs e)
   bij Meebey.SmartIrc4net.IrcClient._Event_JOIN(IrcMessageData ircdata)
   bij Meebey.SmartIrc4net.IrcClient._HandleEvents(IrcMessageData ircdata)
   bij Meebey.SmartIrc4net.IrcClient._Worker(Object sender, ReadLineEventArgs e)
   bij Meebey.SmartIrc4net.ReadLineEventHandler.Invoke(Object sender, ReadLineEventArgs e)
   bij Meebey.SmartIrc4net.IrcConnection.ReadLine(Boolean blocking)
   bij Meebey.SmartIrc4net.IrcConnection.Listen(Boolean blocking)
   bij OpenRA.Chat.GlobalChat.<Connect>m__8()
   bij System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bij System.Threading.ThreadHelper.ThreadStart()
```

**Comment by RoosterDragon** [comment] 2016-03-25 09:56
Duplicate of #10338.

**Closed by RoosterDragon** 2016-03-25 09:56 UTC
