### ISSUE TITLE
Helicopter disappears at the top edge of the map

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4841] opened 2014-03-09 12:01 UTC
Helicopters can hide at the top edge of the map completely and they are only visible through their shadow on the ground.

![heli](https://f.cloud.github.com/assets/6599106/2367880/1575bd1a-a784-11e3-8266-f7ed6217acaf.png)

This is probably caused by the perspective of the view. Maybe map edges could be extended by a couple of tiles, or maps could have a thin layer at the edges that are visible but not maneuverable. Or the units at the edge could be drawn on top of the shroud. Because shroud outside the map is different than the one inside, it can't be uncovered. Or outside shroud could have different color, which would also help see the map edges at the beginning of the game...

**Comment by penev92** [comment] 2016-02-13 21:31
Closing as reverse duplicate of #9552.

**Closed by penev92** 2016-02-13 21:31 UTC
Labels: Polish
