### ISSUE TITLE
Blue Tiberium doesn't create an explosive chain reaction

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#17195] opened 2019-10-07 01:20 UTC
In the original TS, Blue Tiberium would explode violently when fire or certain explosive weapons were used on it, which would create a chain reaction that would often destroy most of the field. While ORA currently has the DestroyResource warhead, this doesn't allow for the explosive chain reaction to be implemented.

**Comment by abcdefg30** [comment] 2019-10-07 13:44
Duplicate of #13955.

**Closed by abcdefg30** 2019-10-07 13:44 UTC
Labels: Feature, Tiberian Sun
