### ISSUE TITLE
Idea:Multi-Language support

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12569] opened 2017-01-12 05:58 UTC
OpenRA should support multi-language.
The core idea of Multi-Language support system is "localiztion string" which can be replaced by any other language.
There are some solutions:
UCS
UCS is a text format which contains "code" and "string", the code is the unique ID of the string, it can be any pure numbers, such as "160011"; The string is the localized string, for example, if we run OpenRA in English, the local string which ID is 160011 is "SinglePlayer", but if we run OpenRA in other language such as Chinese, it will be "单人游戏”.
UCS is quite simple to be processed, each UCS line is splited by "<TAB>", we just use split function to split each line of UCS file to get both ID and string.
we can use this code "160011" to stand for string "SinglePlayer" in English,  the only  thing translator need to do is translate the code "160011" to "SinglePlayer" in their language.

CSV
CSV is famous text format, it is splited by a "|", before the "|" is ID, after it is string.

**Comment by MustaphaTR** [comment] 2017-01-12 06:51
Duplicate of https://github.com/OpenRA/OpenRA/issues/10475

**Comment by cookgreen** [comment] 2017-01-12 08:22
yes, but you guys didn't implement it

**Comment by pchote** [comment] 2017-01-12 08:25
Closing as duplicate.

**Closed** 2017-01-12 08:25 UTC
