### ISSUE TITLE
Limit the amount of engineers built by the AIs

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#12206] opened 2016-10-11 08:41 UTC
From http://www.openra.net/#comment-2943347335:

> Please remove the enigneers from the AIs again. The AI now wastes a lot of money sending engineers to death for no reason. The AI just isn't smart enough to use this unit.
> Playing against AIs became much easier because of this.

**Comment by pi99y** [comment] 2016-10-11 10:07
I'd prefer if you just limit the amount of engineers (as title suggests) as opposed to removing them (as the quote suggests). I've lost buildings to AI's engineers a few times so it works against noobs :)

**Comment by pchote** [comment] 2016-10-11 17:57
I have also noticed this: the AI will happily send a constant stream of undefended engineers at you at the expense of building a real attack force.

I agree that we should disable this on prep so that we have time to fix it properly (together with ##11981) in Next + 1.

**Comment by MustaphaTR** [comment] 2016-10-11 18:19
We should add a new trait to say AI to not include specific units in Attack Force but still build them. There can be other units that will be used better by AI in such cases.

**Comment by MustaphaTR** [comment] 2016-10-11 18:24
Wait, we already have "ExcludeFromSquads:" trait? Why not just add Engineer here?

**Comment by GraionDilach** [comment] 2016-10-11 18:48
The issue is exactly that the AI Engineer usage is a giant top of a hack and engineers aren't used in tandem with other units. IOW you can already consider them listed there.

**Comment by MustaphaTR** [comment] 2016-10-11 18:51
I don't think so, i saw AI sending Engineers in Attack Force before. Also i checked code there is nothing about Engineers under `FindNewUnits:`

**Comment by pchote** [comment] 2016-10-11 19:56
#12212 covers this for prep, so moving to Next + 1.

**Closed** 2016-12-21 20:17 UTC
Labels: AI, Easy
