### ISSUE TITLE
White pixels appearing on tiles and actors

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17000] opened 2019-08-28 10:35 UTC
![Screen Shot 2019-08-28 at 13 27 49](https://user-images.githubusercontent.com/37534529/63848097-d908fb80-c997-11e9-9d2a-c46b418b992a.png)
![Screen Shot 2019-08-28 at 13 27 45](https://user-images.githubusercontent.com/37534529/63848100-da3a2880-c997-11e9-8547-3da4662007c1.png)
![Screen Shot 2019-08-28 at 13 27 23](https://user-images.githubusercontent.com/37534529/63848103-db6b5580-c997-11e9-87b5-0986f6dbd139.png)
![Screen Shot 2019-08-28 at 13 26 56](https://user-images.githubusercontent.com/37534529/63848108-dc9c8280-c997-11e9-9eb5-7394c81e3340.png)

I downloaded the playtest on an old Mac, 
macOS Sierra 10.12.6
Graphics: ATI Radeon HD 4850 512 MB

**Comment by pchote** [comment] 2019-08-28 10:52
Are you sure that this doesn't also happen on release-20190314?

**Comment by Punsho** [comment] 2019-08-28 12:06
it does, must have happened after some os update

**Comment by GraionDilach** [comment] 2019-08-28 14:46
Duplicate of #8596.

**Closed** 2019-08-28 16:20 UTC
