### ISSUE TITLE
Ore truck with inaccessible destination just stops

### ISSUE THREAD

**Issue by collimation** [OpenRA/OpenRA#11615] opened 2016-07-09 08:05 UTC
If an ore truck has an inaccessible destination it will stop rather than pick up other nearby ore.

**Comment by pchote** [comment] 2016-07-09 10:41
This is intentional.  The automatic harvesting behaviour is disabled when you explicitly move or stop a harvester because players don't like it when the harvester ignores their explicit orders.  Having the move order fail is a bit of an edge case, but IMO this is still the correct behaviour.

The automatic behaviour is restored when you issue a harvest/deliver order.

**Comment by DeclanMurphyCit** [comment] 2016-07-18 14:26
Would it be possible to get the ore truck to move towards the nearest refinery and just wait outside until it becomes available?

**Comment by WolfGaming** [comment] 2016-08-10 11:23
Couldn't we change the move order so it moves to the closest accessible point on the map?

**Comment by reaperrr** [comment] 2017-07-11 16:17
IIRC this was fixed in the last release, can anyone confirm @OpenRA/engine-hackers ?

**Comment by abcdefg30** [comment] 2019-09-18 13:16
Harvesters still stop. But I would agree with @pchote here that this is expected behaviour.

**Comment by tovl** [comment] 2019-09-18 20:00
#2309 is the real bug here. The harvester behaviour is just a consequence of that.

**Comment by tovl** [comment] 2020-09-17 15:35
Closing as a duplicate of #2309.

**Closed by tovl** 2020-09-17 15:35 UTC
Labels: Bug, Pathfinding
