### ISSUE TITLE
Add internal version number in custom maps

### ISSUE THREAD

**Issue by Kaito-Kid** [OpenRA/OpenRA#7856] opened 2015-04-04 15:13 UTC
If you have to many maps from the same author (only different versions) it spams your map chooser. May it's better if you see only one version of the Map (the newest) and by clicking you see all versions,

![3](https://cloud.githubusercontent.com/assets/5711422/6993219/d1bfe20a-daed-11e4-826a-caa72675b479.jpg)

![4](https://cloud.githubusercontent.com/assets/5711422/6993222/d6a67eb4-daed-11e4-94c1-c8b7fb90db2d.jpg)

**Comment by Mailaender** [comment] 2015-04-04 15:22
Duplicate of https://github.com/OpenRA/OpenRA/issues/4058.

**Closed by Mailaender** 2015-04-04 15:22 UTC
