### ISSUE TITLE
AI build choice metrics

### ISSUE THREAD

**Issue by Ayanami251379** [OpenRA/OpenRA#19213] opened 2021-03-04 07:54 UTC
## Motivation
While monitoring the AI I noticed there is no real build order or pattern for it.
As an example, the AI would construct two power plants in the beginning of the match instead of one and then constructing a refinery or infantry building. (Note that the tested AI's "InititalMinimumRefineryCount" is set to one)
This also causes the AI to take a much longer time to replace critical structures like a construction yard or war factory once they are destroyed.

The purpose of this request is to add more definable behavior to the AI as to having it just randomly filling blanks.

## Proposed solution
Adding choice metrics to base builder and unit builder modules.
As an example, in the module a extra choice metric can be added "BuildingPriority" and each building would have a priority to be build over other buildings.

Say if a refinery has a metric of 1 and a power plant a metric of 2 the refinery is more likely to be built, but if a power plant does not exist the tech is unavailable and a next priority has to be selected and in this case it would be a power plant. Thus with the next tick no refinery exists but the tech is available so the next building to be built will be a refinery.

## Side effects
Given the current implementation of the building choices the AI might consume more system resources to make choices as it will need to be implemented with the existing choice tests.

If implemented on the unit queues the AI might be stuck building only one type of unit until that unit max has been reached.
So the AI might have 25 rocket infantry but no rifle infantry.

## Alternatives
Adding a construction list instead of a choice metric. This will force an AI to tick off buildings on a list in a construction order to "emulate" behavior similar to traditional AI.

**Comment by pchote** [comment] 2021-03-04 09:54
Thanks for your input on this! However, this issue is largely a duplicate of #16634 and #16633 (which will be reopened at some point). Please comment on those if you think the discussion there is missing anything.

**Closed as completed by pchote** 2021-03-04 09:54 UTC
Labels: Idea/Wishlist

**Comment by Ayanami251379** [comment] 2021-03-05 11:37
@pchote I see, yes, I see now why I didn't find the desired issue.
Though do we keep the discussion on #16634 or #16633 ?
