### ISSUE TITLE
When opening a replay with an unknown map, make the client identify and/or offer downloading from the resource center.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11150] opened 2016-04-18 17:17 UTC
The error message could tell you the map's resource site map ID and perhaps even offer up a link to it or offer up a direct download.

**Comment by GraionDilach** [comment] 2016-04-18 17:25
Duplicate of #11149.

**Comment by abcdefg30** [comment] 2016-04-18 20:53
Seems like it, closing as duplicate then.

**Closed by abcdefg30** 2016-04-18 20:53 UTC
