### ISSUE TITLE
Sound and/or map notification on enemy engineer capture start

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13799] opened 2017-08-08 16:00 UTC
Currently it's only a subject of map control and perception to not be a victim of base capturing from an enemy because when engineer triggers capturing it goes completely unnoticed (except losing your production tab access if it is the only production building type you have).

**Comment by MustaphaTR** [comment] 2017-08-08 16:18
Vanilla D2K had text notification saying "One of our buildings has been captured" for that. I think all our mods has a "Enemy building captured" notification already. With some sound editing with "Our base is under attack" i guess we can make "Our building captured" notification. I dunno how to do sound editing tho, but i guess we can find someone to do so.

**Comment by netnazgul** [comment] 2017-08-08 17:03
Question here is not about capture finish but the capture itself.
Most players however counter it by saying that being able to spot the engie and deal with it is a part of the game, and by warning the capture engineers will be much less useful.

Still I think this issue is at least worth discussing

**Comment by AoAGeneral** [comment] 2017-08-09 02:09
This has been something I have noted when I wanted to change TD Engineers to external capture. It got put on hold for now but I had it set in the test where the Engineer would Start to capture and EVA would say "Base Under Attack". It wasn't the correct message because it doesn't have a "Capture Attack" EVA notification but what it did do is when that notification went off you could hit Space Bar and it would center your screen on that "Attack".

**Comment by MustaphaTR** [comment] 2017-08-14 10:52
Duplicate of #3797?

**Closed** 2017-08-15 10:16 UTC
Labels: Balancing, Idea/Wishlist
