### ISSUE TITLE
Artillery shells exploding under war factory

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#11648] opened 2016-07-13 16:21 UTC
Release-20160508.
Replay : https://filebin.net/w73silvd7ol48ttc @ 13:30 in the center of the map

Here you can see artillery shells exploding above the door of the war factory but under the war factory itself.

![phantom factory](https://cloud.githubusercontent.com/assets/8930382/16810889/2917c052-4926-11e6-9027-182bd85e3305.gif)

**Comment by pchote** [comment] 2016-07-13 16:38
Duplicate of #11612 / #11178.

**Closed by pchote** 2016-07-13 16:38 UTC
