### ISSUE TITLE
game crash on mouse over latency with my own 'server' 

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#9405] opened 2015-09-22 15:11 UTC
hey since the new release, whenever i use automatic port forwardning (upnp) to make a server everything works, but when i mouse over the latency red/orange/green light, my game will crash.
seems similar like a problem i had before in the older release and i think got it fixed then when i redownloaded red alert

**Comment by Zjordy** [comment] 2015-09-22 15:13
similar to my post: #9112

**Comment by pchote** [comment] 2015-09-22 16:11
Maybe a duplicate of #8787?

**Comment by penev92** [comment] 2015-09-30 12:27
Just had a similar report on bleed, commit 0e9257abcf39e2118b7b53df5c9f13fad429b828, happening in the skirmish lobby:

```
Crystallized Doom Mod at Version 0.3 Closed Dev Beta - 2015-26-09
Operating System: Windows (Microsoft Windows NT 6.1.7600.0)
Runtime Version: .NET CLR 4.0.30319.17929
Exception of type `System.Reflection.TargetInvocationException`: Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Inner Exception of type `Mono.Nat.MappingException`: Error 8: The underlying connection was closed: The connection was lost unexpectedly ..
     bei Mono.Nat.Upnp.UpnpNatDevice.EndGetExternalIP(IAsyncResult result)
   bei Mono.Nat.AbstractNatDevice.GetExternalIP()
   bei OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.GetExternalIP(Int32 clientIndex, OrderManager orderManager)
   bei OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic..ctor(Widget widget, TooltipContainerWidget tooltipContainer, OrderManager orderManager, Int32 clientIndex)
```

**Closed** 2015-12-01 16:20 UTC
Labels: Crash, Networking
