### ISSUE TITLE
Possibility to modify player spawn order in map editor

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17948] opened 2020-04-15 18:56 UTC
Currently player spawns are indexed in the order of their placement on the map. This sometimes creates a mess when a map has a lot of spawns and there is no order to them.

There are two ways to tackle that at the moment - place a placeholder near each spawn, remove all of them then place spawns back honouring the correct order; other way is to manually edit the map.yaml.

**Comment by Smittytron** [comment] 2021-03-18 17:48
Closing as duplicate of #16801

**Closed as completed by Smittytron** 2021-03-18 17:48 UTC
Labels: Idea/Wishlist, Map Editor, UI
