### ISSUE TITLE
War factories get blocked by only two produced units

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17404] opened 2019-11-30 15:42 UTC
Units should move out of the way (as the infantry units do when there is a lack of space) rather than blocking the factory. Apparently this happens even when there is a waypoint.

**Comment by reaperrr** [comment] 2019-11-30 22:16
I could swear they did until recently, so this might be a new regression.

**Comment by abmyii** [comment] 2019-11-30 23:54
> I could swear they did until recently, so this might be a new regression.

Yup, I think that's the case.

**Comment by tovl** [comment] 2019-12-01 11:39
I cannot reproduce this on bleed nor on release.

**Comment by pchote** [comment] 2019-12-01 11:42
I can't reproduce this either. @abmyii can you please provide more information for a repro case?

**Comment by abmyii** [comment] 2019-12-01 12:32
I can't remember if this happens when you have only one war factory (I think I have a long replay demonstrating that somewhere which would take time to find the exact timestamp), but in the replay I've attached I made two war factories with the one on the left primary. After making just one V2 the next one comes out of the non-primary factory.
Tested on release-20191117.
[https://cdn.discordapp.com/attachments/388282819371204608/650675614973427713/OpenRA-2019-12-01T122732Z.orarep](Replay)

**Comment by abmyii** [comment] 2019-12-01 14:28
Casually watch a FiveAces video and stumbled upon a case-in-point (he makes reference to the war factory waypoint too):
https://youtu.be/-2nqnoGYXs0?t=334
Blocked by only one heavy tank.

**Comment by tovl** [comment] 2019-12-01 17:37
I still cannot reproduce the production getting blocked entirely, but there is definitely something weird going on when you have more then one war factory.

Even when you explicitly set the primary building, it happens quite often that the vehicle pops out of the other building after nudging the previous vehicle. The previous vehicle still moves out of the way, but it seems the newly produced vehicle doesn't wait for that to finish.

**Comment by abmyii** [comment] 2019-12-10 19:49
> Even when you explicitly set the primary building, it happens quite often that the vehicle pops out of the other building after nudging the previous vehicle. The previous vehicle still moves out of the way, but it seems the newly produced vehicle doesn't wait for that to finish.

Just been testing this and I'm now convinced that it has never been any different. I've tried up (down?) to playtest-20140525 and still exactly the same.

**Comment by abcdefg30** [comment] 2019-12-10 21:11
Possibly related: #10055
We simply nudge all actors in front of factories but don't wait for the nudge to finish before letting the unit exit.

**Comment by abmyii** [comment] 2019-12-10 21:16
Any suggestions for a solution? I'm thinking let the primary wait for blocking object(s) to move? I'll try to address #10055 too.

**Comment by abmyii** [comment] 2019-12-13 18:56
> youtu.be/-2nqnoGYXs0?t=334
Blocked by only one heavy tank.

I think this is related to issue #2309. I found that a very simple fix for the primary factory not producing all units which is that a primary-factories only search is done, then a normal search if none available. This allows players to choose a specific factory where necessary by setting it to primary and then disabling primary when they want to disable it.

**Comment by deleted-user-1** [comment] 2020-03-08 20:06
> Units should move out of the way (as the infantry units do when there is a lack of space) rather than blocking the factory. Apparently this happens even when there is a waypoint.

As shown in https://github.com/OpenRA/OpenRA/issues/10055#issuecomment-596241957, the units do move out of the way. This ticket confuses the initial wrong issue description with other aspects that might be worth discussing but are not a bug per se:

> we don't wait for the nudge to finish before letting the unit exit.

It is debatable if changing it to wait for the units to make room is really the desired behavior since it slows down your production whereas the current mechanic ensures production does not need to wait for nudging the *temporarily* blocking units.

**Comment by abmyii** [comment] 2020-03-09 00:33
> It is debatable if changing it to wait for the units to make room is really the desired behavior since it slows down your production whereas the current mechanic ensures production does not need to wait for nudging the temporarily blocking units.

I disagree - production shouldn't be blocked by a single tank (as your GIF clearly shows). If one infiltrates an enemy base and creates a war factory to produce tanks the last thing you want is for half of them to be produced elsewhere rather than just wait for an extra second for the first tank to move out of the way.

**Comment by deleted-user-1** [comment] 2020-05-22 15:21
> > It is debatable if changing it to wait for the units to make room is really the desired behavior since it slows down your production whereas the current mechanic ensures production does not need to wait for nudging the temporarily blocking units.
> 
> I disagree - production shouldn't be blocked by a single tank (as your GIF clearly shows). If one infiltrates an enemy base and creates a war factory to produce tanks the last thing you want is for half of them to be produced elsewhere rather than just wait for an extra second for the first tank to move out of the way.

Please show me the gif that shows how a single produced unit blocks production. You are confusing this with the requested feature that production should be limited exclusively to the primary building! That's something completely different and referencing this as bug from other places only adds more confusion.

**Comment by deleted-user-1** [comment] 2020-05-22 15:38
> If one infiltrates an enemy base and creates a war factory to produce tanks the last thing you want is for half of them to be produced elsewhere rather than just wait for an extra second for the first tank to move out of the way.

I also doubt that this is reproducible in non-debug mode when a primary building is set.

**Comment by abmyii** [comment] 2020-05-22 16:23
> You are confusing this with the requested feature that production should be limited exclusively to the primary building! 

Hmm, it seems I have. Shall I remove my comment?

On a side note, I wasn't asking for it to be exclusive - rather all I ask is for the WF to be able to build more than one or two units before getting stuck and defaulting to another. Is 4/6 units before blocking too much to ask?

**Comment by pchote** [comment] 2020-05-22 16:42
if #18168 is solved using transit-only cells or multiple exits then this one will also be fixed “for free” without any other changes to the primary building logic.

**Comment by StevenL-Up** [comment] 2021-06-21 18:41
Please see the video here for an example of this issue: https://github.com/OpenRA/OpenRA/issues/19450#issuecomment-861663340

**Comment by abcdefg30** [comment] 2022-06-26 08:49
> Please see the video here for an example of this issue: https://github.com/OpenRA/OpenRA/issues/19450#issuecomment-861663340

That video shows the same issue as #10055, so closing as duplicate.

**Closed by abcdefg30** 2022-06-26 08:49 UTC
Labels: Pathfinding
