### ISSUE TITLE
When I click on the Menu Wheel during a replay (of a teamgame) the game crashes

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#11321] opened 2016-05-19 08:24 UTC
This issue may be hard to reproduce. When I am watching a replay and I click on the menuwheel (top right) the game sometimes crashes. The weird thing: it seems to crash for teamgames, but not 1v1s. And I've had an instance where it happened right away, and in another instance I had to click it a couple times (+resume) to invoke the crash.

*edit:Just now I was able to reproduce it in a 1v1 as well. I need to click the menuwheel, resume, the menuwheel again and then it crashes.

Red Alert Mod at Version release-20160508
on map 2592e056aed8d7267b36dfa76d1f8f79e007b06e (Great Sahara by Nuke'm Bro.).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.Reflection.TargetInvocationException`: Exception has been thrown by the target of an invocation.
Inner Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
     at OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.GetExternalIP(Int32 clientIndex, OrderManager orderManager)
   at OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic..ctor(Widget widget, TooltipContainerWidget tooltipContainer, OrderManager orderManager, Int32 clientIndex)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenRA.ObjectCreator.CreateUsingArgs(ConstructorInfo ctor, Dictionary`2 args)
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   at OpenRA.Widgets.Widget.<PostInit>c__AnonStorey0.<>m__0(String l)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.Widgets.Widget.PostInit(WidgetArgs args)
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node)
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w)
   at OpenRA.Widgets.Ui.LoadWidget(String id, Widget parent, WidgetArgs args)
   at OpenRA.Mods.Common.Widgets.TooltipContainerWidget.SetTooltip(String id, WidgetArgs args)
   at OpenRA.Mods.Common.Widgets.ClientTooltipRegionWidget.MouseEntered()
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   at OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey2.<>m__0()
   at OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler)
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by GraionDilach** [comment] 2016-05-19 08:28
Do you have UPnP enabled, by any chance in the network settings?

**Comment by noobmapmaker** [comment] 2016-05-19 08:33
No, UPnP is not checked in the settings.

**Comment by HenrytheSlav** [comment] 2016-05-19 08:34
I think @Micr0Bit found about it and we were discussing it on IRC. Check logs from http://logs.openra.net/?year=2016&month=05&day=10#20:45:21 on. He crashed by rapidly smashing ESC key.

**Comment by Micr0Bit** [comment] 2016-05-19 13:07
#11246

**Comment by abcdefg30** [comment] 2016-05-19 20:19
Indeed duplicate of #11246. Thanks for the report though!

**Closed by abcdefg30** 2016-05-19 20:19 UTC
