### ISSUE TITLE
Custom options for click-and-drag scrolling

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#5368] opened 2014-05-19 19:31 UTC
Using the middle mouse button to drag scroll is a bit of an annoyance for me watching and recording replays. I use 2 different mouses and with both of them it doesn't feel quite right. In-game it's a trivial matter but if in replay mode you could choose to switch drag-scrolling to e.g. right mouse button, it would IMO make replay viewing a better experience.

**Comment by penev92** [comment] 2015-09-21 01:30
Reverse duplicate of #9399.

**Closed by penev92** 2015-09-21 01:30 UTC
Labels: Feature
