### ISSUE TITLE
[RA] Review balance change methodology and add more balance changes to the playtest.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11995] opened 2016-09-07 00:16 UTC
Following the Mammoth Tank buff suggestion in #11731 I'd planned to bring along a series of balance PR's but was stalled due to the miscalculation on my part on how balance PR's was evaluated on GitHub. I honestly believed that this particular PR would be merged within hours due to the initial comment pointing to balance discussions among many of OpenRA's most invested players, the series of recorded map playtests and widely distributed map downloads (thousands!) over the course of 4 months with the particular balance change involved. Naturally I didn't expect everyone to agree on the PR itself but the sheer volume of support behind the balance change (compared to anything else noted in the changelog history) led me to believe that regardless of whatever gobbledygook it would meet in the comments in terms of impact on gameplay and balance it would be merged into the bleed like a magnet.

First, just to put this issue dead once and for all, despite mentioned in #11731 **5 times**, there's little-to-nothing in terms of balance changes in this playtest for the RA mod. The artillery nerf and late tech air buff effects has to some degree already been mapped out, demonstrated for months with the map playtests mentioned above including Frame Limiters own extensive map playtesting. With the exception of faster aircraft rearmament there's little else of effect on gameplay we should expect from the couple of weeks that the official playtest will be running. Ore harvester self-healing is a minor tweak and faction neutral. Transport accessibility to beach tiles has been improved, Nuke Truck damage vs air nerfed. GPS down with Tech Center and/or Radar Dome powerdown. Minor tweaks - improves gameplay with specific scenarios, not overall gameplay. 

Unfortunately I was a bit preoccupied and came up short in the comment section of the Mammoth PR which was the reason why I put up the forum poll thread, knowing it was gonna be a landslide. Personally I'm not a big fan of forum polls when it comes to balance discussions but with the PR being unreasonably sandbagged I just didn't care at that point.

I know there's been discussions among the devs on establishing balance teams for the RA mod in order to avoid cases such as this but I feel that it ought not be necessary. With exception to the TD mod the great majority of power players has little to nothing to do with GitHub and for the most part leave the forum's balance discussions alone. They _do_ play a ton of games tho and when they do voice their opinions it should carry real weight. Their reasoning may not always be substantiated by long posts but when there's an unmistakably strong opinion among these players you can bet your monthly salary on that there's gameplay insight involved. If balancing the mod is to move forward efficiently then documenting these voices should go a long way together with the overall discussions among Github contributors to get these changes into the playtests. Case in point, the Mig/Longbow buff with #11337 came out of community interest but was driven mostly because of interest by contributors. In turn contributors interpreted the buffs differently from what was originally proposed by the players (from damage vs armor buff and price reduction towards range and rate of fire buffs) which so far (tested for months) doesn't look like it will bring Longbows and especially MiGs much closer to be included in the meta with the next release. When players such as newwe, Kyrylo, Murto and klaas in the prior balance discussion brings up points as to how buffs ought to be implemented, and is subsequently ignored, you should expect the end result to come up short.

Game balance is one of the few things in the development that needs a particularly strong influence from the playing community. That's why beta testing exists for pretty much every AAA game out there, especially complex RTS multiplayer games - in order for for SC and COH to develop an advanced and exciting meta from beginning to end of any match, committed players are brought in for months to playtest the hell out of the game, directly influencing the flow and vibe of the game. Now, OpenRA is OpenRA but the above principle is no less relevant for the direction of the game balance.

With all that said, I'm not gonna immediately double down with another PR after the Mammoth PR plus I needed the above expressed before I could expect any chance whatsoever to have any other changes merged with another playtest. So here's a list of idiot-proof balance changes, cross-checked by hundreds of games by committed players over the course of many months that was intended to be brought on to seperate PRs before the playtests:

**Mammoth Tank:**
Speed 50, up from 42

Should be self explanatory even after the wheel-of-fortune style of commenting by users (including myself) in #11713. Turn rate buff is out of the question - the Mammoth Tank already has a turn rate close to that of the Heavy and Medium Tank so unless you want this unit looking like an elephant doing pirouettes on the battlefield then this should be left alone. As pointed to in the forum discussion thread linked in the PR the speed buff is exactly what is expressed as the most crucial element as to making this unit useful for whatever purpose you want it assigned to. The artillery nerf vs the speed 50 Mammoth has been proven long time ago to be an **absolute non-issue**. 
Also, because it happened: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19767&sid=d2c42d564fb40f668711c201b1803296

**Light Tank:**
ReloadDelay doubled, Damage doubled
Damage vs Heavy Armor +12,5%
Damage vs Light Armor +20%

Tested somewhat in the shadow of the other balance changes but has proved valuable in extending the units longevity and adding options to the Allied early- to mid-game. A concern with the rate-of-fire was raised on http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19768 but I lastly got an IRC msg from MustaphaTR saying he wouldn't oppose it should I push it.

Edit: Alternatively, ReloadDelay + Damage, both up by approx. 69%. Both values scales really well to this approx % number - ReloadDelay, from 13 to 22 = 69,2% increase and Damage, from 16 to 27 = 68,8%. The reason I initially doubled it was because it was the safest way to alter the fire rate (at least until #11719 comes along).

**Missile Sub:**
Cost: $2000, down from $2400
Damage: 25, down from 30
Added air as a valid target
Visual: Adjusted missile trajectory

This is an old one but it's really bad that this hasn't made it's way into the game yet. Hamb first exposed this on his twitch a year ago and pretty much got a round of applause. This balance change more or less drowned in the balance discussions raging on before and after the 20151224 holiday release and pretty much remained dormant. However it was brought back in map playtesting from May this year and despite having limited visibility due to being a Naval late tech unit has delivered as expected, picking off lazy Hinds and Longbows over or close to water with the sudden burst of its submissiles. Plays well and fun as hell. The damage and cost was somewhat reduced to gain the unit a little more accessibility. There's also a version provided on Frame Limiter's playtest maps with the AA being a more efficient seeker missile.

**Camo. Pillbox:** 
Health: 450HP down from 600HP

Should be self-explanatory. The camo pillbox having cloak and at the same giving the same health/price value as the regular pillbox makes it way op. It tanks way too much for its price considering its often met unexpectedly giving the defender a Heavy Tanks worth of HP before the attacker can refocus over to other targets. Not long ago the camo. pillbox was super close to being merged in as a french exclusive structure #11431. It was playtested for some time, indicating that overall it lessened the gameplay experience for the remaining Allied factions not having the camo. pillbox available for various scenarios where the cloak trait was neccessary. The next step was playtesting the camo pillbox as more of an option by nerfing the HP, meaning Allied players was at all times choosing between stealth or damage soak value which made both the reguar and camo. pillbox more distinct. The latest change was playtested extensively since late July and pretty much proved its concept.

**Shock Troopers:**
Health: 45HP, down from 60HP

It's a bit funny how the shock trooper has faded away a bit from competetive play the past couple of months. This made me think of the 100HP shock trooper deliberately not being used in matches precisely because they were OP. This isn't exactly the story here but the shock trooper still is super strong if you can get to them safely. Murto, pretty much becoming a scapegoat for the most recent balance discussion about the strong shock trooper, recently left Russia behind despite crushing the player base with late tech Russia in favor of the more "fun" Ukraine. Although the discussions was overall pretty divided on what alterations was needed, the most conservative and accepted one was an additional health nerf bringing the shock trooper health down to the level of the rocket trooper. This in order to aid specific counters such as Artillery, V2, Yak, Hinds and Parabombs. The playtesting proved the nerf to be at most moderate but rewards micro and did help stopping shock trooper swarms on narrow maps.
Relevant discussion: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=296107#296107

**Allied Tech Center:**
Health: 600HP, up from 400HP

The low health on the Allied Tech Center has been an issue for some time, especially with Parabombs that will have at minimum one shot at guarantee-sniping the structure before the GPS satellite is done, forcing the Allied player to build two tech centers. With the recent changes in the playtest, making the GPS satellite liable to loss of the Radar Dome _and_ base powerdowns (#11018) I think it would be a good time to up the health a bit. This HP buff has been with the earliest playtest maps, showing modest  but positive results - effectively, 600HP allows the tech center to retain about 10% health after a full Parabomb drop and requires two YAKs to empty it's entire arsenal forcing them to do two complete swipes or bring in a 3rd Yak do get a snipe of an AA protected tech center. Virtually the same effect applies to Hinds.

**Comment by ChristianDK** [comment] 2016-09-07 00:44
Yes agreed more balance changes are needed and I think nerfing camo pillboxes is the most important one as they are very OP. I would nerf their health down to 400HP though. 

For shock troopers I think their HP is fair and reducing their range a bit is better than a health nerf.

I think walls should get a health nerf as well since they are super cheap and super strong - it’s way too easy to stop big attacks and block paths completely just by building walls.

**Comment by SoScared** [comment] 2016-09-07 17:58
@ChristianDK #11910 sort of tip toes towards Walls being more breachable for both factions. Walls are a bit funky in that they're incredible strong yet still underused by the majority of players. If the problem persists then we probably would want to see walls integrated with some new ideas if we want to solve it without fading them out of the game. relevant discussion: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19730

**Comment by pchote** [comment] 2016-09-07 19:14
> I know there's been discussions among the devs on establishing balance teams for the RA mod in order to avoid cases such as this but I feel that it ought not be necessary.

The rest of the first half of your post demonstrates why this is necessary.  Our RA community has enough people with opinions that there will never be a consensus on even (or especially!) the simplest things.

The main motivation for designating a few people to collaborate on balance is that you can politely tell people "We appreciate your ideas, thanks, but we've already thought about this and are doing it our way for now" without too many hard feelings.  The bikeshedding should stay on the forums.

**Comment by SoScared** [comment] 2016-09-07 22:30
It feels a bit murky, delegating a few to stand as guardians for balance changes but at minimum I feel like if there were some sort of hard protocol as to how balance changes and tweaks are tested and quality checked _before_ being run through an official playtest then balance PR discussions would be way easier by avoiding talking points that second guess well-founded arguments and weed out emotional input.

The official playtest isn't really a place to reliably test balance changes. There's too little time, too few games with too few committed players to cover 3 mods worth of balance changes. It's a good place for weeding out errors but balance is something that settles months after it's been implemented by a committed player base so if we don't have a good pre convieved idea on how balance changes will affect games when the official playtests comes about then by law of nature the official playtests becomes a huge bottleneck for functional balance tweaks. Instead the changes are leapfrogging from realease after release where minor balance tweaks are overshadowed by broader strokes. This is why units such as the Chrono Tank, MAD Tank, Radar Jammer and every other fringe unit stay exactly the same and don't stand a chance making its way into the game.

If there was some sort of an established protocol with the above points taken into account then peer reviewing balance PR's could be streamlined but that would require those with merging powers to willingly go in and evaluate the groundwork done by the PR author instead of balance discussions done on a whim with that particular PR. Knowing that the devs generally are soaked in code work it might be considered a drag looking over documentation and overseing the process in general but the development in balance would be tenfolds more efficient and not least, predictable.

**Comment by pchote** [comment] 2016-09-08 07:54
Indeed.  My comment above is based on the assumption that the balance changes that do make it through to a PR have first been tested and shown to be an improvement on the community balance test maps.

**Comment by SoScared** [comment] 2016-09-08 15:08
After a short nice talk with AoAGeneral I just want to clarify that balance changes doesn't neccessarily mean just tweaking faction strengths against one another, it also includes improving upon existing gameplay in ways that adds versatility to certain stages of play. It's an important distinction because some people will always be very hesitent to touch the status quo when you have expressed public opinion polls such as http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19498 and http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19579.

**Comment by SoScared** [comment] 2016-09-11 13:49
Circumventing the idea of balance teams for the moment, one specific solution involves adding a wiki section on game balance PRs, e.g. a topic under 'Development Topics' and/or 'Guides', laying down some guidelines and/or prerequisites for a good balance PR. 

Depending on its content the wiki entry could allow PR authors, contributors and developers to be better equipped taking on balance PRs in general by taking into account evaluations of balance implications done outside the sphere of Github and Sleipnir's forum alone where contributors do not directly participate in tests and discussions.

Guidelines/prerequisite standards might include sourcing 1) relevant opinions (fully excluding anonymous polls) and discussions, and 2) playtesting and evaluation done by a certain group of players. Additionally all discussions, playtesting etc. would have to be fully transparent and available for anyone who wishes to check up on it (e.g. excluding protected discussions or game servers). Certain balance PRs could then be evaluated by contributors upon how well it falls in line with these pointers, quality, and on what kind of players are involved, forcing PR discussions to focus on relevant topics not covered in the prerequisites.

Note that this wouldn't _exclude_ balance PR's that don't follow these guidelines, as done in the past, but rather include those that are prepared below the radar of contributors that in the end stands in the backline, evaluating the PR in before it gets merged or rejected by developers with merging powers.

This has the advantage of encouraging the community to come up more interesting and creative solutions and doing its own homework instead of pussyfooting ideas that eventually don't get anywhere.

With this, grey areas cases are destined to pop up from time to time, but as of now the balance PR process is nothing _but_ a grey area.

**Comment by Smittytron** [comment] 2016-12-07 02:47
Have any steps been taken since September to form balance teams or a competition committee?  
I have a couple of thoughts in regards to SoScared’s point on transparency. One would be to get a panel together over voice or video chat and stream it in a podcast-like setting. Or you could go lower-tech and send mailouts to top-tier and respected players, asking them to write their thoughts on pertinent issues (i.e. Pillboxes). 

A committee should come with a mission statement to use as guild-lines. Beyond balance and state of play I think an obvious guideline some people tend to gloss over when proposing changes would be: ‘Is it in the spirit of the original game?’ In other words, if someone starts playing OpenRA for the first time, will it give them the proper nostalgia kick from when they played it as a kid, or will it feel too foreign?

**Comment by SoScared** [comment] 2017-01-28 18:29
At this point I'm ready to throw away any guideline specific solution and fully endorse a balance team to which balance changes will be filtered through. There's obviously not enough game-play invested developers/contributors to drive forward balance PR's post-1019 and, I guess, after this specific issue was posted. Currently there's only #12470 for the next release and frankly I'm dismayed of how fluffy that specific PR process was compared to how straight forward, self evident and secure that change was.  I'm starting to feel concerned with the stale nature hereof and I want to underscore the importance of the continued development of game balance in order to support growth both to the player base and the newly acquired competitive scene of RA. And as for the competitive scene the community is starting to experience a bit of overheating due to the map pool and game balancing not being able enough to keep up with the growth of skill and the sheer numbers of skilled players.

One straightforward way would simply be for the devs to approve of a balance team/person, say 1-3 months after every release, approved through a documentation PR or whatever and simply delegate the power of bringing balance PR's to the table. Unless there's a concern with the balance change in terms of game concept or lack of groundwork, the devs approve and ship it with the next release.

**Comment by pchote** [comment] 2017-01-28 18:41
IMO the problem is that most players love to complain but have no interest in helping themselves.  It's simply too easy to blame the faceless "developers" for anything that they don't like.

There are a few people doing interesting things with mod maps, but it feels to me like they are focusing on dramatic changes so that they can stand out from the default gameplay.  I don't think that's a bad thing at all, just that our default mods are well into the evolutionary (not revolutionary) phase of their lives.

> There's obviously not enough game-play invested developers/contributors to drive forward balance PR's post-1019

>  a balance team/person, say 1-3 months after every release

That balance team / person is *by definition* a gameplay invested developer/contributor!

**Comment by SoScared** [comment] 2017-01-28 18:57
As for the dramatic changes experimented by the community I believe they for the most part a reaction to lack of change for the past 1 year or so. Besides the map pool very little has been done (and often opposed) to accommodate the need for better adjusted game-play balance. It didn't suddenly come out of the blue.

With the right changes the game will grow regardless. Let them complain. Personally I thrive on complaints  but I don't know I might be a masochist. Overall I've always worked on the assumption on that good game balancing is mostly an objective matter and if done correctly, haters, complainers, downers will simply wither away with time, allowing the process to move forward. So... to hell with 'em.

**Comment by pchote** [comment] 2017-01-28 19:07
My point really is that the "OpenRA developers" isn't a group of people who are dedicated to keeping the RA gameplay alive, but a (very small) set of individual people who are working on the things that they personally find interesting.

Speaking for myself, RA stopped being interesting a long time ago and so i'm not going to invest time in micromanaging that mod (unless there are specific things that I find interesting, like the recent gapgen change).

The only way that things like the RA balance or the TD map pool are going to improve is if people who are specifically interested in seeing them improve decide to make that happen.

**Comment by SoScared** [comment] 2017-01-28 20:08
Hmm... well in that case, as I see it the only realistic way forward is to present batches of balance changes to the same PR as with #12040. I would rather traverse the inferno of hell than splitting up balance changes into separate balance PR's.

**Comment by pchote** [comment] 2017-01-28 20:11
That's what @AoAGeneral has been doing for TD, and it works well enough.  The important thing is to be able to explain the overarching motivations behind the changes in each PR.

**Comment by Smittytron** [comment] 2017-01-28 23:40
> The only way that things like the RA balance or the TD map pool are going to improve is if people who are specifically interested in seeing them improve decide to make that happen. The problem so far isn't that "the devs" won't agree on a balance team, it's that we don't have anyone volunteering to be that team in the first place.

@pchote I promise myself and every other competitive player I know would step up for a spot on a balance team if that's on the table.

**Comment by SoScared** [comment] 2017-01-28 23:45
#12536 #12507 - 50 balance changes after a few comments and reviews. Not that I'm against it but that's gonna be tough pulling off with the RA mod.

**Comment by SoScared** [comment] 2017-01-29 00:28
Wait, balance team volunteers? I think comments above were edited past each-other. 

If we're already talking about scouting for volunteers my interest is naturally there. I've spent a few years now attempting to push the mod's game-play in a certain direction, taking no shortcuts. To be able to finally punch through what I consider completely to be "delayed" balance changes would be immensely satisfying.

**Comment by AoAGeneral** [comment] 2017-01-29 01:00
@SoScared its going to be tough with RA because many people have different ideas on what the problem is but many of them don't have a good solution to it. I stated numbers in thread post and the response here http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19877&start=120 provided some feedback but the post itself also left holes open in the topic. Describing that he saw different results from what I spoke but in the same words spoke potential issues.

TD is a bit more simpler because there isn't as many players as RA and im keeping in mind of new players and skilled players while attempting to keep to the classic gameplay. (Such as the example of wanting to bring in single engineer captures just with a bit more balance.) Another being putting the Guard Tower to GDI only and Gun Turrets to Nod (Such as CNC95) while balancing it.

The other issue is players in RA much prefer base crawling/walking tactics while the others dislike it. The players who enjoy unit on unit clashes often find themselves in TD.

**Comment by pchote** [comment] 2017-01-29 01:04
TD also has the advantage of having a compact tech tree without many overlapping units.

**Comment by SoScared** [comment] 2017-01-29 09:44
My experience so far has been, the more RA is getting pulled towards army compositions, the more satisfied the player-base. There's not really many supporters of base crawling in RA any more. That race pretty much died out after the build radius was added in 12.23.2013.

When it comes to the core game-play of RA there's not really that much of a divide among the players. The surge of OMnom's playtesting (and now I guess also Fortnight) is a very recent phenomena started within the past 2 months. Some of the new, more radical changes presented with them, I believe, are due to the lack of punch from the community the past 1-2 years and so we're seeing new solutions to the same problems that has been effectively quarantined. The new playtesting threads in the community is a very good sign for the future of the RA mod but will inevitably turn back on itself when realizing that there's no realistic path forward. What they will need is something to measure up against.

Ok then. So for the past 2 years there's been gradually growing a consensus on what steps to take in what direction. The problem isn't really about division but rather on giving weight to the opinion of players who know the game inside-out when important decisions are being made. Effectively the past year, after abandoning map design, I've done my best to bring aboard the most reasonable balance changes that continually nudge the game in the right direction and, to be frank, have again and again provided better games than the release was ever able to - consistently, and with every round of playtesting since my first batch early last year. That's a pretty bold statement but my track track record would prove that and there never really was ever a divided opinion of it. This is also why the recent experimental builds managed to hold such a big list of changes and still provide reliably great games - they've all been progressively added under scrutiny from the community's finest with every batch of playtest maps (with months of analysis between them) all pulling in the same direction. IMHO it's long overdue to raise the floor and ship some of the longstanding changes. With exceptions of a few certain names there won't much of a division of the community thereof.

The above would be my contribution towards balancing the RA mod for the next release or two. As for the other emerging playtest threads I don't have a strong inclination for or against but in principle I would make the case for my own set of changes _first_ as the most time honored, proven and the most predictable course of change to make the RA mod a better game. There's surely tons of potential with the current play-testers but IMO this is the place to start.

**Comment by Smittytron** [comment] 2017-01-30 02:17
@SoScared 
> I would rather traverse the inferno of hell than splitting up balance changes into separate balance PR's.

I understand the sentiment but I think making a call on the most pressing concerns, (i.e. the pillbox change that was made) and then testing different changes on top of those earlier decisions is the way to go.

Once the pillbox change went through, everyone knew to make that change in their playtest maps. This allowed playtesters to a) save time by not testing different solutions to an issue that was already acted upon and b) test tweeks and ideas against the new reality of 600/800/800 allied static.

It also allowed Raishiwi and I to use 600/800/800 (such an important change from the current release) with legitimacy in the KotH tournament. 

Legitimacy is the main point of a competitive committee. While it would add the burden of extra bureaucracy on the process, I believe it could also get changes through with extra focus. I.e. 'This week the competition committee is tackling issue x'. 

Also I believe some of the ideas out there that are more 'new feature' oriented in nature, (Think 5a's sniper drop, my engi salvage idea, your work on gap generators), could be assigned to different volunteers and presented to the community in a way where they could get more traction than 'eh, that looks cool'.

**Comment by SoScared** [comment] 2017-01-31 17:33
@Smitty I was referring to the experience following #11731. The pillbox change was a different beast in that it was outright demanded by the community, to the point where people took it for granted as a change for the next release, long before the PR. Also the OP of this very issue might have kept away some contributors to discuss the PR back and forth.

Anyways while I appreciate the idea of having an orderly bureaucracy to deal with the balance (competitive or casual) I shudder a bit thinking of its implementation, at least with the current size of the player-base.

**Comment by Smittytron** [comment] 2017-01-31 20:32
Ouch! I see what you mean, that’s an awful lot of flak to take for a change that was great in retrospect. 

> I shudder a bit thinking of its implementation, at least with the current size of the player-base.

Do you mean there are too many players or too few? I'm counting the number of players currently active in competitive 1v1 and I'm not making it very far past ten.

I don’t think the problems from a committee would stem from the community, at least compared to how things are now. If anything I think that the committee could push through changes with added focus. Sure you’ll have the same amount of teeth gnashing over it but hopefully a balance committee could have the weight of legitimacy to move things along.

The main problems would likely come from within. A balance team will naturally have disagreements and will need some bylaws to keep them on track. For now, I believe there are enough issues and ideas out there to switch targets and keep things moving so that a single controversial change doesn’t shut the whole process down.

**Comment by pchote** [comment] 2017-01-31 20:55
Lets not forget that we have over 20000 active players (i.e those who have run OpenRA in the last 3 months), and the vast majority of those are not competative 1v1 players or online players at all.  Balancing the game exclusively for that niche would be a mistake.

**Comment by Smittytron** [comment] 2017-01-31 22:12
I can’t conceive of a situation where balancing the game around competitive 1v1 would negatively impact the rest of the community, including team games. At least not in a manner that better map design couldn’t solve.

I can however, think of several ways lending credence to someone who, for example, thinks artillery or Soviets are overpowered would negatively impact the 1v1 scene.

Most of the competitive balance talk revolves around making play less stale, making unused units like the MAD tank and Gap Generator worth something and deciding what/if new abilities and units should be added. If anything, we want to give everyone more toys to play with.

**Comment by pchote** [comment] 2017-01-31 22:32
The artillery is a good example, because this is something that many newbies feel is completely broken balance wise, only to have experienced players respond with an equivalent of "no, they're fine. learn2play".  While that may be true objectively speaking, if it ruins the gameplay experience for new players then I strongly suspect that a decent fraction of these people will simply stop playing.

**Comment by AoAGeneral** [comment] 2017-01-31 23:57
I agree with @pchote on this one. Biggest example I can think of is flame tanks and stealth tanks. Flame tanks used to be really strong with openings where you could decimate bases due to their speed and HP. Going against stealth tanks was tough to detect them. To make it easier on everyone detection was increased and the flame tanks HP and speed were reduced. Also increased their explosion when they die so a pack of them blow up but all still effective units to use.

The hard part is balancing the unit out while keeping in mind what a new player does. The only solution I have been able to come up for this is watching streams and see how they play and react in situations. IE: A reason I want single engineer capture is not only to balance and make engineers more useful but new players coming in don't realize its a double capture system and often times are never seen used again. (Still the case in 1v1 TD side).

**Comment by Smittytron** [comment] 2017-02-01 15:47
I understand the sentiment but I respectfully disagree that game balance isn't best left in the hands of competitive players.

Maybe we need to unionize. We’ll call ourselves the Committee for the Conservation of Competitive Play; CCCP if you will.

**Comment by SoScared** [comment] 2017-02-01 17:01
> Do you mean there are too many players or too few? I'm counting the number of players currently active in competitive 1v1 and I'm not making it very far past ten.

I was thinking about both the total and competitive player base. Being relatively small, everybody knows everybody. Within this context, in a team structure, relations are more than likely to affect objectivity and with the very short distance between competitive and casual players the friction would be very high. Emotions _always_ run high in these scenarios - not because we underestimate the integrity of ora players but by simply the fact that the community is way too short and cozy. We're human beings after all. By comparison, if OpenRA was a sizeable corporation there would be infinitely easier to establish a structured balance team setting their own agendas, corresponding with competitive players in subgroups and whatnot.  

IMO balance decision makers for the RA mod would have to be able to trusted to make autonomous decisions, to stand alone, avoiding others outside the sphere to take part in the decision making process. Perhaps that sounds counter-intuitive but I don't see another way for it to work reliably. Certainly you wouldn't have to go far to track down the one responsible for good or bad decisions.

**Comment by pchote** [comment] 2018-05-10 17:59
Closing as partially resolved/outdated (balance discussion) and partially as a reverse duplicate of #11995 (balance process discussion).

**Closed by pchote** 2018-05-10 17:59 UTC
Labels: Balancing, Red Alert
