### ISSUE TITLE
RenderBuildingWall frozen actor visual bug

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#9146] opened 2015-08-23 20:18 UTC
Discovered on #9144 but that is (obviously) not the source.

![screen shot 2015-08-23 at 3 14 43 pm](https://cloud.githubusercontent.com/assets/4861023/9430013/2563a1e6-49aa-11e5-855b-aa08edbb6193.png)

**Comment by pchote** [comment] 2016-07-09 00:33
Duplicate of #7103.

**Closed by pchote** 2016-07-09 00:33 UTC
Labels: Polish
