### ISSUE TITLE
When a user get forcefully disconnected from a multiplayer server the server crashes

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#17774] opened 2020-03-06 21:43 UTC
This happens on release and is a widely known problem, that's most likely the reason why it never got reported

Clarification on forcefully: when a user loses connection to a server or when a user has forgotten to download a map when the game starts

**Comment by pchote** [comment] 2020-03-06 21:56
I'm unable to reproduce this locally.

My testcase 1:
1. Start a local dedicated server (RA)
2. Start a local client, join server, select map Agenda
3. Delete local copy of agenda.oramap
4. Start a second local client, join server
5. Force start the game using the first client.

The game starts for the first client and the second client is kicked, as expected. The server does not crash.

My testcase 2:
1. Start a local dedicated server (RA)
2. Start a local client, join server
3. SIGTSTP the game process to simulate connection problems
4. Wait for the connection timeout to expire and for the client to be disconnected
5. SIGCONT to restore the game process.

The client is kicked, as expected. The server does not crash.

**Comment by PunkPun** [comment] 2020-03-06 22:06
Forgot to mention but it doesn't crash immediately, the game stops but you still have about 20 seconds to chat, afterwards none of your messages reach others. If you can't reproduce it locally try to test on already available servers

**Comment by pchote** [comment] 2020-03-06 22:09
Which servers experience this problem?

**Comment by PunkPun** [comment] 2020-07-01 08:43
I think this bug happens when in lobby all players click ready (and have downloaded the map), while one of the spectators doesn't have the map downloaded so it crashes the server

**Comment by PunkPun** [comment] 2020-07-01 08:57
> Which servers experience this problem?

we just crashed on EU Official server
but when I tried to reproduce it with a group of people by the method mentioned above the server did not crash but cleanly kicked the spectators

**Comment by Orb370** [comment] 2020-10-16 04:39
Idk if this is helpful, but I have not experienced this bug at all while playing TD for the last 6 months. I got it in RA occasionally.

I'm not suggesting it's an RA specific bug, but it could be related to how many people are in the lobby. I recall it usually occured  with more than...and this is a very rough estimate, 10 people in a lobby?

**Comment by OpenOP2Admin** [comment] 2020-10-19 20:27
happens all the time. usually hangs when somebody disconnects right after or during the start of the game

**Comment by pchote** [comment] 2020-10-19 20:29
We still dont have steps to reproduce this, so can't do much to fix it.

**Comment by pchote** [comment] 2021-08-04 17:37
We believe/hope that this was fixed by #19429.

**Closed as completed by pchote** 2021-08-04 17:37 UTC
Labels: Bug, Networking
