### ISSUE TITLE
Make parabombs timing more consistent

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14181] opened 2017-10-15 01:45 UTC
Parabombs subject has been previously discussed
http://www.sleipnirstuff.com/forum/viewtopic.php?t=19742
Also see : https://github.com/OpenRA/OpenRA/issues/4873

However, an idea to make Parabombs more consistent, would be to make them arrive within (almost) a fixed duration. 
Badgers appearance on the map would be related to the chosen angle (if #4873 implemented), i.e. : 
T_appearance + T_travel(angle) = T_constant (or almost constant, depending on map size, ...)

Therefore, there would be less randomness and bad luck for the bombing player, who would still need to anticipate enemy movement within T_constant. 
(Would be similar to how Abombs can be used to nuke an army, with a bit of mind games).

An anticipated problem is : is it fair if the player chooses the shortest path, while enemy's army is at the edge of the map ? (as the enemy won't be able to see badgers approaching)
However, this is more related to the drag'n'drop feature, if implemented. 

Also, the T_constant would mitigate the "OPness" of Parabombs at map edges (enemy army might move away by chance), while improving it elsewhere (less random, more consistent)

**Comment by netnazgul** [comment] 2017-11-07 12:35
This could be an issue on huge maps where now you at least have a chance to bomb an enemy on the map edge. This update will make parabombs more tied to map size and less viable on bigger ones.

Other than that I'm fully for this idea to be implemented. Although technical aspect of this still needs to be looked at.

**Comment by abcdefg30** [comment] 2020-08-29 18:03
Closing as duplicate of #5057.

**Closed by abcdefg30** 2020-08-29 18:03 UTC
Labels: Balancing, Red Alert
