### ISSUE TITLE
Missing hold button scrolling

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#6025] opened 2014-07-22 06:39 UTC
If you hold a button and move the mouse in a direction (lets say 0-1 cm gives you slow speed, 1-2 cm faster, 2-3 cm faster even, etc. from the point the mouse was when scroll button was activated) you get scrolling in that direction until you change mouse direction or let go of the button.

Or scrolling until you press the button again, like a on/off scrolling button (especially useful for replays).

Xanaxs mockup of a possible in-game example: 
![image](https://cloud.githubusercontent.com/assets/1732773/3359165/8921ff8a-fae5-11e3-90c0-1d4eac7d5df4.gif)

Also see #5587, #5368

**Comment by penev92** [comment] 2015-09-21 01:36
Duplicate of a number of other issues and superseded by #9399.

**Closed by penev92** 2015-09-21 01:36 UTC
Labels: Feature

**Comment by Snurre86** [comment] 2016-11-21 08:01
This is now fixed except for the scrolling animation.
