### ISSUE TITLE
If unit cant attack, it shouldnt move 'face to face' to the target instead

### ISSUE THREAD

**Issue by s1ww** [OpenRA/OpenRA#6624] opened 2014-09-30 02:54 UTC
If unit cant attack, the default behaviour should be _ignore_ the attack command

this apply for e.g.:
medics
mehanics (vs buildings)
aa's vs land units (mobile s.a.m.)
special units (gap generators, radar jammers, miners...)

its just waste of units if we missed it in group during fight
creating special groups for them is really unhandy
##

**Comment by Snurre86** [comment] 2015-06-22 14:49
If the medic healed in guard mod you could assign him to guard an infantry unit and the the game would ignore him like it does the ore miner if it is on guard duty.

**Comment by matjaeck** [comment] 2019-02-26 18:30
Potential duplicate of #5507.

**Comment by abcdefg30** [comment] 2020-05-10 16:12
Closing as duplicate of #5507.

**Closed by abcdefg30** 2020-05-10 16:12 UTC
Labels: Polish
