### ISSUE TITLE
WithTextDecoration trait doesnt change the colour of the owner when owner changed with lua

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#14389] opened 2017-11-19 21:18 UTC
UsePlayerColor: True
Wont work in this case

**Comment by pchote** [comment] 2017-11-19 21:20
The problem is that `WithTextDecoration` implements `INotifyCapture` when it should be using `INotifyOwnerChanged`.  This is an easy two line fix.

**Comment by pchote** [comment] 2017-11-19 21:30
`WithTextControlGroupDecoration` suffers from the same issue, and has the same fix.

**Comment by pchote** [comment] 2017-11-26 14:38
Fixed by #14391.

**Closed by pchote** 2017-11-26 14:38 UTC
Labels: Bug, Easy
