### ISSUE TITLE
Crash in Dune skirmish

### ISSUE THREAD

**Issue by schmendrick** [OpenRA/OpenRA#11340] opened 2016-05-22 19:07 UTC
played i think against 8 bots. after around 40 minutes i guess the game CTDed, what seems to me with an infamous nullreference exception ;)

[Logs.zip](https://github.com/OpenRA/OpenRA/files/276532/Logs.zip)

only occurred to me once so far. hope it helps

**Comment by obrakmann** [comment] 2016-05-22 19:24
Your exception.log is from April 18th and release-20151224, so the game probably didn't crash in managed (openra) code (otherwise an exception.log would have been written), but was killed by something else.

**Comment by obrakmann** [comment] 2016-05-22 19:37
Can you please let us know what operating system and GPU you're using? Thanks.

**Comment by schmendrick** [comment] 2016-05-23 21:13
oh, i just realize the exception log is indeed old. granted! 
but as you see on the other files, i _was_ playing.

here now the informations i should have given in the first place:

i played the latest release.

here are my system informations:
Win7 ultimate 64bit SP1,

intel i7-2600k, 8gb ram
AMD Radeon HD 7700 Series (and onboard Intel HD 3000)

**Comment by schmendrick** [comment] 2016-05-23 21:19
and after the crash he showed me an openra popup, i think saying it crashed and 2 buttons. one i think led to the FAQ

**Comment by pchote** [comment] 2016-08-06 19:13
I expect this will be a duplicate of #11310 / #11345  / #11251, so closing.

**Closed by pchote** 2016-08-06 19:13 UTC
Labels: Crash
