### ISSUE TITLE
Game crashes on window unfocus Ubuntu 15.04/16.04

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#12204] opened 2016-10-11 02:10 UTC
### Description

I get pretty persistent game crashes when the window loses focus, sometimes the Window can lose focus without issue, it seems to occur most frequently (if not exclusively) when focus is lost whilst interacting with the game, for example if I accidentally hit the volume key or Windows key whilst trying to micro.

When it happens killing the process with `sudo kill -9` doesn't close the game window, it just kills the music, I can still open the window and see the frozen game, however the cursor doesn't change as normal and I can't interact with it at all. The only way to get rid of the dead window is to reboot.

<details>
<summary>

Click to expand logs</summary>

### exception.log

```
Date: 2016-09-12 20:45:39Z
Operating System: Windows (Microsoft Windows NT 5.1.2600.196608 Service Pack 3)
Runtime Version: Mono 2.11.4 (tarball) CLR 4.0.30319.17020
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0
```
### graphics.log

```
System.DllNotFoundException: SDL2.dll
  at (wrapper managed-to-native) SDL2.SDL:SDL_Init (uint)
  at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor (Size windowSize, WindowMode windowMode) [0x00000] in <filename unknown>:0 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateGraphics (Size size, WindowMode windowMode) [0x00000] in <filename unknown>:0 
  at OpenRA.Renderer..ctor (IPlatform platform, OpenRA.GraphicSettings graphicSettings) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00000] in <filename unknown>:0 
System.DllNotFoundException: SDL2.dll
  at (wrapper managed-to-native) SDL2.SDL:SDL_Init (uint)
  at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor (Size windowSize, WindowMode windowMode) [0x00000] in <filename unknown>:0 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateGraphics (Size size, WindowMode windowMode) [0x00000] in <filename unknown>:0 
  at OpenRA.Renderer..ctor (IPlatform platform, OpenRA.GraphicSettings graphicSettings) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00000] in <filename unknown>:0
```
### IRC log

```
02:48] <AMHOL> Anyone know how to stop the game crashes on Ubuntu?
[02:49] <AMHOL> I can't alt-tab at all, have reported in the past but still no luck
[02:49] <+pchote> I don't think anyone knows how to start the game crashes on Ubuntu
[02:49] <+pchote> you'll need to give some details
[02:49] <AMHOL> lol
[02:49] <AMHOL> Well if I accidentally hit the volume key
[02:49] <AMHOL> Or the windows key or alt-tab
[02:49] <AMHOL> And the window loses focus
[02:49] <AMHOL> The game freezes
[02:49] <+pchote> that sounds like a driver / window manager related thing
[02:49] <+pchote> what openra window mode are you using?
[02:50] <AMHOL> The music still plays but no movement and can't interact at all
[02:50] <AMHOL> Can alt-tab out and everything else runs fine
[02:50] <AMHOL> Erm let me check 1 sec
[02:50] <+pchote> and what version are you on?
[02:50] <+pchote> if you're on release, then test the playtest
[02:50] <AMHOL> Pseudo-fullscreen
[02:51] <AMHOL> It happens in the playtest too
[02:51] <AMHOL> Tried upgrading mono
[02:51] <+pchote> try switching to Fullscreen
[02:51] <+pchote> which is called Fullscreen (Legacy) now on the playtest
[02:51] <AMHOL> Will give it a shot, thanks
[02:52] <AMHOL> Nope still happens
[02:53] <AMHOL> I have it frozen now, only way to quit is to kill the process
[02:53] <+pchote> what version of ubuntu are you running?
[02:53] <AMHOL> 16.04
[02:53] <AMHOL> But it was the same in 15.04
[02:54] <AMHOL> Mono JIT compiler version 4.6.1 (Stable 4.6.1.3/abb06f1 Wed Sep 28 13:54:26 UTC 2016)
[02:54] <+pchote> yeah, this won't be a mono issue
[02:54] <+pchote> it will be your gpu driver
[02:54] <AMHOL> Also, the game video a lot if I try recording the screen with OBS studio
[02:54] <+pchote> which is somehow interacting badly with openra
[02:54] <AMHOL> Ahh OK
[02:55] <+pchote> it probably will relate back to something we're doing wrong in openra, but that will take more debugging and knowledge than I can give to track down
[02:56] <AMHOL> Yeah looks like same as https://github.com/OpenRA/OpenRA/issues/6341
[02:56] <@orabot> Title: Unable to Alt+Tab out of window when 'Lock mouse to window' enabled · Issue #6341 · OpenRA/OpenRA · GitHub
[02:57] -travis-ci:#openra- OpenRA/OpenRA#21263 f66883c Paul Chote: The build passed. https://travis-ci.org/OpenRA/OpenRA/builds/166609235
[02:57] <AMHOL> Well not the same
[02:57] <AMHOL> But maybe lock mouse to window will stop it from happening
[02:58] <AMHOL> Do you know which processes I need to kill?
[02:59] <AMHOL> Killed
[02:59] <AMHOL> andy     26758  6.3  3.3 2152112 552696 ?      Sl   02:52   0:19 /usr/bin/mono-sgen /usr/lib/openra/OpenRA.Game.exe
[02:59] <AMHOL> But the game is still open
[02:59] <+pchote> weird
[02:59] <+pchote> that will be the correct one
[03:00] <AMHOL> Ahh OK
[03:00] <AMHOL> I normally have to restart when it happens
```

</details>

**Comment by pi99y** [comment] 2016-10-11 06:56
I tried this with live Linux Mint 18 Xfce 64bit, Intel graphics HD 4400 but could not reproduce.

**Comment by pi99y** [comment] 2016-10-11 10:00
@AMHOL Try "lock mouse to window" option as a workaround. Does it help?

**Comment by AMHOL** [comment] 2016-10-11 13:12
@pi99y I have tried this with various different settings for window mode, lock mouse to window, edge scrolling, tried with and without workspaces enabled, it's pretty consistently reproducible for me, figured out it doesn't even have to be during a game, I can make it happen on the main menu or anywhere really, just hold Alt and hit tab a few times

**Comment by obrakmann** [comment] 2016-10-11 17:58
Which desktop are you using? If it's Unity, install the `compizconfig-settings-manager` and try disabling everything that's not strictly necessary for Unity to keep working. It _might_ help, no guarantees, though.

**Comment by AMHOL** [comment] 2016-10-13 18:55
@obrakmann just tried this and the problem still persists

**Comment by AMHOL** [comment] 2016-10-17 23:29
Trying `LXDE` and it seems to be working so far, although the graphics do seem a little "jumpy"

**Comment by AMHOL** [comment] 2016-10-24 02:29
This problem seems specific to Unity, GNOME is working fine so just using that for now

**Comment by pchote** [comment] 2017-02-05 18:25
It looks like this is a bug with the lower level libraries (SDL and/or the window manager) that we have no control over or ability to fix.  Unfortunately I doubt there's any thing we can do on our end to fix this (except suggest workarounds on a case by case basis), so closing.

**Closed by pchote** 2017-02-05 18:25 UTC
Labels: Crash, OS: Linux
