### ISSUE TITLE
Nuke subs ground attack damages air

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#14866] opened 2018-02-28 17:36 UTC
### Issue Summary
I presume this is unintended but when a Nuke sub attacks the ground cell an aircraft is positioned over it will damage a helicopter above it. I doubt its intended but if so, it still looks quite ugly since it is no where near the impact point

- Steps to reproduce
	1. Attack ground underneath a heli

- OpenRA Replays
[2 bugs for the price of 1.zip](https://github.com/OpenRA/OpenRA/files/1768152/2.bugs.for.the.price.of.1.zip)

**Comment by abcdefg30** [comment] 2018-02-28 23:36
Duplicate of #14860.

**Closed by abcdefg30** 2018-02-28 23:36 UTC
Labels: Bug
