### ISSUE TITLE
RA: Weird behavior with fix rally point

### ISSUE THREAD

**Issue by theKalash** [OpenRA/OpenRA#12965] opened 2017-03-14 14:29 UTC
I long suspected something is up with the rally point of the fix but couldn't quite put my finger on it.

But with one of the recent patches someone was kind enough to introduce TS like automatic gates in the RA mod.

Using those I found strange behavior, maybe it will help someone investigate what's up with the fix rally point.

Setup:

Have Service depot and production building and enclose it by a concrete wall with gates.
Set rally points outside the walls

Units produced from production buildings will go to their rally point, pathing through the gate as expected. 

Units that leave the service depot after repair however will follow the rally point straight towards the wall and then stop.

**Comment by Snurre86** [comment] 2017-03-17 15:40
#5553 ?

**Comment by theKalash** [comment] 2017-03-17 15:46
Here are some screenshot of my setup:

<img width="465" alt="screen shot 2017-03-17 at 4 45 21 pm" src="https://cloud.githubusercontent.com/assets/19913563/24051070/313bf726-0b31-11e7-9f4f-b83bd4fc7949.png">

Rally point of the fact works fine, tank traves to rally point through gate


<img width="402" alt="screen shot 2017-03-17 at 4 45 47 pm" src="https://cloud.githubusercontent.com/assets/19913563/24051083/4057adf4-0b31-11e7-99de-291caa4e3d95.png">

After being repaired on the fix however, it stops here.

**Comment by Snurre86** [comment] 2017-03-17 16:04
def is related as if you change the rally point north and there is a vehicle or anything in the cell to the north it gets stuck to the point you have to sell the SD.

**Comment by theKalash** [comment] 2017-03-18 12:21
I don't think so. My issue is with the unit not reaching it's rally point though gates, not exit cell's being blocked.

**Comment by rob-v** [comment] 2017-04-09 17:18
PR #13093 
In my test you don't need a gate. a building or wall is sufficient. with move order or Rally point from factory, the unit finds path to Rally point. Repaired unit went towards Rally point but stopped on first obstacle - could be wall, building,... so in your sample you could delete gate and have there hole, the unit will still go the same way and stop before wall.

**Comment by pchote** [comment] 2017-04-10 21:05
This is caused by https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Move/Move.cs#L88 running the pathfinder with `checkForBlocked = false`.  This makes it ignore *all* actors, not just the one we want.

**Comment by pchote** [comment] 2017-05-07 07:49
Fixed by #13093.

**Closed by pchote** 2017-05-07 07:49 UTC
Labels: Bug
