### ISSUE TITLE
Bleed: Regression - Nod 03a and 03b have Scripting Crash

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#19777] opened 2021-10-27 17:55 UTC
After awhile the script fails and kicks you out of the game. Just play on fastest for about 30s and clear out the map.

[Lua Crash.txt](https://github.com/OpenRA/OpenRA/files/7428368/Lua.Crash.txt)

**Comment by pchote** [comment] 2021-10-27 18:09
Another regression (this time on JEEP) from #19067 that wasn't fixed by #19746.

**Comment by Orb370** [comment] 2021-10-27 20:45
Occurs on Nod 07C with Medium Tank.

**Comment by reaperrr** [comment] 2021-10-27 21:04
OK, we really didn't review that carefully enough (though I do think @VonNah should have tested it more before submitting the changes, too).

Just by looking at #19067 more closely again, even without testing I can tell that at least Apache/Orca, Gunboats and probably all(!) turreted tanks are affected as well, since all of them received `AttackFrontal` entries instead of adding the voice entries to `AttackTurreted`, -`Aircraft` and -`TDGunboatTurreted`.

**Comment by pchote** [comment] 2021-10-27 22:21
IMO the really stupid thing here is that it it slipped past the linter, runtime checks, and a months worth of (apparently lack of) testing on bleed.

We may be able to add an `ai.TraitInfos<AttackBaseInfo>().Count() > 1` check to `AttackBaseInfo.RulesetLoaded` to throw a `YamlException`.

**Comment by reaperrr** [comment] 2021-10-28 01:07
> We may be able to add an ai.TraitInfos<AttackBaseInfo>().Count() > 1 check to AttackBaseInfo.RulesetLoaded to throw a YamlException.

We do support multiple `Attack*` traits per actor though, just not more than 1 _enabled_ at any given time.
So that check should only throw on more than 1 `EnabledByDefault` Attack trait, to avoid throwing false positives (which is probably one reason why we didn't add such a check yet, since accounting for conditions during linting is a bit of a pain).

**Closed as completed** 2021-11-08 13:46 UTC
Labels: Crash, Tiberian Dawn, Scripting
