### ISSUE TITLE
[RA] [release-20161019] [Ubuntu] Not possible to play movies

### ISSUE THREAD

**Issue by j2k15** [OpenRA/OpenRA#12829] opened 2017-02-22 17:24 UTC
Hi,

I've extracted movies1.mix and movies2.mix and placed them under movies folder in the content folder.

When I try to play a video briefing (e.g. from 1st allied mission), it asks me to install via content management menu.

In this menu, I see something that the videos are not recocgnized (installable via CD).

Note : I've extracted the video files from French versions.

**Comment by pchote** [comment] 2017-02-22 17:32
Sorry, but we only support the english game content.  You can download the freeware english releases from http://www.cncnz.com/features/freeware-classic-command-conquer-games/

Support for other languages is planned and partially implemented, but we do not currently have the manpower to complete this.  Closing as a duplicate of #10475.

**Closed by pchote** 2017-02-22 17:32 UTC

**Comment by j2k15** [comment] 2017-02-23 05:52
I thought that this limitation only applies to CD.
I did not know that putting manually extracted movies1.mix and movies2.mix files and putting them in the right folder would work wathever the CD version they come from...

**Comment by j2k15** [comment] 2017-02-23 09:05
By the way I see that you edited the Game Content wiki page more or less ah the moment you closes this issue and the manual installation section has been deleted. Any reason ?

**Comment by pchote** [comment] 2017-02-23 09:59
The manual installation instructions only applied to older versions of OpenRA and no longer work.  In [release-20161019](http://www.openra.net/news/release-20161019/) we had to change the way that assets were installed to support the different package layouts used by the digital releases.  Some mix files are still directly copied, but others (like the movie mixes) must be extracted – and the list of what must be copied vs extracted depends on where you are copying the assets from.

**Comment by j2k15** [comment] 2017-02-23 12:51
Thanks for the input.
I'll stick with English content for now.

I did not know this wiki became obsolete.
