### ISSUE TITLE
Multi-language support？

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#8968] opened 2015-08-06 06:03 UTC
Creaters just do the function, and player can do the translate, menu and unit desciption.

**Comment by ScottNZ** [comment] 2015-08-06 06:11
Duplicate of #2824

**Comment by abcdefg30** [comment] 2015-08-06 20:41
Reopening as #2824 was closed and considered to be too messy to be reopened.
See https://github.com/OpenRA/OpenRA/issues/2824#issuecomment-128472763.

**Comment by reaperrr** [comment] 2015-09-06 21:28
```
[21:18:57]	<reaperrr> pchote: do we have a ticket including a list of things that need to be done to implement them? I do want translation support...
[21:19:21]	<pchote> no, because there is only one thing
[21:19:47]	<pchote> which is code-based translation lookups
[21:19:56]	<pchote> extracting all the hardcoded strings to the translation yaml
[21:20:36]	<pchote> and a Game.Moddata.Translate("STRING_ID") method 
```

**Comment by pchote** [comment] 2016-01-10 23:16
Superseded by #10475.

**Closed by pchote** 2016-01-10 23:16 UTC
Labels: Feature, UI

**Comment by KevinYeti** [comment] 2016-06-07 07:26
hello @pchote  
What is the progress of the translation support work now ? I have tried to do some translation work of my own language but seems not work. Is there any document like <<How To Translate Using Yaml>>? Or angthing I can help to do .
thank you.

**Comment by pchote** [comment] 2016-06-07 08:03
Progress is summarized in #10475.

**Comment by KevinYeti** [comment] 2016-06-07 08:11
thank you for fast reply 
and yes , i have checked that list . 
The translation support for yaml-defined strings seems not to work on my PC. I tried to change yaml file but  the text did not show on the button. 
I think there should be a guide of how to make the translation file correctly.

**Comment by pchote** [comment] 2016-06-07 09:05
The engine support for yaml-defined strings is there, but none of the mods are set up to use it yet.
There's still a lot of work to do before translations can be exposed to the players.
