### ISSUE TITLE
Crash at start Log included

### ISSUE THREAD

**Issue by RAOkie** [OpenRA/OpenRA#12061] opened 2016-09-19 03:14 UTC
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IO.FileNotFoundException`: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.Sound..ctor(String engineName)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by RAOkie** [comment] 2016-09-19 03:52
Issue corrected: I forgot to delete the opra folder in documents before reinstalling, all works fine now ;)

**Comment by pchote** [comment] 2016-09-19 08:44
Thanks for the report! This is a duplicate of #11252, which has been fixed in playtest-20160904.

**Closed by pchote** 2016-09-19 08:44 UTC
