### ISSUE TITLE
Rocket soldier sometimes misses the target

### ISSUE THREAD

**Issue by kyrylo** [OpenRA/OpenRA#11064] opened 2016-04-07 19:09 UTC
I found a bug where a rocket soldier sometimes misses his target.
The direction is important. The target must be directly above the rocket soldier.

[Video demonstration](https://www.dropbox.com/s/8mzsi2yraqvoi2u/openra-rocket-soldier-bug.mp4?dl=0)

![monosnap 2016-04-07 22-02-31](https://cloud.githubusercontent.com/assets/1079123/14363361/7769d666-fd0c-11e5-8e9c-65efe1ae87b3.png)

This bug occurs both in release-20151224 and playtest-20160403, but in the playtest the chance of missing is a bit lower (might be subjective).

**Comment by abcdefg30** [comment] 2016-04-07 19:37
I saw that quite often in streams/games, but thought it was fixed on bleed already, doesn't seem like it then. IMHO we should get rid of that nasty bug before the next release.

**Comment by reaperrr** [comment] 2016-04-08 13:30
Duplicate of #10305.

**Comment by abcdefg30** [comment] 2016-04-08 14:26
Ah yeah, closing this then.

**Closed by abcdefg30** 2016-04-08 14:26 UTC
Labels: Bug
