### ISSUE TITLE
Air units won't close the distance to attack other air units if ground weapon range is different

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#11430] opened 2016-06-10 22:50 UTC
As was mentioned by @HenrytheSlav in https://github.com/OpenRA/OpenRA/pull/11337#issuecomment-221490963 

> it was found that if longbow has two weapons with different ranges, f.e. AA 5 cells and ground 6 cells, then it will fail to shoot/move closer when at 6 cells distance against aircraft because it tries to use wrong weapon.

On bleed

**Comment by GraionDilach** [comment] 2016-06-11 00:09
Isn't this pretty much a duplicate of #10625?

**Comment by r34ch** [comment] 2016-06-11 00:35
It might be, although that other issue looks like target prioritization. This issue involved the one unit and never getting in range.

**Comment by GraionDilach** [comment] 2016-06-11 00:39
True, it might not be a true duplicate itself, just probably related.

**Comment by reaperrr** [comment] 2016-06-11 00:52
The problem here is most likely that the `GetMinimumRange()/GetMaximumRange()` use all weapons to get the range and don't consider validity against a specific target.

#10625 sounds more like effectiveness of the primary weapon takes priority when chosing targets, so they're really separate issues, as far as  I can tell.

**Comment by AoAGeneral** [comment] 2016-06-11 11:51
This also happens in TD. If the Anti air gun on the helicopters change for extra range over the anti ground target it goes to the distance of the anti air range and doesn't fire.

**Closed** 2016-07-01 12:24 UTC
Labels: Bug
