### ISSUE TITLE
TS dev Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by jtyle6** [OpenRA/OpenRA#11072] opened 2016-04-08 08:12 UTC
I was playing the dev Version of game on Garden Redux,

````
Tiberian Sun Mod at Version {DEV_VERSION}
on map aacb9f022ce6404729df36d38f6139dc1c65e8bc (Tiberium Garden Redux by Westwood Studios).
Operating System: OSX (Unix 14.5.0.0)
Runtime Version: Mono 4.2.1 (explicit/6dd2d0d Tue Nov 10 18:01:18 EST 2015) CLR 4.0.30319.17020
Exception of type `System.OverflowException`: Value was either too large or too small for an Int32.
  at System.Decimal.ToInt32 (Decimal d) [0x00060] in /private/tmp/source-mono-mac-4.2.0-branch-64/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.1-x86/external/referencesource/mscorlib/system/decimal.cs:938 
  at System.Decimal.op_Explicit (Decimal value) [0x00000] in /private/tmp/source-mono-mac-4.2.0-branch-64/bockbuild-mono-4.2.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.2.1-x86/external/referencesource/mscorlib/system/decimal.cs:1115 
  at OpenRA.WPos.LerpQuadratic (WPos a, WPos b, WAngle pitch, Int32 mul, Int32 div) [0x00058] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//WPos.cs:68 
  at OpenRA.Mods.Common.Effects.Bullet.Tick (OpenRA.World world) <0x14de59e8 + 0x0016f> in <filename unknown>:0 
  at OpenRA.World.<Tick>m__4 (IEffect e) [0x00002] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//World.cs:331 
  at OpenRA.WorldUtils.DoTimed[T] (IEnumerable`1 e, System.Action`1 a, System.String text) [0x00022] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//WorldUtils.cs:70 
  at OpenRA.World.Tick () [0x0013e] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//World.cs:331 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00226] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:519 
  at OpenRA.Game.LogicTick () [0x00055] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:544 
  at OpenRA.Game.Loop () [0x000d4] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:671 
  at OpenRA.Game.Run () [0x00042] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Game.cs:711 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Support/Program.cs:118 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /Users/JoelTyler/Documents/OpenRA/OpenRA.Game//Support/Program.cs:40 
```

**Comment by abcdefg30** [comment] 2016-04-08 08:15
Duplicate of #11026. Thanks for the report though. ;)

**Closed by abcdefg30** 2016-04-08 08:15 UTC
