### ISSUE TITLE
Native screen resolution not recognized. Window scale 1.25 instead.

### ISSUE THREAD

**Issue by christoph110** [OpenRA/OpenRA#18165] opened 2020-05-21 22:06 UTC
DESCRIPTION
After installing the new release 20200503 OpenRA does not recognize the native resolution of my screen (1920x1080) anymore. Instead Window scale is set to 1.25
(see screenshot of installing screen below). Additionally there is now laggy mouse movement and screen stuttering.
Is there a way to set the window scale manually in the settings.yaml?
![OpenRa-release-20200503](https://user-images.githubusercontent.com/59751309/82610854-760f6280-9bbf-11ea-8966-7ab70e31c8ee.jpg)

STEPS TO REPRODUCE THE ISSUE
Reinstalling (OpenRa or graphic driver) does not help.

EXPECTED BEHAVIOR
Expected Resolution: 1920x1080
Window Scale: 1.00

**Comment by pchote** [comment] 2020-05-21 22:32
OpenRA will be picking up the 1.25x scaling from your standard OS DPI configuration. This was an intentional change, and an important part of being able to support HiDPI configurations on Windows.

We have received reports from a small number of players about performance issues, but have so far not been able to identify a cause or common hardware configuration behind it.

**Comment by christoph110** [comment] 2020-05-21 22:41
Taking the scaling from the OS DPI configuration was introduced with the last release (20200503)?
As with the previous release 20200202 I did not face the issue.

**Comment by pchote** [comment] 2020-05-21 22:56
Yes. You can see more info on this change in Fiveaces' patch spotlight https://youtu.be/L2sQP3YYBMA?t=108.

**Comment by christoph110** [comment] 2020-05-21 23:13
Can you tell me, which parts (.EXEs, .DLLs) are using the OS DPI scaling as I can switch this off for individual applications (following this thread: https://superuser.com/questions/66101/set-dpi-of-individual-applications-in-windows).
I can see that this works for the RedAlert.exe but other parts of the game seem to have still the original OS scaling.

**Comment by pchote** [comment] 2020-05-21 23:51
Do you notice an actual change in the size of the menus and sidebar? My understanding of Windows's HiDPI support is that it was previously scaling the OpenRA window anyway, so in the new release the UI should stay the same size but now everything will be less blurry.

If you are concerned about the size of the battlefield viewport, that is controlled by a different setting (called Battlefield Viewport), and is not related to the DPI scaling.

**Comment by christoph110** [comment] 2020-05-24 18:29
I did some tests with different OS DPI scaling configurations (it is actually much simpler to switch of the OS DPI scaling in the compatibility properties for OpenRA than using the manifest solution I posted above):


OS DPI scaling 100%:
- Parameters retrieved from clean start of OpenRA: 
     - Screen size: 1920 x 1080
     - Window scale: 1.00
- Battlefield Viewport can be switched up to "far"
--> works as expected (Parameters are correct)
--> Graphic looks "smooth"


OS DPI scaling 125%:
- Parameters retrieved from clean start of OpenRA: 
   - Screen size 1536 x 864
   - Window scale: 1.25
--> Window scale is correct, but I do not know if the screen size is supposed to change as well...
- With FullscreenSize: 1536, 864 in settings.yaml:
   - smooth graphics (larger UI elements)
   - Battlefield Viewport can be switched only up to "medium" (UI scale disabled)
- With FullscreenSize: 1920, 1080 in settings.yaml:
   - graphics not "smooth", looks like pixel doubling (see screenshot below)
   - expected size of UI elements
   - mouse cursor does not match selection position (the cursor is not visible in the screenshot but was at the position of the tesla tank on the bridge)
   - Battlefield Viewport can be switched up to "far" (UI scale enabled)
![OSDPIScale125_res1920x1080](https://user-images.githubusercontent.com/59751309/82761205-33d16580-9df9-11ea-9722-d7755e0de132.jpg)


OS DPI scaling 125% but deactivated in the compatibility properties of RedAlert.exe
- Parameters retrieved from clean start of OpenRA: 
   - Screen size 1536 x 864
   - Window scale: 1.00
--> Window scale as expected, but screen size still not native resolution 1920 x 1080
- With default or FullscreenSize: 1536 x 864 in settings.yaml:
   - graphics not smooth but looks exactly like for the case that the OS DPI scaling is set to 1.00 and FullscreenSize: 1536, 864 in settings.yaml
- With FullscreenSize: 1920, 1080 in settings.yaml:
   - graphics not "smooth", looks like pixel doubling
   - expected size of UI elements but text looks weird
   - mouse curser does not match selection position (see screenshot)
   - Battlefield Viewport can be switched up to "far" (UI scale enabled)

It seems to me that switching off the DPI scaling for the RedAlert.exe does work for some parts of the game but the screen resolution is not affected.
Is it possible that the screen size should always return the native resolution (which does not work here)?

**Comment by antzpantz** [comment] 2020-05-29 14:26
I'm having a similar issue here. I play games on my 50" TV and its normally set to 150% scaling on a 1920x1080 resolution. I previously had set the Application to override the High DPI scaling behaviour so that I could play the game properly at 1920x1080 but now OpenRA is stuck on 1280x720 regardless.

**Comment by christoph110** [comment] 2020-05-29 17:40
@antzpantz : I have seen that the feature "DisableWindowsDPIScaling" in the settings has been removed for the release 20200503 which is quite unfortunate for users that want to play with a high resolution despite OS DPI scaling. I assume that the plan was to use the "Battlefield Viewport" now instead (which however does not allow you to choose the option "far" when your scaled/effective resolution is too small).
filed a feature request --> https://github.com/OpenRA/OpenRA/issues/18206

In the meantime, I found a temporary solution for myself where I hard-coded the resution and window scaling into the source code (This however does not allow you to change the resultion via the settings.yaml anymore)
If you want to use the resolution 1920 x 1080 with window scaling 1, replace the OpenRA.Platforms.Default.dll with following file in your OpenRA parent folder:
[OpenRA.Platforms.Default.zip](https://github.com/OpenRA/OpenRA/files/4703353/OpenRA.Platforms.Default.zip)

**Comment by pchote** [comment] 2020-05-31 12:35
Closing this as a reverse-duplicate of #18206, which is more directly actionable.

**Closed as completed by pchote** 2020-05-31 12:35 UTC
Labels: Bug, Performance, UI, OS: Windows
