### ISSUE TITLE
Undeploying a chrono MCV at just the right moment duplicates the MCV

### ISSUE THREAD

**Issue by ashleynewson** [OpenRA/OpenRA#15793] opened 2018-11-05 21:27 UTC
### Issue Summary
When a chrono MCV is undeployed at just the right moment it is erroneously duplicated.

#### System Information
- **OpenRA Version:** release-20180923 (compiled locally)
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Start a game
	2. Create chronosphere
	3. Chronoshift an MCV
	4. Deploy the MCV
	5. Wait until chronoshift period is almost over and undeploy the MCV such that the undeployment finishes at exactly the same time as the chronoshift period ends.
	6. There will now be two MCVs: one in the chrono-return position and another in the undeployment position.

- OpenRA Replays

	 - In this example, I successively double my number of MCVs (took a bit of practice). [OpenRA-2018-11-05T204839Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/2550636/OpenRA-2018-11-05T204839Z.orarep.zip)

**Comment by pchote** [comment] 2018-11-25 13:43
This is the same type of problem, caused by interleaving FrameEndTasks, that #14220 fixed for capturing.

The basics of the fix here is the same: introduce a `DisposeSync` method and make sure that all disposals from inside FrameEndTasks use this instead of the async version.  Some careful thought and testing will be required to handle the activity disposing, as that currently relies on *not* being called from a FrameEndTask.

The fix here is too complicated to rush into a hotfix / the next playtest, so moving to Next + 1.

**Closed** 2018-12-08 10:34 UTC
Labels: Bug
