### ISSUE TITLE
[TS] World Domination Tour Mode (WDT)

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#6715] opened 2014-10-08 14:11 UTC
World Domination Tour worse introduced in Tiberian Sun Firestorm and also available to Red Alert 2 ... 
Westwood has shutdown these Servers a long time ago 

So i ask when TS is almost released and Firestorm Support is also done, so we could implement this Feature for both versions... TS So we need only to implement it for TS-FS and adapt it later for RA2 when openRA is RA2 ready :)

**Comment by pchote** [comment] 2015-11-22 14:27
Duplicate of #3814.

**Closed by pchote** 2015-11-22 14:27 UTC
Labels: Idea, Tiberian Sun

**Comment by KOYK** [comment] 2017-12-16 05:37
@pchote you have closed this and the duplicate #3814, is that wise? i mean if any one is wiling to do this needs to see the issue first, just saying.

**Comment by GraionDilach** [comment] 2017-12-16 10:11
Third-party mod features should not be tied to main OpenRA feature requests - it's their project's leaders task to decide what they need, want, and able to do. There are already features in OPmod, MW and AS which are completely unrelated to base OpenRA requests and nothing stops random-capable-modder following the same footsteps.

In the case of WDT, however, this prolly need some server enhancements as well, though.

**Comment by penev92** [comment] 2017-12-16 13:24
It is highly unlikely that someone is just randomly going to pick such a massive task anyway. I expect if someone does it will be because they had been wanting to/planning it for a while.
