### ISSUE TITLE
Subterranean Units can Attackmove while underground

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#17631] opened 2020-01-29 11:51 UTC
1. Subterranean units will not show where they are when subterranean.

I think the method that orignal TS game use, which give a healthy bar for subterranean units, is pretty good on solving this problem. The better idea I think however, is to make all friendly unit covered by terrain and building show a dot image/outline of themselves in player's own colour.

2. Subterranean units can attack underground by using certain technique. 

you can reproduce it by using Attack Move.

**Comment by pchote** [comment] 2020-01-29 12:04
Duplicate of #12912 / #12913 / #13163?

**Comment by dnqbob** [comment] 2020-01-29 12:27
> Duplicate of #12912 / #12913 / #13163?

Good to see same idea. But I think this one can be not only apply to tunnel and subterrain, but also the unit is covered or part of by buildings/cliff.

Bug 2 now is uncertain for me because I am not familar with the yaml file and AI part for Openra TS.

**Comment by dragunoff** [comment] 2020-01-29 13:31
> 
> Good to see same idea. But I think this one can be not only apply to tunnel and subterrain, but also the unit is covered or covered part of by buildings image/cliff.
> 
This is tracked in #15880

**Comment by dnqbob** [comment] 2020-01-29 15:34
> This is tracked in #15880
Now the only probelm is to confirm that if "subterranean units can attack underground by using certain technique" in TS.

**Comment by dnqbob** [comment] 2020-02-01 07:47
OK, I reproduce this bug by using Attack Move by myself. 
The invisible flametank attack directly underground.
![bug TS](https://user-images.githubusercontent.com/13763394/73588909-05f2a900-450a-11ea-8bb8-efc7e958e73e.gif)

**Comment by PunkPun** [comment] 2023-05-02 16:14
First point is duplicate of #12913
Second point is duplicate of #18734 and fixed by #20512

**Closed by PunkPun** 2023-05-02 16:14 UTC
Labels: Bug, Tiberian Sun
