### ISSUE TITLE
Crashes running openra (red alert mod) in dedicated server mode on linux (Ubuntu 14.04.2 LTS)

### ISSUE THREAD

**Issue by Styrbjorn** [OpenRA/OpenRA#7886] opened 2015-04-06 14:14 UTC
It seems like my dedicated OpenRA server crashes after an hour or so of uptime. I have no idea why this is happening.

the server is launched via the following command (on a screen session)
screen -dmS openra_ded_ra mono --debug OpenRA.Game.exe Game.Mod=ra Server.Dedicated=True Server.DedicatedLoop=True Server.Name=Cinqore AB RA [ www.cinqore.se ] Server.ListenPort=1235 Server.ExternalPort=123

**Comment by obrakmann** [comment] 2015-04-06 14:16
crash log:
```
Red Alert Mod at Version release-20141029
Operating System: Linux (Unix 3.13.0.48)
Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1) CLR 4.0.30319.17020
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Mods.RA.Server.LobbyCommands.ValidateCommand (OpenRA.Server.Server server, OpenRA.Server.Connection conn, OpenRA.Network.Client client, System.String cmd) [0x00000] in <filename unknown>:0
  at OpenRA.Mods.RA.Server.LobbyCommands.InterpretCommand (OpenRA.Server.Server server, OpenRA.Server.Connection conn, OpenRA.Network.Client client, System.String cmd) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrder (OpenRA.Server.Connection conn, OpenRA.Server.ServerOrder so) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.InterpretServerOrders (OpenRA.Server.Connection conn, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.DispatchOrders (OpenRA.Server.Connection conn, Int32 frame, System.Byte[] data) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Connection.ReadData (OpenRA.Server.Server server) [0x00000] in <filename unknown>:0
  at OpenRA.Server.Server.<Server>m__0 (System.Object _) [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0
```

**Comment by obrakmann** [comment] 2015-04-06 14:17
Duplicate of #4720

**Closed by obrakmann** 2015-04-06 14:17 UTC

**Comment by Styrbjorn** [comment] 2015-04-06 14:22
Yes that looks like the problem im having.
