### ISSUE TITLE
AI planes follow other planes

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13286] opened 2017-05-13 17:05 UTC
Release-20170421.
AI planes can chase badgers and other flying enemies but can't attack them.

![yak](https://cloud.githubusercontent.com/assets/25843400/26027509/3cb0ec32-380f-11e7-85b8-e5fa7884c218.gif)
![mig](https://cloud.githubusercontent.com/assets/25843400/26027512/3f922254-380f-11e7-89cc-02aab9107b01.gif)

**Comment by MustaphaTR** [comment] 2017-05-14 08:56
Duplicate of #12190. But i think it could be better if we had a more generic issue about that targeting situation. It looks like AI doesn't check `Targetable:`/`(In)VaildTargets:` at all while chasing enemy units.

**Comment by abcdefg30** [comment] 2018-10-01 08:40
Closing as duplicate of #3468.

**Closed by abcdefg30** 2018-10-01 08:40 UTC
Labels: AI, Bug
