### ISSUE TITLE
Tick tank AttackMove target line missing

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20533] opened 2022-12-10 03:25 UTC
Reproduction:
1. use TS
2. build tick tank
3. use tick tank to attack move to somwhere
4. targetline missing

**Comment by Leo512bit** [comment] 2022-12-10 03:56
Can confirm, odd.

**Comment by PunkPun** [comment] 2022-12-10 07:39
duplicate of #19793
fixed in #20523

**Closed as not planned** 2022-12-10 10:29 UTC
Labels: Bug
