### ISSUE TITLE
Utility application crash when creating hash

### ISSUE THREAD

**Issue by Murto** [OpenRA/OpenRA#12516] opened 2016-12-28 13:13 UTC
The OpenRA utility is crashing for some maps in the resource center when trying to create a hash for them, resulting in the hash "Error: Utility application crashed. See utility.log for details". This also prevents uploading another map that results in the same error as it recognises them as the same map. I don't know what would be causing such an error.

**Comment by Murto** [comment] 2016-12-28 13:18
Recent observation: The maps affected are unable to be played when packed as a .oramap but can be played when unpacked

**Comment by Murto** [comment] 2016-12-28 15:23
Seems like when a map has directories for scripts/rules it causes this error.

**Comment by rob-v** [comment] 2017-04-08 17:12
@Murto Can you please provide an example/link for such map?

**Comment by Murto** [comment] 2017-04-08 17:24
@rob-v Here are a couple of examples: http://resource.openra.net/maps/duplicates/Error:%20Utility%20application%20crashed.%20See%20utility.log%20for%20details/

**Comment by rob-v** [comment] 2017-04-08 18:58
The .oramap is zipped in Unix I assume, SharpZipLib (seems like not maintained, last release in 2010?) has some not resolved bugs:
https://github.com/icsharpcode/SharpZipLib/issues/166
https://github.com/icsharpcode/SharpZipLib/issues/157
When I extract and zip it again on Windows with 7-zip it works.

**Comment by pchote** [comment] 2017-04-08 18:59
People shouldn't be manually compressing maps - use the map editor for that!

**Comment by rob-v** [comment] 2017-04-08 19:04
@Murto  How was the map compressed? My manual extract/zip was only with that already 'broken' zip. If you did it manually, you just need to use map editor as explained above.

**Comment by Murto** [comment] 2017-04-08 21:03
I tried compressing it manually and using the map editor and both had the same error

**Comment by rob-v** [comment] 2017-04-08 21:13
It seems as more people have this unresolved issue and you tried it manually and with map editor, that the problem is in unpacking by SharpZipLib (my 7zip could unpack it fine). I think there is known fix, but not applied/released by SharpZipLib .

I don't know why it happens only sometimes, I assume you can save it as workaround if needed on Windows.

**Comment by Smittytron** [comment] 2021-04-09 14:07
Closing as duplicate of #7861

**Closed by Smittytron** 2021-04-09 14:07 UTC
Labels: Crash, Utility
