### ISSUE TITLE
Mayor issue with attacking buildings

### ISSUE THREAD

**Issue by christerulfsparre** [OpenRA/OpenRA#4456] opened 2014-01-13 13:15 UTC
There is a issue with how units target buildings or other large actors
Example if there is a building that is 6x6 in size. And a unit is standing in Lower-Right corner. That unit might not be able to attack the building even if he is standing next to it.
Because he must attack the Upper-Left corner of the building.
He cannot simply attack any square that the building occupies.
This makes close combat stuff impossible to do at the moment. If I make a unit with range of 1. He will not be able to attack anything except for silos and other 1x1 buildings.
This also effects RA and CNC gameplay. Because units attacking from the north can stand further away from the target then units from the south.
= Advatange for north players

**Comment by pchote** [comment] 2015-11-22 12:00
Duplicate of #4310

**Closed by pchote** 2015-11-22 12:00 UTC
Labels: Balancing
