### ISSUE TITLE
Artillery can't force fire onto camo pillboxes in the shroud. 

### ISSUE THREAD

**Issue by SamKeightley** [OpenRA/OpenRA#12812] opened 2017-02-20 15:29 UTC
I'm not sure if this was a balancing thing or a bug, but what's the difference between firing on a blank tile in the shroud and firing on the tile where a camo pillbox has been placed. Nothing.. They are both just a location to provide to the unit to fire at. 

Having the camo pillbox show up in the shroud is fine, because once you learn of the location of one, you make a mental note to pay close attention to it with artillery or v2's, even if it disappears or something later. But restricting the ability to force fire on it is absolute garbage.

**Comment by MustaphaTR** [comment] 2017-02-20 15:31
I think duplicate of #11265.

**Comment by abcdefg30** [comment] 2017-02-20 15:35
Sounds like it. Closing as duplicate.

**Closed by abcdefg30** 2017-02-20 15:35 UTC
Labels: Bug
