### ISSUE TITLE
Spies can't detect enemy disguised spies

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#12443] opened 2016-12-01 18:28 UTC
Nothing happens when an enemy (disguised) spy come in the radius of own spy (whether own spy is disguised or not / whether there are units alongside own spy or not)

Replay : https://drive.google.com/open?id=0B4bdF_48xIwKUFpsSlhRYkFVcnM

**Comment by FrameLimiter** [comment] 2016-12-01 19:15
This is a duplicate issue, but has been ignored for too long now. Spies were suppose to detect other spies since Jul 2, 2015: [#8616](https://github.com/OpenRA/OpenRA/pull/8616)
In order to make them work as intended they need the AutoTarget Trait.

To fix them add this:
OpenRA\mods\ra\rules\infantry.yaml
SPY:
+AutoTarget:
++InitialStance: HoldFire
++ScanRadius: 5

Duplicate tickets:
[#12185](https://github.com/OpenRA/OpenRA/issues/12185)
[#9424](https://github.com/OpenRA/OpenRA/issues/9424)

**Comment by Mailaender** [comment] 2016-12-12 06:24
Closing as it is a duplicate.

**Closed by Mailaender** 2016-12-12 06:24 UTC
Labels: Balancing, Red Alert
