### ISSUE TITLE
OpenRA.Utility should have a "Render Map" command.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16849] opened 2019-07-27 09:52 UTC
One of the benefits of the CnCNet5 client in the legacy TS/RA2 games is to utilize resized results from the respective map renderer as map preview in the main menus. Since OpenRA also uses images for the map previews, ORA.Utility could be used to generate 1:1 map previews for the usecase and/or other promotional reasoning.

Zooming out the amp within Map Editor might result with driver errors,. so that's not a solution.

**Comment by Mailaender** [comment] 2019-08-04 11:08
Duplicate of https://github.com/OpenRA/OpenRA/issues/2762.

**Closed by Mailaender** 2019-08-04 11:08 UTC
Labels: Idea/Wishlist, Utility
