### ISSUE TITLE
Tiberian Dawn: New build cyborg doesn't respect defence stance

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14257] opened 2017-10-24 15:15 UTC
Hello,
I found a small bug in following situation:

1. Your base gets attacked by an enemy orca and nothing is there that fights against that orca 
2. You build a rocket cyborg to fight the orca.
3. That rocket cyborg leaves the factory and starts to fight the orca by itself (you don't touch the rocket cyborg and your cyborg factory is near the orca)
4. The orca fly away
5. The rocket cyborg tries to hunt the orca in order to fight it even it is in defence stance, where units usually don't hunt enemies.
6. The rocket cyborg gets shot once it reaches the enemy base, where the orca has flown^^
I would expect here, that the rocket cyborg stops shooting once the orca is out of reach.

**Comment by abcdefg30** [comment] 2017-10-24 15:35
This has probably something to do with units Attack-Moving to the rally point.

**Comment by Diranus** [comment] 2017-10-24 15:53
The rally point was set near the factory inside my base.

**Comment by GraionDilach** [comment] 2017-10-24 21:15
Since when TD has cyborgs?!

**Comment by Diranus** [comment] 2017-10-24 21:24
These small men?

**Comment by GraionDilach** [comment] 2017-10-24 21:25
Those are plain infantry.

**Comment by AndriiYukhymchak** [comment] 2017-10-24 21:25
Td had cyborgs in German version. It has to do with attack move for rally point. Attack move will get overhauled at some point... Hopefully

**Comment by Diranus** [comment] 2017-10-24 21:29
Ok, that is something I don't know.
I mean these soldiers.
I'm used to call these "cyborgs" because these were such in original C&C game (which I have in german language). ;-)
I didn't notice yet that OpenRA call them differently. Sorry.

**Comment by AndriiYukhymchak** [comment] 2017-10-24 21:33
Well what interests me is do you still see them as cyborgs in openra? The bug itself is currently intended behavior, but I agree that it is misleading

**Comment by Diranus** [comment] 2017-10-24 21:40
Yes, these looks exactly like cyborgs.

**Comment by AndriiYukhymchak** [comment] 2017-10-24 21:41
Well congrats, you have German mix file it seems

**Comment by Diranus** [comment] 2017-10-24 21:46
And where the german should come from?

The soldiers or cyborgs look like these in my copy of OpenRA:
https://imgur.com/a/rFWO4

I don't know other ones. :-(
I'm going to reinstall the game tomorrow and pay attention about what it actually installs.

**Comment by AndriiYukhymchak** [comment] 2017-10-24 21:48
Reinstall won't help. I'm not at my computer right now but I will write details later if no one beats me to it

**Comment by GraionDilach** [comment] 2017-10-25 10:09
I only heard of Tiberian Sun and Generals being cyborgified in Germany.

The graphics should be shared, I'd assume that only the blood during deathanims got recolored to black - for oil - in the supposed-to-German version (since TS did exactly that). So that screenshot proves nothing.

However, since OpenRAs cannot be translated at all by now (nor it reads german.mix which AFAIK was the language override), the cameos and the text should be in English.

**Comment by Diranus** [comment] 2017-10-25 12:34
In both, Tiberian Dawn and Red Alert, these were cyborgs. I didn't ever play Tiberian Sun or Generals so I can't confirm that.

I'm still a bit confused about this. I have no clue how my installation has gone wrong. :-(

I shot one of the cyborgs in OpenRA and it's bleeding out red-colored.

I can't remember how it was animated in the original version. 
I can't compare the death animation or something else to the german original game I have, because my computer is running under linux and has no CD drive so it would be very tricky to install it - even using DosBox.

**Comment by tovl** [comment] 2019-09-14 13:07
Since attack-move doesn't chase anymore, this should be considered fixed.

**Closed** 2019-09-14 19:38 UTC
Labels: Bug
