### ISSUE TITLE
Harvester self-healing to 50%

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#11224] opened 2016-05-05 11:03 UTC
After a quick discussion in IRC where there were mostly possitive responses to this idea, I create this ticket to track the disscusion about the possibility to implement original harvester self-healing.

There are several factors to consider, especially balance in early rushing tactics and the speed of heal, which was quite slow in original. Please, feel free to elaborate your opinon on this idea.

**Comment by Micr0Bit** [comment] 2016-05-05 15:43
if this is related to redalert ... we have repair-pads and mechanics ... you can even repair a harvester-husk to get a destroyed one back ... (the soviet counter-part to mechanics is the hijacker which "surprise surprise" is mostly good at stealing slow vehicles like harvesters , he still needs to get more polished though) 

D2k has this feature for harvesters ... good for D2k 

and this isnt balance-related at all ...since there is no issue with harvesters that could justify such a "buff"

**Comment by HenrytheSlav** [comment] 2016-05-05 16:29
The argument for is authenticity, the argument against would be balancing, at least that is how I see it. But yeah, this is just to gather opinions on this matter, since I can't find any mention of this being even considered.

**Comment by SoScared** [comment] 2016-05-05 22:10
If it's a slow heal then I don't see why not. It was so in the original game and as mentioned it won't affect balance too much. As a convenience I think casual players will appreciate not having to micro every low health harvester they've got.

**Comment by AoAGeneral** [comment] 2016-05-06 09:17
Is this for RA, TD, or both?

**Comment by HenrytheSlav** [comment] 2016-05-06 09:58
I meant RA, since I don't know if TD had this.
http://cnc.wikia.com/wiki/Harvester_%28Tiberian_Dawn%29 doesn't meniton it, while RA version has self-healing ability included.

**Comment by Lukemtesta** [comment] 2016-05-06 10:03
I agree with @SoScared - If it was by design in the original a slow heal is unlikely to unbalance the game - The heal should probably be significantly slower than the average rate a unit can chase and damage one continuously

**Comment by Townes27** [comment] 2016-05-06 14:29
The harvester in Red Alert 1 had the same selfheal property as the mammoth tank.

**Comment by abcdefg30** [comment] 2016-05-06 14:31
I'd be for a slow regeneration rate up to 50% health for harvesters in all mods.

**Comment by AoAGeneral** [comment] 2016-05-07 07:21
In regards to the regeneration effect is it possible to allow harvesters the regeneration if a silo is built?

**Comment by HenrytheSlav** [comment] 2016-05-07 07:41
Why, @AoAGeneral? That has no relation at all, if anything then after repair pad, but silo? We shouldn't try to force people use silos in this way. Silos are here, they work the way that is intended. Some players can find use for them, especially if reduced to single refinery. Giving them artifical atributes like this is very nonsensical.

**Comment by AoAGeneral** [comment] 2016-05-07 19:55
But that is the thing. Silos currently have no use lol

**Comment by reaperrr** [comment] 2016-05-15 20:50
Closed via #11254.

**Closed by reaperrr** 2016-05-15 20:50 UTC
Labels: Balancing
