### ISSUE TITLE
AI LAG when no attack path is available

### ISSUE THREAD

**Issue by Ayanami251379** [OpenRA/OpenRA#19212] opened 2021-03-04 06:53 UTC
## Issue Summary
While running on the TS mod on the bleed branch the AI seems to cause a massive LAG when no viable ground path is available for attacks.

## Reproduction
1) Create custom map with water separated terrain, add bridges that can be destroyed.
2) Run map with AI and destroy bridge after AI first attack.

Note, LAG is compounded when more AI is on map.

## Expected behavior
The expected reaction for traditional AI is to stop attacking any enemies that has no ground-based paths and then resume attacks once paths have been created.

Note, since OpenRA does not need traditional AI a choice can be added as a fall-back behavior to check for bridge repair options.

**Comment by Leo512bit** [comment] 2021-03-04 07:21
Yes the AI also doesn't seem how to deal with tunnels and kind of gives up

**Comment by Ayanami251379** [comment] 2021-03-04 07:58
@Leo512bit this question might be off topic, but I have not tested how units move via tunnels. Do units move through a tunnel if it is the shortest route to it's destination ?

**Comment by Leo512bit** [comment] 2021-03-04 18:43
I believe so

**Comment by abcdefg30** [comment] 2021-03-11 23:48
Duplicate of #12435.

**Closed as completed by abcdefg30** 2021-03-11 23:48 UTC
Labels: Bug
