### ISSUE TITLE
Openra change map crash

### ISSUE THREAD

**Issue by FIREOFDOOM** [OpenRA/OpenRA#7958] opened 2015-04-15 06:34 UTC
So I decided to try the new play test had some fun with the new features and downloaded a custom map for it. Note I go to uninstall it and when I reinstall it I go to a server and proceed to change the map and as soon as I hit that button the game crashes. Any help is appreciated

**Comment by Unit158** [comment] 2015-04-15 17:35
Uninstall what? The map or the playtest?

**Comment by pchote** [comment] 2015-04-15 17:36
From the playtest news posts:
> A note on map compatibility: already with the first playtest a new map format was introduced which is not backward-compatible with last October’s release-20141029. This means that if you have downloaded custom maps from the Resource Center or elsewhere, these maps will have been automatically updated to the new map format once you have run this or one of the previous playtests. If you later go back to the release version, it will not be able to parse the new map format and crash. You can avoid the problem by either deleting the contents of your map folder, or by making backups of the map folder and restoring that when you switch back to release-20141029.

**Comment by FIREOFDOOM** [comment] 2015-04-15 18:07
I uninstalled the play test sorry for not being so clear I was a bit frustrated when I wrote this.

**Comment by obrakmann** [comment] 2015-04-15 18:35
Ok. As mentioned above, please delete the contents of your map folder then. The maps in there have been automatically updated to a new format and the old release cannot read them anymore and crashes. You can find the location of the map folder for your operating system [here](https://github.com/OpenRA/OpenRA/wiki/Mapping#location).

**Comment by obrakmann** [comment] 2015-04-15 18:44
Duplicate of #7494.

**Closed by obrakmann** 2015-04-15 18:44 UTC
Labels: Crash

**Comment by FIREOFDOOM** [comment] 2015-04-15 18:51
Thx
