### ISSUE TITLE
Join already started game as a spectator if allowed by a game admin

### ISSUE THREAD

**Issue by Cr0s** [OpenRA/OpenRA#13062] opened 2017-04-04 05:05 UTC
Hi!

I'd like to discuss a feature that I mentioned in the subject. It seems to be not hard to implement, just to send simulation state to the player as it joins currently running game and then the player runs the same simulation as other players and specs in the currently running match.

It would be cool to be able to join a running game to spectate how it goes, might be useful on the tournaments as well.

Cheers.

**Comment by FrameLimiter** [comment] 2017-04-04 14:07
Duplicate of:  #7024 #6131 #3255

**Comment by pchote** [comment] 2017-04-04 14:09
Closing as duplicate.  As mentioned in the other tickets, this is actually extremely hard to implement.

**Closed by pchote** 2017-04-04 14:09 UTC
Labels: Idea/Wishlist
