### ISSUE TITLE
Playtest Debian Crash 

### ISSUE THREAD

**Issue by MajorTom6** [OpenRA/OpenRA#7965] opened 2015-04-17 01:26 UTC
Very strange bug I have, when playing the first skirmish after installing game works wonderfully, but after playing and launching a second one it crashes. I've replicated this two or three times and it happens within the playtest and official release. I have the latest mono version installed.

Report:
```Red Alert Mod at Version playtest-20150408
Operating System: Linux (Unix 3.16.0.4)
Runtime Version: Mono 3.12.1 (tarball Fri Mar  6 19:12:47 UTC 2015) CLR 4.0.30319.17020
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,OpenRA.Mods.Common.Widgets.Logic.LobbyCountry].get_Item (System.String key) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.SetupEditableFactionWidget (OpenRA.Widgets.Widget parent, OpenRA.Network.Slot s, OpenRA.Network.Client c, OpenRA.Network.OrderManager orderManager, System.Collections.Generic.Dictionary`2 countries) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at OpenRA.Game.SyncLobbyInfo () [0x00000] in <filename unknown>:0 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0```

**Comment by MajorTom6** [comment] 2015-04-17 01:30
And while running through terminal.

```tom@ground-control:~$ openra
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1600x900
Using resolution: 1024x768
Detected OpenGL version: 4.4
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn (playtest-20150408)
	d2k: Dune 2000 (playtest-20150408)
	modchooser: Mod Chooser (playtest-20150408)
	ra: Red Alert (playtest-20150408)
Loading mod: ra
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,OpenRA.Mods.Common.Widgets.Logic.LobbyCountry].get_Item (System.String key) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.SetupEditableFactionWidget (OpenRA.Widgets.Widget parent, OpenRA.Network.Slot s, OpenRA.Network.Client c, OpenRA.Network.OrderManager orderManager, System.Collections.Generic.Dictionary`2 countries) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at (wrapper delegate-invoke) <Module>:invoke_void ()
  at OpenRA.Game.SyncLobbyInfo () [0x00000] in <filename unknown>:0 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by ScottNZ** [comment] 2015-04-17 01:37
Duplicate of #7927

**Closed by ScottNZ** 2015-04-17 01:37 UTC

**Comment by MajorTom6** [comment] 2015-04-17 01:42
Mine has nothing to do with maps I believe, it is now also happening when just even launching the game.
