### ISSUE TITLE
[playtest-20190825] Cannot find / connect Servers 

### ISSUE THREAD

**Issue by klaas1** [OpenRA/OpenRA#17008] opened 2019-08-29 09:34 UTC
Issue Summary:

I cannot connect to any servers from within the playtest, also the forum cannot be reached for player information. However, whenever I try to connect from the release via "Incompatible version" -> "Switch", I can connect.  From within this server on the playtest, I cannot connect to other servers again (see screenshot).

#### System Information
- **Operating System: Ubuntu 18.04.3 LTS
- **.NET / Mono Version: 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1); ASP.NET Version: 4.0.30319.42000
- **OpenRA Version: playtest-20190825
- **Mod: RA

- Logs
No crash

- Screenshot
![OpenRA_002](https://user-images.githubusercontent.com/4115991/63928806-90614900-ca50-11e9-8c62-c7950971dc0c.png)

**Comment by teinarss** [comment] 2019-08-29 09:43
Looks similar to #16988

**Comment by abcdefg30** [comment] 2019-08-29 10:03
Yes, closing as duplicate of #16988. Thanks for the report nonetheless!

**Closed by abcdefg30** 2019-08-29 10:03 UTC
