### ISSUE TITLE
Subs firing without having a clear line of sight/aim

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13491] opened 2017-06-10 21:50 UTC
![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/6293391/27006569-88c57348-4e37-11e7-9e89-ffaa06b5445e.gif)

**Comment by deleted-user-1** [comment] 2020-06-06 16:09
Duplicate of #12635.

**Closed** 2020-06-06 16:40 UTC
Labels: Bug
