### ISSUE TITLE
Unable to detect CD Linux (Ubuntu 15.04)

### ISSUE THREAD

**Issue by dan9550** [OpenRA/OpenRA#8767] opened 2015-07-24 13:44 UTC
Having issues with OpenRA detecting my Tiberian Sun CD to install content.

The disc is mounted by default at /media/danny/TS1 which does not seem to work, i had a look at #5970 which suggested mounting the disc at /media/danny/cdrom.

This is not working either, RA is not working but TD did (using GDI disc and Allied disc). No mounting trick required for TD.

```
danny@zeus:~/Projects/OpenRA/OpenRA-Dan9550$ ls -l /media/danny/TS2
total 566411
-r-------- 1 danny danny        20 Jul 29  1999 00000001.tmp
-r-------- 1 danny danny   2119160 Jan 19  1999 autoplay.wav
-r-------- 1 danny danny    532480 Jul 17  1999 autorun.exe
-r-------- 1 danny danny       133 Jun  8  1999 autorun.inf
dr-x------ 1 danny danny      2048 Jul 29  1999 dxsetup
dr-x------ 1 danny danny      2048 Jul 29  1999 install
-r-------- 1 danny danny     26112 Jul 20  1999 license.doc
-r-------- 1 danny danny   3503740 Jul 27  1999 maps02.mix
-r-------- 1 danny danny 490656380 Jul 21  1999 movies02.mix
-r-------- 1 danny danny   8558956 Jul 25  1999 multi.mix
-r-------- 1 danny danny     23040 Jul 22  1999 readme.doc
-r-------- 1 danny danny      9300 Jul 22  1999 readme.txt
-r-------- 1 danny danny  51332268 Jul 20  1999 scores.mix
dr-x------ 1 danny danny      2048 Jul 29  1999 setup
-r-------- 1 danny danny     98304 Jul 17  1999 setup.exe
-r-------- 1 danny danny  11141812 Jul 15  1999 sidecd02.mix
-r-------- 1 danny danny  11340738 Jul 24  1999 sizzle1.vqa
-r-------- 1 danny danny        19 Jan 13  1999 ts2.dsk
-r-------- 1 danny danny    650266 Jul 14  1999 westwood.hlp
dr-x------ 1 danny danny      2048 Jul 29  1999 wolapi
```

**Comment by pchote** [comment] 2015-07-24 13:48
Duplicate of #3892?

**Comment by dan9550** [comment] 2015-07-24 13:50
Possibly? *facepalm* i will confirm tomorrow morning.

**Comment by dan9550** [comment] 2015-07-25 00:45
Yes looks like a duplicate of #3892 i was able to get the install to work by running thw following 

```
umount /media/danny/TS2
umount /media/dannt/cdrom
mount -o ro,check=relaxed /dev/sr0 /media/danny/cdrom
```

**Closed** 2015-07-25 01:14 UTC
