### ISSUE TITLE
cash-tick-sounds will stop when pressing escape

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12264] opened 2016-10-19 14:07 UTC
in multiplayer games , 20161015

__________________________________________________
there is also another soundbug ... that makes a music-track restart for unknown reasons ... i noticed this only one time so far ( so did @abcdefg30 )

**Comment by obrakmann** [comment] 2016-10-19 18:56
duplicate of #12235

**Closed by obrakmann** 2016-10-19 18:56 UTC
