### ISSUE TITLE
Crash related to aircraft entering aircraft

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20459] opened 2022-11-16 10:50 UTC
Note:
It is an edge case and I can fix it by simply add `TakeUpCellWhenLand`. Don't know if it is worth to fix, though.

## version
Third party mod as Shattered Paradise, version is [3d8733a](https://github.com/ABrandau/Shattered-Paradise-SDK/commit/3d8733a9fc288771e5ede9d87af3af06edf3a58c)

In this version we remove `TakeUpCellWhenLand` to test if aircraft enter aircraft still crash, and unfortunately still crash.

## log
[exception-2022-11-16T093650Z.log](https://github.com/OpenRA/OpenRA/files/10020831/exception-2022-11-16T093650Z.log)
```
OpenRA engine version cb73812
OpenRA Language: en
Shattered Paradise mod version ${DEV_VERSION}
on map d92505e9f538ae9d0ab06982f316944516697ef7 (Way to Uganda by Morton).
Date: 2022-11-16 09:36:50Z
Operating System: Windows (Microsoft Windows NT 10.0.19045.0)
Runtime Version: .NET CLR 6.0.11
Installed Language: zh (Installed) zh (Current) zh (Current UI)
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 880
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 891
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Air\Land.cs:line 238
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.Enter.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Enter.cs:line 141
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 639
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 654
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 823
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 876
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[sp-2022-11-16T091036Z.zip](https://github.com/OpenRA/OpenRA/files/10020881/sp-2022-11-16T091036Z.zip)

## Extra Info
![crash](https://user-images.githubusercontent.com/13763394/202161110-0cd1a370-f819-45ef-8d73-26350fc4c6b8.png)
It related to carrier code which use aircraft enter aircraft

**Comment by abcdefg30** [comment] 2022-11-16 10:56
I don't see a reference to `TakeUpCellWhenLand` in our code, so this is probably a problem of a custom trait? (The error message suggests, that that code is not removing previous influence.)

**Comment by dnqbob** [comment] 2022-11-16 11:23
> I don't see a reference to `TakeUpCellWhenLand` in our code,

Sorry for not put it clearly, I added  `TakeUpCellWhenLand` in SP and other mods to cancel all add influence to actor map for certain aircraft, for example, carrier drone, to fix this crash (I have met the crash before), which is mentioned in the disscusion of https://github.com/OpenRA/OpenRA/issues/20370#issuecomment-1278747329. 

> so this is probably a problem of a custom trait? (The error message suggests, that that code is not removing previous influence.)

It is related to custom trait, but custom trait and activity does not add any influence by using `Aircraft.AddInfluence()`. It is actually an edge case that: 

actor with `Aircraft`, `Enter(activity)` another actor with `Aircraft`

(Imagining an flying engineer hijack an aircraft)

**Comment by abcdefg30** [comment] 2022-11-16 16:18
I'm not sure if there is anything to do here on our end, `Land` already has a protection that you can't land twice on the same spot (and thus add your influence twice):
https://github.com/OpenRA/OpenRA/blob/b8a71215eb93e57eb22e1147fbed1f5bf07639d7/OpenRA.Mods.Common/Activities/Air/Land.cs#L112-L114

**Comment by Mailaender** [comment] 2024-07-21 10:25
We have the same crash in https://github.com/OpenHV/OpenHV/issues/1006 it is related to the carrier traits.

**Comment by Mailaender** [comment] 2024-07-21 11:03
How do you reproduce this in a vanilla engine? `TakeUpCellWhenLand` seems to be a parameter of your modified version of `Aircraft` and I understand that it is a workaround and not the cause. `TakeUpCellWhenLand` also seems redundant to the existing `OccupiesSpace` interface.

**Comment by Mailaender** [comment] 2024-07-21 11:06
Also, you are probably using a custom activity [EnterCarrierMaster](https://github.com/MustaphaTR/OpenRA/blob/SP-Bleed-Branch/OpenRA.Mods.AS/Yupgi/EnterCarrierMaster.cs) so why don't you apply the fix there?

**Comment by dnqbob** [comment] 2024-07-21 12:59
> How do you reproduce this in a vanilla engine

Very hard for a stable reproduce, replay is very important.

**Comment by dnqbob** [comment] 2024-07-21 13:06
> Also, you are probably using a custom activity [EnterCarrierMaster](https://github.com/MustaphaTR/OpenRA/blob/SP-Bleed-Branch/OpenRA.Mods.AS/Yupgi/EnterCarrierMaster.cs) so why don't you apply the fix there?

It is imposible to fix it in downstream code: after many trying I think the causing is within `Land` and `Enter`, and I cannot avoid those 2 activities when making my own [EnterCarrierMaster](https://github.com/MustaphaTR/OpenRA/blob/rv-engine/OpenRA.Mods.AS/Activities/EnterCarrierMaster.cs) and tackle influence outside of `Aircraft` and `Land` is ineffective.

**Comment by dnqbob** [comment] 2024-07-21 13:40
All I have known on this issue: when I added `TakeUpCellWhenLand` which cancelled all add-influence to actor map, the problem solved. I know it is a work around but it is the only method as far as I know to make the replay not crashed, and the crash never happens since I apply  `TakeUpCellWhenLand=true` to carrier spawn.

So @Mailaender the crashed replay is very important if you want to apply your own exploration on this issue.

**Comment by Mailaender** [comment] 2024-07-21 15:12
Is this fix https://github.com/Inq8/CAmod/commit/c6a348284f16d449ac1d5659ab6dd2fcc883e8e4 related or something else?

**Comment by dnqbob** [comment] 2024-07-22 02:44
> Is this fix https://github.com/Inq8/CAmod/commit/c6a348284f16d449ac1d5659ab6dd2fcc883e8e4 related or something else

It is better to ask @Inq8 and @darkademic that if this kind of crash happens again.

**Comment by dnqbob** [comment] 2024-07-22 07:46
And if they have a replay testcase that crash before fix and won't crash after fix, it will definitely prove the effectiveness of their patch.

**Comment by darkademic** [comment] 2024-07-22 08:18
Don't have any replays as it was a while ago, but it seems to be the same crash.

IIRC I replicated it by building lots of drone carriers and using them to attack a large number of submarines - then the crash would happen if drones were launched from the carriers at the exact moment their target submarine submerged (assume it'd happen with any cloaking target).

**Comment by Mailaender** [comment] 2024-07-22 15:19
Is https://github.com/OpenRA/OpenRA/pull/20401 the root cause for this?

**Comment by dnqbob** [comment] 2024-07-22 16:03
I guess you mean a regression in #20401?  I think it is not the cause.  #20401 makes aircraft updates influence when they get too close to terrain, but in my and your carrier testcase, aircraft land on another aircraft in the middle air, which is obviously higher than MinAirborneAltitude so there is only chance of removal of influence, instead of adding influence.

**Comment by dnqbob** [comment] 2024-07-23 04:28
In openra engine, I think we can create some testcase based on "Aircraft enter aircraft", like a flying hijacker to reproduce this bug.

**Comment by Mailaender** [comment] 2024-07-27 09:51
Closing here as this can be fixed in downstream code like this. https://github.com/OpenHV/OpenHV/commit/e7197c75d97930f46568b18d212ffd86d2ea7956

**Closed as not planned by Mailaender** 2024-07-27 09:51 UTC
Labels: Crash
