### ISSUE TITLE
Add shortcut for "move,land and deploy"

### ISSUE THREAD

**Issue by marcos111** [OpenRA/OpenRA#9374] opened 2015-09-19 09:08 UTC
Hi!

Is possible add the hotkey for "move to selected point and deploy" for the chooper, APC .....? I think it will be very helpful.

thanks

**Comment by r34ch** [comment] 2015-09-19 12:08
shift + F would be a nice feature

**Comment by pchote** [comment] 2015-09-19 12:12
Duplicate of #4774.  You should be able to do this by holding shift while issuing the deploy order, but this doesn't work for transports.

**Closed by pchote** 2015-09-19 12:12 UTC
Labels: Idea, Question

**Comment by marcos111** [comment] 2015-09-19 12:28
Ok, thanks
