### ISSUE TITLE
Setting War Factory as Primary building doesn't work when having too many factories.

### ISSUE THREAD

**Issue by dariuszsikorski** [OpenRA/OpenRA#10173] opened 2015-12-03 19:31 UTC
When too many war factories are in the game, setting one as "primary" doesn't work anymore. Instead always the new placed factory is set as the primary and the only way to have a new spawn spot is to build another war factory.

Tested in Red Alert mod with Russian faction.

Regards, Ant ₪

**Comment by obrakmann** [comment] 2015-12-03 20:01
Can't reproduce on the latest playtest nor current bleed.

You may not be aware, but there *are* situations where units will not come out of your primary building, namely in the case where the exit of the primary building is blocked. In that case the exit of the last (ie. the newest) building of the type will be used instead (or the one before that if that's blocked, too, and so on). Please check if that may have been the case. Otherwise please share the replay.

**Comment by epicelite** [comment] 2015-12-03 20:49
I've been meaning to post about this but keep forgetting so here goes!

This bug effects ALL factories! Barracks, War Factory, Airfield, Helipad, Sub Pen, Ship Yard etc.

How to reproduce: 
1)Build one or more factory of the same type. 
2)Set one of them to primary
3)Build another of that same factory
4)That newest building will be the "PRIMARY" even though the game says otherwise.

However, I just tested it and it appears to be fixed in the latest playtest so, IDK.

**Comment by obrakmann** [comment] 2015-12-03 21:06
I can't reproduce that on the current stable release either. But anyway, if you say it's fixed in the playtest, I'm closing here.

**Closed by obrakmann** 2015-12-03 21:06 UTC
Labels: Bug
