### ISSUE TITLE
PCX support for individual cameos

### ISSUE THREAD

**Issue by Deformat** [OpenRA/OpenRA#3309] opened 2013-05-17 19:43 UTC
Basically, allow a cameo to have a specific palette, or allow it to be loaded as a .PCX file.

**Comment by Mailaender** [comment] 2015-06-12 19:10
> allow a cameo to have a specific palette

Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/8464.

**Comment by pchote** [comment] 2015-11-22 01:57
We now support per-icon palettes, which should be sufficient.

**Closed by pchote** 2015-11-22 01:57 UTC
Labels: Feature

**Comment by Mailaender** [comment] 2015-11-22 06:15
I guess the specific request for PCX is because of legacy compatibility with RA2 mods?

**Comment by GraionDilach** [comment] 2015-11-22 10:09
Kinda but those RA2 modders should know that any cameo PCX they have can be separated into an SHP-PAL combination with XCC Mixer in four clicks. I'm fine with this.
