### ISSUE TITLE
Game crash: a new guard page for the stack cannot be created

### ISSUE THREAD

**Issue by yili001** [OpenRA/OpenRA#19592] opened 2021-08-07 09:55 UTC
## System Information

- Operating System:  Windows10 20H2
- OpenRA Version: I don't know if it's the engine version or not, but the product version is release-20210321 which I saw it in windows control panel.
- OpenRA Mod: none
- Source: Official download package from official website
- For self-compiled or third-party packages: none

## Exception log

```
Sorry guys , I didn't find a file named exception.log in my C:\Users\username\AppData\Roaming\OpenRA\Logs path,
the only files in this directory is following:
08/07/2021  05:38 PM                 0 client.log
08/07/2021  05:42 PM           125,757 debug.log
08/07/2021  05:38 PM                 0 geoip.log
08/07/2021  05:42 PM        35,669,067 graphics.log
08/07/2021  05:38 PM                 0 lua.log
08/07/2021  05:38 PM                 0 nat.log
08/07/2021  05:42 PM            16,175 perf.log
08/07/2021  05:38 PM               422 server.log
08/07/2021  05:38 PM                 0 sound.log
```

## Replay

This error happens randomly, so I am not sure if the replay helps.

## Additional information

The circumstance: openra RedAlert, skirmish mode, single player, 2v2, map name called "Ridges"
the error information: 
A modal will popup: title is OpenRA Red Alert System error, and the message is: **a new guard page for the stack cannot be created.**
My hardware information: 
CPU:11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Video Card: no video card

**Comment by pchote** [comment] 2021-08-07 10:01
I had never heard of that error message before, it is not generated by OpenRA itself.

Searching the internet suggests that this is caused by corrupted files in your Windows installation.

There is no specific advice we can offer since this is not an OpenRA issue, but some of the suggestions from https://www.google.com/search?q=%22a+new+guard+page+for+the+stack+cannot+be+created%22 might help.

**Comment by pchote** [comment] 2021-08-07 10:06
The next release of OpenRA will be removing the dependency on Window's built in .NET installation, so that will hopefully work for you even if you can't solve the problem here. I'll close this issue since I don't think there is anything more we can do here.

**Closed as completed** 2021-08-07 10:07 UTC
Labels: Crash

**Comment by yili001** [comment] 2021-08-07 10:30
Thanks for your reply, I am looking - forward to see it😊
