### ISSUE TITLE
Bridge repair appears through fog of war

### ISSUE THREAD

**Issue by TheGrinningSkull** [OpenRA/OpenRA#13614] opened 2017-07-09 01:32 UTC
Opponents are able to see bridge repairs when map is explored despite not actively scouting the bridge.  This thwarts any surprise attacks bridge users might have and affects naval maps with bridge mechanics in play.

**Comment by Mailaender** [comment] 2017-07-09 09:40
Duplicate of https://github.com/OpenRA/OpenRA/issues/3654.

**Closed by Mailaender** 2017-07-09 09:40 UTC
