### ISSUE TITLE
Visual glitches when some units exit the weapons factory

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18008] opened 2020-04-29 21:31 UTC
## Issue Summary

As seen in the examples below, there are visual glitches when units exit the gdi weapons factory.

## Reproduction

Build one of the units in the examples and pause the game when the unit is about to exit to see the glitches.

## Expected behavior

Units should be moving out through the opened factory door (not earlier). Their spawn must be in the back of the weapons factory so that they do not suddenly "appear" when the door is open.

### ORA TS

<details>

![sensor_exit_wf](https://user-images.githubusercontent.com/59416324/80648672-dd2e7100-8a70-11ea-99d9-211443c76707.png)
![hover_exit_wf](https://user-images.githubusercontent.com/59416324/80648674-de5f9e00-8a70-11ea-81ac-226ac2ff0a02.png)
![mkii_exit_wf](https://user-images.githubusercontent.com/59416324/80648677-def83480-8a70-11ea-817f-9347ed6b9427.png)

</details>

### Original TS

<details>

![og_hover_exit_wf](https://user-images.githubusercontent.com/59416324/80648721-f0d9d780-8a70-11ea-9a63-9ca718e63fc5.gif)
![og_sensor_exit_wf](https://user-images.githubusercontent.com/59416324/80648723-f1726e00-8a70-11ea-90fc-b48ef3b00df0.gif)
![og_mkii_exit_wf](https://user-images.githubusercontent.com/59416324/80648719-efa8aa80-8a70-11ea-95cd-c29dd0156b1a.gif)

</details>

**Comment by pchote** [comment] 2020-04-29 21:49
This is our standard voxels-dont-z issue. Closing as duplicate of the issues that I can’t conveniently look up on mobile.

**Closed as completed by pchote** 2020-04-29 21:49 UTC
Labels: Bug
