### ISSUE TITLE
openRA crash on start openSUSE Leap 42.2 XFCE

### ISSUE THREAD

**Issue by vincentvandenbergh** [OpenRA/OpenRA#13091] opened 2017-04-09 15:29 UTC
opening with the terminal gives this:
```

No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL version: 3.0 Mesa 11.2.2
Using default sound device
ALSA lib pcm_dmix.c:1077:(snd_pcm_dmix_open) unable to create IPC shm instance
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Invalid argument
Failed to open device. Falling back to default
ALSA lib pcm_dmix.c:1077:(snd_pcm_dmix_open) unable to create IPC shm instance
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Invalid argument
Renderer initialization failed. Check graphics.log for details.
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0011b] in <c04fecf34d0e4bf383d47cf37435b845>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in <c04fecf34d0e4bf383d47cf37435b845>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <c04fecf34d0e4bf383d47cf37435b845>:0 

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
vincent@linux-zp7s:~> 
```
```
exception-2017-04-09T150052Z.log tells me: 
> Date: 2017-04-09 15:01:46Z
> Operating System: Linux (Unix 4.4.49.16)
> Runtime Version: Mono 4.6.1 (Stable 4.6.1.3/abb06f1 Thu Oct 20 14:33:14 UTC 2016) CLR 4.0.30319.42000
> Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
>   at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x0011b] in <c04fecf34d0e4bf383d47cf37435b845>:0 
>   at OpenRA.Program.Run (System.String[] args) [0x00007] in <c04fecf34d0e4bf383d47cf37435b845>:0 
>   at OpenRA.Program.Main (System.String[] args) [0x0004f] in <c04fecf34d0e4bf383d47cf37435b845>:0 

```
Graphics.log says:

```
System.InvalidOperationException: Can't create OpenAL device
  at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor (System.String deviceName) [0x0008a] in <b012b52045114146ad31c0bf89e2a7d2>:0 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateSound (System.String device) [0x00001] in <b012b52045114146ad31c0bf89e2a7d2>:0 
  at OpenRA.Sound..ctor (OpenRA.IPlatform platform, OpenRA.SoundSettings soundSettings) [0x0001d] in <c04fecf34d0e4bf383d47cf37435b845>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x001d3] in <c04fecf34d0e4bf383d47cf37435b845>:0 
System.InvalidOperationException: Can't create OpenAL device
  at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor (System.String deviceName) [0x0008a] in <b012b52045114146ad31c0bf89e2a7d2>:0 
  at OpenRA.Platforms.Default.DefaultPlatform.CreateSound (System.String device) [0x00001] in <b012b52045114146ad31c0bf89e2a7d2>:0 
  at OpenRA.Sound..ctor (OpenRA.IPlatform platform, OpenRA.SoundSettings soundSettings) [0x0001d] in <c04fecf34d0e4bf383d47cf37435b845>:0 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x001d3] in <c04fecf34d0e4bf383d47cf37435b845>:0 
```

**Comment by obrakmann** [comment] 2017-04-14 20:07
> ALSA lib pcm_dmix.c:1077:(snd_pcm_dmix_open) unable to create IPC shm instance

This is your problem.  There's something wrong with your sound driver. You can try plugging in speakers or headphones, this fixes sound-related problems sometimes on Linux, but if not, you need to check your OS configuration.

I'm sorry, but there's nothing we can do here, so closing.

**Closed by obrakmann** 2017-04-14 20:07 UTC
Labels: Crash, OS: Linux

**Comment by pchote** [comment] 2017-04-14 20:10
I believe this is a duplicate of #12300 / #12526.  On our end we could fall back to a dummy sound device (but in a better way than we used to) instead of crashing.

**Comment by abcdefg30** [comment] 2017-04-22 12:04
From http://www.openra.net/news/playtest-20170408/#comment-3265088521:
> apparently, openSUSE had a flaw in the ALSA sound software. It is patched now, and openRA works again. I think more players on Linux were affected, but all should be helped with installing the latest ALSA software (1.1.3-8.6.1) with plugin and utilities on version 1.1.1-1.3 and 1.1.2-1.2
