### ISSUE TITLE
CancelActivity doesn't stop attack activity

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13762] opened 2017-08-02 05:37 UTC
https://youtu.be/zDa8bFbBHsI

I made rage generator, which at the end of the Rage condition, CancelActivity() is called so that units will stop doing friendly fire. However, that doesn't work on some attack activities. I'm not sure why because "S" key, the stop order, even works on force fire on the ground.

I did verify that CancelActivity is run on the actor that's still attacking after the enraging effect.

After some examination now I see it is TRAIT that's doing the attack (AttackFollow)
I need to call OnStopOrder() in the attack activity but that's not possible due to protection.
I can't issue stop order to units from the code because that will trigger anti-cheat function of ORA.

**Comment by abcdefg30** [comment] 2017-08-02 18:08
Duplicate of https://github.com/OpenRA/OpenRA/issues/7086#issuecomment-66019719 ?

**Comment by forcecore** [comment] 2017-08-02 18:13
Seems to have some relation because this has to do with AttackBase and the Activity interaction. However, I'd say it is a duplicate because you can stop the turreted units force firing on the ground (1 of the comment) and (2) is on stance. This issue is more about canceling the attack from the activity side or from some other trait.

**Comment by GraionDilach** [comment] 2017-08-02 21:14
Pretty sure that the 1) listed there is related. AttackFrontal trait is perfectly okay with invalidating targets on the fly, say, having a conditrion granted to damaged units and a Repair targetable value basede on said condition will allow medics/mechanics to autoacquire and perfectly switch between targets but not to a setup akin to the RA2 IFV due to AttackTurreted.

Also, #12856.

**Comment by Inqubi** [comment] 2017-08-05 21:53
Not sure if its related, but Aircraft: with AbortOnResupply: False, ignore new fire orders & sometimes movement orders aswell once resupplied.

**Comment by matjaeck** [comment] 2019-10-05 21:45
The activity code has been refactored so this may be outdated now. Perhaps the issue can be addressed in @tovl's `Attack` refactor otherwise.

**Comment by GraionDilach** [comment] 2019-10-05 23:55
No, this got fixed in these last months. The OP usage works properly now - tested on latest codes multiple times.

**Comment by reaperrr** [comment] 2019-10-06 00:13
Closing as fixed then.

**Closed by reaperrr** 2019-10-06 00:13 UTC
Labels: Bug
