### ISSUE TITLE
feature request, option to disable shell map animation

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#17155] opened 2019-09-27 16:33 UTC
in older versions it was possible to disable and/or stop the shell map (the map displayed as background in the game menu) from animating.

it would be nice to have this feature back. now with reach release i make a custom patch to disable the shell map animation in the map lua code.

the moving of the map makes me feel dizzy, gives the feeling or road sickness quite quickly.

**Comment by abcdefg30** [comment] 2019-09-27 16:38
Duplicate of #13279.

**Closed by abcdefg30** 2019-09-27 16:38 UTC
