### ISSUE TITLE
Hide cloak/decloak sounds under shroud

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#12850] opened 2017-02-25 11:53 UTC
As of now in TD, when a stealth tank is on the playing field everyone else in the game knows as well and if they are smart they can even try to count how many this person is acquiring. On top of this it also tells the enemy that you have a Temple of Nod. My suggestion is to only allow the sound to be heard when in the players active view.

**Comment by AoAGeneral** [comment] 2017-02-26 11:11
Duplicate of #9487 ? 

I do agree that things under fog should be somewhat muted. But I disagree of the cloak sound being muted upon first unit construction. It helps let the player know that stealthers are now on the map and start thinking of a counter.

As for the temple you still need to scout it to find it. Hearing stealth tanks and knowing a temple exists applies to com center tech in which seeing medium tanks/light tanks is a give away that the person has gone com tech.

**Comment by pchote** [comment] 2017-02-26 11:12
IMO this should apply to *all* sounds, not just cloak.  It doesn't make sense that you can hear battles that are happening on the other side of the map from where your units are.

**Comment by anjew175** [comment] 2017-02-26 11:46
> Duplicate of #9487 ?

I think it is, my mistake.

> As for the temple you still need to scout it to find it. Hearing stealth tanks and knowing a temple exists applies to com center tech in which seeing medium tanks/light tanks is a give away that the person has gone com tech.

The difference is you still need to scout those tanks, they dont make a global sound.

>  It helps let the player know that stealthers are now on the map and start thinking of a counter.

Then every unit should have a global sound so that people can make a counter.
Right now, discerning which Nods vehicles are being made requires little to no scouting from the opponent, depending on the map. This in turn allows players to allows know what tech level a Nod player is at. Finding the temple is only a problem 5 minutes after its been made. This is why I usually wait a few minutes before making stealth tanks.

> IMO this should apply to all sounds, not just cloak. It doesn't make sense that you can hear battles that are happening on the other side of the map from where your units are.

I also agree with this however, as was discussed, i think it needs to be either around the edge of the shroud or based on whether a shot lands inside active vision so that you can here artillery or bikes shooting your harvester under shroud

**Comment by AoAGeneral** [comment] 2017-02-26 14:01
I disagree that it should be all sounds. Im still in favor of allowing the sounds toggled by the first built Stealth Tanks to make a sound. This also goes with commandos.

Nod vehicles are still unscouted despite spotting the planes. Despite of this GDI factions lose heavily to Nod as it is of this current release and will depend on how the roles play in the playtest/next release. Stealth Tanks are extremely powerful and outrange a lot of vehicles to help combat head on fights.

Silencing the first built unit changes the gameplay completely to a point where you can have them idle with very little to not detection scouted. If you at least have the idea that they were built spreading of infantry or structures made to detect can be best utilized.

Silencing the sound will also give some paranoid reactions in which you never know if they are even built in the first place. SCBW is a prime example of even seeing the stealth units without a revealing mechanic done to allow time to come up with a counter.

**Comment by GraionDilach** [comment] 2017-02-26 16:41
>I disagree that it should be all sounds. Im still in favor of allowing the sounds toggled by the first built Stealth Tanks to make a sound. This also goes with commandos.

Sounds like something you should use AnnounceOnBuild for instead of relying on an obvious bug/issue.

**Comment by abcdefg30** [comment] 2020-08-29 18:04
Closing as covered by the more general #9487.

**Closed by abcdefg30** 2020-08-29 18:04 UTC
Labels: Balancing, Tiberian Dawn
