### ISSUE TITLE
LAG when units are stuck

### ISSUE THREAD

**Issue by gijs370** [OpenRA/OpenRA#5591] opened 2014-06-09 19:39 UTC
First of all, thank you for recreating the game i loved a decade ago :)

There seems to be a problem with units getting stuck causing lag. When i play this with a friend, the game sometimes gets really slow. I usually ask if the other party has some units stuck, and when he moves them, the games runs normal again. 

It is a minor inconvenience, and easily fixed by moving units. However i of course can't ask the AI the same question, which is why the games almost halts when i play against AI. 

Units are stuck when you give them an order to move, but other units or buildings block are in the way. It seems that the unit won't stop trying to get out.

The task manager usually shows that OpenRA is using about 10% of the CPU. When a few units get stuck, then the CPU uses weirdly drops to below 5%. It is actually using less CPU.

I think this problem could be fixed if the behavior of units is changed or if the order is canceled after X amount of time when there is no way to get to the destination. 
##

**Comment by obrakmann** [comment] 2017-06-03 12:06
Closing as reverse duplicate of #12435, as that has more discussion.

**Closed by obrakmann** 2017-06-03 12:06 UTC
Labels: Pathfinding, Performance
