### ISSUE TITLE
Help I Can't Start My OpenRA!

### ISSUE THREAD

**Issue by V1NnYT** [OpenRA/OpenRA#12313] opened 2016-10-29 05:06 UTC
Date: 2016-10-29 05:02:51Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

this was the log i got for the crash. idk what to do L("A" L)

**Comment by cjshmyr** [comment] 2016-10-29 05:47
OpenRA now requires at least version 4.5 of the .NET framework, looks like you are on 4.0. Can grab it [here](https://www.microsoft.com/en-ca/download/details.aspx?id=42642).

**Comment by V1NnYT** [comment] 2016-10-29 05:54
![microsoft net framework 4 5 2 29_10_2016 1_53_16 pm](https://cloud.githubusercontent.com/assets/23132732/19827505/20516a82-9ddf-11e6-944a-56b182340a22.png)

I Already DId. It's Still Having The Problem

**Comment by yaaaaa** [comment] 2016-10-29 09:02
OpenGL support?

**Comment by pchote** [comment] 2016-10-29 10:45
Please include the contents of the graphics.log.

**Comment by V1NnYT** [comment] 2016-10-29 11:51
here's the graphic log

System.InvalidOperationException: Can't create OpenAL device
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)
   at OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings)
   at OpenRA.Game.Initialize(Arguments args)
System.InvalidOperationException: Can't create OpenAL device
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)
   at OpenRA.Sound..ctor(IPlatform platform, SoundSettings soundSettings)
   at OpenRA.Game.Initialize(Arguments args)

**Comment by V1NnYT** [comment] 2016-10-31 15:27
okay. Now I Noticed What's The Problem. Its Quite An Embarrassing For Me Not To Notice The Problem. Thanks For The Participants. And Sorry For Wasting Your Time For My Mistake.

**Comment by chrisforbes** [comment] 2016-11-13 06:40
Sounds like you solved this. Reopen if that's not the case.

**Comment by V1NnYT** [comment] 2016-11-14 04:00
I Noticed That I play My Computer without my earphones, and nothing else is connected. soo it doesn't work.. sorry for wasting anybody's time.

**Comment by WolfGaming** [comment] 2016-11-14 12:21
Wait so OpenRA doesnt work if the computer has no audio device connected?

**Comment by Biofreak1987** [comment] 2016-11-14 17:22
I can confirm on my windows 10 machine that both the stable and bleed don't boot if there are no audio devices connected/installed:

![rundll32_2016-11-14_18-19-25](https://cloud.githubusercontent.com/assets/4711816/20275030/30844054-aa97-11e6-91af-c1735fa0d171.png)

**Comment by GraionDilach** [comment] 2016-11-14 18:20
Duplicate of #12300 then.

**Closed** 2016-11-14 18:33 UTC
Labels: Audio, Crash, OS: Windows

**Comment by corsel** [comment] 2018-03-13 18:25
had the same problem, noticed the solution here to realize that i previously disabled my audio output from device settings. so thanks i guess :D

**Comment by corsel** [comment] 2018-03-13 18:30
had the same problem, noticed the solution here to realize that i previously disabled my audio output from device settings. so thanks i guess :D
