### ISSUE TITLE
Maps editing the Map Selections Options

### ISSUE THREAD

**Issue by ben132** [OpenRA/OpenRA#20517] opened 2022-12-06 00:27 UTC
It would be cool if the map creators could add or remove factions in the map, for example have a Faction that cannot be played in a given map, like no SubFactions, or Custom Factions added to the map.  Whilst also editing the options in the Map Selection, like custom game modes, custom factions, no subfactions, editing predefined factions, dropdown, new rules etc.

**Comment by Leo512bit** [comment] 2022-12-06 02:14
You can do all of that expect for custom factions.

**Comment by ben132** [comment] 2022-12-06 18:11
So maps can edit the dropdowns lists, and the checkboxes for custom gamemodes? or do you mean that you can have custom game modes within the maps itself.

**Comment by Leo512bit** [comment] 2022-12-06 23:42
Look at: https://resource.openra.net/maps/42983 and: https://github.com/OpenRA/OpenRA/wiki/Map-Options

**Comment by ben132** [comment] 2022-12-07 10:20
Thanks xD

**Comment by PunkPun** [comment] 2022-12-07 10:30
Duplicate of #3012?

**Comment by Leo512bit** [comment] 2022-12-07 17:41
Yeah, I think this can be closed.

**Closed as not planned** 2022-12-07 19:38 UTC
Labels: Idea/Wishlist
