### ISSUE TITLE
The game crashes on start up.

### ISSUE THREAD

**Issue by CRITAWAKETS** [OpenRA/OpenRA#8982] opened 2015-08-07 16:51 UTC
OpenRA seems to crash on start up for me...

So far this is probably one of 3 things.

1.Windows 10 does not support OpenRA.

2.The version i use(Playtest 20150628)is not working for me.

3.My install is corrupted.

Crashlog from exception.log:
Mod Chooser Mod at Version playtest-20150628
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.TypeInitializationException`: The type initializer for 'OpenRA.Graphics.SpriteFont' threw an exception.
Inner Exception of type `System.DllNotFoundException`: Unable to load DLL 'freetype6.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  TypeName=``
     at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor()
   at OpenRA.Graphics.SpriteFont..cctor()
   at OpenRA.Graphics.SpriteFont..ctor(String name, Int32 size, SheetBuilder builder)
   at OpenRA.Graphics.Renderer.<InitializeFonts>m__1(KeyValuePair`2 x)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at OpenRA.Graphics.Renderer.InitializeFonts(Manifest m)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by penev92** [comment] 2015-08-07 16:55
You need Microsoft Visual C++ Redistributable 2010 or later.

**Comment by CRITAWAKETS** [comment] 2015-08-07 17:25
Visual C++ Does nothing... I guess a reinstall is necessary...

**Comment by penev92** [comment] 2015-08-07 17:31
What do you mean "does nothing" ?

**Comment by Mailaender** [comment] 2015-08-07 17:57
Duplicate of https://github.com/OpenRA/OpenRA/issues/8493.

**Closed by Mailaender** 2015-08-07 17:57 UTC
Labels: Crash, OS: Windows, Packaging
