### ISSUE TITLE
AI attempts to kill tanks and base defences with dogs

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#18478] opened 2020-08-02 08:38 UTC
Dogs chase tanks

**Comment by abcdefg30** [comment] 2020-08-02 09:59
Basically the same as #3468.

**Comment by PunkPun** [comment] 2020-08-02 11:43
Then it might be good to merge this issue into #3468

ping @Mailaender

**Comment by PunkPun** [comment] 2022-07-05 13:06
ping @Mailaender

**Comment by Mailaender** [comment] 2022-07-05 14:39
Duplicate of #3468

**Closed as not planned by Mailaender** 2022-07-05 14:39 UTC
Labels: Bug, AI
