### ISSUE TITLE
aftermatch expansion: can not import music

### ISSUE THREAD

**Issue by legluondunet** [OpenRA/OpenRA#13343] opened 2017-05-24 19:10 UTC
Hello,

OpenRA can not import music from my mounted iso (627 Mo), I obtain this error log from install.log:

System.IO.DirectoryNotFoundException: Could not find a part of the path "/usr/lib/openra/SETUP/INSTALL/PATCH.RTP".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x001cf] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.OpenRead (System.String path) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic.ExtractFromPackage (OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic+ExtractionType type, System.String path, OpenRA.MiniYaml actionYaml, System.Collections.Generic.List`1[T] extractedFiles, System.Action`1[T] updateMessage) [0x00033] in <a37e43d8e61a40c988b8127309461bed>:0 
  at OpenRA.Mods.Common.Widgets.Logic.InstallFromDiscLogic+<InstallFromDisc>c__AnonStorey5.<>m__1 () [0x00238] in <a37e43d8e61a40c988b8127309461bed>:0 

Thank you for your help.

**Comment by Walkman100** [comment] 2017-08-25 03:40
Dupe of #12009

**Comment by pchote** [comment] 2017-08-25 06:26
This was fixed by #13760.

**Closed by pchote** 2017-08-25 06:26 UTC
Labels: Crash, OS: Linux
