### ISSUE TITLE
Planes disappearing near the bottom map edge

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7826] opened 2015-04-02 09:30 UTC
Migs and Yaks (other RA units seem to be fine) disappear (as if they were outside of the map) one or two tiles too early before reaching the **bottom edge.**

How to recreate:
- order a Yak/Mig toward the **bottom edge** of the map (right next to it)
- when it's approaching the edge (just a few tiles before) order it to move along the edge
- it will start its **turning animation** and disappear (the selection box remains around it)

It reappears moments later or if you move it further into the map.

![yak_under](https://cloud.githubusercontent.com/assets/10639257/6961389/d1960e4a-d92a-11e4-8195-4177647a8266.jpg)

**Comment by obrakmann** [comment] 2015-04-02 19:20
It seems this was caused by #7487. The renderer probably does not take the altitude into account?

**Comment by pi99y** [comment] 2015-04-06 05:57
This still remains a problem in "Playtest 20150405". It's just a little less obvious now since it's limited to less tiles. Steps to reproduce are the same, but since it has more limited "range" its just a bit harder to reproduce (but still quite easy).

**Comment by pi99y** [comment] 2015-04-08 19:11
Fixed / Can't recreate it anymore in Playtest-20150408

**Comment by abcdefg30** [comment] 2015-04-11 17:44
> Fixed / Can't recreate it anymore in Playtest-20150408

I guess this is "fixed" by #7842 and #7866 then.

**Comment by penev92** [comment] 2015-04-11 17:47
Let's keep this open until the real fix though.

**Comment by pchote** [comment] 2015-07-25 22:24
This was fixed by one of my heightmap-shroud preparation PRs.

**Closed by pchote** 2015-07-25 22:24 UTC
Labels: Bug, Red Alert
