### ISSUE TITLE
Actors in the map editor use more space than it is needed.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#18638] opened 2020-09-22 13:42 UTC
As you can see on the following images, the Tiberian Sun mod has a problem sorting actors in the editor sidebar, the actors would be displayed at their max dimension and sometimes they are resized down, this is troublesome when scrolling to find the actor you require to decorate a map.

In the pictures the pictures shown i use an edited sidebar window that is bigger than the one from tiberian sun, but this does not solve actor size being a problem.

I have a couple of suggestions, either a scale option for the sidebar alone, or an option to give custom art to actors ONLY IN THE SIDEBAR, otherwise it could be confusing for mappers.

![unknown](https://user-images.githubusercontent.com/11763228/93889592-c3135a80-fcbf-11ea-917e-49f16d729dcf.png)
![unknown (1)](https://user-images.githubusercontent.com/11763228/93889597-c4448780-fcbf-11ea-8e12-d4fe64fb30ae.png)
![unknown (2)](https://user-images.githubusercontent.com/11763228/93889600-c4dd1e00-fcbf-11ea-9115-d822c6af8c07.png)

**Comment by PunkPun** [comment] 2022-07-07 22:03
duplicate of #10138

**Closed as not planned** 2022-07-08 07:23 UTC
Labels: Bug, Map Editor, UI
