### ISSUE TITLE
Units giving up on move orders

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#14163] opened 2017-10-12 02:50 UTC
It feels like groups of units are struggling and giving up on their moves before reaching destination. Attack-move seems fine though. Easy enough to do with tanks or any mix of units, bonus points for trees or other obstacles causing it too

Before/after 
![image](https://user-images.githubusercontent.com/566742/31476805-aa2ca242-aec5-11e7-93b0-ef2637d16bbf.png)

Edit: Attack Move for comparison
![image](https://user-images.githubusercontent.com/566742/31480001-71169bee-aed8-11e7-9116-f9cee389e3b2.png)

Reproduced on playtest-20170930 and bleed

**Comment by anjew175** [comment] 2017-10-12 03:00
This is still a problem with Attack Move. I thought this was in the release version too but I could be wrong. It seems anytime a unit has to devise new orders to get around an obstacle, they either succeed or just sit there.

**Comment by netnazgul** [comment] 2017-10-12 04:35
It's in both release and playtest. It is also an issue when War Factory rally point is placed on a tile that is occupied/not passable - new units just clutter the WF exit

**Comment by FRenzy-OpenRA** [comment] 2017-10-12 07:15
#5968 ?

**Comment by abcdefg30** [comment] 2017-10-12 08:01
Looks like a duplicate of #5968, indeed.

**Closed by abcdefg30** 2017-10-12 08:01 UTC
