### ISSUE TITLE
Helicopter: Repair and Ammoreful command with shift leads to crash #crash

### ISSUE THREAD

**Issue by derestle** [OpenRA/OpenRA#10807] opened 2016-02-21 23:20 UTC
Damaged helicopter sending to repair and after that to Ammorefill with Shift pressed leads to a game crash. See replay

[OpenRA-2016-02-21T122936Z.zip](https://github.com/OpenRA/OpenRA/files/139921/OpenRA-2016-02-21T122936Z.zip)

Red Alert Mod at Version release-20151224
on map 1b678380f5ff618e438f9ffd645bc4f367205933 (Suffrage by Nuke'm Bro.).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Attempted to finalize an undisposed DisposableAction. hind (39) reserved fix (33)
   bei OpenRA.Mods.Common.Traits.Reservable.<Reserve>c__AnonStorey0.<>m__2()
   bei OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime)
   bei OpenRA.Game.LogicTick()
   bei OpenRA.Game.Loop()
   bei OpenRA.Game.Run()
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)

**Comment by derestle** [comment] 2016-02-22 10:01
here is exactly what i did, maybe it helps:

I had a helicopter damaged and it lost some ammo. So i wanted it to get repaired and after that to start refulling its ammo.
So i selected the Helicopter and hold shift. Then i clicked to the repairbuilding and then to the Helipad. Immediatelly after that the Game crashed.
This Crash happens even without Cheats. I Enabled them to show this issue faster.

**Comment by RoosterDragon** [comment] 2016-02-23 19:35
Duplicate of #9783, fixed in #9786. The fix didn't make it into release-20151224, but it will be in for the next playtest/release.

**Closed by RoosterDragon** 2016-02-23 19:35 UTC
Labels: Crash
