### ISSUE TITLE
Game become slow playing against the IA

### ISSUE THREAD

**Issue by bioinfornatics** [OpenRA/OpenRA#18339] opened 2020-06-28 15:29 UTC
If all bridges are broken and IA sent units through those bridges the path up to the enemy base can not not be reached thus the search path take lot of CPU resources and the game become really slow until at least one bridge is repaired.

**Comment by abcdefg30** [comment] 2020-06-28 16:05
Thanks for the report. Duplicate of #12435 though. That is why we disabled the AI on maps like Poland Raid.

**Closed as completed by abcdefg30** 2020-06-28 16:05 UTC
Labels: Bug, Performance, AI
