### ISSUE TITLE
Fix building/training spam

### ISSUE THREAD

**Issue by ROCKNROLLKID** [OpenRA/OpenRA#11825] opened 2016-08-17 18:05 UTC
Hello OpenRA community.

One thing that is really kind of annoying in OpenRA, is that everything you click on a building to be built  or a vehicle/infantry to be made, it will spam building over and over again (or training for infantry). There is a similar pull request to mine for unit commands, but I also wish for this to be fixed, as well.

Here is the pull request: https://github.com/OpenRA/OpenRA/pull/11781

**Comment by ROCKNROLLKID** [comment] 2016-08-17 18:08
It would be kind of nice if you could get it more like how it was in the originals, where it would be like this:

Building - 3 second delay - Building - 3 second delay - etc.

**Comment by Mailaender** [comment] 2016-08-17 20:40
Duplicate of https://github.com/OpenRA/OpenRA/issues/4690.

**Closed by Mailaender** 2016-08-17 20:40 UTC
Labels: Audio, Polish
