### ISSUE TITLE
A crash when i was in modchooser

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#12500] opened 2016-12-23 21:20 UTC
i wanted to change from td to ra.

Mod Chooser Mod at Version release-20161019
Date: 2016-12-23 21:11:17Z
Operating System: Linux (Unix 4.4.0.21)
Runtime Version: Mono 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4) CLR 4.0.30319.17020
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.ThrowHelper.ThrowKeyNotFoundException () <0x7f4274cb6ea0 + 0x00015> in <filename unknown>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (System.Collections.Generic.TKey key) <0x7f4274b3d830 + 0x00042> in <filename unknown>:0 
  at OpenRA.Widgets.ChromeMetrics.Get[T] (System.String key) <0x41e20eb0 + 0x0002d> in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.GlobalChatLogic.MakeHistoryWidget (System.Object o) <0x41f35ba0 + 0x00107> in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.BindingAddImpl (System.Object item) <0x41f35ad0 + 0x00037> in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.ScrollPanelWidget+<BindingAdd>c__AnonStorey2.<>m__0 () <0x41f35aa0 + 0x00017> in <filename unknown>:0 
  at OpenRA.Primitives.ActionQueue.PerformActions (Int64 currentTime) <0x41eff4e0 + 0x001ba> in <filename unknown>:0 
  at OpenRA.Game.LogicTick () <0x41eff3c0 + 0x0002b> in <filename unknown>:0 
  at OpenRA.Game.Loop () <0x41eff160 + 0x0014f> in <filename unknown>:0 
  at OpenRA.Game.Run () <0x41eff000 + 0x00077> in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) <0x41ceca80 + 0x0005f> in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) <0x41cebd60 + 0x000f7> in <filename unknown>:0

**Comment by pchote** [comment] 2017-02-05 18:01
Duplicate of #12271, which was fixed by #12318.

**Closed by pchote** 2017-02-05 18:01 UTC
Labels: Crash
