### ISSUE TITLE
Force firing on a submerged unit plays an explosion animation instead of splash

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#11584] opened 2016-07-05 19:13 UTC
But does no damage. 

In RA mod, on bleed.

**Comment by pchote** [comment] 2017-02-05 20:26
Ping @reaperrr: any thoughts on this one?  The cleanups in #12633 don't change this.

**Comment by reaperrr** [comment] 2017-02-06 00:06
I think this would require fixing the `ImpactType`s to take target validity into consideration, but all attempts at this that I've made locally a few months ago caused regressions or would have made the yaml setup quite a bit more complicated, so I haven't looked into this for a while.

**Comment by Smittytron** [comment] 2017-11-09 00:19
Seems to be splashing now. Was this fixed by #14058?

**Comment by reaperrr** [comment] 2017-11-09 08:51
Earlier than that, but fixed in any case.

**Closed by reaperrr** 2017-11-09 08:51 UTC
Labels: Polish
