### ISSUE TITLE
Waypoint mode issue

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#18409] opened 2020-07-16 09:31 UTC
nr1995:
While holding [Shift] for waypoint mode,
your unit(s) should not move, even after clicking on open ground.
Currently, they begin moving as soon as you lay down the first position.

Also, it could use a different/clearer line, like vanilla does.

https://github.com/cookgreen/Yuris-Revenge/issues/152

**Comment by tovl** [comment] 2020-07-16 13:13
Duplicate of  #12408

**Closed as completed** 2020-07-16 13:15 UTC
Labels: UI
