### ISSUE TITLE
Win automatically when you are the last player in the game

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13725] opened 2017-07-25 16:16 UTC
It's an __option__ request.
I played a 5v5 game where all the players in my team left after "gging" because we were overnumbered.
I was the last of my team versus 5 players so these players "gged" too and left the game.
Finally I was alone versus nobody so I had to destroy every enemy asset to get the correct/normal ending and actually __win__ that game.
With this option enabled the game could automatically give you the victory if you are the last player on the server.

**Comment by pchote** [comment] 2017-07-25 16:22
#13284 would solve this.

**Comment by PunkPun** [comment] 2022-07-11 17:42
closing as a reverse duplicate of #13284 and #18643

**Closed by PunkPun** 2022-07-11 17:42 UTC
Labels: Idea/Wishlist
