### ISSUE TITLE
convert RA map to TD and vice versa

### ISSUE THREAD

**Issue by SevaJmurov** [OpenRA/OpenRA#14356] opened 2017-11-14 16:55 UTC
I thought that it's as easy as getting rid of mod specific actors, overlays etc. and copy paste map to another folder. But nope.
Is that possible at all?

**Comment by SevaJmurov** [comment] 2017-11-14 18:38
Well, I figured that it's as easy as all the above + changing RequiresMod to ra/cnc in map.yaml.

**Comment by SevaJmurov** [comment] 2017-11-14 18:41
Yes, but all the tiles are completely broken that way, so apparently there is no way other than redrawing map.

**Comment by Mailaender** [comment] 2017-11-19 20:50
Duplicate of https://github.com/OpenRA/OpenRA/issues/2963.

**Closed by Mailaender** 2017-11-19 20:50 UTC
Labels: Question / Support
