### ISSUE TITLE
Nuget-provided windows dependencies don't work for many players

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7363] opened 2015-01-20 03:24 UTC
playtest-20150118 would not run for many people, and we had to work around this by manually packaging a new installer with the dlls from release-20141029.  I expect this to be a regression from #7346, which I suspect will be caused by the nuget-provided dlls linking against one or more VC runtimes that some people don't have installed.

If this is indeed the problem, then it is a bit crap to expect players to install N different C runtimes before they can run OpenRA, so we should revert back to our previous working libraries.

**Comment by dan9550** [comment] 2015-01-20 03:41
Couldn't we have our installer download and silently run the installs for any of the C runtime libraries we need?

**Comment by pchote** [comment] 2015-01-20 03:56
The thing is that we only need one, which is the situation that we had previously.  There's no reason to require additional dependencies here.

**Comment by Mailaender** [comment] 2015-01-20 05:39
The bug description is very foggy. We need a list which DLL is causing whom trouble. For the moment I assume this is a duplicate of https://github.com/Robmaister/SharpFont/issues/48.

**Comment by LipkeGu** [comment] 2015-01-20 08:07
I noticed the installer chrashes, when it runs without elevated rights on my side it was when the installer is etracting the maps

**Comment by Mailaender** [comment] 2015-01-20 18:58
Sounds like that is another issue. Can you file a bug report for it including when this first started to be a problem?

**Comment by Mailaender** [comment] 2015-02-01 14:02
We resolved https://github.com/Robmaister/SharpFont/issues/48 by https://github.com/OpenRA/OpenRA/issues/7212, but it is possible that I had not updated DLL in my branch. Building the setup with AppVeyor will probably avoid trouble like that https://github.com/OpenRA/OpenRA/pull/7351.

**Comment by pchote** [comment] 2015-02-01 18:55
#7351 is unrelated, and I don't think that the sharp font change will be sufficient. Reopening until we have confirmation from one of the affected players that their game runs.

**Comment by Mailaender** [comment] 2015-02-01 19:05
Who is affected and what error message did they receive? Nothing about it on the social media comments so far.

**Comment by Mailaender** [comment] 2015-02-15 10:38
Closing as there is no evidence that "many" players are effected as not one can be named. No complains from my social media surveillance.

**Comment by penev92** [comment] 2015-03-03 15:06
Just got evidence on 3 different Windows 7 machines in the last 2 days. Will upload the exception.log when I get home. In all cases the problem was freetype6.dll

**Comment by pchote** [comment] 2015-03-03 20:30
This also affects at least the native lua dll:
```
[19:55:58]	<penev> http://pastebin.com/f0SA8srW 
[19:56:14]	<Phrohdoh> Unable to load DLL 'lua51.dll' 
[20:12:23]	<penev> ok so apparently freetype6.dll v2.5.3.0 + the Lua DLL from the playtest makes bleed actually work
[20:12:38]	<penev> at least in Mike_msk's case... 
```
(note: the "playtest" versions are actually the pre-nuget release-20141029 versions, as I explained above).

**Comment by Mailaender** [comment] 2015-03-03 20:34
I think you are mixing things up. We had to revert back to freetype 2.5.1.0 in https://github.com/OpenRA/OpenRA/pull/7212 so the playtest does not ship 2.5.3.0 at all.

**Comment by pchote** [comment] 2015-03-03 20:41
Actually, I think you are mixing things up.  The playtest-20150118.exe doesn't ship any nuget provided dlls.  As I explained above, I manually built that package with the versions that we previously included in our repository after people started complaining that they couldn't run the game.

**Comment by Mailaender** [comment] 2015-03-03 20:42
Tell people to install http://www.microsoft.com/en-us/download/details.aspx?id=30679 and see https://github.com/OpenRA/OpenRA/issues/7579 so we revert the dependency to avoid a too new VS runtime dependency in our native bundled packages.

**Comment by Mailaender** [comment] 2015-03-03 20:51
Your outside the repository hack fix only led to confusion. It did not really help track down and resolve the problem at the source. Next time I propose we collect more evidence and do a re-release after some thought went into the issue. These nebulous bug descriptions and unrevisioned uploads have only delayed things in the long term.

**Closed** 2015-03-08 00:27 UTC
Labels: Crash, Packaging, Regression
