### ISSUE TITLE
Minimap Preview Icons

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15590] opened 2018-09-06 16:52 UTC
Generals had icons on the lobby map previews to show locations of the tech structures and supply docks/piles. I have implemented something similar for my engine, but i'm not sure how good would it be for upstream. It is currently manually define everything in map.yaml (with format as below) and not realated to actors. Left is location, right is chrome.yaml reference under `map-preview-icons:`.

    Icons:
    	4,53: pile
    	4,55: pile
    	5,33: derrick
    	10,19: dock
    	23,56: pile
    	25,54: pile
    	27,53: pile
    	29,40: dock
    	37,7: pile
    	39,9: pile
    	57,36: derrick
    	60,20: derrick
    	65,5: dock
    	65,52: pad
    	65,69: hospital
    	69,20: derrick
    	72,36: derrick
    	90,9: pile
    	92,7: pile
    	99,40: dock
    	101,53: pile
    	103,54: pile
    	105,56: pile
    	119,19: dock
    	124,33: derrick
    	125,53: pile
    	125,55: pile
    	64,63: dock
    	64,33: soviet

![resim](https://user-images.githubusercontent.com/7933210/45172532-4a432200-b20e-11e8-9401-09a47ebb778d.png)

**Comment by pchote** [comment] 2018-09-06 17:00
Duplicate of #3359 - would you mind moving this over to a comment there and closing this?

**Closed** 2018-09-06 17:03 UTC
Labels: Feature
