### ISSUE TITLE
[TS] Red "unbuildable area" is not active on walls but for Gates it is

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#16454] opened 2019-04-28 01:26 UTC
When we place a buildung like a Powerplant, we get an red cell indicator that the building cant be placed on this type of terain, the same happens for Gates. and in orig TS also for Walls.

So when we choose a location for Walls, we always Get white indication "We can place the object here", but placing it like on tiberium results in not buildable "can not deploy here". we also get white indications in Buildings.

![Unbenannt](https://user-images.githubusercontent.com/2057932/56856922-e53b6880-6965-11e9-8865-7cf1dc4f2426.png)

![Unbenannt2](https://user-images.githubusercontent.com/2057932/56856931-17e56100-6966-11e9-8f3c-5efe60c18baa.png)

Expected behavier: Show Red indication on cells where it isnt able to place walls. as like for gates.

**Comment by MustaphaTR** [comment] 2019-04-28 08:16
Duplicate of https://github.com/OpenRA/OpenRA/issues/13632

**Closed by MustaphaTR** 2019-04-28 08:16 UTC
Labels: Bug
