### ISSUE TITLE
please make the map editor more user friendly

### ISSUE THREAD

**Issue by francisxxx0** [OpenRA/OpenRA#10262] opened 2015-12-22 11:39 UTC
Hey, it would be awsome if you could add some bigger brushes for water and terrain. Its so anoing to paint with 1x1

**Comment by x-a-n-a-x** [comment] 2015-12-22 14:29
Hi francisxxx0. See https://github.com/OpenRA/OpenRA/issues/5164

**Comment by pchote** [comment] 2015-12-22 15:05
Thanks for the report.  This is a duplicate of #9935, so i'll close this one.

**Closed by pchote** 2015-12-22 15:05 UTC
