### ISSUE TITLE
Spy gets shot

### ISSUE THREAD

**Issue by pas62** [OpenRA/OpenRA#10265] opened 2015-12-23 02:49 UTC
OpenRA.exe ver 12/13/2015. Mission 5a, Tanya's Tale: spy gets noticed and shot by soldiers.

**Comment by abcdefg30** [comment] 2015-12-23 11:22
I think this is a duplicate of #10226.
From that issue:
> Stupid question, but did you disguise the spy?

Anyway, you're somewhat correct though. The description of the mission is not fitting anymore.
I filed #10267 and hope it's clear then.

**Closed** 2015-12-24 14:08 UTC
