### ISSUE TITLE
minimap displayes ore disappearing even under fog of war

### ISSUE THREAD

**Issue by platinumICE** [OpenRA/OpenRA#11490] opened 2016-06-19 23:10 UTC
Tested with: version 2016-05-08 RA mod

Start skirmish map and reveal some terrain with ore on it. Build radar so that minimap appears. If the ore is being mined by another player (with the terrain is still covered under the fog of war) the ore symbols disappears on the minimap. The map itself correctly displayes the last known information (ore being present) but the minimap errorly shows the current state of ore (ore being absent). The minimap should display last known information about the ore.

**Comment by GraionDilach** [comment] 2016-06-20 00:21
Duplicate of #5908.

**Comment by abcdefg30** [comment] 2016-06-20 11:23
Indeed a duplicate.
Thanks for the report, though!

**Closed by abcdefg30** 2016-06-20 11:23 UTC
Labels: Bug
