### ISSUE TITLE
Performance on latest playtest seems significantly worse than release 20150614

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9839] opened 2015-10-31 22:32 UTC
I downloaded and installed the Windows packages of release 20150614 and playtest 20151031 and ran one instance each. On my system (Win7x64, i5-2500 @ 3.5 GHz, Turbo disabled), `Tick` on the RA shellmap on older release hovered in the 2.5-3.3 ms range, while the playtest varied from 3.2-5.2ms.

`Render` was ~1.7-2.2ms for both.

Their respective `perf.log` (I used local `support` dir) didn't turn up anything out of the ordinary, in fact going by `perf.log` alone, the playtest should have been a bit faster.

**Comment by JFreegman** [comment] 2015-11-01 04:24
I've experienced some severe performance regressions with both RA and TS (haven't tried the others). Compiled from source on Linux Mint 17 64-bit.

current playtest: http://i.imgur.com/syT7bAW.png
release-20150919: http://i.imgur.com/Vaoe2Y0.png
release-20150614: http://i.imgur.com/bs8PGbx.png

**Comment by pchote** [comment] 2015-11-01 10:39
@JFreegman: Please also post perf.log files associated with those screenshots.

**Comment by pchote** [comment] 2015-11-01 10:55
Actually, perf.log isn't going to help in that case.  All your perf is going into render flip.

**Comment by RoosterDragon** [comment] 2015-11-01 19:55
I wonder if these lame graphics driver stalls are due to https://github.com/OpenRA/OpenRA/pull/8387#issuecomment-119801214.

**Comment by pchote** [comment] 2015-11-14 14:31
Any progress with testing this @reaperrr or @RoosterDragon?

Bear in mind that you can't trust the results of locally compiled builds for this - we know that the performance profile is different for builds compiled on .NET vs mono.

**Comment by reaperrr** [comment] 2015-11-14 15:56
No progress on my end, precisely because my own .NET compiles don't show any striking enough differences to attribute this to one specific change.

**Comment by JFreegman** [comment] 2015-11-15 09:36
https://github.com/OpenRA/OpenRA/pull/9476

Everything commit before that was merged is smooth as butter.

**Comment by pchote** [comment] 2015-11-15 11:33
@JFreegman: That's indeed expected, but I suspect it will be caused by your GPU drivers.  Your render flip perf is significantly worse than i'd expect even before that change.

**Comment by GraionDilach** [comment] 2015-11-15 11:51
@JFreegman just taking a guess here but are you using a Radeon HD2000/3000/4000 series graphic card? In your case, it's indeed the GPU driver, Mesa sucks at blending, fglrx would work flawlessly but the latest fglrx which works with your card is too outdated for Xserver 1.12. (This is the same reason I am stuck on Kubuntu 12.04.1-.5 mixture.)

**Comment by RoosterDragon** [comment] 2015-11-15 14:13
Following on from reaperrr's comment. MS builds don't show any significant difference on the two versions for me. The current playtest has similar perf as the MS build. The weird one is release 20150614, which is oddly somehow faster.

Therefore I wonder if the mono build regressed in performance due to a compiler change, or if we passed it different flags or such.

At the moment, I am disinclined to think this was due to a new feature.

I'm not really sure what to make of it all, to be honest.

**Comment by JFreegman** [comment] 2015-11-15 21:24
@GraionDilach I'm actually on a Geforce 6150 SE, using proprietary nvidia nforce 430 driver version 304.128-0ubuntu0.0.1

I'll try to test some different drivers when I have the time

**Comment by reaperrr** [comment] 2015-12-06 03:06
@RoosterDragon:
I doubt it's a Mono/compiler issue, The relative regression between releases is consistent for me regardless of whether I test self-compiled builds or our shipped release/playtest compiles (playtest 1129 is at least 60% slower than release 0614, applies to both self-compiled and download packages).

Additionally, playtest 1129 further regressed by at least 20% or so compared to release 0919 for me (again, both self-compiled builds and release packages from site).

Might be a "death by thousand cuts" thing, i.e. the various new features and refactorings simply costing more total performance than we've gained through optimizations.

**Comment by RoosterDragon** [comment] 2015-12-07 01:32
For me, a self compiled release mode build of release-20150614 runs at 6-7ms / tick on the shellmap, and for playtest-20151129 runs at 5-6ms / tick.

The downloads page has playtest-20151129 running at 5-6 ms / tick and playtest-20151129 gives about 6ms / tick.

**Comment by reaperrr** [comment] 2015-12-07 13:00
Huh... that's really completely different from my numbers...
What CPU and OS do you have?

**Comment by RoosterDragon** [comment] 2015-12-07 18:09
Win10, i7, 2.30 GHz.

**Comment by RoosterDragon** [comment] 2015-12-10 21:18
One thing that often throws my tick numbers about is how fast the CPU is deciding to be running at any given time. If turbo was active (140%) or speed step had throttled the CPU for either power saving or to prevent overheating (34%) then my tick/render times go up and down in almost direct correlation. It can step to intermediate values too, depending on load and whatnot.

Might be worth double checking you're taking the measurements on the two builds when the CPU is running at similar speeds. Maybe there's a slim chance you took the playtest ones when the CPU had scaled down a bit? I'm not holding out much hope that is the case, but it's worth a shot I guess.

![Perf comparison as related to CPU frequency](http://imgur.com/rhNgxLW.png)

**Comment by reaperrr** [comment] 2015-12-10 23:48
I'm running an i5-2500 at fixed 3.5 GHz (all cores, turbo and power states completely disabled), so it shouldn't be turbo/throttle in my case.

**Comment by pchote** [comment] 2016-08-06 18:56
I dont think we can do much more here, so closing.

**Closed by pchote** 2016-08-06 18:56 UTC
Labels: Performance, Regression
