### ISSUE TITLE
Crash in the thumper code

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#9996] opened 2015-11-15 00:09 UTC
```
Dune 2000 Mod at Version playtest-20151114
on map 4da18863d6ae1bec117b6b4163e179a6f73e958a (Tuck's Sietch by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Object <OpenRA.Mods.Common.Traits.DeployToUpgrade> revoked more levels of upgrade deployed than it granted for thumper 324.
   at OpenRA.Mods.Common.Traits.UpgradeManager.RevokeUpgrade(Actor self, String upgrade, Object source)
   at OpenRA.Mods.Common.Traits.DeployToUpgrade.RevokeUpgrades()
   at OpenRA.Mods.Common.Traits.DeployToUpgrade.<ResolveOrder>c__AnonStorey1.<>m__0()
   at OpenRA.Activities.CallFunc.Tick(Actor self)
   at OpenRA.Traits.Util.RunActivity(Actor self, Activity act)
   at OpenRA.Actor.Tick()
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment] 2015-11-15 00:20
The curious thing with this crash is that it only crashed about half of the people on the MP game.  That suggests that something odd is going on.

**Comment by pchote** [comment] 2015-11-15 00:24
DeployToUpgrade mixes CallFuncs to apply/remove the upgrade with CancelActivies to clear the queues.  This is just asking for a CallFunc to be cancelled, which will cause a mismatch and this crash.

**Comment by pchote** [comment] 2015-11-15 00:26
I suspect that the repro case for this will be to mix queued move and deploy orders, like @obrakmann mentioned in #9987.

**Comment by penev92** [comment] 2015-11-15 02:41
Duplicate of #9242 btw.

**Comment by penev92** [comment] 2015-11-15 02:44
We should check if the tick tank PR does indeed fix this. Of course we first need to find a way to reliably reproduce the crash.

**Comment by pchote** [comment] 2015-11-15 10:15
That pr has been sitting with changes requested for almost a month now, FWIW.

**Comment by penev92** [comment] 2015-11-15 11:02
Yes, because it is a low-priority PR that nobody cares about anyway. And we've been pushing towards getting the playtests ready.

**Comment by pchote** [comment] 2015-11-15 11:44
I think we can now consider it to be a high priority PR :)

**Comment by pchote** [comment] 2015-11-15 14:11
If we want this to be completely robust I suggest making the `CallFunc`s toggle a flag on the trait, and then grant/revoke the upgrades from the trait's `Tick` method.  That ensures that it can only grant/revoke one upgrade, and so the worst that the broken activity logic can do is to forget an order.

**Comment by GraionDilach** [comment] 2015-11-15 14:28
I have to acknowledge that I seen similar crashes with UpgradeActorsNear with an around 5% chance of happening, so I guess the source is shared.

**Closed** 2015-11-21 23:59 UTC
Labels: Bug, Dune 2000
