### ISSUE TITLE
Feature to allow you to change game settings within a game

### ISSUE THREAD

**Issue by binyata** [OpenRA/OpenRA#13029] opened 2017-03-28 23:06 UTC
I have had this happened many times where I get together with my brothers to play some Command and Conquer Tiberium Dawn online then I forget to set the game speed to be fastest instead of normal, resulting in us needing to leave the game and change the settings all over again.

Would it be possible to add settings such as game speed within the in game menu?

**Comment by Smittytron** [comment] 2021-07-15 15:29
Closing as reverse duplicate of #16323

**Closed by Smittytron** 2021-07-15 15:29 UTC
Labels: Question / Support
