### ISSUE TITLE
Hijacking can be prevented by spam move orders on the vehicle

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#16045] opened 2019-01-08 21:18 UTC
At least this is what it felt like - FiveAces tried to move MCV away while it was being captured; it didn't move, but thief couldn't capture it either, just moving into MCV cell and out of it 5 times.

**Comment by abcdefg30** [comment] 2019-01-08 21:20
The same is true for spies and infiltrating buildings.

**Comment by matjaeck** [comment] 2019-03-17 19:44
Can somebody confirm this for / reproduce this in release-20190314? I fail to do so.

**Comment by Smittytron** [comment] 2021-04-11 21:21
Closing as reverse duplicate of #19339

**Closed by Smittytron** 2021-04-11 21:21 UTC
Labels: Bug

**Comment by abcdefg30** [comment] 2021-05-06 11:02
It's actually the other way around here most likely: A repeated order causes units to move in and out of the target as described in the OP:
![spamInfilitrate](https://user-images.githubusercontent.com/7704140/117287617-d4822f00-ae6a-11eb-8a4d-78f0cfc777cf.gif)
![spamInfiltrate2](https://user-images.githubusercontent.com/7704140/117287880-275be680-ae6b-11eb-8ad2-4b0a2fb3662c.gif)

But it appears like #16569 is already covering this, too.
