### ISSUE TITLE
Carryalls disappear under FoW in d2k

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#9166] opened 2015-08-25 20:54 UTC
This is on bleed. The only problem I have with this is that the carryall makes off with my harvester and unless I am constantly defending my spice patches, I can't see if someone set up a rocket tank to snipe the carryalls.
##

**Comment by pchote** [comment] 2015-08-25 22:53
This must be a recent regression, as I specifically fixed this for the first time only a few weeks(?) ago.

**Comment by penev92** [comment] 2015-08-25 23:47
Yes I also remember you changing that and them being visible after that.
Also currently missile tanks are unable to fire at air targets (nothing is).

**Comment by GraionDilach** [comment] 2015-08-26 11:35
I'm not even certain that stuff could fire at air targets in D2k, never seen losing a carryall in that game.

**Comment by penev92** [comment] 2015-08-26 14:01
I believe missile tanks were able to. Also missile turrets could fire on at least ornithopters, so it makes sense that they could also fire on carryalls.
[Some random image from the internet](http://media.moddb.com/images/games/1/14/13377/big-battle.jpg)

**Comment by Unit158** [comment] 2015-08-26 14:21
I'm certain they could, because I did it to destroy income lines in the original game vs the computer.

**Comment by pchote** [comment] 2015-08-28 15:07
It turns out that I did this intentionally (see #8477):
> The new-found configurability is used to hide your own 
                delivery aircraft under the fog in TD and D2K: these actors do 
                not reveal any shroud, and having them visible is inconsistent 
                with the idea that the fogged regions of the map are "blind" to 
                you -- you should not have any idea what is happening under it.

**Comment by Phrohdoh** [comment] 2016-03-15 16:25
Can this be closed?

**Comment by Unit158** [comment] 2016-03-17 16:19
I'll see when I get back home. AFAIK the real issue hasn't been resolved

On 2016-03-15, at 12:26, Taryn Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


Can this be closed?

**Comment by Phrohdoh** [comment] 2016-03-17 16:23
Is there an issue to solve?
Carryalls are not visible under fog (which I think is not a great choice) but this seems to be desired.

>This was an intentional change, see #8477.
> It turns out that I did this intentionally

This is unrelated (but should be investigated in its own ticket [does it already exist?]):
>Also currently missile tanks are unable to fire at air targets (nothing is).

The issue noted here is:
> The only problem I have with this is that the carryall makes off with my harvester and unless I am constantly defending my spice patches, I can't see if someone set up a rocket tank to snipe the carryalls.

Which, again, was an intentional decision.
That isn't to say we can't change it, but that discussion hasn't been had.

**Comment by Unit158** [comment] 2016-03-17 16:26
If you open a new ticket you can close this one I guess. This is probably a non-problem now anyway.

On 2016-03-17, at 12:23, Taryn Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there an issue to solve?
Carryalls are not visible under fog (which I think is not a great choice) but this seems to be desired.

This was an intentional change, see #8477<https://github.com/OpenRA/OpenRA/pull/8477>.
It turns out that I did this intentionally

This is unrelated (but should be investigated in its own ticket [does it already exist?]):

Also currently missile tanks are unable to fire at air targets (nothing is).

The issue noted here is:

The only problem I have with this is that the carryall makes off with my harvester and unless I am constantly defending my spice patches, I can't see if someone set up a rocket tank to snipe the carryalls.

Which, again, was an intentional decision.
That isn't to say we can't change it, but that discussion hasn't been had.

**Comment by pchote** [comment] 2018-11-27 23:49
Closing as outdated (i believe this predated the changes to bring D2K in line with original balance where its a significant effort to shoot down a carryall) / intentional behaviour.

**Closed by pchote** 2018-11-27 23:49 UTC
Labels: Balancing, Dune 2000
