### ISSUE TITLE
Making Fake Structures Truly Deceiving

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#15038] opened 2018-04-10 22:04 UTC
So, you know how when you attack a fake structure, you can clearly see it's health drastically going down? Yeah, shoot one once with a rifleman, and you know it's a fake right away.

In my CG420 maps for testing various balance tweaks, version 37, I have made fake structures appear real.

Instead of attacking a fake and going "oh, that's obviously fake" you will now go "kill that structure!" because when you attack the fakes, it appears to be taking damage as a real structure would. Because it is. However, once the health reaches, IIRC, 80-85% health, it explodes/dies. THEN you go "oh shit that was a fake."

If you want I can put in a PR for this.

As a bonus, fakes can now build off of each other. The dummy that I am sometimes, didn't think ahead and saw someone spam fake power plants like a mad man, which made base pushing overpowered. A simple tweak to make fakes take longer to build, and even possibly a limit on the number a player can build, should remedy this.

edit: actually, this could happen in the default game rules too. I think this is the first time I've seen someone abuse it. The only difference is they'd need one real structure to keep the fake spam base push going. So maybe this should be added.

You can forget the bonus if you want, but the first part......well, what's the point of having fakes if the enemy can obviously tell they're fake? :D

**Comment by abcdefg30** [comment] 2018-04-11 09:47
> edit: actually, this could happen in the default game rules too. I think this is the first time I've seen someone abuse it. The only difference is they'd need one real structure to keep the fake spam base push going. So maybe this should be added.

Sounds like this is a duplicate of #10969 then.

**Closed by abcdefg30** 2018-04-11 09:47 UTC
