### ISSUE TITLE
request for formation option

### ISSUE THREAD

**Issue by runeavalon** [OpenRA/OpenRA#12423] opened 2016-11-24 15:43 UTC
i remember from the oldschool red alert, that there was an update in which they implied an option to make the selected units move in the formation in which they stood when you implied the command. The command was "ctrl f".  it would be great if this was implemented in the openra version of the game to. It allows your selected units not only to stay in formation, but also to adjust the speed of the group to the slowest unit in the group. I think it was a great addition to the oldschool red alert which unlocked cool new strategies. I'm curious what you guys think of this request.

**Comment by runeavalon** [comment] 2016-11-24 15:47
cheers Ohmk torque

**Comment by abcdefg30** [comment] 2016-11-24 15:54
Duplicate of #3880.

**Closed by abcdefg30** 2016-11-24 15:54 UTC
