### ISSUE TITLE
Compress replay files. 

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21449] opened 2024-06-15 21:59 UTC
Use a zip/gzip/compress stream while writing and reading replay files.

Requested by a player who noticed he has 8GB of replay files. 

Perhaps support both. .orarepgz

**Comment by Mailaender** [comment] 2024-07-02 14:46
Duplicate of https://github.com/OpenRA/OpenRA/issues/8844

**Closed as not planned by Mailaender** 2024-07-02 14:46 UTC
Labels: Idea/Wishlist, Performance
