### ISSUE TITLE
Air AI units attacking Cruisers forget to reload

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#12365] opened 2016-11-08 04:06 UTC
I took a swarm of cruisers down the coast and a handful of AI air units came and attacked. When they ran out of ammo they continued to swarm rather than reloading.

**Comment by abcdefg30** [comment] 2016-11-08 10:50
This is the fault of our AI. Thus closing as duplicate of #6316. Thanks for the report though. :)

**Closed by abcdefg30** 2016-11-08 10:50 UTC
Labels: AI, Bug
