### ISSUE TITLE
"Server not responding" : Can't exit multiplayer game

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#13144] opened 2017-04-17 15:36 UTC
Cf title
Can't exit frozen game with Esc button.
Need to Alt-F4 the game.

**Comment by rob-v** [comment] 2017-04-17 16:04
It is known issue, fortunately you can at least click the Options button with mouse so you don't need to close the game.

**Comment by pchote** [comment] 2017-04-17 16:04
Closing as duplicate of #12314.

**Closed by pchote** 2017-04-17 16:04 UTC
