### ISSUE TITLE
Localization/Translation to Filipino 

### ISSUE THREAD

**Issue by Cyyy1998** [OpenRA/OpenRA#14812] opened 2018-02-11 15:18 UTC
Good day sir,

May I translate it to my native language which is Fililpino?

**Comment by MustaphaTR** [comment] 2018-02-11 15:32
Translations are not yet supported. There are plans for it, but no-one working on it currently.

Closing as a duplicate of #10475.

**Closed by MustaphaTR** 2018-02-11 15:32 UTC
