### ISSUE TITLE
Game freezes, probably pathfinder-related

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#7955] opened 2015-04-14 21:20 UTC
The game somtimes freezes at arbitrary times. It's therefore hard to track down, but our user Clemmy has managed to catch a replay of it ([download here](http://www.pipelinestall.org/stuff/OpenRA-2015-04-14T164638Z.rar), cnc@playtest-20150408).

Edit: The freeze happens at around 16:56 in the replay.

**Comment by RoosterDragon** [comment] 2015-04-14 22:31
It's looping endlessly inside [PathFinder.FindPath](https://github.com/OpenRA/OpenRA/blob/6a66cea01f8b309578aad132c74be6f9f8313708/OpenRA.Mods.Common/Traits/World/PathFinder.cs#L125-L133). The caller is [Harvester.ClosestProc](https://github.com/OpenRA/OpenRA/blob/6a66cea01f8b309578aad132c74be6f9f8313708/OpenRA.Mods.Common/Traits/Harvester.cs#L124-L137).

**Comment by penev92** [comment] 2015-04-14 22:38
Pinging @Rydra, as he is most likely to be able to help with this.

**Comment by Rydra** [comment] 2015-04-15 05:50
I will check it out, yet I would need if possible some information to help me reproduce the error, conditions, etc...

**Comment by Rydra** [comment] 2015-04-15 05:51
Ohhh it has a replay, then I'll reproduce and check as soon as I can.

**Comment by penev92** [comment] 2015-04-15 12:46
I added some logging to check for who does what.
I got the following using Clemmy's replay:
>--Tick: 27137 (local)
DeliverResources is ticking for harvester 266 (Watson (1)) and he doesn't have an OwnerLinkedProc.
Harvester 266 (Watson (1)) is looking for ClosestProc.
Started looking for path at 16.4.2015 г. 14:27:42 ч..
Finished looking for path at 16.4.2015 г. 14:28:13 ч..
Harvester 266 (Watson (1)) finished searching for ClosestProc.
--Tick: 27138 (local)

This is a half-minute path search, and all 31 seconds of it are in the `while` that @RoosterDragon pointed out - [PathFinder.FindPath](https://github.com/OpenRA/OpenRA/blob/6a66cea01f8b309578aad132c74be6f9f8313708/OpenRA.Mods.Common/Traits/World/PathFinder.cs#L125-L133)

Sadly I was unable to get such info from my replay :/

**Comment by RoosterDragon** [comment] 2015-04-15 17:58
Now I'm taking a wild stab in the dark here:

Is it possible [this line in Expand](https://github.com/OpenRA/OpenRA/blob/6a66cea01f8b309578aad132c74be6f9f8313708/OpenRA.Mods.Common/Pathfinder/PathSearch.cs#L119) is re-opening nodes that are closed, and thus allowing the search to keep reconsidering the same cells?

Maybe it shouldn't be updating closed cells at all? i.e:
```c#
// Closed nodes remain closed, unvisited or open nodes become open.
if(neighborCell.Status != CellStatus.Closed)
    Graph[neighborCPos] = new CellInfo(gCost, gCost + hCost, currentMinNode, newStatus);
```

Or maybe it should update the costs, but keep closed cells closed?
```c#
// Closed nodes remain closed, unvisited or open nodes become open.
var newStatus = neighborCell.Status == CellStatus.Closed ? CellStatus.Closed : CellStatus.Open;
Graph[neighborCPos] = new CellInfo(gCost, gCost + hCost, currentMinNode, newStatus);
```

Or maybe it is meant to reopen them, in which case I don't know what to do.

I could of course be talking utter nonsense because I don't understand the pathing, so that's also an option. :)

**Comment by Rydra** [comment] 2015-04-15 18:28
@RoosterDragon it reopens closed cells because there exists the possibility to find a better path to an already processed node. Not reopening closed nodes improves performance at the expense of providing possibly suboptimal paths.

This crash must be something deeper and must be dealt with. When I analyze the replay I hope I can come up with some conclusions.

Indeed not reopening closed nodes would be a fast way to deal with this bug issue, but imho I should get a grasp why it has failed in this very specific case.

**Comment by Rydra** [comment] 2015-04-15 20:23
Just a small question... How can I play (and therefore debug) this replay? Because in the DEV_VERSION I can't run it due to different version replay.

**Comment by penev92** [comment] 2015-04-15 20:26
Open OpenRA\mods\cnc\mod.yaml and set `Version:` to `playtest-20150408`. Basically lie to the game :D

**Comment by chrisforbes** [comment] 2015-04-15 20:40
> @RoosterDragon it reopens closed cells because there exists the possibility to find a better path to an already processed node

Nak! It's possible to find a better path to a cell in the open queue, but *not* once the node has been visited.

**Comment by Rydra** [comment] 2015-04-15 20:49
@chrisforbes It is possible, I could put a graphic example about it but I feel somewhat lazy now. Just put a conditional breakpoint in the line 115 of the file PathSearch.cs (from the bleed branch) where it only stops if CellStatus is closed. If it stops during a gameplay, it means that for an already visited node it has found a better way to reach it. Make the test.

A.I. books implementations take this scenario into account in the algorithms. (Although I have read some too that do not). Yet not doing so leads to suboptimal paths.

**Comment by Rydra** [comment] 2015-04-15 21:36
Ok I've finally found the real issue here. It's indeed one of those extreme rare cases and we should consider carefully the implications of this.

The issue is found in the line 114 from the file PathGraph.cs: var directions = DirectedNeighbors[index]. Just to sum up what this does, Regular A* implementations found in books and other resources consider all 8 neighbours when making the neighbour loop. Prior to the pathfinder refactor, the neighbour selection was made based so that it would consider only the neighbours that would bring your forward from your goal given the previous point.

For instance, if you are in 1, 2 because you came from 1, 1, there's on a 99% basis no need to consider the points that you "left behind". This was implemented that way before I laid my hands on the pathfinder, and I considered it a clever "heuristic" to cut down the amount of iterations you had to do. Yet this comes with the flaw that it could lead to suboptimal paths (sometimes that's ok).

Yet replay's case is one of those 1% cases where the pathing to perform is so complex that to perform a correct pathfinding conflicts with the optimality of a solution (made by reopening closed nodes as needed). You can try by replacing the line "var directions = DirectedNeighbors[index]" by "var directions = DirectedNeighbors[4]". Now the replay won't be stuck in that forever loop.

Quite curious.

To prevent this error to happen again, there exist 2 possible solutions:

1- Consider the 8 neighbours every time. This will solve this problem and return always the one and only shortest path from a source to destination. Performance will be hit "a bit".
2- Not reopening again closed nodes. This will solve this problem, improve a bit performance at the expense of not ensuring that a given path is the shortest.

Up to you and what you decide. Both solutions are extremely easy to implement.

**Comment by pchote** [comment] 2015-04-15 21:38
Do we really care if an actor doesn't pick the globally shortest path? Chances are that this path will be invalidated/recalculated at least once while the unit is following it.

**Comment by chrisforbes** [comment] 2015-04-15 21:44
This is actually just completely broken, and there are a bunch of things interacting.

- PathSearch.cs:119 allows state transitions from Closed to Open.
- PathSearch.cs:121 suppresses readding open nodes to the open set with a lower cost, which is *required* when the pq implementation lacks a reduceKey operation.

As for @pchote's question: no, this is a game -- we don't care about optimal paths in the slightest. We care about producing reasonable paths (or even reasonable path prefixes) as quickly as possible.

**Comment by Rydra** [comment] 2015-04-15 21:53
@chrisforbes I'm not fine with your first point.
And for your second point, the class RecordComparer takes the live value from the cellLayer, no need to update it in the openQueue. I implemented the Node array A* variant for the pathfinder when refactoring. My two cents.

**Comment by chrisforbes** [comment] 2015-04-15 22:09
s/RecordComparer/PositionComparer/ ?

Pulling the live values doesn't mitigate it (and really, makes things worse -- the pq never has a chance to shuffle things to maintain its invariants. You *will* pull items out in the wrong order.)

**Comment by Rydra** [comment] 2015-04-15 22:13
The class is PositionComparer. Can't remember the file where it is placed.

The implemented priorityqueue reorders it's elements when popping out of the queue afaik.

**Comment by chrisforbes** [comment] 2015-04-15 22:15
It only behaves correctly if the minheap was consistent before the pop.

**Comment by Rydra** [comment] 2015-04-16 05:25
'''It only behaves correctly if the minheap was consistent before the pop.'''

After making some research I trust this. For the time being it's ok in the pathfinder, no one noted this, but it would be cool if the priority queue implements some kind of "update" function or something to reorder in necessary.

I'll do some research when I have some time to spare.

**Comment by pi99y** [comment] 2015-04-16 15:22
One more replay file: http://s000.tinyupload.com/index.php?file_id=06337738901118615067
Fist time it froze around 22-23th minute, then around 29th

**Comment by Mailaender** [comment] 2015-04-16 18:47
A patch has been suggested at https://github.com/OpenRA/OpenRA/pull/7959.

**Closed** 2015-04-16 20:22 UTC
Labels: Bug, Pathfinding, Regression

**Comment by Beep6581** [comment] 2015-04-18 09:26
Hey!

I was plagued by freezing in offline skirmishes 7 bots vs 1 me in playtest-20150405, but they would not happen when I ran it through monodevelop, only when run normally. The freeze, a complete OpenRA lockup requiring killing OpenRA, would happen in about 80% of games. I'm happy to see you found this issue. I provide here a dump of my replays so you can check whether the cause is the same. I hexdumped the latest replay and indeed the last word in the replay is "harvester" so it could be the same thing.
http://filebin.net/1lfu4tsfjb
