### ISSUE TITLE
Set team chat availability dynamically

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#6064] opened 2014-07-25 22:10 UTC
While trying to make spectator team chat to fix #2062, I came across this limitation:

The variable disableTeamChat in IngameChatLogic.cs is set at the game start. But it needs to be adjustable according to the game state. For example, in an FFA game, a player that is dead should be able to team chat with other spectators or dead players. To do that, team chat has to be made available when player WinState changes. Or when other spectators disconnect and only one remains, team chat should be turned off. So team chat availability should be determined for every player at each tick. And the ingame chat window should also take this into account when team chat gets disabled while the chat window is open.

**Comment by pchote** [comment] 2015-11-22 12:53
Duplicate of the other team-chat related tickets.

**Closed by pchote** 2015-11-22 12:53 UTC
Labels: Feature, UI
