### ISSUE TITLE
E3 in a PBOX or HBOX is broken

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18088] opened 2020-05-12 12:54 UTC
In the RA mod:
Rocket Soldier when put into an Pillbox(hidden or regular indiffering)will have severe issues with firing its weapon properly.
The projectile might fire in a opposite direction, the missile might collide with the building, exploding and dealing damage to itself, the missile projectile might decide to make an curved arc instead of flying straight to the target, all for no apparent reason.
It needs some adjustments to be viable. I mean its also an balance issue so should probably fix it.

**Comment by netnazgul** [comment] 2020-05-13 15:12
CC @Punsho as this is related to recent balance works.

**Comment by PunkPun** [comment] 2020-05-13 19:38
> It needs some adjustments to be viable. I mean its also an balance issue so should probably fix it.

It's unlikely to become viable even if it stops being bugged. Rocket Soldiers gain little for entering a pillbox, but you do lose out on strong infantry killing capabilities

Incase it's a balance issue it would be best to fix it in the playtesting stage of release cycle

**Comment by abcdefg30** [comment] 2020-05-13 23:11
Agree that this has basically no impact. Regardless, we should still fix the bug(s). We can worry about making this viable later.

**Comment by MlemandPurrs** [comment] 2020-05-15 13:12
I have detected that an Bullet based weaponry doesnt suffer those misfiring problems.
So an possible bandaid might be to give E3 an new Garrisoned weapon that is an clone of Dragon except using an Bullet projectile. 
This will have drawbacks of becoming dumbfire as Bullets are not being able to lock on target, and it will not be able to get jammed. In return might increase the weapon range, so that it equals to Rocket Soldier gaining an range radius when in pillboxes yet losing homing capabilities.
In all ways it becomes an Gun Turret that performs worser, atleast no more projectile colliding with itself then.

**Comment by abcdefg30** [comment] 2020-09-12 16:01
I couldn't reproduce this on bleed, so maybe this was fixed in the meantime?

**Comment by reaperrr** [comment] 2020-10-10 23:54
Cannot reproduce it, either.
The only thing I noticed is that when firing straight west or east, it randomly alternates between the closest fire ports, but it doesn't have any trouble hitting the targeted position.

I'd say we consider this fixed until someone is able to reproduce it on bleed or one of the upcoming playtests.

**Closed as completed by reaperrr** 2020-10-10 23:54 UTC
Labels: Bug
