### ISSUE TITLE
Commit 25692 (2d4bad6) crashes mid game: Maximum range is less than the minimum range.

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#16185] opened 2019-02-09 17:42 UTC
### Issue Summary
Mid game on map (according to exception log): 9b65169023d890025df6e69052800d4bbdca8f51 (Pool Party by PizzaAtomica) Red Alert crashes. The exception log is:

```bash
on map 9b65169023d890025df6e69052800d4bbdca8f51 (Pool Party by PizzaAtomica).
Date: 2019-02-09 17:26:46Z
Operating System: Linux (Unix 4.19.16.0)
Runtime Version: Mono 5.16.0.220 (tarball Sun Jan  6 14:59:55 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.ArgumentOutOfRangeException`: Maximum range is less than the minimum range.
Parameter name: maxRange
  at OpenRA.Map+<FindTilesInAnnulus>c__Iterator0.MoveNext () [0x00032] in <c154a41179a048458af88a33df3403b3>:0 
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () [0x0004e] in <dbc731b3823b48689299547fb566d4a8>:0 
  at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget (OpenRA.Actor self) [0x00066] in <401b64c21fd447238064fd05f1452d0c>:0 
  at OpenRA.Mods.Common.Activities.MoveAdjacentTo+<Tick>c__AnonStorey0.<>m__0 () [0x00000] in <401b64c21fd447238064fd05f1452d0c>:0 
  at OpenRA.Mods.Common.Activities.Move.EvalPath () [0x00000] in <401b64c21fd447238064fd05f1452d0c>:0 
  at OpenRA.Mods.Common.Activities.Move.Tick (OpenRA.Actor self) [0x000a6] in <401b64c21fd447238064fd05f1452d0c>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005c] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x0001b] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick (OpenRA.Actor self) [0x00201] in <401b64c21fd447238064fd05f1452d0c>:0 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x0005c] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x0001b] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Actor.Tick () [0x0000f] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.World.Tick () [0x00043] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00231] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.LogicTick () [0x0004d] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.Loop () [0x000d2] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.Run () [0x0003e] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00048] in <c154a41179a048458af88a33df3403b3>:0 
```

#### System Information
- **Operating System:** NixOS 19.03pre166987.bc41317e243.
- **Mono Version:** 5.16.0.220.
- **OpenRA Version:** commit 25692 (2d4bad66aeea97ef9a59f70ac87da98c83daee55). 
- **Mod:** Red Alert.

#### Additional Information:
- Steps to reproduce
1. Build the above commit
2. Run Red Alert
3. Load the replay
and hopefully you'll find this error occurs for you too. It's a shame too, I was winning that game and it was not an easy game either.

- Logs & Replay
[openra-ra-25692-commit-2d4bad66aeea97ef9a59f70ac87da98c83daee55-max-range-less-than-min.zip](https://github.com/OpenRA/OpenRA/files/2848075/openra-ra-25692-commit-2d4bad66aeea97ef9a59f70ac87da98c83daee55-max-range-less-than-min.zip)

I tried using this replay to determine what I was doing and sadly it crashed before it got to the error I'm reporting, if relevant the error I got was:

```bash
OpenRA engine version bleed-25692
Red Alert mod version bleed-25692
on map 9b65169023d890025df6e69052800d4bbdca8f51 (Pool Party by PizzaAtomica).
Date: 2019-02-09 17:40:15Z
Operating System: Linux (Unix 4.19.16.0)
Runtime Version: Mono 5.16.0.220 (tarball Sun Jan  6 14:59:55 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Out of sync in frame 9288.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (System.Int32 frame) [0x00037] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00044] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Network.OrderManager+<TickImmediate>c__AnonStorey0.<>m__0 (System.Int32 clientId, System.Byte[] packet) [0x00048] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Network.ReplayConnection.Receive (System.Action`2[T1,T2] packetFn) [0x00063] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x000b3] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Sync+<RunUnsynced>c__AnonStorey0.<>m__0 () [0x00000] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Sync.RunUnsynced[T] (System.Boolean checkSyncHash, OpenRA.World world, System.Func`1[TResult] fn) [0x0002c] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Sync.RunUnsynced (System.Boolean checkSyncHash, OpenRA.World world, System.Action fn) [0x0000d] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00114] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.LogicTick () [0x0004d] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.Loop () [0x000d2] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.Run () [0x0003e] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <c154a41179a048458af88a33df3403b3>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00048] in <c154a41179a048458af88a33df3403b3>:0 
```

syncreport.log is:

```bash
No sync report available!
```

**Comment by fusion809** [comment] 2019-02-09 17:51
(Beware I messed up the version string (it used bleed-25690, when it was meant to be bleed-25692, I've checked the commit it was built from and it is the one mentioned in this issue) in my Nix package of OpenRA).

**Comment by obrakmann** [comment] 2019-02-09 17:54
Duplicate of #16172

**Comment by fusion809** [comment] 2019-02-09 17:55
Oops sorry, I just saw that.

**Closed by obrakmann** 2019-02-09 17:54 UTC
