### ISSUE TITLE
"Red Alert has encountered a fatal error and must close. Refer to the crash logs and FAQ for more information."

### ISSUE THREAD

**Issue by hallodome** [OpenRA/OpenRA#15812] opened 2018-11-11 22:56 UTC
I have downloaded and uninstalled numerous times, but I still get the error message when trying to load any of the Open RA games.  The error is below:
"Red Alert has encountered a fatal error and must close. Refer to the crash logs and FAQ for more information."

I go to view logs, it is empty.

**Comment by pchote** [comment] 2018-11-11 23:00
This is nearly always caused by a virus scanner blocking OpenRA from running.

I am using #15580 to track adding a specific check and error message for this case, but can't proceed as I am not able to reproduce this locally.

**Comment by hallodome** [comment] 2018-11-13 21:14
Thank you! I will try to disable the virus scanner.


Peace,
-Jonathan

"Art enables us to find ourselves and lose ourselves at the same time." -
Thomas Merton

**Comment by braefpapa** [comment] 2018-11-29 15:45
Unsupported OpenGL version: 1.1.0

OpenGL Information:
Vendor: Microsoft Corporation
Note:  The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.

Renderer: GDI Generic
GL Version: 1.1.0
Shader Version: 
Available extensions:
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   em OpenRA.Platforms.Default.OpenGL.Initialize()
   em OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   em OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestWindowSize, WindowMode windowMode, Int32 batchSize)
   em OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Int32 batchSize)
   em OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   em OpenRA.Game.Initialize(Arguments args)
Unsupported OpenGL version: 1.1.0

OpenGL Information:
Vendor: Microsoft Corporation
Note:  The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.

Renderer: GDI Generic
GL Version: 1.1.0
Shader Version: 
Available extensions:
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   em OpenRA.Platforms.Default.OpenGL.Initialize()
   em OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   em OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestWindowSize, WindowMode windowMode, Int32 batchSize)
   em OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Int32 batchSize)
   em OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   em OpenRA.Game.Initialize(Arguments args)

**Comment by reaperrr** [comment] 2018-11-29 18:01
@braefpapa OpenRA requires a GPU (and driver) with at least OpenGL 2.0 support. The error report suggests that you only have the default Windows graphics driver installed, which doesn't support anything newer than OGL 1.1.

Try to find out what graphics card (or integrated graphics) your system has and then try to find the newest possible driver supported by your Windows version.

**Comment by hallodome** [comment] 2018-11-29 19:52
If I disable my antivirus, it works.

**Comment by matjaeck** [comment] 2018-11-29 20:40
What anti virus have you been using? (#15580)

**Comment by hallodome** [comment] 2018-11-29 21:32
Bitdefender.
I just pause it for 5 minutes. Once I get the game going, it is fine.


Peace,
-Jonathan

"Art enables us to find ourselves and lose ourselves at the same time." -
Thomas Merton

**Comment by abcdefg30** [comment] 2020-01-28 09:42
Closing as resolved.

**Closed by abcdefg30** 2020-01-28 09:42 UTC
Labels: Crash

**Comment by AleBHZ** [comment] 2024-03-19 21:56
I've done everything and nothing still won't open

**Comment by ThomasChr** [comment] 2024-03-20 05:33
@AleBHZ
This is an issue from 2020.
If you have a similar problem please open a new issue so that we can investigate.
