### ISSUE TITLE
OpenRA lagging, very slow in Skirmish/Singleplayer

### ISSUE THREAD

**Issue by CARST84** [OpenRA/OpenRA#10296] opened 2015-12-27 13:50 UTC
Hello everyone,

I am playing OpenRA, mostly in Skirmish mode on my own maps, normal size 128x128 or 256x256. The game is lagging massively.

Here is a screenshot showing the performance graphs and a copy of the perf.log of the currently running game:

![screenshotopenrawithlags](https://cloud.githubusercontent.com/assets/16452503/12010459/31f44a76-aca8-11e5-9152-b77b9df21064.png)

[perf - Kopie.zip](https://github.com/OpenRA/OpenRA/files/72690/perf.-.Kopie.zip)

Kind regards,
Carst

Sorry, edit, I forgot my PC details:
i7-2700K @ 3.5Ghz
16GB of RAM
64-bit Win10
GeForce GTX580
Computer is running well in all other games and programs. I can play games like GTA5 at near max settings, just for reference.

**Comment by obrakmann** [comment] 2015-12-27 14:41
Can you show the map, please? From the screenshot, it looks like there isn't any ore near the refinery, which is a situation known for creating huge latency issues in the harvesting code. If that's true for all of the map, it might well pose a problem.

Your perf.log, however, shows that the Move activity causes most of the latency. Do your maps have separate islands, or land masses which are only connected by destroyed bridges, by any chance? The pathfinder doesn't really like that situation and the AI doesn't handle it properly either.

**Comment by MicroJOo** [comment] 2015-12-27 14:41
@CARST84 the map itself is probably more interesting ... would be nice if you could upload it , so we can take a look at it ?

this here is the common website to upload maps ... -> http://resource.openra.net/ 
and then link it here

**Comment by pchote** [comment] 2015-12-27 14:46
I agree that this looks like it could be the disconnected islands issue.  @CARST84 can you reproduce similar performance problems on our default maps?

**Comment by CARST84** [comment] 2015-12-27 14:46
Hello guys, thanks for the quick answers. I think @obrakmann  might be on track here for the right answer. The map has seprate land masses connected by bridges. But they are not destroyed. Also I had no ore in that map, I was just quickly testing the layout with a lot of startmoney. I will add ore and gems to the map and then report back if it is still lagging.

@pchote can there be seperate landmasses when the bridges are not destroyed?

**Comment by Mailaender** [comment] 2015-12-27 15:17
Which version are you using. This should be already fixed in https://github.com/OpenRA/OpenRA/pull/9144.

**Comment by CARST84** [comment] 2015-12-27 15:25
@Mailaender I am using version 20150919 ... should I update to the newest version?

I now replaced all destroyable bridges with static ones and also added ore. The map started out very good, but after a few minutes it all started lagging again. I add a screenshot which shows the full map and also the island in the middle connecting the four main islands with player spawns.
![screenshotopenrawithlags2](https://cloud.githubusercontent.com/assets/16452503/12010832/79857032-acb6-11e5-9bcf-c16c2560987b.png)

**Comment by Mailaender** [comment] 2015-12-27 15:28
> @Mailaender I am using version 20150919 ... should I update to the newest version?

Yes!

**Comment by pchote** [comment] 2015-12-27 15:28
The AI performance goes through the floor as soon as you segment the map in any way: this includes separated islands, bridges, or walls.  If you open out the map the problem should fix itself.

**Closed by Mailaender** 2015-12-27 15:28 UTC
Labels: Performance, Question

**Comment by CARST84** [comment] 2015-12-27 15:34
Thanks guys, well noted. I installed version 20151224 now and will try to "fix" the map to be more AI friendly. Will report back in the next days, when I have time to create the map again. The update to the new version kind of deleted my maps...

**Comment by Mailaender** [comment] 2015-12-27 15:37
That shouldn't happen if you store them at the correct https://github.com/OpenRA/OpenRA/wiki/Mapping#location
