### ISSUE TITLE
Minelayer sound-issues

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11230] opened 2016-05-06 11:47 UTC
release-20151224 - RedAlert

- you can hear "every" minelayer" including your enemys minelayer , when they stand on a repair-pad and reload 

- once the minelayer has finished "reloading" , a voice-message saying "Unit Repaired" pops up which isnt appropriate for having finished "reloading" ...

**Comment by reaperrr** [comment] 2016-05-06 11:51
The first issue might have been adressed in the playtest already.

Fixing the "unit repaired" voice will be hard until we've separated the rearm logic from the repair logic, though.

**Comment by Micr0Bit** [comment] 2016-05-06 12:01
from what i have seen ... https://github.com/OpenRA/OpenRA/pull/10412 - has been adressed in the playtest

**Comment by Mailaender** [comment] 2016-05-06 13:33
> The first issue might have been adressed in the playtest already.

The second one is a duplicate of https://github.com/OpenRA/OpenRA/issues/10195.

**Closed by Mailaender** 2016-05-06 13:33 UTC
Labels: Balancing, Red Alert
