### ISSUE TITLE
Attack command done with LMB doesn't work, if engineer is in the selected group

### ISSUE THREAD

**Issue by Pawonashi** [OpenRA/OpenRA#13723] opened 2017-07-25 14:44 UTC
I've immidiatelly launched Dune 2000 mod after installing latest playtest and picked Atreides Mission 5. Few seconds later I was attacked, so I've selected some units (soldier, trike and an engineer) and pressed left mouse button on the enemy (I've checked left mouse button commands) and instead of attacking this unit, I've selected it. I've changed to right mouse button, selected the same units and pressed right mouse button on the enemy, and my units started attacking it and they were still selected.

**Comment by pchote** [comment] 2017-07-25 16:24
I can't reproduce this.  Are you sure you move the cursor while you had the button pressed? If you drag too much with the button pressed the left-click orders scheme will switch from action to select mode.

**Comment by abcdefg30** [comment] 2017-07-26 21:18
I could reproduce this on the playtest. I selected the units and ordered them to move so that I hear the voice. Once the voice was the engineer's voice I couldn't attack anymore.

**Comment by abcdefg30** [comment] 2017-07-26 21:23
Just to clarify: This is also present in the last release.

**Comment by CH4Code** [comment] 2017-08-22 15:22
I mean, this is a known and accepted flaw, isn't it? 
Thats why in the RA mod you can't box-select engies, MCV and harvesters so they don't mess up your targeting, right? Same thing with dogs targeting structures/tanks (dogs though still can be box selected, which is good). 
Most annoying when trying to target an air unit with a group that has units with no air attack.

**Comment by GraionDilach** [comment] 2017-08-22 21:14
>target an air unit with a group that has units with no air attack.

Wait, what? Right-click controls doesn't have this one?! this is really annoying btw. Pretty sure it's an old bug though.

**Comment by GraionDilach** [comment] 2017-08-28 13:52
Confirmed: the bug @CH4Code mentions indeed only seem to apply to left-click orders.

**Comment by CH4Code** [comment] 2017-08-28 14:27
kind of off-topic, but this #12922 is problematic as well with left klick orders (&select), since the "selection lost" usualy happens in precarious situations.

**Comment by CH4Code** [comment] 2018-01-09 13:21
Have been playing around this bug so much that I didn't notice that medics, mcv, harvester and probably other units without any attack convert an attack command to a move order if they can't attack the target.

I would like this behaviour for rocket+rifle blobs as well (rifles moving/attack moving towards heli) and for the dog which can't target structures and tanks (and hence any blob which includes a single dog can't target fire structures and tanks).

**Comment by matjaeck** [comment] 2019-02-03 16:16
I think, but am not sure, the cause of this is that https://github.com/OpenRA/OpenRA/blob/2194f17dc2e098e65024c3d5547dc6a5bddb4a60/OpenRA.Game/Orders/UnitOrderGenerator.cs#L88-L120

returns `false` for medics because their `UnitOrderResult` is (I think) `null`.

This (I think) does not happen when the soldier (see gif above) is closer to the target because the result of `WithHighestSelectionPriority` is based on the `pixelDistance` in `CalculateActorSelectionPriority` https://github.com/OpenRA/OpenRA/blob/1830b3ee805d3c7bb43d2b54ddef34ead6d2a15b/OpenRA.Game/SelectableExts.cs#L61-L72.

It does not happen for right-click orders (I think) because in this case there is no conflict between move order and select.

**Comment by matjaeck** [comment] 2019-02-04 02:16
This (see gif above) is caused by the way how `InputOverridesSelection` in the UnitOrderGenerator works in conjunction with `WithHighestSelectionPriority`. WHSP is here, if I understand it correctly, the sum of the pixel distance (between the target and the selected unit) and the unit's selection priority (I don't really understand how this makes sense). 

Only the pixel distance for units like medics matters, as they share the same selection priority with E1 etc. so that you can select them together. 

So `underCursor`, which is the unit WHSP gives you, in `var o = OrderForUnit(underCursor, target, actorsAt, cell, mi)` will be the medic if it is closer to the target, than the E1 is.

Then, despite having an attack cursor, the checks after `if (o != null)` will not return true (unless you use force move, then the modifier will cause `InputOverridesSelection` to return true - ForceAttack does not work because medics can't ForceAttack) so that `InputOverridesSelection` returns false, and causing selecting the actor you clicked on with the attack cursor.

A workaround that I think confirms that this is the causes is to add 
```c#
if (GetCursor(world, cell, worldPixel, mi) != null)
	return true;
```
after the modifier checks to look for a `cursorOrder`. This of course changes the behavior fundamentally because you can not select anything, when something is already selected. This workaround requires to add another argument to all the references of `InputOverridesSelection`: `InputOverridesSelection(WorldRenderer wr, World world, int2 xy, MouseInput mi, int2 worldPixel)` and `uog.InputOverridesSelection(worldRenderer, World, mousePos, mi, mousePos))` in the WorldInteractionControllerWidget.

I willl check how exactly the original RA handled it when you hovered over or clicked on something while having a unit selected that can not target it. Showing the move cursor is flawed (also for right click controls) and it should either show the select cursor or the blocked cursor but move does not really make sense in my eyes if the location is impassable. Maybe this helps to find a proper fix for this.

**Comment by matjaeck** [comment] 2019-10-20 22:17
> I willl check how exactly the original RA handled it when you hovered over or clicked on something while having a unit selected that can not target it.

When you select a medic in the original and point at an enemy structure or unit, the "blocked" cursor is shown. When there are other units in the selection that can attack, the attack cursor is shown. The medic will in both cases move to the location on click.

When you have a unit selected and point at your own structures/units, the move cursor is replaced with the selection cursor (OpenRA: move cursor). The move cursor will in the original only appear when holding down ALT for force move.

Another difference to OpenRA is that when you have a tank selected and point at another own tank/structure or tree, the blocked cursor is shown (OpenRA: move cursor).

**Closed** 2019-10-30 13:53 UTC
Labels: Bug
