### ISSUE TITLE
AI detecting/attacking disguised spies without apparent reason

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9431] opened 2015-09-25 09:44 UTC
(Release 20150919)
In the attached replay you can see the AI attack disguised spies although there are no "detectors" present. It happens after the same spies have been around for a while, so it seems a bit random. (Maybe it has something to do with spies avoidning getting accidently run over?)
 
It happens 2 times in the replay: 
at ~12 minutes in the blue AI's base in the northern ore field 
and at ~22 minutes in the same base at the northern ore factory. 
 
It also seems that revealing one spy reveals all others in the vicinity as well.
http://www.megafileupload.com/5cbi/AIdetectingSpies.orarep

**Comment by abcdefg30** [comment] 2015-09-25 12:13
Duplicate of #2959.

**Closed by abcdefg30** 2015-09-25 12:13 UTC
Labels: AI, Bug
