### ISSUE TITLE
APM seem under-reported in playtest-20180102

### ISSUE THREAD

**Issue by gdavegdave** [OpenRA/OpenRA#14707] opened 2018-01-10 18:08 UTC
The actions per minute (APM) seem to be under-counted/under-reported in playtest-20180102. I attach a replay in which the supposed APM were 1.7 to 2.8, but they would've been reported considerably higher in previous versions (double figures for sure, and a few tens are reasonable if someone is controlling air units a lot). 
[OpenRA-2018-01-10T173703Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1619916/OpenRA-2018-01-10T173703Z.orarep.zip)

I simply renamed the file to .zip so github would accept it. I checked: the APM numbers were low during the game too, not just at the end.

**Comment by abcdefg30** [comment] 2018-01-10 19:07
Duplicate of #14671.

**Closed by abcdefg30** 2018-01-10 19:07 UTC
Labels: Bug
