### ISSUE TITLE
TS laser turret preview shows random voxel instead of turret

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12109] opened 2016-09-25 23:24 UTC
Before placing them down, the preview often shows some other randomly chosen voxel. Once placed down, everything is fine.

I assume this affects voxel turrets in general.

**Comment by pchote** [comment] 2016-09-25 23:26
Something seems to have regressed our texture bindings.  See also http://logs.openra.net/#21:33:03

**Comment by abcdefg30** [comment] 2016-09-26 10:19
Could #11341 be related as well?

**Comment by pchote** [comment] 2016-09-26 10:49
It very likely is.

**Comment by pchote** [comment] 2017-01-18 23:16
Closing as duplicate of #11341.

**Closed by pchote** 2017-01-18 23:16 UTC
Labels: Bug, Tiberian Sun

**Comment by reaperrr** [comment] 2017-06-14 16:55
This is actually still a problem on bleed, but it *is* fixed by #13485 so I won't bother reopening this.
