### ISSUE TITLE
Red Alert: Attack move shows mine location

### ISSUE THREAD

**Issue by megavirus11** [OpenRA/OpenRA#7994] opened 2015-04-20 12:12 UTC
When a player builds a minelayer and lays mines for the enemy, the enemy will be able to see the location of the mines when Attack moving.
- Build minelayer
- Lay mines
- Enemy player will Attack Move to the enemy base
- Enemy units will target mine locations when refreshing Attack Move Command if a mine is close
##

**Comment by pchote** [comment] 2015-04-20 13:37
It seems to be a bit more subtle than this.  I was able to reproduce this (and also discovered #7995) the first time I tried, but not a second time.

**Comment by FrameLimiter** [comment] 2018-07-26 15:11
This was fixed by #12171

**Closed** 2018-07-26 15:12 UTC
Labels: Bug, Red Alert
