### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Janevski** [OpenRA/OpenRA#17251] opened 2019-10-19 02:55 UTC
### Issue Summary
The performance using the latest appimages (playtest-20190825), is far worse than the last deb archive build (Release 20180307).
I get 10-20 fps at best during a skirmish game on the latest playtest appimage and the ingame clock lags, while on the last stable deb release there is no fps counter, but the pefromance is through the roof - very smooth and nice.
<s>If i enable graphing, i see that a lot of time is lost during rendering - the red graph line.
The rest is low.</s>

On a more powerful pc, such as something with an Intel i5 the issue is not noticeable.

Disclaimer: The only occasion when a (Release 20180307) might start to chop is from empty ore mines via bot ore truck pathfinders, or a bot trying to find you and you are on an island.
But that's a completely different topic.

#### System Information
- **Operating System:**  Ubuntu 16.04.2
- **.NET / Mono Version:**  4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
- **OpenRA Version:** playtest-20190825 (appimage) bad vs Release 20180307 (.deb archive) good
- **Mod:** Red Alert
- **CPU:** AMD Athlon(tm) II X4 620 Processor 4x2600MHz 2MB L2 cache
- **RAM:** 6GB DDR2
- **GPU:** Palit GF8400GS 512M DDR2 64B CRT DVI HDMI

#### Additional Information:
- Steps to reproduce
	1. install the game
	2. play skirmish vs a bot
	3. check the fps, or check the system ingame clock vs real time stopwatch

- Logs

- OpenRA Replays

- Screenshots & Videos

**Comment by reaperrr** [comment] 2019-10-19 09:22
I suspect the 8400GS might not like some of the changes we made to our renderer, I doubt that the issue is CPU-side.

**Comment by GraionDilach** [comment] 2019-10-19 10:19
Bleed already got the OpenGL2 to OpenGL3 bump - that might have fixed this already.

**Comment by Janevski** [comment] 2020-01-05 19:10
**Comment:**
No, beyond Release 20180307 (.deb archive) OpenRA is still very bat performace-wise.
This is not noticed by users, since many gamers have high end PCs.

**Scenario:**
Huawei Y5II stock Android 5.1 stopwatch

I played Fort Lonestar skirmish with three Fort Lonestar AI bots.
At the 5:00 phone stopwatch realtime mark,
release-20191117 (appimage) - bad - showed 4:08 ingame clock (**lagged 52 seconds**)
Release 20180307 (.deb archive) - good - showed 5:00 ingame clock
To the experienced eye it is quite noticeable during play that the game runs slower on release-20191117 (appimage).

**Info:**
CPU: AMD Athlon(tm) II X4 620 Processor
RAM: 6GB DDR2
GPU: GT218 [GeForce 210] 1GB vRAM
MB:   ASUS M4N78 PRO
HDD: no
OS: Ubuntu 16.04.2 LTS (custom live boot image)
**Good OpenRA: Release 20180307 (.deb archive)**
**Bad OpenRA: release-20191117 (appimage)**

**Comment by Janevski** [comment] 2020-01-07 18:36
Post scriptum.
mod: Red Alert
mono:
```
$ mono -V
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by reaperrr** [comment] 2020-01-07 23:35
@pchote: Could it be that #15179 or one of the "performance improvements" we made for 20180923 is causing this performance regression?

**Comment by pchote** [comment] 2020-01-07 23:46
Previous reports have suggested that it is probably #15194 that the old GeForces don't like. That PR brought significant improvements for everything else, so this may just be an unfortunate case that this hardware generation falls below our effective minimum spec.

Wikipedia suggests that it will still be compatible with the new GL renderer (after #17566 and any other lingering issues are fixed), so it will be interesting to see if that changes anything.

**Comment by abmyii** [comment] 2020-03-24 11:47
@Janevski Try running the game with `vglrun` (requires the `virtualgl` package).

**Comment by abcdefg30** [comment] 2021-08-20 06:14
@Janevski does the current release work for you? (Did you try running it in the legacy GL mode?)

**Comment by Janevski** [comment] 2021-08-30 22:39
> @Janevski does the current release work for you? (Did you try running it in the legacy GL mode?)

Shall test and update the issue.

**Comment by abcdefg30** [comment] 2022-06-26 08:54
Any news?

**Comment by Mailaender** [comment] 2022-11-07 11:12
Closing due to inactivity.

**Closed by Mailaender** 2022-11-07 11:12 UTC
Labels: Performance
