### ISSUE TITLE
[D2K] Concrete Wall build hash does not go red over unbuildable spots.

### ISSUE THREAD

**Issue by alercah** [OpenRA/OpenRA#14785] opened 2018-02-04 17:03 UTC
Found in bleed, just now.

To reproduce, attempt to build a concrete wall. When you try to place the wall, hover over a building; the build hash mark is still white, even though you can't build there. If you try to build, you are told you can't.

The hash mark should go red over an un-buildable tile.

**Comment by MustaphaTR** [comment] 2018-02-04 17:10
Duplicate of #13632

**Closed** 2018-02-04 18:29 UTC
