### ISSUE TITLE
[CI] Suggestion Disable or remove AppVeyor entirely for bleed :(

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8172] opened 2015-05-15 01:07 UTC
Its nice to have Appveyor for Windows builds but the last time it makes more problems than helping us X.x

- Nearly every third Build (PR) fails becaus of something what isnt supported on this named CI doesnt do its job right

- What about Jenkins X.x ?! 
- Or we disable Appveyor for bleed (what sense has Appveyor on Bleed?) When we package some things for Windows at release time it would be nice but doesnt help us all the time =(

Ideas how to fix that CI problems?

**Comment by pchote** [comment] 2015-05-15 08:49
Duplicate of #8069.

**Closed by pchote** 2015-05-15 08:49 UTC
