### ISSUE TITLE
AI will try hunt down cloaked units it can't attack

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3763] opened 2013-08-29 20:40 UTC
decreasing the performance dramatically, introduced/revealed by #3726.

**Comment by obrakmann** [comment] 2015-01-12 17:32
This has been fixed as part of #7097

**Comment by Mailaender** [comment] 2016-02-29 20:51
Are you sure. it still seems to happen https://www.youtube.com/watch?v=SqzODnoPjos

**Comment by SoScared** [comment] 2018-09-30 22:36
This seem to still be an issue. I've run a big batch of AI games lately, Aircraft will hover over cloaked units until it uncloaks. It probably had the unit targeted while visible but still sticks to the actor when cloaking.

**Comment by PunkPun** [comment] 2023-09-08 08:25
Fixed by #20227

**Comment by RoosterDragon** [comment] 2023-09-08 14:58
This wasn't addressed in #20227. It will be addressed via #20228.

**Comment by PunkPun** [comment] 2023-09-08 15:02
I could no longer reproduce the behaviour on bleed after the merge of that PR

**Comment by RoosterDragon** [comment] 2023-09-08 15:05
Well #20227 didn't change anything in this regard. So it's either been solved prior to that PR by accident, or it's possible that recreating it has become more stuble but is still possible - since #20228 has changes to address it which have yet to be merged.

**Comment by PunkPun** [comment] 2023-09-08 17:58
It has added a bunch of additional checks which prevent invalid targets from being picked

**Comment by PunkPun** [comment] 2023-09-09 10:50
My testcase was seeing if AI selects stealthed actors as targets, and wether it stops targeting actors that become stealthed. In both of these situations were the AI acted correctly

**Closed** 2023-09-11 11:57 UTC
Labels: Bug, Performance, AI
