### ISSUE TITLE
TD/RA Tanya/Commando/Engineer Building entry.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11416] opened 2016-06-07 22:23 UTC
Is there a way for the units Tanya, Commando, Engineer (TD) to have them enter into only part of the building instead of the center? This would help prevent the units being crushed which are not standing on the tile as they do the entry animations.

**Comment by pchote** [comment] 2016-06-07 23:33
Related to / partial duplicate of #5183.

Related to #8064.

**Comment by pchote** [comment] 2017-05-14 14:00
#13196 introduces a new `Target.Positions.PositionClosestTo()` method that does most of the work we need to fix this.

**Comment by pchote** [comment] 2017-05-14 15:17
I have f0dd2ee511cb0b252684678287708dd3263512d7 ready to fix this as soon as #13196 is merged.

**Closed** 2017-06-17 19:18 UTC
Labels: Feature
