### ISSUE TITLE
Non-stacking units can not queue order

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#16882] opened 2019-08-05 07:43 UTC
Some units can stack on the same cell (see https://github.com/OpenRA/OpenRA/issues/16880), but for units that don't, this also lead to their own problem. This is typically an issue with hinds, where you can't queue more order because they never reach their destination:

![hind-nostack](https://user-images.githubusercontent.com/34467/62447321-6a080080-b765-11e9-9f16-22bd163cf798.gif)

Reproduced with bleed @ 58bb7fcbc

**Comment by Punsho** [comment] 2019-08-05 08:17
It is not a bug but a lack of a feature. Helicopters behaved like this forever and the only fixes I see is letting helicopters bunch up like in sc2 or develop scattered move orders like in original TS and RA2

**Comment by tovl** [comment] 2019-08-05 10:32
This is indeed not a new issue, but all the other improvements for queued orders make this stand out like a sore thumb. It also greatly diminishes the usability of some other aircraft improvements for next release. This makes this a far more urgent issue than it has been before.

I am already working on a fix that will implement scattered move orders for aircraft that I hope can be merged before next release.

**Comment by matjaeck** [comment] 2019-08-05 10:33
#13753, #10449

**Comment by abcdefg30** [comment] 2019-08-05 12:17
Closing as duplicate then.

**Closed by abcdefg30** 2019-08-05 12:17 UTC
