### ISSUE TITLE
Different type of "cash\money"

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13235] opened 2017-05-03 20:58 UTC
From what i understand there is only 1 type of currency, and all resource gathering is related to that.

For new mods that are going far from the basics of C&C logic (resource related at least) this could be a preventing factor for making these kinds of mods.

As we know the OpenRa engine aims to be a more wide and open base for more and new "games".

For example we want to add more requirements to build a castle, not only money but also stone, there are other examples like TS chemical missile.
In my case i wan't to add research points that are gathered via tech centers like an oil, in order to research new tech but prevent players doing so by the use of money.

**Comment by pchote** [comment] 2017-05-03 21:00
Duplicate of #9872.

**Closed by pchote** 2017-05-03 21:00 UTC
