### ISSUE TITLE
Captured turrets shot friendfire when the unit was targeted as enemy

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7403] opened 2015-01-30 01:24 UTC
I have experienced this with both transport helicopter and longbow. But he only shots down one and does not continue to another, The turret will stop firing on it's target if you press (default S).
![openra game_2015_01_30_00_43_01_958](https://cloud.githubusercontent.com/assets/7798635/5969685/0def56f6-a827-11e4-84be-dee57c239a8e.png)

**Comment by MicroJOo** [comment] 2015-01-30 02:37
link to the map and a uploadet replay would help

**Comment by Snurre86** [comment] 2015-01-30 02:45
There are no replays for single player missions ? The mission is ""Survival 01 hard" in "PT 20150118"

**Comment by Mailaender** [comment] 2015-01-31 09:16
Every game is recorded for debugging purposes.

**Comment by abcdefg30** [comment] 2015-01-31 09:28
> (abcdefg30) Mailaender: https://github.com/OpenRA/OpenRA/issues/7403#issuecomment-72310637 where are the replays of the sp missions?
(pchote) abcdefg30: replays aren't saved for singleplayer missions
(abcdefg30) ^ the link says sth different
(pchote) so it does
(pchote) but that doesn't change what the game (doesn't) do :P
(pchote) there were issues with singleplayer replays always desyncing, and a few secondary concerns about them giving away too much info / showing unpolished scripted stuff
(Mailaender) oh
(pchote) so the mission browser specifically disabled the replay saving when it starts the game 
(Mailaender) you may correct me then at https://github.com/OpenRA/OpenRA/issues/7403#issuecomment-72310637
(abcdefg30) k

**Comment by MicroJOo** [comment] 2015-01-31 11:01
im not keen of playing that mission over and over again , to find the problem ... or to reproduce ... just because the replays are deactivated .... 
sorry

**Comment by abcdefg30** [comment] 2015-02-02 13:48
I don't think you've to play this mission in order to reproduce the bug.
(The SAM Sites targeting isn't scripted.)

**Comment by Mailaender** [comment] 2015-02-02 20:07
Was the SAM site captured while it was targeting that helicopter?

**Comment by pevers** [comment] 2015-02-23 22:44
I can reproduce this:
1. Settle engineer to take over SAM site
2. Take SAM site while it is targetting choppa
3. If the choppa is still alive it will also still be targetted

Looks like change of owner doesn't change already targetted actors.

**Comment by penev92** [comment] 2015-02-23 23:03
This should then be an easy fix. :)

**Comment by pevers** [comment] 2015-02-23 23:03
I'll give it a try.

**Comment by jabbink** [comment] 2015-02-24 14:02
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs#L89

While already attacking this will make sure it continues to attack the same target, I think.

**Comment by pevers** [comment] 2015-02-24 14:12
@jabbink there are multuple issues. One of them is that AttackGarrisoned is not cancelled when ownership is transferred. I'm fixing it atm.

**Comment by Snurre86** [comment] 2015-02-28 08:38
This happens with all turrets that are captured after it has made a target.

**Comment by Phrohdoh** [comment] 2015-03-12 21:36
Closed with #7544.

**Closed by Phrohdoh** 2015-03-12 21:36 UTC
Labels: Bug, Easy

**Comment by Snurre86** [comment] 2015-04-24 19:13
Fixed in playtest 2015-04-18.
