### ISSUE TITLE
Latency stats viewable during game play.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#20224] opened 2022-08-27 12:27 UTC
Multi player games often are impacted by lag. The connection of one or more players being slow or rather the PC of a player not being able to keep up with the game. 

Currently we can see the latency of players in the lobby in for form of a red, amber green color. This is good. 

Showing detailled absolute latency/ping information in numbers on players may not be beneficial - as it may get many players excluded from games.

However it would be useful to be able to see the red/amber/green latency status of players in game - during gameplay.

Feature request:
- Show latency in game i.e. under settings menu

Benenfit:
- Take the guessing out of which player started to lag. 
- Avoid the poisenous culture of people getting blamed to lag and causing them to be excluded from games. 
- Reduce situations where 3+ games in a row are unplayable due to lag. 
- Convince players with latency issues that they really have latency issues. I.e. allowing you to refer them to some documentation on what they could check and do to resolve it. Everyone always claims they have the fastest connection on earth.

**Comment by dragunoff** [comment] 2022-09-20 14:10
Duplicate of #4577?

**Closed as not planned** 2022-09-20 15:15 UTC
Labels: Idea/Wishlist, Networking

**Comment by anvilvapre** [comment] 2022-09-20 18:27
@teinarss Perhaps/optionally you could consider this in future.

Should be very well possible now with the new netcode running in a seperate thread. Ping requests from the server could be returned asap.

Also, in the old situation - it is only good that the latency also includes game logic and render times. Latency does not only have to be network. Only an indicator of "client speed".
