### ISSUE TITLE
TD SAM site and advanced guard tower don't play building notifications

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#11073] opened 2016-04-08 13:45 UTC
See title

**Comment by pchote** [comment] 2016-04-08 13:47
Duplicate of #11052 maybe?

**Comment by Biofreak1987** [comment] 2016-04-08 13:51
Dunno, I've tested it without a building que and those 2 structures never played the "Building" sound.

**Comment by obrakmann** [comment] 2016-04-08 18:55
This one is new though, and git bisect points to #10570.

**Closed** 2016-04-16 17:00 UTC
Labels: Regression
