### ISSUE TITLE
Engineer repair improvement

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#5183] opened 2014-04-22 22:56 UTC
im trying hard to get more use out of him by using him to repair important buildings , the construction yard for example ... 

it often fails on the fact , that the engineer has to reach the "center" of a building to enter it ... 
in the case of an contruction yard , its like 1,5 cell walking above the building before the repair triggers ... that is enough time for my enemy , to destroy the building with like 1 hp left , or even kill the engineer "walking above the building" before he reaches the center 

yellow point is the trigger (or it feels like that atleast) : 

![3time](https://cloud.githubusercontent.com/assets/1997864/2771879/fc5e62a2-ca72-11e3-93a0-450095e4a17a.png)

![trigger](https://cloud.githubusercontent.com/assets/1997864/2771810/56d55332-ca71-11e3-82e6-5e97c709bbc6.png) 

since there is not really alot use for engineers anymore ... i suggest we make it more easier for him to save a building from being destroyed ... let him enter the building on the first cell of the building he touches ... 
##

**Comment by HenrytheSlav** [comment] 2015-09-21 14:10
While I disagree with this conceptually (I prefer the entering inside), it would solve #8064

**Comment by pchote** [comment] 2017-05-14 13:58
Closing as reverse-duplicate of #11416.

**Closed by pchote** 2017-05-14 13:58 UTC
Labels: Polish
