### ISSUE TITLE
Enter enemy transports

### ISSUE THREAD

**Issue by Kanar** [OpenRA/OpenRA#5614] opened 2014-06-11 22:45 UTC
Holding ctrl, you can make various weapon-less units (dog, engy, spy, mechanic, hijacker (!), mcv, radar jammer, mobile gap, money truck, minelayer and so on) enter enemy transport ships, helitrans, apcs, phase tanks or rangers.

Also, the hijacker can't hijack transport ships and helitrans (only enter em with ctrl).
##

**Comment by penev92** [comment] 2015-02-14 17:21
This should be rechecked now that #7445 was merged.

**Comment by Mailaender** [comment] 2015-02-28 10:46
This is still not fixed:

![image](https://cloud.githubusercontent.com/assets/756669/6425869/6c92337a-bf3f-11e4-86d2-0b82c558fb82.png)

**Comment by matjaeck** [comment] 2018-08-13 14:29
I can not reproduce this in RA of playtest-20180729. It is worth to note that if you use right-click-orders, the unit will move to the cell next to the blocked cell (heli does not block due to another known issue), however when you use left click orders it will deselect the unit on ctrl+left click on the enemy actor, which is the same behavior as in #13723.

![101](https://user-images.githubusercontent.com/37185497/44037939-e9ac460c-9f15-11e8-9238-495f880e8e64.gif)

**Closed** 2018-08-13 14:36 UTC
Labels: Bug
