### ISSUE TITLE
Resolution too small, can not be changed OSX

### ISSUE THREAD

**Issue by nothingleftinside** [OpenRA/OpenRA#13261] opened 2017-05-07 23:49 UTC
I just downloaded this and started a game, but I thought the resolution was too big for my tastes. I went to the preferences and my only other choice was "legacy" so i selected that and re-launched. Now it is way too big and I can only see the upper left 1/4 of the game. I can stumble to the preferences again but I don't have any options other than legacy resolution. I re-installed and the problem persists. There is no openRA directory in my Application Support folder, so I can't change the resolution there.

**Comment by Phrohdoh** [comment] 2017-05-07 23:55
Hi @nothingleftinside,

Sorry about this situation, it sounds quite irritating.

You said you started a game which implies you have the content installed (which lives in `~/Library/Application Support/OpenRA/Content/`).

Are you absolutely positive that `~/Library/Application Support/OpenRA/` doesn't exist?

**Comment by nothingleftinside** [comment] 2017-05-08 03:47
Yes. There is no OpenRA folder in /Library/Application Support. It is very
strange

**Comment by Phrohdoh** [comment] 2017-05-10 02:24
Pinging @pchote

**Comment by pchote** [comment] 2017-05-10 18:27
The directory is inside `~/Library/Application Support`, not `/Library/Application Support/`.  It is a hidden directory that can't be seen by default through the Finder.  Press cmd+shift+g in a finder window and then paste the path to open in.

The Legacy renderer bug is caused by #13216.

**Comment by pchote** [comment] 2018-03-04 09:58
This was fixed by #13282.

**Closed by pchote** 2018-03-04 09:58 UTC
Labels: Bug, OS: MacOS X
