### ISSUE TITLE
Secondary Resources (Power)

### ISSUE THREAD

**Issue by ben132** [OpenRA/OpenRA#20613] opened 2023-01-14 13:39 UTC
I don't know if this is the correct way to phrase it.
I am refering to Power as secondary resouces, it would be fun to have factions that do not require Power but instead Food like with Warcraft and Starcraft.  Then have a faction that requires either or even both would be possible, or combining the factions and mechanics like in Cameo.

**Comment by abcdefg30** [comment] 2023-01-15 21:38
Duplicate of #20305.

**Closed as completed by abcdefg30** 2023-01-15 21:38 UTC
Labels: Idea/Wishlist
