### ISSUE TITLE
Add Documentation On Weapon traits

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13659] opened 2017-07-19 11:55 UTC
As the title say. there is no way to know what to add or how to use with weapon traits when there is not any documentation on the subject.

They only way atm is to learn from the existing yaml files, but they don't come with a full list of all traits or comments to explain the logic of the traits that are being used.

**Comment by abcdefg30** [comment] 2017-07-19 13:23
Duplicate of #9880.

**Closed by abcdefg30** 2017-07-19 13:23 UTC
