### ISSUE TITLE
Transport Boats dont move all to the landing spot

### ISSUE THREAD

**Issue by Serasul** [OpenRA/OpenRA#4675] opened 2014-02-16 23:38 UTC
Example:

You command 3 units of transport boats to an iland.
but they dont all move to the strand NO only one the other two move behind the one in the water (in an line) so that you must order them seperate from eatch other to move to the strand .........
##

**Comment by FrameLimiter** [comment] 2018-07-26 15:13
Duplicate of #5968

**Closed** 2018-07-26 15:40 UTC
Labels: Pathfinding, Polish, Red Alert
