### ISSUE TITLE
OutOfMemoryException when playing large maps

### ISSUE THREAD

**Issue by pekq** [OpenRA/OpenRA#14178] opened 2017-10-14 20:55 UTC
Had three out of memory crashes with the `release-20171014` playing online multiplayer (RA mod) today.  
```Exception of type `System.OutOfMemoryException`: Out of memory```  

Two the games had fairly large maps and one had huge. While playing the biggest map of the three the crash happened already in the early game, so the size of the map might be a factor.

[exception-2017-10-14T191305Z.log](https://github.com/OpenRA/OpenRA/files/1384972/exception-2017-10-14T191305Z.log)
[exception-2017-10-14T173429Z.log](https://github.com/OpenRA/OpenRA/files/1384973/exception-2017-10-14T173429Z.log)
[exception-2017-10-14T170228Z.log](https://github.com/OpenRA/OpenRA/files/1384974/exception-2017-10-14T170228Z.log)

Hardware:
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,2
  Processor Name:	Intel Core i7
  Processor Speed:	2,2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
```

Running latest Mono:
```
$ mono --version
Mono JIT compiler version 5.2.0.224 (d15-3/14f2c81 Thu Aug 24 10:33:52 EDT 2017)
```

**Comment by GraionDilach** [comment] 2017-10-14 21:03
My question would be if that you were having these crashes on your first game or you got these on your nth game start (asin, 5th round or something)?

**Comment by reaperrr** [comment] 2017-10-14 21:05
Pinging @RoosterDragon to take a look.

**Comment by GraionDilach** [comment] 2017-10-14 21:11
I suspect that this will be related to what I'm saying for years now - OpenRA doesn't unload/free the unused tilesets during map load - however this was prematurely closed in #11419.

**Comment by pekq** [comment] 2017-10-14 21:16
@GraionDilach not sure if I understood you correctly but I played in total of ten games today and three of them crashed (with the same exception). One crash was in the early game (biggest map) and two of them happened in the late game (> 15min).  

I went through my other exception logs and didn't find similar cases happening with the earlier releases so this must be some sort of regression.

**Comment by pekq** [comment] 2017-10-14 21:24
@GraionDilach sorry I can't recall whether or not the crashes happened after playing several games on the same session.

**Comment by theKalash** [comment] 2017-10-15 15:08
Actually, I already had these crashes (out of memory) with the last playtest. Especially towards the end of long games with lot's of units. 

Also in a MacBook.

**Comment by pchote** [comment] 2017-10-15 15:44
> I suspect that this will be related to what I'm saying for years now - OpenRA doesn't unload/free the unused tilesets during map load - however this was prematurely closed in #11419.

I still haven't seen any evidence for leaks in the tileset code, but we *do* leak sequence textures.  See discussion in #12494.

**Comment by gdavegdave** [comment] 2017-10-20 12:59
I've experienced a lot of crashes too (12 times in the past 3 days), since updating to release-20171014 and upgrading Mono. This is the Mono I have now:  
Mono JIT compiler version 5.4.0.201 (2017-06/71277e78f6e Thu Sep 21 19:22:55 EDT 2017)

I also crashed with a previous version of Mono, which suggests that the issue lies with OpenRA:
Runtime Version: Mono 4.8.1 (mono-4.8.0-branch/22a39d7) CLR 4.0.30319.42000

I attach two exception logs (experienced with each mentioned version of Mono).
[exception-2017-10-17T141830Z.log](https://github.com/OpenRA/OpenRA/files/1401964/exception-2017-10-17T141830Z.log)
[exception-2017-10-20T124836Z.log](https://github.com/OpenRA/OpenRA/files/1401960/exception-2017-10-20T124836Z.log)

**Comment by gdavegdave** [comment] 2017-10-20 13:04
I've experienced  a lot of crashes too (12 in the past three days), all with 'Exception of type `System.OutOfMemoryException`: Out of memory'.

My current version of Mono is:
Mono JIT compiler version 5.4.0.201 (2017-06/71277e78f6e Thu Sep 21 19:22:55 EDT 2017)

But I also experienced these type of crashes with the another version of Mono:
Runtime Version: Mono 4.8.1 (mono-4.8.0-branch/22a39d7) CLR 4.0.30319.42000

That leads to believe that the issue lies with OpenRA - did something change that could've exacerbated this issue with release-2017014 (that wasn't in the playtest).

I attach exception logs for crashes experienced with both of those versions.
earlier:
[exception-2017-10-17T141830Z.log](https://github.com/OpenRA/OpenRA/files/1401986/exception-2017-10-17T141830Z.log)
later:
[exception-2017-10-20T124836Z.log](https://github.com/OpenRA/OpenRA/files/1401987/exception-2017-10-20T124836Z.log)

**Comment by gdavegdave** [comment] 2017-10-21 13:13
I experienced a few more crashes:
[exception-2017-10-21T131234Z.log](https://github.com/OpenRA/OpenRA/files/1404120/exception-2017-10-21T131234Z.log)
[exception-2017-10-20T194917Z.log](https://github.com/OpenRA/OpenRA/files/1404121/exception-2017-10-20T194917Z.log)
[exception-2017-10-20T001948Z.log](https://github.com/OpenRA/OpenRA/files/1404125/exception-2017-10-20T001948Z.log)

**Comment by gdavegdave** [comment] 2017-10-23 11:10
More crashes with:
"Exception of type `System.OutOfMemoryException`: Out of memory"

[exception-2017-10-22T193957Z.log](https://github.com/OpenRA/OpenRA/files/1406806/exception-2017-10-22T193957Z.log)
[exception-2017-10-22T011828Z.log](https://github.com/OpenRA/OpenRA/files/1406807/exception-2017-10-22T011828Z.log)
[exception-2017-10-21T152715Z.log](https://github.com/OpenRA/OpenRA/files/1406808/exception-2017-10-21T152715Z.log)

I do not think it happens only when playing very large maps

**Comment by theKalash** [comment] 2017-10-23 11:16
@gdavegdave no, I reproduced it on 128x128 regularly and even on 96x96 map. It takes considerably longer though.

**Comment by gdavegdave** [comment] 2017-10-23 14:21
Yeah, that sounds like it @theKalash . I've taken to restarting OpenRA every game, yet still I get crashes. Just now on a long game on a 3v3:
[exception-2017-10-23T110925Z.log](https://github.com/OpenRA/OpenRA/files/1407484/exception-2017-10-23T110925Z.log)

**Comment by RoosterDragon** [comment] 2017-10-23 19:23
Does a replay of the crashing game still manage to get created? If so:

- Do you still crash with out-of-memory if you watch the replay to the end?
- If not, once you reach the end, is OpenRA using a large amount of memory? How much?
- If you could share one of the replays, that might be helpful.

I notice everybody in this thread so far has been using Macs, I'd be curious to know if any non-Mac users have been seeing similar crashes during long games in the recent releases.

**Comment by theKalash** [comment] 2017-10-23 21:12
They create replays. I just watched one and it runs normally all the way to the end (99%) and then the game crashes.

Memory usage does go up steadily, during games and replays. It was at around 700mb on the last crash, about the same before (the spikes are all crashes, last one was the replay).

![screen shot 2017-10-23 at 10 27 10 pm 1](https://user-images.githubusercontent.com/19913563/31913240-eac7c978-b846-11e7-9a6a-d88ab48c9594.png)
![screen shot 2017-10-23 at 11 06 43 pm](https://user-images.githubusercontent.com/19913563/31913241-eae44bfc-b846-11e7-80c2-f0e6a1db3076.png)

I can share you a replay tomorrow or so, have to make one with a crash on the unmodded version.

**Comment by pekq** [comment] 2017-10-23 21:54
> Do you still crash with out-of-memory if you watch the replay to the end?  

Nope

> If not, once you reach the end, is OpenRA using a large amount of memory? How much?  

![image](https://user-images.githubusercontent.com/4521827/31914905-3ef46764-b855-11e7-91d6-2b0d82c94d3d.png)

> If you could share one of the replays, that might be helpful.  

[OpenRA-2017-10-14T172745Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1408862/OpenRA-2017-10-14T172745Z.orarep.zip)

**Comment by theKalash** [comment] 2017-10-24 11:23
[OpenRA-2017-10-24T092709Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1410531/OpenRA-2017-10-24T092709Z.orarep.zip)

Another replay of a crash. I watch it all the way again and this time the game didn't crash.

I'm pretty sure I can explain why the replay yesterday crashed and this one didn't. 

Whatever problem there is, it cumulates between games if you do not restart the client. So I played a short game (that ended with a player winning) and then recorded another game that went on to crash. 

Now if I restart the game I can watch the replay and it will just run to the end and finish. 

However, restart the client, go directly into a game that runs long enough till it crashes then the client will also crash when watching the replay because all the "memory" came from that one game.

**Comment by ugotbroiled** [comment] 2017-10-25 16:49
I have also been experiencing this issue, which has occurred frequently since I updated mono from V4.0.1 to V5.2.0215 and most recently 5.2.0.224
exception-2017-10-24T225310Z.log

**Comment by gdavegdave** [comment] 2017-10-25 21:05
@ugotbroiled - another OSX user. InsaneH / Han is also suffering crashes and he is also on OSX. So it seems OS specific. Devs - any idea if the issue may lie with OpenRA, Mono or whatever? Any ideas on troubleshooting / fixing the issue?

**Comment by pchote** [comment] 2017-10-25 21:54
> OpenRA-2017-10-24T092709Z.orarep.zip

On my system (macOS 10.13, mono 5.4.0) the memory usage grew from ~511 MB at the start of the replay to ~680 MB at the end.

Could we be leaking sound memory again?

**Comment by RoosterDragon** [comment] 2017-10-26 17:24
A straightforward first test would be:
- Wait 30 secs to let the memory settle after the game loads
- Stay in the menu
- Switch music tracks every, say, 20 seconds
- Keep switching tracks for, say, 5-15 minutes
- See if virtual memory & real memory usage seem to be creeping up without going back down
- Optionally, compare with starting the game, pausing music, and waiting for 15 minutes to pass

That should help us work out if it's music specifically being the problem on OSX.

Running on my Windows system, even running under mono, I don't see any indications of memory creeping up from the music tracks. There's a brief spike each time the track switches, but this goes back down to the previous level, usually within a few seconds.

**Comment by ugotbroiled** [comment] 2017-10-26 17:45
I don't even have the music installed and I still have the out of memory crash occurring frequently.

**Comment by theKalash** [comment] 2017-10-26 20:26
Would an issue with music explain why the issue seems to correlate with map size and/or amount of units in the game, generally? 

Because I can reproduce the crash much faster and more reliable on large maps or maps with high resources. Modifying the AI to build more stuff also seems to help (especially on maps with high resources) to induce the crash more quickly.

**Comment by pchote** [comment] 2017-10-26 20:28
I was thinking normal sounds (explosions, voices, etc), which will scale with unit count.

**Comment by theKalash** [comment] 2017-10-26 20:31
Ok, that makes sense. I do most of my testing against AI though. Is sound a factor for the AI? Because adding more AI (and thus units) increases crash frequency. 

Around 40 minutes on a very large map against a single aI vs 20-30 minutes against 3 or more. 

The amount of units I build and command doesn't change much in the at cases. Also the crash happens when observing games with only AI players (as you may have noticed in the replay you watched above).

**Comment by theKalash** [comment] 2017-10-26 20:35
Actually you might be right. The replay above on regeneration basin was quite long, It crashed a lot quicker when I was playing. So AI only would mean only the global sounds are played and not the voices, giving it a considerable longer time to build up memory before crashing.

So sound might be it after all .. i really don't know enough about this, just speculating from experience.

**Comment by pchote** [comment] 2017-10-26 21:07
@gdavegdave, @theKalash: Can you please try out this build: [[dropbox link](https://www.dropbox.com/s/g8a1706h9dq6p7e/OpenRA-release-20171014.dmg?dl=1)]?

This changes OpenRA to run as a 64 bit application that can access all of your system RAM.

From your perspective this should defer the crashes to the point where they shouldn't happen during a normal gaming session.  From our perspective it will be interesting to see if your memory usage keeps on growing indefinitely (indicating a real leak), or stabilizes at some point not much larger than the 32 bit vmem limit.

**Comment by theKalash** [comment] 2017-10-27 10:26
Yeah, that seems to work well. Couldn't get a crash so far. 

![screen shot 2017-10-27 at 12 21 44 pm](https://user-images.githubusercontent.com/19913563/32099736-cbbcaee0-bb11-11e7-867a-fb668c7d96fa.png)

The bottom arrow shows the start of the game with memory growing to around 1.2GB and then drops from "active" to "inactive" memory. Top arrow is the end of the game.

**Comment by gdavegdave** [comment] 2017-10-28 21:44
@pchote, I haven't experienced another crash yet. I've been using that custom build and not restarting.

**Comment by djlists** [comment] 2017-10-29 02:31
I'm on OSX and just got an outofmemory crash with the latest version. I never play the music. I'll try the 64 bit version.

Exception of type `System.OutOfMemoryException`: Out of memory
GC Memory (post-collect)=241,257,744
GC Memory (pre-collect)=444,415,144
Working Set=469,426,176
Private Memory=469,426,176
Virtual Memory=1,530,564,608

**Comment by djlists** [comment] 2017-10-29 15:01
I let the computer play a handful of similar games and so far no crash with the 64 bit version.

**Comment by visav** [comment] 2017-11-03 20:11
Also having crashes on macOS 10.12.6 (16G29):
```
$ mono --version
Mono JIT compiler version 5.2.0.215 (d15-3/da80840 Thu Jul 20 16:43:07 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen (concurrent by default)```

After playing (or spectating) bigger maps that take a while to play, the game just suddenly crashes. This occurs frequently with big maps / more players. Most of the times there is no `exception-*.log` s at all after the crash. `debug.log`, `perf.log` etc are written, but these vary between crashes.

**Comment by CH4Code** [comment] 2017-12-16 12:32
The game also crashes with an OutOfMemoryException if you use the map editor to create maps of size larger than 888x888 on my PC. Idk at which map size it exactly crashes, but this is the highest still possible on my machine which I tried.
Is an issue, since you can create maps up to size 999x999 by default.

**Comment by LipkeGu** [comment] 2018-01-16 18:49
It tried this with TS the map was around 888 * 888 in VS and it crashes at
![outofmemory](https://user-images.githubusercontent.com/2057932/35006175-3caed41a-faf6-11e7-98eb-8893a9cbe548.png)

**Comment by pchote** [comment] 2018-01-16 20:05
The map editor is a development tool, and it is the responsibility of the user to take the responsibility of not shooting themselves in the feet with it.  Properly baby-proofing it would require an unreasonable amount of effort and would very likely break use cases that we want to be able to support.

The original premise of this issue is about playing our sensibly sized shipped maps, which happen to be labeled in the map chooser as "Large" (between 90 and 119 cells square) and "Huge" (larger than 120 cells square) in the map chooser.

**Comment by GraionDilach** [comment] 2018-01-16 22:32
I'd like to mention here however that for some reason I never seen a RA2 map not labelled as Large in OpenRA. If anything, we should be able to support any map where the sum of it's width and height are less than 512 because that was the maximum the legacy games could be capable of.

**Comment by LipkeGu** [comment] 2018-01-17 01:17
I can remember that final sun putted a warn message that the games can have problems with maps in such sizes.

**Comment by GraionDilach** [comment] 2018-01-17 10:11
FinalSun/FinalAlert are not relevant to TS/RA2, they were made by an outside developer and WW just bought the software thenafter.

**Comment by RoosterDragon** [comment] 2018-01-17 20:05
64-bit builds are quite happily capable of creating the current maximum of 999x999 - so on platforms that currently support it - there's no problem.

**Comment by abcdefg30** [comment] 2020-08-29 20:16
Closing due to inactivity, perf has improved over time.

**Closed by abcdefg30** 2020-08-29 20:16 UTC
Labels: Crash, Performance
