### ISSUE TITLE
Idea for mechanics and ally husks

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#9960] opened 2015-11-11 00:17 UTC
Was playing RA multilayer the other day and one of my allies lost their MCV, I put a mechanic in to try to revive it, however, it came back as my unit, would be good if it remained their unit if the husk belongs to an ally. There have also been cases where I've wanted to allow an ally to capture my second construction yard, could be good to allow allies buildings to be captured, not sure whether this would be better if you explicitly allowed it, not doing so would open the game up to ally sabotage, which would take a lot of collaborative planning so might be worth allowing as a game tactic?
##

**Comment by penev92** [comment] 2015-11-11 12:27
I'm really not convinced of both of the proposed changes.

**Comment by Phrohdoh** [comment] 2015-11-11 12:36
Please keep one idea to a ticket.
Partial duplicate of #5691.

**Closed** 2018-11-25 18:20 UTC
Labels: Idea/Wishlist, Red Alert
