### ISSUE TITLE
Evacuation issue

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11755] opened 2016-08-01 01:48 UTC
#6754 followup

on bleed ... 
1. Create a server with any map (singleplayer or multiplayer doesnt matter)
2. While on the server, pick the mission "Evacuation" (or a minigame , just something with different options)
3. Leave the server (check the options before)
4. Create server again (leave map as is , should be Evacuation or the mini-game you had before)
5. Now pick a standard conquest map ... 
6. Check the options 

the conquest-map should now have the same options as Evacuation (Boac off, short game off) and every map you pick afterwards ... will have the same options as Evacuation unless you start your server with a standard conquest-map

@pchote : http://i.imgur.com/gDQk9GQ.gif :)

**Comment by obrakmann** [comment] 2016-08-03 17:20
The critical part here is that you need to set the starting map to one with non-standard rules. It looks like the server will then use those settings as default whenever you switch to a map that doesn't lock them.

**Comment by abcdefg30** [comment] 2019-09-18 13:07
This sounds like intentional behaviour. The game doesn't differentiate between a map changing the options and a player doing so. Resetting back to default settings on map change sounds like a bad idea to me. The only thing I can imagine is storing which settings were forcibly overwritten and resetting those, but I don't know if it is really worth the effort.

**Comment by abcdefg30** [comment] 2020-08-29 21:05
Duplicate of #15545.

**Closed by abcdefg30** 2020-08-29 21:05 UTC
Labels: Bug, UI
