### ISSUE TITLE
Add observer/replay interface features to TD [$25]

### ISSUE THREAD

**Issue by RiderRockon** [OpenRA/OpenRA#4716] opened 2014-02-23 15:52 UTC
Currently there are none, and much has been said about redesigning the existing window in Red Alert, so simply using that would not suffice.

I've drawn up a few mock ups of how these might look, trying to adhere to the style already present in the TD UI.

![productiontabopenra-3](https://f.cloud.github.com/assets/6692167/2240667/41dcd8bc-9ca2-11e3-8248-46cd4d1fefd9.jpg)

![economytabopenra](https://f.cloud.github.com/assets/6692167/2240669/636f6d96-9ca2-11e3-861c-d7af2779510a.jpg)

![assetcounttabopenra](https://f.cloud.github.com/assets/6692167/2240671/67181042-9ca2-11e3-99f3-cdfc68661ed6.jpg)

**Comment by StexoO** [comment] 2015-06-02 17:37
And a useful feature when you spectate a game or watch a replay is to bring face to face players/teams statistics, like the two red and blue bars in the center of this screenshot (from Starcraft 2).
![guides_gw2_spectator2](https://cloud.githubusercontent.com/assets/8930382/7941823/217ef516-095a-11e5-998a-d79bfd1a6c16.jpg)

**Comment by pchote** [comment] 2015-11-22 12:13
Closing as reverse-duplicate of #5121.

**Closed by pchote** 2015-11-22 12:13 UTC
Labels: Bounty, Feature, Tiberian Dawn

**Comment by Mailaender** [comment] 2016-11-10 21:22
Note: there is still bounty on it https://www.bountysource.com/issues/1424131-add-observer-replay-interface-features-to-td which needs to be retracted.
