### ISSUE TITLE
PVE Game Freeze Which May Caused By AI Attacking Stealth Units Or Structures

### ISSUE THREAD

**Issue by HansNilhall** [OpenRA/OpenRA#17173] opened 2019-10-04 18:33 UTC
### Issue Summary

When AI tries to detect or attack some stealth units or structures, the game then might freeze and can only be closed by task manager. I have received several these kinds of reports from Chinese community and then try to test them out. Now as I myself have reproduced one of that circumstances which might cause bug, I believe it should be an issue.

In RA mod, there are two reports. 
1. At the moment when the reporter's Missile Sub was attacked by some AI infantries while the sub was trying submerging after firing missiles, the game froze.  
2. In Allies Mission 08b, after laying some mines by using Minelayers on the field, the game might freeze. _**(This is the circumstances I reproduced)**_

In SP mod, there are also two reports.
1. The game froze when AI tried to attack the Nod stealth tank which is trying to stealth again after hit-and-run or the buildings which are protected by Nod stealth generator.
2. When AI tried to attack CABAL's deployed Abductor or mines layed by CABAL's Artisan.

**The second circumstance is the only one I can reproduce by myself because the others are reported by different Chinese players** and **I only experience others in multiplayer PVE while we were testing those two problems from SP**. And we are using different OS.

#### System Information

I will use some special marks to show or explain clearly in the section of System Information
 **bolded texts** - means my situation while reproducing the bug;
 _italic text_ - means other testers and me while experience the bug in SP;
 '...' - means the reporter's OS of the first circumstance of RA.

- **Operating System:** **Win10**, 'Win7 64x', _Win10 Win7_
- **.NET / Mono Version:** **.NET 4.8**, 'Unknown', _.NET 4.8 .NET 4.7_ 
- **OpenRA Version:** **playtest-20190825**, 'release-20190314, _SP release-20190623_
- **Mod:** **Red Alert**, 'Red Alert', _Shattered Paradise_

#### Additional Information:
**- Steps to reproduce**
	1. Allies Mission 08b
	2. Clear the road to the base
	3. Use the minelayers to set mines on the way which enemies must come from
        4. Wait or play normally until the game freeze
        _PS: FiveAces had reported the same thing on discord channel on 26th, Aug 2019._

**- Logs**
_There is no useful log_

**- OpenRA Replays**
[Allies 08b - playtest-20190825.zip](https://github.com/OpenRA/OpenRA/files/3691747/Allies.08b.-.playtest-20190825.zip)

**- Screenshots & Videos**

The sceenshot below was given by the reporters who reports the submarine freeze.
The cursor shows the game was freeze at that moment and in the red circle, an AI rifle man was trying to attack player's missile sub.
![QQ截图20191005021013](https://user-images.githubusercontent.com/56157741/66229846-594c1a80-e715-11e9-9e0f-cd0ee812ff60.png)

The screenshot below was the moment when the game freeze while playing Allies Mission 08b.
The white fog-like thing is the special effect of the app having no respond in Win10.
This one was captured by myself.
![QQ图片20191005020618](https://user-images.githubusercontent.com/56157741/66229847-594c1a80-e715-11e9-8388-9a39ad068503.png)

**Comment by pchote** [comment] 2019-10-04 22:45
Reproduced the freeze in `allies-08a` and used the debugger to break out and see that this is caused by the lua script calling `Actor.QueueActivity` which then seems to get in an endless loop of `Activity.Queue`. This suggests that we have an activity loop somewhere (activity has queued itself or another activity that has queued the first).

**Comment by pchote** [comment] 2019-10-04 22:49
Possibly related to:
> IMO this is getting pretty hacky. The real issue is that `ReturnToBase` cancels the whole queue, which is against our own guidelines for how activities should behave.
>
> The proper solution is to remove the activity cancelling from `ReturnToBase` entirely and let `FlyAttack` be solely responsible for breaking out of a potential infinite loop. This can be done by checking whether the branch of `FlyAttack.Tick` that calls `ReturnToBase` is entered two ticks in a row and going to `NextActivity` if that is the case.

_Originally posted by @tovl in https://github.com/OpenRA/OpenRA/pull/17030#issuecomment-528047732_

**Comment by tovl** [comment] 2019-10-06 18:14
The relevant part of the Lua script:

https://github.com/OpenRA/OpenRA/blob/acea19312d1e3cfcb0b95fd03208ef25c102ab0e/mods/ra/maps/allies-08b/allies08b-AI.lua#L131-L150

**Comment by pchote** [comment] 2019-10-09 12:31
That will certainly do it...

There is a good chance that the issue with submarines / SP units has already been fixed by the activity rework, so the best approach here will be to fix the script issue then consider this solved.

**Closed** 2019-10-11 19:00 UTC
Labels: Bug
