### ISSUE TITLE
Unit tooltips in the build menu should show stats.

### ISSUE THREAD

**Issue by Doctormedic** [OpenRA/OpenRA#4643] opened 2014-02-13 17:16 UTC
Stats such as health,damage at specific units,etc

**Comment by pchote** [comment] 2015-11-22 12:11
A third party mod could add this.  Otherwise, I agree with @UberWaffe that this is best done in the encyclopedia.  Closing as duplicate of #3788.

**Closed by pchote** 2015-11-22 12:11 UTC
Labels: Feature, UI
