### ISSUE TITLE
TS: Refinery/harvester explosions distribute wrong amount/type of resource.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#15826] opened 2018-11-17 09:55 UTC
In TS, any stored resource within actors had a chance to respawn when the containers got destroyed, this means that a harvester filled with blue tib would only spawn blue tib when killed (assuming said blue tib wouldn't explode along). The best one can do currently is to use CreateResourceWarhead, but there's no way to control the resource amount or type according to storage spawned that way.

**Comment by abcdefg30** [comment] 2018-11-17 19:50
Duplicate of #7490.

**Closed by abcdefg30** 2018-11-17 19:50 UTC
