### ISSUE TITLE
cannot surrender in multiplayer map

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#13227] opened 2017-05-02 21:47 UTC
Cannot surrender in this map
http://resource.openra.net/maps/20471/

**Comment by rob-v** [comment] 2017-05-03 09:13
It is caused by map's Visibility: MissionSelector. You can remove it and keep only Lobby, then all works fine (Surrender, stats, observer options).

**Comment by abcdefg30** [comment] 2017-05-09 21:16
This looks to be a duplicate of #13228, so closing (?).

**Comment by abcdefg30** [comment] 2017-05-09 21:19
Ah wait, this is actually a bit different, but https://github.com/OpenRA/OpenRA/issues/13228#issuecomment-298865510 explains why we "can't" allow surrendering. Although, we still allow spectators and a player should get the same behaviour after surrendering.

**Comment by rob-v** [comment] 2017-05-18 16:25
Surrender button is currently disabled in Missions but also in multiplayer when a map can be used both in lobby and mission. We can enable Surrender as agreed for these maps while in multiplayer, but is there a reason why not to enable it also for missions? 
Surrender in mission causes to play 'failure' video like when failing a mission objective. It seems to work fine as expected.

**Comment by Smittytron** [comment] 2021-03-14 21:12
Closing this as working as intended. It's fair to expect map makers to use the correct mission selector options, and maps in error can easily be fixed and reuploaded to the Resource Center.

**Closed by Smittytron** 2021-03-14 21:12 UTC
Labels: Bug
