### ISSUE TITLE
Save game on Missions & AI controlled skirmish sessions

### ISSUE THREAD

**Issue by PUOjACKz** [OpenRA/OpenRA#9780] opened 2015-10-27 13:00 UTC
In the original TS/RA1 game you could save the state of the single-player mission. This feature, at this moment, is not implemented yet. And I take the opportunity to ask to extend it even for AI-controlled Skirmish game sessions.

**Comment by penev92** [comment] 2015-10-27 13:12
I'm sure we already have an issue for that.

**Comment by atlimit8** [comment] 2015-10-27 15:14
Duplicate of #2743.

**Closed by atlimit8** 2015-10-27 15:14 UTC

**Comment by ndaidong** [comment] 2015-11-11 08:03
I like this idea. It would be better if we can save games and open them later.
