### ISSUE TITLE
Ability to start a rematch at the end of a game without exiting to lobby

### ISSUE THREAD

**Issue by vvaezian** [OpenRA/OpenRA#20724] opened 2023-03-04 07:26 UTC
It's common to request for "re" after the game ends (usually by the loser). It would be nice if this can happen without the need to exit to lobby and creating a new game.

**Comment by PunkPun** [comment] 2023-03-15 11:11
Duplicate of #15181

**Closed as not planned by PunkPun** 2023-03-15 11:11 UTC
Labels: Idea/Wishlist
