### ISSUE TITLE
Crash related to pathfinding to unreachable point, again

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20326] opened 2022-09-25 07:43 UTC
## System Information
- Operating System:  Win10
- OpenRA Version: SP engine with newst commit to bleed, unchanged to pathfinding
- OpenRA Mod: SP

## Exception log

```
OpenRA engine version f8ff174
Shattered Paradise mod version {DEV_VERSION}
on map 12b35c47aae1b7bdd48cbe3ee831dc5b1132738d (Borrowed Time by StolenTech).
Date: 2022-09-25 04:01:15Z
Operating System: Windows (Microsoft Windows NT 10.0.19043.0)
Runtime Version: .NET CLR 6.0.8
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. This is a bug. Failed lookup for an abstract cell.
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.<>c__DisplayClass40_0.<Heuristic>b__0(CPos cell) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 0
   at OpenRA.Mods.Common.Pathfinder.PathSearch.Expand() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 241
   at OpenRA.Mods.Common.Pathfinder.PathSearch.FindPath() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\PathSearch.cs:line 290
   at OpenRA.Mods.Common.Pathfinder.HierarchicalPathFinder.FindPath(Actor self, IReadOnlyCollection`1 sources, CPos target, BlockedByActor check, Int32 heuristicWeightPercentage, Func`2 customCost, Actor ignoreActor, Boolean laneBias, PathFinderOverlay pathFinderOverlay) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Pathfinder\HierarchicalPathFinder.cs:line 755
   at OpenRA.Mods.Common.Traits.PathFinder.FindPathToTargetCell(Actor self, IEnumerable`1 sources, CPos target, BlockedByActor check, Func`2 customCost, Actor ignoreActor, Boolean laneBias) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Traits\World\PathFinder.cs:line 89
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 131
   at OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 114
   at OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\Move.cs:line 129
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Mods.Common\Activities\Move\MoveAdjacentTo.cs:line 103
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Activities.Activity.TickChild(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 147
   at OpenRA.Activities.Activity.TickOuter(Actor self) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Activities\Activity.cs:line 111
   at OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Traits\ActivityUtils.cs:line 31
   at OpenRA.Actor.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Actor.cs:line 262
   at OpenRA.World.Tick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\World.cs:line 441
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 636
   at OpenRA.Game.LogicTick() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 651
   at OpenRA.Game.Loop() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 820
   at OpenRA.Game.Run() in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Game\Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in D:\work\Projects\Github\shattered-paradise-sdk-mirror\engine\OpenRA.Launcher\Program.cs:line 32
```

## Replay
[bugreplay.zip](https://github.com/OpenRA/OpenRA/files/9640237/bugreplay.zip)
This is a pretty long one, 33 mins

## Additional information
![bug2](https://user-images.githubusercontent.com/13763394/192133409-ebe5bf42-18a2-48fa-8125-3c73c50351d6.png)
It is the mk2 crash the game, doing pathfinding under cliff. But I cannot reproduce another when I trying in SP and in TS bleed.

![bug](https://user-images.githubusercontent.com/13763394/192133408-3a28523d-93b6-48ca-b0b6-e636ce7c256c.png)
grid position

![bug3](https://user-images.githubusercontent.com/13763394/192149947-0aa1b7dc-2b52-48dc-8c42-1151ffaed4af.PNG)
I will look into 93,2 on map tomorrow, it is the cause of the crash

**Comment by dnqbob** [comment] 2022-09-25 07:44
Note: you need to fix #20325 manually in engine (mods/common) before you can access replay

**Comment by RoosterDragon** [comment] 2022-09-25 15:29
Thanks for the report. This appears to be another crushability related issue. `hmec 2587` is trying to enter a cell occupied by `subtank 2722`, which is something it can crush. However at some point `subtank 2722` was above ground level, and thus not crushable.

Due to inconsistencies in timing, the game isn't sure whether the actor is crushable or not and crashes.

This will be fixed by #20329.

**Comment by PunkPun** [comment] 2022-10-07 08:28
I could not reproduce this crash on bleed. Units seem to work correctly around crushable subterraneans. Could this have something to do with custom mod code?

**Comment by dnqbob** [comment] 2022-10-07 09:29
https://github.com/MustaphaTR/OpenRA/commits/rv-engine/OpenRA.Mods.Common/Traits/Conditions/GrantConditionOnSubterraneanLayer.cs

so far we only add
1. sound control and related crash fix
2. resurface condition 

without modifying other place

**Comment by PunkPun** [comment] 2022-10-07 09:32
How were you able to fix subterranean units with just these changes though? #20334
This bug was present for multiple years

**Comment by dnqbob** [comment] 2022-10-07 09:48
Already tested it on another repo, jumpjet and sub tank are normal now
https://github.com/EoralMilk/OpenMeow

**Closed as completed** 2022-10-07 19:06 UTC
Labels: Crash
