### ISSUE TITLE
InvalidOperationException: Out of sync as spectator

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#17591] opened 2020-01-18 22:51 UTC
crash, multi player, game just started, few secs,  i was spec, asked a question to admin, admin replied, could read the reply, after which game crashed.

some ore gardens map.
 

Platform is Linux
Engine version is release-20191117
Using SDL 2 with OpenGL renderer
Desktop resolution: 1600x900
No custom resolution provided, using desktop resolution
Using resolution: 1600x900
Using window scale 1.00
OpenGL version: 3.0 Mesa 19.0.8
Using default sound device
Internal mods:
        modcontent: Mod Content Manager (release-20191117)
        ra: Red Alert (release-20191117)
External mods:
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
        ra-playtest-20190825: Red Alert (playtest-20190825)
        ra-release-20190314: Red Alert (release-20190314)
        ra-release-20191117: Red Alert (release-20191117)
Loading mod: ra
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
...
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
Exception of type `System.InvalidOperationException`: Out of sync in frame 508.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (System.Int32 frame) [0x00037] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00034] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Network.OrderManager+<>c__DisplayClass41_0.<TickImmediate>b__1 (System.Int32 clientId, System.Byte[] packet) [0x00038] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Network.EchoConnection.Receive (System.Action`2[T1,T2] packetFn) [0x00045] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00080] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Sync+<>c__DisplayClass13_0.<RunUnsynced>b__0 () [0x00000] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Sync.RunUnsynced[T] (System.Boolean checkSyncHash, OpenRA.World world, System.Func`1[TResult] fn) [0x00023] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Sync.RunUnsynced (System.Boolean checkSyncHash, OpenRA.World world, System.Action fn) [0x0000d] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x000fb] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Game.LogicTick () [0x0003e] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Game.Loop () [0x000e3] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Game.Run () [0x0003c] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <41ea05b7ed284beb982b402d91ea028d>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00044] in <41ea05b7ed284beb982b402d91ea028d>:0 

AL lib: FreeContext: (0x2e89640) Deleting 32 Source(s)

**Comment by Mailaender** [comment] 2020-01-18 23:10
Duplicate of https://github.com/OpenRA/OpenRA/issues/16614.

**Comment by Mailaender** [comment] 2020-01-18 23:11
Sorry. That was just a warning. The real crash is:

```
Exception of type System.InvalidOperationException: Out of sync in frame 508.
Compare syncreport.log with other players.
```

Please collect all the `syncreport.log` files.

**Closed** 2020-01-25 19:40 UTC
Labels: Crash, Networking, OS: Linux
