### ISSUE TITLE
Movement glitch

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#9404] opened 2015-09-22 11:23 UTC
There is a movement glitch in the latest release. It appears that sometimes, when a unit stops, its visual position is not properly updated and does not match its actual position. When the unit begins moving again, its sprite kinda "morphs" or slides into the correct position. I haven't found a way to reproduce this reliably, but I've seen it a couple of times now.

Edit: [Here's a video illustrating the bug](https://seacloud.cc/d/5d1adbebce/files/?p=/ora_bug9404.mp4). Look at the bottom-left medium tank attacking the E1 on the island.
##

**Comment by HenrytheSlav** [comment] 2015-09-22 11:46
Is it possible that the unit was on water tile? Thus teleported onto closest land tile? It is hard to tell for me.

**Comment by reaperrr** [comment] 2015-09-22 11:48
@RoosterDragon partially refactored pathfinding on bleed (after the feature-freeze for last release), if we're lucky this was fixed as a side-effect.

**Comment by reaperrr** [comment] 2015-09-22 11:49
Sorry, mis-clicked.

**Comment by pchote** [comment] 2015-09-22 12:21
@obrakmann: Could you upload the replay from the game in the video?

**Comment by HenrytheSlav** [comment] 2015-09-22 12:25
Well, it's from Soviets05 mission, do we have replays of SP games?

**Comment by pchote** [comment] 2015-09-22 12:40
We do as of a couple of playtests ago, yeah.

**Comment by HenrytheSlav** [comment] 2015-09-22 12:46
@obrakmann: Has it happened in different map, possibly MP? Because this could be either bug in my map lua or transport unloading problem (unloaded into water somehow). Thanks

**Comment by obrakmann** [comment] 2015-09-22 14:05
[Here's the replay](https://seacloud.cc/d/5d1adbebce/files/?p=/ora_bug9404.orarep). It happens about 60% in.

I'm pretty sure I've seen it on other maps, on land, and without transports involved, too. This was just the one occasion where I remembered where it happened so I could produce the video.

**Comment by HenrytheSlav** [comment] 2015-09-22 14:17
Okay thanks, then it is unfortunately an issue I can help with.

**Comment by MicroJOo** [comment] 2015-10-17 10:38
here the replay 
https://www.dropbox.com/s/aybqg2hh42fe424/movementGlitches.rar?dl=0

here 2 units that glitch (please look at the minimap and timer to get the information how to locate them)

![openra 2015-10-07 17-59-29-72](https://cloud.githubusercontent.com/assets/9139965/10558330/f9194738-74cb-11e5-819b-730334df32ff.png)

![openra 2015-10-17 02-54-46-61](https://cloud.githubusercontent.com/assets/9139965/10558331/fc83800a-74cb-11e5-8a09-84d8ae9798f2.png)

**Comment by pchote** [comment] 2016-10-10 19:25
> [18:26:42]	&lt;kyrylo&gt; hamb, abcdefg30 this is probably a bug :) http://i.imgur.com/y7TUwkt.gifv
[18:33:44]	&lt;AoAGeneral&gt; Tends to happen when they lose focus of the target they are after and they do the warp.
[18:34:29]	&lt;pchote&gt; something is probably cancelling the activity queue in the middle of a move, then issues a new move
[18:34:32]	&lt;pchote&gt; probably autotarget
[18:35:10]	&lt;AoAGeneral&gt; That might be it then. It happens a lot when its doing the 1A move but I tested it doing selective firing. When it moves out of sight (AKA fog) they do the warp stutter and imediately target something new.

**Comment by pchote** [comment] 2018-01-21 14:08
I suspect this is the same thing as #10224.  Both issues were filed within a couple of months of #8084 being merged.

**Comment by Micr0Bit** [comment] 2018-01-21 14:10
>I suspect this is the same thing as #10224. Both issues were filed within a couple of months of #8084 being merged. 
I was thinking the same

**Comment by pchote** [comment] 2019-01-16 18:58
Closing as a reverse-duplicate of #10224, unless someone can prove otherwise.

**Closed by pchote** 2019-01-16 18:58 UTC
Labels: Bug
