### ISSUE TITLE
PickAny for actors. Place random actor.

### ISSUE THREAD

**Issue by SevaJmurov** [OpenRA/OpenRA#14351] opened 2017-11-13 20:57 UTC
Another thought on map editor.
PickAny property for actors which randomly selects actor's image from list of shp frames, as it currently does for ground tiles. That way we could have ability to place random Actor (tree, civilian etc.) on the map. 

This can work only for objects with common traits of course, but still can be useful and any map editors of the original RA era (HoMM, TTD etc.) had this feature.

**Comment by Unit158** [comment] 2017-11-14 03:33
:+1: the decorating committee will thank whoever implements this!

**Comment by pchote** [comment] 2017-11-15 21:09
Closing as duplicate of #10655.

**Closed by pchote** 2017-11-15 21:09 UTC
Labels: Feature, Map Editor
