### ISSUE TITLE
harvesters go for much further away ore over near by gems

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18188] opened 2020-05-25 19:50 UTC
possible bug
release: latest
map: ana* gardens
faction: both, or alies/france

how to reproduce:
1. pick bottom team - either near the left or right side - of the map.
2. deploy, or move even closer to gems
3. place refinery as close as you can to gems
4. not sure if required, point harvester at gems
5. notice that even after a while - once you have a war factory? - there are still - about half of the - gems harvesters at some point move away from the gems to drive up to the much further away, nearest ore patch

happens each time on this map.

**Comment by abcdefg30** [comment] 2020-05-26 09:11
Kind of a duplicate of #17046.

**Comment by deleted-user-1** [comment] 2020-05-27 22:09
Yes, it's the same issue. The map Oregardens and this popular fork are particularly effected by this issue due to the spawn location layout.

**Comment by tovl** [comment] 2020-09-17 15:20
closing as duplicate.

**Closed as completed by tovl** 2020-09-17 15:20 UTC
Labels: Bug
