### ISSUE TITLE
Helicopters can be repulsed off the edge of the map.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9651] opened 2015-10-17 15:43 UTC
Make a bunch of helicopters, then start making a line of them from the edge of the map. Eventually the latest heli the enter the line will push the first one out of the playable area. Continue doing this and you can push several helis off the map and then sneak behind enemy defenses and such with them.

**Comment by pi99y** [comment] 2015-10-17 20:42
You can do a similar thing with planes, but much easier. See #9552

**Comment by penev92** [comment] 2016-02-13 21:31
Closing as duplicate of #9552.

**Closed by penev92** 2016-02-13 21:31 UTC
Labels: Bug
