### ISSUE TITLE
Selected across map in replay

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8541] opened 2015-06-22 13:00 UTC
Add the ability to double click or "w" to select all units by type in replay (with different shroud settings). This will make it easier to count and get an overview in a replay(/as a spectator).
![openra game_2015_06_22_14_55_34_987](https://cloud.githubusercontent.com/assets/7798635/8282231/63c637dc-18ef-11e5-86ea-860f2f0903ba.png)
##

**Comment by obrakmann** [comment] 2015-06-22 15:45
Selection across the map already works, but only in per-player views. Is that enough, or do you have something else in mind?

**Comment by Snurre86** [comment] 2015-06-22 22:55
You are right, but as "Disable Shroud" is the default I thought it was broken as it says in the screenshot "Debug:Selected across map" even if it did not. Should be possible in my opinion.

**Comment by penev92** [comment] 2015-06-23 07:58
I see no gain from being to select all actors of type X for all players.

**Comment by Unit158** [comment] 2015-06-23 11:35
We should disable the debug prompt in that case.

**Comment by Snurre86** [comment] 2015-06-27 20:17
It is not about being able to select all actors of type X for all players but being able to select all by type with different shroud settings.

**Comment by Snurre86** [comment] 2016-01-11 14:12
What I mean to say is that I would like to see this option available and not linked to shroud settings in replay/spectator mode.

**Comment by pchote** [comment] 2018-08-11 12:37
Closing as reverse duplicate of #8541, which has a more descriptive title.

**Closed by pchote** 2018-08-11 12:37 UTC
Labels: UI
