### ISSUE TITLE
Tiberian Dawn Map Editor - Issue when spawn point is at the bottom edge

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14234] opened 2017-10-21 15:31 UTC
Hello,

if you place a spawn point at the last row in the bottom of a map, the MCV of that player stuck in the black "wall", while the other inital units are placed correctly and can be used.

Reproduction:
1. Create a new, empty map
2. Add a spawn point in the bottom at the last row inside the map bounds.
3. Add another spawn point for the enemy somewhere else in the map
4. Start a skirmish game and assign yourself the spawn point at the bottom side
5. Try to play it (or more specific: Try to move your MCV out of the "black wall")

**Comment by AndriiYukhymchak** [comment] 2017-10-21 19:35
The inability to move mcv from bounds is not a bug. However ability to place player start there is. I will look into it

**Comment by pchote** [comment] 2017-10-21 19:37
The map editor is a development tool, and comes with a degree of responsibility: there have been various discussions over the years about adding features to prevent people from shooting themselves in the feet, but restricting actor placement in particular has been rejected as something that can end up doing more harm than good.

**Comment by abcdefg30** [comment] 2017-10-23 22:04
Closing as this is intended behavior.

**Closed by abcdefg30** 2017-10-23 22:04 UTC
