### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by gnumoksha** [OpenRA/OpenRA#17335] opened 2019-11-15 13:24 UTC
### Issue Summary
After some time playing, the game always stops and, after some time, crashes.

#### System Information
- **Operating System:**
```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye
```
- **.NET / Mono Version:**
```console
$ mono --version
Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3+b1 Sat Aug 24 06:28:57 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```
- **OpenRA Version:** release-20190314
- **Mod:** Red Alert

#### Additional Information:
- Download the Red Alert AppImage from https://www.openra.net/download/
- Start the game
- Select Singleplayer
- Select Skirmish
- Play for some time

- Logs  `exception-2019-11-15T130643Z.log`:
```
OpenRA engine version release-20190314
Red Alert mod version release-20190314
on map e4b6a8614527e698744b2909a881c1594228d9cd (Crossfire by Janitor).
Date: 2019-11-15 13:06:43Z
Operating System: Linux (Unix 5.2.0.3)
Runtime Version: Mono 5.18.0.240 (Debian 5.18.0.240+dfsg-3+b1 Sat Aug 24 06:28:57 UTC 2019) CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at System.Collections.Generic.LargeArrayBuilder`1[T].GetBuffer (System.Int32 index) [0x00022] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.LargeArrayBuilder`1[T].CopyTo (System.Collections.Generic.CopyPosition position, T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00041] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].CopyTo (T[] array, System.Int32 arrayIndex, System.Int32 count) [0x00035] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Collections.Generic.SparseArrayBuilder`1[T].ToArray () [0x00028] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].LazyToArray () [0x00048] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable+ConcatNIterator`1[TSource].ToArray () [0x00016] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00021] in <13c0993ff82548209b09f271bd5e6a78>:0 
  at OpenRA.Mods.Common.Activities.ResupplyAircraft.OnFirstRun (OpenRA.Actor self) [0x000de] in /home/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs:45 
  at OpenRA.Activities.Activity.TickOuter (OpenRA.Actor self) [0x00050] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Actor.Tick () [0x00010] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.World.Tick () [0x00046] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00237] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.Loop () [0x000d6] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.Run () [0x00042] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00011] in <f69fafde25414782b71cd55dd1b3d620>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <f69fafde25414782b71cd55dd1b3d620>:0 
```
The other logs are attached.
[Logs.zip](https://github.com/OpenRA/OpenRA/files/3851626/Logs.zip)

**Comment by abcdefg30** [comment] 2019-11-15 13:27
Hi and thanks for the report. This looks like #16235. Does the solution from https://github.com/OpenRA/OpenRA/issues/16235#issuecomment-498896728 help? (Upgrading the mono version.)

**Comment by pchote** [comment] 2019-11-15 13:29
This is a known issue with Debian/Ubuntu, which ships a broken version of Mono. The current playtest (which should become a stable release within the next few days) avoids the issue by shipping its own Mono runtime, but the actual fix is to reinstall mono using the upstream repository: https://www.mono-project.com/download/stable/#download-lin-debian

**Comment by pchote** [comment] 2019-11-15 13:31
Closing as duplicate of #16235.

**Closed by pchote** 2019-11-15 13:31 UTC
Labels: Crash, OS: Linux

**Comment by gnumoksha** [comment] 2019-11-15 21:00
The playtest version works well.
