### ISSUE TITLE
OpenRA Red Alert mode slowing down, than Fatal Error

### ISSUE THREAD

**Issue by prutskip** [OpenRA/OpenRA#11516] opened 2016-06-24 15:05 UTC
At first let me mention I really find your team work really awesome to get these old games running again. Spent a lot of hours when I was young and now again on these great games!!!

I was playing RA skirmish against four enemies (all four classes) and winning big time by being tactical ofcourse ;) Suddenly the game slowed down and that went on for about 20 minutes after the game crashed with a Fatal Error (bummer, all my nice work for nothing).

Could this be a OpenRA bug or just a system issue (running Windows 10 with 8GB and AMD Radeon 6950)?

Exception log:
> Red Alert Mod at Version release-20160508
on map 3af3d6e6a39a4e020fb601ef8cac7742a929f553 (Blitzkrieg by s1w).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.OverflowException`: Negating the minimum value of a twos complement number is invalid.
   at System.Math.AbsHelper(Int32 value)
   at OpenRA.WAngle.ArcTan(Int32 y, Int32 x, Int32 stride)
   at OpenRA.WVec.get_Yaw()
   at OpenRA.Mods.Common.Traits.Turreted.FaceTarget(Actor self, Target target)
   at OpenRA.Mods.Common.Traits.AttackTurreted.CanAttack(Actor self, Target target)
   at OpenRA.Mods.Common.Traits.AttackBase.DoAttack(Actor self, Target target, IEnumerable`1 armaments)
   at OpenRA.Mods.Common.Traits.AttackFollow.Tick(Actor self)
   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

Second issue, but less important: sometimes loosing my cursor. After moving it few times around, it shows up again.

Debug log:
Failed to initialize hardware cursors. Falling back to software cursors.
Error was: Failed to create hardware cursor `guard-minimap` - Failed to create cursor: CreateIconIndirect(): The parameter is incorrect.

**Comment by abcdefg30** [comment] 2016-06-24 15:06
For your second issue see #10172.

**Comment by reaperrr** [comment] 2016-06-24 15:09
For your first issue, definitely looks like an OpenRA bug.

**Comment by reaperrr** [comment] 2016-06-25 23:36
We should at least investigate this for next release.

**Comment by obrakmann** [comment] 2016-07-05 10:42
@prutskip: do you happen to still have the replay from that crash? It would help with debugging this. Thanks!

**Comment by prutskip** [comment] 2016-07-05 18:29
Hi Obrakmann, here's the replay: [https://we.tl/WvszG0opz6](url)

Don't mind the skills, I was having a bad day ;)

Ps.: password is openra

**Comment by RoosterDragon** [comment] 2016-07-30 15:46
@prutskip: I don't suppose you can upload the replay again? It is no longer available at that link.

**Comment by pchote** [comment] 2016-08-24 15:30
We can't do much without the replay, so closing.  Please file a new ticket if you can reproduce this and provide a replay.

**Closed by pchote** 2016-08-24 15:30 UTC
Labels: Crash
