### ISSUE TITLE
Don't allow teamchat if not assigned to a team.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#9281] opened 2015-09-06 00:00 UTC
Currently you can tab to teamchat if your are not assigned to a team in lobby chat.
These messages are not sent to anyone who _is_ teamed.
##

**Comment by Mailaender** [comment] 2017-09-02 15:47
Duplicate of https://github.com/OpenRA/OpenRA/issues/4033 which is already resolved.

**Closed by Mailaender** 2017-09-02 15:47 UTC
Labels: Polish, UI
