### ISSUE TITLE
Ability to use Shift key on harvesters

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#13267] opened 2017-05-09 21:44 UTC
I notice during a game that I couldn't use Shift key on my harvester (will go directly to the last given location)

Especially during early game, micro-managing a harvester is a good practice, to maximise early cash flow. However, this requires some micro, while it could be needed elsewhere (fighting for derricks, early attacks, ...)

So one possible idea : being able to use the Shift key on harvesters, to draw a path of 1-cell steps. 
That could be a "quick fix" (I've no idea if this is difficult to implement) to improve harvesters behaviour.

**Comment by abcdefg30** [comment] 2017-05-09 22:06
Looks like a duplicate of #11264. Thanks for the report though! :)

**Closed by abcdefg30** 2017-05-09 22:06 UTC
Labels: Bug

**Comment by leodew** [comment] 2017-05-09 22:34
My bad ! Looked for sth similar but couldn't find :) 
Thanks !
