### ISSUE TITLE
Time to fix the annoying "training...tra...tra..tra...training" notification voice?

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12722] opened 2017-02-08 05:01 UTC
In red alert 2 sounds have a priority check and or a pause between sounds.for example you will not hear the same notification twice for some time,or an annoying training...tra...tra..tra...training voice...so isn't it the time to fix that for the sake of our ears and mental health?

**Comment by GraionDilach** [comment] 2017-02-08 06:05
Sure, when do you file the PR containing the fix?

**Comment by KOYK** [comment] 2017-02-08 06:53
Good one,but am not a programmer.and am not going to be one for at least a.. hmm wait! never!
i am just a mediocre modder. you are the unpaid asset you do the job.

**Comment by abcdefg30** [comment] 2017-02-08 09:32
Duplicate of #4690.

**Closed by abcdefg30** 2017-02-08 09:32 UTC
