### ISSUE TITLE
Damage fire overlays are missing from the mods.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16871] opened 2019-08-03 06:42 UTC
In the legacy games (notsure about D2k), buildings started to emit fire overlays when damaged stage or beyond. Before RA2, these also damaged the building at hand, but considering how ORA mods function gameplaywise, this aspect probably should not return in TD/RA.

Would mean a lot of visual polish for TS, because the artwork has specific spots for the fires to spawn. The end result probably can be simplified with sequence inheritances, since the engine requirements are basically `WithIdleOverlay`s enabled by `GrantConditionOnDamageState`s along with a negative `SelfHealing` if necessary, and individual buildings only need to define offsets for shared templates set up around the amount of damage fires.

**Comment by Mailaender** [comment] 2019-08-04 11:49
Duplicate of https://github.com/OpenRA/OpenRA/issues/9409.

**Closed by Mailaender** 2019-08-04 11:49 UTC
Labels: Polish
