### ISSUE TITLE
 Grant Condition on Passenger when Actor is loaded?

### ISSUE THREAD

**Issue by Omnomon** [OpenRA/OpenRA#14215] opened 2017-10-19 08:04 UTC
Could you guys implement some logic that will grant a condition to Passenger when it is loaded into an Actor? I realize this is kind of redundant with how Armaments already works, but this may be a useful trait in the future...  The reason I'm asking for this change in particular is because it seems like there is no way to activate conditional multipliers (firepower, experience, etc) onto the actor when it is loaded in an APC or Pillbox. 

I tried to implement this myself by using other .cs files as examples, but I am extremely new to C# coding and coding in general...my build compiles, but I have no idea what I am doing. If anyone's interested in helping me fix it, it's in a test branch on my github fork .

**Comment by AndriiYukhymchak** [comment] 2017-10-19 08:16
don't see how actor has any influence on the world when it is removed from world by being inside different object...

**Comment by Omnomon** [comment] 2017-10-19 08:34
This is probably not the right fix, the but I was trying to put GainsExperienceMultiplier on the actor inside the pillbox to stop the E1 from leveling up so quickly...according to pchote, Nolt, and MustaphaTR, there is no way to achieve this effect unless you put the weapons on the Pillbox itself.

**Comment by GraionDilach** [comment] 2017-10-19 15:39
Yes, this would be really useful to have and even required for YR OpenTopped logic, which applied a range modifier to actors firing out from OpenTopped units (Battle Fortress). Sure, that can be done via duplicating all weapons, but that's ungh.

**Comment by FrameLimiter** [comment] 2017-10-19 19:00
Duplicate of #14086 & #13113

**Comment by pchote** [comment] 2018-05-10 12:09
Fixed by #15066.

**Closed by pchote** 2018-05-10 12:09 UTC
Labels: Feature
