### ISSUE TITLE
INotifyBuildComplete not used correctly.

### ISSUE THREAD

**Issue by IceReaper** [OpenRA/OpenRA#13472] opened 2017-06-07 14:33 UTC
There are currently a lot of traits, which should only get active after INotifyBuildComplete is triggered.
While this does not make a huge impact on the core games (due to extremely fast deploy or make animations), but this is a huge gameplay breaker for mods which have longer make animations or custom make code (in my case it can take a minute).

- Production should only be possible if the building is fully build up
- ProvidesPrerequisite should only provide if the building is fully build up
- Free actor should spawn the actor after the building is fully build up
- Traits which grant special abilities like the radar, spyplane, etc.
- Buildings granting the player money each X ticks, should only be active after the building is fully build up.

Feel free to add missing ones here. Basically a building in construction state / not have called implementing methods, should be fully dis-functional and should under no circumstances provide any features to the player. Sadly i do not have a list of all traits yet which should be affected, but the above mirror the ones i need for my project to behave correctly.

**Comment by GraionDilach** [comment] 2017-06-07 14:51
Keep in mind that a lot of these traits are conditional with the intention that WithMakeAnimation providing the disabled condition. Providing a prerequisite during buildup is for example a standard C&C feature.

**Comment by MustaphaTR** [comment] 2017-06-07 14:53
> ProvidesPrerequisite should only provide if the building is fully build up

Related to #12665.

There is a problem with that that @GraionDilach pointed out at there tho.
> I don't like that implication though - if both undeployed and deployed states provide the same prereq, but not the deployanimation, the players would complain about legit bugs when their build orders become noisy. Examples where such a setup was used was YR Slave Miner and RA3 Empire of the Rising Sun.

I think, if not all, some of those tags should provide .yaml values to either allow or disallow during build anim.

Or maybe a Condition given by WithMakeAnimation:. So we can disable ones we don't want. Edit: @GraionDilach was quicker.

**Comment by pchote** [comment] 2017-06-07 15:32
`INotifyBuildComplete` has been superseded by conditions, and will be removed as soon as someone finds time to adapt the default mod rules to use them.  Closing as WONTFIX / duplicate of #7035.

**Closed by pchote** 2017-06-07 15:32 UTC
