### ISSUE TITLE
ranking system

### ISSUE THREAD

**Issue by runeavalon** [OpenRA/OpenRA#12303] opened 2016-10-25 01:58 UTC
I really think (and i asked a lot in the lobby, lots of ppl agree) that you guys should imply a ranking system to insure that the matches are allways balanced. Like in league of legends. A sort of system where ppl get a higher or lower rank based on their results of winning and losing. And then make sure that all the ppl with the same rank are put together against eachother ina fight. It is a thing that happens so often that the matches ate so unbalanced, making ppl leave the match early. or ragequit. I wonder what you guys think of this idea. Plzz let me know

cheers, Leander Letworry (game name Ohmk Torque)

**Comment by StexoO** [comment] 2016-10-25 05:36
Related to https://github.com/OpenRA/OpenRA/issues/2815 ?

**Comment by runeavalon** [comment] 2016-10-25 15:39
yeah, i didnt see that threat, but i would also imply things as micromanaging ability, units killed and lost . every stat that the game allready shows at at the end of the match. and i think its worth it to take a look at how league of legends took its aproach on that. that all i have to add then.
good greetings, Ohmk Torque

**Comment by Micr0Bit** [comment] 2016-10-25 19:17
@pchote is already working on "authentication" ... wins and losses will get tracked on everyones dropdown-profile ... that should help balance games better 
#2265

and yes , this is a duplicate of #2815
please close

**Comment by cjshmyr** [comment] 2016-10-25 20:49
Closed as duplicate, feel free to leave remarks on the other ticket

**Closed by cjshmyr** 2016-10-25 20:49 UTC
