### ISSUE TITLE
Allow StartingUnits to contain Buildings too

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18843] opened 2020-11-20 11:07 UTC
Currently if you add any Structure to SupportActors: of an MPStartUnits: it throws an error about IPositionableInfo the moment it tries to place down those right at game begin.

**Comment by MustaphaTR** [comment] 2020-11-22 07:44
Duplicate of https://github.com/OpenRA/OpenRA/issues/13264

**Closed as completed by MustaphaTR** 2020-11-22 07:44 UTC
Labels: Idea/Wishlist
