### ISSUE TITLE
"Primary" building is Ignored/Reset when a new one is built

### ISSUE THREAD

**Issue by StevenL-Up** [OpenRA/OpenRA#19450] opened 2021-06-14 22:21 UTC
## Issue Summary

DESCRIPTION

If you select a War Factory as "Primary", and then build another one, the units start coming out of the new one, regardless/over-riding your prior selection.

Version `release-20210321`
Red Alert (original)

EXPECTED BEHAVIOR

The building you selected as Primary should remain as such, and units should only come out of that one.

**Comment by abcdefg30** [comment] 2021-06-15 08:02
I just tested this on bleed and it seems to work there. The issue might have been fixed in the meantime. Do you have a replay showcasing the issue so that we can confirm that?

**Comment by StevenL-Up** [comment] 2021-06-15 16:49
This is with "Instant Build" turned on in Debug to make the video shorter.

https://user-images.githubusercontent.com/66263703/122092633-25753380-cdd8-11eb-888c-32f6ceae2d15.mp4

**Comment by abcdefg30** [comment] 2021-06-16 21:08
I see, thanks for the video. The unit comes out of the other factory because the primary one is blocked (temporarily). So code-wise this is working as it should. The question is now if we want to change the code to wait if the blocking actor of the primary building is moving out of the way or keep it as-is.

**Comment by abmyii** [comment] 2021-06-21 11:03
Duplicate of #17404. I agree that this issue is really frustrating and needs to be addressed.

**Comment by abcdefg30** [comment] 2021-06-21 12:35
Closing as duplicate then. We can continue the discussion in #17404.

**Closed as completed by abcdefg30** 2021-06-21 12:35 UTC
Labels: Bug, UI

**Comment by abmyii** [comment] 2021-06-21 15:47
@steven-levine-uplight Could you please forward your video to the main issue so that those subscribed can see an example of the issue.
