### ISSUE TITLE
Print name of server ingame

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#17833] opened 2020-03-22 18:57 UTC
The server just did not respond anymore.
I am not sure if it was hosted game, or server, or what kind of server.
Sometimes someone kills the server if they are about to die.
Name of server should be printed somewhere:

- In chat in the start of the game (easy fix)
- Under the server did not respond
- The escape screen like #12349 (but with pingcolor, and mouseover for country)
- or somewhere else

It would be nice if the ping to that server is shown, so you can see if you have yellow or red, or if all players have red to it then its the server not the client...

**Comment by Smittytron** [comment] 2021-05-07 00:30
Closing as duplicate of #12349. I'll copy the comment there.

**Closed as completed by Smittytron** 2021-05-07 00:30 UTC
Labels: Idea/Wishlist, Networking, UI
