### ISSUE TITLE
Disable Linter map importer actor checks if mod is unknown

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14904] opened 2018-03-11 01:08 UTC
For example, currently if your custom mod uses the D2k.dll but doesn't implement any D2k actors, you get like 50 lint errors per map. This is horrible.

IMO we should only run the mod-specific actor import checks if the mod name matches the corresponding official mod.

**Comment by pchote** [comment] 2018-12-06 05:45
The simple fix here is to make `CheckImportActors` check the mod id and bail if it isn't d2k.  This may require passing extra metadata to `ILintRulesPass` etc.

**Comment by Mailaender** [comment] 2022-09-07 10:27
Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/19527.

**Closed by Mailaender** 2022-09-07 10:27 UTC
Labels: Utility, Usability
