### ISSUE TITLE
Yaks/Migs do a 360° spin when commanded to land at an airfield

### ISSUE THREAD

**Issue by vietman391** [OpenRA/OpenRA#9502] opened 2015-10-01 18:45 UTC
I deal with this several times in my games, but this is very much a minor issue since I can always command them to go near an airfield first, then ask them to land. Otherwise, they may be near AA guns or SAM sites and the 360° turn causes them to come too close.

**Comment by pchote** [comment] 2015-11-22 14:00
Reverse-duplicate of #10029

**Closed by pchote** 2015-11-22 14:00 UTC
Labels: Bug
