### ISSUE TITLE
Exception of type System.IO.InvalidDataException: chrotnk1.aud is not a valid sound file!

### ISSUE THREAD

**Issue by ibrokemypie** [OpenRA/OpenRA#12772] opened 2017-02-13 12:45 UTC
````
Red Alert Mod at Version release-20161019
on map 7631f49bad03324648dd66e854bd755d10eb3373 (East vs West by Chris Forbes).
Date: 2017-02-13 12:34:12Z
Operating System: OSX (Unix 16.4.0.0)
Runtime Version: Mono 4.6.2 (mono-4.6.0-branch/ac9e222) CLR 4.0.30319.42000
Exception of type System.IO.InvalidDataException: chrotnk1.aud is not a valid sound file!
  at OpenRA.Sound.LoadSound (OpenRA.ISoundLoader[] loaders, OpenRA.FileSystem.IReadOnlyFileSystem fileSystem, System.String filename) [0x000cc] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Sound+<Initialize>c__AnonStorey0.<>m__0 (System.String s) [0x00000] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Exts.GetOrAdd[K,V] (System.Collections.Generic.Dictionary`2[TKey,TValue] d, K k, System.Func`2[T,TResult] createFn) [0x0000f] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Primitives.Cache`2[T,U].get_Item (T key) [0x00001] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Sound.Play (OpenRA.Player player, System.String name, System.Boolean headRelative, OpenRA.WPos pos, System.Single volumeModifier, System.Boolean loop) [0x00031] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Sound.Play (System.String name, OpenRA.WPos pos) [0x00001] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Mods.RA.Activities.Teleport.Tick (OpenRA.Actor self) [0x000c7] in <c1b43287c4ef4e54a2fe2009fb9769eb>:0 
  at OpenRA.Traits.ActivityUtils.RunActivity (OpenRA.Actor self, OpenRA.Activities.Activity act) [0x00022] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Actor.Tick () [0x00008] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.World.Tick () [0x000c1] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x0022b] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Game.LogicTick () [0x00050] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Game.Loop () [0x000d6] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Game.Run () [0x00042] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00011] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Program.Main (System.String[] args) [0x0004f] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0
````

**Comment by pchote** [comment] 2017-02-13 13:22
Duplicate of #12420.  I assume that you installed from the CNCNZ (broken) aftermath iso?

To fix the issue go into the support directory, delete the RA content, then reinstall it from another source.

**Closed by pchote** 2017-02-13 13:22 UTC
Labels: Crash
