### ISSUE TITLE
"Unit Lost" Sound Loud at End of Game when Master Volume Set to Low

### ISSUE THREAD

**Issue by TheGrinningSkull** [OpenRA/OpenRA#13775] opened 2017-08-05 14:35 UTC
At the end of a game when surrendering, the "Unit Lost" speech is substantially higher than the "Unit Lost" sound during regular game play when the Audio Settings are set to the lower end of the scale.

**Comment by GraionDilach** [comment] 2017-08-05 15:07
The game plays a report for each unit destroyed during surrender and the reports just add up together.

**Comment by abcdefg30** [comment] 2017-08-05 16:34
Duplicate of #3844.

**Closed by abcdefg30** 2017-08-05 16:34 UTC
