### ISSUE TITLE
multi player, pre assign slots to team and spawns

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#16844] opened 2019-07-26 19:29 UTC
next to/as part of the bot selection menu allow the admin of a multi player game in the game lobby to select 2v2, 3v3, 4v4 as a pull down menu option.

once selected the lobby prefills the game slots with player pawns that are far away from each other and sets the teams accordingly. allow the admin to manually override as normal.

after when players join the game they enter the default next slot and get assigned the correct team and spawn already.  the player can change the slot like he can, but it makes more sense for him to switch slots if he wan't to play for a different team or at a different pawn.

why?
many game start with people in wrong team or spawn.
a lot of time is wasted in the lobby on selecting pawns and figuring out which team you are on. 
no longer endless waiting for people to pick spots. only for them to select ready.
no longer shouting at people who pick the wrong team a few times.
99% of the time we play north/south or east west, the obvious. 

how?
currently slots in the lobby do not have a team assigned to them, only a future player that has a team assigned. so the slots should have a initial team.
same like spawn?

**Comment by pchote** [comment] 2019-07-26 19:32
These features have been available for a long time, through the "Slot Admin" menu

**Comment by anvilvapre** [comment] 2019-07-26 19:36
yes, for bots, but us real player often find it even more difficult to find ourselves a spot.

**Comment by GraionDilach** [comment] 2019-07-27 07:14
Selecting the preset team options does not preset spawns, only the team assignments. From what I read, OP want to have both preset.

**Comment by anvilvapre** [comment] 2019-07-27 16:46
i did not know it already worked for real players, thought the option only worked for bots. 
but yet:
1. would be great if slots would also be assigned
2. more importantly, let the admin be able to do this before/while the other joins

because the confusion about who needs to join what team at what spot starts once the xth person joins in.

**Comment by abcdefg30** [comment] 2019-09-17 14:31
I think we can close this as duplicate of #2992 then.

**Closed by abcdefg30** 2019-09-17 14:31 UTC
Labels: Idea/Wishlist
