### ISSUE TITLE
show stats after game without first return to map

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#9653] opened 2015-10-17 19:18 UTC
![stats](https://cloud.githubusercontent.com/assets/526956/10560742/85644cb8-7514-11e5-9545-26ee54f0c22c.png)

now you have to:
1: press return to map
2: find the stats in the top right corner..

This takes time.and could be easier done...

**Comment by pi99y** [comment] 2015-10-17 20:40
Also reported here #9198

**Comment by abcdefg30** [comment] 2015-10-17 20:55
Closing as duplicate of  #9198 then.

**Closed by abcdefg30** 2015-10-17 20:55 UTC
Labels: Polish, UI
