### ISSUE TITLE
OpenRA Red Alert Mac OS X "Out of Memory" exception causing crash when idle

### ISSUE THREAD

**Issue by reedand** [OpenRA/OpenRA#14710] opened 2018-01-11 11:30 UTC
I've found an issue with the current (OpenRA engine version release-20171014 / Red Alert mod version release-20171014) and previous version (Tiberian Dawn Mod at Version release-20161019). 

If I play a single player skirmish against AI, finish the game, leave the app running and leave my laptop, when I return I sometimes find the app has crashed.

MacBook Pro (Retina, 13-inch, Mid 2014) / MacOS Sierra 10.12.6
Processor: 2.8 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel Iris 1536 MB

[exception-2017-10-25T223709Z.log](https://github.com/OpenRA/OpenRA/files/1619988/exception-2017-10-25T223709Z.log)
[exception-2018-01-08T114459Z.log](https://github.com/OpenRA/OpenRA/files/1619989/exception-2018-01-08T114459Z.log)
[exception-2018-01-09T133134Z.log](https://github.com/OpenRA/OpenRA/files/1619990/exception-2018-01-09T133134Z.log)

**Comment by pchote** [comment] 2018-01-11 11:54
Closing as duplicate of #12494.  These crashes on macOS specifically have been fixed in the playtest version.

**Closed by pchote** 2018-01-11 11:54 UTC
Labels: Crash, OS: MacOS X
