### ISSUE TITLE
Demo truck kills

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9729] opened 2015-10-23 13:51 UTC
When you detonate a demo truck using F it counts as a kill and a death
![demo](https://cloud.githubusercontent.com/assets/3636652/10693768/3cc798ac-7992-11e5-8b67-997c8304f577.png)

When an enemy kills a demo truck any enemies killed in the blast are counted towards the enemies kill count
![demo2](https://cloud.githubusercontent.com/assets/3636652/10694461/30580710-7996-11e5-928d-56d1c53bce7c.png)

When a demo targets an actor and explodes as normally the owner is properly credited the kills.

On release and bleed.

**Comment by pchote** [comment] 2015-10-23 14:05
Basically a duplicate of #9044.

**Closed** 2015-10-23 14:12 UTC
