### ISSUE TITLE
Yaks get stuck

### ISSUE THREAD

**Issue by senneschall** [OpenRA/OpenRA#14102] opened 2017-10-02 13:24 UTC
In the latest playtest 20170930 I noticed some strange behavior of the Yaks:
I play as Ukraine, build only one air field and queue up some Yaks. Once two Yaks are built, I deplete their ammo so they try to go back to the air field. But none of the two Yaks actually land on the air field, but they keep staying mid air. When the next Yak in the queue is ready, it does not appear on the empty air field, but it only says "ready" and can't be cancelled any more.

So it seems the air field is blocked by one of the two flying Yaks which can't land for some reasons (this seems to be the initial bug to me).
A new Yak does not appear despite the air field being empty and the queue can't be emptied any more (is this also a bug?)

I saw this twice on the new playtest.

**Comment by senneschall** [comment] 2017-10-04 19:39
This bug also happens with the latest release, so this is not specific to the playtest.

I didn't quite figure out when this happens exactly. It seems to happen sometimes when the queued up new yak would be ready while the depleted yaks are already flying back to the airfield.
But it doesn't happen every time, that's very odd.

**Comment by senneschall** [comment] 2017-10-04 19:55
The replay attached to #14114 shows the bug: at ~6:20 the yaks try to get back to the airfield. The new yak would be ready at ~6:30. At ~6:40 the depleted yaks are flying around the air field, not landing and the new yak is not spawning.

The bug is resolved at ~7:10 when I manually clicked the yaks to fly somewhere else.

**Comment by Kanar** [comment] 2017-12-29 23:17
I think it should be made clear EXACTLY what yak behaviour is desired before looking into it.

I remember rewriting the whole aircraft logic a long time ago;
you can actually make aircraft act so independently, that I was actually asking myself if that was not too much AI and not enough player-handled microing anymore.

Should aircraft depleted of ammo return to the airfield automatically?
Should they land and rearm automatically after that?
Should they take off after rearming automatically?
Where is Holloweye? Is he still around?
Should aircraft queue up and rearm automatically one after the other?
If their previous target was not destroyed completely: Should they make a second attempt to attack it automatically or just move to their rally point?
How much microing should be involved?
How much microing should the player have to do before he considers building a second airfield?

So many decisions to make.

I also found it quite weird that they return to the conyard when their only airfield is destroyed... maybe there is a better solution. Sometimes they will fly somewhere across the map in this case where you least expect em to be and you spot them circling in a lonely corner...

**Comment by matjaeck** [comment] 2019-06-09 06:50
I can't reproduce this on bleed or on #16509 and suspect that this was fixed by #16584.

**Closed** 2019-06-09 08:13 UTC
Labels: Bug
