### ISSUE TITLE
AA units loose theyr target if aircraft is outside of the map

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#12238] opened 2016-10-15 22:18 UTC
That means planes can't be aimed if you fly outside in my case i tryed to aim migs with my Longbows but i think this affects other aa units too. You can fly with planes outside of the map without being hit if you got some skills with them.
This is with helicopters only possible at the north i think.
See this replay at min 14 at the left side if you don't understand what i mean.
http://www.gamereplays.org/openra/replays.php?game=92&show=details&id=314762

**Comment by airetaM** [comment] 2016-10-15 22:27
The game was totally lagfree and balance seems to be fine thanks for the great work btw :dancing_women:

**Comment by anjew175** [comment] 2016-10-15 22:30
This is a duplicate of #9552 
pchote said that the root cause of this issue (aircraft leaving the map) could be fixed by implementing aircraft repulsion.

**Comment by abcdefg30** [comment] 2016-10-16 15:11
Yep, looks indeed like a duplicate of #9552. Thanks for the report though. :)

**Closed by abcdefg30** 2016-10-16 15:11 UTC
