### ISSUE TITLE
Tiberium Dawn (Feature): add bookmark for options

### ISSUE THREAD

**Issue by binyata** [OpenRA/OpenRA#12819] opened 2017-02-20 20:00 UTC
Maybe this feature has already been added to the game, but I was thinking it would be really convenient for the user to be able to save their settings on a multiplayer game or skirmish so that they don't have to reset the settings they prefer every time they decide to play a multiplayer game.

For example, going to the options on a multiplayer game, there would be a drop down menu called Saved settings, then you would see the last one you saved, which will be named by the user.

**Comment by ROCKNROLLKID** [comment] 2017-02-20 20:15
Maybe they could just cache the settings so it remembers the last settings you used. Would kind of be the same thing.

**Comment by Mailaender** [comment] 2017-02-21 19:50
Duplicate of https://github.com/OpenRA/OpenRA/issues/4122 if I understood it correctly.

**Closed by Mailaender** 2017-02-21 19:50 UTC
