### ISSUE TITLE
Buildings "blink" when you reveal them

### ISSUE THREAD

**Issue by AndriiYukhymchak** [OpenRA/OpenRA#14645] opened 2018-01-03 14:37 UTC
When you move into known/unknown part of the map, every building there will blink when you reveal it. Most likely something to do with renderer as building disappears for an instant then reappears

**Comment by pchote** [comment] 2018-01-03 14:38
Duplicate of #14614 which should have been fixed by #14619?

**Comment by AndriiYukhymchak** [comment] 2018-01-03 14:39
snap, forgot to check closed ones too. Thanks

**Comment by pchote** [comment] 2018-01-03 15:15
Can you please confirm that this is fixed for you on the latest bleed / playtest?

**Comment by FrameLimiter** [comment] 2018-01-03 15:28
Just checked the bleed, it's still an issue. :(

**Comment by pchote** [comment] 2018-01-03 15:29
This is probably the opposite case to #14614 then.

**Closed** 2018-01-06 14:17 UTC
Labels: Regression
