### ISSUE TITLE
Pausing AttackFrontal doesn't seem to work

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#16398] opened 2019-04-11 14:38 UTC
In RV being emped/removed via Chrono Legionnarie pauses the Attack* traits of the units but it seems like it is not working for AttackFrontal. AttackTurreted units properly stop firing in that case, but not the frontal ones.

**Comment by pchote** [comment] 2019-04-11 14:48
Duplicate of #13355, which will be fixed by #15651.

**Closed by pchote** 2019-04-11 14:48 UTC
