### ISSUE TITLE
Power down sprite does not show if you zoom out too far in spec view

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19357] opened 2021-04-18 22:47 UTC
## Reproduction

Have your zoom level set to far and zoom out far enough from a powered down building in spec view

## Expected behavior

Should not disappear 

## Screenshots / Screen recordings / Replays

![20210417162753_1](https://user-images.githubusercontent.com/64435704/115163316-5269cc00-a05d-11eb-8d3c-b0bb49c3fd42.jpg)
![20210417162751_1](https://user-images.githubusercontent.com/64435704/115163317-54cc2600-a05d-11eb-993b-1c8bc34d2013.jpg)

**Comment by MlemandPurrs** [comment] 2021-04-23 08:06
AmmoPips, various WithDecorationOverlay etc. too are become invisible on too far out zoom.

**Comment by ghost** [comment] 2021-07-07 00:26
[This has already been reported and is a duplicate issue.](https://github.com/OpenRA/OpenRA/issues/19232)

**Comment by Smittytron** [comment] 2021-07-07 00:39
Yep, closing as duplicate of #19232

**Closed as completed by Smittytron** 2021-07-07 00:39 UTC
Labels: Bug
