### ISSUE TITLE
Pathfinding Improvements

### ISSUE THREAD

**Issue by MunWolf** [OpenRA/OpenRA#14830] opened 2018-02-18 12:13 UTC
These points came up on the IRC channel to improve our pathfinding computation time, I did not find a duplicate issue describing these points but please close this issue if you can find it.

1) Restrict units to N mod-defined movement types (defined on their own trait on the world)
2) Precalculate path costs between waypoints on the domain layer for each of the movement types
3) Make units navigate via those waypoint regions so that they never need to search more than ~20 cells

The world trait that defines movement types would define the name of the type, passable terrain and costs on those terrain types (example, tiberium passable by infantry but not preferred).

**Comment by abmyii** [comment] 2019-12-27 23:06
Another:
Faster units will get stuck behind slower units rather than going around.

**Comment by abcdefg30** [comment] 2020-08-29 20:36
Some points have been implemented. Closing as duplicate of #9315 for the rest.

**Closed by abcdefg30** 2020-08-29 20:36 UTC
Labels: Pathfinding, Performance
