### ISSUE TITLE
Exception of type `System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by fastslack** [OpenRA/OpenRA#7927] opened 2015-04-12 00:34 UTC
```
$ openra 
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Detected OpenGL version: 4.5
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn (playtest-20150408)
	d2k: Dune 2000 (playtest-20150408)
	modchooser: Mod Chooser (playtest-20150408)
	ra: Red Alert (playtest-20150408)
Loading mod: ra
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.String,OpenRA.Mods.Common.Widgets.Logic.LobbyCountry].get_Item (System.String key) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.SetupEditableFactionWidget (OpenRA.Widgets.Widget parent, OpenRA.Network.Slot s, OpenRA.Network.Client c, OpenRA.Network.OrderManager orderManager, System.Collections.Generic.Dictionary`2 countries) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void__this__ ()
  at (wrapper delegate-invoke) <Module>:invoke_void__this__ ()
  at OpenRA.Game.SyncLobbyInfo () [0x00000] in <filename unknown>:0 
  at OpenRA.Network.UnitOrders.ProcessOrder (OpenRA.Network.OrderManager orderManager, OpenRA.World world, Int32 clientId, OpenRA.Order order) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

I receive this error when i try to open a new skirmish game

**Comment by penev92** [comment] 2015-04-12 01:00
Can you provide some more information as to what custom maps you have installed?

**Comment by penev92** [comment] 2015-04-12 03:01
My moderately-wild guess would be that some custom map is forcing either Allies or Soviets as some player's race. And since they are no longer playable, the lobby can't get the info it needs to display for them and crashes.

**Comment by Mailaender** [comment] 2015-04-12 05:58
Can you look for your https://github.com/OpenRA/OpenRA/wiki/Settings file and post the hash of the map written their as last player choice.

**Comment by fastslack** [comment] 2015-04-12 16:30
I cant see the map because the crash is before that i can choose the map. But yes, i think the latest map that i used is a custom map.

```
$ cat ~/.openra/settings.yaml
Player:
	Name: FasTSlacK
	Color: 187,255,25

Game:
	Mod: ra
	ViewportEdgeScroll: False
	ViewportEdgeScrollStep: 16.08696
	TeamHealthColors: True
	NewsFetchedDate: 2015-04-11 03-00-00

Sound:
	MusicVolume: 0

Graphics:
	Mode: Fullscreen
	MaxFramerate: 100

Server:
	Name: Argentina
	AdvertiseOnline: False
	AllowPortForward: False
	Map: 2caee56595c29bba263ba7de1b9fee8c688bf56e

Debug:
	PerfText: True
	PerfGraph: True

Keys:
```

**Comment by Mailaender** [comment] 2015-04-12 16:52
Can you upload it? It does not exist at http://resource.openra.net/map/2caee56595c29bba263ba7de1b9fee8c688bf56e

**Comment by Mailaender** [comment] 2015-04-12 16:54
http://resource.openra.net/map/url/2caee56595c29bba263ba7de1b9fee8c688bf56e

**Comment by pchote** [comment] 2015-04-12 16:57
It will probably be a custom map that was created for the release, and has been automatically upgraded by the game.  This changes the UID compared to what it would be on the resource site.

**Comment by fastslack** [comment] 2015-04-12 17:18
anyone know any way to find a oramap file using the hash? I tryed with ```grep 2caee56595c29bba263ba7de1b9fee8c688bf56e * -d rec``` but didnt work

**Comment by pchote** [comment] 2015-04-12 17:27
`mono OpenRA.Utility.exe ra --map-hash <path to map>` will print the hash for the given map.  You could put that in a loop over all the files in a dir and print the file/hash.

**Comment by fastslack** [comment] 2015-04-12 18:07
```
$ mono OpenRA.Utility.exe ra --map-hash /home/user/.openra/maps/
Error: Utility application crashed. See utility.log for details

Unhandled Exception:
System.InvalidOperationException: Required file map.yaml not present in this map
  at OpenRA.Map.AssertExists (System.String filename) [0x00000] in <filename unknown>:0 
  at OpenRA.Map..ctor (System.String path) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.GetMapHashCommand.Run (OpenRA.ModData modData, System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Required file map.yaml not present in this map
  at OpenRA.Map.AssertExists (System.String filename) [0x00000] in <filename unknown>:0 
  at OpenRA.Map..ctor (System.String path) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.GetMapHashCommand.Run (OpenRA.ModData modData, System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Anyway, i solved the problem removing the hash from settings.yaml. Thanks guys

**Comment by fastslack** [comment] 2015-04-12 18:17
Again, but this time we know the map that cause the issue.

```
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Detected OpenGL version: 4.5
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn (playtest-20150408)
	d2k: Dune 2000 (playtest-20150408)
	modchooser: Mod Chooser (playtest-20150408)
	ra: Red Alert (playtest-20150408)
Loading mod: ra
Game started
Exception of type `System.InvalidOperationException`: /home/user/.openra/maps/ra/time-trouble.oramap:17748: Sequence scrate.water uses frames [2..5] of SHP `wwcrate.shp`, but only 0..3 actually exist
  at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence..ctor (OpenRA.ModData modData, OpenRA.TileSet tileSet, OpenRA.Graphics.SpriteCache cache, ISpriteSequenceLoader loader, System.String sequence, System.String animation, OpenRA.MiniYaml info) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Graphics.TilesetSpecificSpriteSequence..ctor (OpenRA.ModData modData, OpenRA.TileSet tileSet, OpenRA.Graphics.SpriteCache cache, ISpriteSequenceLoader loader, System.String sequence, System.String animation, OpenRA.MiniYaml info) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Graphics.TilesetSpecificSpriteSequenceLoader.CreateSequence (OpenRA.ModData modData, OpenRA.TileSet tileSet, OpenRA.Graphics.SpriteCache cache, System.String sequence, System.String animation, OpenRA.MiniYaml info) [0x00000] in <filename unknown>:0 
  at OpenRA.Mods.Common.Graphics.DefaultSpriteSequenceLoader.ParseSequences (OpenRA.ModData modData, OpenRA.TileSet tileSet, OpenRA.Graphics.SpriteCache cache, OpenRA.MiniYamlNode node) [0x00000] in <filename unknown>:0 
  at OpenRA.Graphics.SequenceCache+<Load>c__AnonStorey1.<>m__0 () [0x00000] in <filename unknown>:0 
  at System.Lazy`1[OpenRA.IReadOnlyDictionary`2[System.String,OpenRA.Graphics.ISpriteSequence]].InitValue () [0x00000] in <filename unknown>:0 
```

**Comment by Mailaender** [comment] 2015-04-12 19:12
You need to get the latest version of that map from http://resource.openra.net/maps/2786/

**Comment by Mailaender** [comment] 2015-04-12 19:14
> `mono OpenRA.Utility.exe ra --map-hash /home/user/.openra/maps/`

You will need to do this with every .oramap file not the map path.

**Comment by fastslack** [comment] 2015-04-12 20:01
A small script to get maps hashes:
```
#!/bin/bash

for f in *.oramap
do
  printf "\nThe hash for $f is: "
	mono /usr/lib/openra/OpenRA.Utility.exe ra --map-hash $f
done
```
I'm using the latest _time-trouble.oramap_ map.

**Comment by Mailaender** [comment] 2015-04-12 20:14
Report to the author that his map is broken.

**Comment by pchote** [comment] 2015-04-12 20:20
A bad map shouldn't be able to take down the game.  We have checks in place to catch rule errors, but apparently not for sequences.

**Comment by penev92** [comment] 2015-04-12 23:31
Did anyone notice that the last posted exception is completely different to the original one?
First is a `KeyNotFoundException` about factions, second is `InvalidOperationException` about crate SHP frames.

**Comment by fastslack** [comment] 2015-04-13 01:12
Its another map, the first one is a map that i cannot see the name because its not representated by the hash in any other map installed on my system.

The second is another error that i got using other map.

**Comment by brightshine** [comment] 2015-04-15 14:29
Hi, I also encounter this bug, but in Windows.
Exception.log and settings.yaml listed below.

Red Alert Mod at Version playtest-20150408
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.Collections.Generic.KeyNotFoundException`: 指定的索引鍵不在字典中。
   於 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   於 OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.SetupEditableFactionWidget(Widget parent, Slot s, Client c, OrderManager orderManager, Dictionary`2 countries)
   於 OpenRA.Mods.Common.Widgets.Logic.LobbyLogic.UpdatePlayerList()
   於 System.Action.Invoke()
   於 OpenRA.Game.SyncLobbyInfo()
   於 OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
   於 OpenRA.Network.OrderManager.TickImmediate()
   於 OpenRA.Sync.<>c__DisplayClass5.<CheckSyncUnchanged>b__4()
   於 OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   於 OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   於 OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   於 OpenRA.Game.LogicTick()
   於 OpenRA.Game.Loop()
   於 OpenRA.Game.Run()
   於 OpenRA.Program.Run(String[] args)
   於 OpenRA.Program.Main(String[] args)

My settings.yaml : 
Player:
	Name: Bright
	Color: 247,236,127

Game:
	Mod: ra
	PreviousMod: cnc
	ViewportEdgeScrollStep: 43.04348
	UIScrollSpeed: 75.46522
	NewsFetchedDate: 2015-04-16 08-00-00

Sound:

Graphics:
	WindowedSize: 1920,1080
	HardwareCursors: False

Server:
	AllowPortForward: False
	Map: 2caee56595c29bba263ba7de1b9fee8c688bf56e

Debug:

Keys:

**Comment by penev92** [comment] 2015-04-17 09:29
Three people so far that I can count, and nobody can say what map did this :/

**Comment by MajorTom6** [comment] 2015-04-17 12:34
I've got this issue from joining servers hosting quite a few different maps, so it may not be whatever is currently picked in the lobby.

**Comment by brightshine** [comment] 2015-04-17 14:11
Hi penev92, do you have any procedure to determine which map triggers this bug?
It will crash after clicking 'skirmish' button, so I can't know which map did it .

**Comment by obrakmann** [comment] 2015-04-17 16:39
I can reproduce at least some of these crashes with our shipped minigames.

**Comment by penev92** [comment] 2015-04-17 17:08
OK, I managed to reproduce this using the map Bomber John.
The problem is that some maps force a certain faction some for the players:
>	PlayerReference@Multi0:
		Name: Multi0
		Playable: True
		AllowBots: False
		LockRace: True
		Race: soviet

The game lobby needs to show info (faction description, faction flag, actual faction name, etc.) for every faction in the game.
But "soviet" and "allies" are no longer playable, and the game lobby only has the factions that are marked as `Selectable: True`, so it doesn't have any information for these two.
Hence the crash.

**Closed** 2015-04-17 19:37 UTC
Labels: Crash, Red Alert
