### ISSUE TITLE
Naval Structure Overlaps Bridge Repair

### ISSUE THREAD

**Issue by TheGrinningSkull** [OpenRA/OpenRA#13843] opened 2017-08-13 14:21 UTC
Building navy structures in the middle of a destroyed bridge results in an overlap of structure on top of when bridge gets repaired.

The navy structure blocks unit pathing across the bridge and is still able to produce naval units.
![openra-2017-08-13t130503085z](https://user-images.githubusercontent.com/30012195/29250481-fca33cc0-803a-11e7-93dc-dd908ad4b585.png)
![openra-2017-08-13t130524372z](https://user-images.githubusercontent.com/30012195/29250485-fcc82e5e-803a-11e7-9439-1e6c9363015e.png)
![openra-2017-08-13t130555936z](https://user-images.githubusercontent.com/30012195/29250487-fcc928f4-803a-11e7-8c58-1a0d2fc29437.png)
![openra-2017-08-13t130559246z](https://user-images.githubusercontent.com/30012195/29250486-fcc84cea-803a-11e7-99d4-67f0b35beffe.png)
![openra-2017-08-13t130615037z](https://user-images.githubusercontent.com/30012195/29250484-fcc8010e-803a-11e7-93f4-3ea1cd847714.png)
![openra-2017-08-13t130627424z](https://user-images.githubusercontent.com/30012195/29250483-fcc2b046-803a-11e7-927a-c4b7ebed6843.png)
![openra-2017-08-13t130629167z](https://user-images.githubusercontent.com/30012195/29250482-fcbce76a-803a-11e7-8f62-8419c0655af1.png)

**Comment by FrameLimiter** [comment] 2017-08-13 14:26
Duplicate of #9416

**Comment by abcdefg30** [comment] 2017-08-13 14:36
Yep, indeed a duplicate. Thanks for the detailed report though. :)

**Closed** 2017-08-13 14:36 UTC
