### ISSUE TITLE
Dune2000 Crash

### ISSUE THREAD

**Issue by hanakocz** [OpenRA/OpenRA#11251] opened 2016-05-10 18:08 UTC
> Podpis problému:
>   Název události problému:	CLR20r3
>   Podpis problému 01:	OpenRA.Game.exe
>   Podpis problému 02:	0.0.0.0
>   Podpis problému 03:	0
>   Podpis problému 04:	OpenRA.Game
>   Podpis problému 05:	0.0.0.0
>   Podpis problému 06:	0
>   Podpis problému 07:	8
>   Podpis problému 08:	0
>   Podpis problému 09:	System.StackOverflowException
>   Verze operačního systému:	6.3.9600.2.0.0.768.101
>   ID národního prostředí:	1029
>   Další informace 1:	199c
>   Další informace 2:	199cc907df8a4654c8ebf31545ec3b64
>   Další informace 3:	ac93
>   Další informace 4:	ac932fb721b478be6e53cf5b63cba0e7

I read FAQ and located my log folder, but there is no exceptions.log nor anything similar. The error above was the only thing that Windows gave me when wanted to close the errored app. I just played Singleplayer Skirmish for like ~15 minutes. I downloaded the game just today, so I bet I have actual version.

If you need any additional info, ask me what you need.

**Comment by chrisforbes** [comment] 2016-05-23 04:47
Details of what you were doing at the time, or ideally steps to reproduce it, would help.

**Comment by hanakocz** [comment] 2016-05-23 07:20
As I said, I played skirmish, it was early start of the game, was playing against one computer. There were first clashes with enemy, but was not doing anything in particular. Just normally playing ( building, cmmanding units, and so) and I'm sorry that I cannot point to any particular action...Ya,it probaly cannot help much, except codes of the error, but....well, even adding something that could catch the error next time can be good :)

**Comment by abcdefg30** [comment] 2016-05-23 10:50
See also #11345.

**Comment by Mailaender** [comment] 2016-07-10 14:01
Closing as duplicate of https://github.com/OpenRA/OpenRA/issues/11310 as that comes with an English stacktrace.

**Closed by Mailaender** 2016-07-10 14:01 UTC
Labels: Crash, OS: Windows
