### ISSUE TITLE
Harvesters in TS don't switch back to regular graphics if refinery is killed during unload

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#18733] opened 2020-10-17 15:42 UTC
Seem to get stuck, too.
Observed in an AI-only game.

**Comment by pchote** [comment] 2020-10-17 15:43
Possibly related to or duplicate of #18422?

**Comment by reaperrr** [comment] 2020-10-17 15:59
Very much possible.

**Closed as completed** 2020-11-15 15:56 UTC
Labels: Bug, Tiberian Sun
