### ISSUE TITLE
OpenRA 2015919 crashing 

### ISSUE THREAD

**Issue by CreepyOwl** [OpenRA/OpenRA#9401] opened 2015-09-21 16:04 UTC
Exception.log
```
Red Alert Mod at Version release-20150919
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34014
Exception of type `System.ArgumentException`: sounds.mix (RA/TS/RA2 format, Encrypted: True, DataStart: 94932), duplicate values found for the following keys: 693256111: [(offs=4081033222, len=1309399711),(offs=3532496902, len=1980120954)], 2877828482: [(offs=908731656, len=2191301893),(offs=1886659848, len=1313679266)], 278278454: [(offs=1906858133, len=3977486992),(offs=2697287829, len=717990464)]
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, String debugName, Func`2 logKey, Func`2 logValue)
   at OpenRA.FileSystem.MixFile..ctor(String filename, PackageHashType type, Int32 priority)
   at OpenRA.FileSystem.GlobalFileSystem.OpenPackage(String filename, String annotation, Int32 order)
   at OpenRA.FileSystem.GlobalFileSystem.<Mount>c__AnonStorey0.<>m__0()
   at OpenRA.FileSystem.GlobalFileSystem.Mount(String name, String annotation)
   at OpenRA.FileSystem.GlobalFileSystem.LoadFromManifest(Manifest manifest)
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.Widgets.Logic.IngameMenuLogic.<IngameMenuLogic>c__AnonStorey0.<>m__16()
   at System.Action.Invoke()
   at OpenRA.Primitives.ActionQueue.PerformActions()
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

```

**Comment by clemty** [comment] 2015-09-21 16:19
Looks related to #9347

**Comment by RoosterDragon** [comment] 2015-09-21 17:00
Closing as a duplicate of #2441.

**Closed by RoosterDragon** 2015-09-21 17:00 UTC
