### ISSUE TITLE
Clicking in the minimap should take you to where you click but it does nothing

### ISSUE THREAD

**Issue by yetisyny** [OpenRA/OpenRA#14877] opened 2018-03-04 06:39 UTC
### Issue Summary

If you click somewhere in the minimap in the upper right corner it should take you there, to where you click. But instead it does nothing. This happens in the mode of the game where you are having a skirmish between different AIs and you are an observer, where it is super-obvious since that is the only thing clicking on the minimap ought to do in that mode. It ALSO happens in regular games too when you are a player but not an observer but in regular games since if you have units selected you can use the minimap to send them somewhere, you have to do this without any units selected.

#### System Information
- **Operating System:** macOS 10.12 Sierra
- **.NET / Mono Version:** Mono 5.8.0
- **OpenRA Version:** release-20180218
- **Mod:** Tiberian Dawn (applies to other mods too)

#### Additional Information:
- Steps to reproduce
	1. Click on a spot in the minimap in the upper right corner (while NOT having any units you control selected).
	2. Nothing happens! You don’t get taken to the place you clicked on.

**Comment by GraionDilach** [comment] 2018-03-04 08:42
Is this with left-click orders or right-click orders? Even LCO uses the right button to jump on the minimap IIRC.

**Comment by yetisyny** [comment] 2018-03-07 16:39
On a Mac there is only one mouse button. So left vs. right click does not exist on Macs.

**Comment by pchote** [comment] 2018-03-07 16:48
Pretty much all macs released in the last 10-15 years are capable of distinguishing between left and right click.  Even with the first party mice and trackpads, click type is distinguished based on finger position or number of fingers used.

**Comment by yetisyny** [comment] 2018-03-07 18:12
Oh I figured out how to get it to work, I have to tap with 2 fingers instead of one, then it can jump to a location on a Mac when clicking on the minimap. But still I have the settings to do things with one mouse button, for instance “Left-click Orders” is on in the Input settings. Usually in most programs I can control-click to get a right click and cmd-click to get a middle click but in OpenRA the control-click modifier has different results (attack cursor) and cmd-click doesn’t seem to make any difference, cmd only exists on Macs, it is in addition to shift, control, and alt/option, cmd is kinda the equivalent of the Windows key on a PC keyboard except it is used with the touchpad to be like a middle-click.

Anyway I figured out I have to tap with 2 fingers at once (equivalent to a right click) for this to work. Still I would like it to work with one finger (equivalent to left click) on a Mac since that is much easier, at least if the “Left-click Orders” option under Input is enabled that ought to change this. Thanks.

**Comment by yetisyny** [comment] 2018-03-07 18:34
Oh wait, the tapping with 2 fingers things works if you are an active player but not in Observer mode if you are an observer. If you are in Observer mode watching AIs fight, nothing seems to work for clicking on the minimap to move to another part of the main map.

**Comment by reaperrr** [comment] 2018-05-30 19:18
So, I guess this can be closed?

**Comment by matjaeck** [comment] 2018-08-13 18:06
> So, I guess this can be closed?

IMO yes.

**Comment by abcdefg30** [comment] 2018-08-14 20:18
> Anyway I figured out I have to tap with 2 fingers at once (equivalent to a right click) for this to work. Still I would like it to work with one finger (equivalent to left click) on a Mac since that is much easier, at least if the “Left-click Orders” option under Input is enabled that ought to change this. Thanks.

I interpret this as saying that using a left click on the minimap doesn't work when left click orders are enabled, similar to how right clicking on the minimap has no effect with right click orders. The question is whether we want to 'fix' this behaviour.

**Comment by matjaeck** [comment] 2018-11-25 15:52
> The question is whether we want to 'fix' this behaviour.

https://github.com/OpenRA/OpenRA/issues/11263#issuecomment-218663798 sounds like a plan.

**Comment by gardolf** [comment] 2018-12-05 16:43
I believe this can be closed.

Release 20180923

**Comment by pchote** [comment] 2018-12-05 18:34
Closing as duplicate of #11263.

**Closed by pchote** 2018-12-05 18:34 UTC
Labels: Bug
