### ISSUE TITLE
Shroud broken buildings under the shroud get attacked 

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#21200] opened 2023-11-10 00:31 UTC
Shroud broken, defences under the shroud get attacked when scouted before. Gapgenerators can get attacked without scouting by ctrl+ A-move. Long range weapons like Artys attack everything under the shroud when scouted before.

**Comment by PunkPun** [comment] 2023-11-10 07:11
Duplicate of #20946

**Closed as not planned** 2023-11-12 10:47 UTC
Labels: Bug
