### ISSUE TITLE
deploy glitch

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#9902] opened 2015-11-06 03:08 UTC
![some](https://cloud.githubusercontent.com/assets/9139965/10988272/3c938914-843b-11e5-958e-41a14e4e1f51.png)

1. select mcv
2. rightclick on a cell near a cliff (or whatever)
3. while the mcv is moving to this position ... shift-rightclick on the mcv and wait for it to deploy

![some2](https://cloud.githubusercontent.com/assets/9139965/10988539/6d0901a8-843d-11e5-90d5-4fd06842844a.png)

**Comment by GraionDilach** [comment] 2015-11-06 08:48
Duplicate of #6683?

**Comment by reaperrr** [comment] 2015-11-06 11:09
I think so, the underlying problem seems to be that not the cells at the target destination, but rather the cells around the moving actor's current position are checked when issuing the deploy command.

**Comment by GraionDilach** [comment] 2015-11-06 11:15
Moreso https://github.com/OpenRA/OpenRA/issues/6683#issuecomment-58641783

**Comment by MicroJOo** [comment] 2015-11-06 15:04
@pchote : you should add this back to the release-milestone cause people started using this "ingame" ... and it got popular in the last couple of days ...

**Comment by epicelite** [comment] 2015-11-06 17:58
Yeah thanks for telling everyone.

**Comment by MicroJOo** [comment] 2015-11-06 18:06
@epicelite : for you that makes no difference ... they beat you anyway

**Closed** 2015-11-14 15:41 UTC
Labels: Bug
